### ISSUE TITLE
[Enhancement] C/C++ style pointer dereferencing for member access.

### ISSUE THREAD

**Issue by Scripptor** [beefytech/Beef#1006]
Please implement a second way of dereferencing pointers specifically for member access.
Current method:
`(*ptr).Foobar();`

Suggested alternative:
`ptr->Foobar();`

**Comment by bfiete** [comment]
Pointers to structs, struct values, and class reference value are all accessed via `ptr.Foobar()`.

If you need `(*ptr).Foobar()` then you may have a pointer to a reference value, which is essentially a double pointer. If so, that may be accidental on your part and it's possible you may not yet understand the difference between a valuetype and a reference type (Google it for C# if so).

**Comment by Scripptor** [comment]
No, it's intentional.. I've for the most part implemented a LinkedList class, and it makes use of a double pointer.. Stored data is wrapped and with a LinkedItem class. 

Thanks for the help and advice, I will look that up. 

I noticed this type crashes the IDE:
`(ptr).Foobar()`

Alright, the "->" should denote dereferencing of a double pointer.. Perhaps have it as optional even?
I just think being able to drop the parenthesis is more concise and readable..

**Comment by bfiete** [comment]
Well, double pointers are supposed generally pretty rare.
Even in C++ you'd have to do a `(*ptr)->Foobar()` or `(**ptr).Foobar()` for a double pointer...

I think using `->` for a double pointer in Beef would be confusing because it would look like the standard way to do a single-pointer dereference in C.

**Comment by Scripptor** [comment]
Yeah, I've been looking up the difference between a valuetype and a reference type and, it's certainly helped. I'm still reading into it. But anyway I'm closing this issue..
