### ISSUE TITLE
SDL2_ttf.bf RenderText_Solid, typo in binding

### ISSUE THREAD

**Issue by Scripptor** [beefytech/Beef#1007]
In SDL2_ttf.bf  at line 190 TTF_RenderText_Solid gets imported, however there is a typo in the binding!

```
[LinkName("TTF_RenderText_Solid")]
public static extern SDL.Surface* RenderText_Solid(
	Font* font,
	char8 text, // <--- here, this needs to be a pointer
	SDL.Color fg
);
```

Fixed version:
```
[LinkName("TTF_RenderText_Solid")]
public static extern SDL.Surface* RenderText_Solid(
	Font* font,
	char8* text, // fixed
	SDL.Color fg
);
```

**Comment by bfiete** [comment]
This was already fixed here https://github.com/beefytech/Beef/commit/dfdfe094cd57a51e24f7df7c862808d707deb2df#diff-95dd80c0f6dd3577200f445cfa230863b4b0dc6018a1b61678a55c7162571cbd

It's fixed in the nightly builds but the fix didn't make it into the last official release.
