### ISSUE TITLE
codegen crash with const type

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1011]
Compiling this crashes the compiler at BfCodeGenThread::RunLoop() when hashing Beefy::BeCallInst::HashInst. arg.mValue is null at BeModule.h:1345.

```
using System;
using System.Collections;

namespace BfTest
{
	class Program
	{
		static List<Type> ts = new .();

		static void Main()
		{
			const Type t = typeof(Program);
			ts.Contains(t);
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed at 41f7fd57e600a595ff092e07c42f6c585a6c379d
