### ISSUE TITLE
[Request] Add CallerClass to System.Compiler

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#1021]
Is it possible to add something that will just return name of a class that called some method?
Right now there is only Compiler.ModuleName which returns whole namespace + class.

**Comment by M0n7y5** [comment]
Also CallingMethod would be nice :)

**Comment by bfiete** [comment]
Added at 045e706600d3ab9be3aff15772a9fd9998e7cfb6
`CallerType`, `CallerTypeName`, `CallerMemberName`
