### ISSUE TITLE
Calling Directory.EnumerateFiles caused an attempt to a deleted obejct

### ISSUE THREAD

**Issue by andreakarasho** [beefytech/Beef#1025]
![image](https://user-images.githubusercontent.com/20810422/120087294-e14f1700-c0e6-11eb-8d2a-309fdc6cb939.png)

```c
var files = Directory.EnumerateFiles("./");
for (var f in files)
{
}
// here crashes
```

something deletes the internal string [allocated in the heap]

**Comment by EinBurgbauer** [comment]
The repro code works fine for me. The String that is deleted there is created by Enumarate() for that purpose.

**Comment by andreakarasho** [comment]
> The repro code works fine for me. The String that is deleted there is created by Enumarate() for that purpose.

I analyzed my code and i found that i've a `break` into the loop. This `break` trigger the issue. Try this snippet:
```
var files = System.IO.Directory.EnumerateFiles("./");
for (var f in files)
{
    break;
}
```
The `Dispose` method is called twice
