### ISSUE TITLE
macOS - BeefBuild fails clang: error: unsupported option '-static-libgcc'

### ISSUE THREAD

**Issue by andreakarasho** [beefytech/Beef#1028]
the error happens when compiling a beefproject

**Comment by bfiete** [comment]
I don't have a mac to test on at the moment but I committed a potential fix at https://github.com/beefytech/Beef/commit/6962343e23d0f0a0d73a3f66243a0371dbeab717

**Comment by andreakarasho** [comment]
I’ll let you know in 1h ~

**Comment by andreakarasho** [comment]
The error is gone, but i get this warn:
`clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]`
