### ISSUE TITLE
[BUG] Bad popup window text rendering

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#1029]
![image](https://user-images.githubusercontent.com/17201053/120367493-37070780-c311-11eb-8039-777e2d72f89c.png)

Image is self explanatory

**Comment by wilsonk** [comment]
Seems like this has been fixed now, yes? I can't seem to get it to happen anyways. Even against the edge of my screen it seems to handle things fine now.

Perhaps this can be closed?
