### ISSUE TITLE
[Crash] inline attribute causes crash on compile

### ISSUE THREAD

**Issue by MoshiBar** [beefytech/Beef#1035]
Nightly(06/06/2021)
```
static float value => Math.[Inline]Sqrt(0);

public static void Main()
{
	Console.WriteLine(value);
}
```

attempting to compile this code will result in a crash

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/e6fdfa39d0a287caa1f5c2b9a7f72fafd9dc6a32
