### ISSUE TITLE
Can Beef make desktop GUI application?

### ISSUE THREAD

**Issue by RealAquilus** [beefytech/Beef#1036]
Hi! I have been messing around with beef and damn i really like this software! i have some questions, the first one as the title say, can i make some GUI with Beef? Even if with imgui or similar, just something that makes me build some GUI stuff.
The second one is, is Beef complitely stand-alone? Because when i press compile i see that it calls my Visual Studio folder.
Thanks and keep going with the project!! A native C# like language that doesn't require .net is just too good to be true, even more if this become cross-platform one day!

**Comment by RogueMacro** [comment]
For gui there are several libraries. I suggest checking out https://github.com/Jonathan-Racaud/awesome-beef for more libraries. ImGui you can find here: https://github.com/RogueMacro/imgui-beef. As for compiling, yes you would need visual studio build tools, but, if you change Workspace > Toolset to LLVM, and each project's c library to Static MSVCRT I think you can get around that. It has worked in the past for me.
