### ISSUE TITLE
[Enhancement] Attributes on extensions

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#1037]
Currently, adding an attribute to an extension doesn't work, but like with adding interfaces with extensions it may feel like this should be possible. Even if this is not implemented, it would be nice to see a warning saying that attributes are of no use on extensions.

Example of how it could have looked like:
```bf
class BaseClass
{
    public int MyInt;
}

[Reflect]
extension BaseClass
{
    public int AnotherInt;
}

class Program
{
    public static int Main(String[] args)
    {
        for (let field in typeof(BaseClass).GetFields())
        {
            Console.WriteLine(field.Name);
        }

        Console.Read();
        return 0;
    }
}
```

**Comment by bfiete** [comment]
Fixed at 361be9dc92103be9b16b3b81b429cc477f735af6
