### ISSUE TITLE
[Bug] Issue with reflections and CustomAttributes

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#1038]
I am not actually sure, what causes this Problem, but when trying to get a custom attribute on a type it doesnt seem to work.
![unknown](https://user-images.githubusercontent.com/59422062/122291207-d8d34a80-cef4-11eb-9e2c-de73177f731d.png)

The Auto tab has a -1 for the CustomAttributesIdex and I think that means that it doesnt recognize it.
Im not sure what exactly causes it, however it seems reproduceable on newer versions of the nightly.

[beef-debug-console.zip](https://github.com/beefytech/Beef/files/6665778/beef-debug-console.zip)

**Comment by RogueMacro** [comment]
It is most probably because you forgot to set ReflectAttribute as a flag. Like this:
```bf
[AttributeUsage(.Types, .ReflectAttribute)]
public struct SomeAttribute : Attribute {}
```

**Comment by Booklordofthedings** [comment]
yea that was it, also agree
