### ISSUE TITLE
[Bug] const float in function scope displays as 0 in debugger

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1039]
Given the following test code:
```beef
const int32 iConstA = 1;
const float fConstA = 1.0f;
void Testy()
{
	const int32 iConstB = 1;
	const float fConstB = 1.0f;
				
	int32 iResult = iConstA + iConstB;
	float fResult = fConstA + fConstB;
				
	System.Runtime.Assert(iResult == 2);
	System.Runtime.Assert(fResult == 2.0f);
}
```

The values of `const int32` variables `iConstA` and `iConstB` display as 1 in the debugger, and `iResult` is the expected value.
This value of `const float` variable `fConstA` displays correctly in the debugger, but `fConstB` displays as 0. However, `fResult` still ends up with the expected value of 2.0f.

Screenshot:

![image](https://user-images.githubusercontent.com/775593/122454166-f12c7f00-cf5f-11eb-9e0c-c53cbeb7c0ae.png)

**Comment by bfiete** [comment]
One-character fix at 90f34b6bee177bc4d1b8a59aca631e045e9e4ade
Thanks, C++, for not even warning on comparing two completely different enum types.
