### ISSUE TITLE
[BUG] Unable to use Reflected Construction 

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#1040]
I am unable to create objects from reflected typeinfo... CreateObject from TypeInstance fails.
Also provided example code from docs doesnt work ether:
https://www.beeflang.org/docs/language-guide/reflection/#reflected-construction

**Comment by RogueMacro** [comment]
Can you include an example of what you're doing?

**Comment by M0n7y5** [comment]
Looks like it just outdated docs ...

**Comment by bfiete** [comment]
Fixed with 9154511e7898dfe92d9c91e11faeebecf3943b89 and 545323fb51138d9087c3b86b0a0586f742c6d95c

**Comment by EinBurgbauer** [comment]
those docs are now fixed (at least the version in the repo)
