### ISSUE TITLE
[BUG] Auto formating is deleting parameters attributes

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#1041]
![EdeIddAzuH](https://user-images.githubusercontent.com/17201053/122510409-d4e31d80-d005-11eb-8421-f7473c2b3dbe.gif)

When i press keystroke for formatting document, parameter attributes gets deleted.

**Comment by bfiete** [comment]
Fixed at e6fdfa39d0a287caa1f5c2b9a7f72fafd9dc6a32
