### ISSUE TITLE
Assert failed "inst->mArg0.IsVReg()"

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1044]
The assert failure mentioned in the issue title can be easily reproducible if you try to compile a Test project with BeefIDE_d that contains the following code:
```
using System;
using System.IO;

namespace BeefBugRepros
{
	static
	{
		private static int a1;
		private static int a2 => (Environment.TickCount % 2) == 0 ? 1 : 3;

		[Test]
		public static void TestBug()
		{
			a1 = (a1 + 1) % a2;
		}
	}
}
```
Tested with e6fdfa3

**Comment by bfiete** [comment]
Fixed at 80007037d793f627cdebb2dcafbbcbd229955ef9
