### ISSUE TITLE
Implicit cast of same delegate/function pointers

### ISSUE THREAD

**Issue by HydrogenC** [beefytech/Beef#105]
`delegate void(int64 idx)` and `delegate void(int64 item)` are basically the same, but the IDE tells me that "Unable to implicitly cast 'delegate void(int64 idx)' to 'delegate void(int64 item)' ".

**Comment by bfiete** [comment]
Delegate/function casting has been worked a bit - the parameter matching rules are similar to tuples now. Parameter names are no longer required, so "delegate void(int64)" is valid. When implicitly between delegate types, if one type's parameter has a specified name but the other doesn't then it is considered a valid match. If the both delegate types specify a parameter name then an explicit cast is required. Explicit casts will only succeed if the delegates are call-equivalent (same calling convention, return type, parameter types).

Will be in 0.42.2.

**Comment by HydrogenC** [comment]
Glad to hear that!
