### ISSUE TITLE
Assert failed "phiValue->GetType() == value->GetType()"

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1053]
The assert failure mentioned in the issue title can be easily reproducible if you try to compile a Test project with BeefIDE_d that contains the following code:
```
using System;
using System.IO;
using System.Collections;

namespace BeefBugRepros
{
	static
	{
		[Test]
		public static void TestBug()
		{
			uint8[] data = null;
			Console.WriteLine(data ?? Span<uint8>());
		}
	}
}
```
Tested with e6fdfa3

**Comment by bfiete** [comment]
Fixed at 4189d10f412109b56b643da336b6890028e4c57a
