### ISSUE TITLE
File is erased if you try to save when the disk is full

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1058]
If you try to save a file when the disk is full, an assert failure occurs, this causes the save to only erase the contents of the file and if there is no recovery file, your file is gone.

**Comment by disarray2077** [comment]
I found where the assert failure (`Unhandled error in result`) happens, it's in this line: https://github.com/beefytech/Beef/blob/e5f92fb21b327b8d5c89da4a413d509a5169db20/BeefLibs/corlib/src/IO/BufferedStream.bf#L154
I would do a PR to fix it, but I'm not sure what to do, this isn't an error that should be ignored but the current code seems to want to ignore all errors, and I have no idea why it was written like this.

**Comment by bfiete** [comment]
Just an oversight. An `else return .Err;` would work there.

**Comment by disarray2077** [comment]
This ended up being more complicated than I expected, but the pull request that I did seems to solve the problems related with this issue 👍
