### ISSUE TITLE
"repeat...while" breaks IDE indentation if not terminated with semicolon

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1061]
The issue title says it all, but here is an image to make it clearer.
![image](https://user-images.githubusercontent.com/86157825/122648855-684d4900-d101-11eb-9177-dd848d37d7ab.png)
_(PS: No syntax error shows, so I guess this is valid code)_

**Comment by bfiete** [comment]
The real bug here is what repeat/while loops should require semicolon termination...

**Comment by bfiete** [comment]
Fixed at a888fd745adeabb7171aa06c73a509c090833c9c
