### ISSUE TITLE
LLVM doesn't compile with CMake versions older than 3.15

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1063]
I didn't find about this in [Beef's documentation](https://www.beeflang.org/docs/getting-start/building/) and there was no warnings or errors, but after failing to compile Beef because of unrecognized parameters, I noticed that Beef's compile script uses a feature that is [only supported in CMake version 3.15 and above](https://stackoverflow.com/a/56490428).
I suggest that this should be added to the documentation to save the others people time :-)

**Comment by bfiete** [comment]
The website is hosted at https://github.com/beefytech/Beef_website
If you are feeling ambitious, feel free to submit PRs there (as well as here)!

**Comment by disarray2077** [comment]
Thanks for the directions, I will create a PR there (and here as well, whenever possible) :+1:
