### ISSUE TITLE
Parse failure while binding a generic function

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1066]
Looks like the Beef parser fails to correctly parse the following code:
```
CallTest(=> Test<List<int>>);
```

One (ugly) way around this is doing the following:
```
const Type workaround = typeof(List<int>);
CallTest(=> Test<comptype(workaround)>);
```

**Comment by bfiete** [comment]
Fixed at 34c444767dea1a8c75fd1dcaf9ff2e17e9c1a547
