### ISSUE TITLE
Properties doesn't support auto-destructor syntax

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1068]
I guess this is more a feature request than a bug, but currently the following code doesn't work, and I think it really should as it's really annoying to have to create a destructor only for properties (or expose the backing field)

Example:
```
public static ref Event<Action> MyPrettyEvent { get; set; } ~ _.Dispose();
```

**Comment by bfiete** [comment]
Added at f831d75de2c525a9b8d6f683d1621ea9fab71ddd
