### ISSUE TITLE
Why an IDE though?

### ISSUE THREAD

**Issue by sukhchainn** [beefytech/Beef#107]
You spent so much time writing an IDE, but why did you spent so much time in writing an IDE when you could have written a VS Code extension or plugins for other editors, why?

**Comment by bfiete** [comment]
The point of the BeefLang project is not just to create a programming language, it is to create a great development environment. The programming language, IDE, libraries, and other tools are all part of that and I believed they should be created in unison. I did not believe that creating an extension or plugin for an editor would give enough control over the development experience, particularly in the areas of debugging and code awareness.

**Comment by ChlorineX** [comment]
VS Code is not as integrated as an IDE and is not good at project management, so a individual IDE like VS is required for large project. Besides, I think that having a IDE written in Beef itself also can prove that Beef can indeed create something useful and is not a toy.

**Comment by sukhchainn** [comment]
Oh, I see.
But creating entire libraries from ground up will be a very long and painful process.
I think porting C libraries in beef would be quicker and writing a wrapper generator will make beef even more fun working with.

**Comment by ChlorineX** [comment]
It won't be too difficult, I think that we could try to create a wrapper generator by ourselves.

**Comment by sukhchainn** [comment]
For that to happen we need to learn in and out of beef language and we also have to learn about AST parsing, specializer and generators. Which seems like a lot of work right now when I don't have much experience with writing programs in beef. I think I'll fiddle around a bit with a language before making a generator in that language.

**Comment by bfiete** [comment]
My approach would be to adapt the SWIG C# support to BeefLang - which would mostly be removing outputted interop code since BeefLang semantics are much more similar to C than C#'s semantics.

**Comment by Heromyth** [comment]
> 
> 
> VS Code is not as integrated as an IDE and is not good at project management, so a individual IDE like VS is required for large project. Besides, I think that having a IDE written in Beef itself also can prove that Beef can indeed create something useful and is not a toy.

There is another thing.  A good lang needs a good IDE. There is a long way for Beef IDE before be a good IDE. VS Code is well for so many languages. Maybe we can do somthing like C# in VS Code.
