### ISSUE TITLE
Many methods don't have a name in Reflection within a ConstEval context

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1072]
_Tested with the type `System.Console` using the default `GetMethods()`_

On a side note, I managed to get the name calling directly `Type.Comptime_Method_GetName` but others things went wrong, like calling 
```
methodInfo.ReturnType.GetFullName(.. scope .());
```
results in a FatalError, so I gave up trying to workaround this issue =P

**Comment by RogueMacro** [comment]
You have to request reflected info if you want it at runtime. Normally, you would add a `[Reflect(.Methods)]` attribute to the type, but you can't do that in corlib or other libraries that are locked or you don't want to change. In that case you can go to your Project Properties > General > Beef > Distinct Build Options. Type in `System.Console` then under Reflect you choose what to reflect, i.e. `Non-Static Methods`.

**Comment by disarray2077** [comment]
@RogueMacro This is true only at runtime, but as I said in the issue title, this issue is related to compile-time.
e.g.
```
[Comptime(ConstEval=true)
public static void ListMethods<T>()
{
     // ... code here ...
}
```
From what I saw, the Reflect attribute shouldn't be necessary to do Reflection during compile-time.

**Comment by bfiete** [comment]
I tried reproducing this, and it looks like this got fixed somewhere already.

**Comment by disarray2077** [comment]
Looks like some issues were fixed but others are still happening, but I'm not sure anymore about what really is happening, seems to be an issue related with `String.AppendF`... I will create another issue
