### ISSUE TITLE
[Inline] at callsite throws "unused attribute warning"

### ISSUE THREAD

**Issue by EinBurgbauer** [beefytech/Beef#1073]
I saw this in the docs, tried it, and concluded it didn't work. So now i tried it again and it turns out it does properly inline, but confusingly still tells you that the attribute is unused.

c.[Inline]Clear();

**Comment by bfiete** [comment]
I'm not seeing this issue. Can you post a more complete example that shows the problem?

**Comment by EinBurgbauer** [comment]
I rebuilt to make sure i was not missing anything and it turns out i totally was. Turns out i didn't have the newest commits, sorry about that.
