### ISSUE TITLE
initializers being skipped with = '.{}' initializer expression

### ISSUE THREAD

**Issue by EinBurgbauer** [beefytech/Beef#1074]
```
struct RunConfig
{
	public uint32 windowWidth = 1280;
	public uint32 windowHeight;
	
	this
	{
		windowHeight = 720;
	}
}
```

i noticed that with .(){} 1280 and 720 are set, while with .{} the fields are 0. This is relatively new, but i'd say this is probably not intentional. The initializer expression doesnt have to be empty for this to happen

**Comment by bfiete** [comment]
This was intentional.
```C#
RunConfig rc = .(){windowHeight=123};
```
is equivalent to
```C#
RunConfig rc = .();
rc.windowHeight = 123;
```

whereas

```C#
RunConfig rc = .{windowHeight=123};
```
is equivalent to
```C#
RunConfig rc = default;
rc.windowHeight = 123;
```

I guess that didn't make it into the docs yet :-)
