### ISSUE TITLE
Broken partial property & Wrong destructor highlight (?)

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1079]
The following code behaves exactly like a auto-property, ignoring the declared body, the same thing happens with `set`, but if both `get` and `set` have a declared body then the property works as expected. _(or in the following code, fails as expected)_
```
public static ref Event<Action> TestEvent
{
    // declared body is never called
    get
    {
        Runtime.FatalError();
    }
    set;
} ~ _.Dispose(); // Wrong highlight (_. shouldn't be green, I guess)
```

**Comment by bfiete** [comment]
Fixed at 78c39c5f8724731881e93d332ca0d5ac8320f5e3 and 91897f8cb31b9f0ef05727770d477f53b93030e9
