### ISSUE TITLE
Project/file locking doesn't handle correctly some key combinations

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1080]
- CTRL+C/CTRL+A (and maybe others combinations that don't modify anything)
 **Result**: Triggers the lock sound unnecessarily (but works as expected)

- CTRL+Z/CTRL+SHIFT+Z
 **Result**: Changes the content of the file if the file was modified before locking

**Comment by bfiete** [comment]
Fixed at f49c1957a0e1a797a9dc0e63f29552183b54fc1f and b743bd5dd819e079233d80625a00503c2bda02f0
