### ISSUE TITLE
Null coalescing operator doesn't work as expected

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1081]
In the following code the expected would be that the Span with length 4 would be the one that would be used as the parameter for `TestSpan`, but actually what happens is that Beef first casts the variable `data` to Span (which crashes because data is null, but this is a unrelated issue so let's ignore this for now) and as structs can never be null, beef just wrongly uses the casted Span instead.

```
using System;

namespace BeefBugRepros
{
    static
    {
        public static void TestSpan(Span<uint8> span)
        {
            Test.Assert(span.Length == 4);
        }

        [Test]
        public static void TestBug()
        {
            uint8[] data = null;
            TestSpan(data ?? Span<uint8>(scope uint8[] (2,0,7,7)));
        }
    }
}
```
Tested with 4189d10f412109b56b643da336b6890028e4c57a

**Comment by bfiete** [comment]
Fixed at 096dc0aaa33296076d4cb75a4daafaa0adc0b220
