### ISSUE TITLE
[BUG?] Unable to use Tests

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#1088]
For some reason i am getting this message  when i create project using Test template and using `'Test' menu` to launch tests.

```
ERROR: Test project 'BeefTest' has been selected as the Startup Project. Use the 'Test' menu to run or debug tests.
WARNING: No projects have a test configuration specified
```

![image](https://user-images.githubusercontent.com/17201053/124204904-53e55500-dae0-11eb-9a32-5a5a925ca157.png)

IDE ver **0.43.1 (Nightly 06/30/2021) built 6/30/2021**

**Comment by bfiete** [comment]
Fixed at a825b392ea02d1a45e5b31316cfe31cc1676baf2
Also you can work around it by selecting a non-test project (such as corlib) to be the startup project.
