### ISSUE TITLE
Expose FileStream's file handle

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1090]
One example where it's necessary is for the function [TransmitFile](https://docs.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-transmitfile), as it requires the handle of the file but it's currently not exposed by the FileStream class.

**Comment by bfiete** [comment]
You should probably just use `Windows.CreateFile` if you want low-level file handle support...

**Comment by bfiete** [comment]
Eh, probably adding the ability to get a system file handle is a good idea still, though.

**Comment by disarray2077** [comment]
> You should probably just use `Windows.CreateFile` if you want low-level file handle support...

I guess so, but this wouldn't take advantage of the already existing cross-platform code of Beef _(Unix platforms also has a similar function, [sendfile](https://man7.org/linux/man-pages/man2/sendfile.2.html))_

**Comment by bfiete** [comment]
Yeah, you're right-
Implemented at 961e71c62addb9ec016bb91e7c30822c457fa71d
