### ISSUE TITLE
[Bug] Switch cases shared with default are skipped entirely

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1095]
When using switch case, if a case is shared with default, it will be entirely skipped.

Repro code:
```beef
namespace Logic
{
	class EnumTest
	{
		public enum TestEnum : uint8
		{
			CASE_A,
			CASE_B
		}

		public TestEnum testEnum;

		public void Test()
		{
			int result = 0;

			testEnum = .CASE_A;
			switch (testEnum)
			{
			case .CASE_B:
				result = 2;
				break;

			case .CASE_A:
			default:
				result = 1;
				break;
			}
		}
	}
}
```

Repro steps:
1. Instantiate `EnumTest`
2. Call `instance.Test()`
3. Step through in Debug config

Expected: `result` is set to `1` in the switch

Actual: case is never executed, `result` is 0 at the end of the function

**Comment by bfiete** [comment]
https://www.beeflang.org/docs/language-guide/statements/#switch

Breaks are implicit. `fallthrough` must be specified to fall through.

**Comment by hunterbridges** [comment]
Oh I see... is there a way to stack cases without writing fallthrough on all of them?

**Comment by bfiete** [comment]
Yeah-
`case 'E', 'I', 'O', 'U':`

**Comment by hunterbridges** [comment]
Got it... so the way to stack with `default` is like so?
```
case 'E': fallthrough;
default:
    blah();
```

**Comment by bfiete** [comment]
Yeah. I mean, if the `case 'E':` doesn't actually do anything then you just remove it :-)

**Comment by hunterbridges** [comment]
Got it, thanks!
