### ISSUE TITLE
[Enhancement] Using literals as generic arguments

### ISSUE THREAD

**Issue by Moneyl** [beefytech/Beef#1100]
E.g. `FixedArray<16>`, `FixedPoint<16, 16>` This is a feature of C++ that would be useful in Beef.

**Comment by Fusioon** [comment]
This is already supported.
Type definition: 
```
class FixedArray<T, Count> where Count : const int
{
    public T[Count] data;
}
```
Using the type:
```
FixedArray<int, const 16> foo;
```
I believe you can use any primitive type as generic const parameter.

**Comment by Moneyl** [comment]
Ah. I didn't think to make them const. It works. Thanks @Fusioon. The docs even have an example of this so my mistake.
