### ISSUE TITLE
[BUG] System mixins defined in static block are not found when using full name

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1102]
Mixins defined inside System's static block can't be accessed by their full name. For example `System.Swap!` will error out with `Cannot find mixin`. Also System's static methods are not shown in autocomplete.

**Comment by MoshiBar** [comment]
everything in that static block exists in the global namespace, not the System namespace.

**Comment by Fusioon** [comment]
Oh, how did i miss that 😅 So no bugs just user error.. Thank you @MoshiBar
