### ISSUE TITLE
Wrong working directory when running a project with "BeefBuild -run" on Linux

### ISSUE THREAD

**Issue by kumikumi** [beefytech/Beef#1104]
When running a project with `BeefBuild -run` on Linux, work directory points to location of the BeefBuild executable instead of the root of the project directory. This causes problems when trying to load files from relative paths.

To reproduce, include this code in a Beef program:

```
String dirStr = scope String();
Directory.GetCurrentDirectory(dirStr);
Console.WriteLine("Current directory: {}", dirStr);
```

Run the project with `BeefBuild -run`.

Expected behavior: Under Windows you'll get

```
Current directory: C:\path\to\project
```

Actual behavior: Under Linux you get

```
Current directory: /path/to/Beef-0.43.0/IDE/dist
```

**Comment by bfiete** [comment]
Fixed at 8d2b222c1a2498081a055167717e503171453f60
