### ISSUE TITLE
[HARDCRASH] IDE crashing when right click on inherited interface 

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#1106]
How to reproduce:
1. Open provided workspace
2. Right click on interface
3. Watch how IDE dies in pain

NOTE: Even crash dialog crashed to the point that it can't be closed 😥 
*Version 0.43.1 (Nightly 07/07/2021) built 7/7/2021 at 5:56 AM.*
![image](https://user-images.githubusercontent.com/17201053/125711209-c32b3732-42de-4806-badc-2efe09d0d987.png)

[BeefCrashWorkspace.zip](https://github.com/beefytech/Beef/files/6819622/BeefCrashWorkspace.zip)

**Comment by bfiete** [comment]
Fixed at 40cc6b27b738d04e3d279cc0fc00aab9000d7f2f
