### ISSUE TITLE
struct renaming destroys that type's dot syntax consts

### ISSUE THREAD

**Issue by EinBurgbauer** [beefytech/Beef#1107]
For constant values, dot syntax will be recognized and highlighted as the full name, affecting unrelated chars (place cursor on any Point2 text to see).
When renaming Point2, these unrelated chars will be replaced too. (on STRG R, ".(0, 0" becomes "Point2" and so on)

```cs
struct Point2
{
	public const Point2 Zero = .(0, 0);
	public const Point2 One = .(1, 1);
	public const Point2 UnitX = .(1, 0);
	public const Point2 UnitY = .(0, 1);

	public const Point2 NegateX = .(-1, 1);
	public const Point2 NegateY = .(1, -1);

	int x, y;

	public this (int x, int y)
	{
		this.x = x;
		this.y = y;
	}
}
```

**Comment by bfiete** [comment]
Thanks
Fixed at 0ebe4ae929b59df7ec2518e8bc0f8f0c887604de
