### ISSUE TITLE
UnicodeString: specialized string just for unicode

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#111]
Would it be worth implementing? I benchmarked c# string builder it's about twice as fast as our string with utf16 for appending, but it doesn't have to do any encoding. I appreciate how flexible string is so I don't propose to change that.

**Comment by bfiete** [comment]
Mind posting the benchmark code you used?

**Comment by bfiete** [comment]
Comparing a BeefLang String.Append(char32) to a C# StringBuilder.Append(char16) is not comparing apples to apples...

UTF16 is a bit strange - if you are handling unicode codepoints of 0x8000 and above then C# requires that you break those into UTF16 surrogate pairs yourself before inserting them into a StringBuilder. 

So saying that StringBuilder does not require encoding is not really true, it just expects you handle it yourself. That's similar to saying that BeefLang's String doesn't need to do any encoding as long as you're inserting chars below 0x80, and if that's the case when BeefLang's char append is faster than C#'s...

**Comment by damianday** [comment]
@bfiete Thats all true, if you start getting messy with unicode then c# quickly starts showing its warts, so I think you pay the price with either complexity or performance.

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;

namespace Test
{
	class Program
	{
		public static int Main(String[] args)
		{
			var times = scope List<int64>();
			var sw = scope Stopwatch();

			for (let i < 100)
			{
				var str = scope String();
				char16 ch0 = '¥';

				sw.Restart();
				TestAppend(str, ch0);
				sw.Stop();

				times.Add(sw.ElapsedMilliseconds);
			}

			Debug.WriteLine("Average: {0}", Average(times));

			return 0;
		}
		
		private static float Average(List<int64> values)
		{
		    int64 sum = 0;
		    for (int i = 0; i < values.Count; i++)
		    {
		        sum += values[i];
		    }
		    return (float)sum/values.Count;
		}

		[Inline]
		public static void TestAppend(String str, char16 ch)
		{
			for (let i < 1000000)
			{
				str.Append(ch);
			}
		}
	}
}
```

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var times = new List<long>();

            var sw = new Stopwatch();
            
            for (var n = 0; n < 100; n++)
            {
                var sb = new StringBuilder();
                sw.Restart();
                char ch0 = '¥';
                for (var i = 0; i < 1000000; i++)
                {
                    sb.Append(ch0);
                }
                sw.Stop();

                times.Add(sw.ElapsedMilliseconds);
            }

            Debug.WriteLine("Average: {0}", Average(times));
        }

        private static float Average(List<long> values)
        {
            long sum = 0;
            for (int i = 0; i < values.Count; i++)
            {
                sum += values[i];
            }
            return (float)sum / values.Count;
        }
    }
}
```

**Comment by damianday** [comment]
When I ran the benchmarks with Beef release build actually performed worse which I didnt investiagate.

**Comment by bfiete** [comment]
Oh really? I see release outperforming debug...

For the test- I moved the string allocation out of the 'n' loop and reserved the 1000000 to remove any allocation timings.

C#: 1.72ms
Beef Release: 2.3ms
Beef Debug: 6.0ms

But again- this test is only valid for appending UTF16 characters, not actual unicode codepoints. If you are writing a unicode-compliaint application then you cannot assume your unicode characters only occupy a single UTF16 character.

**Comment by bfiete** [comment]
UTF16 is extra confusing because of it's historical overlap with UCS2. Widechar on Windows used to mean UCS2 but then it switched to mean UTF16 when it was clear that characters above 0xFFFF were needed. 

UTF16 is kindof the worst of both words - almost always less memory-efficient than UTF8, but still requires multi-character encoding for unicode codepoints. 

C# does allow you to still write UCS2 application for the most part, however. In that case, their String is better because no encoding is needed. If you're trying to write a UNICODE application, however, then I will posit that a UTF8 encoding will be faster.

**Comment by damianday** [comment]
Damn that release build makes a huge difference, didn't expect that, the performance with c# is negligible, I'll see if I can find the root cause of it slowing on my machine.

**Comment by damianday** [comment]
My use case is for a EditBox widget for which I'd just like to use utf32 string for convenience and ease of use, performance doesn't really matter in this case, it would be a lot simpler to work with if the underlying array was utf32 obviously memory wise it wouldn't be great but I'd happily pay that price.

**Comment by bfiete** [comment]
There's also grapheme clusters to consider. é can be encoded as 'U+00E9' or the two-codepoint method of 'e' followed by 'U+0301'. So even if you were working directly with an array of randomly addressable unicode codepoints, one codepoint in that array does not equal one displayed character in your EditBox...  Cursor position will not equal character index. 

I mean, you can internally use a List of char32's, but I just don't think it buys you any extra simplicitly, really...

**Comment by damianday** [comment]
That's troublesome, it wouldn't really buy me any kind of usability improvement then. It would seem their is little benefit to adding   a specific class for a unicode string.

**Comment by damianday** [comment]
I'm getting these results with an iteration of 100000:
Debug: 3.009
Release: 4.675

These results are curious.. but the rest make sense.

I'm getting these results with an iteration of 1000000:
Debug: 44.244
Release: 33.634

If I reserve with the string first I get
100000 iterations
Debug: 2.865
Release: 1.005

1000000 iterations
Debug: 43.415
Release: 16.420


```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;

namespace Test
{
	class Program
	{
		public static int Main(String[] args)
		{
			var times = scope List<int64>();
			var sw = scope Stopwatch();

			for (let i < 200)
			{
				var str = scope String();
				char16 ch0 = '¥'; 

				sw.Restart();
				TestAppend0(str, ch0);
				sw.Stop();

				times.Add(sw.ElapsedMilliseconds);
			}

			Debug.WriteLine("Average: {0}", Average(times));

			return 0;
		}
		
		private static float Average(List<int64> values)
		{
		    int64 sum = 0;
		    for (int i = 0; i < values.Count; i++)
		    {
		        sum += values[i];
		    }
		    return (float)sum/values.Count;
		}

		[Inline]
		public static void TestAppend0(String str, char16 ch)
		{
			for (let i < 100000)
			{
				str.Append(ch);
			}
		}
	}
}
```

**Comment by bfiete** [comment]
Yeah- the timing differences there are the differences in the allocator. 
- C# was extra fast because it never had to actually do any memory releasing so you were just timing the generation 0 allocation and the GC didn't even collect.
- Beef Debug was faster than Beef Release because the debug leak-detecting allocator happens to be faster than the standard C allocator (used in release) in this case.

**Comment by damianday** [comment]
Ok that makes perfect sense thanks.

I'll close this request for now if someone comes up with any good counter arguments they can reopen.
