### ISSUE TITLE
[BUG] Returning Span created from constant array results in garbage values

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1110]
Code to reproduce:
```
class Program
{
    public const uint32[?] ArrayValue = uint32[7](0,1,2,3,4,5,6);
    public static Span<uint32> SpanValue => uint32[7](0,1,2,3,4,5,6);

    public static void Main()
    {
        // This works as expected
        Span<uint32> foo = ArrayValue;
        for(let i in foo)
            Console.WriteLine(i);	// Prints 0, 1, 2, 3, 4, 5, 6

        // This does not work
        Span<uint32> bar = SpanValue;
        for(let i in bar)
            Console.WriteLine(i);	// Prints random values
    }
}
```

**Comment by bfiete** [comment]
Hm, there may not be an easy way to fix this. It's essentially the same issue as this (in C++)
```C
std::string_view Get()
{
	char c[6] = { 1, 2, 3, 4, 5, 0 };
	return c;
}

int main()
{
	auto sv = Get();
	for (auto c : sv)
		printf("%d ", c);
	return 0;
}
```

It's just a case of a pointer to stack memory being returned -- there's no reasonable proper way for the compiler to detect those cases. It may seem that this particular case would be detectable, but even only slightly more complicated examples become impossible to detect quickly.

**Comment by Fusioon** [comment]
Oh, now that makes sense. for some reason i thought const arrays are stored in memory like String literals.  Thank you for explanation.
