### ISSUE TITLE
[Crash] Using const let with static method/property returning Span

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1112]
Also a feature request, would it be possible to enable comptime evaluation of the `T.RequiredValues`?
Code to reproduce: 
```
class Program
{
    interface IFace
    {
        static Span<uint32> RequiredValues { get; }
    }

    static void GetRequiredValues<T>() where T : IFace
    {
        const let qwe = T.RequiredValues;   // Caused by this line, when let is replaced with uint32[?] it doesn't crash
        for (let i in qwe)
            Console.WriteLine(i);
    }

    struct Foo : IFace
    {
        public static Span<uint32> RequiredValues => uint32[?](0,1,2,3,4,5);
    }	

    public static void Main()
    {
        const let FOO_REQ_VALUES = Foo.RequiredValues;	// Will also crash for the same reason
    }
}
```
Tested with: 4b8983a

**Comment by bfiete** [comment]
This works now at f1d9964ba102eccb37e9bf48d4535402e77739cc

The `const let qwe = T.RequiredValues;` produces a warning now - there is no constraint that can ensure that the concrete `RequiredValues` implementation can be comptimed when the generic method is specialized (ie: with T as `Foo`), so this has the ability to generate errors at generic specialization time (which is not nice), and thus the warning.
