### ISSUE TITLE
Broken for(i < x)

### ISSUE THREAD

**Issue by EinBurgbauer** [beefytech/Beef#1113]
the recent `for (var i < Func())` changes mean that this doesnt work anymore, which i always found very nice
```cs
List<int> l = scope .() { 1, 2, 3, 4, 5, 6 };
for (var i < l.Count)
{
	l.RemoveAtFast(i);
}
```
I guess i could also put Count into a local var (if that worked), but sometimes one would actually want the func in the loop to be periodically called. Not sure if this is a bug, just wanted to ask if this is an intended effect.

```cs
var count = 5;
for (var i < count)
//for (var i = 0; i < count; i++)
{
	Runtime.Assert(i < count);
	count--;
}

for (var i < count)
//for (var i = 0; i < count; i++)
{
	Runtime.Assert(i < count);
	count++; // Infinite LOOOOOOP
}
```
this doesnt work either anymore though, which is a bug. Changes to count are seemingly just ignored

**Comment by bfiete** [comment]
Yeah, the intention is for it to behave like this:
`for (var i in Range(0, count))`
rather than this:
`for (var i = 0; i < count; i++)`

I know Range doesn't actually exist currently, but the intention is that it behaves more like that enumerator case (where the enumerator ctor arguments are only evaluated on initialization) than the generalized `for` loop case where the extents are re-evaluated on each iteration.

**Comment by EinBurgbauer** [comment]
Okay, so i guess that means i should basically convert everything where i need any loop length control to the generalized for, which is fine.

The change, especially with a variable like in the issue is a bit confusing when you can clearly change the variable, but i'll get used to that.
I see the use case for functions and can probably shorten some code other now. Thanks for clarifying and the last week's quick patches.

**Comment by bfiete** [comment]
I might revise this- maybe the C# 8 style of ranges like `for (int i in 0..count)` is best for expressing that type of count-invariant optimization.

**Comment by EinBurgbauer** [comment]
I think i would support that.

the c# syntax is better i think, but weird when .. already cascades and we want to use calls with it.

``for (var i to count){} for (var i to func())`` sounds a bit weird, but on par with what for (i < x) can do.
``for (var i in 0->count)`` weird but unused, as is ',' and ':' theoretically
``for (var i in 0 to count)`` very verbose but clear

This is what i could come up with, not sure i like everything but just some thoughts. Hm

**Comment by bfiete** [comment]
I would read `for (var i in 0 to count)` as an inclusive range, meaning `for (var i in 0 to count - 1)` would be required...

But Swift has an answer for this, too-
`a..<b` is an exclusive range (ie: `for (int i in 0..<count)`)
`a...b` is an inclusive range

So, different operators than the `..`, and both exclusive and inclusive ranges are handled.

**Comment by EinBurgbauer** [comment]
Yeah, that'd seem reasonable to me, i think that would be fine.

**Comment by bfiete** [comment]
The old `for (var i < Func())` functionality is back in now. The "optimized" non-reevaluating version will use ranges as proposed, whenever I get around to that

**Comment by EinBurgbauer** [comment]
Thanks!
