### ISSUE TITLE
False mut error on non readonly struct setter

### ISSUE THREAD

**Issue by EinBurgbauer** [beefytech/Beef#1115]
On the following code, trying to set Length to one will error: "Cannot call mutating method ... on read-only variable ..."
```cs
var replace = StringView("HELLLO");
replace.Length = 1;
```

**Comment by bfiete** [comment]
Just to verify - you aren't getting this error on compile, just a mouseover error squiggle in the IDE, right?

**Comment by EinBurgbauer** [comment]
Yep... the error is not on compile... except for when you try to build it with a lib project as the startup project (dont know why i would use that as a test case), which is why i didnt catch this originally, sorry

**Comment by bfiete** [comment]
Fixed at 85a2a089f40c97f321e5fac2fbec0009c5fceafd
