### ISSUE TITLE
Incorrect "Invalid use of inferred-sized array" error

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1117]
This code causes the "Invalid use of inferred-sized array" error, but there's no inferred size to be seen.
```
		static struct MyCoolStruct<T>
		{
			public const int MyConst = GetMyConst();
			public static int[MyConst] MyInts;

			public static int GetMyConst()
			{
				return 10;
			}

			public static int[MyConst] GetMyInts()
			{
				return MyInts;
			}
		}
```
Tested with https://github.com/beefytech/Beef/commit/d86eb0625c1463966c86d4e14a1accdaabf75a00

**Comment by bfiete** [comment]
This magically got fixed somewhere...
