### ISSUE TITLE
IDE crash when using properties and structs in a certain way

### ISSUE THREAD

**Issue by mandrelavoie** [beefytech/Beef#112]
Hi,

The following code reliably make my IDE crash:
```
namespace PropertyStructCrash
{
	struct B
	{
		public int c;
	}

	struct A
	{
		public B Prop { get; set; }
	}

	class Program
	{
		public static void Main()
		{
			var a = A();
			a.Prop = B();
		}
	}
}
```

With this error message:
![crash](https://user-images.githubusercontent.com/6820392/78829515-76a7bd00-79b4-11ea-8a68-21f58a3b159c.png)

Making `B` a class instead of a struct fix the problem.
Making `A.Prop` an attribute instead of a property also fix the problem.

**Comment by damianday** [comment]
It crashes with master as well, but the error reported was in a different location.

**Comment by bfiete** [comment]
Auto-implemented properties had atrophied from lack of use. This should be fixed in https://github.com/beefytech/Beef/commit/664078557f772dd269d99af58fe1cfb8813d57f3 and some tests have been added. Will be in release 0.42.2.

**Comment by mandrelavoie** [comment]
I rebuilt from master and it works fine now. Thanks!
