### ISSUE TITLE
IDE crashes when I give a default lambda to a method parameter

### ISSUE THREAD

**Issue by HLSSLenda** [beefytech/Beef#1131]
Test code:
```beef
namespace System.Linq
{
    public static class Enumerable
    {
        private typealias Predicate<T> = delegate bool(T);
        public static int Count<TSource>(this IEnumerable<TSource> source, Predicate<T> predicate = (_) => true) // when I hover (sometimes) or select near the "predicate" parameter, the IDE crashes
        {
        }
    }
}
```
Also, does Beef allows lambdas as default parameter in methods?
[bf.zip](https://github.com/beefytech/Beef/files/6917496/bf.zip)

**Comment by bfiete** [comment]
Crashes fixed at 974b3a58e834d83cfd55f55625ad63485d987fa6

Default param values must be constant - delegates must be allocated, and allocations can never be constant, so that's not allowed. Currently, function binding is also not considered constant but that could one day be supported.
