### ISSUE TITLE
Abstract methods can't be declared inside extensions

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1133]
I suppose this is a bug since the error doesn't make it clear that it's because the method is inside an extension, code to reproduce is below.
```
	abstract class Foo<T>
	{
		protected abstract void Foo();
	}

	extension Foo
	{
		protected abstract void Bar(); // Method is abstract but it is contained in non-abstract class
	}
```
Tested with https://github.com/beefytech/Beef/commit/d86eb0625c1463966c86d4e14a1accdaabf75a00

**Comment by bfiete** [comment]
Fixed at 16829900bc8a9330e487b88178b013c02e960211
