### ISSUE TITLE
String allocation causes expression block to yield wrong value

### ISSUE THREAD

**Issue by gopakumar-gg** [beefytech/Beef#1144]
Issue occurred in Release version 0.43.0

For the snippet below, I input "-1" at Console.ReadLine(str).   But it enters the if-block.

		public static void ExpressionBlock()
		{
			int num = 5;
			
			if ( {
				    String str = scope String(16);
				    Console.ReadLine(str);  // input -1 here.
				    num = int.Parse(str); // str gets properly parsed and num becomes -1
				    num > 0
				 })
			{
 				// wrongly enters here and below statement is executed.
				Console.WriteLine("{} - 2 = {}", num, num - 2 );  // prints -1 - 2 = -3.
			}

			Console.WriteLine("Done\n");
		}

If I move the string allocation to outside the if-block (as shown below), there is no problem.

		public static void ExpressionBlock()
		{
			int num = 5;
			String str = scope String(16);
			if ( {
				    
				    Console.ReadLine(str);  // input -1 here.
				    num = int.Parse(str); // str gets properly parsed and num becomes -1
				    num > 0
				 })
			{
 				// It will not come here if str is "-1"
				Console.WriteLine("{} - 2 = {}", num, num - 2 ); 
			}

			Console.WriteLine("Done\n");
		}

**Comment by bfiete** [comment]
Thanks for the bug- fixed at 723e2177fc769066d681d9f98ca9b85962a4957c
