### ISSUE TITLE
IDE doesnt support .TTC font files

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#1146]
IDE cant load fonts like MS Gothic and so on. Mainly used for Chinese and Japanese symbols.
![obrazek](https://user-images.githubusercontent.com/17201053/133450979-b092e960-c543-4c1f-89a6-ce26a95b9d18.png)

**Comment by bfiete** [comment]
Added at fb1d1aecc0091511cac56fefc9f2ee2deec6421d
