### ISSUE TITLE
[BUG] Array allocation allows invalid syntax

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1149]
When doing a array allocation it's possible to use multiple literals/variables when they are not separated by comma. Code will compile fine but linker will error out with unresolved external symbols.
Code to reproduce:
```
class Program
{
    static void Main(String[] args)
    {
        uint16 size = 100;
        uint8[] data = new uint8[size size];
    }
}
```
Tested with: (Nightly 09/22/2021)

**Comment by bfiete** [comment]
Fixed at a5fff0fdbcd5d3d3ac0198b39df1af06556ef25e
