### ISSUE TITLE
[Bug] Crash with negative array size and allocator keyword

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#1150]
The following snippet crashes the IDE:

```
namespace beef_test
{
	class Program
	{
		public static void Main(){
			uint8[] a = scope uint8[-2]();
		}
	}
}
```

Two things needed for the crash to happen:
- Allocator keyword must be used (scope/new)
- The size must be smaller than -1.

Surprisingly, with an array size of "-1", no visual warning/error is shown, but anything below will crash.

Version 0.43.1 (Nightly 09/26/2021)

**Comment by bfiete** [comment]
Fixed at 6b9bb361f9adb6165fff0f5d6e73b43958256e02
