### ISSUE TITLE
[Bug] IDE crashes on StackOverflowError when typing out generic argument

### ISSUE THREAD

**Issue by heisluft** [beefytech/Beef#1151]
IDE version: latest commit (6b9bb361f9adb6165fff0f5d6e73b43958256e02)

```beef
using System;
using System.Collections;

namespace ExtensionGenericCrash {
	public interface SuperType {}

	public class ListOfItselfOrIntegers<T> : SuperType, List<T> where T : SuperType {}

	public class Program {
		public static void Main() {
			ListOfItselfOrIntegers<ARG> array = scope .(); //ARG is a substitute, desired type: uint32
		}
	}
}


namespace System {
	public extension IInteger : ExtensionGenericCrash.SuperType {}
}
```

Typing out "uint32" in place of ARG in any way crashes the IDE on a stackoverflow error.
Pasting "uint32" or beginning to type and then selecting "uint32" from the Autocompletion does not only not crash the IDE but also compile and run as intended.

I have not attached a minidump as i dont know how to create one, help would be appreciated

Cheers!

**Comment by bfiete** [comment]
Thanks. Fixed at 37e4c589b0c3ff569557fe16265e76962d5b4c1d (fix will be in the next nightly build)
