### ISSUE TITLE
[BUG] Constants of enum type need default branch in switch

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1154]
Defining an enum constant and then using it in `switch` even with all possible values listed will still result in error: `Switch must be exhaustive`. 
Code to reproduce:
```
class Program
{
    enum Foo
    {
        One,
        Two
    }

    static void Main(String[] args)
    {
        const Foo VALUE = .One;
        switch (VALUE)
        {
        case .One:
        case .Two:
        }
    }
}
```
Tested with: (Nightly 10/01/2021)

**Comment by bfiete** [comment]
Fixed at 63a87cbe57d8788070aab7f90cda82352a089f38
