### ISSUE TITLE
[Crash] Resetting UI after modifying a source file results in a crash

### ISSUE THREAD

**Issue by MoshiBar** [beefytech/Beef#1156]
Nightly 10/03/2021

if you modify a source file without saving, then choose reset UI, then the IDE will crash with this error:

`Assert failed: Source marked as modified with no SourceViewPanel at line 13418 in c:\Jenkins\workspace\Beef\IDE\src\IDEApp.bf`

**Comment by bfiete** [comment]
Fixed at a2a97a8e5fc745ea0f43f9f4e3854b0695b6fa0a
