### ISSUE TITLE
[IDE][Enhancement] Collapsible brackets

### ISSUE THREAD

**Issue by LoopyAshy** [beefytech/Beef#1163]
The title speaks for itself: the ability to visibly collapse brackets within the code to hide sections of the document.
Collapsible brackets is an ability which most IDEs already have(VSCode, VS, Intellij, etc) and has become very much the standard and honestly I feel it is too useful to miss out on for readability sake.

**Comment by bfiete** [comment]
Dup of https://github.com/beefytech/Beef/issues/363
