### ISSUE TITLE
Dictionary EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#117]
I've reduced it now to this, seems to happen during GC RawMarkSpan.
I can't see whats causing it, I do know if i use an empty struct as the value or a primitive like int the problem vanishes.
At first I thought I had a dangling pointer with the key before I reduced it, but thats not the case.

```
using System;
using System.Collections.Generic;

namespace Test
{
	public struct Section
	{
		private String mSectionName = new String();

		public StringView Name
		{
			get { return mSectionName; }
		}

		public this(StringView sectionName)
		{
			mSectionName.Set(sectionName);
		}
	}

	class Program
	{

		public static int Main(String[] args)
		{
			Dictionary<StringView, Section> mSections = new .();
			let section = Section("Name");
			mSections.Add(section.Name, section);

			while (true)
			{

			}
			return 0;
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed by https://github.com/beefytech/Beef/commit/accc74957a2a6b91aaf11c92ec27104c30f1acb1

It was a calling convention issue - again, thanks for exercising the Win32 side!
