### ISSUE TITLE
argument cascade operator valid in indexers (and also doesnt work there)

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1186]
I was originally just trying out ranges, but the fact that this was valid seems weird. It doesn't actually override the return either, but then again why should you be able to override the return of an indexer from what with index with? This just seems like a easy trip-up for new people due to the close resemblence with ranges and an easy mistake. The cascade operator maybe shouldn't be valid in indexers.

```
int[] a = scope .[8](1,2,3,4,5,6,7,8);

let s = a[.. ^1];
Debug.WriteLine(s.ToString(.. scope .()));
```

**Comment by bfiete** [comment]
Fixed at c939ec1cf6bae1606473b8221045673c325c365b
