### ISSUE TITLE
comptime false Invalid stringView / access violation

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1188]
it's basically bug1 of #954 still, but this time easier to reproduce.

to reproduce, grab Pile and open the Examples/Square project. https://github.com/EinScott/Pile

1. clean & compile
2. add "String s;" as a member of Example at the top of the class & compile
3. add [PerfTrack] to Update(). The error will already be reported with squiggles, compiling also errors

alternative way (though it doesnt differ that much and it may just be the same thing with extra steps)
1. clean & compile
2. add [PerfTrack] to Update()
3. add "String s;" as a member of Example at the top of the class & compile
4. comment out [PerfTrack] & compile
5. uncomment [PerfTrack] . The error will not be reported with squiggles, compiling errors

**Comment by bfiete** [comment]
Well, that was a bit painful to track down. This is a bug that I've seen a few times but never had a good repro for it until now.
Finally fixed at da428d2c50aa5dc5c237b0c59b2843f83dff395b

**Comment by EinScott** [comment]
Thanks! That bug had been a regular for most of the year
