### ISSUE TITLE
weird mouse-over at the end of enums

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1192]
Example, everyday, normal enum:
```
enum YEEE
{
	A, B, C,
	LALA,
	EEEE,
	mm
}
```

hovering over the space just after "mm" (or rather the rightmost edge of the glyph almost) will produce a weird popup, listing the entire enum with weird formatting, a missing character (and the value of mm, so this is probably supposed to be a mouseover of just that)

also, when hovering over the move-over windows of the enum values on their name (for example, the "mm" of the window appearing when hovering over "mm" in the sourceView), another mouse-over reading "int64_t" pops up.

**Comment by bfiete** [comment]
Fixed at a17f57f4c61cf6d934da71b23bfe9906de366164
