### ISSUE TITLE
Struct constructor isn't unconstrained by `var`

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1194]
The below (commented out) code should work as everything should have been unconstrained by `var`

```
	struct Test<T> where T : var
	{
		mixin Allocate() where T : class
		{
			new T() // ok
		}

		mixin Allocate() where T : struct
		{
			//T() // ERROR: Must add where T : new, struct
			default(T) // ok
		}

		//T a = T(); // ERROR: Must add where T : new, struct
		T a = Allocate!(); // ok
	}
```

Now, not sure if the below one is really an issue, but if you go the other way around (no constraints and not unconstrained) it also doesn't work.
Looks like the only way to add the `new` constraint is in the type definition itself, it doesn't work if you use it only on the method where you want to call it.

```
	struct Test<T>
	{
		mixin Allocate() where T : new, class
		{
			new T() // ERROR: Must add where T : new
		}

		mixin Allocate() where T : new, struct
		{
			T() // ERROR: Must add where T : new, struct
		}

		mixin Allocate()
		{
			default(T)
		}

		T a = Allocate!();
	}
```

But if you change the code and add `where T : new` in the type definition, then `new T()` works as expected, but `T()` still doesn't work.

```
	struct Test<T> where T : new
	{
		mixin Allocate() where T : class
		{
			new T() // ok
		}

		mixin Allocate() where T : struct
		{
			T() // ERROR: Must add where T : struct
		}

		mixin Allocate()
		{
			default(T)
		}

		T a = Allocate!();
	}
```

**Comment by bfiete** [comment]
Fixed at 7a8592268c6c907acc2a8442f80f04bfbc3e073d
