### ISSUE TITLE
`Not Implemented` fatal error while hovering field type

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1199]
Hovering over `<int>` will crash the IDE.

Crash message
```
FATAL MODULE ERROR
Not implemented at D:\BeefLang\Repository\Beef\IDEHelper\Compiler\BfModuleTypeUtils.cpp:13878
Module: 
Type: BeefBugRepros
```

Repro code:
```
	static
	{
		const Tt<int> b = new .();
	}

	struct Tt<T>
	{
	}
```
Tested with: https://github.com/beefytech/Beef/commit/7a8592268c6c907acc2a8442f80f04bfbc3e073d

**Comment by bfiete** [comment]
Fixed at 42874ed25293beb9caa92344ff155a42c5564754
