### ISSUE TITLE
Access violation creating const result

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1200]
Repro code:
```
	static
	{
		const Test<String> aaa = .();
	}

	struct Test<T>
	{
		T a = default(T);
	}
```
Tested with: https://github.com/beefytech/Beef/commit/7a8592268c6c907acc2a8442f80f04bfbc3e073d

**Comment by bfiete** [comment]
Fixed at b298b232ef5cf3b2326974bd80584aaf0c802437
