### ISSUE TITLE
Treating result type as tuple crashes the IDE

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1202]
The below code causes a crash, the crash only occurs if the `.0` is present.
```
	struct Test<T>
		where T : var
	{
		public U Crash<U>(U a) where U : var
		{
			return default(U);
		}

		typealias TKey = decltype(default(Self).Crash(default(T)).0);
	}
```
Tested with: https://github.com/beefytech/Beef/commit/7a8592268c6c907acc2a8442f80f04bfbc3e073d

**Comment by bfiete** [comment]
Fixed at 2af4468b4db21561d1e960bee1c73497b7f5044b
