### ISSUE TITLE
String.Append causes access violation

### ISSUE THREAD

**Issue by HydrogenC** [beefytech/Beef#121]
```
String str="AString";
str.Append(" AnotherString");
```
The code above causes access violation at String.bf:717.

**Comment by bfiete** [comment]
You can't modify a string literal. You need to allocate your own string.

```
let str = scope String("AString");
str.Append(" AnotherString");
```

**Comment by HydrogenC** [comment]
Thanks!

**Comment by HydrogenC** [comment]
I think that there should be a warning or a compiler error here insteading of crashing during runtime.

**Comment by bfiete** [comment]
This particular case wouldn't be that hard to detect, but most other cases would be extremely hard to detect, particularly when the literal crosses call boundaries. Even this simple case here would require some frontend flow analysis that we don't do...

It would be easier to add some better runtime help for the crash...

**Comment by HydrogenC** [comment]
And also, I would like to write something about this in the docs as this is pretty different from C++ and C#, which reallocates when appending.

**Comment by bfiete** [comment]
Yeah, I think you're right - the string models for C, C#, C++, and Beef are all pretty different and they do go a long way to exemplify the differences in the languages.

Beef's string would be best described as a merging of C#'s String and StringBuilder. C++ strings are always mutable, but they do not give you the capability to point to a string literal without allocation.

I would also like to point out that Beef and C are the only of those languages that lets you perform this string concatenation WITHOUT a heap allocation, assuming you reserve enough stack space. But of course in C you'd have to use C char arrays which is pretty terrible. Also Beef lets you use custom allocators for internal working string memory.

Beef string with reserved stack space:
```
let str = scope String(256)..Set("AString");
str.Append(" AnotherString");
```

C++ std::string MAY heap allocate on both the initial assignment and on the append... depending on the string sizes and how those correlate to the "small-string optimization" internal buffers and the initial string allocation size.

C# lets you point to string literals without allocation but then you have to decide between massive allocations and GC pressure with String concatenation or using a StringBuilder - though a StringBuilder lacks the capability to work only without stack memory or memory from a custom allocator.

**Comment by HydrogenC** [comment]
Thanks for explaining.
