### ISSUE TITLE
Assert failed "block->mKind == ChBlockKind_Unused"

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1213]
The assertion failure mentioned in the issue title can be reproduced if you try to compile the below code in the Debug IDE (BeefIDE_d).
There's also another issue that can be reproduced using this code, the details are in the commented line in the code.

```
namespace BeefBugRepros
{
	static
	{
		[Comptime]
		public static void EmitBindCode<T>()
		{
			let type = typeof(T); // if you comment out this line, the compiler hangs while trying to compile the code.
			let code = scope String();

			for (var method in type.GetMethods())
			{
				String retType = method.ReturnType.GetFullName(.. scope .());
				code.AppendF(@$"{retType}");
			}
		}

		[Test]
		public static void TestBug()
		{
			EmitBindCode<System.Console>();
		}
	}
}
```
Tested with: 344b8d01818be06b336186041c85993f4368f2f6

**Comment by bfiete** [comment]
Fixed at 7e36f374e1361223cbd402e0163aa7aa24520ca8
There was some bugs in the actual comptime heap implementation - this should fix a number of general "strange behavior" comptime issues.
