### ISSUE TITLE
Unable to implicitly cast `method reference` to `void*`

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1220]
The code below fails to compile because of the error `Unable to implicitly cast 'method reference BeefBugRepros.GetStr(System.String str, uint8 a)' to 'void*'`
```
using System;

namespace BeefBugRepros
{
	static
	{
		public static void Test1(void* ptr)
		{
		}

		public static void Test2<F>(F func)
			where F : function String(String, uint8)
		{
			Test1(func);
		}

		public static String GetStr(String str, uint8 a)
		{
			return str;
		}

		[Test]
		public static void TestBug()
		{
			Test2(=> GetStr);
		}
	}
}
```

**Comment by bfiete** [comment]
This will now error on the definition at bb6c59e39ea093d3bd09b4e2c8abb643512431d0
(because `F` could be a valueless method reference)
