### ISSUE TITLE
Struct mutable function can be called with an invalid instance

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1222]
You can bind a struct's mutable function to a function pointer without the `mut` qualifier, this causes the code to deref the instance instead of passing it, which causes an Access Violation when the function tries to deref the instance.

Repro code:
```
	struct Vector2 : this(int x, int y);

	struct Actor
	{
		private Vector2 mPos;

		public void SetPosition(Vector2 vec) mut
		{
			mPos = vec;
		}

		public Vector2 GetPosition()
		{
			return mPos;
		}
	}

	class Program
	{
		public static int Main(String[] args)
		{
			Actor actor = .();

			function void(mut Actor this, Vector2) fun = => Actor.SetPosition;
			fun(actor, Vector2(3, 4)); // works as expected

			function void(Actor this, Vector2) fun2 = => Actor.SetPosition;
			fun2(actor, Vector2(3, 4)); // access violation, the instance address was "0x'00000003"

			return 0;
		}
	}
```

**Comment by bfiete** [comment]
Fixed at 6a95cbb3b8af31457170983345978ae52f6e6a41 in the sense that there will be a bind error now. A nice feature would be to create a function thunk automatically, but that's for the future sometime.
