### ISSUE TITLE
[Enhancement] Allow properties to have a ref setter

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1223]
Repro code:
```
		private void* ptr;

		public ref T ValueRef
		{
			get
			{
				Debug.Assert(ptr != null);
				return ref *(T*)ptr;
			}
			set
			{
				ptr = &value; // Cannot take address of parameter 'value'. Consider adding 'ref'
			}
		}
```

**Comment by bfiete** [comment]
Yeah, that's on purpose. `ref` only refers to the getter, not the setter.

**Comment by bfiete** [comment]
I mean, otherwise you'd have to say `instance.ValueRef = ref x;` in the user code, too... which... yeah, hard to imagine a case where you'd want that.

**Comment by bfiete** [comment]
I suppose you could make a case for a qualifier on `set` to override that... just like there's a `set mut`, we could have a `set ref` to indicate you want incoming values to be `ref` also...

**Comment by disarray2077** [comment]
> I mean, otherwise you'd have to say `instance.ValueRef = ref x;` in the user code, too... which... yeah, hard to imagine a case where you'd want that.

I mean... That's exactly what I wanted lol

> I suppose you could make a case for a qualifier on `set` to override that... just like there's a `set mut`, we could have a `set ref` to indicate you want incoming values to be `ref` also...

That would be nice!

**Comment by bfiete** [comment]
Supported at 40b0d78d166dcf30f1bd93dd00dfab9c400acd5a
