### ISSUE TITLE
[Bug] @param doesn't render anymore

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#1230]
_/// @param argname message_

Used to add an explanation to the parameter.
In the current nightly this isnt the case anymore and instead it seems to render an empty line.

**Comment by Booklordofthedings** [comment]
examples
![unknown-4.png](https://user-images.githubusercontent.com/59422062/141738118-eaaf7d11-2f1f-4aa2-9880-6ea2c73b33b0.png)
![unknown-5.png](https://user-images.githubusercontent.com/59422062/141738138-5656d4c8-1f8d-4072-a71c-7215a5596fc8.png)

**Comment by bfiete** [comment]
Fixed at 7dbd5294d724824477ea6c4d004c78b520983b1b
