### ISSUE TITLE
Crash when writing Result keyword

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#1232]
My IDE crashes after writing Result in my code. I was unable to replicate this in empty project so its project wise bug.

![image](https://user-images.githubusercontent.com/17201053/142041299-cb970ed2-69f2-4d03-b0ad-410628b4b32c.png)

Steps to replicate:
1. Open attached workspace
2. Go to Reader class
3. try to add method with Result return type. 
4. Crash

Project files
[BJSON.zip](https://github.com/beefytech/Beef/files/7548830/BJSON.zip)

**Comment by bfiete** [comment]
Fixed at 11e41558d7452d4698a7c2f4e577705e756bf901
