### ISSUE TITLE
[Enhancement] Internal types

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1236]
I guess this may also be a bug since the error message doesn't say anything about internal:
![image](https://user-images.githubusercontent.com/86157825/142298656-aee7e1fe-fab3-4599-8d00-438d83122791.png)

**Comment by bfiete** [comment]
Fixed at 870c9914beb177b368d5a97a38b99076a526a5dd

**Comment by disarray2077** [comment]
@bfiete
Thanks! It's working... but I have to say that the errors are really unhelpful (they don't even jump to the source)
```
Compiling...
Beef compilation time: 0.09s
ERROR: 'BeefFNT.XmlNodeEnumerator' is inaccessible due to its protection level
ERROR: 'BeefFNT.XmlNodeEnumerator' is inaccessible due to its protection level
ERROR: 'BeefFNT.XmlNodeEnumerator' is inaccessible due to its protection level
15 modules built, 11 object files generated
Errors: 3.
Compile failed.
```

**Comment by disarray2077** [comment]
@bfiete Nevermind, the problem solved itself after doing another pull and recompile
