### ISSUE TITLE
[Enhancement] Object shallow copy

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1237]
Having some way to create shallow copies of objects can be useful (i.e. `MemberwiseClone`), I ended up having the need for this when I wanted to clone delegates but there is no way to do this currently.

**Comment by bfiete** [comment]
I would say that most system objects cannot be memberwise-cloned. If you memberwise-clone a `System.String` then both copies will attempt to free the character data array when destructed - CRASH. Pretty much the same for all containers, actually. These kind of things are much more likely to work correctly with GC-based systems.

Also, a Clone method implies that it always allocates on the global heap, and we don't like requiring that. On the other hand, you wouldn't get the type erasure you need for cloning delegates (ie: cloning a closure with captures) if you have to have a-priori type knowledge for allocating the result ahead of time.

It feels like a reasonable feature for C# but it doesn't feel like it fits here...

**Comment by disarray2077** [comment]
Oh, you're right, I thought this could have some usefulness when the types are simple but after a second thought, I guess almost every type would end up having a class as one of its members, and if it's a struct it could just be copied... Fair enough.

About `Clone method implies that it always allocates on the global heap`, I don't think this would be much of an issue if it was a method like `Type.CreateObject`, which also allocates on the global heap. I managed to create a `MemberwiseClone` method based on the `Type.CreateObject` method that seems to be working for my purpose of cloning simple delegates (https://pastebin.com/Crq9eSL4), but I can understand if the usefulness of this method is too small to be added as something official to the corlib.

**Comment by bfiete** [comment]
Just keep in mind that lambdas can have user-defined destructors that won't be aware of the possibility of being executed more than once. It's fine if you're using it for your own delegates where you know that will never be an issue, but it wouldn't be good for a library that clones unknown incoming delegates.
