### ISSUE TITLE
IDE crash

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#124]
Exception: Access Violation (code 0xc0000005) at address 247'88d1a980 in thread 2BBC
Executable: C:\beef\IDE\dist\BeefIDE.exe
File Version: 0.42.2
Product Version: 0000000000000000

Logical Address: 0001:'004f9980

71'de6fdf20 247'88d1a980 IDEHelper64.dll class llvm::Use * __ptr64 std::_Copy_unchecked<class llvm::Value * __ptr64 const * __ptr64,class llvm::Use * __ptr64>(class llvm::Value * __ptr64 const * __ptr64,class llvm::Value * __ptr64 const * __ptr64,class llvm::Use * __ptr64)+70
    Params: '00000005 247'88d65abb '00000004 247'88961ec4

71'de6fdf60 247'88d23455 IDEHelper64.dll void llvm::CallInst::init(class llvm::FunctionType * __ptr64,class llvm::Value * __ptr64,class llvm::ArrayRef<class llvm::Value * __ptr64>,class llvm::ArrayRef<class llvm::OperandBundleDefT<class llvm::Value * __ptr64> >,class llvm::Twine const & __ptr64+95
    Params: 71'de6fe020 71'de6fe030 71'de6fe030 ffffffff'ffffffff

71'de6fdfe0 247'8895f3e7 IDEHelper64.dll llvm::CallInst::Create+1B7
    at c:\beef\extern\llvm-project_8_0_1\llvm\include\llvm\ir\instructions.h:1501
    Params: 247'9e34f0c0 71'de6fe1c0 247'9deae670 247'9ee41f70

71'de6fe060 247'8896f9c5 IDEHelper64.dll llvm::IRBuilder<llvm::ConstantFolder,llvm::IRBuilderDefaultInserter>::CreateCall+55
    at c:\beef\extern\llvm-project_8_0_1\llvm\include\llvm\ir\irbuilder.h:1977
    Params: '00000001 247'9e34f0c0 247'9e50fde0 247'889703f0

71'de6fe0b0 247'8896d2d5 IDEHelper64.dll llvm::IRBuilder<llvm::ConstantFolder,llvm::IRBuilderDefaultInserter>::CreateCall+35
    at c:\beef\extern\llvm-project_8_0_1\llvm\include\llvm\ir\irbuilder.h:2010
    Params: 247'88820000 247'9e34f0c0 247'9919bfd0 247'9f169398

71'de6fe470 247'88966e6c IDEHelper64.dll Beefy::BfIRCodeGen::HandleNextCmd+47CC
    at c:\beef\idehelper\compiler\bfircodegen.cpp:2451
    Params: 247'ffffffff 247'9e0c56b8 247'9e0c56b8 247'00001a91

71'de6fe4a0 247'8896158f IDEHelper64.dll Beefy::BfIRCodeGen::ProcessBfIRData+AF
    at c:\beef\idehelper\compiler\bfircodegen.cpp:443
    Params: 247'9ee82400 247'90e4d1c0 71'de6fe5b0 247'9e50fde0

71'de6ffb70 247'888fbce0 IDEHelper64.dll Beefy::BfCodeGenThread::RunLoop+1160
    at c:\beef\idehelper\compiler\bfcodegen.cpp:476
    Params: 247'9dab4860 '00000000 '00000000 247'9e174da0

71'de6ffba0 7ffe'50e97bd4 KERNEL32.DLL BaseThreadInitThunk+14
    Params: '00000000 '00000000 '00000000 '00000000

71'de6ffc20 7ffe'5164ce51 ntdll.dll RtlUserThreadStart+21
    Params: '00000000 '00000000 '00000000 '00000000

RAX:2'0000000c RBX:'00000005 RCX:247'9deae5e8 RDX:71'de6fe278 RSI:71'de6fe030 RDI:247'9deae670
R8:247'9deae5e0 R9:247'9e62c0f0 R10:71'de6fe250 R11:'00000000
R12:247'9e34f0c0 R13:'00000001 R14:247'9e0c56b8 R15:'00000000
EIP:247'88d1a980 ESP:71'de6fdf28 EBP:247'9ec3bae8
CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:'00010206

[crash.zip](https://github.com/beefytech/Beef/files/4499788/crash.zip)

**Comment by damianday** [comment]
FATAL ERROR: irValue.mId >= 0
Assertion failed!

Program: C:\beef\IDE\dist\IDEHelper64_d.dll
File: c:\beef\idehelper\compiler\bfirbuilder.cpp
Line: 1792

Expression: irValue.mId >= 0

**Comment by damianday** [comment]
If I compile with 64 bit instead I get

Exception: Access Violation (code 0xc0000005) at address 1bb'f55847c5 in thread 1CC0
Executable: C:\beef\IDE\dist\BeefIDE.exe
File Version: 0.42.2
Product Version: 0000000000000000

Logical Address: 0001:'000737c5

2e'efc4ce10 1bb'f55847c5 IDEHelper64.dll Beefy::BePointerType::HashContent+35
    at c:\beef\idehelper\backend\becontext.h:175
    Params: '0000000b 1bb'87a7a6f0 '00000039 1bb'f66eecac

2e'efc4cfe0 1bb'f559ba2c IDEHelper64.dll Beefy::BeMCContext::GetOperand+5C
    at c:\beef\idehelper\backend\bemccontext.cpp:2141
    Params: 2e'efc4e440 2e'efc4d0c0 1bb'87a7a6f0 2e'efc4d578

2e'efc4d0e0 1bb'f559d68f IDEHelper64.dll Beefy::BeMCContext::CreateCall+6F
    at c:\beef\idehelper\backend\bemccontext.cpp:2749
    Params: '00000000 '00000000 2e'efc4d1f0 1bb'88602580

2e'efc4e2a0 1bb'f55c075f IDEHelper64.dll Beefy::BeMCContext::Generate+2CBF
    at c:\beef\idehelper\backend\bemccontext.cpp:16311
    Params: 1bb'88575600 1bb'87bea2a0 1bb'87a43c00 1bb'879fce00

2e'efc4e790 1bb'f5580eda IDEHelper64.dll Beefy::BeCOFFObject::Generate+98A
    at c:\beef\idehelper\backend\becoffobject.cpp:2092
    Params: 1bb'87c2b360 1bb'87e53450 '00000000 1bb'87e375e0

2e'efc4e850 1bb'f5581517 IDEHelper64.dll Beefy::BeCOFFObject::Generate+D7
    at c:\beef\idehelper\backend\becoffobject.cpp:2129
    Params: 1bb'873a0b28 1bb'873a0b28 1bb'87e45e00 1bb'882e0b78

2e'efc4ff20 1bb'f55ebb7e IDEHelper64.dll Beefy::BfCodeGenThread::RunLoop+FFE
    at c:\beef\idehelper\compiler\bfcodegen.cpp:453
    Params: 1bb'8794eda0 '00000000 '00000000 1bb'87d634b0

2e'efc4ff50 7ffe'50e97bd4 KERNEL32.DLL BaseThreadInitThunk+14
    Params: '00000000 '00000000 '00000000 '00000000

2e'efc4ffd0 7ffe'5164ce51 ntdll.dll RtlUserThreadStart+21
    Params: '00000000 '00000000 '00000000 '00000000


RAX:2e'efc4d0de RBX:9000e4ff'c2f43e7d RCX:'00000022 RDX:2e'efc4ce20 RSI:2e'efc4de78 RDI:2e'efc4d0c0
R8:'00000004 R9:1bb'f5510000 R10:2e'efc4ce20 R11:2e'efc4d0de
R12:2e'efc4e440 R13:1bb'885756c0 R14:2e'efc4d0c0 R15:2e'efc4e440
EIP:1bb'f55847c5 ESP:2e'efc4cdf0 EBP:2e'efc4cf20
CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:'00010202

[crash.zip](https://github.com/beefytech/Beef/files/4499800/crash.zip)

**Comment by damianday** [comment]
All I did was refactor some code, go to recompile and it blew up, tried to undo those changes but still happening

**Comment by bfiete** [comment]
- Execute an instance of BeefIDE_d.exe from the "Debug / Launch Process..." from another BeefIDE instance.
- When it crashes, select the 'BeMCContext::Generate(Beefy::BeFunction* function)' call on the callstack at line 16311.  
- Type in 'mBeFunction.mName' - this is the mangled name of the function being compiled
- Type in '((Beefy::BeFunction*)castedInst.mFunc).mName' this is the function which is being called incorrectly

Presumably that information will help you build a minimal repro case, or may be obvious what's going on...

**Comment by damianday** [comment]
I can reproduce it with the below, I do a Clean and then Build and it crashes.

```
typealias RectanglePx = Rectangle<int>;

public struct Rectangle<T> where T : IOpAddable
{
	private T _x = default(T);
	private T _y = default(T);
	private T _width = default(T);
	private T _height = default(T);

	public this(T x, T y, T width, T height)
	{
		_x = x;
		_y = y;
		_width = width;
		_height = height;
	}
}

class Program
{
	public static int Main(String[] args)
	{
		let rc = RectanglePx(0, 0, 100, 100);

		return 0;
	}
}
```

**Comment by bfiete** [comment]
Great repro. And fixed: https://github.com/beefytech/Beef/commit/33448603b1dbf93922defe125bfec6688dff4a24

**Comment by damianday** [comment]
Thanks, was easy to find after trying your advice 😉
