### ISSUE TITLE
`Type.GetMethods` doesn't respect `bindingFlags` in Comptime

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1242]
In comptime, I'm iterating `System.Console` methods using `type.GetMethods(.Public | .Static)`, which should only iterate over public static methods, but for some reason it also ends up iterating over extern private methods like `SetConsoleTextAttribute`

**Comment by disarray2077** [comment]
Actually, this also happens with `OpenStreamWriter`, so I guess this isn't about `extern`... So I guess the visibility filter isn't working at all?

**Comment by bfiete** [comment]
Nope, that's just not implemented at all (yet).

**Comment by bfiete** [comment]
Implemented at b7e5d3fda5d8c7bfa2124cbbdbc1634c09954d11
