### ISSUE TITLE
typeof(T) isn't constant anymore

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1243]
The below code used to work before the const changes but now it says that `typeof(T)` isn't constant, maybe it's a regression caused by https://github.com/beefytech/Beef/commit/a7da8a75d69f1ec6826e3450065f4e73642f6cd8? 😅 
```
	static
	{
		public typealias RemovePtr<T> = comptype(RemovePtr(typeof(T))); // ERROR: Non-constant argument for param 'type'

		[Comptime]
		public static Type RemovePtr(Type type)
		{
			if (type.IsPointer)
				return type.UnderlyingType;
			return type;
		}
	}
```

**Comment by bfiete** [comment]
Fixed at c52ef256a541ab380aa7ab06e2b0a1148176633e
