### ISSUE TITLE
field destructor ignored in specific cases & other specific bugs

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1247]
(tested with c5e2b78, currently newest)

I've mailed you a collection of projects again for some otherwise hard to replicate bugs. Open the workspace of the "Cavex" project. (Atma.Json also needs to be installed or added manually)

1: When opening the project in the debug IDE (also maybe try compiling in this mode, when this first one is fixed, maybe there's more?), a ``BF_ASSERT`` will fail. In ``EmitDtorBody()``, the types for the dtor's declaring type and the field's declaring type are named the same, but different instances apparently? so they are asserted to be partials, but arent (there is only one definition in the code too, so that is correct, it is no partial). It's at ``BfModule.cpp:15973``

This may fix the behaviour below (seems related at least, this is what i primarily wanted to report):

Until recently i was on a nightly version from maybe 3 weeks ago. Since upgrading to the new release, i get 4 or variably 5 memory leaks of things that were, and should still be, deleted.
Repro: Run the program, close the window.

~~2: [comptime] type body emit edit crashes~~ you just fixed it while i was writing this

3: [codegen??] weird debug break when moving in a specific way, then ``ACCESS VIOLATION`` crash on continue, no message pops up on initial break.
Repro: In the game (press F1 to see exact collision), a demonstration gif is inside the zip. Description: go onto the top of the first platform of tiles on the right, that overlap the other non-tile hitbox. Then, from the right edge of the continuous row of tiles, press down and left to slide over the platform. Before leaving contact with the platform left to the non-tile bound hitbox, the debug break should occur on the "CheckMove" call. Pressing F10 a few times, or F5 will crash.

4: [PerfTrack] (as seen in ``GameScene`` on ``Tick()`` for example) now sometimes errors with "Method not generated in comptime..." (just ghost error, not preventing compile), still weird
Repro: This sometimes shows up randomly. ATM it consistently occurs when cleaning while the file containing ``CollisionSystem:Resolve()`` is open and cleaning (and waiting for comptime to finish - aka when the wall of errors is gone). If it doesnt show up, put some nonsense inside the function, like putting ``dddd`` in front of a method call, then undo it, then clean again. If it still doesnt, switch to another panel and hover over some stuff, switch back and clean. There's a chance it works, when in doubt, clean again. Alternative error i just got with this: "Invalid virtual method target in comptime System.String.Append(char8* appendPtr, int length at ...)", root of the trace is "methodInfo.ToString(sectionName);" in Pile: ``Perf.bf`` (navigate to ``Perf``, above the class) line 68.

5: [visual] readonly assignment in this {} block has squiggles on = in the ide
Repro: navigate to CollisionSystem, inside the "this" block, hover over the = if it doesnt already have squiggles. Error shown: Cannot assign to readonly field '...' within method '..._BfInit()' (but of course it still does)
This does not happen on this()/constructors.

**Comment by EinScott** [comment]
Highliting is also somewhat broken or at least indefinitly delayed it seems?
Some methods are only highlited when placing the cursor near them, and placed attributes and things like Debug just stay white forever. Also, classes just have the struct color.

This should also reproduce with the project, noticable in ComponentSerializer and CollisionSystem (and probably others?)

**Comment by bfiete** [comment]
3) `Edge` is a bitset, and in this breaking case you have `.Left | .Bottom`. In `Edge.Inverse` you don't have a `default:` case but the switch think it's "exhaustive" so that missed case of `.Left | .Bottom` hits an "unreachable" instruction. If you remove `[Optimize]` from `CheckMove` then you'll have a clean break in the `Inverse` method, but with `[Optimize]` you get a less friendly break that's actually located outside the reported function code space.

**Comment by EinScott** [comment]
Ohh i see, i totally missed that while changing it to report multiple edges. It still was a bit confusing to just hit a break without a breakpoint or message/error at all, but i guess i also should have thought of debugging without [optimize], thanks!

**Comment by bfiete** [comment]
1, 4, and 5 fixed at ed06ff4dce35afb2170bd1e8f31f95dd29c45226
Fixed hiliting issues at 7691c414c3787cc097d4d8084ae2d4eb3be647cd
