### ISSUE TITLE
IDE crash 2

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#125]
Happened after removing a dependency in project settings then, selecting the dependency in the workspace view and pressing delete to remove from workspace.

[crash.zip](https://github.com/beefytech/Beef/files/4500238/crash.zip)

Exception: Access Violation (code 0xc0000005) at address 7ffe'515e72a6 in thread 24E0
Executable: C:\beef\IDE\dist\BeefIDE.exe
File Version: 0.42.2
Product Version: 0000000000000000

Logical Address: 0001:'000062a6

50'7e10f590 7ffe'515e72a6 ntdll.dll RtlDllShutdownInProgress+C6
    Params: 7ff6'0bde4fc0 1f4'8cd7fe40 'fffffffa 1f4'858a9c2f

50'7e10f5f0 7ffe'515fb576 ntdll.dll RtlEnterCriticalSection+1F6
    Params: 7ff6'0bde4fc0 50'7e10f7e0 1f4'8ccbbba0 7ff6'0baca9f4

50'7e10f620 7ffe'515fb3c0 ntdll.dll RtlEnterCriticalSection+40
    Params: '00000001 1f4'8498aa12 1f4'8ccbbdc0 1f4'9511eb60

50'7e10f660 7ff6'0bc94fa5 BeefIDE.exe System.Threading.Monitor.Enter+15
    at c:\Beef\BeefLibs\corlib\src\Threading\Monitor.bf:38
    Params: 1f4'8cfa16e0 1f4'00000000 1f4'8ccbbba0 1f4'8cd7b7a0

50'7e10f8c0 7ff6'0bac7e0f BeefIDE.exe IDE.Compiler.BfCompiler.DoProcessQueue+90F
    at c:\Beef\IDE\src\Compiler\BfCompiler.bf:453
    Params: '00000000 7ffe'4e9ec2c7 1f4'8cfa16e0 7ff6'0bc35ce6

50'7e10f930 7ff6'0bb2ca87 BeefIDE.exe IDE.ThreadWorkerContext.DoBackground$Qm+E7
    at c:\Beef\IDE\src\CommandQueueManager.bf:47
    Params: 1f4'8cfa2d60 50'7e10f988 1f4'8cfa16e0 50'7e10f988

50'7e10fa20 7ff6'0bc9719f BeefIDE.exe System.Threading.ThreadPool.WorkerProc+15F
    at c:\Beef\BeefLibs\corlib\src\Threading\ThreadPool.bf:174
    Params: '00000000 '00000000 '00000000 '00000002

50'7e10fa60 7ff6'0bc97420 BeefIDE.exe System.Threading.Thread.RuntimeThreadInit.Thread_StartProc+60
    at c:\Beef\BeefLibs\corlib\src\Threading\Thread.bf:79
    Params: '00000000 '00000000 '00000000 '000006b0

50'7e10fa90 7ffe'469a3d7d Beef042RT64.dll CStartProc+8D
    at c:\beef\beefrt\rt\thread.cpp:129
    Params: 1f4'8cdf4930 '00000000 '00000000 '00000000

50'7e10fac0 7ffe'50e97bd4 KERNEL32.DLL BaseThreadInitThunk+14
    Params: '00000000 '00000000 '00000000 '00000000

50'7e10fb40 7ffe'5164ce51 ntdll.dll RtlUserThreadStart+21
    Params: '00000000 '00000000 '00000000 '00000000

RAX:'00000000 RBX:1f4'8ce42780 RCX:1f4'8ce42780 RDX:'fffffffa RSI:'00000000 RDI:'00000000
R8:'00000000 R9:1f4'8ce42700 R10:7ff6'0bde4fa8 R11:1f4'9511eb50
R12:'00000000 R13:50'7d367000 R14:'00000001 R15:'00000000
EIP:7ffe'515e72a6 ESP:50'7e10f4c0 EBP:50'7e10f700
CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:'00010213

**Comment by bfiete** [comment]
These crash dumps are of pretty limited use when you're building yourself unless you post your BeefIDE.exe/pdb and IDEHelper64.dll/pdb.

I'll see if I can reproduce something like that from your instructions, though.

**Comment by bfiete** [comment]
Ah, that was pretty easy to find. Fixed by https://github.com/beefytech/Beef/commit/2b6e1d0d5d0964f31bb32bda6d5a62bcbd22d6a6
