### ISSUE TITLE
IDE hangs when there's a large amount of raw memory leaks

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1251]
The following code causes the leak report to hang the IDE:
```
			for (var i < 184000)
			{
				new uint8[8]*;
			}
```

_**EXTRA:**_ If you try to debug the non-responding IDE, the IDE you're using to debug it becomes painfully slow.

**Comment by bfiete** [comment]
Fixed at 09bf85ad0e4155aec405978bb9019462819d4fff
