### ISSUE TITLE
[Enhancement] Allow embedding files directly in the executable

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1254]
It would be nice to be able to do something like

```c#
uint8[?] fileContents = __magicEmbedFile("example.txt");
```

And the compiler would then read the entirety of the file, and place it into the array every time you compile, as if you had typed it out yourself:

```c#
uint8[?] fileContents = .(0xDE,0xAD,0xBE,0xEF, ... );
```

There is already a tool that generates beef code like this: https://github.com/Booklordofthedings/BeefBrand, but it would be better if this was built into the language - then you don't have to run this tool every time the file changes or something.

Note that this isn't possible to do with Comptime because file IO doesn't work at comptime.

I think Windows resources were already requested before in #717, but with something like this we wouldn't need them at all - and it would work on all platforms.

**Comment by bfiete** [comment]
Supported at ce4b6e04de2b68d4692be6487f8f00f3440bffb9
`const uint8[?] cTest0Binary = Compiler.ReadBinary("Test0.txt");`

`ReadBinary` is mostly just a call to `File.ReadAll` - we have file IO support in comptime now, as well as process spawning.
