### ISSUE TITLE
[Crash] Instant crash when static int used as array count

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1257]
Super easy to reproduce - just paste the following code somewhere and the IDE will instantly crash.

```c#
namespace Crash
{
	class Moo
	{
		static int N;
		int[N] x;
	}
}
```

It looks like it only crashes specifically when `N` is `int` - not `int32`/`int64`/`float` etc, and it also needs to be `static`. The type of `x` doesn't seem to matter.

Tested with 46fbba9, but also happens in the 0.43.1 release.

**Comment by bfiete** [comment]
Fixed at ff54f3ce9cb9f405a8ae40dafa787a964dcf23ec
