### ISSUE TITLE
0.42.2 IDE Crash

### ISSUE THREAD

**Issue by jhenzie** [beefytech/Beef#126]
Crash minidump saved as C:\Program Files\BeefLang\bin\CrashDumps\BeefIDE_20200424_151730.dmp

Exception: Access Violation (code 0xc0000005) at address 7ff7'003c7e1f in thread 1DE0
Executable: C:\Program Files\BeefLang\bin\BeefIDE.exe
File Version: 0.42.2
Product Version: 905330ce12cd1f1cb9435463d8ab08c06d6d2451

Logical Address: 0001:'00006e1f

cc'04afeda0 7ff7'003c7e1f 0001:'00006e1f BeefIDE.exe
    Params: cc'04aff080 cc'04afef50 '00000001 1f1'f7a6ae30

cc'04afeee0 7ff7'003d14be 0001:'000104be BeefIDE.exe
    Params: cc'04aff228 7ff7'003d0e95 '00000001 cc'04aff110

cc'04aff0b0 7ff7'003d2d25 0001:'00011d25 BeefIDE.exe
    Params: '00000000 7ff7'0055b69a cc'04aff288 7ff7'00607ea0

cc'04aff190 7ff7'003f77fb 0001:'000367fb BeefIDE.exe
    Params: '00000000 7ff7'005e32d9 1f1'f78ba360 '00000000

cc'04aff1e0 7ff7'00436334 0001:'00075334 BeefIDE.exe
    Params: 1f1'f78a9870 7ff8'13a5fb91 1f1'f78a9870 1f1'eef80000

cc'04aff320 7ff7'00458508 0001:'00097508 BeefIDE.exe
    Params: 'ef152401 1f1'f7807d98 1f1'ef006310 cc'04aff440

cc'04aff4c0 7ff7'004504ae 0001:'0008f4ae BeefIDE.exe
    Params: cc'04aff530 cc'04aff510 cc'04aff510 7ff7'003c6ea2

cc'04aff560 7ff7'00440553 0001:'0007f553 BeefIDE.exe
    Params: 1f1'f7c15850 'f7a83701 1f1'f7ae0720 '00000000

cc'04aff5e0 7ff7'00473a5e 0001:'000b2a5e BeefIDE.exe
    Params: '44658000 '00000000 '00000000 1f1'f7ad1b70

cc'04aff6a0 7ff7'004f638c 0001:'0013538c BeefIDE.exe
    Params: '00000000 cc'04aff750 cc'04aff740 7ff7'0059efe8

cc'04aff710 7ff7'003ebd3f 0001:'0002ad3f BeefIDE.exe
    Params: '00000000 '00000000 '00000000 1f1'f325a840

cc'04aff7b0 7ff7'0059edcd 0001:'001dddcd BeefIDE.exe
    Params: '00000000 '00000000 '00000000 '00000000

cc'04aff840 7ff7'00404423 0001:'00043423 BeefIDE.exe
    Params: 7ff8'11a01324 '000002e9 '00000000 7ff7'003c32fe

cc'04aff8a0 7ff7'00405bd1 0001:'00044bd1 BeefIDE.exe
    Params: '001007f4 '001007f4 '00000202 7ff8'0f609810

cc'04aff940 1'8002bcd5 BeefySysLib64.dll BFApp_RunPerfTest+4655
    Params: '00000000 '001007f4 '00000202 '00000000

cc'04aff980 1'8002c2ea BeefySysLib64.dll BFApp_RunPerfTest+4C6A
    Params: '00000001 '00000000 '00000000 '00000000

cc'04affb10 7ff8'12b45c0d USER32.dll CallWindowProcW+3BD
    Params: 1f1'f14b8b70 1'8002c2a0 '001007f4 cc'04affbd0

cc'04affb90 7ff8'12b45602 USER32.dll DispatchMessageW+1F2
    Params: 1'8002c2a0 1f1'eef882b0 1f1'ef006310 10001f1'ef01df00

cc'04affc00 1'8002c7b6 BeefySysLib64.dll BFApp_RunPerfTest+5136
    Params: '00000001 '00000000 '00000000 '00000000

cc'04affc40 7ff7'0045df2e 0001:'0009cf2e BeefIDE.exe
    Params: 1f1'eef99370 7ff7'00000022 1f1'eef847fa 1f1'eef99f5a

cc'04affc80 7ff7'005f4426 0001:'00233426 BeefIDE.exe
    Params: '00000001 '00000000 '00000000 '00000000

cc'04affcc0 7ff7'005f46ae 0001:'002336ae BeefIDE.exe
    Params: '00000000 '00000000 '00000000 '00000000

cc'04affcf0 7ff8'12cf7bd4 KERNEL32.DLL BaseThreadInitThunk+14
    Params: '00000000 '00000000 '00000000 '00000000

cc'04affd70 7ff8'13a8ce51 ntdll.dll RtlUserThreadStart+21
    Params: '00000000 '00000000 '00000000 '00000000

RAX:'00000000 RBX:'00000000 RCX:1f1'f7c15b30 RDX:'0000003f RSI:'00000000 RDI:'00000001
R8:cc'04afef20 R9:'00000038 R10:'00000001 R11:'00000049
R12:1f1'f78ba360 R13:cc'04afed28 R14:'00000038 R15:cc'04afed20
EIP:7ff7'003c7e1f ESP:cc'04afed00 EBP:'00000049
CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:'00010206

Occured when trying to set a new font in the Settings Properties window
Deleted all the other fonts in the font list and set font #! to fonts/SourceCodePro-Medium

Crash occured on clicking [Apply]  

Crash dump attached.

[BeefIDE_20200424_151730.zip](https://github.com/beefytech/Beef/files/4529445/BeefIDE_20200424_151730.zip)

**Comment by jhenzie** [comment]
This appears to occur if the font #1 is not recognized by the ide.  I have source code pro installed but setting the font causes the crash,

Note setting the font to Consolas succeeded.

**Comment by HydrogenC** [comment]
I also have a issue related to the font. 
The default font will cause the text in the bottom panels to overlap and cannot be recognized. Switching the font to 'Consolas' fixes this.

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/d6a4b8b62c9472cfac26a7dc33c539f06f8bd827. Will be in release 0.42.3.
