### ISSUE TITLE
[BUG] Compiler crash during debug build - release build works fine

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1265]
I've been working on a win32 api projection - basically a library that imports all the various win32 apis.

But I get a fatal error from the compiler when I try to build it in debug mode:

```
CrashCatcher::Crash
FATAL ERROR

mBeContext->AreTypesEqual(varType, initializer->GetType()) in C:\Users\Boris\Desktop\Beef\IDEHelper\Backend\BeIRCodeGen.cpp:1928
```

This is what that looks like from the IDE:

![Capture](https://user-images.githubusercontent.com/55242398/145487027-a11b9970-a69a-4ceb-9d06-a40f78b74b41.PNG)

Strangely enough the whole thing compiles and runs fine in release mode.

I attached the whole project as a repro case ([Test.zip](https://github.com/beefytech/Beef/files/7688904/Test.zip)). Sadly it's a massive codebase - if it's too difficult to find any problems because of the size then I can try to make a smaller repro case, but the whole thing is a tangled mess so removing anything from it is gonna be difficult.

Tested with 195c705.

Oh yea, and also as a side note - it takes 33 seconds to compile this in debug mode, and I feel like that's way too much. There's no actual code in there, it's just a bunch of type defs and dll imports. And the whole IDE is incredibly unresponsive with it.

**Comment by bfiete** [comment]
Fixed by 5c08c3716c69a890ad2202dd76e15e7804ddf460 (and a few commits preceding that)
