### ISSUE TITLE
[IDE][BUG] Crash when declaring function that returns an array.

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1267]
If you paste this function declaration in any namespace the IDE immediately enters a crash loop:

```c#
int[ Foo(int x) { return null; } // Note the int[ instead of int[].
```

![crash](https://user-images.githubusercontent.com/55242398/145673479-5447d0a8-328d-4cb2-9ede-483ac55c4a28.png)

It looks like it only happens if the function has at least 1 argument:

```c#
int[ Foo() { return null; } // works
int[ Foo(int x) { return null; } // crash
int[ Foo(int x, int y) { return null; } // crash
```

Here's a repro project: [Crash.zip](https://github.com/beefytech/Beef/files/7696802/Crash.zip)

Crashdump: [crashdump.zip](https://github.com/beefytech/Beef/files/7696805/crashdump.zip)

Tested with 195c705.

**Comment by bfiete** [comment]
Fixed at 06d896330d61a53a284ecebe98049dfb413c799e
