### ISSUE TITLE
Unable to build examples 0.42.2 

### ISSUE THREAD

**Issue by kolombet** [beefytech/Beef#127]
Hi! 
Trying to build space game example after clear installation of beef. 
Beef IDE unable to compile without visual studio tool (no debugging) 
Is this correct behavior? Didn't see any requirements to install visual studio in installation guide
The [requirements ](https://www.beeflang.org/docs/getting-start/building/)of C++ build tools only for building beef, am I correctly understand? 
```
Compiling...
Beef compilation time: 0.32s
515 modules built, 515 object files generated
ERROR: Visual Studio tool path not configured. Check Visual Studio configuration in File\Preferences\Settings.
Compile failed.
Executing Command: CopyToDependents("$(ProjectDir)/dist/*.dll")
Command Time: 0.02s
Total build time: 0.36s
```

**Comment by bfiete** [comment]
Visual Studio Build Tools are required for linking: https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019

**Comment by kolombet** [comment]
Thanks for information. 
But still problem with compilation. 

`Compiling...
Beef compilation time: 2.49s
ERROR: Module 'vdata' failed during codegen with: Failed to write object file: C:\Program Files\BeefLang\Samples\SpaceGame/build/Debug_Win64/SpaceGame/vdata.obj
ERROR: Failed to write lib file 'C:\Program Files\BeefLang\Samples\SpaceGame/build/Debug_Win64/corlib/corlib__.lib'
ERROR: Failed to write lib file 'C:\Program Files\BeefLang\Samples\SpaceGame/build/Debug_Win64/SpaceGame/SpaceGame__.lib'
ERROR: Failed to write lib file 'C:\Program Files\BeefLang\Samples\SpaceGame/build/Debug_Win64/SDL2/SDL2__.lib'
515 modules built, 514 object files generated
Errors: 4.
Compile failed.
`

Compilation failed, then if I try to close IDE, it shows crash log
`Exception: Access Violation (code 0xc0000005) at address '00000000 in thread 437C
Executable: C:\Program Files\BeefLang\bin\BeefIDE_d.exe
File Version: 0.42.2
Product Version: 905330ce12cd1f1cb9435463d8ab08c06d6d2451

Logical Address: 0000:'00000000

bc'018fbd90 '00000000 0000:'00000000 
    Params: 1ed'a66d0b50 '00000000 cccccccc'cccccccc cccccccc'cccccccc

bc'018fce40 1'00092de6 BeefySysLib64_d.dll BFApp_RunPerfTest+11946
    Params: 1ed'a66d0b50 '0004063a bc'00000008 '00000000

bc'018fcf70 1'00093887 BeefySysLib64_d.dll BFApp_RunPerfTest+123E7
    Params: '0004063a '00000008 '00000000 '00000000

bc'018fd100 7fff'38a55c0d USER32.dll CallWindowProcW+3BD
    Params: '00000388 1'00093800 '0004063a '80000000

bc'018fd160 7fff'38a557dc USER32.dll DispatchMessageW+3CC
    Params: '00000000 '00000000 '00000000 '0000437c

bc'018fd1c0 7fff'38a61f73 USER32.dll IsWindowVisible+1A3
    Params: 1ed'99820528 bc'018fd2c0 1ed'a7f29020 '00012012

bc'018fd248 7fff'3a25fde4 ntdll.dll KiUserCallbackDispatcher+24
    Params: 7fff'38a6bc77 '00010003 '00000000 '00000000

bc'018fd250 7fff'372a8024 win32u.dll NtUserCallHwndParamLockSafe+14
    Params: '00010003 '00000000 '00000000 '00000002

bc'018fd2b0 7fff'38a6bc77 USER32.dll DialogBoxIndirectParamAorW+107
    Params: '00010003 bc'018fd3c0 bc'018fd5e0 1ed'a7f29020

bc'018fd400 7fff'38ab2f99 USER32.dll SoftModalMessageBox+7E9
    Params: bc'00000000 1'00000111 '000002f0 1'00000032

bc'018fd5b0 7fff'38ab19d5 USER32.dll DrawStateA+1C45
    Params: 7fff'00000000 '00000010 '0000000e '00000800

bc'018fd6b0 7fff'38ab2712 USER32.dll MessageBoxTimeoutW+192
    Params: fff37e4'9db5d44d fff366e'1cdfd44d 1'003e5658 1'002ea604

bc'018fd6f0 7fff'38ab279e USER32.dll MessageBoxW+4E
    Params: d17a'f9cfd44d '00000000 7fff'38a51040 1'002ea3aa

bc'018fd740 7fff'34f323ff apphelp.dll SE_WINRT_HookObject+157F
    Params: '00000265 '00000225 bc'018fdd50 1'002eb5f3

bc'018fd790 1'002eb393 BeefySysLib64_d.dll PerfTimer_ZoneStart+B9873
    Params: '0004063a bc'018fd8d0 1'003c8410 d1c6'00012012

bc'018fd7c0 1'002d444d BeefySysLib64_d.dll PerfTimer_ZoneStart+A292D
    Params: bc'018fd808 bc'018fd820 bc'018fd828 bc'018fd830

bc'018fd810 1'002d4313 BeefySysLib64_d.dll PerfTimer_ZoneStart+A27F3
    Params: bc'018fd8d0 1'003c8410 '00012012 '00000000

bc'018fd840 1'002d44f7 BeefySysLib64_d.dll PerfTimer_ZoneStart+A29D7
    Params: bc'018fd8d0 1'003c8410 d1c6'00012012 cccccccc'cccccccc

bc'018fd870 1'002b5c7d BeefySysLib64_d.dll PerfTimer_ZoneStart+8415D
    Params: bc'018fd8d0 bc'018fd8c0 bc'018fd8b4 1ed'a9b389c0

bc'018fdd60 1'002b3cbe BeefySysLib64_d.dll PerfTimer_ZoneStart+8219E
    Params: 1ed'a9319ca0 1ed'a9b389c0 cccccccc'000000fb 1'000a6732

bc'018fdda0 1'002b3b13 BeefySysLib64_d.dll PerfTimer_ZoneStart+81FF3
    Params: 1ed'a9319ca0 1ed'a9b389c0 cccccccc'000000fb 1'000a6732

bc'018fddd0 1'002b648f BeefySysLib64_d.dll PerfTimer_ZoneStart+8496F
    Params: 1ed'a9319ca0 1ed'a9b389c0 '000000fb 1'00000000

bc'018fdf70 1'000a6732 BeefySysLib64_d.dll BFApp_RunPerfTest+25292
    Params: bc'018fe098 bc'018fe068 cccccccc'000000fb cccccccc'cccccccc

bc'018fe110 1'0000e819 BeefySysLib64_d.dll BFSoundManager_LoadSound+29E9
    Params: 1'00337740 1'003376e0 '000000fb bc'018fe6d8

bc'018fe6e0 1'0008a58b BeefySysLib64_d.dll BFApp_RunPerfTest+90EB
    Params: 1ed'a66d0b50 1ed'a16f83f0 bc'018fe9b8 cccccccc'0000025d

bc'018fe880 1'0008c53f BeefySysLib64_d.dll BFApp_RunPerfTest+B09F
    Params: 1ed'99903c20 1ed'a16f83f0 bc'018fe9b8 cccccccc'00000265

bc'018fe9f0 1'0000888d BeefySysLib64_d.dll BFApp_CreateWindow+9D
    Params: 1ed'a16f83f0 1ed'a40f5558 bc'00000265 1ed'00000225

bc'018fec70 7ff6'886ac882 0001:'001bb882 BeefIDE_d.exe
    Params: 1ed'9cc2c300 1ed'9cc2c180 bc'018feeb0 1ed'a40f5540

bc'018fed10 7ff6'886add10 0001:'001bcd10 BeefIDE_d.exe
    Params: 1ed'9cc2c300 1ed'9cc2c180 bc'018feeb0 1ed'a40f5540

bc'018fedc0 7ff6'886fe409 0001:'0020d409 BeefIDE_d.exe
    Params: 1ed'9cc2c300 1ed'a40f0e40 bc'018feeb0 1ed'9cc2c300

bc'018feea0 7ff6'886a693d 0001:'001b593d BeefIDE_d.exe
    Params: bc'018ff1ef bc'018ff150 bc'018ff150 7ff6'887aafcb

bc'018ff110 7ff6'885b0bd2 0001:'000bfbd2 BeefIDE_d.exe
    Params: 1ed'9b2d0000 1ed'9c409840 '00000030 bc'018ff302

bc'018ff300 7ff6'885c7208 0001:'000d6208 BeefIDE_d.exe
    Params: '00000048 7fff'00000001 '00000000 '00000000

bc'018ff580 7ff6'8864a2ce 0001:'001592ce BeefIDE_d.exe
    Params: cccccccc'cccccccc cccccccc'cccccccc cccccccc'cccccccc cccccccc'cccccccc

bc'018ff750 7ff6'885de42d 0001:'000ed42d BeefIDE_d.exe
    Params: 1ed'9b2a0f00 1ed'9b2a0f00 '00000000 '00000000

bc'018ff7a0 7ff6'884f438b 0001:'0000338b BeefIDE_d.exe
    Params: '00000000 '00000000 '00000000 '00000000

bc'018ff7d0 7ff6'884f14ad 0001:'000004ad BeefIDE_d.exe
    Params: '00000001 7ff6'888218d9 '00000000 '00010001

bc'018ff810 7ff6'884f19eb 0001:'000009eb BeefIDE_d.exe
    Params: '00000000 7ff6'887fe2fd '00000000 7ff6'88899120

bc'018ff850 7ff6'887fdc3d 0001:'0030cc3d BeefIDE_d.exe
    Params: 7ff6'88899000 7ff6'888990e8 '00000000 '00000000

bc'018ff8c0 7ff6'887fdb6e 0001:'0030cb6e BeefIDE_d.exe
    Params: '00000000 '00000000 '00000000 '00000000

bc'018ff8f0 7ff6'887fda2e 0001:'0030ca2e BeefIDE_d.exe
    Params: '00000000 '00000000 '00000000 '00000000

bc'018ff920 7ff6'887fdcb9 0001:'0030ccb9 BeefIDE_d.exe
    Params: '00000000 '00000000 '00000000 '00000000

bc'018ff950 7fff'38917bd4 KERNEL32.DLL BaseThreadInitThunk+14
    Params: '00000000 '00000000 '00000000 '00000000

bc'018ff9d0 7fff'3a22ce51 ntdll.dll RtlUserThreadStart+21
    Params: '00000000 '00000000 '00000000 '00000000


RAX:1ed'a66d0b50 RBX:'00000001 RCX:1ed'a66d0b50 RDX:'00000000 RSI:'00000000 RDI:bc'018fce30
R8:'00000008 R9:'00000000 R10:1ed'99d7fe30 R11:'00000000
R12:'00000008 R13:'0004063a R14:'00000000 R15:'00000000
EIP:'00000000 ESP:bc'018fbd98 EBP:bc'018fbdd0
CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:'00010246
`

**Comment by kolombet** [comment]
I suppose problem was with write protection. Examples were in program files, and you can't write there without admin rights.
I tried to move sample project in other directory, got these errors: 
`
Compiling...
Beef compilation time: 0.02s
Executing Command: CopyToDependents("$(ProjectDir)/dist/*.dll")
Executing: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\Hostx64\\x64/link.exe" -out:c:\beefsamples\Samples\SpaceGame\dist\SpaceGame_d.exe -subsystem:windows C:\beefsamples\Samples\SpaceGame/build/Debug_Win64/corlib/corlib__.lib C:\beefsamples\Samples\SpaceGame/build/Debug_Win64/SDL2/SDL2__.lib C:\beefsamples\Samples\SpaceGame/build/Debug_Win64/SpaceGame/SpaceGame__.lib C:\beefsamples\Samples\SpaceGame/build/Debug_Win64/SpaceGame/vdata.obj -defaultlib:libcmtd "c:\Program Files\BeefLang\BeefLibs\SDL2\dist\SDL2.lib" "c:\Program Files\BeefLang\BeefLibs\SDL2\dist\SDL2_ttf.lib" "c:\Program Files\BeefLang\BeefLibs\SDL2\dist\SDL2_image.lib" "c:\Program Files\BeefLang\BeefLibs\SDL2\dist\SDL2_mixer.lib" -nologo -incremental:no -pdb:c:\beefsamples\Samples\SpaceGame\dist\SpaceGame_d.pdb -debug -opt:noref -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64" -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64" -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64" -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64" -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64" -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64" -libpath:"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\lib\x64" -libpath:"C:\Program Files\BeefLang\bin\lib\x64" -libpath:c:\beefsamples\Samples\SpaceGame\dist Beef042RT64.lib Beef042Dbg64.lib 
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
Execution time: 0.06s
Execution Failed
ERROR: BUILD FAILED
Total build time: 0.14s
`

**Comment by bfiete** [comment]
Does the latest version work for you?
