### ISSUE TITLE
[IDE][Enhancement] IDE shouldn't append .bf suffix to new file name if it already has it.

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1270]
When I add a new class from the IDE and call it "Foo.bf", the IDE will still add the .bf suffix to it, resulting in Foo.bf.bf being made.

The IDE should check whether the filename I entered already contains .bf, and only add the suffix if it doesn't already have it.

**Comment by bfiete** [comment]
Fixed at 73099e4a04f5674bbf46ff57d0acdb7d9f70cd17
