### ISSUE TITLE
`AssertErrorState` crash

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1272]
The pull request https://github.com/beefytech/Beef/pull/1134 makes the BeefBuild crash while compiling the IDE

Tested with https://github.com/beefytech/Beef/commit/cb6f88b047da0d067f47fb0a559940683ce22473

**Comment by bfiete** [comment]
Fixed at 9517b3a9d5753cb70f6c73278dc2244f598564a5

**Comment by disarray2077** [comment]
@bfiete It still is crashing, looks like at least one more null check is needed:
![image](https://user-images.githubusercontent.com/86157825/145693365-8b1bdcc0-af72-4750-a3f6-596563b10f2d.png)

**Comment by bfiete** [comment]
The null check is fixed at d0f083446310c8fd2423ee3bf66eaf5a571625c4 at least.
But yeah. This `AssertErrorState` method is a check for when the compiler is in a state that should only be possible if the program has an error, and in this case there wasn't an error which means there's a compiler bug somewhere else...
