### ISSUE TITLE
Assert failed "mCompiler->mPassInstance->HasFailed()"

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1275]
As discovered when https://github.com/beefytech/Beef/issues/1272 was solved, the assert mentioned in the issue title fails while compiling the IDE with the pull request #1134.

Tested with cb6f88b

**Comment by bfiete** [comment]
Fixed at c59fac571a7e02d78ffaff9e2df82334f262329f
The issue was with a function with a ref to the opaque `PROPERTYKEY`. Usually we know the size of `ref` values but we don't when they are opaque - which is not illegal, just an unhandled case.
