### ISSUE TITLE
Wrong "value doesn't fit into int64" error

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1281]
The value `-9223372036854775808L` does fit int64, but the IDE gives an error anyway.

Meanwhile, `9223372036854775808` doesn't fit int64 but it compiles and overflows:
![image](https://user-images.githubusercontent.com/86157825/146219498-d00f0b64-ff2b-43f4-9ffc-c361b1eeeee1.png)

**Comment by bfiete** [comment]
Should be fixed at a3b761ab266f13292cd067abf3b10a091c4ff392
