### ISSUE TITLE
[BUG?] Boxed interface binding error to emitted method when using comptime code generation

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1283]
It works when the `ISerializable` interface is implemented manually

Code to reproduce:
```
using System;

class SerializationContext
{
	public void Serialize<T>(String name, T val) where T : struct
	{
	}
}

interface ISerializable
{
	void Serialize(SerializationContext ctx);
}

[AttributeUsage(.Enum | .Struct | .Class, .NotInherited | .ReflectAttribute | .DisallowAllowMultiple)]
struct SerializableAttribute : Attribute, IComptimeTypeApply
{
	[Comptime]
	public void ApplyToType(Type type)
	{
		const String SERIALIZE_NAME = "void ISerializable.Serialize(SerializationContext ctx)\n";

		String serializeBuffer = new .();

		Compiler.Assert(!type.IsUnion);

		for (let field in type.GetFields())
		{
			if (!field.IsInstanceField || field.DeclaringType != type)
				continue;

			serializeBuffer.AppendF($"\n\tctx.Serialize(\"{field.Name}\", {field.Name});");
		}

		Compiler.EmitTypeBody(type, scope $"{SERIALIZE_NAME}{{{serializeBuffer}\n}}\n");
	}
}

namespace Tests
{
	[Serializable]
	struct Foo : this(float x, float y), ISerializable
	{
	}

	public class ComponentHandler<T>
		where T : struct
	{
		uint8* data;
		protected override void GCMarkMembers()
		{
			T* ptr = (T*)data;
			GC.Mark!((*ptr));
		}
	}

	class Program
	{
		static void Main()
		{
			Foo bar = .(10, 2);
			let handler = scope ComponentHandler<Foo>();
		}
	}	
}
```

Tested with: (Nightly 12/13/2021)

**Comment by bfiete** [comment]
Fixed at 2932fceae4b905bf70d2b9a795f769fbf66e8cba

Hm. It would be nice if there were a `Compiler.EmitAddInterface(type, "ISerializable")`, so users could just use the attribute alone, eh?

**Comment by bfiete** [comment]
It was such a nice idea that I did it at 612368b0f7750f54c6074860eac11dfbb20fa37d
Now you can do `Compiler.EmitAddInterface(type, typeof(ISerializable));`

**Comment by Fusioon** [comment]
Now that is much better, thanks! Also would you mind explaining to me why does it even tries to generate boxed type? It seems it's because of the `GCMarkMembers` but only when it's called from generic type? 

This did work without the 2932fce
```
  Foo bar = .(10, 2);
  bar.[Friend]GCMarkMembers();
``` 
but when it's called from `ComponentHandler<T>` it failed

**Comment by bfiete** [comment]
What was happening was with:
```C#
public static mixin Mark<T>(T val) where T : struct
{
    val.[Friend]GCMarkMembers();
}
```

The `GCMarkMembers` call is special in that it's a virtual method in `System.Object` - besides `ToString`, it's the only method that you can bind via just a `where T : struct` constraint. Since structs don't have virtual tables, the way we determine which virtual method is actually bound in that slot is by generating the boxed type - even though the boxed type wasn't actually used.

There's now an `Unbound` attribute added to that call, which avoids that unnecessary boxing.
