### ISSUE TITLE
[BUG?] Enums can no longer inherit from other enums/primitive structs

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1284]
Not sure if this change was intentional but following code worked few days ago. Now it fails with `Invalid underlying enum type` error. 
```
enum Foo
{

}

enum Bar : Foo
{

}

struct Jazz : int32;

enum E : Jazz
{

}
```

**Comment by bfiete** [comment]
Yes, that change was intentional - that is illegal.

It didn't actually work before, either - it just silently failed and acted as if you hadn't specified an underlying type at all.

**Comment by bfiete** [comment]
Also the same is true in C# - you can't inherit with enums.
