### ISSUE TITLE
Large strings causes crash in Comptime

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1285]
Found this while testing Comptime File IO, the second crash only occurs with `Large Strings` enabled.
```
		[Test]
		public static void TestBug()
		{
			const String aaa = new String('\0', 9999999); // crash (memset)
			TestLargeStr(); // another crash (malloc)
		}

		[Comptime]
		public static void TestLargeStr()
		{
			String str = scope .();
			str.Reserve(29567025152);
		}
```

Tested with https://github.com/beefytech/Beef/commit/002fd075d1b2eeb83154d7ff0811ffea4bd27400

**Comment by bfiete** [comment]
Fixed at 2f72311f1fa24ab14e2f6a47f75c5d6d9f725590
Comptime memory is limited to 2GB so the second one won't work still but it won't crash anymore
