### ISSUE TITLE
[Feature request] Allow redefining constants in static scope

### ISSUE THREAD

**Issue by EnokViking** [beefytech/Beef#1286]
When binding C API's, it's not uncommon that some API defines a constant that consumer code can redefine for configuration purposes.
Consider the following:

library.bf
```cs
namespace Library
{
    static 
    {
        public const int32 TM_MAX_DEPENDENCIES_FOR_SIMULATION_ENTRY = 16;
    }
}
```

libconsumer.bf
```cs
namespace Library
{
    extension @ //extend static
    {
        public new const int32 TM_MAX_DEPENDENCIES_FOR_SIMULATION_ENTRY = 18; //redefined, library.bf will now use this
    }
}
```

I think this would be a good addition simply for the sake of consistency with the API you're binding, minimizing differences that need documentation.

**Comment by bfiete** [comment]
I don't understand the proposal. Imagine there were a class
```C#
class DependencyTracker
{
   Object[TM_MAX_DEPENDENCIES_FOR_SIMULATION_ENTRY] mDependencies;
}
```

So are you saying if you allocate this object in a `library.bf` then you would expect that sized array to be 18 elements long, but then if you allocate it somewhere else then it would only be 16 elements long?

**Comment by bfiete** [comment]
This kind of feature only works in a separate-compilation type environment such as C/C++. Despite it's "power" for this kind of stuff, I would argue that this kind of thing is one of the biggest weaknesses of those languages, actually.

**Comment by EnokViking** [comment]
Redefining the constant would effectively be equivalent of unlocking the padlock of the library in the IDE, going into the file where the constant is defined and manually edit the value, is what I mean.

**Comment by bfiete** [comment]
Then there's the issue of library dependencies.
Imagine a workspace with the following projects:
MainProgram depends on LibA and LibB
LibA depends on LibC
LibB depends on LibC

If LibA wants to redefine something in LibC, then LibB would also see that change even though LibB does not even know about LibA at all. If the constant is a `System.Type` then it would even be possible to override with a type from LibA that is supposed to be invisible to LibB.

What if both LibA and LibB want to redefine something in LibC? Who "wins"?

I agree it would be nice to have a way to configure libraries, but subverting the project dependency chain to override constant values does not seem like the correct way to do it for this language.

**Comment by EnokViking** [comment]
Ah, yeah. It's clear I haven't thought this proposal through well enough, it certainly gets very complex once you start dealing with several libraries. Hm..

**Comment by bfiete** [comment]
There won't be a way to redefine constants.

As mentioned, it may be useful to have a way to have more library configuration support, but that's not what this particular issue is about.
