### ISSUE TITLE
[BUG] SourceViewPanel - Attempt to access deleted object

### ISSUE THREAD

**Issue by marsej** [beefytech/Beef#1287]
Attached zip unzips to a "0432a" folder which contains a workspace.
[issue7.zip](https://github.com/beefytech/Beef/files/7748329/issue7.zip)

steps:
1. open C:\beefsrc-0.43.1\IDE\dist\BeefIDE.exe (or any other build before the commit mentioned below)
2. in IDE open workspace in folder C:\beefsrc-0.43.1\IDE
3. Press F5 (Debug build)
4. in the new Beef IDE [d] window, open workspace in c:\beef\Samples\0432a\
5. check that Format on Save is enabled
6. copy paste fos3.txt to Program.bf
7. save Program.bf
8. exit IDE [d]
9. press F5 in the IDE that you ran IDE [d] from
No errors occurred in any of the steps above.

repeating same steps on (freshly built with bin\build.bat)
C:\beefsrc-master\IDE (any build containing the commit below)

in step 4. after opening the workspace containing fos3.txt and Program.bf:
"Attempt to access deleted object"
in c:\beefsrc-master\IDE\src\ui\SourceViewPanel.bf
		public ~this()
		{
			if (mProjectSource?.mEditData?.HasTextChanged() == true)

after removing this commit, no more "Attempt to access deleted object" error:
https://github.com/beefytech/Beef/commit/a2a97a8e5fc745ea0f43f9f4e3854b0695b6fa0a

There's also another error (IDE crash) at step 9 if trying to skip past the error in step 4. It too goes away by reverting that commit.

**Comment by bfiete** [comment]
I'm having trouble getting a repro here. You're saying that you get the failure immediately on loading the 0432a workspace?

**Comment by bfiete** [comment]
It doesn't really make sense, because that code only gets run when you're closing a document view...

**Comment by bfiete** [comment]
I also don't see a reason why Format on Save would interact with these bugs in any way... 
I did find a formatting issue, but not related to this.

**Comment by bfiete** [comment]
I think I reproed these. Fixes incoming.

**Comment by marsej** [comment]
"you get the failure immediately on loading the 0432a workspace?" Correct and also other workspaces it seems, I was just focused on that one.

Is there a way to generate a dump somewhere in the stack (where) that would help with this? (or something else) I can only offer this image of the stack now (for some reason hovering over mEditData is all 000.. but in the Auto window it's not):

![step4](https://user-images.githubusercontent.com/81806010/146851525-15ecf0a7-9554-4a6e-90ed-075fef195a1f.png)

---
Also after enabling FoS and saving things (adding/removing the commit mentioned in SourceViewPanel.bf) in the host non-debug IDE with it, I got this:

ERROR: Expected ')' at line 5748:84 in c:\github\my\BeefMasterBuild\IDE\src\ui\SourceViewPanel.bf
    else if ((mWantsFullClassify) && (mTicksSinceTextChanged >= classifyDelayTicks) //TODO: Debug, remove /*&& (mWidgetWindow.IsKeyDown(KeyCode.Alt))*/)
                                                                                   ^
ERROR: Expected expression at line 5760:5 in c:\github\my\BeefMasterBuild\IDE\src\ui\SourceViewPanel.bf
    else if (mWantsParserCleanup)
    ^^^^
ERROR: Invalid token at line 5760:5 in c:\github\my\BeefMasterBuild\IDE\src\ui\SourceViewPanel.bf
    else if (mWantsParserCleanup)
    ^^^^

**Comment by bfiete** [comment]
These should all be fixed at c06b4eb946dd8f3e2afa72b1cc6839ba0b2e94b1
