### ISSUE TITLE
Hot reload issue with shared libraries

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1292]
I was trying to track down an issue in my project where I always would get an access violation after hot reloading the project, although I couldn't find the exact same issue, I managed to find this one that has the exact same consequences, so I guess this must be it.
When you hot reload after making any kind of change to a library that has extern methods, the extern method pointers become null.

Here's a little gif demonstrating the issue, just in case I wasn't clear enough:
![2021-12-22_14-18-47](https://user-images.githubusercontent.com/86157825/147131141-4e73b627-1ed9-4c44-9108-c69073327513.gif)

**Comment by bfiete** [comment]
It can't just be that - the IDE has many extern methods and I use hot reload all the time on that project.

**Comment by disarray2077** [comment]
Here is a minimal reproduction of the project:
[test6.zip](https://github.com/beefytech/Beef/files/7764427/test6.zip)
 The bass dll can be found here: https://www.un4seen.com/download.php?bass24

**Comment by bfiete** [comment]
Fixed at a5a8ae90763831343d07fa3d33765607624fabef
It's not often I get to do a one-character fix!
The key here was using `LinkName`. There's a symbol prefix that was supposed to be prepended which indicates to the debugger that it should reuse the existing symbol address, and that ended up getting stripped off in this case.
