### ISSUE TITLE
[Bug] Generic attributes can't be applied using shorthand name

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1298]
Generic attributes actually work in beef. But it looks like they need to be applied using their full name (`[XyzAttribute]` instead of just `[Xyz]`):

```c#
[AttributeUsage(.Class)]
struct GenericAttribute<T> : Attribute {}

[Generic<int>] // Error: Type could not be found
class Test1 {}
[GenericAttribute<int>] // Ok
class Test2 {}
```

Not a big deal obviously, but it would be nice if this worked.

**Comment by bfiete** [comment]
Fixed at 8e543d8cc5dca8478fdeadee83237dc392c9633e
