### ISSUE TITLE
Codegen failure "Invalid gep target"

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1302]
The failure mentioned in the issue title happens with a code very similar to https://github.com/beefytech/Beef/issues/1296, I even thought that the failure would be fixed when https://github.com/beefytech/Beef/issues/1296 was fixed, but it actually wasn't.

But the fix from https://github.com/beefytech/Beef/issues/1296 allowed me to find another assert failure that is surely related to the codegen failure:
![image](https://user-images.githubusercontent.com/86157825/147260663-50b1ee03-8aa1-4fee-b2c8-3dd4e35a1eeb.png)

Unfortunately, I can't share a crash dump from the IDE debug build since the nightly IDE still doesn't have the https://github.com/beefytech/Beef/issues/1296 fix, but here is a crash dump from the IDE release build:
[codegen.zip](https://github.com/beefytech/Beef/files/7770130/codegen.zip)

**Comment by bfiete** [comment]
Crash dumps usually don't really help with crashes that occur in the backend (which is the case here).
Do you have a code sample to reproduce this?

**Comment by bfiete** [comment]
(or a full project! :-) )

**Comment by disarray2077** [comment]
Oh well, I guess it can't be helped... The project below should reproduce the same crash
[test7.zip](https://github.com/beefytech/Beef/files/7781296/test7.zip)

**Comment by bfiete** [comment]
Thanks. Fixed at 268d7f7dba52a970ff80b103bccc3a1fdac4b057
