### ISSUE TITLE
[Enhancement] Enum GetHashCode

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1306]
`GetHashCode` should be made available to Enums. Currently, it's possible to make it work with the code below, but something more "official" surely would be better. 
```
	public static int GetHashCode<T>(this T value)
		where T : enum
	{
		return ((int)value).GetHashCode();
	}
```

**Comment by bfiete** [comment]
Enums already implement `IHashable`. The `GetHashCode` method is not public, however, but it can be accessed via any IHashable constraint such as:
`static int Hash<T>(T val) where T : IHashable => val.GetHashCode();`
