### ISSUE TITLE
Incorrect captured value in lambda

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1311]
Still using the same project from https://github.com/beefytech/Beef/issues/1302, the lambda seems to capture the value wrongly.
![2021-12-27_16-49-38](https://user-images.githubusercontent.com/86157825/147502976-abed0527-71c0-4f48-b7c3-fe0b08cb4ba6.gif)

I guess this isn't a issue with the project since `ScheduleCommand` is just `((Action)(scope () => { action(); })).Invoke();`... Unless the scope of the allocation is only inside the parentheses.

**Comment by bfiete** [comment]
POSSIBLY fixed with e81c0d6dfa016bc14cb3ac0638cc21a6a0f4f297

**Comment by disarray2077** [comment]
Yeah, it's fixed :D
For some reason, the IDE was randomly crashing while compiling the project, when it did compile I could check that it was fixed.
But, in the code below the value is wrong in the debug visualizer, although the actual value was right.

![image](https://user-images.githubusercontent.com/86157825/147506378-68147ab3-9642-47fc-9d98-a969d909d0c5.png)

**Comment by bfiete** [comment]
I managed to reproduce the crash.
Fixed at 98eb8f5840d936425563cbc73cd9cb0dfbd93c90
