### ISSUE TITLE
[Enhancement] Allow System.IO method calls at comptime

### ISSUE THREAD

**Issue by MaddyThorson** [beefytech/Beef#1313]
If this is possible, it would make comptime very useful for game asset systems - ie. preprocessing assets such as performing texture packing at comptime, and then generating a static class with resolved fields pointing to every asset. This enables autocomplete in code for assets, and more importantly removes fragile string lookups in asset referencing.

Currently, System.IO.Directory.Exists and System.IO.Directory.EnumerateFiles are extern methods not available at comptime - I didn't try opening specific files yet.

This is possible in C# using their T4 text templating system, but comptime seems like the right place for it in Beef.

**Comment by bfiete** [comment]
Hi, Maddy! Good to see you around.

Yes, those methods are possible to expose at comptime - they were on my list to good to soon. I'll notify you here when they go in.

**Comment by bfiete** [comment]
These methods have been added at 915a8df50eddbf484502b985e67520d5198cde6d (available in the next nightly build)

You can either create a generator, which is the most like T4, where you would manually right-click and Regenerate your asset file(s) (example at https://github.com/beefytech/Beef/blob/master/BeefLibs/corlib/src/Compiler.bf#L161 but this feature is not yet documented)

.. or you can use "standard" comptime to add fields to asset collection classes at compile-time, which will work automatically and even re-run automatically when referenced files and directories change. Automatic can be nice but if the process is slow then you may want manual control over the process.

**Comment by MaddyThorson** [comment]
Amazing! Thanks :)
