### ISSUE TITLE
[Bug] IDE crashes on call parameter for generic params array

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1314]
The code below crashes the IDE consistently when removing the `//`.
I tried to cut down the code as much as possible while still crashing.

As soon as input is entered in the method call, it crashes. Instead of `2` you can write anything else, and it will crash.
Even a single `"` will.
There is an exception however. If you enter a non-existing variable name, it does not crash. As soon as the variable exist, even if created afterwards, it crashes instantly.

Tested in latest release (0.43.1) as well as nightly.

```beef
	class Program
	{
		void SomeMethod<T>(params T[] values) {}
		public static int Main()
		{
			//SomeMethod<uint8>(2);
		}
	}
```

**Comment by bfiete** [comment]
Fixed at cfaeb875f884c85d03b24d7e649cf42fa638b974
