### ISSUE TITLE
Sometimes the IDE doesn't close

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1316]
Sometimes the IDE doesn't close and becomes a zombie that you need to kill with Task Manager. Usually, I just close it and that's it but now I remembered that I should open an issue about it :)

Here is what was stopping the IDE from successfully dying:
![image](https://user-images.githubusercontent.com/86157825/147567177-d41bbc7c-e2e8-4406-ba32-9fba87558fd9.png)

Looks like this is a deadlock since there was no thread pool worker doing anything.
![image](https://user-images.githubusercontent.com/86157825/147567573-cd4bcb29-3ab6-4966-a9b9-5b9661bee405.png)

**Comment by bfiete** [comment]
If this is still happening, can you try using https://docs.microsoft.com/en-us/sysinternals/downloads/procdump to generate a minidump?

**Comment by disarray2077** [comment]
Yes, it is still happening, in fact, I just stumbled into another issue like this while I was debugging the IDE, which seems to be caused by the compiler being stuck inside of a loop, which causes a lock to never be released.
Here is the dump of this new one:
[BeefIDE.exe_220106_143103.dmp.zip](https://github.com/beefytech/Beef/files/7824416/BeefIDE.exe_220106_143103.dmp.zip)

Here is the dump of the deadlock from this issue:
[BeefIDE.exe_220106_171053.dmp.zip](https://github.com/beefytech/Beef/files/7824440/BeefIDE.exe_220106_171053.dmp.zip)

**Comment by disarray2077** [comment]
Looks like sometimes the IDE hangs because of this same deadlock while closing tabs, here is the dump for this too:
[BeefIDE.exe_220106_190053.dmp.zip](https://github.com/beefytech/Beef/files/7824978/BeefIDE.exe_220106_190053.dmp.zip)

**Comment by marsej** [comment]
When did you first notice this issue? If the dumps don't help, bisecting some of the IDE files is a bit tedious but possible approach. I had this issue also couple times but I don't know what triggered it.

**Comment by bfiete** [comment]
I see where it gets stuck waiting, but it doesn't make sense that it should get stuck there... I think I'm going to have to add some logging to the IDE to figure this out since I can't reproduce it nor make sense of it yet...

**Comment by disarray2077** [comment]
> When did you first notice this issue? If the dumps don't help, bisecting some of the IDE files is a bit tedious but possible approach. I had this issue also couple times but I don't know what triggered it.

Honestly, I have no idea, but that won't be needed, since...

> I see where it gets stuck waiting, but it doesn't make sense that it should get stuck there... I think I'm going to have to add some logging to the IDE to figure this out since I can't reproduce it nor make sense of it yet...

I found a consistent way to reproduce the hang while closing tabs, most probably solving this will also solve the IDE not closing. 
To do it just open a crash dump and try to close the tab. Yeah, it's that simple. Here is a little video:


https://user-images.githubusercontent.com/86157825/148628807-e2bf9544-bb4e-411e-bd7e-aeabd1281c8c.mp4

**Comment by bfiete** [comment]
Lol. I do love a nice clean repro!

**Comment by bfiete** [comment]
Fixed at 2634d0c7ecd630066cbce90e7437ee66c6268fc3
We can reopen this if you find another case of this issue.
