### ISSUE TITLE
Codegen failed "Invalid rm"

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1321]
Looks like this is an upgraded version of the issue https://github.com/beefytech/Beef/issues/1050, trying to compile the below code causes the codegen failure mentioned in the issue title.
(This only happens when compiling a Debug build)
```
using System;
using System.IO;
using System.Collections;

namespace BeefBugRepros
{
	public struct Vector2 : this(float x, float y);

	static
	{
		static Vector2 vec2;
		
		const int c0 = 1;
		const int32 c1 = 1;

		[Test]
		public static void TestBug()
		{
			int i0 = 0;

			vec2 = Vector2(/*(int32)*/(i0 % c0) * (c1 + c1), 1); // Uncommenting the cast is a workaround
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed at eb0cd3aefbece52726b7816f4cd2c14c39f3cbd6
