### ISSUE TITLE
Generator stops to work after creating a extension method with error

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1330]
If you generate a new class and paste the below code in the file, you won't be able to generate another new class because of the following error: `Method not generated in comptime System.Compiler.Generator.Generate<System.Compiler.NewClassGenerator>(System.String args)`

Code:
```
using System.Collections;
using System.Linq;

static
{
	public static bool CompareTo<T>(this List<T> list, List<T> list2)
	{
	    if (list.Count  != list2.Count) return false;

	    return !list.Where((t, i) => !(t === list2[i])).Any();
	}
}
```

(This code depends on Beef_Linq, but maybe the issue is reproducible even without it)

**Comment by bfiete** [comment]
Fixed at ba0c23b8c5eff6378cbe7c4b9c5a22d1419e8489
