### ISSUE TITLE
comptime removeMethod with unset callTable entry crash

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1338]
Formerly i had a ghost "method not generated in comptime" error on the usual suspect, my [PerfTrack] attribute...
Now the ide now randomly hard-crashes (might or might not be related, but this issue is about the first BF_ASSERT that went off when i tried to debug that anyway).

**To reproduce:**
- Grab pile and open the Pile/Pile/ workspace.
- Unfold the Pile project and it's folders
- Open files from the workspace panel (clicking once to preview is fine) and click somewhere inside the source view panel.
- Repeat until crash! (shouldn't take more than a minute, but might also crash immediately)

Here's what crashes, the uninitialized entry in ceFunction->mCallTable. I don't know how it ended up there exactly, my last build was only a few days old, so maybe it's related to [this](https://github.com/beefytech/Beef/commit/ba0c23b8c5eff6378cbe7c4b9c5a22d1419e8489#diff-e0bbb22dd174e03872b46907e68a4d9c834c20950c78201f6f5b7e56f0a1c6c1R6458) change?
As far as the contents of the callTable go, i think the only thing missing from it is probably Perf.[Friend]CrappyCompHash(). See Core/Perf.bf for both that and the crashing attribute function (ComptimeMethodApply).

(thanks for the safe mode toggle!)

![grafik](https://user-images.githubusercontent.com/38580263/147876745-157d303d-7140-47cc-b50e-6e5534da8ab5.png)

**Comment by bfiete** [comment]
Yep- that change indeed caused it. I didn't properly ref count. Fixed at db6cfcf2111f2a9fc0e053e6337c0badf7c78609
