### ISSUE TITLE
[Enhancement] Allow [Align] on fields

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1339]
Currently `AlignAttribute` cannot be applied to struct/class fields, only to the struct directly. So instead of this:

```c#
struct Moo {
    [Align(64)] int32 a;
    [Align(64)] int32 b;
}
```

We have to write this boilerplate every time:

```c#
[Align(64)]
struct AlignedInt : int32 {}

struct Moo {
    AlignedInt a;
    AlignedInt b;
}
```

But this should be an easy transformation for the compiler to do.

**Comment by bfiete** [comment]
Added at 58eec21fbf201589599c3e5c3e338fa601e3e6c3
