### ISSUE TITLE
[IDE][Bug] Error list perpetually shows error even after it's fixed

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1346]
![1](https://user-images.githubusercontent.com/55242398/148123713-9e43212d-32e8-46ca-a700-4a489b9e65ee.png)

These errors will never disappear no matter what I do. The only way to get rid of them seems to be restarting the IDE.

The error appears as you type out the property. To reproduce it first go to any class, and then you have to **type every character in order** (not sure why):

```c#
int X { private set; } 
```

**Comment by bfiete** [comment]
Fixed at 632c8a4cc54de30ad63a1b52a4b00900113db54b
