### ISSUE TITLE
type-named getter crash

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1347]
This code crashes immediately. Something is a class, but in this case the getter has the same name too. Typing (or just having) a dot at the end with some static class below crashes.

```
class Something
{
	public int a;
}

static class A
{
	public static Something Something => null;
}

class Program
{
	static void Main()
	{
		A.Something.

		Console.WriteLine();
	}
}
```

**Comment by bfiete** [comment]
Oops. I tried to improve an error message and caused a crash :-(
Fixed at e4510fdb3a04c42360683b1e3305a89c420f775a
