### ISSUE TITLE
Unable to compile the IDE on Manjaro

### ISSUE THREAD

**Issue by linkpy** [beefytech/Beef#135]
At first I thought i was doing something wrong, but after comparing `build.sh` and `build.bat` i noticed the linux version didn't have the build commands for the IDE (`IDE/dist/BeefBuild -proddir=IDE -clean -config=Debug_NoDeps` for example). So i tried manually using them in a terminal and i ended up with 139 errors : 

Here are the errors : https://pastebin.com/ww0j7D4f 
Most of them are related to missing methods but I dont really know how to fix this.

**Comment by ArcOfDream** [comment]
From the looks at the corlib source, the part of the IO API that handles the FileDialog is available only to Windows, and is missing in the Linux version of the corlib.

**Comment by bfiete** [comment]
The IDE is Windows-only at the moment.

**Comment by linkpy** [comment]
Oh ok then, that makes sense.
