### ISSUE TITLE
Method call preparation failed

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1350]
The code below fails to compile because of the error mentioned in the issue title.
```
		public class Wrapper<T>
		{
			[OnCompile(.TypeInit), Comptime]
			public static void Generate()
			{
			}
		}
```

Tested with ec83ae50fa2e7259e486519e4550e89b434b98cf

**Comment by bfiete** [comment]
Fixed at 40288eeb3a7def0a976fdce18cce23da415dfbcf
