### ISSUE TITLE
[IDE][Bug] Crash with invalid comptime expression

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1353]
If you paste this anywhere, the IDE will immediately enter a crash loop:

```c#
class Moo { const int x = (() => { return 1; })(); }
```

It only happens if `x` is const and if it appears as a class member - it works fine in the body of a method.

**Comment by blat-blatnik** [comment]
This also crashes: `const int x = () => 1;`. Not sure if it's the same thing or not.

**Comment by bfiete** [comment]
Fixed at 24c91d373c1ddbd668a909e0827c1e9616fc972f
