### ISSUE TITLE
Compiler crash when casting between void* and thiscall function ptrs on aarch64

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1360]
Using target platform `aarch64-unknown-linux`

If you define a `struct` as such:
```
namespace Testy
{
	struct FuncPtrTest
	{
		protected void** vTable;

		public bool Test() mut
		{
			function bool(void* this) func = (.)vTable[0];
			return func(&this);
		}
	}
}
```

Then instantiate and call the function:
```
Testy.FuncPtrTest test = .();
test.Test();
```

The compiler will crash with
```
FATAL ERROR
Unsupported calling convention. in C:\Jenkins\workspace\Beef\IDEHelper\DebugManager.cpp:578
```

It's expected that this would compile, then fail at runtime due to attempting to dereference the empty `vTable`

**Comment by hunterbridges** [comment]
I was able to dig in a bit on this. After tracing the IR generation a bit, I noticed that the `BfIRCmd_SetCallCallingConv` command being generated in the module was calling `GetLLVMCallingConv` in `BfIRCodeGen.cpp`:

![image](https://user-images.githubusercontent.com/775593/148628146-68ec9810-1cdb-4a7c-982a-8689692d8991.png)

However, in llvm `AArch64TargetLowering::CCAssignFnForCall`, the `X86_ThisCall` case is not handled which is causing the fatal error to be thrown in the `default` case:

![image](https://user-images.githubusercontent.com/775593/148628206-139133d0-f1f8-439c-ac83-89bbe5426854.png)

I was fishing around various discussions about this error, and it seems like another common way people hit this is by trying to use the `PreserveAll` calling convention, and the common patch-up seems to be to use `PreserveMost` instead (which does have a case in the Target Lowering handler). So, I tried patching `GetLLVMCallingConv` this way:

![image](https://user-images.githubusercontent.com/775593/148628415-ed6f592d-4bb0-417a-b24f-ec5cc8009783.png)

I have not yet been able to test yet whether the generated IR actually works as expected... but it does seem to be that the issue lies in how the Beef IR generator is selecting its calling convention for function pointers, and that's creating a mismatch with what is supported on the AArch64 backend.

**Comment by hunterbridges** [comment]
Well, in Release mode I needed to call `.GetMachineType()` instead of simply reading `.mMachineType`...

**Comment by hunterbridges** [comment]
I was able to try this on target aarch64 hardware with the above compiler patch, and a slightly more developed test case in my prepped harness app:

Test class:
```
using System;

namespace SwitchTestyBeef
{
	struct FuncPtrTest
	{
		protected void*[4] vTable;
		int i = 1234;

		public this(int i)
		{
			function int(FuncPtrTest this) func = =>Inner_Test;
			vTable[0] = (void*)func;

			this.i = i;
		}

		int Inner_Test()
		{
			return i;
		}

		public int Test() mut
		{
			function int(void* this) func = (.)vTable[0];
			return func(&this);
		}
	}
}
```

And then my Beef entry point:
```
using System;

namespace SwitchTestyBeef
{
	class Program
	{
		[LinkName("SwitchTesty_Entry")] public static void Main()
		{
			Console.WriteLine("Hello world from beef!");

			FuncPtrTest t = .(1234);
			int tResult = t.Test();
			Console.WriteLine($"tResult = {tResult}");
		}
	}
}
```

C++ entry point:
```
#include <stdio.h>

extern "C" void BeefStart();
extern "C" void BeefStop();
extern "C" void SwitchTesty_Entry();

extern "C" void nnMain()
{
	printf("Hello world from C++!\n");

	BeefStart();
	SwitchTesty_Entry();
	BeefStop();
}
```

Run output matches what I would expect:
```
Hello world from C++!
Hello world from beef!
tResult = 1234
```

**Comment by hunterbridges** [comment]
I submitted a PR for the change I made to the `GetLLVMCallingConv` function...

**Comment by bfiete** [comment]
Patch applied. Closing (assuming this fully fixes the issue)
