### ISSUE TITLE
Bug: wrong behavior when comparing int32 to way bigger 64-bit value

### ISSUE THREAD

**Issue by rds1983** [beefytech/Beef#1367]
Code:
```
int32 val = 2299126;
if (val > 2147483647) {
  var why = true;
}
```

For some reason, the debugger enters that if:
![image](https://user-images.githubusercontent.com/1057289/148664532-523a2de7-b0b6-4489-8848-3a20da8b74e0.png)

**Comment by bfiete** [comment]
Thanks. Fixed at 9fc6ae9f05b49bcd3fa12231bc4349e68253faf3
