### ISSUE TITLE
Constraint-sized array doesn't work

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1370]
The below code doesn't compile even though there should be nothing wrong with it.

```
	struct StringViewEnumerator<TS, C> : IEnumerator<StringView>
		where TS : StringView[C]
		where C : const int
	{
		private TS mStrings;
		private int mIdx;

		public this(TS strings)
		{
			mStrings = strings;
			mIdx = -1;
		}
		
		public StringView Current
		{
			get
			{
				return mStrings[mIdx];
			}
		}

		public bool MoveNext() mut
		{
			return ++mIdx != mStrings.Length;
		}

		public Result<StringView> GetNext() mut
		{
			if (!MoveNext())
				return .Err;
			return Current;
		}
	}
```

Also, if you swap the order of the constraints, an error shows up, but the error doesn't say that you need to use this specific order so I guess it could be improved (or fixed if this actually is a bug)
![image](https://user-images.githubusercontent.com/86157825/148811483-3a6353f3-f3c0-4987-a0e6-43dd0d472aa5.png)

**Comment by bfiete** [comment]
Fixed at ed6959973a062b124eea6a90f05f4a9ee78ca1a8
