### ISSUE TITLE
[Enhancement] LTO should be turned on in release builds by default

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1373]
As the title says, I would have expected this to be the default and was kind of surprised that it isn't.

Without LTO even simple things from corlib, such as a Span constructor won't be inlined in a project. I shipped a small project without LTO without knowing. Even though I now know better, I think there's value in just having it on by default.

I see now that that requires switching to LLVM output in Workspace Properties -> Build -> Toolset, when by default it's Microsoft. I'm not sure if there are any downsides to switching that by default that would prevent this.

**Comment by blat-blatnik** [comment]
Related, if you try to enable LTO without switching to LLVM output, the compiler will emit this error message:

```
ERROR: The Workspace Toolset must be set to 'LLVM' in order to use LTO in 'Test, corlib'.
Consider changing 'Workspace/General/Toolset' to 'LLVM'.
```

But the LLVM switch is actually in Workspace/_**Targeted/Build**_/General/Toolset.

**Comment by bfiete** [comment]
Release detauls to LTO at 0f694cf33da0a4e1a1c7bc5b58707b843ad00927
Error changed at e7f50985dc9a1b7a90a575c46a229e16aa9c094a
