### ISSUE TITLE
[IDE][Bug] Crash when backspace after delete

### ISSUE THREAD

**Issue by blat-blatnik** [beefytech/Beef#1374]
Steps to reproduce:
1. Type `[`. The IDE will automatically insert a matching `]`.
2. Type delete
3. Then backspace

If you do this on an empty text buffer, the IDE will immediately crash from an out of bounds access. If you do it on a non-empy buffer it still does something strange but it doesn't crash.

I guess it's probably confused about the auto-inserted ']'.

**Comment by bfiete** [comment]
Fixed at 3f6d4d1199f553d39e41700e39f4dcc1662f7ca6
