### ISSUE TITLE
[Bug] (aarch64) Matrix parameters not working as expected when passed by value in * operator

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1377]
In our engine, we have a Matrix struct defined as such:
https://gist.github.com/hunterbridges/eeaf34fa8e58bde18c5cd72385b6e82d

(There are also more Matrix functions in an extension, linked from our C++ codebase)

There is a `*` operator override defined with the signature:
```bf
public static Matrix operator *(Matrix a, Matrix b)
```

When running in aarch64, the `*` operator implementation crashes when called by a compound multiplication expression that is using multiple temporary values:
```bf
Matrix transform = Matrix.RotateT(0.25f, Math.RandGauss(), 0.0f, .XYZ)
	* Matrix.Rotate(Quaternion.FromToRotation(Vector3.UP, dir))
	* Matrix.Scale(Math.RandFloat(1.3f, 2.2f))
	* Matrix.Translate(dir * RADIUS * 0.9f);
```

When stepping through in the debugger, it seems that the parameters were not properly passed to the operator function:
![image](https://user-images.githubusercontent.com/775593/149397049-111d3312-f772-4085-9e21-6478e9a23f67.png)

NOTE: I am able to work around this by changing the signature to use const ref `in` parameters, instead of passing by value:
```bf
public static Matrix operator *(in Matrix a, in Matrix b)
```

**Comment by bfiete** [comment]
Or does this just crash in isolation?

**Comment by hunterbridges** [comment]
Seems to be fixed in https://github.com/beefytech/Beef/commit/dc5ba5c67eed599154cb1b38d6cbdb1dce030f69
