### ISSUE TITLE
[Bug] (aarch64) ABI issue when calling extern Cdecl function with Matrix return type

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1378]
In our engine, we have a `Matrix` struct defined as such:
https://gist.github.com/hunterbridges/eeaf34fa8e58bde18c5cd72385b6e82d

We also have a Matrix extension that links to our C++ API. Among them are these functions:
```bf
[LinkName("RSDK_Matrix_BuildTransform"), CallingConvention(.Cdecl)] extern public static Matrix BuildTransform(Vector3 position, Quaternion rotation);
[LinkName("RSDK_Matrix_BuildTransform_2"), CallingConvention(.Cdecl)] extern public static Matrix BuildTransform(Vector3 position, Vector3 scale);
[LinkName("RSDK_Matrix_BuildTransform_3"), CallingConvention(.Cdecl)] extern public static Matrix BuildTransform(Vector3 position, Quaternion rotation, Vector3 scale);
[LinkName("RSDK_Matrix_BuildTransform_4"), CallingConvention(.Cdecl)] extern public static Matrix BuildTransform(Vector3 position, Vector3 forward, Vector3 up);
```

These are simply C-linkage wrappers for C++ functions under-the-hood:
```cpp
Matrix RSDK_Matrix_BuildTransform(Vector3 position, Quaternion rotation)
{
    return Matrix::BuildTransform(position, rotation);
}

Matrix RSDK_Matrix_BuildTransform_2(Vector3 position, Vector3 scale)
{
    return Matrix::BuildTransform(position, scale);
}

Matrix RSDK_Matrix_BuildTransform_3(Vector3 position, Quaternion rotation, Vector3 scale)
{
    return Matrix::BuildTransform(position, rotation, scale);
}

Matrix RSDK_Matrix_BuildTransform_4(Vector3 position, Vector3 forward, Vector3 up)
{
    return Matrix::BuildTransform(position, forward, up);
}
```

When running on aarch64, there is a problematic call-site for `RSDK_Matrix_BuildTransform_3`. The following parameters are passed in at the callsite:
![image](https://user-images.githubusercontent.com/775593/149398500-7ecb3fbf-6058-4d6e-8b98-ebba099cfd29.png)

But then the parameters are scrambled in the receiving function:
![image](https://user-images.githubusercontent.com/775593/149398578-cc6e53b1-2ffc-4737-aa39-6fb8700ff6b4.png)

Curiously, if I inspect the memory of `position` at the callsite, it looks like this:
![image](https://user-images.githubusercontent.com/775593/149398677-bb711814-fd4b-48fa-8a48-ec6db1998380.png)

But then in the receiving frame it looks like this, suggesting the `y` component is getting dropped:
![image](https://user-images.githubusercontent.com/775593/149398713-cb9f8880-96d0-4cf5-9a1c-0f08391b1def.png)

**Comment by bfiete** [comment]
C calling convention matching in LLVM sucks. The front-end devs basically have to just look at Clang output for a bunch of different types of arguments & return types on every platform and try to match it.

Anyway- there's a bunch of fixes at 5bc9642d263177e70b034ddc19abb4dd88712826

Hopefully this hits all your interop cases and magically fixes your other issues as well.

**Comment by hunterbridges** [comment]
I pulled the latest and tried compiling. Got a fatal compiler error crash, build log here:
https://gist.github.com/hunterbridges/c6d0c6a7087cfd70398e06bb301bf752

Here's a small sampling of method signatures it is dying on:
```bf
struct PathNode
{
    public void DefaultDraw(Color color = 0xFFFFFFFF);
}

struct Path
{
    [LinkName("RSDK_Path_GetPosition"), CallingConvention(.Cdecl)] extern private static Vector3 GetPosition_Impl(void* thisPtr);
    [LinkName("RSDK_Path_GetColor"), CallingConvention(.Cdecl)] extern private static Color GetColor_Impl(void* thisPtr);
    [LinkName("RSDK_Path_GetColorForNode"), CallingConvention(.Cdecl)] extern private static Color GetColorForNode_Impl(void* thisPtr, uint32 i);
}
```

It seems to be something around `void*` and thiscalls. A lot of them are thiscalls in our engine bindings, which use `void*`. Curiously, some of them are just pure Beef instance methods

**Comment by bfiete** [comment]
Ah, yes - I didn't properly test the calling code, just the method declaration code. Well, to the point that I can test any of this stuff, really.

I think this may fix it dc5ba5c67eed599154cb1b38d6cbdb1dce030f69

**Comment by hunterbridges** [comment]
Great thanks! This one compiled fine. Going to test out these cases...

**Comment by hunterbridges** [comment]
Appears to be fixed!
