### ISSUE TITLE
[Bug] (aarch64) Implicit constructor behavior is not consistent

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1379]
We have a `Camera` class defined as such:
https://gist.github.com/hunterbridges/373835db20185b85e997ba99792080ae

`Camera` has the following members [on line 149](https://gist.github.com/hunterbridges/373835db20185b85e997ba99792080ae#file-camera-bf-L149):
```bf
// Camera Configurations
public ConfigStack configStack = .();
public Config* lastConfig = null;
public Config* lastConfigCheck = null;
public Config baseCamConfig;
```

`ConfigStack` also has the following member [on line 50](https://gist.github.com/hunterbridges/373835db20185b85e997ba99792080ae#file-camera-bf-L50):
```bf
public Array<Config*, const CAMERACONFIG_STACK_SIZE> data = .();
```

When the class is constructed using the default `()` constructor, it is expected that:
- structs with no explicit constructor called during initialization will be zero (e.g. `baseCamConfig`)
- struct types with no defined constructor will implicitly construct child members if default constructor is called (e.g. `ConfigStack`'s `data` member)

However, on aarch64, it seems that if left as-is, the constructors are not consistently cascaded and both `baseCamConfig` and `configStack.data` are left with garbage data:
![image](https://user-images.githubusercontent.com/775593/149401244-9955395b-1057-4749-9aa8-735a0e575e74.png)

It is possible to work around the `baseCamConfig` issue by calling default initializer, and by implementing a default initializer on `ConfigStack` which manually calls the default constructor for `data`
![image](https://user-images.githubusercontent.com/775593/149401369-d38db66f-ace5-418f-8810-7904164eada9.png)

**Comment by bfiete** [comment]
I'm not even sure how to _begin_ to investigate this...

**Comment by hunterbridges** [comment]
Perhaps... I can dig in further. It does seem to be getting set to the garbage values just after construction. Perhaps it deserves to be mentioned that objects are constructed with a "placement new" kind of thing like so:

```bf
struct PlacementAlloc
{
    void *ptr;
    
    public this(void *ptr)
    {
	    this.ptr = ptr;
    }
    
    public void* Alloc(int size, int align)
    {
		      return ptr;
    }
}

// Example construction
new:(PlacementAlloc(memory)) E();
```

**Comment by hunterbridges** [comment]
Here is something kind of strange. So, the `CameraStack` data member is an `Array` generic type, which is defined as such:
```bf
namespace RSDK
{
	struct Array<T, N> where N : const uint32
	{
		// -------
		// Members
		// -------

		T[N] data;
		uint32 mLength;

		// -------------------
		// Getters and Setters
		// -------------------

		public uint32 length { get => mLength; }
		public uint32 size { get => N; }

		// ------------
		// Constructors
		// ------------

		public this()
		{
			data = ?;
			mLength = 0;
		}

		// Methods, etc.
	}
}
```

When I look at it in the debugger, I noticed some odd things:
![image](https://user-images.githubusercontent.com/775593/149416989-360f9d13-7db3-4461-a9a7-8e1b7934b2d1.png)

So the debugger says the `Camera`'s `configStack` member is at address `0x00000021'afaa3670`. Then it says the `data` array starts at `0x00000000'afaa3630`. This is weird to me for two reasons:
- Looks like the upper bits of the address are being truncated to a 32-bit value
- The address of this member _should_ just be the same address as `configStack` since it is the first member
- Assuming the address is actually supposed to be `0x00000021'afaa3630`, that would actually be 64 bytes _before_ where it should be. Curiously this is an array of 8 pointers, so that would be 64 bytes on a 64-bit architecture.

Is it possible this has to do something with computing member offsets?

**Comment by hunterbridges** [comment]
I have stepped through this a few times now. When I inspect the memory at `0x00000021'afaa3670` it looks like this:
![image](https://user-images.githubusercontent.com/775593/149420278-b05faf64-5fbd-4e94-960b-7f61d8f35a92.png)

Since the Array `data` is initialized with `?`, it seems like maybe the array data is getting initialized in the right place, but then something is going amiss whenever other code tries to access the members of the struct?

We are feeding it data that is already zeroed. The contents of the address gets changed during the Camera's `__BfCtor()` on the highlighted line:
![image](https://user-images.githubusercontent.com/775593/149420947-88c23e81-6de6-4e62-b6d4-1aa3fbb32aa6.png)

**Comment by bfiete** [comment]
Well, hopefully this all has to do with calling convention issues - because I am fixing some stuff there. The debugger screenshots aren't really helpful for anything though, unfortunately.

**Comment by hunterbridges** [comment]
Hm, so the game code seems to be running normally now and not hitting the bugs in the camera code. But the nested struct values do still look weird in the debugger. Maybe this is a bug with the debug view?

**Comment by bfiete** [comment]
Well, it's either an issue with LLVM debug info emission, with Visual Studio, or with the compiler. LLVM has a number of issues with debug info, especially with optimizations...

**Comment by hunterbridges** [comment]
I see... for what it's worth, this was a Debug build so at least there should be no optimizations at play
