### ISSUE TITLE
[ide] Automatically complete the drop-down box, optimize the display

### ISSUE THREAD

**Issue by sgf** [beefytech/Beef#1380]
![动画](https://user-images.githubusercontent.com/2557696/149441397-cb8c6fc2-92fb-4459-b147-f04b295331e4.gif)

**Comment by bfiete** [comment]
Huh?

**Comment by bfiete** [comment]
Looks like a display driver bug of some sort to me.

**Comment by sgf** [comment]
> Looks like a display driver bug of some sort to me.
maybe u are right. im test in my pc(not book).thats correctly
