### ISSUE TITLE
Generic attribute using generic parameter causes crash

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1381]
As an example, the code below crashes:

```
		struct TestGenericAttribute<T> : Attribute
		{
		}

		[TestGeneric<T>]
		void TestGenericMethod<T>()
		{
		}
```

Tested with https://github.com/beefytech/Beef/commit/8f7f7cba21fe9b1bc27d20d773eca2772bd44f13

**Comment by bfiete** [comment]
Fixed at 4e18517c036089d3b6d5175832f7df09bc60f742
