### ISSUE TITLE
[Enhancement] Give priority to derived type in method selection

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1385]
Right now the project https://github.com/disarray2077/LuaTinker-Beef is failing to build because of the following error caused by the commit https://github.com/beefytech/Beef/commit/10e8136a9cac9f5bec692c867d2de21174693190:
![image](https://user-images.githubusercontent.com/86157825/149666265-7fe4f9eb-1d41-4c85-b68b-cc0f795348bf.png)

I could change the code IInteger and IUnsigned but I think it would make more sense if Beef could see that IFloating is just a more specialized version of INumeric and could pick the method with IFloating constraint.

**Comment by bfiete** [comment]
Fixed at c7d2d2e9bd5957db0824318a75ef22114a9a4022
