### ISSUE TITLE
UI becomes unresponsive after clicking "Don't save" on unsaved document close (...)

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#1388]
Steps to reproduce:
1. Open the IDE
2. Open the "Workspace" view
3. Click File -> New -> New file
4. "untitled" file opens
5. Close the file and click "Don't save" (or "Cancel")
6. Right click anywhere inside the workspace view

**Step 6** is important, although nothing is shown on the workspace view at this point because no project is opened.

The things that don't work after:
- The whole IDE's top right corner buttons don't react (Minimize, Maximize, Close)
- The IDE's menubar don't react (also no hover effect)
- (If a project was opened after Step 1 or Step 2) The workspace view reacts to right clicks on files and folders, but the tooltip menu
that opens doesn't show which list item I'm hovering on. Also if I click any of them,
the menu just disappears, but doesn't execute the action (as if I clicked outside the list)

Version: 0.43.2 (Nightly 01/18/2022)

**Comment by bfiete** [comment]
I couldn't repro this... weird.

**Comment by Hiroko103** [comment]
I will try to gather more information about this in the source files.

**Comment by Hiroko103** [comment]
I found an important detail (,which I wasn't aware of) that matters.
The "untitled" tab should be closed with a middle mouse click.
When I tried closing it with the little dedicated "X" button, the issue didn't happen. (I repeated it 10 times, and the result was always the same)

**Comment by Hiroko103** [comment]
I think the UI gets stuck because when I close it with the middle mouse button, the "(Middle) Mouse down" event gets generated for the main IDE window, but as the dialog box pops up, the main IDE window won't receive the corresponding "(Middle) Mouse Up" event.

If the IDE gets into the stuck state, I can get out of it if I click anywhere in the IDE again with the middle mouse button (even on the process' titlebar).

Also, I should mention that debugging the IDE itself makes reproducing the bug a bit more tricky.
As a breakpoint is triggered in the "host" IDE, the window switch caused by it prevents the bug to appear.

**Comment by bfiete** [comment]
Yep, the middle button was the key.
Fixed at 1e63e68e3d9f2ab5d1105ce951f2affc6529c30e
