### ISSUE TITLE
Unable to open any of the sample projects or corlib within Beef IDE

### ISSUE THREAD

**Issue by Sheepfh** [beefytech/Beef#139]
After installation, I tried opening one of the two sample project and I got this error 
![image](https://user-images.githubusercontent.com/64324649/80286621-c9ab9f00-872c-11ea-813f-200274e1118d.png)

When I try to create a new project from scratch I get this error
![image](https://user-images.githubusercontent.com/64324649/80286697-3757cb00-872d-11ea-8ce6-c3dec47ac4ca.png)

I made sure the paths shown in the pictures exist on my disk.
I used the installer from the website and am on Windows10 x64

**Comment by mundusnine** [comment]
I had this issue when I didn't start the beef installer as an admin; When I used run as administrator it made it possible to compile and run the hello world because corlib could be loaded.

**Comment by Sheepfh** [comment]
I tried reinstalling everything from scratch a couple of time, at different locations, while running as admin but I keep getting the same error messages..

**Comment by RogueMacro** [comment]
I'm getting this too.

**Comment by bfiete** [comment]
Fixed.
