### ISSUE TITLE
[BUG][IDE Crash] - Crash when creating/opening new project in UnversionedLibDirs

### ISSUE THREAD

**Issue by Jonathan-Racaud** [beefytech/Beef#1392]
[Error]
IDE crash when creating or opening a new project with its location inside a folder part of the "UnversionedLibDirs"

[Expected]
Not to crash

[Context]
I wanted to have my own "MyBeefLibs" directory to test that "UnversionedLibDirs" parameter.

[Steps to reproduce]
1. Open BeefLang/bin/BeefConfig.toml
2. Add a path to "UnversionedLibDirs"
3. Open Beef IDE
4. Create a new project
5. Select project type: Library (I assume this doesn't really matter)
6. Select an empty folder inside of the newly added library dir
7. Click create

Or after step 3, just try to open a Beef project located inside the folder. 

[Beef IDE version]
Version 0.43.2 (Nightly 01/14/2022)

[Dump crash]
[IDE_Crash_new_project_in_lib_dir.zip](https://github.com/beefytech/Beef/files/7900072/IDE_Crash_new_project_in_lib_dir.zip)

**Comment by bfiete** [comment]
Fixed at 11b43b0d1c688ffb7d2b9f1be9219ce45f7b55c5
