### ISSUE TITLE
Random crash on compile

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1398]
[here](https://github.com/beefytech/Beef/files/7942978/CrashOnCompile.zip) is dmp file from the crash, it seems to happen randomly usually on clean compile but had it happen few times with prior successful builds.

Tested with: (Nightly 01/25/2022)

**Comment by bfiete** [comment]
Hm. Can you send the workspace?

**Comment by Fusioon** [comment]
Sent via email.

**Comment by bfiete** [comment]
Crash if fixed here f6e8516fc00110b289eb373e6b8e043d7cc0528e
Interface issue where first compile throws an error is fixed at 7e03ce86bc09503caf266fb7a6124a69ea3b8706
