### ISSUE TITLE
[Feature Request] Add open folder location to projects in workspace

### ISSUE THREAD

**Issue by Salvakiya** [beefytech/Beef#140]
would be neat to add open folder location to this dialogue similar to how it shows for .bf files.
![image](https://user-images.githubusercontent.com/6888784/80291139-cb12a280-86ff-11ea-88e4-f786e4197060.png)

**Comment by bfiete** [comment]
Added in https://github.com/beefytech/Beef/commit/9c59fd0dbf64e829aa0290d8114f68e9aabacd6f.  Will be in release 0.42.3.
