### ISSUE TITLE
[IDE][Bug] Wrong method reference found

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1401]
Using the code below, selecting the `EvaluateIntX()` method in the class will highlight the `GenerateAssi` part in `GenerateAssignmentWat`. As if they were the same.

The same issue is seen when uing "Find All References" on the `EvaluateIntX()` class method. `GenerateAssignmentWat()` will be seen as a reference.

Renaming `EvaluateIntX` in the class also renames `GenerateAssignmentWat` in the interface.

Changing whitespace in the class might remove the issue temporarily. Changing code elsewhere sometimes return the issue.
Did not figure out quite how that works.

Adding or removing code in the interface or class might make other methods match incorrectly instead.
If the `void Asd() { }` line is removed from the example. The `IntXExpression` contructor will be the one seen as the same reference as `GenerateAssignmentWat`

```beef
using System;
namespace Clean
{
	public interface IExpr
	{
	    void Asd() { }
    
	    void GenerateAssignmentWat() {  }

	    int64 EvaluateIntX() { return 0; }
	    int64 EvaluateInt64() { return 0; }
	}

	public class IntXExpression : IExpr
	{
		private int64 value;

		public this(int64 value) {
		    this.value = value;
		}


		public int64 EvaluateIntX() => value;
		public int64 EvaluateInt64() => value;

	}
}
```

**Comment by bfiete** [comment]
Fixed at eab64df7ce895ac10af94113a46672ab74a155f6
