### ISSUE TITLE
ide hard crash with mixins

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1402]
get bon
https://github.com/EinScott/bon

search for "\@report", should yield 2 results. Comments describe issues in detail, both simply involve putting something in the source code. Both issues cause the ide to hard-crash

**Comment by bfiete** [comment]
Fixed at 639bfac45b417f5a2743210a09e488d4574d5484 and c23d44502b9be932d0b18729a99adf2ac8104a60
