### ISSUE TITLE
Comptime method always gives error

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1404]
For some reason, the below code always fails, I'm not sure if this is actually a bug, but this code used to have no issues (the last time I tested was with commit https://github.com/beefytech/Beef/commit/5267e18783c9f280431de7b691edb7e138a46586). 

I tried to use `type.IsGenericParam` to immediately return `void` when the type was unspecialized (which most likely is the issue) but it doesn't seem to be possible since `IsGenericParam` is returning false in this case.

```cs
		public struct GetTupleField<T, C>
		    where C : const int
		{
			public typealias Type = comptype(getTupleFieldType(typeof(T), C)); //  Fatal Error: Type "void" isn't tuple

			[Comptime]
			private static Type getTupleFieldType(Type type, int index)
			{
				if (!type.IsTuple)
					Runtime.FatalError(scope $"Type \"{type}\" isn't tuple");
				Compiler.Assert(type.FieldCount > index);
				return type.GetField(index).Get().FieldType;
			}
		}
```

Tested with https://github.com/beefytech/Beef/commit/c2a2cf221a9887f4049ef2166a7458813b332733

**Comment by bfiete** [comment]
Fixed at 26506efc1e11ae244d44ae471552b452b8c7b7af

The generic param name will now properly print in the error message. (ie: `Type "T" isn't tuple`).
And you can do `if (type.IsGenericParam) return typeof(var);` to handle the generic definition case now.
