### ISSUE TITLE
`Compiler.Mixin` affecting comptime method

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1407]
The below code, which uses `Compiler.Mixin` inside of a comptime method, is now failing to build. I guess this is a bug since you can't use comptime to emit comptime code (although if this was possible it would be sick!)

Code:
```cs
		[Comptime]
		public static void EmitReturn()
		{
			Compiler.Mixin("return 0;");
		}


		[Reflect]
		public static int Main(String[] args)
		{
			EmitReturn(); // Unable to implicitly cast 'int' to 'void'

			return 0;
		}
```

Tested with 21366d48ecae18a19af50507186881076beffabe

**Comment by bfiete** [comment]
I hadn't properly considered using `Compiler.Mixin` within another comptime method.

Now as of 6c18ffd607c9da1428f89fd755d6d121b70ab14b:
- `Compiler.Mixin` will properly mixin in-place (ie: in your example the `return 0;` would apply to the `EmitReturn` method just as if you had just typed in `return 0;` directly in there. 
- `Compiler.MixinRoot` will apply to the comptime-invoking method, which is what you were attempting to do here.
