### ISSUE TITLE
ghost 'Unused 'params' expression' warning while compiling

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1408]

**Comment by EinScott** [comment]
today i learned accidentally pressing enter while inputting the tile just posts the issue.

Anyway, grab Pile and clean compile the Square example. The warnings should show up twice in the output window. I'm pretty sure i don't have any unused ones. Furthermore i'm getting the warning twice, but only use the params keyword once in the class which it is reported on.

**Comment by bfiete** [comment]
Fixed at 1f5a56488be3727fb5fa516141338f1a622cae99
