### ISSUE TITLE
[Bug] [IDE] Creating enum with both unavailable type and attribute crashes IDE

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1414]
The following code crashes the IDE instantly when loaded.
The combination of an unavailable enum attribute (`Asd`) and type (`asd`) triggers this.
The enum has to be used somewhere as well.

```beef
namespace Clean
{
    [Asd]
    enum SomeEnum : asd
    {
    }
    
	public class Program {
		public static int Main() {
			SomeEnum e;
			return 0;
		}
	}
}
```

I stumbled upon this when porting a c# project.
It makes the following c# enum crash:
```csharp
    [Flags]
    enum SomeEnum : short
    {
    }
```

**Comment by bfiete** [comment]
Fixed at 2130715f216c398c83625989a6d072cdf7fe6f64
