### ISSUE TITLE
[BUG] Compiling never finishes

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1418]
This code: [link](https://gist.github.com/Fusioon/d2ac51e13763da0f8953a868dcb33832) 
causes the compiler to never finish compiling. (Code may not be valid)

Tested with: (Nightly 02/06/2022)

**Comment by Fusioon** [comment]
Seems like issue is missing `>` symbols in some  `ChunkStream<T>` and `Vector<T>` type methods. (So code is definitely not valid)

**Comment by bfiete** [comment]
Fixed at ceb400d57359f54a280c906455df5d8a13597e89
