### ISSUE TITLE
Crash when closing Output tab

### ISSUE THREAD

**Issue by mundusnine** [beefytech/Beef#142]
Using 0.42.2 BeefIDE
I have dual screens. 
Windows latest.

[crash_dump_closing_a_tab_dual_screen.zip](https://github.com/beefytech/Beef/files/4535807/crash_dump_closing_a_tab_dual_screen.zip)

![image](https://user-images.githubusercontent.com/29337013/80312961-28692b00-87b6-11ea-9c7e-ff7ce9aa085d.png)

 I can drag the output tab at the right top like this:
![image](https://user-images.githubusercontent.com/29337013/80312981-46cf2680-87b6-11ea-86bf-973de5e6e5d3.png)

When closing the output tab at the bottom I dont get a crash; When closing the output tab at the top right I do get the crash that is specified in the crash dump. 

If I close the bottom tab of Ouput before the top right one; I dont get the crash. 

Using Beef tech 0.42.1 I dont have the additional output tab at the top.

**Comment by bfiete** [comment]
Oh how did you manage to get multiple output panels?

**Comment by mundusnine** [comment]
It boots like this.

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/07df54ddbac10c8c803534ebbc25a6fffe5689c6, will be in 0.42.3.

**Comment by mundusnine** [comment]
This is fixed now in the new release.
