### ISSUE TITLE
[Enhancement] Allow dll import failure handling

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1423]
Failing to load a DLL or find a DLL method isn't really a fatal error, for example, in C# you can just catch the `DllNotFoundException` or the `EntryPointNotFoundException`.
Although I guess this would have to be handled differently in Beef since Beef loads the DLL and its methods before any user code is run (and we don't have exceptions lol), so we would have to find another way to do it.

My suggestion is that we add "non-fatal DLL loading" as an alternative option and allow it to be chosen in the project settings, so instead of failing at the start-up, we only fail when you try to call a not-loaded method from the DLL. This could allow us to check if the DLL exists or if the method is loaded and handle such cases beforehand.
Although, what I was thinking for "checking if the method is loaded" is checking if it's null, but currently you can't get the address of extern methods so this would also need to be allowed, or maybe this could somehow be done with an Internal method.

**Comment by bfiete** [comment]
We could just do
```C#
[Import("test.dll"), LinkName("func")]
static function void() mFunc;
```

And do normal null checking on it.

**Comment by disarray2077** [comment]
That would be nice too, but people would need to explicitly use it in their libraries, unless we removed DLL loading from extern methods with import attribute, otherwise even only one dependency using a DLL that doesn't exist would cause a crash at startup if it's using an extern method...

**Comment by bfiete** [comment]
Yeah- the library writer would determine which method to use. It seems like that's the right way to go about it... C# is a bit of a different example because it's a JIT and nothing uses normal linking.

**Comment by disarray2077** [comment]
Well, that's okay then, but I see no benefit in using `[Import("test.dll"), LinkName("func")]` in this case since it is no better than something like this:
```
static function void() mFunc = (.)Internal.GetSharedProcAddress("test.dll", "func");
```
... which already exists, but currently gives a fatal error when it can't find the method.

**Comment by bfiete** [comment]
True- the advantage would be slightly cleaner syntax and the ability to infer the link name... 

Hm. But now that I think of it, we _could_ create a mechanism for installing an error handler which could ignore errors from `Internal.GetSharedProcAddress`, and it already is possible to set static ctor priorities that can run before DLLs get loaded...

**Comment by disarray2077** [comment]
This sounds good! although the handler would be quite limited since no static class would have been initialized, but it still would be better than nothing.

**Comment by bfiete** [comment]
Added at 657a64f59cd286f147b373c82f04c03997b19304

```C#
[AlwaysInclude, StaticInitPriority(101)]
static class AllowFail
{
	public static this()
	{
		Runtime.AddErrorHandler(new => Handle);
	}

	public static Runtime.ErrorHandlerResult Handle(Runtime.ErrorStage errorStage, Runtime.Error error)
	{
		if (errorStage == .PreFail)
		{
			if (var loadLibaryError = error as Runtime.LoadSharedLibraryError)
				if (loadLibaryError.mPath == "abc.dll")
					return .Ignore;
			if (var getProcAddressError = error as Runtime.GetSharedProcAddressError)
				if (getProcAddressError.mProcName == "Zonk")
					return .Ignore;
		}
		return .ContinueFailure;
	}
}
```
