### ISSUE TITLE
"Static lambdas" only work when empty

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1426]
When you try to use a lambda that doesn't capture as a static method it currently doesn't work.

Example:
![image](https://user-images.githubusercontent.com/86157825/153434227-b99e7d13-342e-46e8-91af-f45db3ed096f.png)

But if you delete `gApp.RunStep();` then it compiles fine, so I guess that this is happening because the lambda is capturing `gApp` even though it is static?

**Comment by bfiete** [comment]
Fixed at d9725dda7c0e2f97b0c75c4395d6d1c892bcb4aa
