### ISSUE TITLE
[Enhancement] Static local functions

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1427]
Beef already supports local functions, so I guess supporting static local functions wouldn't be too hard, since they don't capture.

C# implemented it in C# 8: https://www.telerik.com/blogs/c-8-static-local-functions-and-using-declarations

**Comment by bfiete** [comment]
I guess the benefits are to ensure you don't accidentally capture something, and to ensure that the method signature will be compatible with a specific delegate or function type?

**Comment by bfiete** [comment]
Added at d9725dda7c0e2f97b0c75c4395d6d1c892bcb4aa
