### ISSUE TITLE
Failed to build on Manjaro

### ISSUE THREAD

**Issue by henriquelalves** [beefytech/Beef#143]
On Manjaro, building the project fails at `/home/henrique/Dev/Beef/IDEHelper/../extern/llvm-project_8_0_0/llvm/include/llvm/IR/Intrinsics.h:44:7: error: redefinition of ‘num_intrinsics’`. This happenned after I installed `llvm` from pacman to solve some dependencies with the project.

Is there a specific version I'm missing out? `make clean` on jbuild folder doesn't solve this problem.

The building log can be found here (only the last couple of lines appear to be relevant): https://gist.github.com/henriquelalves/1286e4fe39a35c8c6e416fa949689c8e

**Comment by mundusnine** [comment]
THe IDE is windows only apparently: https://github.com/beefytech/Beef/issues/135

**Comment by henriquelalves** [comment]
Oh damn. It looks like that would be a problem I would have after successfully building this step, tho. Should I keep this issue open?

**Comment by bfiete** [comment]
What do you mean "installed llvm form pacman"? Did you not use build.sh to build llvm?

**Comment by henriquelalves** [comment]
I did, but `llvm-config.h` header was missing, so I installed the LLVM libraries through the Arch Linux repository. This certainly is the root of the problem, but which library I'd have to install to fix that dependency?

(Another dependency I had trouble with was `backtrace.h` header, which I solved installing the `libbacktrace-git` in the AUR repository).

**Comment by Pseudooo** [comment]
> I did, but `llvm-config.h` header was missing, so I installed the LLVM libraries through the Arch Linux repository. This certainly is the root of the problem, but which library I'd have to install to fix that dependency?

I'm currently experiencing the same issue, I'm running Ubuntu 20.04 and when i try to run build.sh it fails due to the lack of `llvm-config.h`.

If you find a fix please update!
