### ISSUE TITLE
Crash while hovering call parameters

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1438]
Probably related to https://github.com/beefytech/Beef/commit/cd3318cc3e9d248c39dce6e91b3ca615caab086a.

https://user-images.githubusercontent.com/86157825/153724848-6dc37421-caa9-4954-9385-ba814baeb7e4.mp4

Tested with https://github.com/beefytech/Beef/commit/d9ba98486ec3159b9496613dbe0d4635b20ae1d1

**Comment by bfiete** [comment]
Fixed at a277fa18cf78eda0837b381fa353ad984a63e604
