### ISSUE TITLE
Crash in StreamWriter, mEncoding is null

### ISSUE THREAD

**Issue by jayrulez** [beefytech/Beef#1442]
When the sample in my Bulkan library is run in release mode, it hits this line https://github.com/jayrulez/Bulkan/blob/master/Bulkan/src/NativeLibrary.bf#L68
which eventually calls into https://github.com/beefytech/Beef/blob/master/BeefLibs/corlib/src/IO/StreamWriter.bf#L62

At this point, mEncoding is null which causes a crash.

You can reproduce it by cloning this repo: https://github.com/jayrulez/Bulkan and running the VulkanTriangle sample program in Release mode. Works fine in Debug mode.

**Comment by disarray2077** [comment]
I have this issue but only when I change the StaticInitPriority of a type, so your issue most probably is because your static class happened to initialize before the Console class. I guess a solution to this is increasing the Console `StaticInitPriority` to higher than the default.

**Comment by bfiete** [comment]
Console issue fixed @ 8b01d806d073f00fd033d28a8585f1d8e5c85ce2
Init order differences between Debug/Release builds fixed @ 9bce9f2ce7abd53813e1e6a6cfdb1230d73959b5
