### ISSUE TITLE
[Enhancement] Improve delegate equality

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1446]
Beef's implementation of `Delegate.Equals` currently doesn't work for the use case below. I found this while porting some C# code to Beef.

In C# the below code runs `act` only one time:
```cs
            Action act = null;

            for (int i = 0; i < 10; i++)
            {
                Action newAct = () =>
                {
                    Console.WriteLine("act");
                };

                if (act == null || !Delegate.Equals(act, newAct))
                {
                    act = newAct;
                    act();
                }
            }
```

While in Beef the (almost) same code runs `act` every loop:
```bf
	Action act = null;

	for (int i = 0; i < 10; i++)
	{
		Action newAct = new () =>
		{
			Console.WriteLine("act");
		};

		if (act == null || !Delegate.Equals(act, newAct))
		{
			delete act;
			act = newAct;
			act();
		}
	}
```

**Comment by bfiete** [comment]
Improved at a3a8bfa40cebab551ea91a848a428f0a9ab4483a
- Operator == is now implemented (as in C#)
- Delegates are hashable
- lambdas with captures will actually compare the captured fields
