### ISSUE TITLE
[Enhancement] Recursive lambda

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1449]
Example code:
```
	Action act = null;
	act = new () =>
	{
		Console.WriteLine("{0}{1}", "act ", act);
	};
	act();
```

The above code works in C# but `act` is null in Beef.

**Comment by bfiete** [comment]
C# doesn't do capture-by-value, only capture-by-reference. It's actually more complicated than that - it actually rewrites the entire method so that 'act' isn't even a local variable anymore, it's a member reference of a closure state even when accessed outside of the lambda. 

I think the best we can do is to allow you to specify an `[&act]` capture by reference (you can't capture reference types by reference currently)

**Comment by bfiete** [comment]
This is the basic transformation in C#.
Which, yes, means that you get a perf hit on `act` for class field access instead of direct local variable access, but also you get hit with a heap allocation for every call into that method even if you don't end up taking a branch that actually allocates the lambda!

```C#
class State
{
	Action act;
}
State state = new State();

state.act = null;
state.act = new () =>
{
	Console.WriteLine("{0}{1}", "act ", state.act);
};
state.act();
```

**Comment by bfiete** [comment]
Also, of course this is the kind of case where you would probably just use a local method instead of a lambda :-)

**Comment by disarray2077** [comment]
> I think the best we can do is to allow you to specify an `[&act]` capture by reference (you can't capture reference types by reference currently)

That wouldn't work for me since I need to call the delegate from outside the method on which it is created.

> This is the basic transformation in C#. Which, yes, means that you get a perf hit on `act` for class field access instead of direct local variable access, but also you get hit with a heap allocation for every call into that method even if you don't end up taking a branch that actually allocates the lambda!

Oh, I see, I knew about this transformation but I didn't think about it in this case 😓
I don't mind about perf hit in this case since this code isn't called very often, so I came up with the code below based on the transformation that you provided, it works perfectly and isn't too ugly so I'm happy with it :)
```
	class RecursiveLambdaHelper<TDlg> where TDlg : var
	{
		private typealias TRet = GetInvokeReturn<TDlg>.Type;

		public TDlg act;

		public static TDlg Create(delegate TRet(TDlg) dlg)
		{
			Self s = new .();
			delegate TRet() act = new () =>
			{
				defer delete dlg;
				return dlg(s.act);
			} ~ delete s;
			s.act = act;
			return s.act;
		}
	}

	Action act = RecursiveLambdaHelper<Action>.Create(new (self) =>
	{
		Console.WriteLine("{0}{1}", "act ", self);
	});
	act(); // just works!
```
Maybe something like this could be done automatically by Beef when it's detected that a delegate is trying to capture itself... Not sure how feasible this is though, or even if this hidden allocation would be desirable in Beef...

**Comment by bfiete** [comment]
Hm. I guess it could also be possible to have something like `@this` evaluate to the delegate address... I suppose that could be generally useful for lambdas that need to remove themselves from an Event...

**Comment by disarray2077** [comment]
> Also, of course this is the kind of case where you would probably just use a local method instead of a lambda :-)

I don't think this would be possible since my usage is a little more complex than what I'm showing in the issue, I need to insert the delegate in a list of delegates, and I need the delegate to remove itself from the list when it's called. 

> Hm. I guess it could also be possible to have something like `@this` evaluate to the delegate address... I suppose that could be generally useful for lambdas that need to remove themselves from an Event...

Yeah, this is literally what I was trying to do :^)
My code currently looks kind of like this:
```
		delegate void MoveEventHandler(int x, int y);

		static List<MoveEventHandler> list = new .() ~ delete _;

		public static void BindOnce()
		{
			list.Add(RecursiveLambdaHelper2<MoveEventHandler>.Create(new (act, x, y) =>
			{
				Console.WriteLine("{0} {1}", x, y);

				if (list.GetAndRemove(act) case .Ok(let removed))
					delete removed;
			}));
		}

		public static int Main(String[] args)
		{
			BindOnce();

			// ...

			for (let act in list)
				act(10, 10);

			// list is now empty and act is already deleted.

			return 0;
		}
```

**Comment by bfiete** [comment]
Actually pretty trivial to implement @ e83d9f5bae3ca7515f2c3fa5b7e535de44a16095
