### ISSUE TITLE
`CrashCatcher::Get()` returns bad pointer if Beef DLL is unlinked, then a different Beef DLL is linked within the same process runtime

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1455]
We have a use case with our game logic development DLL, where basically it needs to be unlinked, updated, and relinked with our editor. This is so devs can make changes to the logic without having to restart the editor and lose their place. We also do it this way in order to maintain compatibility with our C++ game logic DLLs.

Currently, I'm getting a crash when I try to do that, related to the `CrashCatcher`. Because `CrashCatcher` uses the shared memory map file to store the shared `CrashCatcher` pointer, the pointer stored on there is going bad once the outgoing DLL is unlinked. When you try to link the incoming DLL, the PID matches and `CrashCatcher::Get()` returns the stale pointer from the unlinked DLL.

![image](https://user-images.githubusercontent.com/775593/154185043-460bf67f-e151-490f-acc5-f787ba2fbe86.png)

Could the `CrashCatcher` be made to cleanly shut down if all Beef DLLs are unlinked from a process, so it can properly reinitialize in this case?

If that doesn't work, could you make the CrashCatcher registration flag explicit in the build settings? (Right now it seems like it depends on the Object Debug Information.) Then we could simply disable the CrashCatcher in the DLL and host it in our engine runner EXE.

**Comment by bfiete** [comment]
Fixed at 1b217e96aa169606b70856fbbe5238ac98464d80
