### ISSUE TITLE
extension of inner type affects its accessibility modifier

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1458]
without **public extesion** in the inner extension, the compiler will complain

```
namespace System
{
	namespace Collections
	{
		extension Dictionary<T1,T2>
		{
			// @report: 'public' is necessary here, otherwise Dictionary.bf complains about inconsistent accessibility of Enumerator when returning it from GetEnumerator
			extension Enumerator {}
		}
	}
}
```

EDIT:
adding ``extension KeyValuePair {}`` into the dictionary extension block also yields some weird error, in **both** files, although i'm not sure that extension is even a valid thing.

**Comment by bfiete** [comment]
Fixed at c91c81f77d0123609269a22ebfde11cd19239d8a
