### ISSUE TITLE
Crash when opening project

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1461]
After installing nightly from 2/17/2022 my project instantly crashes upon opening. It worked fine with previous version so it's something related to allowing custom attributes at comptime. 
Project sent to email.

**Comment by bfiete** [comment]
There were a couple issues in there- one with comptime field custom attributes, and one with interface generic methods with default implementations. Both fixed at 88121831e212c16e7b9dbc70896df89c6c1c1882
