### ISSUE TITLE
`IOnMethodInit` crash

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1467]
The below code crashes, I'm not sure what exactly is causing the crash but I guess it's `IOnMethodInit` since I never used it before.

```
[AttributeUsage(.Method)]
public struct StaticalizeStringReturnAttribute : Attribute, IOnMethodInit
{
	[Comptime]
	public void OnMethodInit(MethodInfo methodInfo, Self* prev)
	{
		Type type = methodInfo.DeclaringType;
		String code = scope .();

		Compiler.EmitTypeBody(type, scope $"private String _a;");
	}
}

[StaticalizeStringReturn]
public static String TickCount => Environment.TickCount.ToString(.. scope .());
```
Tested with https://github.com/beefytech/Beef/commit/e5f280de328afc1af00bbcd24dd265da8b039b78

**Comment by bfiete** [comment]
First issue fixed at 6f8ee9aef0bd0e7ef3d7580fbc27746a140ffd63 - but you can only emit to the type body during type init, so it's too late here and you'll get an error.

Second issue fixed at f8d6f1405a92e1a31bef13f42339a5efc897be28

**Comment by disarray2077** [comment]
>but you can only emit to the type body during type init, so it's too late here and you'll get an error.

Dang, I saw that this was working with `Bitfield` for fields and thought it would also work for methods... 😑 
Well, It was worth a try.

**Comment by bfiete** [comment]
I'm going to make a commit tomorrow that will allow for this:

```C#
[AttributeUsage(.Method)]
public struct StaticalizeStringReturnAttribute : Attribute, IOnTypeInit, IOnMethodInit
{
	[Comptime]
	public void OnMethodInit(MethodInfo methodInfo, Self* prev)
	{
		Compiler.EmitMethodExit(methodInfo, "@return = __StringReturn..Set(@return);");
	}

	[Comptime]
	public void OnTypeInit(Type type, Self* prev)
	{
		if (prev != null)
			return;
		Compiler.EmitTypeBody(type, scope $"static String __StringReturn = new .() ~ delete _;");
	}
}
```

I mean, _if_ you wanted to do that..

**Comment by disarray2077** [comment]
Yes, this is basically what I wanted to do, thanks!

**Comment by bfiete** [comment]
You can also iterate through the methods with `OnTypeInit` and check for the attribute with `GetCustomAttribute`...

One issues is generic methods - each specialization will generate a different method, so you'd need to share a variable between them.

Still- even if each method has a different variable, the string will be trashed if someone makes another call to the same method before reading the result... it would make for a bit of a strange public-facing API. Also there's the issue of thread safety, but that's solvable...

**Comment by disarray2077** [comment]
@bfiete Looks like that code isn't actually working, the String gets destroyed before `Set` is called...
![image](https://user-images.githubusercontent.com/86157825/155794168-c51cf665-8529-43e2-a4d8-8a66016c7afe.png)

**Comment by bfiete** [comment]
The method exit is similar to having a `defer` block on the first line of your method - any scope-allocated strings will exit scope _before_ that block executes. 

I don't think it make sense to change that order of operations...

**Comment by disarray2077** [comment]
I just realized that this can be solved by doing something like this:
```cs
			[Comptime]
			public void OnMethodInit(MethodInfo methodInfo, Self* prev)
			{
				Compiler.EmitMethodEntry(methodInfo, "String returnValue = __StringReturn..Clear();");
				Compiler.EmitMethodExit(methodInfo, "@return = returnValue;");
			}

			[Comptime]
			public void OnTypeInit(Type type, Self* prev)
			{
				if (prev != null)
					return;
				Compiler.EmitTypeBody(type, scope $"static String __StringReturn = new .() ~ delete _;");
			}
```
So I can just replace `.. scope .()` with `.. returnValue` 👍

**Comment by disarray2077** [comment]
Hm... I tried to do the following and it didn't work:
```
		[AttributeUsage(.Method)]
		public struct StaticalizeStringReturnAttribute : Attribute, IOnTypeInit, IOnMethodInit
		{
			private static int counter = 0;
			private int id = ++counter;

			[Comptime]
			public void OnMethodInit(MethodInfo methodInfo, Self* prev)
			{
				Compiler.EmitMethodEntry(methodInfo, scope $"String returnValue = __{id}..Clear();");
			}

			[Comptime]
			public void OnTypeInit(Type type, Self* prev) mut
			{
				if (prev != null)
					return;
				Compiler.EmitTypeBody(type, scope $"static String __{id} = new .() ~ delete _;");
			}
		}
```
It looks like `OnTypeInit` only runs for one attribute, is this right @bfiete?

**Comment by disarray2077** [comment]
This is strange, the below code works:
```
		[AttributeUsage(.Method)]
		public struct StaticalizeStringReturnAttribute : Attribute, IOnTypeInit, IOnMethodInit
		{
			private int id;
			public this(int id) => this.id = id;

			[Comptime]
			public void OnMethodInit(MethodInfo methodInfo, Self* prev)
			{
				Compiler.EmitMethodEntry(methodInfo, scope $"String returnValue = __{id}..Clear();");
			}

			[Comptime]
			public void OnTypeInit(Type type, Self* prev) mut
			{
				Compiler.EmitTypeBody(type, scope $"static String __{id} = new .() ~ delete _;");
			}
		}
```
but if you replace
```
			private int id;
			public this(int id) => this.id = id;
```	
with
```
			private static int counter = 0;
			private int id;
			public this() => this.id = ++counter;
```
it doesn't work anymore, all attributes use the id `1`...

**Comment by bfiete** [comment]
With comptime you basically get a clean VM for every comptime invocation. With the `prev` argument, we explicitly serialize and then deserialize the attribute for subsequent execution.
