### ISSUE TITLE
ide variable debug hover info hard crash with mixins

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1476]
I've discovered this weeks ago, but now i've got a repro case. hovering over variables in the sourceViewPanel when debugging sometimes hard-crashes the ide when it's within a mixin (or something like that).

For repro, grab bon, search for "\@report", set a breakpoint in that line, step into the mixin, hover over the "val" variable in the mixin's last line.

**Comment by bfiete** [comment]
Fixed at 28a03fcc4b9f3acccbf74beefb6596d3cde7eda2
