### ISSUE TITLE
Platform Manager is broken

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1479]
"Platform Manager" currently can't properly delete/rename platforms. Deleting most of the time simply doesn't work and renaming doesn't rename; if you didn't try to delete the platform being renamed, it will just create another platform, but if you did try to delete then renaming will do nothing.

In the below video I demonstrate all these issues:

https://user-images.githubusercontent.com/86157825/156059019-ad815f16-2021-413e-a815-aa0156b3698e.mp4

**Comment by bfiete** [comment]
Fixed at c3f7a996e0c548e9f01e2351e4f7b33b86354947
