### ISSUE TITLE
Crash while debugging crash dump

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1482]
Some crashes are happening when you try to debug crash dumps, they seem to happen mostly when you hover identifiers in Beef code.

Example crash dump:
https://github.com/beefytech/Beef/files/7982418/crash1.zip

Video demonstrating the crash:

https://user-images.githubusercontent.com/86157825/156234773-e6279365-1d1e-4d11-8a6a-c3712146944f.mp4

**Comment by bfiete** [comment]
I think that should be fixed with a change that was included in the collapsible regions commit from earlier today.

**Comment by bfiete** [comment]
Btw- I can't use crash dumps from your own builds, only from "official" builds.

**Comment by bfiete** [comment]
Hm, I really can't trigger this, even in a release build. Could you do it with the last nightly build and send the crash dump?

**Comment by bfiete** [comment]
That'll do it!
13eee411a9ab2e0e704e35a9097870ee95ba8306
