### ISSUE TITLE
const string doesn't evaluate to a constant value anymore

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1486]
The code below fails to compile with the error `Expression does not evaluate to a constant value`:
```
		const String DllName = "test.dll";

		[Import(DllName)]
		public static extern void Test();
```
Tested with https://github.com/beefytech/Beef/commit/080dadb24bb1b6a1cf7054785ad1f4a87200743d

**Comment by bfiete** [comment]
Fixed at e11c4aa0fefb8cc441fd06847f90ac0ffb9372a8
