### ISSUE TITLE
Installer Crashes on Windows 7 64bit (Failed to load Installer UI)

### ISSUE THREAD

**Issue by mmutee** [beefytech/Beef#149]
Trying to install "BeefSetup_0_42_2.exe"

I get the error

FATAL ERROR: Failed to load installer UI
'Path\temp\BeefinstallerUI.dll'

I looked for system requirements but couldn't find any. Does this run on Windows 7?

**Comment by bfiete** [comment]
This should fix your issue. Reopen if not.
https://www.youtube.com/watch?v=VXce98z-pyM
