### ISSUE TITLE
Corrupted `params`

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1491]
The assertion in the following code fails, but it clearly shouldn't, so it looks like `params` is getting corrupted.

```
		public Result<Variant> TestV(ref Variant a, params Span<Variant> s)
		{
			Debug.Assert(s.Length == 3);
			return .Err;
		}

		public static int Main(String[] args)
		{
			var f = default(Variant);
			let v = Variant.Create((int32)1);
			let va = Variant.Create(1);
			scope Program().TestV(ref f, v, va, va);

			return 0;
		}
```
Tested with https://github.com/beefytech/Beef/commit/1223395a01a6989419a69b94e0a25ead35f31bfc

**Comment by bfiete** [comment]
Fixed at 84d4084f8347349a09c9df7b6c45fd1b86bb154a
