### ISSUE TITLE
IDE is Not Responding after typing 'typealias char = char8;' under namespace line

### ISSUE THREAD

**Issue by gopakumar-gg** [beefytech/Beef#1493]
Steps for reproducing the issue.
1.  Create a workspace and a console application.
2.  type typealias char = char8;  above the class definition.   You can see a red line appears under char8.
3.  Right click anywhere in the editor.   IDE become unstable
![typealias](https://user-images.githubusercontent.com/36254079/156910264-b0f4b5aa-4f16-4da5-8059-0d646d4d0e55.PNG)

**Comment by gopakumar-gg** [comment]
I am using 4th March Nightly build

**Comment by bfiete** [comment]
Note: also check to see if this is the same thing `typealias MyType<T> = MyType<T>`

**Comment by gopakumar-gg** [comment]
Yes, I think so.  IDE becomes Not Responding with any of the below statements too.

typealias MyType<int> = MyType<int>;  // Defined MyType as a class template above this.
typealias MyType = MyType;  // Defined MyType as a structure before this.

**Comment by bfiete** [comment]
Fixed at 69028249d74f60691914bc308ba49303a51ef1e6
