### ISSUE TITLE
IDE crashes when typing square brackets in method signature

### ISSUE THREAD

**Issue by DerTee** [beefytech/Beef#1495]
Beef version: commit 1223395a01a6989419a69b94e0a25ead35f31bfc (from 03/03/2022 21:56:10)

When I tried changing a method parameter from an `Array1<T>` to a `T[]` while being confused about the syntax and first typing `[]` without the `T` in front the Beef IDE crashed.
![image](https://user-images.githubusercontent.com/4346532/157741942-211b85a7-81ef-4f54-886c-666610a62e3d.png)

Steps to reproduce with minimal example:
 1. create an empty workspace + new project + new class
 2. copy paste this into the class file:
```
namespace crash
{
	class CrashIDE
	{
		public static void Crash()
		{
		}
	}
}
```
 3. type, not paste `[]` into the Crash() function signature, so that you would get `public static void Crash([])`
 4. -> IDE crashes

[crashdump-beef-ide__array_in_method_signature.zip](https://github.com/beefytech/Beef/files/8226753/crashdump-beef-ide__array_in_method_signature.zip)

**Comment by bfiete** [comment]
Fixed at 323e69bbd6a7ec9f688f0d8ce541d86c3398fe73
