### ISSUE TITLE
[BUG] Linux - Segfault when running compiler tests

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1499]
After updating to 0feaade from 1223395 the `./BeefBuild_d -proddir=../../IDEHelper/Tests -test` segfaults with this output: 
```
Testing IDEHelper/Tests in BeefBuild_d
Compiling for testing...
[malloc(): invalid size (unsorted)
./build.sh: line 77: 36384 Aborted                 (core dumped) ./BeefBuild_d -proddir=../../IDEHelper/Tests -test
```
Size passed into `malloc` is `32`
Tried googling `malloc(): invalid size (unsorted)` and someone suggested memory corruption somewhere in code.
Stacktrace: [link](https://pastebin.com/mjDe0W8w)
core dump: [core.BeefBuild_d.1000.7775aabe6d96430e81413e5fc5098753.50921.1647565776000000.zip](https://github.com/beefytech/Beef/files/8301610/core.BeefBuild_d.1000.7775aabe6d96430e81413e5fc5098753.50921.1647565776000000.zip)

Build machine info:
```
Operating System: Manjaro Linux
Release:	21.2.5                  
Kernel: Linux 5.15.28-1-MANJARO
Architecture: x86-64
```

Note that this only happens with debug `BeefBuild_d`, release `BeefBuild` completes these tests successfully. I will be glad to provide any additional assistance.

**Comment by bfiete** [comment]
Fixed at 676e7988fb5176ca4ed45dc13ba80f08e3d8ceca

I hadn't used valgrind before, but I used it to fix this issue and ended up finding some other dormant issues as well.
