### ISSUE TITLE
Ambiguity between null conditional member access and conditional

### ISSUE THREAD

**Issue by rumbu13** [beefytech/Beef#15]
return hasErrors ?.Err :.Ok; // equivalent to "if (hasErrors) return .Err else return .Ok

In the case above ?. is considered a single operator instead of two. This can be avoided by putting a space between ? and ., but since hasError is not a nullable, my expectation was that the compiler will figure it out.

**Comment by bfiete** [comment]
Parsing is not entirely space insensitive. Here's another case where spacing matters (also legal in C, C#, and other languages):
```
int c = a - --b;
```
vs
```
int c = a - - -b;
```

You're right that your example is something someone might actually try. But consider the case:
```
int? len = useStr ? str?.Length : null;
```
One the cases start getting more complex then it's not so easy to disambiguate those, especially not at parse time.
