### ISSUE TITLE
Error while building from source 

### ISSUE THREAD

**Issue by heisluft** [beefytech/Beef#1502]
While performing a build of beef from source (including first building llvm), I get the following error when trying to build BeefBuild:
```log
Building BeefBuild
[******************************]
Beef compilation time: 18.81s
lld-link: error: Unknown attribute kind (70) (Producer: 'LLVM13.0.1' Reader: 'LLVM 11.0.0')
Execution Failed
Executing Command: CopyToDependents("$(ProjectDir)/dist/BeefySysLib64.dll")
Executing Command: CopyToDependents("$(ProjectDir)/dist/BeefySysLib64.pdb")
ERROR: BUILD FAILED
=================FAILED=================
Press any key to continue . . .
```
I took the lld-link.exe from the latest beef installation (freshly installed BeefSetup 0.43.1)
Is this some kind of error on my end (LLVM is freshly cloned and lld is from latest official install though)?
Cheers

**Comment by bfiete** [comment]
Take the lld-link.exe from the latest nightly build at https://nightly.beeflang.org/BeefSetup.exe

**Comment by heisluft** [comment]
That worked like a charm, thank you!
Perhaps it would be helpful to note that newer Versions need the latest nightly to be installed and cannot simply be built with the last release lld in the Readme?
