### ISSUE TITLE
Constructor of empty struct cannot evaluate to const value

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#1506]
In the example below the declaration of `ConstValue` as well as the call of `DoStuff` throw the error "Expression does not evaluate to a constant value". As soon as you add a field to MyStruct it compiles just fine

```bf
struct MyStruct
{
	public this() {  }

	public const MyStruct ConstValue = MyStruct();
}

class Program
{
	static T DoStuff<T>(T value = T()) where T : struct, new
	{
		return value;
	}

	static int Main(String[] args)
	{
		MyStruct s = DoStuff<MyStruct>();

		return 0;
	}
}
```

**Comment by bfiete** [comment]
Fixed at b5ddc1c24b149d5bdee9cc5ca1fd959384582be1
