### ISSUE TITLE
Beef IDE - Caret end-line snapping

### ISSUE THREAD

**Issue by erherhh4herh** [beefytech/Beef#151]
This is a quality-of-life improvement to the IDE that could be added as an option (or maybe it already is, or is planned?) In visual-studio (and many other IDEs) the typing caret is snapped to the end of the line when clicking on it. Videos speak louder than words, so here's an example:

Visual Studio:
![image](https://i.imgur.com/0qLnL1f.gif)

Beef IDE:
![image](https://i.imgur.com/OdVy3cI.gif)

Thank you for your time,
erherhh4herh.

**Comment by HydrogenC** [comment]
This is actually the same as the text editor of Delphi, but I personally prefer the visual studio editor.

**Comment by bfiete** [comment]
This is now an editor setting called "Free Cursor Movement" which defaults to 'off' for the moment. https://github.com/beefytech/Beef/commit/562b565f49c8f48e16c32c64667e8b67feca93d6, will be in release 0.42.4
