### ISSUE TITLE
[WASM] Bad path format for Beef042RT32_wasm.a

### ISSUE THREAD

**Issue by andreakarasho** [beefytech/Beef#1512]
The file is actually located in
`C:\Program Files\BeefLang\bin\Beef042RT32_wasm.a`
The `BeefBuild`  [and the IDE] cuts the `C:\Program` due to the whitespace i guess

```
emcc: error: Files/BeefLang/bin/Beef042RT32_wasm.a: No such file or directory ("Files/BeefLang/bin/Beef042RT32_wasm.a" was expected to be an input file, based on the commandline arguments provided)
```

**Comment by bfiete** [comment]
Fixed at 166ff4d5e3329dca9ce3f48b228d1fa76d1b8026
