### ISSUE TITLE
[WASM] build_wasm.bat distribuited with the precompiled IDE has wrong paths inside

### ISSUE THREAD

**Issue by andreakarasho** [beefytech/Beef#1513]
Steps to reproduce:
- download nightly build 
- go to `C:\Program Files\BeefLang\wasm\src`
- run the `build_wasm.bat`

The workaroud is to download the source, run the script, copy & paste `Beef042RT32_wasm.a` to `C:\Program Files\BeefLang\bin`

**Comment by bfiete** [comment]
Fixed in the next nightly
