### ISSUE TITLE
using Ctrl+R in a source file while in safe mode crashes the IDE

### ISSUE THREAD

**Issue by MoshiBar** [beefytech/Beef#1514]
put the IDE into safe mode, focus on a source file and press Ctrl+R

**Comment by Fusioon** [comment]
Just to add, IDE will crash when safe mode is active and user uses any operation requiring compiler instance.  

Found problem with: 
- Go to definition
- Find all references
- Rename Symbol

Tested with: Nightly 04/02/2022 ee27f6f

**Comment by bfiete** [comment]
Fixed at 0ee3259eb123a7293f508376f7258b61cc123276
