### ISSUE TITLE
[BUG] Rename symbol doesn't work properly with fields in auto constructor

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1516]
Code to reproduce:
```
struct Foo : this(int x)
{

}

public static void Main()
{
    Foo f = .(5);
    Console.WriteLine(f.x);
    Console.WriteLine(f.x);	// Renames both
}
```
When you try to rename symbol `x` in constructor it renames only in the constructor and when you rename `x` on any of the `Console.WriteLine` it renames both but not the field.

Tested with: (Nightly 04/02/2022)

**Comment by bfiete** [comment]
Fixed at 44ecb9231549356d4bdbf8152af3abdb899834e5
