### ISSUE TITLE
cannot rename tuple field

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1518]
Named tuple members cannot be renamed with CTRL+R, renaming it on the assignment only renames that instance of it.
```bf
public static void Main()
{
	(int a, int b) thing;
	thing.a = 5;
	thing.a = 1;
}
```

**Comment by bfiete** [comment]
Would you imagine that renaming 'a' would rename _every_ instance of `(int a, int b)` in the entire workspace?

C# does not allow renaming tuple fields...

**Comment by EinScott** [comment]
Yea i guess i was expecting it to rename it on that thing's type only, but i can still see how that causes problems... i didn't really think this through enough. I guess it's a bit weird that you can rename the a's on the assignments, which does nothing special, but thats not a *real* problem either. Feel free to close this.

**Comment by bfiete** [comment]
In the latest nightly you get a proper error when you attempt this.
