### ISSUE TITLE
va_list is not treated properly on aarch64

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1520]
Currently, `va_list` is treated as `void*` for interop purposes. However, on `aarch64`, `va_list` is a struct and has to be treated as such.

The [calling convention docs](https://c9x.me/compile/bib/abi-arm64.pdf) describe the layout as
```C
struct __va_list {
    void *__stack;
    void *__gr_top;
    void *__vr_top;
    int __gr_offs;
    int __vr_offs;
}
```

---

I did attempt a workaround which almost worked:

Beef calling frame:
```bf
[System.InlineAttribute] public static void Print(char8* destChars, uint32 maxLength, char8* format, ...)
{
	System.VarArgs vArgs = System.VarArgs();

	vArgs.Start!();
	Print_VA(destChars, maxLength, format, vArgs.ToVAList());
	vArgs.End!();
}
```

C++ receiving frame:
```cpp
void String::Print_VA(char8 *destChars, uint32 maxLength, const char8 *format, void *argPtr)
{
	va_list args = *(va_list*)argPtr;
	stbsp_vsprintf(destChars, format, args);
}
```

Dereferencing `argPtr` did yield a valid `va_list` struct, but the `format` pointer was invalid, and instead was filled with the binary values for the `__gr_offs` and `__vr_offs` fields. So it seems that calling convention is incorrect, and `va_list*` lining up with the valid data was merely coincidental

**Comment by bfiete** [comment]
Out of curiousity-

if in VarArgs you change `int[3] mVAListl` to `int[5] mVAList;`, does that fix this workaround example?

**Comment by hunterbridges** [comment]
Ah ok, yes, that does fix the workaround on Switch.

However, now there is an issue when running on Windows due to different levels of indirection used in `ToVAList` whether you're on Windows or not. But, if I also change that function to simply this:

```bf
public void* ToVAList() mut
{
	return &mVAList;
}
```

then I can use the same code in `Print_VA` above and get consistent results on both platforms

**Comment by bfiete** [comment]
Just to check - does the `int[5]` change not fix the normal `ToVAList()` usage without the extra dereference hack?

It seems that it should.

**Comment by hunterbridges** [comment]
It does fix it on aarch64. However the dereference hack is to make it so where consumers on the C++ side do not have to treat the incoming va_list pointer argument differently depending on the platform

**Comment by hunterbridges** [comment]
So the way to make it work without the additional dereference would be to just pass the va_list struct by value on platforms where it is a struct

**Comment by bfiete** [comment]
Um I think I'm confused.

I thought the other platforms _already worked_ before this issue was posted.

I'm simply asking: does the sole change of making `int[3]` an `int[5]` completely fix the issue if you revert everything else back how it was before this issue was ever posted?

**Comment by bfiete** [comment]
On aarch64, passing `va_list` by value _does_ lower to passing a copy by address. That's what we were already doing. I think the issue was just that there wasn't enough memory reserved for the values that needed to be placed in it.

Look at this - https://godbolt.org/z/9aEToY5cY
You can see the va_list gets lowered to a simple pointer:
`define dso_local void @_Z12VAListMethodSt9__va_list(%"struct.std::__va_list"* noundef %0)`

**Comment by hunterbridges** [comment]
> does the sole change of making int[3] an int[5] completely fix the issue if you revert everything else back how it was before this issue was ever posted?

It does fix the va_list itself, which was getting corrupted at first. But you still have to dereference it on the receiving side in order to work with it, and you don’t on Windows.

**Comment by hunterbridges** [comment]
A limiting factor is that clang is super picky about how it lets you cast with va_list. You can’t cast the incoming arg directly to it

**Comment by bfiete** [comment]
On the C size you should be able to just directly declare the parameter type as `va_list` with no pointer. No dereference.

**Comment by bfiete** [comment]
For all platforms.

**Comment by hunterbridges** [comment]
Ah yeah of course, that makes sense. I can try that tomorrow

**Comment by hunterbridges** [comment]
Yep, I have confirmed it works on Windows and aarch64.

**Comment by bfiete** [comment]
Okay so we can close this, yes?
