### ISSUE TITLE
Intermittent stack alignment faults on aarch64

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1521]
Testing on Switch, we have run into intermittent cases where certain stack frames emit a stack alignment fault.

This seems like it may be related to [Stack Pointer Register usage rules](https://developer.arm.com/documentation/dui0801/a/Overview-of-AArch64-state/Stack-Pointer-register)

[This article](https://community.arm.com/arm-community-blogs/b/architectures-and-processors-blog/posts/using-the-stack-in-aarch32-and-aarch64) has a more in-depth break down of the stack usage rules on aarch64

---

We have noticed this occurring in an implicit conversion operator used as a temporary value in a method call to our C++ API. Beef Disassembly is here:

```asm
		public static implicit operator VertexStyle(Color color)
0x08370688:    sub			 sp, sp, #48 ; 0x30 ; RSDK::VertexStyle::operator RSDK.VertexStyle(RSDK::Color$part) 
0x0837068C:    str			 x30, [sp, #32] 
0x08370690:    stur			 x0, [sp, #28] 
			return VertexStyle(color);
0x08370694:    ldur			 x1, [sp, #28] 
0x08370698:    add			 x0, sp, #8 
0x0837069C:    bl			 0x8370514 ; RSDK::VertexStyle::__BfCtor(RSDK::Color$part) 
0x083706A0:    ldrh			 w13, [sp, #8] 
0x083706A4:    ldrh			 w12, [sp, #10] 
0x083706A8:    ldrh			 w11, [sp, #12] 
0x083706AC:    ldrh			 w10, [sp, #14] 
0x083706B0:    ldrb			 w9, [sp, #16] 
0x083706B4:    ldrb			 w8, [sp, #17] 
0x083706B8:    strh			 w13, [sp, #18] 
0x083706BC:    strh			 w12, [sp, #20] 
0x083706C0:    strh			 w11, [sp, #22] 
0x083706C4:    strh			 w10, [sp, #24] 
0x083706C8:    strb			 w9, [sp, #26] 
0x083706CC:    strb			 w8, [sp, #27] 
		}
0x083706D0:    ldrh			 w0, [sp, #18] 
0x083706D4:    ldrh			 w1, [sp, #20] 
0x083706D8:    ldrh			 w2, [sp, #22] 
0x083706DC:    ldrh			 w3, [sp, #24] 
0x083706E0:    ldrb			 w4, [sp, #26] 
0x083706E4:    ldrb			 w5, [sp, #27] 
0x083706E8:    ldr			 x30, [sp, #32] 
0x083706EC:    add			 sp, sp, #48 ; 0x30 
0x083706F0:    ret
```

Execution continues to `ret`, then after stepping over `ret` the runtime crashes with a stack alignment fault.

**Comment by bfiete** [comment]
LLVM is generating the actual machine code here. I would assume there's probably a calling convention issue at the IR level, but there's not enough context here to determine that.

**Comment by bfiete** [comment]
My guess would be that the stack pointer was corrupted during the return of the call _preceding_ this operator call. What happened immediately before this?

**Comment by hunterbridges** [comment]
I'll do my best to explain the context! This is happening in the `Draw` hook of an object called `FXFade`

```bf
public override void Draw()
{
	switch (blendMode)
	{
	case .ADD:
		RSDK.Graphics.SetGPUState(sVars.gpuStateAdd);
		
	case .SUBTRACT:
		RSDK.Graphics.SetGPUState(sVars.gpuStateSub);

	default:
		RSDK.Graphics.SetGPUState(sVars.gpuStateMul);
	}

	RSDK.Graphics.PushViewMatrix(matView);
	RSDK.Graphics.PushProjectionMatrix(matProj);

	RSDK.Graphics.DrawRect(0.0f, 2.0f, drawColor, .ALL_CENTER);

	RSDK.Graphics.PopViewMatrix();
	RSDK.Graphics.PopProjectionMatrix();
}
```

The call that's kicking the issue off is the call to `DrawRect`. In static builds, the signature of `DrawRect` looks like this:
```bf
[LinkName("RSDK_Graphics_DrawRect"), CallingConvention(.Cdecl)]
extern public static void DrawRect(Vector3 position, Vector2 size, VertexStyle style = 0xFFFFFFFF, Graphics.Align align = .ALL_CENTER, Matrix* transform = null);
```

---

What happens on run is, first execution continues smoothly to the `DrawRect` call in `FXFade.Draw`. Then, it starts calculating the temporary values that are to be passed into `DrawRect`.

First, it runs this `Vector3` conversion operator to convert first param `0.0f` to ` Vector3`:
```bf
public static implicit operator Vector3(float f)
{
	return Vector3(f);
}
```

Then it runs this `Vector2` conversion operator to convert second param `2.0f` to `Vector2`:
```bf
public static implicit operator Vector2(float f)
{
	return Vector2(f);
}
```

After that, it runs this `VertexStyle` conversion operator (mentioned in original post) to convert third param `drawColor` to `VertexStyle`:
```bf
public static implicit operator VertexStyle(Color color)
{
	return VertexStyle(color);
}
```

Upon returning from that operator, program crashes with stack alignment fault

**Comment by bfiete** [comment]
And what's the data definition of Vector2 and Vector3? Just 2 float members and 3 float members, respectively?

**Comment by hunterbridges** [comment]
Yeah, layout-wise they are defined as such:

```bf
[CRepr]
public struct Vector2
{
    public float x;
    public float y;
}

[CRepr]
public struct Vector3
{
    public float x;
    public float y;
    public float z;
}
```

**Comment by hunterbridges** [comment]
`VertexStyle` is a bit more unique:

```bf
[CRepr]
public struct VertexStyle
{
    // -----
    // Enums
    // -----

    public enum ColorMode : uint8
    {
        OFF,
        FLAT,
        LINEAR_GRADIENT,
        RADIAL_GRADIENT
    }

    public enum TextureMode : uint8
    {
        OFF,
        UV_FIT,
        UV_XY,
        UV_MATRIX,
        SPRITE,
        DECAL,
        GRADIENT_ID
    }

    // -------
    // Structs
    // -------

    [Union]
    public struct Param
    {
        public Color color;
        public GPUTexture texture;
    }

    // -------
    // Members
    // -------

    public Param paramA;
    public Param paramB;

    public ColorMode colorMode;
    public TextureMode textureMode;
}
```

**Comment by hunterbridges** [comment]
One thing to mention is that we weren't hitting this alignment fault issue when we were first getting Beef running on Switch back in January. So perhaps it is due to something that changed within the past 3 months?

**Comment by bfiete** [comment]
Can you get rid of the error by getting rid of some of the operator calls?
ie:
`RSDK.Graphics.DrawRect(Vector3(0.0f), Vector2(2.0f), drawColor, .ALL_CENTER);`

**Comment by bfiete** [comment]
What are Color and GPUTexture, and what do the definitions of VertexStyle and members look like on the C++ side?

**Comment by hunterbridges** [comment]
Here's `Color` in Beef (actually may be missing CRepr)

```bf
public struct Color
{
    public uint8 b;
    public uint8 g;
    public uint8 r;
    public uint8 a;
}
```

The definition for `GPUTexture` is inherited from another struct called `Asset`, and doesn't add any new members. It mainly just adds new methods and stuff.

```bf
typealias IDValue = uint16;

[CRepr]
public struct Asset
{
    public IDValue id;
}

public struct GPUTexture : Asset
{
    // Methods + enum definitions
}
````

---

Here's the C++ side:

```cpp
struct Color
{
    union
    {
        uint32 value;

        struct
        {
            uint8 b;
            uint8 g;
            uint8 r;
            uint8 a;
        };
    };
};
```

```cpp
struct Asset
{
    uint16 id;
}

struct GPUTexture : public Asset
{
    // Methods and stuff
}
```

**Comment by hunterbridges** [comment]
(I did just try adding `CRepr` attribute to the Beef `Color` struct, but it didn't fix the issue)

**Comment by bfiete** [comment]
CRepr just causes the sizeof to equal strideof (which it already does) and prevents reordering of fields by alignment size (no ordering would occur here)

**Comment by bfiete** [comment]
Just another thought - I think if you change `VertexStyle style` to `in VertexStyle style` and then on the C++ side you change it to be a `const&` then you can get around the pass-by-value struct lowering issues since you'll explicitly be passing by reference.

**Comment by hunterbridges** [comment]
Hm, a const ref may work in place of passing by value here, but in this case I don't think it's an interop issue. The execution in this case isn't making it past the `VertexStyle boxStyle = drawColor;` line in the example where I'm setting everything to a local before calling the interop function.

Another thing I thought to try is just implementing the constructor logic directly in the implicit operator like so:
```bf
public static implicit operator VertexStyle(Color color)
{
    VertexStyle style = ?;

    style.paramA.color = color;
    style.colorMode = .FLAT;
    style.textureMode = .OFF;

    return style;
}
```

^ This actually seems to work around the stack alignment fault.

Before, the implicit operator was calling the constructor, so it was more like this code path:
```
public this(Color color)
{
    this = ?;

    paramA.color = color;
    colorMode = .FLAT;
    textureMode = .OFF;
}

public static implicit operator VertexStyle(Color color)
{
    return VertexStyle(color);
}
```

Not a whole lot of difference, but I guess homes in on the discrepancy a little more?

**Comment by bfiete** [comment]
Hm. Yeah that is strange -- there's no actual interop at that point. 

And you say it's an _intermittent_ failure? That's even more strange.

Hard to believe it could be an LLVM bug... seems like it needs some real hands-on debugging to understand what exactly is going on.

**Comment by hunterbridges** [comment]
Intermittent in that it consistently happens on certain calls, but for example it's failing in the context of this `DrawRect` call, but other instances of `DrawRect` work ok. 

I am not sure if you have access to a Switch dev kit... we could either arrange a source share, or a screen share to dig in if you'd be open to it?

**Comment by hunterbridges** [comment]
Ok, I poked at it some more. I tried:

- Creating another non-constructor function that did the same thing as constructor (crashed, basically same as calling constructor)
- Inlining that function (passed, basically same as implementing that logic in the operator directly)
- Calling the constructor from a wrapper function (Crashed when returning from that wrapper function)

Then I tried simply getting rid of the nested union in the struct, so changing it to this essentially
```bf
[CRepr]
public struct VertexStyle
{
    //[Union]
    public struct Param
    {
        public Color color;
        //public GPUTexture texture;
    }

    public Param paramA;
    public Param paramB;

    public ColorMode colorMode;
    public TextureMode textureMode;
}
```

This got around the crash. So it seems to maybe have something to do with the union!

One thing to note about this union is that the members are different sizes. In Beef, `Color` is a 4 byte struct of `uint8`, and `GPUTexture` is a 2 byte struct of a single `uint16` member ( [see above](https://github.com/beefytech/Beef/issues/1521#issuecomment-1098262517) )

**Comment by hunterbridges** [comment]
A little more data... I tried flipping the script and commenting the `color` instead, leaving only the `texture` member:

```bf
[CRepr]
public struct VertexStyle
{
    //[Union]
    public struct Param
    {
        //public Color color;
        public GPUTexture texture;
    }

    public Param paramA;
    public Param paramB;

    public ColorMode colorMode;
    public TextureMode textureMode;
}
```

This exhibits the same crashing behavior as just having the full union with both members in there. Normally this struct with `color` in the inner `Param` union would be 10 bytes, but having the `Param` only be `texture` brings it down to 6 bytes.

So then I thought, well maybe its a size thing? So I just changed it to this:
```bf
[CRepr]
public struct VertexStyle
{
    uint8[4] pad;

    public ColorMode colorMode;
    public TextureMode textureMode;
}
```

Same crashing behavior. Then I tried changing around the size of `pad`. Sizes 1-6 (aka `VertexStyle` sizes 3-8) all crashed. But as soon as I set `pad` to 7 (`VertexStyle` size 9), crashing went away.

**Comment by hunterbridges** [comment]
At this point I think there may be two bugs:

- Stack alignment bug for struct sizes 8 or less
- Bug where union thinks it's the wrong size in some cases

**Comment by bfiete** [comment]
Hm. Could you set the Workspace / Beef / Intermediate Type to Object and IRCode, and then send the .beir file for the module from the type where the crashing call is occurring?

It'll be in the build directory.

**Comment by hunterbridges** [comment]
No .beir files came out, just .ll files. Here's all the ones for `VertexStyle`

[VertexStyle.zip](https://github.com/beefytech/Beef/files/8486387/VertexStyle.zip)

**Comment by hunterbridges** [comment]
Hm, something else curious. Since it seems like maybe `texture` is the problematic member in the union, and maybe making something thing `sizeof(Param)` is 2, I tried switching the position of `color` and `texture`, still was crashing. Then I tried swapping out `texture` with same-sized members (all are listed here, but I tried them one at a time).

```bf
[Union]
public struct Param
{
    public Color color;
    //public GPUTexture texture;
    //public uint16 uintVar;
    public uint8[2] pad;
}
```

So having the 2-byte `GPUTexture texture` member always crashes. Substituting the `uint16 uintVar` member also crashes. But, having `uint8[2] pad` gets around the crash

**Comment by bfiete** [comment]
Can you include the ll file that actually has the crashing call in it? IE: the actual `FXFade.Draw` call.

**Comment by bfiete** [comment]
Oh and just one more for comparison - can you do one of the "fixes" and send a Logic_FXFade.ll where it doesn't crash?

**Comment by hunterbridges** [comment]
Sure thing. I went with the "fix" of replacing `GPUTexture texture;` in the `Param` union with `uint8[2] pad`, since it seems like that is the change that is closest to the original code path

[FXFade_and_VertexStyle_with_fix.zip](https://github.com/beefytech/Beef/files/8491632/FXFade_and_VertexStyle_with_fix.zip)

**Comment by hunterbridges** [comment]
I was poking around a bit more. I diffed the bugged IR and the "fixed" IR, and noticed that the key effect of swapping the `GPUTexture` member out with the `uint8[2]` member was that the alignment of the `Param` union changed from 2 bytes to 1 bytes. (Kinda raises a tangential interop issue, as on the C++ side some of these types such as `Color` are unions with a uint32 member, where they aren't in Beef, so I assume their alignment would be 4... need to look into that)

Nonetheless, I played around with adding the `Align` attribute on some of these problematic structs. I wasn't really able to get any breakthroughs. The only thing was, if I changed `VertexStyle.Param` to have an align of 1, it worked the same as the `uint8[2] pad` workaround from earlier. Like so:

```bf
[Union, Align(1)]
public struct Param
{
    public Color color;
    public GPUTexture texture;
}
```

So I think the core issue has something to do with struct alignment. Gonna try and do more digging

**Comment by hunterbridges** [comment]
Ok I went and scrubbed all our structs that our used in our engine API. Most were ok but a few of them had aligns that didn't match up (Among them `VertexStyle` and `Color`). So I made sure all the struct aligns matched up, and now I'm no longer getting an alignment fault, but an access violation instead

**Comment by bfiete** [comment]
I did notice one issue - your definition of `Color` in Beef should have `[Align(4)]`. On the C++ side there is a 4-byte alignment requirement because of the `uint32` union member.

**Comment by hunterbridges** [comment]
Yeah, I noticed that as well and fixed it on our end. Still crashing in the same spots, but with an access violation instead of an alignment fault

**Comment by bfiete** [comment]
Fixed by https://github.com/beefytech/Beef/commit/2de490fd5914e2820ecc878ebf1775e04ea7f9a4
