### ISSUE TITLE
(aarch64) Generated offset for field members of subclass sometimes higher than expected

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1524]
In our codebase, we have a class `AudioLimiter`, which extends `AudioEntity`, which extends `Object.Entity`. In one of our Beef functions, we are creating an instance of this object, and setting some of its members. In the disassembly, all of the offsets generated for assigning the `AudioEntity` members of the instance are correct, but all of the offsets for the `AudioLimiter` members are 4 bytes higher than they should be.

The layouts look like this:
```bf
public static class Object
{
    [CRepr, AlwaysInclude(IncludeAllMethods = true)]
    public class Entity
    {
        public Entity parent;

        uint32[4] tag;

        public Vector3 position;

        public uint16 objectID;
        public uint16 slot;

        public Active active; // This is a uint8 enum

        bool processFlag;
        bool forEachFlag;
        public bool protect;
        public bool interaction;

        uint64 padding;
    }
}

[CRepr]
class AudioEntity : ObjectEntity
{
    AudioEntity[32] inputList;
    float *pcmOutput;

    uint8 inputCount;
    public Audio.ChannelConfig channelConfig;
    public Audio.MixerChannel mixerChannelID;
    bool expired;
}

[AlwaysInclude(AssumeInstantiated = true), CRepr]
public abstract class AudioLimiter : AudioEntity
{
    public bool bypass;
    public float dbInputGain;
    public float dbOutputGain;
    public float dbThreshold;
    public float attackTimeMs;
    public float releaseTimeMs;
}
```

This is what the disassembly looks like when assigning the properties:
```asm
			limiter.channelConfig = .STEREO;
0x08312CE0:    ldr			 x10, [sp, #56] ; 0x38 
0x08312CE4:    strb			 w9, [x10, #329] ; 0x149 
			limiter.mixerChannelID = .MAIN_MIXER_SFX;
0x08312CE8:    ldr			 x9, [sp, #56] ; 0x38 
0x08312CEC:    strb			 wzr, [x9, #330] ; 0x14a 
			limiter.bypass = true;
0x08312CF0:    ldr			 x10, [sp, #56] ; 0x38 
0x08312CF4:    and			 w9, w11, #1 
0x08312CF8:    and			 w9, w9, w11 
0x08312CFC:    strb			 w9, [x10, #336] ; 0x150 
			limiter.dbThreshold = -6.0f;
0x08312D00:    ldr			 x9, [sp, #56] ; 0x38 
0x08312D04:    fmov			 s0, #-6.000000e+00 
0x08312D08:    str			 s0, [x9, #348] ; 0x15c 
```

`channelConfig` and `mixerChannelID` are `AudioEntity` members, and their offsets are correct. I can confirm it in the VS debugger immediate window:
```
(ptrdiff_t)&limiter->channelConfig - (ptrdiff_t)limiter
329
(ptrdiff_t)&limiter->mixerChannelID - (ptrdiff_t)limiter
330
```

However, `bypass` and `dbThreshold`, members of `AudioLimiter`, are 4 bytes higher than expected in the disassembly. This is causing the values to be assigned to the wrong members. If I look at them in the VS debugger however, the offsets are the expected values.
```
(ptrdiff_t)&limiter->bypass - (ptrdiff_t)limiter
332
(ptrdiff_t)&limiter->dbThreshold - (ptrdiff_t)limiter
344
```

For posterity's sake, Beef IDE reports the offset of the `bypass` field as 336
![image](https://user-images.githubusercontent.com/775593/163634263-7d44d593-711e-4e8b-9612-0dca46759c5e.png)

**Comment by hunterbridges** [comment]
I realized that `sizeof(AudioEntity)` was 332, which is not evenly divisible by 8. I was able to work around this by adding `uint8[4] pad` at the end of `AudioEntity`.

Perhaps Beef expects subclass members to begin at 8-byte aligned offsets on 64-bit, and `CRepr` is tripping up some related assumptions?

Nonetheless, only seeing this on aarch64 and not x64

**Comment by bfiete** [comment]
Do you have a simplified repro case that I can actually compile myself?

**Comment by hunterbridges** [comment]
Let me see if I can get one together

**Comment by hunterbridges** [comment]
Hm... I isolated these in my minimal Switch test harness project. `sizeof(AudioEntity)` reports in both Beef and VS debugger as 336, and the offset of `bypass` is also 336.

The same `AudioEntity` class layout and inheritance structure in C++ also reports sizeof as 336, so I think 336 is the correct size (that is padded to 16 byte alignment). The actual weird thing in the original case was the size being reported as 332. I'll see if I can manage to repro that in the minimal project, but it is currently eluding me

**Comment by bfiete** [comment]
Did you figure out if there's anything to this?

**Comment by bfiete** [comment]
I guess we close this then?

**Comment by hunterbridges** [comment]
Ah woops, sorry I missed the first bump. Yeah, I wasn't able to reproduce this in isolation, so I guess we can close it
