### ISSUE TITLE
Consistent crash when calling a native Vulkan function

### ISSUE THREAD

**Issue by jayrulez** [beefytech/Beef#1526]
Here is the attached crash dump:

[ConsistentCrash.zip](https://github.com/beefytech/Beef/files/8499148/ConsistentCrash.zip)

**Comment by bfiete** [comment]
It's a Vulcan PDB parsing issue in the debugger.

Could you install the latest nightly and send another crash? I can't see the path to the bad PDB in the previous crash dump, but I made a change that should make me able to determine the path with crash dumps from the latest nightly.

Then I can tell you that path and you can attach the PDB from there and then I can figure out what's going on with it.

**Comment by jayrulez** [comment]
[VulkanBeefCrash.zip](https://github.com/beefytech/Beef/files/8515555/VulkanBeefCrash.zip)

Here's the crash dump using the latest nightly.

**Comment by bfiete** [comment]
It appears a Vulkan PDB is slightly malformed. It will now cause a soft error (just printed to the Output panel) rather than a crash, as of 1abccdedf84b72efa7817060d6dd05357ac10e32
