### ISSUE TITLE
Feature request: File scoped namespaces

### ISSUE THREAD

**Issue by jayrulez** [beefytech/Beef#1527]
File scoped name spaces can save a lot of horizontal spacing in most files since most files use a single name space.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces

It would be neat if this C# feature was adopted.

**Comment by bfiete** [comment]
Good feature, easy implementation.
Added at f3f2f4c6ecdc84e17015e66a4c95c2340fdd01f5
