### ISSUE TITLE
Can't rename properties

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1528]
As an example, trying to rename the `i` property results in "Unable to locate symbol" error.
```
		class MyTest
		{
			public int i { get; set; } = 0;
		}

		public static void Main(String[] args)
		{
			MyTest t = scope .();
			t.i = 0;
		}
```

**Comment by bfiete** [comment]
If you're building from source from today - I just made a commit that should fix that.

**Comment by disarray2077** [comment]
Yeah, I guess this must be the issue since even methods are failing to rename.
