### ISSUE TITLE
Compile time emit view - Slow syntax highlight and leaking memory

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1530]
Hi

Tried out the new Emit feature on compile time. Great feature!
Not sure of it's fully complete yet, but heres some performance issues I noticed.

When expanding, most syntax highlight colors is there, but namespace and classes is missing.
After 0.1 to 20 seconds, they appears. The amount of time seem random for each time.

When the 0.1 to 20 seconds is ongoing, a CPU core is sitting at 30% for its duration.
Here is view of the CPU core working when expanding the "Emit" multiple times.
Notice the difference in length for the same emit:
![image](https://user-images.githubusercontent.com/1075088/163715594-a11fed8f-acf0-417c-91db-7ef6d28ee0d7.png)

Memory usage is also rising steadily while this is going on (so little when it takes 0.1s, about 30MB for the 20s)
Having collapsed and expanded it multiple times, the IDE sits at about 850 MB usage. Usually it's in the 60-130MB range.

**Comment by bfiete** [comment]
Do you have an example program that demonstrates this behavior?

**Comment by bfiete** [comment]
Valgrind to the rescue again.
Fixed at ea637c56845e5e58f360336a4dc43a7d2241cb3d
