### ISSUE TITLE
Const needs to be captured and `Compiler.Mixin` doesn't cause capture

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1534]
The below code doesn't compile because `a` wasn't captured, and if you try to manually capture it using `[=a]` the compiler complains about `c` not being captured (it also doesn't work if you try to use T directly).
```
		public static void Test<T>(T c, int a = 0)
			where T : const int
		{
			delegate void() d = scope () => {
				Compiler.Mixin(scope $"Console.WriteLine({c}, a);");
			};
			d();
		}

		public static void Main(String[] args)
		{
			Test(1, 2);
		}
```

Tested with https://github.com/beefytech/Beef/commit/44ecb9231549356d4bdbf8152af3abdb899834e5

**Comment by bfiete** [comment]
Fixed at a30e539d29562e4541cdca5b5fc85a420bce5010
Also `T` should work in place of `c` now, too.

But note the `Console.WriteLine` is malformed - you probably want a `"{}{}"` format string in there.
