### ISSUE TITLE
(aarch64) Wrong pointer passed to callee when getting pointer to struct member as a temporary

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#1537]
We have a class `WickPath` which extends `PathEntity`. `PathEntity` contains a member `Path path`, and `Path` is a struct defined as such:

```bf
[CRepr, Align(8)]
struct Path
{
    public PathType pathType;
    public uint8 editorFlags;
    uint32[7] opaque;
}
```

`WickPath` has a method `WickPath.Draw()` defined as such:

```bf
public override void Draw()
{
    Matrix matWorld = Matrix.Translate(path.GetPosition());
    Graphics.PushWorldMatrix(matWorld);

    Graphics.SetDrawLighting(true);
    DrawConnectingLinesPartial(&path, 0xFFFFFFCC, 4.0f, 0.0f, 1.0f - sparkProgress);
    DrawConnectingLinesPartial(&path, 0xFF111111, 4.0f, 1.0f - sparkProgress, 1.0f);

    Graphics.SetGPUState(.UI_DEPTH);
    Graphics.DrawBox(path.GetNodeAtIndex(path.GetNodeCount() - 1).position, HITBOX_SIZE, 0xFFFFFFCC, .ALL_CENTER);
    
    Graphics.PopWorldMatrix();
}
```

We were getting a crash in the first call to `DrawConnectingLinesPartial`. That method signature looks like this:
```bf
public static void DrawConnectingLinesPartial(Path* path, Color color, float lineThickness, float progressStart, float progressEnd)
```

When I stepped through, I noticed the address to `path` was still a valid pointer in heap space, but not the calling frame's `&this.path`. So it was a valid pointer, but not a valid `Path*`.

---

Then I tried taking the pointer and storing it in a local first like so:

```bf
Path* pathPtr = &path;
DrawConnectingLinesPartial(pathPtr, 0xFFFFFFCC, 4.0f, 0.0f, 1.0f - sparkProgress);

DrawConnectingLinesPartial(&path, 0xFFFFFFCC, 4.0f, 0.0f, 1.0f - sparkProgress);
```

The first call to `DrawConnectingLinesPartial`, using the `pathPtr` local, passed the correct pointer to the function. But the second call, taking the pointer into a temporary, passed the wrong pointer to the function.

Disassembly here:

```asm
			Path* pathPtr = &path;
0x082569A8:    add			 x9, x8, #208 ; 0xd0 
0x082569AC:    str			 x9, [sp, #152] ; 0x98 
			DrawConnectingLinesPartial(pathPtr, 0xFFFFFFCC, 4.0f, 0.0f, 1.0f - sparkProgress);
0x082569B0:    ldr			 x9, [sp, #152] ; 0x98 
0x082569B4:    str			 x9, [sp, #16] 
0x082569B8:    ldr			 s1, [x8, #304] ; 0x130 
0x082569BC:    fmov			 s0, #1.000000e+00 
0x082569C0:    str			 s0, [sp, #52] ; 0x34 
0x082569C4:    fsub			 s0, s0, s1 
0x082569C8:    str			 s0, [sp, #12] 
0x082569CC:    mov			 w0, #-52 ; 0xffffffffffffffcc 
0x082569D0:    str			 w0, [sp, #84] ; 0x54 
0x082569D4:    bl			 0x8192988 ; RSDK::Color::operator RSDK.Color(uint32) 
0x082569D8:    ldr			 s2, [sp, #12] 
0x082569DC:    mov			 w8, w0 
0x082569E0:    ldr			 x0, [sp, #16] 
0x082569E4:    strb			 w8, [sp, #148] ; 0x94 
0x082569E8:    strb			 w1, [sp, #149] ; 0x95 
0x082569EC:    strb			 w2, [sp, #150] ; 0x96 
0x082569F0:    strb			 w3, [sp, #151] ; 0x97 
0x082569F4:    ldur			 x1, [sp, #148] ; 0x94 
0x082569F8:    fmov			 s0, #4.000000e+00 
0x082569FC:    str			 s0, [sp, #44] ; 0x2c 
0x08256A00:    movi			 d1, #0 
0x08256A04:    str			 s1, [sp, #24] 
0x08256A08:    bl			 0x825593c ; Logic::WickPath::DrawConnectingLinesPartial(RSDK::Path$part*, RSDK::Color$part, float, float, float) 
0x08256A0C:    ldr			 s0, [sp, #52] ; 0x34 
0x08256A10:    ldr			 x8, [sp, #64] ; 0x40 
0x08256A14:    ldr			 w0, [sp, #84] ; 0x54 
			DrawConnectingLinesPartial(&path, 0xFFFFFFCC, 4.0f, 0.0f, 1.0f - sparkProgress);
0x08256A18:    add			 x9, x8, #208 ; 0xd0 
0x08256A1C:    str			 x9, [sp, #32] 
0x08256A20:    ldr			 s1, [x8, #304] ; 0x130 
0x08256A24:    fsub			 s0, s0, s1 
0x08256A28:    str			 s0, [sp, #28] 
0x08256A2C:    bl			 0x8192988 ; RSDK::Color::operator RSDK.Color(uint32) 
0x08256A30:    ldr			 s1, [sp, #24] 
0x08256A34:    ldr			 s2, [sp, #28] 
0x08256A38:    ldr			 s0, [sp, #44] ; 0x2c 
0x08256A3C:    mov			 w8, w0 
0x08256A40:    ldr			 x0, [sp, #32] 
0x08256A44:    strb			 w8, [sp, #144] ; 0x90 
0x08256A48:    strb			 w1, [sp, #145] ; 0x91 
0x08256A4C:    strb			 w2, [sp, #146] ; 0x92 
0x08256A50:    strb			 w3, [sp, #147] ; 0x93 
0x08256A54:    ldr			 x1, [sp, #144] ; 0x90 
0x08256A58:    bl			 0x825593c ; Logic::WickPath::DrawConnectingLinesPartial(RSDK::Path$part*, RSDK::Color$part, float, float, float) 
0x08256A5C:    ldr			 s0, [sp, #52] ; 0x34 
0x08256A60:    ldr			 x8, [sp, #64] ; 0x40 
```

**Comment by hunterbridges** [comment]
I am wondering if the underlying cause is related to #1521... The symptoms are not exactly the same, but they do seem similar (passing temporaries to functions, incorrect stack offsets)

**Comment by hunterbridges** [comment]
One curious detail: the expected value of the pointer is `0x00000021abbad9f0`, but the value the callee is receiving in the `&path` case is `0x00000021ffffffcc`. So it looks like maybe the first 4 bytes of the pointer are getting stomped by the `color` param?

**Comment by hunterbridges** [comment]
I was actually able to get a (somewhat) minimal repro of this

[SwitchTesty.zip](https://github.com/beefytech/Beef/files/8503253/SwitchTesty.zip)

**Comment by bfiete** [comment]
I can't actually _use_ the repro, on account of not actually having a Switch dev kit...

**Comment by hunterbridges** [comment]
The Beef project should at least compile if you use `aarch64-unknown-linux` `Debug` config, and it should generate IR that exhibits the issue... The code ultimately doesn't do much other than print the address of the `path` that is passed to `DrawConnectingLinesPartial`

**Comment by bfiete** [comment]
If you pass Color as a uint32 instead of the struct, does that change anything?

Clang generates `define dso_local void @_Z26DrawConnectingLinesPartialP4Path5Colorfff(%class.Path* noundef %0, i64 %1, float noundef %2, float noundef %3, float noundef %4)` for that, which is the same thing we generate....

**Comment by hunterbridges** [comment]
Yeah, if I use `uint32` instead of `Color`, the function call works correctly in both cases

**Comment by bfiete** [comment]
Maybe `aarch64-unknown-linux` is _not_ actually the proper Switch target triple? The only difference would be i32 rather than i64 for Color. Clang generates an i64 for `Color` for `aarch64-unknown-linux`...

**Comment by hunterbridges** [comment]
Well, the Switch generally uses `aarch64-nintendo-nx-elf`. I wonder if `aarch64-none-elf` (bare metal target) would work?

**Comment by hunterbridges** [comment]
Beef IDE currently doesn't permit targeting that kind of triple though

**Comment by hunterbridges** [comment]
Another compiler option Switch needs is `-fno-omit-frame-pointer`, I don't know if that's surfaced in Beef IDE but I could see that being an issue with the various stack-related bugs we've been seeing

**Comment by hunterbridges** [comment]
I think there may be an uncaught case in `BfTypeInstance::GetLoweredType`. Trying a fix

**Comment by bfiete** [comment]
That isn't how Clang represents that Color struct. See https://godbolt.org/z/ETxas5oK4 - it emits as `i64`, not `i32`.

**Comment by bfiete** [comment]
Also- frame pointers can improve debuggability of code on certain platforms, but it doesn't change runtime behavior or cause crashing if it's "incorrect".

**Comment by hunterbridges** [comment]
> That isn't how Clang represents that Color struct. See https://godbolt.org/z/ETxas5oK4

Hm, yeah I see what you mean. My change did straighten out a few things locally, but that may have been a fluke... or maybe there's some particular nuances of the ABI on Switch we are not aware of.

I'm going to see if I can generate the IR for the C++ code using the Nintendo LLVM fork, and see if it's any different from what godbolt says

**Comment by hunterbridges** [comment]
I ran the test C++ code through Nintendo's LLVM with the Switch target triple, and it generated mostly the same IR as godbolt:

```llvm
%class.Path = type { i8 }
%struct.Color = type { %union.anon }
%union.anon = type { i32 }

; Function Attrs: noimplicitfloat noinline nounwind optnone uwtable
define void @_Z26DrawConnectingLinesPartialP4Path5Colorfff(%class.Path* %0, i64 %1, float %2, float %3, float %4) #0 !dbg !8 {
  %6 = alloca %struct.Color, align 4
  %7 = alloca %class.Path*, align 8
  %8 = alloca float, align 4
  %9 = alloca float, align 4
  %10 = alloca float, align 4
  %11 = getelementptr inbounds %struct.Color, %struct.Color* %6, i32 0, i32 0
  %12 = getelementptr inbounds %union.anon, %union.anon* %11, i32 0, i32 0
  %13 = trunc i64 %1 to i32
  store i32 %13, i32* %12, align 4
  store %class.Path* %0, %class.Path** %7, align 8
  call void @llvm.dbg.declare(metadata %class.Path** %7, metadata !33, metadata !DIExpression()), !dbg !34
  call void @llvm.dbg.declare(metadata %struct.Color* %6, metadata !35, metadata !DIExpression()), !dbg !36
  store float %2, float* %8, align 4
  call void @llvm.dbg.declare(metadata float* %8, metadata !37, metadata !DIExpression()), !dbg !38
  store float %3, float* %9, align 4
  call void @llvm.dbg.declare(metadata float* %9, metadata !39, metadata !DIExpression()), !dbg !40
  store float %4, float* %10, align 4
  call void @llvm.dbg.declare(metadata float* %10, metadata !41, metadata !DIExpression()), !dbg !42
  ret void, !dbg !43
}
```

Key thing is, `Color` is indeed treated as i64 here

**Comment by hunterbridges** [comment]
Ok I think I may be honing in.... I reduced my minimal repro case even further. Now I have my Beef function defined as

```bf
public static void DrawConnectingLinesPartial(Path* path, Color color)
{

}
```
IR looks like this:
```llvm
define void @_ZN2bf15SwitchTestyBeef8WickPath26DrawConnectingLinesPartialEPNS0_4PathENS0_5ColorE(%"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef4PathE"* %path, i64 %color__1) #0 !dbg !50 {
entry:
  %path.addr = alloca %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef4PathE"*, align 8
  %color.addr = alloca %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef5ColorE", align 4
  store %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef4PathE"* %path, %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef4PathE"** %path.addr, align 8
  call void @llvm.dbg.declare(metadata %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef4PathE"** %path.addr, metadata !51, metadata !DIExpression()), !dbg !52
  %0 = bitcast %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef5ColorE"* %color.addr to i64*
  store i64 %color__1, i64* %0, align 8
  call void @llvm.dbg.declare(metadata %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef5ColorE"* %color.addr, metadata !53, metadata !DIExpression()), !dbg !52
  br label %exit

exit:                                             ; preds = %entry
  ret void, !dbg !54
}
```

I tried changing the param type of Color to uint64, and the IR came out like this:
```llvm
; Function Attrs: nounwind uwtable
define void @_ZN2bf15SwitchTestyBeef8WickPath26DrawConnectingLinesPartialEPNS0_4PathEm(%"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef4PathE"* %path, i64 %color) #0 !dbg !43 {
entry:
  %path.addr = alloca %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef4PathE"*, align 8
  %color.addr = alloca i64, align 8
  store %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef4PathE"* %path, %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef4PathE"** %path.addr, align 8
  call void @llvm.dbg.declare(metadata %"SwitchTesty Beef._ZTSN2bf15SwitchTestyBeef4PathE"** %path.addr, metadata !44, metadata !DIExpression()), !dbg !45
  store i64 %color, i64* %color.addr, align 8
  call void @llvm.dbg.declare(metadata i64* %color.addr, metadata !46, metadata !DIExpression()), !dbg !45
  br label %exit

exit:                                             ; preds = %entry
  ret void, !dbg !47
}
```

If you diff them only major difference is the align of the `%color.addr` local. I _think_ that the issue is, the alloca is using the align value of `Color` straight up, but it needs to use the align of the lowered type if the lowered type align size is greater than the struct align size

**Comment by hunterbridges** [comment]
If you look at the C++ one, the treatment of the incoming struct is a bit different. An i64 is used for the incoming struct, a uint32 is alloca'd, and the i64 is truncated into the uint32 slot. But in Beef, Color is being alloca'd with align 4, and that's being casted to `i64*`, which is sometimes causing a 4 byte overlap depending on the current layout of the stack

**Comment by hunterbridges** [comment]
Hm, I tried changing the compiler to align the alloca to the larger of the struct align size or lowered type size, but that seems to cause more problems than it solved. Maybe it instead needs to truncate the lowered type value to the alloca size if the alloca size is smaller...

**Comment by bfiete** [comment]
Ah. Yes, this makes sense.

I think if we just truncate the i64 color to i32 before attempting to store in color.addr, then we're all good.

**Comment by hunterbridges** [comment]
Ok, sorry the above posts are all just thinking out loud. I think I have a grasp of what the bug is:

- Lowered type for `Color` is correctly selected as `i64` on aarch64
- `Color` is size 4, align 4. while `i64` is size 8, align 8. So the lowered type is larger than the composite type.
- When entering the function, there is an alloca of `Color` (size 4, align 4)
- Because of its size and align, the alloca memory could end up halfway between an 8-byte boundary (depending on the prior state of the stack)
- The size-4 align-4 alloca block is then casted to `i64*`
- All 8 bytes of the `i64` param are stored into that pointer (even the 4 garbage bytes)

This means the last 4 bytes of the `store` are stomping beyond the range of the alloca. Depending on the prior stack layout, this could mean stomping into other parameters (rip), or just stomping into some alignment padding (not so bad). In this particular case, the first 4 bytes of `path` are getting stomped

**Comment by hunterbridges** [comment]
ah, beat me to the punch by a few seconds 😅

**Comment by bfiete** [comment]
Ah- and I realize we have a similar issue on _invocation_ when we perform an improperly sized (and aligned) i64 read from the address of a 32-bit Color.

**Comment by bfiete** [comment]
I just committed a potential fix at 2de490fd5914e2820ecc878ebf1775e04ea7f9a4

I'll leave it up to you to test... fingers crossed!

**Comment by hunterbridges** [comment]
Cool, thank you! I'll give it a rip

**Comment by hunterbridges** [comment]
Yep, I think that sorted this particular issue... seems to have been the underlying cause of the dangling symptoms of #1521 as well

**Comment by bfiete** [comment]
Yay!
