### ISSUE TITLE
pointer operation precedence 

### ISSUE THREAD

**Issue by andreakarasho** [beefytech/Beef#154]
```c
  uint8[] buffer = scope uint8[100] {0, };
  uint8* ptr = &buffer[0];
  (*ptr)++; // good
```

```c
  uint8[] buffer = scope uint8[100] {0, };
  uint8* ptr = &buffer[0];
  *ptr++; // "expression cannot be used as a statement"
```

**Comment by bfiete** [comment]
This is operating as designed, and according to the same precedence C# and C++ use. See https://en.cppreference.com/w/cpp/language/operator_precedence

The ++ has a higher precedence than the *, so this is `*(ptr++);`. Not a bug.
