### ISSUE TITLE
Params parameter using tuple with comptype field doesn't work

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1541]
As an example, the below code fails to compile with the error: `Parameters with 'params' specifiers can only be used for array, span, delegate, or function types`, which doesn't make sense since the parameter IS a span.

```cs
public static uint64 id { get; private set; }

class PropertyType<TTarget, TProperty>
	where TProperty : const String
{
	public typealias Result = comptype(GetPropertyType(TProperty));

	[Comptime]
	public static Type GetPropertyType(String prop)
	{
		if (typeof(TTarget).GetField(prop) case .Ok(let field))
			return field.FieldType;
		if (typeof(TTarget).GetMethod(scope $"get__{prop}") case .Ok(let method))
			return method.ReturnType;
		if (typeof(TTarget).IsGenericParam)
			return typeof(var);
		Runtime.FatalError(scope $"No field or property named {prop}.");
	}
}

public static void TestTupleParams<T>(T prop, params Span<(int a, PropertyType<Self, T>.Result b)> a)
	where T : const String
{
}

public static void Main(String[] args)
{
	TestTupleParams("id", (0, 1), (0, 1));
}
```

**Comment by bfiete** [comment]
Fixed at f7abec2283f6b6e0702082ae3314b67f3e418a6d

Keep in mind that `var` is a type poison, where `params Span<(int a, var b)>` poisons to `params var`, which means you do lose some autocomplete and error checking on the unspecialized definition. That could change in the future to help support cases like this, but that's how it is right now.
