### ISSUE TITLE
Crash when typing inside a specific class

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1545]
I have a class that always causes a crash when I type anything inside it, to reproduce this crash you can use the project that I had sent to your email and type anything inside the Sprite class (which is located at `PigoFramework` > `Graphics` > `Sprite.bf`)

Here is also a crash dump:
[crash_smh2.zip](https://github.com/beefytech/Beef/files/8567503/crash_smh2.zip)

Tested with https://github.com/beefytech/Beef/commit/5083f5d64eb98fea1ccbb6ec1b63bc3639e6e6b6 & 1abccded (latest nightly build as I write this issue)

**Comment by bfiete** [comment]
Should be fixed at 0b020c2cb0108208d41508831ee27b717e7554a2
