### ISSUE TITLE
Comptime emit view disappears if the last selected type doesn't exist anymore

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1549]
Video to demonstrate the issue:

https://user-images.githubusercontent.com/86157825/165620591-45194bfe-59c8-42a6-9c6d-efd82ce736bc.mp4

Besides what I show in the video, sometimes the "Emit" button doesn't disappear but when you open it and expand the type list, no types are shown.

The code used in the video:
```cs
	class TestEmit<T>
	{
		[Comptime]
		public static void EmitTest()
		{
			if (typeof(T).IsGenericParam)
				return;
			Compiler.MixinRoot(scope $"NOP!();");
		}

		public void Test()
		{
			EmitTest(); 
		}
	}

	class Program
	{
		public static void Main(String[] args)
		{
			let test = scope TestEmit<int>();
			test.Test();
		}
	}
```
Tested with https://github.com/beefytech/Beef/commit/e852ba49bb7195c18f51d6b8e944048886765114

**Comment by bfiete** [comment]
Fixed at 3bc57b174ee037bcc6e16c3d5fcd6743fa22af02
