### ISSUE TITLE
Hard crash while typing method parameter

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1552]
I got this hard crash when I was typing a method parameter. If necessary I can send this project again but it's basically the project that I had sent to beef email with some modifications.

![image](https://user-images.githubusercontent.com/86157825/166115732-156c3afd-78cb-4592-8773-8c8511e5c5e6.png)

Crash dump:
[BeefIDE.exe.60188.dmp.zip](https://github.com/beefytech/Beef/files/8597472/BeefIDE.exe.60188.dmp.zip)

Tested with https://github.com/beefytech/Beef/commit/a874bab0e475d29149adfa8cd500ae5578269bf8 & 23b777c (latest nightly as I write this issue)

**Comment by bfiete** [comment]
Should be fixed at 9972ff32abded6c364ea7eac6c0c4dcf6d21faf4

Comptime emissions made incremental compilation more complex, but I think it feels like we're getting some of these more "interesting" corner cases tamed...
