### ISSUE TITLE
"Emit" marker doesn't show up

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1553]
The emit marker doesn't show up in the file `PigoFramework\Helpers\Tween\Tween.bf:57` that is in the project that I sent to your email.

Another thing that I noticed is that "Find All References" and "Rename Symbol" fails to find the reference to the method being called at line 70 of that same file, I'm not sure if this is a bug since this probably is related to `var` poisoning, but I think I should mention this anyway.

https://user-images.githubusercontent.com/86157825/166119290-53750136-243e-404e-a9b9-a917122b97f2.mp4

Tested with https://github.com/beefytech/Beef/commit/a874bab0e475d29149adfa8cd500ae5578269bf8

**Comment by bfiete** [comment]
Emit marker fixed at 5271f5e2fd8a4633ec5baa028c9433637593862a

The solution was more complicated than I would have liked, but that's just the nature of the issue.

On the method reference issue - when an argument to a method is `var`, no specific method actually gets bound so there's no method reference made. This makes more sense when you consider the case of method overloads where no method selection can occur (not until a concrete type can be bound during specializaiton), but it's also the case even if there aren't overloads.
