### ISSUE TITLE
random autocomplete crash

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1554]
Code sent by mail.

Open workspace in ./Cavex_/

Navigate to Cavex_ -> Pathfinding.bf, method "MakeNavPath" (there is some error that will also bring you there from the debugIde crash).
Code some, for me it usually happened when placing dots after identifiers and writing things out manually at least for the first few chars rather than completing them, and declaring variables... but that could just be illusions.

**Comment by bfiete** [comment]
Fixed at 8dc2cf9652fd7ab8e099692ef1fcc7ea65254f3b
