### ISSUE TITLE
IDE crashes when adding attribute to method

### ISSUE THREAD

**Issue by Rubberduckycooly** [beefytech/Beef#1558]
It seems that adding an attribute to a method crashes the IDE. As shown in the first image, it's fine when the attribute is added to a variable. However as the second image shows, when added to a method the idea will crash. Loading the IDE in safe mode will prevent the crash, the crash seems happen regardless of if the attribute has parameters or not. The crash happens in both the latest stable release and the latest nightly.

No issues with attributes on variables
![image](https://user-images.githubusercontent.com/23735543/167775044-e062a6b5-9267-44f4-adc7-75173fa3263a.png)

Adding an attribute to a method causes a crash
![image](https://user-images.githubusercontent.com/23735543/167775060-6b8984d8-1b6b-40f1-8933-f46232834f73.png)

**Comment by bfiete** [comment]
In the future - it's better to post actual code instead of screenshots so I can copy the code out to test it.

**Comment by bfiete** [comment]
Fixed at ebd341e311797215a282467e807459e101e674e9
