### ISSUE TITLE
IDE crash while typing

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1559]
I was typing this method signature `protected virtual void CaptureMouse(Self widget, bool capture)` it crashed right after i typed the `Se` in `Self widget`. but after restarting the IDE i couldn't get it to reproduce. Here is a crash dump:
[crash_while_typing.zip](https://github.com/beefytech/Beef/files/8668785/crash_while_typing.zip)

 IDE version: 0.43.3 (Nightly 05/10/2022)

**Comment by bfiete** [comment]
Fixed at 2388ae46ff568672fef1c10d6be1ff780a2ff336
