### ISSUE TITLE
[Feature Request] String Interpolation

### ISSUE THREAD

**Issue by jmeyblum** [beefytech/Beef#156]
The language could really benefit from having string interpolation.
Here is how C# approached it: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

**Comment by bfiete** [comment]
Implemented at https://github.com/beefytech/Beef/commit/281f19e04c9dd2e5821f7902e1ef9136122a14ee
See https://github.com/beefytech/Beef/issues/640
