### ISSUE TITLE
Random crash on compile

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1560]
These crashes occur pretty randomly and i haven't figured out how to make it reproducible so i can only provide a crash dump:
[CrashOnCompile.zip](https://github.com/beefytech/Beef/files/8675340/CrashOnCompile.zip)

IDE Version: 0.43.3 (Nightly 05/10/2022)

**Comment by bfiete** [comment]
MAY be fixed at 2c1d38d45fd8008d8db9d8fd3eb2d73e237637ca

**Comment by Fusioon** [comment]
Sadly it seems like it didn't fix the issue. but i may have found a way to reproduce it. Open the project i sent for #1563, remove the contents of the method that has errors and do a compile then compile again, then Clean and compile and compile again. I was able to reproduce this almost every time. sometimes it happens on third/fourth try.

**Comment by bfiete** [comment]
This is actually a longstanding intermittent issue that I've gotten a few crash reports for but had never figured out how to reproduce. Now it's dead @ 347dc5b8cf687ef19a3cd310dad4a2caef895a1f
