### ISSUE TITLE
Crash when clicking on text after `using`

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1563]
Project sent to email.
To reproduce this crash navigate to `Editor/src/UI/Docking/WindowDockCanvas.bf` and then simply click anywhere inside line 4 after the `using` keyword
Crash dump: 
[using_crash.zip](https://github.com/beefytech/Beef/files/8698790/using_crash.zip)

Tested with: Nightly 05/13/2022

**Comment by bfiete** [comment]
Fixed at edfdf7e606963b428f21102d8013c90b51ab3007
