### ISSUE TITLE
Crash while editing

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1564]
Using latest commit (edfdf7e) if you open the project i have sent for issue #1563 and open `Engine/src/Math/Color4.bf` and press Enter couple of times to add new lines after `public const Self Orange = .(0xFF, 0xA5, 0x00, 0xFF);` (line 93) the IDE will crash

**Comment by bfiete** [comment]
Fixed at c73cf12f5e31563ba4642531c9a433cc8b6814df
