### ISSUE TITLE
Crash while editing comptime attribute

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1566]
It crashed right after i typed `if ()` but that is probably not helpful.
Crash dump:
[crash_while_edit_compattr.zip](https://github.com/beefytech/Beef/files/8729121/crash_while_edit_compattr.zip)

IDE Version: Nightly 05/18/2022

**Comment by bfiete** [comment]
Crash dump isn't very helpful. This reproduces with the code you emailed?

**Comment by Fusioon** [comment]
Yeah but it's not very consistent, it's related to editing `SteelEngine.Serialization.SerializableAttribute`. usually if you make enough changes to this attribute it will crash at some point.

**Comment by bfiete** [comment]
I _believe_ this may be fixed at 5699a3ab6ba9e0eedf599db602885a8e80534946
