### ISSUE TITLE
[BUG] Wrong cursor position after undo

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1567]
If you copy whole line (copy without anything selected) and then paste it somewhere after some text then after undo the text cursor will display as being in the same spot as before the paste but if you try to type something it will jump to to start of the line.
![q](https://user-images.githubusercontent.com/11310500/169537605-b86854c4-62d6-4830-b900-178b5fc7c928.gif)

Tested with: Nightly 05/18/2022

**Comment by bfiete** [comment]
Fixed at 44c112363751f82e11deecb7ad74693d654439e8
