### ISSUE TITLE
[BUG?] generic cast operator doesn't work in specific project

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1568]
i have defined this operator 
```cs
public static explicit operator Vector2<F> <F>(Self s)
    where F : IHashable
    where F : operator explicit T
{
    return Vector2<F>((F)s.x, (F)s.y);
}
``` 
and the thing is that this doesn't work in one project but when i moved the definition file to another project it works.
Project in which it works: 
[Test.zip](https://github.com/beefytech/Beef/files/8747242/Test.zip)

Project in which it doesn't work sent to email.

Tested with: Nightly 05/18/2022

**Comment by bfiete** [comment]
Fixed at f9396f69c06584603ad8cc1d106c9f713bfd67bd
