### ISSUE TITLE
Failed to build in Manjaro Linux

### ISSUE THREAD

**Issue by ShadowwLol** [beefytech/Beef#157]
Building the project with "build.sh" on Manjaro gets an error every time:
```
Starting build.sh
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/shadoww/Desktop/Apps/Beef/jbuild_d
[  5%] Built target hunspell
[  5%] Building CXX object BeefySysLib/CMakeFiles/BeefySysLib.dir/platform/linux/LinuxCommon.cpp.o
In file included from /home/shadoww/Desktop/Apps/Beef/BeefySysLib/platform/linux/LinuxCommon.cpp:7:
/home/shadoww/Desktop/Apps/Beef/BeefySysLib/platform/linux/../posix/PosixCommon.cpp:30:10: fatal error: backtrace.h: No such file or directory
   30 | #include "backtrace.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [BeefySysLib/CMakeFiles/BeefySysLib.dir/build.make:2462: BeefySysLib/CMakeFiles/BeefySysLib.dir/platform/linux/LinuxCommon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:225: BeefySysLib/CMakeFiles/BeefySysLib.dir/all] Error 2
make: *** [Makefile:104: all] Error 2
```

**Comment by pmysl** [comment]
Installing `libbacktrace-git` from AUR should help. Check https://github.com/beefytech/Beef/issues/143#issuecomment-619973485

**Comment by davidmc971** [comment]
I had the same problem, sadly using libbacktrace-git caused a linker error for me.
I ended up using systemd-nspawn to create an ubuntu container to compile Beef there and now it's working for me.

**Comment by henriquelalves** [comment]
@davidmc971 I tried doing that too but I got stuck when running ./bin/build.sh (somehow it wasn't finding a LLVM/Tools header). Did you had to setup the container in a specific way, or install any dependencies other than what is on the documentation?

**Comment by Skrylar** [comment]
The build docs should probably mention `libbacktrace` needs to be installed, since the build script isn't detecting it. This error comes up on OpenSuSE too.

**Comment by davidmc971** [comment]
You might be missing libtinfo-dev in your Ubuntu container :)
If you need more information on how I got it to work, I wrote a little article on how I did it:
https://www.reddit.com/r/beeflang/comments/gard75/a_note_on_compiling_beef_on_arch_linux_manjaro/?utm_medium=android_app&utm_source=share

**Comment by bfiete** [comment]
These issues should be resolved now...
