### ISSUE TITLE
IDE crashes

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#1571]
I'm on the nightly build from 05/24/2022.
The project is too large to be attached to an issue so I uploaded it to [google drive](https://drive.google.com/file/d/1i-n_pHmxZeNIluWGTR_xDxAMI0_EdGyQ/view?usp=sharing).
The IDE crashes a couple seconds after I open the workspace or as soon as I hit compile.
Here is a [crashdump](https://github.com/beefytech/Beef/files/8774543/crashdump.zip), just in case.

**Comment by bfiete** [comment]
I'm not sure how someone didn't stumble across that bug before...
Fixed at da29789bd68c867669e036d838a27ff30cd8e0ef
