### ISSUE TITLE
[Enhancement] change local path during code generation

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#1574]
When running a File Generate in the ide the local path is the beef install folder
`C:/Programs/Beeflang`
However I have a generator which wants a file path as an input.

This forces the users to either input a full path or get the relative path from the beef install folder.

I think it would make sense to make the path while generating code, the path of the workspace, similar to how it is during debug.
As this would allow relative pathing in a way that makes sense for the user.

**Comment by Booklordofthedings** [comment]
I did find a solution by using workspace dir, however I still think the path should be workspace dir by default

**Comment by bfiete** [comment]
To be clear - you're just talking about what the comptime current working directory is set to while executing comptime code? Or are you referring to something else?

**Comment by Booklordofthedings** [comment]
I was reffering to the one from the file generator, but that likely is the comptime one, so yea

**Comment by bfiete** [comment]
Fixed at 087a129007dcaa80933b9a3c308102601c775790

Now the cwd defaults to the path you selected to generate from. There's also actual file and folder path editors in the generator so you can use `AddFilePath` instead of `AddEdit`. The path for that defaults to the project's root folder.
