### ISSUE TITLE
[Feature request?] Getting `readonly` modifier from type

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1576]
Is there currently way to get readonly modifier from type? Because calling `Type.GetFullName` on `readonly ref` type does retain `ref` but it doesn't contain the `readonly` (at least when using `Compiler.Generator`, I didn't test this with runtime reflection).

**Comment by bfiete** [comment]
`readonly` is not part of the type system - it's an attribute of variables, fields, and return values.

**Comment by Fusioon** [comment]
I know that it's not part of the type, but it's not possible to retrieve this 'attribute' via reflection, be it on field, param or return value. I'm testing some code generation and it's not possible to generate proper wrapper for methods with `readonly ref` param/return value because of this

**Comment by Fusioon** [comment]
Many thanks! Although it seems like it works the opposite way in `MethodInfo` (returns true for non readonly values and false for readonly values).

**Comment by bfiete** [comment]
Oops- bad copy & paste.
Fixed at eaed87e1b766ee38966bc669e297f91368d4d251
