### ISSUE TITLE
Immediate Window's issue with enums and optional parameters

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1577]
Immediate Window seems not to be able to understand enums very well, and it can't understand optional parameters at all.

Example code:
```cs
enum MyEnum
{
	A,
	B,
	C
}

public static void TestMyEnum(MyEnum e = .A, bool flag = false)
{
	Console.WriteLine("{}{}", e, flag);
}

public static void Main(String[] args)
{
	TestMyEnum(.B);
	Debug.Break();
}
```

Trying to call `TestMyEnum` in the Immediate Window with the parameter `MyEnum.A` results in a failed implicit cast:
```console
> TestMyEnum(MyEnum.A)
   Unable to implicitly cast 'int8' to 'test6.Program.MyEnum'
```

Casting `MyEnum.A` to `MyEnum` solves the previous error, but now it results in a not enough parameters error:
```console
> TestMyEnum((MyEnum)MyEnum.A)
   Not enough parameters specified. Expected 1 more.
```

Finally, adding the extra parameter (that should have been optional) fixes the error and the code now executes.

Tested with 087a129007dcaa80933b9a3c308102601c775790

**Comment by bfiete** [comment]
Sadly Microsoft didn't see fit to add default parameter values as part of the debug information. I can "hack it in" for simple values but more complicated default values that invoke conversion operators probably won't ever work...
