### ISSUE TITLE
[Bug] Linking error with Dictionary and Attribute using DateTime

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1584]
Hi

I have a LLVM linking error for the code below.

It's a strange mixture of seemingly unrelated things that is needed for this to happen. It happens in both Release and Debug (require Clean if already build earlier)

Here is what I found:
- An attribute has to be calling something on `DateTime`
- A `Dictionary<,>` has to be present somewhere. The generic types does not matter.
- Using `DateTime` outside of the attribute no longer produce an error

```beef
using System;
using System.Collections;
namespace Clean;

public struct SomeAttribute : Attribute
{
    static void Method()
    {
        let now = DateTime.Now;
    }
}

class Program
{
    Dictionary<int, int> dic;
    public static int Main(String[] args)
    {
        //let now = DateTime.Now; // <-- Adding this make it work
        return 0;
    }
}
```

**Comment by bfiete** [comment]
Fixed at 6f51eca72c203a3d1c49cb2cdcc77fd32aca21d6
