### ISSUE TITLE
[Bug] Method from extension allows different return type than defined

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1585]
Hi

I'm extending a specific generic on a struct. I'm not sure if this is supported behaviour, but it works for my intended use (`uint8`).
However, when using a different type (`int`) the method is still available. And when used, it return another type than explicitly defined.

First of, I expected the method to not be available.
Secondly, I expect the method to return `MyStruct<uint8>`, since that is what the method defines. It looks like `MyStruct<uint8>` becomes an alias for `MyStruct<T>` in the extension.

```beef
struct MyStruct<T>
{
}

extension MyStruct<uint8>
{
    public static MyStruct<uint8> Method()
    {
        return default;
    }
}

class Program
{

    public static int Main()
    {
        MyStruct<int> x = MyStruct<int>.Method();
        return 0;
    }
}
```

**Comment by bfiete** [comment]
Your extension is equivalent to the following:
```C#
extension MyStruct<T>
{
    public static MyStruct<T> Method()
    {
        return default;
    }
}
```

except instead of naming the generic argument `T` you named it `uint8`.

What you meant to do was:
```C#
extension MyStruct<T> where T : UInt8
{
    public static MyStruct<T> Method()
    {
        return default;
    }
}
```

**Comment by m910q** [comment]
Why didn't I think of that... Yes of course, my bad!
