### ISSUE TITLE
Linking errors and IDE crash with certain optimization levels

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#1587]
I've found a few issues when building my project with different optimization levels. You can download it from google drive [here](https://drive.google.com/file/d/1XwracSYszq6qGyhtHGSitsLi5X4Shuz7/view?usp=sharing).

1. Release only compiles when optimization is set to Og+. If it is set to any other optimization level I get a couple of `lld-link: error: undefined symbol` errors.
Additionally with O2 and O3 I get the error `lld-link: error: Explicit gep type does not match pointee type of pointer operand`.
(Note: Compiling in release also produces a lot of `lld-link: warning: procedure symbol record [...] is not a valid function ID record`. As far as I can tell its a bug in Visual Studio / LLVM and probably isn't related to this issue.)
2. Compiling as Debug with optimization O0 crashes the IDE. Crashdump: [dump.zip](https://github.com/beefytech/Beef/files/8853875/dump.zip)

**Comment by bfiete** [comment]
Can you send a built GlitchyEngineHelper? The CMake step isn't working for me.

**Comment by aharabada** [comment]
Here is the built GlitchyEngineHelper: [GlitchyEngineHelper.zip](https://github.com/beefytech/Beef/files/8883666/GlitchyEngineHelper.zip)
You also might want to remove the prebuild command from the GlitchyEngineHelper project so that it doesn't try run cmake.

**Comment by bfiete** [comment]
Fixed at ae84564fca3943a01e6453fda05b7b6b2b5b81a4
