### ISSUE TITLE
Wrong pointer as current instance (this) passed to method

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#1588]
The project is on [google drive](https://drive.google.com/file/d/1XwracSYszq6qGyhtHGSitsLi5X4Shuz7/view?usp=sharing) (it's the zip from #1587).
The issue occurs when I compile the project as Debug with optimization level Og+. I can't check other optimization levels as they don't compile, see #1587.

In the project you'll find the class `ModelLoader`. In this class is the function `CreateEntity`:
```bf
private static (EcsEntity Entity, TransformComponent* Transform) CreateEntity(EcsWorld world, StringView? name, EcsEntity parent)
{
	...

	/////TODO: !!!!!!!!REPORT!!!!!!!!!!!!!
	// This works
	TransformComponent cmp = .();
	var childTransform = world.AssignComponent<TransformComponent>(entity, cmp);
	// This trashes the stack
	//var childTransform = world.AssignComponent<TransformComponent>(entity);
	childTransform.Parent = parent;

	return (entity, childTransform);
}
```
If you comment the two lines after `// This works`, uncomment the line after `// This trashes the stack` and debug the application it will crash inside the method `AssignComponent` with the error `Attempted to access deleted object`. Inspecting the variables inside `AssignComponent` reveals that the pointer to `this` is wrong.

Contrary to my initial assumption the stack seems to be fine. However stepping through the assembly reveals that the register that contains the pointer to `world` gets overridden multiple times before the method call which is why the pointer to world (this) is wrong inside `AssignComponent`.

If you add `var world;` before the `AssignComponent` call everything works fine.

**Comment by bfiete** [comment]
Fixed at 4c553ee9a3e4f9467f2472883e6ccdc258339292
