### ISSUE TITLE
Memory leak in NumberFormatter

### ISSUE THREAD

**Issue by fjdumont** [beefytech/Beef#159]
NumberFormatter currently leaks.

To reproduce:
```
public static void Main(String[] args)
{
    Console.WriteLine("{0:F2}", Math.PI_d);
}
```

Allocation occurs in `NumberFormatter.ResetCharBuf` and doesn't get free'd:

```
private void ResetCharBuf (int size)
{
	_ind = 0;
	if (_cbuf.Count < size)
	{
		if (_cbuf.Count > 0)
			delete _cbuf;
		_cbuf = new char8 [size];
	}
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/6bd1eb1cc40535f0ae42773646692dca0bbc507e
