### ISSUE TITLE
Access to member field of `var` is always compilable

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1591]
I found this in my project by accident, I never noticed it before since it didn't give any error
That makes me wonder what the compiler actually compiled 🤔 

Example code:
```cs
var a = var.a;
var b = var.b;
Console.WriteLine("{}{}", a, b);
```

Tested with https://github.com/beefytech/Beef/commit/3cc0ba2ed669b97a707463ca4a0d8f3631569c9a

**Comment by bfiete** [comment]
Fixed at 5c59fe694d00fbf8c2820008bead769c04aba8c1

Basically you ended up printing out two "undef" objects which _should_ have only been possible in an error case. It's the same call that would have been generated if you had
```
TypeThatDoesntExist1 a;
TypeThatDoesntExist2 b;
Console.WriteLine("{}{}", a, b);
```
Except in that case you would have had errors generated that would make the code not actually runnable.
