### ISSUE TITLE
No code is shown for debugging comptime emitted code

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1593]
The project [LuaTinker-Beef](https://github.com/disarray2077/LuaTinker-Beef) used to work before but looks like it broke recently.

I tested the project using the nightly build 23b777c, all tests complete successfully and nothing weird happens:
![image](https://user-images.githubusercontent.com/86157825/173921400-2bc172ae-6fb3-44ee-97e7-1beca35ada0a.png)

But when testing it using a build compiled from the latest commit (https://github.com/beefytech/Beef/commit/527935f371415eab4994e9f8ad7f8f68c2dee243), looks like something goes really wrong, but no code is shown for debugging:
![image](https://user-images.githubusercontent.com/86157825/173921580-e1847c38-92bf-48bd-94b9-8412243f2ec8.png)

**Comment by bfiete** [comment]
I'm trying to unravel this...  the first thing I've found is that here https://github.com/disarray2077/LuaTinker-Beef/blob/main/src/StackHelpers/User2Type.bf#L19

It seems that should read `return ref *((T*)ptr);`

`&ptr` is the address of the _local variable_ `ptr`, whereas you want just want to cast the value in the lua user data. That makes the function not crash but then the test fails still.. 

It's unclear how this could have worked before.

Also the ref function result seems to be displayed incorrectly in the debugger... 

Still digging...

**Comment by bfiete** [comment]
Actually that's not really right either. How can you return a `ref T` from GetTypeDirect, when `lua.ToUserData` would presumably just return a _value_...

**Comment by bfiete** [comment]
Ah- I'm finding something here actually...

**Comment by bfiete** [comment]
Okay- the crash is fixed at c670473452680b7ab428539e576ddae60fbcf786

Some of the tests pass but then there's a test failure. If that's a compiler bug then I might need some help pinpointing exactly where things have gone wrong...

**Comment by bfiete** [comment]
I can probably just determine exactly when it stopped working from older builds and figure it out from there..

**Comment by disarray2077** [comment]
>It seems that should read return ref *((T*)ptr);
>Actually that's not really right either. How can you return a ref T from GetTypeDirect, when lua.ToUserData would presumably just return a value...

`GetTypeDirect` assumes the UserData is a LightUserData, which makes `lua.ToUserData` return a pointer, and `*((T*)&ptr)` forces the cast of this pointer to a function, If I'm not mistaken it's the only way of doing `(T)ptr` (The `ref` isn't actually necessary)

>Some of the tests pass but then there's a test failure. If that's a compiler bug then I might need some help pinpointing exactly where things have gone wrong...

Hm... Looks like the struct instance pointer is wrong when `Actor.SetPosition` is called through the function pointer:
```console
// This is the pointer gotten from lua for the Actor instance
> (LuaTinker.Tests.TestMemVar.Vector2*)ptr
   0x281'D6B04030 { x=123 y=321 }
// This is the pointer when we are inside "Actor.SetPosition"
> &this
   0xD8'000FEEA0 { mPos={ x=0 y=0 } }
```
(`ptr` is set here: https://github.com/disarray2077/LuaTinker-Beef/blob/8566f835f87aa10a6a59fe007ee9f9385904b9a2/src/StackHelpers/Translators/Common.bf#L169)

**Comment by bfiete** [comment]
Turns out it was the mixin result change - a `Pop` mixin was pulling the `ref` off of that value and causing it to work on a copy...

I revisited that mixin change and now the behavior is back to how it was before, but now we've addressed the issue of potentially returning the address of an out-of-scope local variable by extending the life of that local variable.

So this project now works as-is, as of ccb16469905fd71ac16e92191f1e0ce4912f13b6
