### ISSUE TITLE
Crash on compile time attribute with params constructor

### ISSUE THREAD

**Issue by LoopyAshy** [beefytech/Beef#1598]
## Beef version

https://github.com/beefytech/Beef/commit/5dcb584242890125f1cf18d8d985d63550127738

## What you did

Created a `IOnTypeInit` attribute with `params` as a parameter in the constructor and applied it to a random struct.
```csharp
[HelloWorld.FunTest("a", "b")]
struct Test {}

[AttributeUsage(.Types)]
public struct FunTest : Attribute, IOnTypeInit
{
    public this(params String[] field) 
    {
    }

    [Comptime]
    public void OnTypeInit(Type type, Self* prev)
    {
    }
}
```

## What went wrong

Crashes the ide instantly.

## What you expected to happen

The attribute to allow a variable amount of string arguments or for the ide to give a error saying variadic arguments are disallowed in compile time context.

## Additional information

Crash dump: [crash.zip](https://github.com/beefytech/Beef/files/8943172/crash.zip)

**Comment by bfiete** [comment]
Fixed at f47d9e0b017a381a74215807ea0512599c6f0f93
