### ISSUE TITLE
[linux, xubuntu] Failed to compile

### ISSUE THREAD

**Issue by quenti77** [beefytech/Beef#16]
I git clone a repo and run a bin/build.sh. At the end i have 2 errors returned :
![image](https://user-images.githubusercontent.com/5288206/72170869-f46a2580-33d1-11ea-86ff-63c8e3b6dbb0.png)

```
/usr/bin/ld: cannot find -ltinfo
collect2: error: ld returned 1 exit status
make[2]: *** [BeefBoot/CMakeFiles/BeefBoot.dir/build.make:173: Debug/bin/BeefBoot] Error 1
make[1]: *** [CMakeFiles/Makefile2:259: BeefBoot/CMakeFiles/BeefBoot.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

If you need more info, ask me

**Comment by bfiete** [comment]
Gotta get that tinfo

I suppose may do it:
sudo apt-get install libtinfo-dev

**Comment by quenti77** [comment]
Ok, thanks, i finish compile with the new lib installed. Just need run now ^^

**Comment by quenti77** [comment]
I try sample workspace with this command :
![image](https://user-images.githubusercontent.com/5288206/72201804-01315c80-3458-11ea-8202-d64aabf6b8ae.png)

```
~/Documents/Beef/IDE/dist master
❯ ./BeefBuild -new -workspace=samples\HelloWorld
Created new workspace in '/home/quentin/Documents/Beef/IDE/dist/samplesHelloWorld'

~/Documents/Beef/IDE/dist master
❯ ./BeefBuild -workspace=samples\HelloWorld -run
**** FATAL APPLICATION ERROR ****
Signal: SIGSEGV

0x0x7f8cfd6c81e3 __libc_start_main
```

**Comment by bfiete** [comment]
Oops, "-run" does indeed crash with an empty project. Add some source into the "src" directory. See Samples\HelloWorld\src\Program.bf for an example.
