### ISSUE TITLE
Find All seems to have a minor thread race issue

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1600]
Looks like "Find All" has a minor thread race issue, since sometimes the search result numbers appears in second, and sometimes it appears first.

Example 1:
![image](https://user-images.githubusercontent.com/86157825/175403823-435b640b-0b22-436e-8e43-a34b356379e4.png)

Example 2:
![image](https://user-images.githubusercontent.com/86157825/175403962-c2ca7e33-0185-439f-8a27-4d118802f552.png)

**Comment by bfiete** [comment]
Fixed at fa1271b6621fa0605410c6c6303c364bd7477704
