### ISSUE TITLE
Spurious method already defined in vdata.obj error

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1602]
The below code causes `vdata.obj : error LNK2005: sBfTypeData.?$_ARRAY@PEAVIRefCounted@System@bf@@$0?0 already defined in vdata.obj` sometimes, looks like a good way to reproduce the error is deleting the `A` from the enum.
```
enum TestEnum
{
	  A
}

IRefCounted[TestEnum.GetCount()] mRefList;
```
Tested with bca82c231fc311d4f07082874b8f49fecdfec0b2

**Comment by bfiete** [comment]
Fixed at 0cf3e2283d73b20ff8b28d457f757a13cdcf3d6c
