### ISSUE TITLE
Enum bug?

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#1604]
Tested with Win32, version 0.43.4 nightly.
CheckWeight1 does not find the weight whereas CheckWeight2 does when checked explicitly.

```
using System;

namespace Test
{
	public enum FontWeight
	{
		Thin = 100,
		ExtraLight = 200,
		Light = 300,
		Regular = 400,
		Medium = 500,
		SemiBold = 600,
		Bold = 700,
		ExtraBold = 800,
		Black = 900
	}

	public class Test
	{
		public void CheckWeight1(FontWeight weight = .Regular)
		{
			var weightName = scope String();

			let en = Enum.GetEnumerator<FontWeight>();
			for (var val in en)
				if (val.value == weight)
					val.ToString(weightName);
		}

		public void CheckWeight2()
		{
			var weightName = scope String();

			let en = Enum.GetEnumerator<FontWeight>();
			for (var val in en)
				if (val.value == .Regular)
					val.ToString(weightName);
		}
	}
}
```

**Comment by bfiete** [comment]
I'm not seeing an issue other than that you probably meant `val.value.ToString(weightName)` or just `weightName.Append(val.name)`

Can you elaborate on exactly what issue you're seeing here when running this code? Or put a `Main` on this sample and an `Assert` that fails that you think shouldn't fail...

**Comment by damianday** [comment]
> I'm not seeing an issue other than that you probably meant `val.value.ToString(weightName)` or just `weightName.Append(val.name)`
> 
> Can you elaborate on exactly what issue you're seeing here when running this code? Or put a `Main` on this sample and an `Assert` that fails that you think shouldn't fail...

Very odd I can see it works in the reduced test case, I'll investiage it further :/

**Comment by damianday** [comment]
Nevermind, the error was in my code, sorry :)
