### ISSUE TITLE
[Enhancement] Allow moving the next statement arrow

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1608]
This feature from the Visual Studio Debugger is very useful sometimes:
![image](https://user-images.githubusercontent.com/86157825/175781172-38706ba6-f3b4-4faf-96d9-184e72041328.png)
So I think it might be a good idea to have something like this in the Beef IDE's Debugger too.

**Comment by bfiete** [comment]
This functionality does actually exist but I realize it wasn't exposed in any menus: Set Next Statement (Ctrl+Shift+F10)

**Comment by disarray2077** [comment]
Oh, I didn't know, that's neat. Then, please consider that I was suggesting only the arrow drag feature, I think that could be a good usability improvement.
