### ISSUE TITLE
Failed to load project 'corlib' when system language is not english

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#161]
As title says beef fails to load projects when system language is not english.

**Comment by HydrogenC** [comment]
I also met this problem. The project under a non-ASCII path will be unable to load correctly, including translated names for system folders (such as Users, Documents, Desktop). Beef tries to get the translated name of them but it should actually get the original English name.

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/4479af6df47570bf019a1dd26140b4d9c1abb8d4, will be in 0.42.3.
