### ISSUE TITLE
Can't subtract TimeSpans

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#1620]
Subtracting two TimeSpans, or any other structs that inherit from an integer type, results in the error "Unable to implicitly cast 'int8' to 'System.TimeSpan'". All the other operators work fine.

Example:
```bf
TimeSpan a = .FromSeconds(5);
TimeSpan b = .FromSeconds(2);
TimeSpan c = a - b;
```

**Comment by bfiete** [comment]
Fixed at cba96f74ab0d54e1f542b4c96b03cc45fa35df24
