### ISSUE TITLE
[Bug] Go to definition on emitted code crashes IDE

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1622]
Using "Go to definition" on a generated method in emitted code crashes IDE.

In this example, open the Emit and "Go to definition" on any method definition or call to crash.
```beef
using System;
namespace Clean;

[AttributeUsage(.Struct)]
public struct MyAttribute : Attribute, IOnTypeInit
{
	[Comptime]
	public void OnTypeInit(Type type, Self* prev)
	{
		Compiler.EmitTypeBody(type, scope $"public void Test() {{}}\r\npublic void TestAnother() {{ Test(); }}");
	}
}

[Clean.MyAttribute]
public struct MyStruct
{
}

```

**Comment by bfiete** [comment]
Fixed at 6ded6a37cce7a1631ddf465edab1a4c5cff5b5c8
Also the fully-qualified attribute name issue is fixed (`[Clean.My]` will work instead of `[Clean.MyAttribute]` now)
