### ISSUE TITLE
Consistent IDE crash

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1624]
I can reproduce it just by clicking inside field name or field type but it also happens randomly, it started to happen with latest nightly (07/02/2022) and does not happen on nightly 07/01/2022. Crash dump:
[consistent_crash.zip](https://github.com/beefytech/Beef/files/9034724/consistent_crash.zip)
I can also send the whole project over if needed.

**Comment by bfiete** [comment]
It looks like this should fix it: cf269db0eb448a09db59aaab5654c2405a52c866
