### ISSUE TITLE
`Attempted to access deleted object` when using `append String` field

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1625]
I just replaced `String _id ~ delete _;` with `append String _id`.  I was unable to reproduce this in test project with similar code, but here are some screenshots that might help. i will also send a the project to your email.
![image](https://user-images.githubusercontent.com/11310500/177238438-71facf3c-f386-423a-84f9-c8e8afb381f9.png)

![image](https://user-images.githubusercontent.com/11310500/177238303-a2b3b7e7-7bfa-4fc7-adfa-7999c251a5ac.png)

Tested with: Nightly 07/03/2022

**Comment by bfiete** [comment]
Fixed at 08a63e5b9f3457e6cf73d591f841606536b05ece
