### ISSUE TITLE
`??=` operator can be used to assign append field

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1636]
code to reproduce:
```
class Program
{
    class Foo
    {
        public append String value;
    }

    public static void Main()
    {
        Foo f = scope .();
        f.value ??= new .();
    }
}
``` 
This code doesn't generate errors but will crash the compiler with `Failure during codegen`.

Tested with: Nightly 07/08/2022

**Comment by bfiete** [comment]
Fixed at ee7c057e25f2634b67fc01135b9f823ab5f069a4
