### ISSUE TITLE
undefined symbol: _modff

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1638]
The below code snippet causes the link error mentioned in the issue title when compiling for Win32 with Release configuration:
```cs
Console.WriteLine(Math.Truncate(1.6234f));
```
Tested with: https://github.com/beefytech/Beef/commit/ff229f385d14f1e64102fe68594e108aad0b7171

**Comment by bfiete** [comment]
Fixed at 90de4fd2ea48123dd02aa0bb1de402924d5b042c
