### ISSUE TITLE
Separating float literals with apostrophe

### ISSUE THREAD

**Issue by Moneyl** [beefytech/Beef#1639]
Trying the feature for separating number literals with apostrophes mentioned at the start of this page: https://www.beeflang.org/docs/language-guide/literals/ on 7278e09

This is supposed to be aesthetic only, right? When using it on floats it ignores all numbers after the first apostrophe. For example, the debugger and IDE mouseover both say this value equals 1 instead of 1 million
```cs
float a  = 1'000'000.0f;
```
If I exclude the `.0f` ending the value is 1 million as expected:
```cs
float a = 1'000'000;
```

**Comment by bfiete** [comment]
Fixed at 727f1b8cbc740f0c9f33f5e6c98bb99ae44a21ff
