### ISSUE TITLE
[Question] Reason for naming of System.Collection.Generic

### ISSUE THREAD

**Issue by robertsundstrom** [beefytech/Beef#164]
What is the reason for putting collection classes in the "Generic" namespace (System.Collection.Generic) and not directly in namespace Collection?

In .NET they created the Generic namespace in order to avoid collision with the non-generic collection classes that now have been removed. You don't have that problem with legacy, unless you want to mimic that too.

Anyway. Great initiative! I first heard about the project and hour ago and I was immediately impressed. :)

**Comment by HydrogenC** [comment]
In .NET, generic interfaces are placed in System.Collections.Generic and non-generic ones are placed under System.Collections. However, Beef does not (yet) have non-generic versions for IEnumerable and ICollection, etc.

**Comment by bfiete** [comment]
This is actually a pretty good point that I hadn't considered. I think I'll take this suggestion.

**Comment by robertsundstrom** [comment]
> In .NET, generic interfaces are placed in System.Collections.Generic and non-generic ones are placed under System.Collections. However, Beef does not (yet) have non-generic versions for IEnumerable and ICollection, etc. I am not sure if non-generic interfaces will be added in the future.

Yes, but the whole point of generics is that you don't need a non-generic type definition. You can just make the generic type take Object as a parameter (```List<Object>```)

C# did not get generics until version 2.0. That is why this .Generic namespace exists.

Hence, do it right from the first time. ```System.Collections``` is where collections should be.

**Comment by bfiete** [comment]
Everything in System.Collections.Generic has now been moved to System.Collections.
