### ISSUE TITLE
[Bug] IDE crashes with partly entered generic mixin

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1643]
Beef IDE closes down without crash dump after adding the code below to a project.
The project closes after about a second after opening the project.

I'll send the workspace on mail.

```beef
    public mixin RegisterController<T>() wh
    {
        Compiler.Mixin("Console.WriteLine(\"Test something\");");
    }
```

**Comment by bfiete** [comment]
This was actually an issue with a cache used for the new named parameters feature.
Fixed at 6cfd027362ae33e9109baf5304bfbe8f1563707b
