### ISSUE TITLE
When running ./bin/build.sh on Mac I get an error that says 'ffi.h' file not found.

### ISSUE THREAD

**Issue by mileshenry31** [beefytech/Beef#1644]
A screenshot of what my terminal looks like is attached. I already have libffi and cffi installed.

<img width="634" alt="Screen Shot 2022-07-11 at 9 40 46 PM" src="https://user-images.githubusercontent.com/73675082/178410239-25fc7fe2-43a4-4610-a0cc-ce02b8aea5a2.png">

**Comment by mileshenry31** [comment]
On my Mac `ffi.h` is where you said it should be but in the Makefile the directory is `BeefySysLib\third_party\libffi\arm-apple-darwin-21.4.0/include`. Should I change it to `BeefySysLib\third_party\libffi\arm-apple-darwin-21.4.0`?

**Comment by mileshenry31** [comment]
Fixed the error that said `ffi.h is missing` I explicitly told `Internal.cpp` where `ffi.h` was and changed `#include <ffitarget.h>` into `#include "ffitarget.h"` inside the `Internal.cpp` file.

**Comment by disarray2077** [comment]
> On my Mac `ffi.h` is where you said it should be but in the Makefile the directory is `BeefySysLib\third_party\libffi\arm-apple-darwin-21.4.0/include`. Should I change it to `BeefySysLib\third_party\libffi\arm-apple-darwin-21.4.0`?

What... The abs_builddir is `BeefySysLib\third_party\libffi\arm-apple-darwin-21.4.0/include`? I didn't see this coming...
