### ISSUE TITLE
Crash after opening project

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1645]
After updating to latest nightly (07/11/2022) from nightly (07/10/2022) my project immediately crashes the IDE when opened. It's reproducible with project i sent for #1625. Crash dump:
[crash_project_open.zip](https://github.com/beefytech/Beef/files/9093715/crash_project_open.zip)

**Comment by bfiete** [comment]
Fixed at 1183007a90367b933f6c75b92ba9f06885fa778a

This was a regression from the fix for this: https://github.com/beefytech/Beef/issues/1641
I suppose my "fingers crossed" messages in there predicted a regression like this... but I think it's actually right now!
