### ISSUE TITLE
GC reporting objects as leaked when they are not

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1648]
So the issue popped up when i changed field to use append allocation (when changed back to = `new .()` it works). I can't get it to reproduce in minimal repro case, so i will send the project to your email.
Here is a screenshot of the watch & output:
![image](https://user-images.githubusercontent.com/11310500/178767981-54068ccb-742f-4859-a157-e39dfaf2289f.png)

Tested with: Nightly 07/10/2022 (newer version crashes when opening this project)

**Comment by bfiete** [comment]
The program fails to run for me - looks like gl is throwing an error on loading a shader...

**Comment by Fusioon** [comment]
I have no clue what could have gone wrong (my guess is driver because it works on my machine). It should have printed the shader compilation/linking error in console but seems like that was broken in the version i have sent to you. could i bother you a little bit and send you the new version which should print the errors and then you would send me the output so i know what is going on?

**Comment by Fusioon** [comment]
I can just make it work without shaders, which is probably better solution.

**Comment by Fusioon** [comment]
Updated the project so it should run even if the shaders fail to load and sent to email. But could you please post the console output here? so i can get some understanding on why it doesn't work.

**Comment by bfiete** [comment]
Fixed at 119e9189e5cc41c747b2af01abbb87966cb6b422

Strangely it seems like the shaders work now...
