### ISSUE TITLE
Beef IDE - Keyboard incompatible

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#165]
I think this happens because of my keyboard, and what I need to press to get certain keys. The problem is that I can't type curly brackets since when I hold down `Alt Gr` it won't let me type anything, but the shortcut for typing curly brackets on my keyboard (norwegian) is `Alt Gr` + `7`.

**Comment by MineGame159** [comment]
I have the same problem. Just change keybinding in preferences.

**Comment by RogueMacro** [comment]
It seems to be working in later releases, but it didn't work in the initial release. No problem now.
