### ISSUE TITLE
Double delete error causes attempted to access deleted object error

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1657]
Repro code:
```cs
{
	let list = new List<Event<EventHandler>>();
	defer delete list;
	delete list;
}
```
NOTE: The same thing happens if you don't use defer, but the call stack is different.

Tested with: https://github.com/beefytech/Beef/commit/119e9189e5cc41c747b2af01abbb87966cb6b422

**Comment by bfiete** [comment]
Error is better now at 57cb170c3867da285aaad3b6f638d66a92d3a7ef
