### ISSUE TITLE
REQUEST(Website): mension other kernels

### ISSUE THREAD

**Issue by Kreyren** [beefytech/Beef#166]
Currently website mensions Windows, MacOS and linux:

![image](https://user-images.githubusercontent.com/11302521/80570594-5db28a80-89fb-11ea-8f83-5520b60c9f56.png)

But offers download only for windows even on user-agent for linux.

Expecting to mension other kernels.

**Comment by bfiete** [comment]
That's what that "build from source" link is for. "Binaries are available for Windows [big button], and building from source is supposed on Windows, Linux, and macOS [see Build from source link]"

**Comment by Kreyren** [comment]
Note that not all linux distros are Linux From Scratch, Enoch-based, slackware-based, etc.. to expect building from source i.e apt-based distros and the current presentation feels kinda disqualifying for XNU and Linux.

but fair enough.
