### ISSUE TITLE
IDE crashes during Release build

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1663]
The below code causes the IDE to crash during a build with Release config.

```cs
public static class Program
{
	public static void Main()
	{
		StringSplitOptions sso = .None;
		switch(sso)
		{
		default:
			Console.WriteLine($"{Environment.GetModuleFilePath(.. scope .())}");
		}
	}
}
```
Tested with: https://github.com/beefytech/Beef/commit/119e9189e5cc41c747b2af01abbb87966cb6b422

**Comment by bfiete** [comment]
Fixed at a1c7e6e02b9ed704c935e5c230ccfaca7264657c
