### ISSUE TITLE
Region gets automatically folded after go to definition

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1668]
In the video below you can see that the region gets automatically folded a split second after "Go To Definition":

https://user-images.githubusercontent.com/86157825/181995123-a6396cc6-bafc-4d52-9b6a-8a6851c878bc.mp4

I guess this must be a bug since this only happens after you save the region as closed and restart the IDE.

**Comment by bfiete** [comment]
Fixed at de4269bf32ee1185e8fa645b23ac7ad1888f9164

**Comment by disarray2077** [comment]
@bfiete Looking at the fix, I noticed that there is a possibility of another problem when there are other regions before the one that has the cursor inside:

https://user-images.githubusercontent.com/86157825/182001773-b9347fc0-5227-4f42-8cea-64acb3f440c9.mp4

**Comment by bfiete** [comment]
Good point. This should fix that: 17dfc96a1fa873b75f8a6fcdac9dc2691f74cfd6
