### ISSUE TITLE
[Enhancement] Allow field attributes to be applied inside auto constructor

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1669]
Currently auto constructor fields can only have parameter targeted attributes (which is expected), but would it be possible to also apply field attributes to them?
Example code:
```cs
struct Foo : this([Bitfield(.Public, .BitsAt(8, 16), "b")] int i)
{
}
```
I'm not really sold on the syntax as i think it can create a little confusion about on what is the attribute applied to. but it's better than having to declare the fields and then constructor
Or there is C# solution to the auto properties & backing field attributes https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.3/auto-prop-field-attrs which could solve this issue and also issue with backing fields (personally not a fan of this)

**Comment by bfiete** [comment]
I feel like the "best" solution here is to provide an IDE fixit to expand the auto-ctor into a "classic" explicit constructor and fields. That would allow you to benefits of initially writing the short version and then still be allowed to expand it if you need to:

1) Add ctor method attributes (to the method itself or to parameters within it)
2) Add extra logic to the ctor 
3) Add field attributes
4) Make one or more of the fields non-public

**Comment by bfiete** [comment]
I added this fixit at b12ceeb6258e19d587a0b5d76fe0e9f8374a7acd

But yeah- I'm not inclined to allow attributes in the condensed auto-ctor format.

**Comment by Fusioon** [comment]
I agree, allowing field attributes in auto constructor would not be the brightest idea. Thanks for the fixit!
