### ISSUE TITLE
Question: Beeflang in gitpod

### ISSUE THREAD

**Issue by Kreyren** [beefytech/Beef#167]
I prefer using gitpod for programming i.e https://gitpod.io/#https://github.com/beefytech/Beef/tree/0.42.2

Is there any way to make Beef IDE work on web on in vscode-like editor? (i want to avoid using NoVNC)

Thanks for an answer

**Comment by bfiete** [comment]
These kinds of things will have to be community-driven at some point. Clearly VSCode would be first, though.
