### ISSUE TITLE
Fatal error in IDE debug build

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1672]
The below code causes a fatal error in the debug build of the IDE:
```
class TestDbgCrash
{
	String value = new .() ~ delete;

	public void operator+=(StringView value)
	{
		this.value.Append(value);
	}
}

public static void Main()
{
	TestDbgCrash tdc = scope .();
	tdc += @"0";
}
```
Tested with https://github.com/beefytech/Beef/commit/a23406d9dd242ce8d6b28d771abb4f94f8d567e5

**Comment by bfiete** [comment]
Fixed at 052edbcb8d4bdd775f729d1a0cb4b98447f5355b
