### ISSUE TITLE
Assert failed "calcAppendMethodModule.mFunc"

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1673]
The code below causes the assert failure mentioned in the issue title when compiled using the IDE debug build.

```
using System;
using System.Collections;

namespace System.Collections
{
	public extension List<T>
	{
		[AllowAppend]
		public this(List<T> other) : this(other.Count)
		{
			AddRange(other);
		}
	}
}

namespace test8
{
	public static class Program
	{
		public static void Main()
		{
			List<int> foo = scope .();
			List<int> bar = scope .(foo);
		}
	}
}
```
Tested with https://github.com/beefytech/Beef/commit/a23406d9dd242ce8d6b28d771abb4f94f8d567e5

**Comment by bfiete** [comment]
Assert fixed at ca83467e1b7e0edf8f05d2fce091e9a357a675a0

Also the extension is a good idea- I added an append ctor to `List<T>` that takes a `Span<T>` at 2c439092c3f52f5c744adfec6296b238d6d8ecd8
