### ISSUE TITLE
Ref enumeration erroneously accepts non-ref value

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1674]
The below code compiles but the value of `r` ends up being incorrect since Beef assigns an address to it, as shown here:
![image](https://user-images.githubusercontent.com/86157825/182517070-2015ac0f-8e57-4d3b-bcd2-7dbac5b8230e.png)

Repro code:
```cs
struct TestRef
{
	public int a = 123;
}

public static void Main()
{
	List<TestRef> a = scope .();
	a.Add(.() { a = 234 });
	a.Add(.());

	for (TestRef r in ref a)
	{
		Console.WriteLine(r);
	}
}
```
Tested with https://github.com/beefytech/Beef/commit/a23406d9dd242ce8d6b28d771abb4f94f8d567e5

**Comment by bfiete** [comment]
Fixed at 5d14e714c2861a771293bef1f86eab38fa126374
This will now properly produce a ref casting error.
