### ISSUE TITLE
Object extension breaks debug alloc information

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1677]
Using extensions on the Object class seems to break the debug alloc information's ability to distinguish types:
![image](https://user-images.githubusercontent.com/86157825/182679608-994fd34e-604b-440a-b0cb-3234cc764bd2.png)

Here is the extension that I use:
```
namespace System
{
	extension Object
	{
		Object mDeleteSentinel ~ { if (Compiler.IsComptime) return; Internal.Dbg_MarkObjectDeleted(_ = new .()); }
	}
}
```

Tested with: https://github.com/beefytech/Beef/commit/0907bd1f521c6702e01ce1da65445c8cb4401071

**Comment by bfiete** [comment]
Fixed at aaa08e9a4e9d217b58ea9f5c5fd81f1053d60a10
