### ISSUE TITLE
Crash on compile when disabling dependecy compilation

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1680]
Steps to reproduce:
Create two project in same workspace, `One` (exe), `Two` (lib), Add `Two` as dependency to `One` and then disable project `Two` in workspace properties. Doing compile will crash the IDE.

Tested with: Nightly 08/04/2022

**Comment by bfiete** [comment]
Fixed at e16be338eaaa27f0a3f5842c1a2d65a147f106dd
