### ISSUE TITLE
Assert failed "typeInstance->mTypeFailed"

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1687]
The code below causes the assert failure mentioned in the issue title when compiled using the IDE debug build.
```cs
	public static class Program
	{
		class FooBase
		{
			public List<Foo> foos;
		}

		class Foo : FooBase
		{
		}

		static List<Foo> test = new .() ~ delete _;

		public static void Main()
		{
			test.Add(scope:: Foo());
			test.Back.foos.Add(test.Back);
		}
	}
```
Tested with https://github.com/beefytech/Beef/commit/aaa08e9a4e9d217b58ea9f5c5fd81f1053d60a10

**Comment by bfiete** [comment]
Fixed at 2f6484894efa073b461973a031b47435801de1bd
