### ISSUE TITLE
Code causes IDE to crash inconsistently

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1688]
The code below causes the IDE to crash a lot, it doesn't look like the crashes are consistent but you can randomly get a crash if you try to write code while the code below is present in the method you're editing.
```cs
List<Object> bb = scope .();
List<String> aa = scope .();
aa.AddRange(bb.Select((n) => (String)n));
```
The code depends on: https://github.com/xposure/Beef.Linq
Tested with: https://github.com/beefytech/Beef/commit/aaa08e9a4e9d217b58ea9f5c5fd81f1053d60a10

**Comment by bfiete** [comment]
Fixed at c04d2402100ee6c969008dadf934af5f62a3be3a

Incremental type dependency bugs are always the most fun!
