### ISSUE TITLE
IDE crash

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#1690]
When you clone https://github.com/MineGame159/Beef, switch to the `lsp` branch and try to rename `BeefLsp/src/Utils.GetPathFromJson()` the IDE crashes with [this](https://cdn.discordapp.com/attachments/465205087967510530/1011705091989979256/ide_crash.dmp) crash report.

The same crash happens when renaming most of the methods / mixins in Utils.bf but also sometimes when building / running the project or just opening files in a specific order.

**Comment by bfiete** [comment]
Fixed at 04f7ee4d2de2f763f59536be65d07288ff233b60

Well, the reported crash- not sure about these other "random" crashes you mentioned. You can also send a crash report for those things even if you don't have a reproducible repro.

**Comment by MineGame159** [comment]
I am not getting them anymore after the fix so guess it was the same thing.
