### ISSUE TITLE
Auto implementing based on an interface created invalid code in some configurations

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1691]
When `Settings` -> `Editor` -> `Formating` -> `Tabs or Spaces` is set to `Spaces`, auto implementing a method from an interface makes the generated body go outside the method scope.

Example after  auto implementing a method:
```beef
interface IInterface
{
    int MyMethod();
}

class Impl : IInterface
{
    public int MyMethod()
    {

    }return default;
}
```

**Comment by bfiete** [comment]
Fixed at ae8ea6281d039984cf9a9c7c0312dc2b07ae7a60
