### ISSUE TITLE
MemoryPanel crash

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#1692]
Debug the program, open the memory panel and... (two different crashes!)
1. go to rcx, press the right arrow key until crash.

```bf
class Program
{
	static void Main()
	{
		int a = 1;
		int b = a == 2 ? 0 : a * 2; // breakpoint here
	}
}
```

2. go to rsp, press the right arrow key until crash.

```bf
class Program
{
	static void Main()
	{
		int a = 1; // breakpoint here
	}
}
```

**Comment by bfiete** [comment]
Fixed at cb13198609deeac4a7820983452a9d3080d95cc4
