### ISSUE TITLE
Unable to compile the simplest program

### ISSUE THREAD

**Issue by yonist** [beefytech/Beef#17]
Hi, 

I was trying to create the simplest console program and I get the following error:

Compiling...
Beef compilation time: 0.06s
ERROR: Unable to find entry point class 'Program' in project 'test_2'
0 modules built, 0 object files generated
Errors: 1.
Compile failed.
Changes not saved.
Workspace closed.

The after closing and restarting the project (and then the entire IDE) I get the following error:

ERROR: Project 'test_2' is not loaded. Retry loading by right clicking on the project in the Workspace panel and selecting 'Retry Load'

**Comment by bfiete** [comment]
What was your program code? This is the simplest program:

```
using System;
class Program
{
	public static int Main(String[] args)
	{
		return 0;
	}
}
```

Hm. I'd be curious what the exact steps were that you took to create the workspace, project, and source code - it appears the project didn't actually get saved.

**Comment by yonist** [comment]
That was exactly the code. Steps to reproduce:
1. Start the ide
2. File -> New -> New Project
3. Choose folder
4. F7 (Build)
5. Choose yes for : "This project does not contains ...  auto generate some startup code"?
6. Save All
7. F7 (Build)

**Comment by bfiete** [comment]
Ah. It does appear there's a bug you enter a project name that does not match the directory name.

You can also just not enter the project name and it will infer the project name from your directory name.

**Comment by Domain** [comment]
I have the same problem. I have no idea what to do.

**Comment by bfiete** [comment]
If you create a new project WITHOUT typing in a project name, does work?

**Comment by yonist** [comment]
Yes. It works as you suggested
