### ISSUE TITLE
[BUG] IDE crashes when trying to autocomplete inside .Ok() return type

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#1700]
When a function/method returns a Result<[x]>, trying to autocomplete inside the return .Ok()
brackets will crash the ide

```
using System;
namespace Test;

class Program
{
	public static void Main()
	{


	}

	public Result<char8> func()
	{
		return .Ok(te);
	}
}
```

addding any character after "te" should crash it

**Comment by bfiete** [comment]
Fixed at 5490af46903312351aa7b5087736893dbb561d98
