### ISSUE TITLE
[Suggestion] Create a "fixed in pending release" label to manage issues better

### ISSUE THREAD

**Issue by HydrogenC** [beefytech/Beef#171]
There are move and more issues as the repository is getting more and more popular. Adding a label like "fixed in pending release" would be easier for everyone to see what bugs are fixed already and will be in the next release.

**Comment by HydrogenC** [comment]
Also, I noticed that some bugs that are already fixed in 0.42.2 are not yet closed.

**Comment by bfiete** [comment]
Good idea, I'll do that.

**Comment by HydrogenC** [comment]
#24 #28 #136 are already fixed in 0.42.2 or duplications, they should be closed.
