### ISSUE TITLE
Crash after invoking BeefBuild -generate

### ISSUE THREAD

**Issue by pmysl** [beefytech/Beef#174]
### Steps to reproduce

1. Create and enter into a new directory
2. Enter the following commands:

```
beefbuild -new
beefbuild -generate
```

### Output
<details>
    <summary>Windows log</summary>

    **** FATAL APPLICATION ERROR ****

    Exception: Access Violation (code 0xc0000005) at address 7ff7'a973b687 in thread 32CC
    Executable: C:\Program Files\BeefLang\bin\BeefBuild.exe
    File Version: 0.42.1
    Product Version: 905330ce12cd1f1cb9435463d8ab08c06d6d2451

    Logical Address: 0001:'0006a687

    5d'4ccff8e0 7ff7'a973b687 0001:'0006a687 BeefBuild.exe
        Params: 16b'0261b101 16b'0261b1e0 5d'4ccff998 7ff7'a973cb63

    5d'4ccffa80 7ff7'a973ce71 0001:'0006be71 BeefBuild.exe
        Params: 16b'0261b1e0 7ff7'a9734667 5d'4ccffaf8 16b'00000000

    5d'4ccffc10 7ff7'a974afb6 0001:'00079fb6 BeefBuild.exe
        Params: 16b'02614530 5d'4ccffb80 5d'4ccffbe0 5d'4ccffba0

    5d'4ccffc90 7ff7'a96d1b62 0001:'00000b62 BeefBuild.exe
        Params: 16b'026163f8 '00000009 '00000000 16b'026091c0

    5d'4ccffd50 7ff7'a96d27b5 0001:'000017b5 BeefBuild.exe
        Params: 16b'02600a10 7ff7'00000000 7fff'25bbb590 '00000001

    5d'4ccffd90 7ff7'a989f5b2 0001:'001ce5b2 BeefBuild.exe
        Params: '00000000 '00000000 '00000000 '00000000

    5d'4ccffdd0 7ff7'a98ad254 0001:'001dc254 BeefBuild.exe
        Params: '00000000 '00000000 '00000000 '00000000

    5d'4ccffe00 7fff'281d7bd4 KERNEL32.DLL BaseThreadInitThunk+14
        Params: '00000000 '00000000 '00000000 '00000000

    5d'4ccffe80 7fff'2850ce51 ntdll.dll RtlUserThreadStart+21
        Params: '00000000 '00000000 '00000000 '00000000

    RAX:'00000000 RBX:16b'0aba44a0 RCX:'00000000 RDX:16b'06585f40 RSI:16b'0261b1e0 RDI:16b'06585f40
    R8:'00000071 R9:'00000040 R10:'00000040 R11:5d'4ccff850
    R12:16b'0ab9a4a0 R13:16b'0261b101 R14:5d'4ccff9b0 R15:5d'4ccff9b0
    EIP:7ff7'a973b687 ESP:5d'4ccff8b0 EBP:5d'4ccff9e0
    CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
    Flags:'00010246
</details>

<details>
    <summary>Linux log</summary>

    **** FATAL APPLICATION ERROR ****
    Signal: SIGSEGV

    0x0x7f0c38951b97 __libc_start_main
</details>

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/82ca79947062fc098422ceba72aef5f0710c3dc2, will be in release 0.42.3.
