### ISSUE TITLE
IDE crashes when the text cursor is on certain method calls

### ISSUE THREAD

**Issue by Entrivax** [beefytech/Beef#1740]
[crashdump.zip](https://github.com/beefytech/Beef/files/9812565/crashdump.zip)

Certain calls, when the text cursor is over them (by either clicking on them or moving it with the keyboard), crashes the IDE (v0.43.4)

https://user-images.githubusercontent.com/1197915/196485692-d1ef4862-0cad-4354-b92c-7dab3cad795a.mp4

**Comment by bfiete** [comment]
Fixed at 3122839ea82adabf5081980fa702adc790e98669 - the fix will be in the next night build
