### ISSUE TITLE
Support MINGW64 compiler on Windows

### ISSUE THREAD

**Issue by 3oheicrw** [beefytech/Beef#1743]
It's currently depends on MSVC. As it's using LLVM technology, LLVM can also works with MINGW. Please see LLVM MINGW:

https://github.com/mstorsjo/llvm-mingw

**Comment by 3oheicrw** [comment]
@bfiete

**Comment by bfiete** [comment]
At one point before LLVM 'properly' supported Windows, Beef _only_ created MinGW executables, actually. The debugger was capable of debugging MinGW executables (with DWARF debug info). It's _possible_ to get that code working again and make MinGW an option, but it's just very low priority.
