### ISSUE TITLE
[IDE][CRASH] Working with comments in fixed-size arrays causes IDE to crash

### ISSUE THREAD

**Issue by kallisto56** [beefytech/Beef#1748]
Hi there,
This issue is related to #1725 

Working with comments in fixed-size arrays causes IDE to crash. To reproduce a crash, remove `/*` in the array.
This happens when at least one item in the array is a `reference` or `function call`. Crash does not occur if we are writing actual values like `56`, `true`, or strings like `Hello world` for example. Crash also does not happen, if an array is created with `new` or `scope` option.

**Crash dump: [crash-dump--comments-inside-fixed-array-of-structs.zip](https://github.com/beefytech/Beef/files/9857496/crash-dump--comments-inside-fixed-array-of-structs.zip)**

```beef
namespace TestProject
{
	public static class Program
	{
		public struct MyStruct
		{
			public int32 value;
		}

		public static void Main ()
		{
			var a = MyStruct();
			var b = MyStruct();
			var c = MyStruct();
			var d = MyStruct();

			MyStruct[?] values = MyStruct[]
			(
				a,
				b,
				/*c,
				d,*/
			);
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed at 213aea8c820d80addf2ae51e9124fc5df9f7badc
