### ISSUE TITLE
VirusTotal Scan [Program:Win32/Wacapew.C!ml]

### ISSUE THREAD

**Issue by jairopaiva** [beefytech/Beef#175]
https://www.virustotal.com/gui/file/59b72f3436cbbe062eee12cb5255d1a5a4f82310308aac5c4215e64a4bacb8d2/detection

![image](https://user-images.githubusercontent.com/43503826/80658764-6d62bb00-8a5d-11ea-8e68-a2a2a40d1162.png)

**Comment by HydrogenC** [comment]
I think that it is over-sensitive. Windows defender and McAfee does not recognize it as a virus.

**Comment by jairopaiva** [comment]
I think it's just a false positive, but since I didn't have time to analyze the code and compile it, I can't say anything.

**Comment by pedrobrito019** [comment]
I've got the same problem with my .py script

**Comment by raspopov** [comment]
I packed a [clean tiny utility](https://www.virustotal.com/gui/file/322c2e38d1c577851ac74a1e822826859a2e6bd58397a82b5457c4739bf4211e/detection) to a zip file and [that zip file itself](https://www.virustotal.com/gui/file/cc696e8b2b1350dece74160b0f0202aeac559c47e49a4849a9d16b6d1a49d93a/detection) started detecting as a "Program:Win32/Wacapew.C!ml". 😣
