### ISSUE TITLE
Beef IDE 0.4.23 Error popup after clicking 'Save All'

### ISSUE THREAD

**Issue by SamWindell** [beefytech/Beef#177]
Getting this error popup when clicking 'Save All' on a new project. This is what I did to get here: open up beef IDE, 'Launch Process' adding in my executable, running the program and then closing it - without opening any sources windows or breaking, then trying to click 'Save All'.

This popup is not causing an issue to me but thought it worth mentioning.

![image](https://user-images.githubusercontent.com/15104010/80706132-ad6a8200-8adf-11ea-9456-ecfa26a05ce5.png)

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/3ebe00d59a81cb6b1f9b04f518e9fbc8672a2084
