### ISSUE TITLE
[Feature Request, FFI] Will it be possible to import C/C++ interfaces by including headers?

### ISSUE THREAD

**Issue by carlcc** [beefytech/Beef#1781]
Hi, I am a newbie, just get to known beef recently, and very interested in the beeflang's overall design.

I found it is easy to map C interfaces into beef, just declare them with attributes, which is similiar to C#. That good, But since beef has many features that compatible to C, we can do better than C#.

By just including C headers in someway (preprocessor or some kind of directive comment or something else), and then beef compile will import related C interfaces automatically for us, no glue code is needed. This will save tons of FFI work since there are tons existing C/C++ libraries.

What's more, may be we can mix C/C++/OC/OC++ in a single project (by adjusting beef's official build tool or thirdparty build tool.

Uhm, just a naive idea...

Regards.

**Comment by EnokViking** [comment]
See https://www.beeflang.org/docs/language-guide/interop/ for some of the hurdles involed in C++ interop. Beef doesn't have or even require anything similar to C#'s P/Invoke mechanism so i'd argue beefs interoperability with C is already better as it doesn't involve the overhead of marshalling where as in C#, a native function call can have a fixed overhead of 10-30 instructions depending on the complexity of the call on top of the marshalling cost.

You can write a bindgen file generator which will effectively do the same thing you're requesting. Not a trivial project, however.

**Comment by bfiete** [comment]
Importing C/C++ libraries is a hack - it only works with the simplest libraries, and it's not really reasonable for the user to figure out which ones will work. Libraries that use C++ templates like basically any Boost library, or libraries that make "clever" use of C macros just can't work in languages that don't support those features (ie: Zig, D, Odin, etc).

There's a reason that the "big" languages don't bother attempting this feature - it just doesn't work well enough to justify it's own existence.

If you want to see a language where it _does_ work, look at Carbon - but that language is _explicitly_ designed for that, with many compromises to make it work.
