### ISSUE TITLE
Restarting the game by importing the library does not work

### ISSUE THREAD

**Issue by fredOnGitHub** [beefytech/Beef#1787]
Hello,

I tried to redo the game by importing the library but without success.

I was able to import SDL2 "Add from Installed" but it is not recognized.

Thank you for your help.

![c](https://user-images.githubusercontent.com/9338756/215873395-9576acb8-3f32-4aef-966f-cb3c309a4bf6.png)

**Comment by disarray2077** [comment]
After the "Add from Installed", you must also add the project as a dependency.
Right-click the "SpaceGame" project, go to "Properties...", click "Dependencies", and check the checkbox for "SDL2".

**Comment by fredOnGitHub** [comment]
Thanks a lot.
I modified 
`Target directory = $(WorkspaceDir)/dist`
`Target name  = $(ProjectName)_d`
like the original and 
**created a "dist" dir and
copy images and sound dir into dist**
and that's OK.

Where can I find these key words  WorkspaceDir and ProjectName ?
I found only [this](https://www.beeflang.org/docs/ide/commandline/).
And If I work with Mac or Linux (so without the IDE), what are the command line to do 
`Target directory = $(WorkspaceDir)/dist`
`Target name  = $(ProjectName)_d` ?

**Comment by bfiete** [comment]
https://www.beeflang.org/docs/projects/

You need to modify the project files, there's no command-line arguments for those. The project file format is not currently documented but you can pretty easily get the gist by just viewing other project files included in the GitHub repository.

**Comment by fredOnGitHub** [comment]
Thanks for your answer.

I watched BeefProj.toml and I saw.

I do all things (debug, genrerate BeefProj.toml, test...)  with Windows IDE and just export the project in Linux or Mac and 
I make ` BeefBuild -run` or ` BeefBuild -clean`
to get an automatic 64 bits program ?
