### ISSUE TITLE
[Bug] Unable to explicitly capture `this` in lambda

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1792]
Code to reproduce:
```
class Foo
{
	String _message = "Hello";
	public void Call()
	{
		String msg = "World!";
		delegate void() d = new [this, =msg]() => {
			Console.WriteLine($"{_message} {msg}");
		};
		d();
	}
}

static void Main()
{
	Foo f = scope .();
	f.Call();
}
```
Tested with: `Nightly 02/10/2023`

**Comment by bfiete** [comment]
Added at 7f695596b88f1961a8089cd9c267b8da07c891f3
For value types, `=this` vs `&this` is meaningful. For reference types there's no difference - we silently allow `&this` even though you can't actually _reassign_ the `this` pointer obviously...
