### ISSUE TITLE
[Bug?] Cannot use generic as append field type

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1799]
Code to reproduce:

```
class Foo<T> where T : class, new, delete
{
	append T bar;
}
```
Code fails with following error message: `Append fields can only be declared in classes`

Tested with: `Nightly 02/17/2023`

**Comment by bfiete** [comment]
Fixed at 7a2fbdfc30e58360ff842ccc8cbfa1dc798cc6be

**Comment by Fusioon** [comment]
Thanks! Would it be possible to also allow this on extensions?

```
class Foo<T> { }

extension Foo<T> where T : class
{
	public append T value;
}
```
Fails with error message: `Append fields must be classes`

**Comment by bfiete** [comment]
That now works at 40165bc33b24e55c4188302884ce8f1067f422e7
