### ISSUE TITLE
Ability to remove a project from a workspace? 

### ISSUE THREAD

**Issue by HydrogenC** [beefytech/Beef#180]
I wanted to remove a project from a workspace but I found no buttons to do that, and I have to edit the BeefSpace.toml manually. Please add a button for removing a project in the right-click menu of a project.

**Comment by bfiete** [comment]
Ah yeah- there should be a menu item for that, but selecting it and pressing the Delete key does it too.

**Comment by HydrogenC** [comment]
That's not as appearant as a menu item.

**Comment by bfiete** [comment]
Added in https://github.com/beefytech/Beef/commit/679f54639edf5fee76c183c4667af26d6799560f
