### ISSUE TITLE
[Bug] Attribute with a Type parameter crashes the IDE

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#1805]
Pasting the following code into a file, uncommenting the commented line and trying to type `typeof(...)` inside the attribute will crash the IDE.

```beef
[AttributeUsage(.Class)]
struct FooAttribute : this(Type type), Attribute {}

//[Foo()]
class Bar {}
```

**Comment by bfiete** [comment]
Fixed at a8b3a7cbf0d288e361e99e8709f2a0fe1c173750
