### ISSUE TITLE
[Bug] Issues with (mostly) code generation emitting to extensions with generic parameters

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#1806]
If the code is manually put inside the extension (not using code generation) then it works correctly, this is true for the first 3 issues.
See issue 4 for the (mostly) part inside the title.

### Issue 1
**Error:** Unable to implicitly cast 'T' to 'float'
```beef
struct Foo<T> : this(T value) {}

[Test]
extension Foo<float> {
	//public static operator float(Self foo) => foo.value;
}

struct TestAttribute : Attribute, IOnTypeInit {
	[Comptime]
	public void OnTypeInit(Type type, Self* prev) {
		Compiler.EmitTypeBody(type, "public static operator float(Self foo) => foo.value;");
	}
}
```

### Issue 2
**Error:** User-defined conversion must convert to or from the enclosing type
```beef
struct Foo<T> : this(T value) {}

[Test]
extension Foo<float> {
	//public static operator Foo<double>(Foo<float> foo) => default;
}

struct TestAttribute : Attribute, IOnTypeInit {
	[Comptime]
	public void OnTypeInit(Type type, Self* prev) {
		Compiler.EmitTypeBody(type, "public static operator Foo<double>(Foo<float> foo) => default;");
	}
}
```

### Issue 3
**Error:** Method 'Something.Foo\<T>.operator Something.Foo\<double>(Something.Foo\<T> foo)' already declared with the same parameter types
```beef
struct Foo<T> : this(T value) {}

[Test]
extension Foo<float> {
	//public static operator Foo<double>(Self foo) => default;
}

[Test]
extension Foo<int> {
	//public static operator Foo<double>(Self foo) => default;
}

struct TestAttribute : Attribute, IOnTypeInit {
	[Comptime]
	public void OnTypeInit(Type type, Self* prev) {
		Compiler.EmitTypeBody(type, "public static operator Foo<double>(Self foo) => default;");
	}
}
```

### * Issue 4
This one is a bit special compared to the rest because it happens even without code generation. It fails to cast float to double even tho it should be an implicit conversion.
**Error:** Unable to implicitly cast 'float' to 'double'
```beef
struct Foo<T> : this(T value) {}

extension Foo<float> {
	public static operator Foo<double>(Foo<float> foo) => .(foo.value);
}
```

**Comment by bfiete** [comment]
Warning added for non-matching generic param names in extensions.
Skipping attribute application on non-matching extensions constraints added at 63b053d7d7c0503d6630453e0db022f478643593
