### ISSUE TITLE
Minor IDE UX improvement: display if the 'Save As' button is inactive

### ISSUE THREAD

**Issue by SamWindell** [beefytech/Beef#181]
With an empty solution with no source files, the Save As button does not do anything. Presumably, because there is nothing to save.

I think it probably should still save just an empty solution file. If not, the alternative would be to either grey-out that button or display a popup dialog explaining that the solution is empty so it cannot save.

**Comment by bfiete** [comment]
Added this in https://github.com/beefytech/Beef/commit/3ebe00d59a81cb6b1f9b04f518e9fbc8672a2084, plus a bunch of other grey-outs
