### ISSUE TITLE
[Bug] const int16 multiplication is adding

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1814]
When doing multiplication with a `const int16`, it does addition instead of multiplication.
Other types like `int8`, `uint16` works fine. Using variables instead of const also works fine.
Tested with latest nightly.

Examples:
```beef
        int16 example1 = 10 * 2;
        System.Diagnostics.Debug.WriteLine($"{example1}");

        bool example2 = (int16)10 * 2 == 12;
        System.Diagnostics.Debug.WriteLine($"{example2}");
```

Output:
```
12
True
```

**Comment by bfiete** [comment]
Fixed at ef9464900ec22e4344366badee8e51b709238f11
