### ISSUE TITLE
Console.ReadLine() doesn't work like it's supposed to

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#1829]
I believe [this](https://github.com/beefytech/Beef/commit/5146a92f2e2ac69b09568ac70295caf6e54bb96a) commit, specifically [this](https://github.com/beefytech/Beef/commit/5146a92f2e2ac69b09568ac70295caf6e54bb96a#diff-35ac63e1e7039ad7d9259cc3a3ca97b9fd0c23661adff60c32a4264608113d03R174) line, which disables echoing and when reading, I need to hit Enter twice to get both `\r` and `\n` to go through. I get the single-char input to work, but how can I use `Console.ReadLine()` like before?

**Comment by bfiete** [comment]
The fix was a bit more involved than I would have liked, but it should be fixed at 037cb39240141b8c7752ccf8e88d2b67c43375a3
