### ISSUE TITLE
IDE crash when referencing a certain static method

### ISSUE THREAD

**Issue by jayrulez** [beefytech/Beef#1830]
[CrashDump_Random0.zip](https://github.com/beefytech/Beef/files/11180322/CrashDump_Random0.zip)

I don't have a lot of details but I will try to attach a repro later.

**Comment by bfiete** [comment]
Should be fixed at aabd84368d23581d5283b91639a53627dfdbf80b

**Comment by bfiete** [comment]
(maybe!)
