### ISSUE TITLE
Auto formatter breaks with the following code

### ISSUE THREAD

**Issue by ShootMe** [beefytech/Beef#1831]
When auto formatting the code with Ctrl+K Ctrl+D, this looks to break it and any code beyond this will not get reformatted.

```
for (int k = 1, m = 0; k <= 20; k++) {
   for (int i = k, j = m; i <= 20; i++) {
       Test(k,i);
        j += i;
   }
   m += k + 1;
}
```

**Comment by bfiete** [comment]
Fixed at 41ab77d22df875a5194aa2706a8af76d30736cc8
