### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1838]
The code below compiles fine on Windows but causes a Segmentation Fault on Linux.
```cs
using System;

namespace TryBeef {
	enum MyEnum {
		A,
		B,
		C
	}
	
	class Program {
		public static mixin Concat(var str1, var str2) {
			scope:mixin String(str1)..Append(str2)
		}

		public static void Main(String[] args) {
			MyEnum m = .B;
			Console.WriteLine(Concat!(@"m-", m.ToString(.. scope .()).ToLower()));
		}
	}
}
```
(https://trybeef.netlify.app/#/YiAS18)

The main issue seems to be this line:
```cs
Console.WriteLine(Concat!(@"m-", m.ToString(.. scope .()).ToLower()));
```
To be more specific, if you change `.ToLower()` to `..ToLower()` the segfault stops happening.

Tested with: https://github.com/beefytech/Beef/commit/678bdc0ba6169eb8c7f8dc820eccd3d71396a258

**Comment by bfiete** [comment]
Fixed at f723ce1e3917ea32d152ea1487d51b24945c8ac1
