### ISSUE TITLE
IDE crash when trying to use "System.Runtime"

### ISSUE THREAD

**Issue by akderebur** [beefytech/Beef#184]
I was trying to use DllImport and wanted to reference "System.Runtime.InteropServices" for it. The IDE showed and exception and crashed in the process. I have attached a screenshot.

![beef_sysruntime_crash](https://user-images.githubusercontent.com/13797984/80746138-0f4fd980-8b2a-11ea-9273-9d7ac0b6766c.png)

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/4a3871a6c07deab8101a66fa1eb5f97865b3b07a. Will be in 0.42.4.
