### ISSUE TITLE
[BUG] Compiler segmentation fault with void enumerators

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#1846]
Title says it all

**Comment by bfiete** [comment]
Does it? A code sample would definitely be better.

**Comment by MineGame159** [comment]
```beef
using System;
using System.Collections;

namespace Test;

class Program {
	public static void Main(String[] args) {
		for (let a in LineEnumerator()) {}
	}
}

struct LineEnumerator : IEnumerator<void> {
	public Result<void> GetNext() {
		return .Err;
	}
}
```
Here is a code sample I just created. Althought with this code it seems like it only seg faults when compiling in release mode but at one point it was happening in debug mode too. Can't recreate that now tho.
