### ISSUE TITLE
Crash at end of installation; crash at start of IDE and debug IDE

### ISSUE THREAD

**Issue by targrub** [beefytech/Beef#185]
Crashed at end of (Windows binary) installation procedure.
Crashes immediately when opening IDE or debug IDE.
Windows 7.  Version 0.42.2.0

[CrashDumps.zip](https://github.com/beefytech/Beef/files/4562068/CrashDumps.zip)

**Comment by HydrogenC** [comment]
The first problem is a duplication of #81, which is already fixed in 0.42.3.

**Comment by targrub** [comment]
If .pdbs were included with the distribution, that would help in debugging the problem.  (Since this is the not-from-source provided binary for Windows.)

**Comment by bfiete** [comment]
The PDBs are archived on a symbol server at symbols.beeflang.org.

**Comment by targrub** [comment]
Neither crash happens for me in 0.42.3.

**Comment by targrub** [comment]
> 
> 
> The PDBs are archived on a symbol server at symbols.beeflang.org.

404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: index.html
    RequestId: C600A05506C9FC5F
    HostId: P/lBE50DL2g/DGkztsA5281614fQTy3FLtZWe7JVIitjrIlXGIMqGt/qBx8z7uD0CW3mOgT1d4A=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html
