### ISSUE TITLE
[Crash] IDE CompTime Crash - Typecasting?

### ISSUE THREAD

**Issue by ESS-BrianValdillez** [beefytech/Beef#1862]
We've been seeing a number of Beef IDE crashes as of late. I've started attempting to repro them via a debugger to provide additional insight, since reproing them in small test projects has proven tricky. This one has occurred of `master`, with commit SHA `56315b291bd121e5e11db6ac278c5bffb4010902`.

Repro Steps:
-Opened workspace, crash randomly triggers a few seconds later (no input)

Output:
CrashCatcher::Crash
FATAL ERROR
toStructTypeInstance->IsSplattable() || (toStructTypeInstance->mInstSize == 0) in C:\EveningStar\Beef\IDEHelper\Compiler\BfModuleTypeUtils.cpp:14860

Callstack:
![image](https://github.com/beefytech/Beef/assets/97473654/4a191a56-5750-432a-8614-fbeb9d351e03)

**Comment by bfiete** [comment]
Well, I'd rather reproduce it and determine the root issue, BUT I've softened that assert to a recoverable non-fatal "internal error"...

0c6bf2d6b5b77d2da16c3b3867c4ae89f8107128

**Comment by bfiete** [comment]
Properly fixed at c18c76b4fee9a7d1f272887bba4d5948c228a176
