### ISSUE TITLE
Output window does not directly print numbers

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#1881]
`[Test]
public static void Test()
{
	Console.WriteLine(1);
}`

Will output an empty line in the Beef Ide's output Panel when tested.
This may be intended, but is confusing when you come upon it, without knowing the cause.

**Comment by bfiete** [comment]
The problem is not numbers, it's any line with only one character in it. `Console.WriteLine("a");` also fails to print.
