### ISSUE TITLE
[Enhancement] rest/leftover function for StringSplitEnumerator

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#1888]
A function returning the rest of the stringView from a string split enumerator.
I think can implement and pr this myself, im just not sure wether it would fit for the corelib.
This could be used to consume parts of a string and then get everything left, and may be usefull for some parsing situations.
Whats your oppinion on including this in corlib ?

**Comment by bfiete** [comment]
Yeah, that sounds fine. I'd probably have it be a property called `Remnant`...
