### ISSUE TITLE
libbacktrace should be in cmake dependencies

### ISSUE THREAD

**Issue by Skrylar** [beefytech/Beef#189]
On OpenSuSE, compiling fails because `backtrace.h` is missing. I located and installed a repository (https://github.com/ianlancetaylor/libbacktrace) and compiling moved forward.

- this dependency isn't mentioned in the "build from source" docs
- cmake doesn't seem to look for it before trying (and failing) to build it

**Comment by bfiete** [comment]
It'd sure be nice for someone to submit a PR that fixes it!

**Comment by damianday** [comment]
@bfiete a new GitHub tag might come in useful here for such simple things 'help wanted' or some such.

**Comment by baccenfutter** [comment]
Same goes goes for Gentoo and there seems to exist no Gentoo ebuild for libbacktrace.

@bfiete not quite sure what the correct place for this new dependency would be: `BeefySysLib/third_party/...` or `extern/...`?

**Comment by baccenfutter** [comment]
I added `extern/libbacktrace_build.sh` analog to `extrn/llvm_build.sh`. It clones/pulsl the git to `extern/ibbacktrace/`.

I then patched `BeefySysLib/CMakeLists.txt`:

```diff
@@ -50,6 +50,7 @@ else()
       third_party
       third_party/freetype/include
       ../extern
+      ../extern/libbacktrace
     )
 endif()
```

It builds :tada: only to then fail with:

```
[ 74%] Building CXX object IDEHelper/CMakeFiles/IDEHelper.dir/X64.cpp.o
In file included from /home/baccenfutter/src/github.com/beefytech/Beef/IDEHelper/X64.cpp:31:
/home/baccenfutter/src/github.com/beefytech/Beef/IDEHelper/../extern/llvm-project_8_0_0/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.h:132:10: fatal error: X86GenRegisterInfo.inc: No such file or directory
  132 | #include "X86GenRegisterInfo.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [IDEHelper/CMakeFiles/IDEHelper.dir/build.make:629: IDEHelper/CMakeFiles/IDEHelper.dir/X64.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:253: IDEHelper/CMakeFiles/IDEHelper.dir/all] Error 2
gmake: *** [Makefile:104: all] Error 2
```

Seems to be unrelated, but I'd still like to successfully finish a build before creating a PR.

**Comment by baccenfutter** [comment]
:mega:

**Comment by bfiete** [comment]
Backtrace is now optional - if you have it then it gets used, otherwise execinfo is used.
