### ISSUE TITLE
IDE does not support german keyboard input with Alt-Gr to type characters like {[]}~@|\

### ISSUE THREAD

**Issue by visard-git** [beefytech/Beef#19]
You can not type any of the characters "{[]}\~@|" in the IDE when using a german keyboard.
It does nothing when pressing the key combination alt-gr + key.

**Comment by tomasgrilo** [comment]
Same for me, and I use a portuguese keyboard, doesnt let me write these characters

**Comment by T-Jeremy** [comment]
Same for me, using a French keyboard (azerty)

**Comment by oswjk** [comment]
Doesn't work with Finnish keyboard either.

**Comment by Ivo-Balbaert** [comment]
Also doesn't work for a Belgian keyboard. Any alternative?

**Comment by bfiete** [comment]
This has been resolved - the fix will be in build 0.42.2. There is no known workaround.

**Comment by Ivo-Balbaert** [comment]
Thanks Brian! I just stumbled upon Beef, but I think it is an amazing effort!

**Comment by bfiete** [comment]
This should have been fixed for a while now.
