### ISSUE TITLE
maybe without distinguishing between class & struct ?

### ISSUE THREAD

**Issue by sgf** [beefytech/Beef#1904]
Regarding passing by reference and passing by value, whether it can be decided by the compiler (without distinguishing between class & struct), rather than letting people decide.
 I am a C# developer and I know this capability of C#. But now it doesn't seem to be good enough.
Design that leaves the details in human control is bad. It is better to leave these to automated decision-making.

**Comment by bfiete** [comment]
I'm not sure I understand your proposal here. Can you give some examples of what you expect the compiler to "decide" with this proposal?

**Comment by bfiete** [comment]
Oh, I get it, you're proposing getting rid of just combining struct and class or something. That's a different language. Feel free to experiment with language design yourself if you wish but that kind of thing will not happen in this language.

**Comment by sgf** [comment]
Similar to golang

**Comment by sgf** [comment]
OK,tks

**Comment by bfiete** [comment]
In what way does Go "let the compiler decide" 
1) Whether an argument is passed by reference or value?
2) Whether a type declaration is a reference type or a value type?

Anyway, in Beef there are a lot of other differences between structs and classes besides how they are passed as arguments. Classes can have virtual methods, they have have append allocations, you can perform dynamic casts on them, they can track memory leaks and report allocation stack traces, Structs are really just aggregates of values...

And I really _would not_ want my compiler to be "smart" about making semantic decisions like you propose. In practice it would mean that one time you compile and the compiler makes one decision and then you change sometime small and the compiler makes a different decision and now your program behaves differently and you have no idea why or how to make it go back to the previous decision. 

I like the idea of a language where you initially define a program a program in a vague way and then work with the compiler through a number of *stable and reproducible* refinement and clarification stages... but so far no language researchers have even the beginnings of such a thing, and even if they did it would probably take another 10 years to make it into a language you could actually use.
