### ISSUE TITLE
[Enhancement] Add indexers to the method list of the opened file

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#1907]
As described in the title, it would be great if the IDE included the indexer(s) in the list above the source code view.
The same way as it is displayed in the class view, shown in the picture.

![kép](https://github.com/beefytech/Beef/assets/6961586/a4813a2e-596d-4816-9762-573c8079b211)

**Comment by bfiete** [comment]
Fixed at 13c66a7d3150218a187867d659e10ce8db328541
