### ISSUE TITLE
Project is able to compile in a broken state due to comptime reflection

### ISSUE THREAD

**Issue by EnokViking** [beefytech/Beef#1919]
(Possibly?) because the reflected type is a tuple, unsure.

Line 50 in FlecsBeef/EcsSystem.bf
This line breaks comptime, comptime debugging yields no errors but the IDE suggests otherwise by displaying a red symbol in the bottom left.
```cs
if (info.GetValue<uint64>(null, let val) case .Ok) {
							
}
```

Line 52 in Testbed/EditorUI.bf, because comptime breaks, the wrong constructor signature is being used when creating a FlecsSystem instance and this shouldn't compile, but it does.

[FullWorkspaceWithLibs.zip](https://github.com/beefytech/Beef/files/13941652/FullWorkspaceWithLibs.zip)

**Comment by bfiete** [comment]
There's no workspace file in this zip

**Comment by EnokViking** [comment]
Oops, fixed

**Comment by EnokViking** [comment]
Actually I'm daft and what I'm trying to do wouldn't work because the value i'm trying to read during comptime isn't written until runtime so that's a bit silly, but either way the jankyness with being able to compile broken code is still an issue, even if it's due to me doing something dumb.

**Comment by bfiete** [comment]
Comptime reflection reads of static fields were just not allowed before. Now they do... a35618651466aee43db9c74c08b9d8003a72bf08
