### ISSUE TITLE
Tabs, carriage returns, and newlines in command line arguments are treated as separate arguments

### ISSUE THREAD

**Issue by rzuckerm** [beefytech/Beef#1920]
This is a test program that reproduces the issue:

```beef
using System;

namespace CommandLineBug;

class Program
{
    public static int Main(String[] args)
    {
        for (int count < args.Count)
        {
            Console.WriteLine($"Arg {count} = '{args[count]}'");
        }

        return 0;
    }
}
```

I compiled the program with tip version of Beef on a Ubuntu 22.04 Linux System. Here are some sample runs:

```console
$ CommandLineBug/build/Debug_Linux64/CommandLineBug/CommandLineBug "$(printf '\tHello\tThere\tFriend\t')"
Arg 0 = 'Hello'
Arg 1 = 'There'
Arg 2 = 'Friend'
$ CommandLineBug/build/Debug_Linux64/CommandLineBug/CommandLineBug "$(printf '\nHello\nThere\nFriend\n')"
Arg 0 = 'Hello'
Arg 1 = 'There'
Arg 2 = 'Friend'
$ CommandLineBug/build/Debug_Linux64/CommandLineBug/CommandLineBug "$(printf '\rHello\rThere\rFriend\r')"
Arg 0 = 'Hello'
Arg 1 = 'There'
Arg 2 = 'Friend'
$ 
```

All the above should just give a single argument instead of 3.

To prove that the `printf` statement above yields a single command-line argument, I tried this simple python script:

```console
$ python3 -c "import sys; print(repr(sys.argv[1:]))" "$(printf '\tHello\t\There\tFriend'\t)"
['\tHello\t\\There\tFriend\t']
$
```

To give some context as to why I'd need to accept such a command line argument is due to the [Remove All Whitespace project](https://sampleprograms.io/projects/remove-all-whitespace/) for the [Sample Programs repository](https://github.com/TheRenegadeCoder/sample-programs).

I'm willing to fix this, but I'll need some guidance on how to procede. I have studied a bit of the Core Library code, but I haven't looked at any of the C++ code that is used for the compiler.

**Comment by bfiete** [comment]
The command line parsing is completely in Beef @ https://github.com/beefytech/Beef/blob/d4529786055e6b9f6e5f032b2910a87f242f494c/BeefLibs/corlib/src/Internal.bf#L258

**Comment by rzuckerm** [comment]
OK, thanks, I'll take a look.
