### ISSUE TITLE
[BUG] Wrong values in debugger

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1931]
Steps to reproduce: 
Just launch the project and wait for the breakpoint to hit, then try to inspect the values of `size` and `position` in `colorRect`

Seems to happen mostly on first compilation

Project:
[WrongFieldInit.zip](https://github.com/beefytech/Beef/files/14289099/WrongFieldInit.zip)

Tested with: Nightly 02/14/2024

**Comment by bfiete** [comment]
Fixed at 6f8dbefdec8ce05b66c0af0b54a48a6e2042d0af

I was expecting a more interesting bug but it was one of those just "using the wrong number" kind of deals.
