### ISSUE TITLE
[Feature Request / BUG?] Allow append fields costructor reference Self type

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#1932]
Currently the following code fails to compile with error: `Field 'Tests.Program.Foo.doesNotWork' causes a data cycle`

```cs
class Foo
{
	public append List<Foo> works;
	public append List<Foo> doesNotWork = .(4); 
}
```
Would it be possible to make it work?

**Comment by bfiete** [comment]
Works at 1c310e1bec1d0d2b3fb8e5a534a529830a6b61e8
