### ISSUE TITLE
Corrupt data using fixed-size array constructor

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#1938]
When using a fixed-sized array contructor with content from another array, it corrupts the data.
This is a regression within the last month or so. Happens in both Release and Debug in the latest nightly.

Example:
```beef
char8[1] charTable = .('b');
char8[4] chars = .('a', charTable[0], 'c', 'd');
```
The result of `chars` is `('\0', 'b', '\0', '\0')`

Changing the `charTable` to an array has the following effect:
```beef
char8[] charTable = scope .('b');
char8[4] chars = .('a', charTable[0], 'c', 'd');
```
The result of `chars` is `('\0', 'b', '\t', 'B')`

**Comment by bfiete** [comment]
Fixed at ddd9b1b21874fcbe1e802c54b3fcf5d45affb38b
