### ISSUE TITLE
[BUG] Syntax highlighting partially disappears in locked project when pressing backspace

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#1939]
**Steps to reproduce**:
1. Create an empty project
2. Add SDL2 as dependency
3. Open SDL2.bf
4. From line 31 ("public static class SDL") select either the word "public" or "static".
5. Press backspace

The problem is not related in any way to SDL, but this was the way I stumbled upon this issue.

**Version**: 0.43.5 (Nightly 03/16/2024) built 3/16/2024

![beef_syntax_highlight](https://github.com/beefytech/Beef/assets/6961586/c761b0d3-af8d-4675-bfd5-8d94ec5d340c)

**Comment by bfiete** [comment]
Fixed at dea665055e2ccd9b2a43ab7618df5e337b5e226d
