### ISSUE TITLE
IDE crash when hot compiling

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#1941]
When trying to hot compile code changes in this [project](https://drive.google.com/file/d/1fEC_-I_q7L8sappZNBzSvxziBfo6RJxj/view?usp=sharing) (it's the same project as for issue #1940) the IDE crashes.

Here is a crash dump from the latest nightly build (16.03.2024): [hotcompile_crash.zip](https://github.com/beefytech/Beef/files/14624766/hotcompile_crash.zip)

**Comment by bfiete** [comment]
Fixed at 887cbc3fa318273f5aab1e0b7f5e6a415f659cb8
