### ISSUE TITLE
Undo corruption

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1952]
Undo gets corrupted in the case below:

https://github.com/beefytech/Beef/assets/86157825/583cd0a5-411e-45cb-a311-7a857768c81a

Tested with: https://github.com/beefytech/Beef/commit/2168fb6917088f00b2d8b4a5e90e88828111da11

**Comment by bfiete** [comment]
Yaay! I'm almost positive this is _the_ mysterious undo bug, and it's been there for 5 years.
Fixed at 6a5b0b49ed02b36f043caee2eff9cfab91334b0f
