### ISSUE TITLE
[BUG] Watched variable lowercase format

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#1954]
Version: 0.43.5 (Nightly 04/08/2024)

According to the docs ( https://www.beeflang.org/docs/ide/watch/ ), the lowercase 'x' specifier should result in a lowercase hexadecimal value. But right now, lower and uppercase formatting shares the same code with uppercase formatting here:

https://github.com/beefytech/Beef/blob/2168fb6917088f00b2d8b4a5e90e88828111da11/IDEHelper/WinDebugger.cpp#L6253-L6276

I assume only the 'X' should be changed to lowercase in the format string on this line after `%d`:

https://github.com/beefytech/Beef/blob/2168fb6917088f00b2d8b4a5e90e88828111da11/IDEHelper/WinDebugger.cpp#L6274

![beef_format](https://github.com/beefytech/Beef/assets/6961586/10d1fd5e-6ef7-48ff-acca-ef997ac44ef6)

**Comment by bfiete** [comment]
To be fair, I did have a `//TODO: Implement HexadecimalLower` there!

Fixed at 21e92ae015914540d904a3ceb1149528b059f3f7
