### ISSUE TITLE
[BUG] Watch tab/window: Most of the right-click context menu items not working

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#1955]
Version: 0.43.5 (Nightly 04/08/2024)

Right click menu items and their states:

**Default Display**: works
**Watch Display**: works
**Lock**: can't change mode
**Add Watch -> Duplicate**: watch not duplicated
**Break when value changes**: works (Error if the value is stored in register, which is understandable)
**Copy Value**: value not copied to clipboard
**Copy Expression**: expression not copied to clipboard
**Delete Watch**: watch not deleted (pressing DEL on keyboard works)

It seemed strange that the majority of the functions didn't work. As if the click don't get registered, but then why the display format ones work? So I tried it in a clean VM, and got the same result.

![beef-watch-context-menu](https://github.com/beefytech/Beef/assets/6961586/0335d8d8-7f9a-4968-93c7-69a5162972c0)

**Comment by Hiroko103** [comment]
Updated "Break when value changes" part, because I had a wrong assumption.

**Comment by bfiete** [comment]
Yeah I think I broke this with the "find in watch" feature.. will investigate, thanks.

**Comment by bfiete** [comment]
Fixed at 16ed9ff8cfd83c061c5825870b706a1d30b91892
