### ISSUE TITLE
[Enhancement] Comptime Hashes

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#1956]
I think that corlib should support hashing at compile time, since they always output the same thing with the same input.
So logically a input that is "constant" at compile time should be able to be hashed at comptime.

**Comment by bfiete** [comment]
Can you give an example of some code that you expect to work but does not work?

**Comment by Booklordofthedings** [comment]
Something like:
`[ConstEval]MD5.Hash(Span<uint8>((.)"Input",5));`
and then being able to further work with the hash struct.

**Comment by bfiete** [comment]
Well Span isn't const-compatible since it inherently contains a pointer, but you should be able to trivially create a function that takes a string and MD5 hashes it and then you can const-eval that method with a string literal....
