### ISSUE TITLE
0.42.3 - Crash while building project

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#196]
When I try to compile the sample game for the Win32 platform the IDE crashes.

    Crash minidump saved as C:\Users\Igor\AppData\Local\BeefLang\bin\CrashDumps\BeefIDE_20200503_004212.dmp

    Exception: Access Violation (code 0xc0000005) at address 23c'45e1e004 in thread 1F28
    Executable: C:\Users\Igor\AppData\Local\BeefLang\bin\BeefIDE.exe
    File Version: 0.42.3
    Product Version: 82ca79947062fc098422ceba72aef5f0710c3dc2

    Logical Address: 0001:'0014d004

    b6'40fde430 23c'45e1e004 IDEHelper64.dll BfpFindFileData_GetTime_LastWrite+20F24
        Params: 23c'0000023f 23c'58324e90 b6'40fde540 23c'57a72020

    b6'40fde7f0 23c'45e1482e IDEHelper64.dll BfpFindFileData_GetTime_LastWrite+1774E
        Params: 23c'584195b8 23c'57d77008 23c'57f9f3b8 23c'00000280

    b6'40fde820 23c'45e1132f IDEHelper64.dll BfpFindFileData_GetTime_LastWrite+1424F
        Params: 23c'57ef4e90 23c'45b345b0 b6'40fde930 23c'57a72020

    b6'40fdfef0 23c'45dabec0 IDEHelper64.dll CDep_Shutdown+10A00
        Params: 23c'57944120 '00000000 '00000000 23c'584ac9c0

    b6'40fdff20 7ff9'49ba7bd4 KERNEL32.DLL BaseThreadInitThunk+14
        Params: '00000000 '00000000 '00000000 '00000000

    b6'40fdffa0 7ff9'4b92ce51 ntdll.dll RtlUserThreadStart+21
        Params: '00000000 '00000000 '00000000 '00000000

    RAX:23c'57f9f380 RBX:'00000000 RCX:23c'57ef4d00 RDX:23c'584195b8 RSI:23c'57a72020 RDI:23c'584195b8
    R8:'00000000 R9:b6'40fde4d0 R10:'00000000 R11:23c'58324e90
    R12:23c'58324e90 R13:'00000001 R14:23c'57ef4d00 R15:23c'57a71b90
    EIP:23c'45e1e004 ESP:b6'40fde3d0 EBP:b6'40fde4d0
    CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
    Flags:'00010202

Crash dump:
[dump.zip](https://github.com/beefytech/Beef/files/4569593/dump.zip)

**Comment by Igoorx** [comment]
Btw, maybe this is related to the crash, this message appears five times alongside the crash:
![image](https://user-images.githubusercontent.com/14041768/80898387-37ca0600-8cd9-11ea-962e-0884ad3d0a7c.png)

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/ae3ea7f2091b6feb18b4c902d42f01ec89913812, will be in release 0.42.4. There will still be linker errors because I only packaged up the 64-bit dlls and libs for SDL2, but presumably if those were added then it would work. Untested.
