### ISSUE TITLE
Beef IDE 0.42.3 Crash - Missing return statement

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#197]
The following code crashes the IDE when building, but only in Release mode. In Debug mode, it compiles and runs just fine.
The IDE doesn't complain that there is no return statement after the while block.

```
using System;

namespace IDECrash
{
    class Program
    {
        public static Result<void> func(){
            while(false){
                return .Ok;
            }
        }

        public static void Main(){
            func();
            return;
        }
    }
}
```

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/dedaf989a61ca746e162e474b9d1930b961ea439, will be in release 0.42.4.

**Comment by Hiroko103** [comment]
Thank you!

Does this fix account for cases when the condition can't be evaluated/optimized out at compile time?

**Comment by Hiroko103** [comment]
I tested it in the new version, and it works in every case.
