### ISSUE TITLE
IDE crashes... AGAIN

### ISSUE THREAD

**Issue by MiguelAtTweddle** [beefytech/Beef#198]
When starting the Sample project 'Hello World', the IDE crashes. CrashDumps contains no dump, only placeholder.txt
Also tried changing the default font to Consolas, but still crashed.

**Comment by HydrogenC** [comment]
Sound weird, even not a minidump?

**Comment by bfiete** [comment]
More information wold be nice. Exactly when does the IDE crash - when the project is opened, when you are compiling, when the target executable runs? What do you actually see on screen when it crashes? Does the SpaceGame sample work and just not the Hello World? Etc

**Comment by bfiete** [comment]
Closing due to lack of information.
