### ISSUE TITLE
Reformat Document mangles code when there's a mismatched curly bracket

### ISSUE THREAD

**Issue by daafu** [beefytech/Beef#1981]
Code with a mismatched curly bracket like this code:
```C#
class badclass
{
    void bad1(int num)
    {
    }
    } // stray curly

    void func2(int num1, int num2, int num3)
    {
    }
}
```
Get mangled into this by Reformat Document, noticed how func name, return, and variable types/names all get joined together:
```C#
class badclass
{
	void bad1(int num)
	{
	}
} // stray curly

voidfunc2(intnum1, intnum2, intnum3)
    {
}
}
```
This happens if Reformat Document is ran manually or enabled to also run on Save (which is my case).

**Comment by bfiete** [comment]
Fixed at c5098cb28b20e07fb828d792f3b1496c25fe63a5
It's not a very good fix, but it's a fix.
