### ISSUE TITLE
Issues with the new LLVM 18 update

### ISSUE THREAD

**Issue by disarray2077** [beefytech/Beef#1983]
I found two new issues after the update to LLVM 18:

- The IDE now crashes when opening the [LuaTinker](https://github.com/disarray2077/LuaTinker-Beef) project.
- The IDE now crashes when compiling this project in Release mode: [zip.zip](https://github.com/beefytech/Beef/files/15366153/zip.zip)

Tested with Beef Nightly 05/17/2024.

**Comment by bfiete** [comment]
The LuaTinker crash was fixed by your PR here already: https://github.com/beefytech/Beef/pull/1979

**Comment by disarray2077** [comment]
Oops, sorry for potentially wasting a bit of your time. I guess I got misled by the `BfCodeGen_GenerateObj+B655` in the crash window. Thinking back, I guess it was caused because it didn't load the Beef Nightly symbols.

**Comment by bfiete** [comment]
Other issue fixed here 7f480846edccbd531601d3d722068f587286c05f
