### ISSUE TITLE
[Bug] Diagnostics graphs: Time markers move to the wrong direction

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#1990]
In the diagnostics panel the time markers (5 seconds, 15 seconds, ...) move from left to right instead of right to left.

![beef_diagnostics_graph](https://github.com/beefytech/Beef/assets/6961586/34c76ce0-9ccf-4511-91af-7fdece17e5a2)

Version 0.43.5 (Nightly 06/02/2024) built 6/2/2024 at 9:30 PM.

**Comment by bfiete** [comment]
It's a non-linear time graph. Notice how after a while the left side has very little motion where the right side continues to show motion.

**Comment by bfiete** [comment]
Anyway, there's no bug here, it's just a side effect of how the data is displayed.

**Comment by bfiete** [comment]
Actually even if it weren't non-linear, the numbers would still move to the right. Maybe you're not understanding that the numbers indicate a time delta from "now"?

**Comment by bfiete** [comment]
(ie: "age")

**Comment by Hiroko103** [comment]
> Maybe you're not understanding that the numbers indicate a time delta from "now"?

Yes, you're right :) I was misunderstanding it, and thought that it was meant to represent the time elapsed since "start".
Thank you for the clarification.
