### ISSUE TITLE
Failure to build from source on windows 10

### ISSUE THREAD

**Issue by heisluft** [beefytech/Beef#1992]
Hello, I recently tried building Beef from source, But it fails after building the BeefBuild_bootd, BeefBuild_boot, BeefBuild_d and  BeefBuild,

the error is:
`lld-link: error: Not an int attribute (Producer: 'LLVM18.1.4' Reader: 'LLVM 13.0.0')`

How can I fix this?

Cheers

**Comment by bfiete** [comment]
It looks like it's using the LLVM 13.0 linker, which is strange since the only binary copy of lld-link is from a dependency zip that build.bat should download, and that one is the correct 18.1.4 version...

**Comment by heisluft** [comment]
I'd last built beef in 2022 when this behaviour was not in place yet, turns out I still had a script manually copying lld-link over from my Install. This old lld-link then overwrote the one from the Dependencies file. The bug once more sat in front of the computer. Thank you for your pointer!
