### ISSUE TITLE
[Enhancement] Integrated terminal panel

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#1995]
The IDE should have a panel that shows a terminal and allows users to input commands and run scripts from the IDE, similar to the one in vscode.

There are several benefits for such a feature that would make it nice to have. For one it would create an easy integration for cmd tools and scripts such as git.

# Main features
- [ ] New panel named "Console" that takes input and can display text output
- [ ] Asynchronously read the output of the console process once started
- [ ] If the panel is selected write keyboard inputs and events to the console process
- [ ] Tabs/Multiple console windows

## Smaller/Side features
- [ ] Custom path/command for the console that should be started by the IDE (This should probably be powershell by default)
- [ ] A different font and font settings just for the console
- [ ] Color support
- [ ] Ansci escape code support

**Comment by Booklordofthedings** [comment]
I have updated the tasks with the relevant info and progress from the discord

**Comment by bfiete** [comment]
And also the issue of whether it needs to be implemented as a Windows psuedoconsole using the Console API instead of through raw stdio redirection...

**Comment by Booklordofthedings** [comment]
Is the current behaviour enough or do you want more out of an implementation ?
Otherwise I would just close this issue as completed

**Comment by bfiete** [comment]
I think we can close this.
