### ISSUE TITLE
IDE save the file in wrong path.

### ISSUE THREAD

**Issue by Domain** [beefytech/Beef#20]
It seems the IDE cannot handle the Users folder in windows 10.
I save my workspace in:
![image](https://user-images.githubusercontent.com/903197/72198122-ae5da200-3463-11ea-9d96-030bca30ccb0.png)
The real path should be:
`C:\Users\Domain\source\repos\Beef\zero`
But when I save the workspace, the file is placed in:
`C:\用户\Domain\source\repos\Beef\zero`
i.e. the Users folder become '用户' in Chinese.

**Comment by bfiete** [comment]
I believe this is a dup of this issue: https://github.com/beefytech/Beef/issues/13
A temporary workaround is to install and work outside the Users directory...

**Comment by bfiete** [comment]
Dup.
