### ISSUE TITLE
Mixin return inconsistency

### ISSUE THREAD

**Issue by Grimelios** [beefytech/Beef#2001]
Consider the following example, using the mixin `ToScopedNativeWChar!()`:

```Beef
String str = "Hello!";
char16* wide = str.ToScopedNativeWChar!();
```

Works like a charm. Here's the same example using an expression block, which does _not_ compile:

```Beef
char16* wide =
{
    String str = "Hello!";
    char16* wide = str.ToScopedNativeWChar!(); // Error! (Unable to implicitly cast void to char16*)

    wide
};
```

This last example modifies the above the surround the mixin with curly braces, fixing the problem.

```Beef
char16* wide =
{
    String str = "Hello!";
    char16* wide = { str.ToScopedNativeWChar!() }; // This now works! (note the curly braces)

    wide
};
```

**Comment by bfiete** [comment]
Fixed at fd3bd861ae9c503a4c9b0c6ac55049e8b4af52a1
