### ISSUE TITLE
Beef 0.43.5 Nightly 07.25.2024 Crashing on opening Console.

### ISSUE THREAD

**Issue by tadgem** [beefytech/Beef#2002]
[console.dmp](https://github.com/user-attachments/files/16376868/console.dmp)
[console2.dmp](https://github.com/user-attachments/files/16376869/console2.dmp)

Attached 2 dumps. Repro steps for each follows:

dump1:
- install latest nightly beef from nightly archive
- open beef ide
- nav to view and click console
- observe

dump2:
- install latest nightly beef from nightly archive
- open beef ide
- open a workspace directory
- nav to view and click console
- observe

If I can provide anything else please do let me know

**Comment by bfiete** [comment]
I think this has been fixed for a while...

**Comment by tadgem** [comment]
thanks for addressing this!
