### ISSUE TITLE
Tuple type ToString empty scenarios

### ISSUE THREAD

**Issue by Grimelios** [beefytech/Beef#2004]
Converting a `System.Type` to a string seems to result in empty parentheses (`"()"`) in some cases. The first is below. Note that the first tuple has three members while the second has four.

```CSharp
public static void Main()
{
    Console.WriteLine(scope $"{typeof((int32, int32, int32))}");        // Outputs "(int32, int32, int32)"
    Console.WriteLine(scope $"{typeof((int32, int32, int32, int32))}"); // Outputs "()"
}
```

Another scenario involves tuples of custom structures. Just two tuple members results in `"()"` this time, even with an empty struct.

```CSharp
namespace A
{
	public static void Main()
	{
	    Console.WriteLine(scope $"{typeof(MyStruct)}");             // Outputs "A.MyStruct"    
	    Console.WriteLine(scope $"{typeof((MyStruct, MyStruct))}"); // Outputs "()"
	}

	public struct MyStruct
	{
	}
}

```

**Comment by bfiete** [comment]
Fixed at 04e67007dd0ec0ad9a279309a0105400290b6ad9
