### ISSUE TITLE
[BUG] Invalid gep Target

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#2006]
![image](https://github.com/user-attachments/assets/9b78c1c3-47d6-481f-ab8d-9521738fb58c)

I am getting this ide crash on the latest nightly, when debugging all tests on my parsing library

[Bofa.zip](https://github.com/user-attachments/files/16573832/Bofa.zip)

The project is also available here: https://code.booklordofthe.dev/Booklordofthedings/Bofa/src/branch/rewrite

**Comment by bfiete** [comment]
Fixed at f88e7523039aad79092e86eaf0ccbae5dead013a
