### ISSUE TITLE
[Bug] IDE crash on input/paste

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#2009]
Pasting the following into beefide crashes it for some reason
![grafik](https://github.com/user-attachments/assets/9af956ec-afb5-4e09-8983-5e9d8044e4c9)

```
namespace System;

extension StringView
{
	publics bool operator==(StringView val1, StringView val2)
	{

	}
}

**Comment by bfiete** [comment]
Fixed at 4bfa087cecaa5892454ed6b77db279a16af02227
