### ISSUE TITLE
CopyToDependents fails in some projects for no obvious reason.

### ISSUE THREAD

**Issue by EnokViking** [beefytech/Beef#2013]
`CopyToDependents("$(ProjectDir)/resources/shaders/circle_sdf.fs")`
This here for instance, doesn't do anything for me but in some projects such as the space shooter sample, DLL's are copied and also in some older projects of mine.

**Comment by bfiete** [comment]
Can you provide a sample workspace where this fails?

**Comment by bfiete** [comment]
Closing due to lack of information/repro.

**Comment by EnokViking** [comment]
[Random.zip](https://github.com/user-attachments/files/17559320/Random.zip)

**Comment by bfiete** [comment]
In the workspace you provided you have a CopyToDependents in Random, but Random _does not have any dependents_.

A dependent is a project that _depends_ on this project.

You would normally put CopyToDependents in a library such as SDL2, which would copy the SDL2 dlls to projects that depend on SDL2.

**Comment by bfiete** [comment]
Maybe you wanted `CopyFilesIfNewer` and not `CopyToDependents`

**Comment by bfiete** [comment]
That being said, perhaps it does make sense to have something like a `CopyToTarget` which works the way you apparently expected: it can be used in either a dependency's postbuild or in a project's own postbuild.

**Comment by bfiete** [comment]
We added a `CopyToTarget` at 2c630a5ba9cfb63b3b4d95dfcf7dd19c73afb1ec
