### ISSUE TITLE
[Bug] IsComposite Assert triggers

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#2014]
There is an assert in IsComposite which errors on my project while being called from BeIRCodeGen.cpp:1700

My project and the dump are attached

![image](https://github.com/user-attachments/assets/88e4dbfb-19da-4d80-98ec-57c9b6cf5639)
[Bofa.zip](https://github.com/user-attachments/files/16732975/Bofa.zip)
[dmp.dmp](https://github.com/user-attachments/files/16732978/dmp.dmp)

**Comment by bfiete** [comment]
Fixed at 29b2299dc2834d4ce080eb6ed100e318d82378c0
