### ISSUE TITLE
Weird leak checker behaviour

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#2015]
My parsing library for a custom object notation allegedly leaks sometimes.
[Bofa.zip](https://github.com/user-attachments/files/16736659/Bofa.zip)

The main problem here is, that its not consistent with its leaks.
Sometimes no leaks are found, other times it finds multiple different ones.
Most of the time if it finds a leak it reports it at originating in BofaParser.bf:35.

**Comment by bfiete** [comment]
Fixed at c18e24d7e6953a50a8bda1dcf12caad1c5ecac18

It was actually a bug in the GC - pretty rare find.
