### ISSUE TITLE
[Bug] Debugger: Hover on variable shows misleading value

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#2016]
If a method in a class contains a variable with the same name as one of the class' variable,
then hovering on the class' variable during debugging will show the value of the variable inside the method.

![beef-debugger-variable](https://github.com/user-attachments/assets/8e07ca85-a177-4e06-b55b-ca905b15444e)

Code:
```
namespace beefbug;

class A {
	public int var1 = 5;

	public void Method(){
		let var1 = 10;
	}
}

class Program
{
	public static void Main(){
		A a = scope A();
		a.Method();
	}
}
```

Version: 0.43.5 (Nightly 08/23/2024)

**Comment by bfiete** [comment]
Yeah, that's life. There isn't a debugger in the world that handles that case.

**Comment by bfiete** [comment]
The metal model you need is this: mousing over text just evaluates the text you mouse over. That's it. There is no "surrounding context" taken into account. That's how all debuggers work that I have ever seen.

**Comment by Hiroko103** [comment]
Ohh.. I didn't know it. Although I was half-expecting this answer.
It seems Beef was the first language in which I got into a situation like this.
I tried it with two other languages and you're right, they also work the same way.
