### ISSUE TITLE
[Enhancement] Flip horizontal scrolling direction

### ISSUE THREAD

**Issue by Grimelios** [beefytech/Beef#2021]
When a horizontal scroll bar is visible in the IDE (in any panel), horizontal scroll directionality behaves the opposite of what I'm accustomed to in other contexts (e.g. within a web browser or when using my phone). For vertical scrolling, the contents of the panel follow the direction of your scroll. For horizontal scrolling, the contents of the panel move in the _opposite_ direction.

An IDE setting to flip directionality would be a minor, but appreciated feature.

**Comment by bfiete** [comment]
Fixed at 4af432955efa32d93123a0bcd5e9077a8e35c684

I just flipped it - no setting. We'll see if anyone complains about it going the "wrong" direction now but I can't imagine anyone who actually uses horizontal mouse wheel scrolling would want it to scroll the opposite of their other apps.
