### ISSUE TITLE
Cannot use initializer properties when passing structs with in.

### ISSUE THREAD

**Issue by jayrulez** [beefytech/Beef#2022]
The issue is shown in the ss below:
![image](https://github.com/user-attachments/assets/cd1c4496-76b2-4a47-b79e-9c38692a5f36)

Sample reproduction code:
```
class Program
{
	struct MyStruct{
		public int X;
	}

	public static void TakeInStruct(in MyStruct s)
	{

	}

	public static void Main()
	{
		TakeInStruct(.() {X = 0});
        }
}
```

**Comment by bfiete** [comment]
Fixed at b34a14502d854db9197d4e387122d37c6ea282e9
