### ISSUE TITLE
[Enhancement] Support custom indexers in interfaces

### ISSUE THREAD

**Issue by Grimelios** [beefytech/Beef#2033]
Beef currently doesn't support custom indexers defined in interfaces, as shown below:

```Beef
public interface IIndexable<T>
{
    T this[int index] { get; set; }
}

public static void Get<T>(T indexable) where T : IIndexable<float>
{
    // This fails!
    float f = indexable[0];
}
```

The same functionality can be achieved using `ref T Index(int index);` in the interface, but a traditional indexer would probably be preferable to most users.

**Comment by bfiete** [comment]
Fixed at c53ef1c3465db98824b4198d935a375dfc2b536c
