### ISSUE TITLE
[Enhancement] Theme color for member variables

### ISSUE THREAD

**Issue by Grimelios** [beefytech/Beef#2035]
Custom themes can use the `Identifier` key to highlight identifiers, but there's currently no way to visually distinguish between member variables and local variables. As an example, here's a screenshot from Visual Studio where `solver` is a member variable of the surrounding class, while `sourceSet` and `sourceSetIndex` are local variables within the function.

![image](https://github.com/user-attachments/assets/311672c8-f6ca-4ef9-8610-779de412983d)

With this distinction, I often use the `this.` prefix liberally, which does clarify a variable's origin at a glance, but also (arguably) clutters the code.

**Comment by bfiete** [comment]
Added at 2b9fa80b81c691c16a199c710434afc63f992fd9

There is now custom colorization of: Member, Local, Parameter

Member defaults to Identifier color
Local defaults Identifier color
Parameter defaults to Local color
