### ISSUE TITLE
Crash from primitive type constraints

### ISSUE THREAD

**Issue by zerkawei** [beefytech/Beef#2036]
In the latest nightly the following code causes the IDE to crash :
```csharp
namespace Repro;

struct Foo<T> where T : int
{
	public this(T[2] values) { }
	public this(T value) { }

	// These cause crashes
	// public static Self Bar() => .(T[2](0, 0));
	// public static Self Bar() => .(default);

	// This works
	public static Self Bar() => .(0);
}
```
Crash dump : [crash.dmp](https://github.com/user-attachments/files/17169198/crash.dmp)

**Comment by bfiete** [comment]
I'm unable to reproduce the issue. Are you able to still reproduce this crash?

**Comment by zerkawei** [comment]
I can't reproduce this crash in the latest nightly, I'll close this issue.
