### ISSUE TITLE
CopyToDependants not working with multiple projects

### ISSUE THREAD

**Issue by DeFYzz** [beefytech/Beef#204]
Im using three projects for testing things out and when using two library projects as dependencies in a console application, CopyToDependants doesnt seem to work. It only copies one file.
The postbuild code is the same in both libraries:
`CopyToDependents("$(ProjectDir)/dist/*.dll")`
When specifying the name directly, it says that it cannot find the file but its looking in the wrong project directory. So it tries to copy the file only existing in the second project from the first project. Looks like a bug to me.

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/0a7e0e01e62d32ecde7ca885d039b3566fdfcda3, will be in 0.42.4.
