### ISSUE TITLE
[Bug] Crash when opening project after latest update

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#2042]
I updated to the latest Beef nightly, and the IDE crashes as soon as I open my project.

Caused by commit bf3dec9

Debugging the IDE gives me this.
Looks like typeInst is null.
![image](https://github.com/user-attachments/assets/6fd59b74-cd1c-4879-b954-befc7748dddb)

**Comment by bfiete** [comment]
Fixed at 01eb80c3d44f24c714722308710fbdbbfba4083a
