### ISSUE TITLE
@ variable fails for return

### ISSUE THREAD

**Issue by Grimelios** [beefytech/Beef#2043]
The `@` symbol can be used to create a variable using an otherwise reserved keyword, but seems to fail for `return`:

```CSharp
let @let = 0;
let @var = 1;
let @return = 2;
let copy1 = @let; // Works!
let copy2 = @var; // Works!
let copy3 = @return; // Fails! ("Identifier not found")
```

Interestingly, adding a _second_ `@` appears to fix the problem:

```CSharp
let @return = 0;
let copy = @@return; // Works!
```

I haven't exhaustively tested `@` variables for every keyword that would otherwise be invalid without `@`, so it's possible this issue applies to other reserved words too.

**Comment by bfiete** [comment]
`@return` is internally generated. It is the return value of the method. One use case is documented here:
https://www.beeflang.org/docs/language-guide/comptime/#compile-time-code-generation

**Comment by Grimelios** [comment]
My mistake! Appreciate the quick reply.
