### ISSUE TITLE
[Bug] IDE crash while trying to create enum

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#2047]
The attached project crashes the ide.
```
typeInstance->mDefineState == BfTypeDefineState_Defined
```
in BfModuleTypeUtils.cpp:6213

It seems to be caused by adding: "public enum PropertyType : c" in SDL3.bf

[SDL3-Beef.zip](https://github.com/user-attachments/files/17474972/SDL3-Beef.zip)

**Comment by bfiete** [comment]
Can't reproduce.

:-(

Can you post the program in an actual broken state such that it crashes when compiled?

**Comment by Booklordofthedings** [comment]
Cannot seem to repro it on the newest nightly. Might be fixed or something else
