### ISSUE TITLE
[Bug] Missing files for compiling wasm

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#2048]
After the recent nightly updates, I tried running the SpaceGame sample in wasm32.
I got into a few issues I solved:

1\.
Unable to execute curl.exe. Full path: `C:\Program Files\BeefLang\bin\curl.exe`
Installing curl.exe manually worked.

2\.
Unable to execute tar.exe. Full path: `C:\Program Files\BeefLang\bin\tar.exe`
Installing tar.exe manually worked.

3\.
Missing `C:\Program Files\BeefLang\bin\Beef042RT32_wasm.a`
Found a file with the same name in `C:\Program Files\BeefLang\IDE\dist\` and copied it over. That worked.

4\.
Error: `Failed to launch: c:\Program Files\BeefLang\Samples\SpaceGame\dist\SpaceGame.html`

No idea why this is the case. The file is there, and it works.
But even if it where to run, the browser security does not allow for wasm to load. But this is not an issue, more of a feature request.

**Comment by m910q** [comment]
Yea, that would make is "just work" for people.
But it might be overkill for now.

I'm not suggesting adding the feature, my comment was more about opening the HTML directly is not going to work well for the majority of people.

If you fixed the other ones, I'm fine closing this one.

**Comment by bfiete** [comment]
Yeah. I think including a tiny HTTP server may be a good idea actually... But anyway, closing this one.
