### ISSUE TITLE
[BUG] Result<void, TErr> and implicit operator

### ISSUE THREAD

**Issue by kallisto56** [beefytech/Beef#2049]
Hi there,

Code below calls `Test` function, that always returns `.Ok` even though it should return `.Err`.
This is because of two reasons:
- implicit operator on `Result` that converts `Error` to `.Err(Error)`;
- single dot instead of two dots in line `return new Error().Append()`;

This happens only when `T` is `void`. For something like `Result<String, Error>` it still thinks that response is `.Ok`, but then it expects payload.

Tested on build from source: [bc5c425](https://github.com/beefytech/Beef/commit/bc5c425d1bc9f0b3653401c2d8686e2936fb99fc)

Here is the code to reproduce with issue:
```beef
namespace bug.NoResultDoubleDot;


using System;
using System.Diagnostics;


class Program
{
	static void Main ()
	{
		var response = Test();
		Debug.WriteLine("WARNING: {}", response);

		if (Error.sLastError != null)
			delete Error.sLastError;
	}

	static Result<void, Error> Test ()
	{
		return new Error().Append("Look to the left, there is only one dot!");
	}
}


class Error
{
	static public Error sLastError;

	public this ()
	{
		sLastError = this;
	}

	public void Append (StringView message)
	{

	}
}


namespace System;


extension Result<T, TErr>
{
	public static implicit operator Result<T, TErr>(TErr error)
	{
	    return .Err(error);
	}
}
```

**Comment by m910q** [comment]
Calling `.Append()` returns `void`, so if you only have one dot, you return `void` in the `Test()` function.
If the return type matches `T` in `Result<>`, there is an implicit operator to convert that to `.Ok`.

I fail to see any wrongdoing by the language here.

**Comment by bfiete** [comment]
Yeah I'm a bit confused about this too - @kallisto56 seems to understand that the `..` is required to flow Error through but then purposely _doesn't_...

**Comment by kallisto56** [comment]
My assumption was that `return` requires something explicit to return from the function. For example:
```beef
Result<Void> Test0()
{
   return;
}
```
Errors out with message "Expected return value".

I'm using double-dot feature especially with errors a lot and this was the first time I wrote single dot instead of two by mistake. This lead to a situation where I could not figure out why my application creates error, but then returns `.Ok`.

When I figured out what's going on, I assumed that in this case IDE/compiler would've show me an error saying something like `Expected return value`, because it does so with `Result<T>` where T is not `void`.

But, if everything seems fine to you, I'm okay with it. Issue can be closed.

**Comment by bfiete** [comment]
`return;` is not equivalent to `return (void)default;`
You could argue that it _should be_ but I wouldn't agree.

But, yes, I do believe it is a very good thing that `void` is first-class type and that we don't restrict its usage as you had expected we would. This allows it to be treated just like normal types in generics and generated code. Without first-class treatment `Result<void>` would not even work.
