### ISSUE TITLE
Link error if startup project does not share dependencies of all dependencies

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#205]
My case was:

[ Project A ]
Startup project
**Dependencies:** Project B, corlib

[ Project B ]
**Dependencies:** SDL2, corlib

**Error:** LNK2019: unresolved external symbol SDL_SetRenderDrawColor referenced in function...

Project A doesn't use SDL2 at all, Project B wraps it. Adding SDL2 to dependencies of Project A fixed the issue.

**Comment by damianday** [comment]
I've also had this, I assumed it was by design so just added all dependencies to the main project.

**Comment by MattThorson** [comment]
I can see the argument for it being intended, but then the error message should be more clear imo

**Comment by bfiete** [comment]
It's not intended - this is a real bug.

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/0a7e0e01e62d32ecde7ca885d039b3566fdfcda3

**Comment by MattThorson** [comment]
Confirmed fixed
