### ISSUE TITLE
Environment.NewLine is null within File.ReadAllText when called from static initializer

### ISSUE THREAD

**Issue by Grimelios** [beefytech/Beef#2050]
```CSharp
namespace MyNamespace
{
    static
    {
        static this()
        {
            // Assuming myFile.txt exists in the working directory, of course.
            let text = File.ReadAllText("myFile.txt", .. scope .());
        }
    }
}
```

Running this code gives an `EXCEPTION_ACCESS_VIOLATION` on line 77 of File.bf (in corlib) because `Environment.NewLine` is null. Accessing `Environment.NewLine` before reading the file avoids the issue:

```CSharp
 static this()
{
    let newLine = Environment.NewLine;

    // Works!
    let text = File.ReadAllText("myFile.txt", .. scope .());
}
```

The same code called from a main function also works:

```CSharp
namespace MyNamespace
{
    static
    {
        public static void Main()
        {
            // Works!
            let text = File.ReadAllText("myFile.txt", .. scope .());
        }
    }
}
```

Given these observations, the issue appears to involve static initialization order. I'm currently running the nightly build from October 23rd, 2024.

**Comment by bfiete** [comment]
Well that one's easy to fix ca2c78130112158ca2200145088477c62b1c03ce
Not sure why I made that static readonly instead of const to begin with.
