### ISSUE TITLE
Allow relaxed access of static fields, methods, properties and mixins withing the same namespace

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#2051]
In the code bellow, the field val1 cannot be assigned to field bar, because val1 is inaccessible due to its protection level.

```csharp
static
{
    static int val1 = 0;

    class Foo
    {
        int bar = val1;
    }
}
```

**Comment by bfiete** [comment]
Fixed at 6c66d27ff48604e62577794657fda8c1d505f2cd
