### ISSUE TITLE
[Bug] IDE crash when using "update package lock"

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#2053]
[AvenTemplate.zip](https://github.com/user-attachments/files/17574032/AvenTemplate.zip)

Ive added a repository without a semver restriction, then I choose Update Package Locks which resulted in the project being in this state and also crashing upon being opened by the ide

**Comment by bfiete** [comment]
Fixed at 2ea5c342524acb006fdbca0b1ae8d8c7fc82bf11
