### ISSUE TITLE
Beef IDE 0.43.5 (Nightly 10/30/2024) crashes trying to rename project

### ISSUE THREAD

**Issue by likadev** [beefytech/Beef#2054]
When I attempt to rename a project, after pressing Enter, the IDE crashes. Happens with or without Safe Mode. I attached the crash dump.

My setup is a GUI Application (sample), library (engine), external library (raylib-beef), and corlib. Renaming the library crashed once but works now. Renaming the main project crashes repeatedly
[rename-project-crash.dmp](https://github.com/user-attachments/files/17594176/rename-project-crash.dmp)
.
![image](https://github.com/user-attachments/assets/32f355e8-3996-4a7d-b31a-a879962a6317)

IDE version: 0.43.5 (Nightly 10/30/2024)

I have not tested this in other versions.

**Comment by likadev** [comment]
I just figured out that the crash only occurs when F2 is used to rename the project. When I right-click and select "Rename", it works without crashing.

**Comment by bfiete** [comment]
Thanks.
Fixed at 864d5e9d244f0ffd633b2fbd8d7190002cd50db3
