### ISSUE TITLE
llvm-ar does not properly combine intermediate .libs into final .lib

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#2057]
We are reworking some linker stuff for new version of the engine... we have run into something again that we worked around the first time.

When generating the static library .lib target, the llvm-ar command is trying to concatenate intermediate .lib outputs into the final .lib. **I don't think llvm-ar actually allows concatenating .lib archives**. Only .obj are getting pulled in properly.

For example, the IDE is generating this command line for the llvm-ar link:
```
"C:\\Program Files\\BeefLang\\bin\\llvm\\bin\\llvm-ar.exe" -qc "c:\\Users\\Hunter\\Projects\\RSDKv7\\Source\\Editor\\Libraries\\RSDKEditor_d.lib" "c:\\Users\\Hunter\\Projects\\RSDKv7\\Source\\Editor\\Beef\\build\\Debug_Win64\\corlib\\corlib__.lib" "c:\\Users\\Hunter\\Projects\\RSDKv7\\Source\\Editor\\Beef\\build\\Debug_Win64\\RSDK Core\\RSDK Core__.lib" "c:\\Users\\Hunter\\Projects\\RSDKv7\\Source\\Editor\\Beef\\build\\Debug_Win64\\RSDK Editor\\RSDK Editor__.lib" "c:\\Users\\Hunter\\Projects\\RSDKv7\\Source\\Editor\\Beef\\build\\Debug_Win64\\RSDK Editor\\vdata.obj"
```

but the RSDKEditor_d.lib only ends up with the contents of vdata.obj, and then also has warnings for all the libs it referenced.
nm says:
```
nm: corlib__.lib: File format not recognized
nm: RSDK: File format not recognized
nm: RSDK Editor__.lib: File format not recognized
```

dumpbin says:
```
RSDKEditor_d.lib : warning LNK4048: Invalid format file; ignored
RSDKEditor_d.lib : warning LNK4048: Invalid format file; ignored
RSDKEditor_d.lib : warning LNK4048: Invalid format file; ignored
```

This can be worked around by extracting all the intermediate libs with `llvm-ar -x` and then linking the resulting .obj files into the final archive

**Comment by bfiete** [comment]
Fixed at 4885871785898d125ea4aa1528279c10037c7c43
