### ISSUE TITLE
IDE Crash when typing `.this`

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#2059]
Basically anytime when `this` keyword is after dot. 

Example code
```
class Program
{
	static void Main ()
	{
		Program.this
	}
}
```

Tested with: Beef IDE Version 0.43.5 (Nightly 11/08/2024) Build 14a3dd8e7d024ed87a8ef3ab775ac180417168e9

**Comment by bfiete** [comment]
Fixed at f43da38dbbfcea985f213713ce93bc88ff52560d
