### ISSUE TITLE
[Crash][Bug] IDE crashes with empty params Span<> in attribute

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#2061]
Crashdump: [dmp.dmp](https://github.com/user-attachments/files/17700842/dmp.dmp)
Project: [Theater-ECS.zip](https://github.com/user-attachments/files/17700850/Theater-ECS.zip)

I have a crashdump attached, however I tested the zip and that doesnt seem to replicate the crash itself
Locally it crashes again upon opening the project.

It triggered for me, when removing the content of the span from this line
SystemMethodAttribute.bf:14
`public this(StringView name, params Span<> types)`

**Comment by bfiete** [comment]
Fixed at 28783a6b5aa4cf64debf91128504fa7a94d49015
