### ISSUE TITLE
Access violation when reflecting at comptime but the correct data is still being emitted.

### ISSUE THREAD

**Issue by EnokViking** [beefytech/Beef#2065]
(debug comptime also crashes the IDE with this code)
```cs
using System;
using System.Reflection;

namespace Random; static
{
	public static void Main()
	{
		TestStruct<Vertex> a = .();
	}

	//3 fields
	struct Vertex : this(float x, float y, float z);

	//emits 3 for TestStruct<Vertex>
	[TestAttribute]
	struct TestStruct<T> where T : struct {}
	struct TestAttributeAttribute : Attribute, IComptimeTypeApply
	{
		[Comptime]
		public void ApplyToType(Type type)
		{
			let specialType = (SpecializedGenericType)type;
			let fieldCount = specialType.GetGenericArg(0).FieldCount;

			Compiler.EmitTypeBody(type, scope $"uint32[{fieldCount}] offsets;");
		}
	}
}
```

**Comment by disarray2077** [comment]
This is because you're trying to cast UnspecializedGenericType to SpecializedGenericType. For each generic method, Beef will always run the comptime method in the unspecialized and specialized variants.

![image](https://github.com/user-attachments/assets/b8953f96-46ac-4b22-89aa-47d91e2045d7)

**Comment by bfiete** [comment]
Yes! 

I'd suggest dynamic casting: `if (let specialType = type as SpecializedGenericType)`

**Comment by EnokViking** [comment]
Ah ok that makes sense. Still an issue with the crash when trying to comptime debug though.

**Comment by EnokViking** [comment]
Well that's annoying, I opened up the same project with the same code and *now* I can't reproduce that anymore.. I'll see if I can figure out a more consistent repro.

**Comment by bfiete** [comment]
Are you still going to attempt a repro or should I close this?

**Comment by EnokViking** [comment]
I'll still try but you can close it, I'll make a new issue if/when i have a consistent repro.
