### ISSUE TITLE
[BUG] Access violation after printing float2 at least 8 times.

### ISSUE THREAD

**Issue by zerkawei** [beefytech/Beef#2068]
The following code causes Beef to try to delete an Object that doesn't exist at the end of the program. `[UnderlyingArray]` seems necessary for the bug to occur. It happens with `float2` and `bool2` but not `float4`, `int32_4` or `bool4`. Adding more `Console.WriteLine` will also trigger this bug but any less won't.
```csharp
public class Program
{
  public static void Main()
  {
      float2 e = ?;
      Console.WriteLine(e);
      Console.WriteLine(e);
      Console.WriteLine(e);
      Console.WriteLine(e);
      Console.WriteLine(e);
      Console.WriteLine(e);
      Console.WriteLine(e);
      Console.WriteLine(e);
  }
}
```

**Comment by bfiete** [comment]
Fixed at b2078b10feacc5e72112c894a2b1834cb29e4d65
