### ISSUE TITLE
Enum with one case can't be used as default value of optional parameter

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#2069]
The value of an enum with only one case can't be used as the default value for an optional parameter anymore.
```C#
enum MyEnum
{
	MyCase
}

public void DoStuff(MyEnum arg = .MyCase)
{
}
```
This throws the error: "Expression does not evaluate to a constant value."

**Comment by bfiete** [comment]
Fixed at 16915d2344fd78f4a6e194732c33b22d6244f2fd
