### ISSUE TITLE
[Bug] Creating const pointer value crashes IDE

### ISSUE THREAD

**Issue by m910q** [beefytech/Beef#2071]
Hey.

The following line crashes the IDE when compiling in the newest nightly.
I'm aware that the code is silly.

```beef
const uint32* NullVal = (.)("null");
```

![image](https://github.com/user-attachments/assets/396eb1c6-605b-4b80-9e8b-17206e3bc3c3)

**Comment by bfiete** [comment]
Fixed at 3864a8896bc2e46538ecf6ac61ce371e565a26c5
