### ISSUE TITLE
Console.ReadLine doesnt work on linux

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#2072]
Atleast it doesnt on some distros/terminals.
Rather it would read forever and never return
This can be fixed by setting *stdbuf -i0* in the terminal that calls that code.
If we wanted to fix this on the Beef side we could potentially call setvbuf or find another better approach (maybe just move it into the c++ runtime)
This issue is mostly here to document the fix for other people

**Comment by Booklordofthedings** [comment]
sorry I misinterpreted, the issue seems to only happen with BeefBuild -run

**Comment by bfiete** [comment]
Actually it didn't work on Windows either.
Fixed at 6a90faddc6e75196c3d2f48d0511d9bf5d869457
