### ISSUE TITLE
Is there any way for me to use reflection on a beeflang assembly via c++

### ISSUE THREAD

**Issue by jit-zs** [beefytech/Beef#2077]

**Comment by bfiete** [comment]
Depends on what you mean by "use reflection" and "via C++".

**Comment by bfiete** [comment]
IE: you could have Beef use reflection on itself via a method that is called from C++. That fits the question technically.

**Comment by jit-zs** [comment]
i mean have a method in c++ that can get a classes name, attribute, properties, etc of a class. I'm wondering if theres a library that will allow me to do this

**Comment by bfiete** [comment]
Nope. But the answer to this question is: yes there is a way, you just need to use or write a C-compatible library to do it.

**Comment by bfiete** [comment]
Discord is probably better than GitHub Issues for asking "how do I do this" questions.
