### ISSUE TITLE
StringView throws error when passed to WriteLine

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#208]
To reproduce:
```c#
// Program.bf
public String GetString()
{
    String str = "Hello, world!";
    return str;
}

public void Print()
{
    Console.WriteLine(GetString());
}
```
Causes error here:
```c#
// String.bf
public static operator StringView (String str)
{
    StringView sv;
    if (str != null)
    {
	sv.mPtr = str.Ptr;
	sv.mLength = str.[Friend]mLength; // Error: Attempted to access deleted object (line 3127)
    }
    else
    {
	sv = default;
    }
	return sv;
}
```

I fixed it by forcing the returned value of `GetString()` to be stored in a `String` instead of a `StringView`:
```c#
public void Print()
{
    String str = GetString();
    Console.WriteLine(str);
}
```

But this happens at random. Most of the time it works, but I get the error about 1/5 of the time.

**Comment by damianday** [comment]
Your GetString is not allocating a string, looks like your just storing a string literal which will then go out of reference.

Try in your GetString method,
`String str = new String("Hello, world!");`

**Comment by bfiete** [comment]
The program is fine as posted above and generates no errors for me. String literals are valid for the entire execution time of a program (no short-lived stack allocations are occurring there).

Not only do I not ever get the error you mentioned above, it seems impossible to me, given the code you posted. I think your actual error case must have been more complicated and you erroneously simplified it here...

**Comment by RogueMacro** [comment]
Actually it works now after I updated to 0.42.3
