### ISSUE TITLE
SDL onKeyUp/onKeyDown bug

### ISSUE THREAD

**Issue by zzador** [beefytech/Beef#210]
Hello everybody,

Just wanted to let you guys know that in the sourcefile "SDLApp.bf" down within the "public void Run()"-method there in the "switch (event.type)"-switch you write:

`case .KeyDown:
	KeyDown(event.key);
case .KeyUp:
	KeyDown(event.key);`

..while there is a KeyUp(...)-Method it never gets called.
I think that is a bug and the switch should be:

`case .KeyDown:
	KeyDown(event.key);
case .KeyUp:
	KeyUp(event.key);`

PS.: Using Beef 0.42.3

**Comment by bfiete** [comment]
Thanks @damianday - I was typing in the same thing at the same time. Checked in at https://github.com/beefytech/Beef/commit/f998ba4b4541fbd7acd1693a2bbead1a6eeb474e, will be in 0.42.4.
