### ISSUE TITLE
The SpaceGame demo has fatal error on linux

### ISSUE THREAD

**Issue by TheRawMeatball** [beefytech/Beef#217]
After #214 and #202 , I officially declare the SpaceGame demo my arch nemesis. This time, I was quite hopeful since the compiler didn't complain at all! But then, when I ran the game it spat out this message:
```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Unhandled error in result
**** FATAL APPLICATION ERROR ****
0x0x430487 main
0x0x7efe4dade0b3 __libc_start_main
```

I fixed the libpng warnigs with [this](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile), it was easy enough but the fatal application error remained. I have no idea where the problem is.

**Comment by TheRawMeatball** [comment]
Found the issue. It was a typo. I'll probably make a PR soon enough.

**Comment by Green-Sky** [comment]
Why did you close the issue?

**Comment by bfiete** [comment]
I didn't get a PR - @TheRawMeatball what was the typo?

**Comment by Green-Sky** [comment]
https://github.com/beefytech/Beef_website/pull/15 is the PR
the typo was bullet01.png -> Bullet01.png, typical windows to linux port error
