### ISSUE TITLE
[Feature Request] Find all reference

### ISSUE THREAD

**Issue by HydrogenC** [beefytech/Beef#219]
Is it possible to add a new menu item called "Find all references" just like Visual Studio? This will make checking all references after a breaking change easier.

**Comment by bfiete** [comment]
There already is one in the edit menu. I use it a lot. Alt-E A

**Comment by bfiete** [comment]
I'll add it to the right-click menu too

**Comment by bfiete** [comment]
Added in https://github.com/beefytech/Beef/commit/8f5b95b7affa4cac4faef099f10ac4f7ce132454, will be in 0.42.4.
