### ISSUE TITLE
Separate 'Start debbuging' and 'Continue' keybinds

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#221]
First new users cant find how to continue and second it will be nice to change continue keybind without changing start debugging keybind

**Comment by bfiete** [comment]
M, I see Visual Studio renames the menu command to "Continue" when a target is running. That seems reasonable.

**Comment by bfiete** [comment]
Added here
https://github.com/beefytech/Beef/commit/28e55fd5aa3bced2384878161ebc27a34cdce52f

**Comment by bfiete** [comment]
They are not separate keybinds as requested, however. But the menu item name changes while the target is running.
