### ISSUE TITLE
Can't type in installation path field

### ISSUE THREAD

**Issue by ITR13** [beefytech/Beef#223]
![image](https://user-images.githubusercontent.com/4341642/81089463-b2bf3680-8efc-11ea-86ce-e38f7df590c1.png)
To change the installation path I have to press the three dots then navigate to the correct folder, even though I just want to change C to D. It also doesn't open up into the folder of the path shown when pressing the three dots.

It would also be nice for it to append the folder it puts all the files by itself, so I don't have to create a folder to select it myself.

**Comment by bfiete** [comment]
Won't fix.
