### ISSUE TITLE
Some IDE Folder bugs

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#229]
1- Empty folders deleted in the file explorer while IDE is open aren't removed from the project list in the IDE
2- Folders created by right-clicking a project and selecting "New Folder" don't immediately exist in the file system. If you then create them in the file explorer, the IDE crashes.
3- Right-click Remove->Delete on a folder seems to always fail, even when the folder does exist in the file system.

(on Windows 10)

**Comment by MattThorson** [comment]
Here's the crash dump for the second bug!

[folder.txt](https://github.com/beefytech/Beef/files/4584475/folder.txt)

**Comment by bfiete** [comment]
Thanks. Fixed in https://github.com/beefytech/Beef/commit/0edc697e1484bf9bd92eeb9ed0a76dc7df71641b, will be in 0.42.4.
