### ISSUE TITLE
Installer crash

### ISSUE THREAD

**Issue by mikota** [beefytech/Beef#230]
FATAL ERROR
Unhandled error in result

Exception: Breakpoint (code 0x80000003) at address 7ff9'b01ea41b in thread 4204
Executable: D:\Downloads\BeefSetup_0_42_3.exe
File Version: 0.42.3
Product Version: 82ca79947062fc098422ceba72aef5f0710c3dc2

Logical Address: 0001:'0007941b

1'43afed60 7ff9'b01ea41b BeefInstallUI.dll Start+6FECB
    Params: 18e'04f83570 '0000000b '0000000b 7ff9'b020ab28

1'43afee10 7ff9'b01e74a7 BeefInstallUI.dll Start+6CF57
    Params: 7ff9'b027d578 1'43aff1a8 1'43aff120 1'43afee88

1'43afee40 7ff9'b01d276f BeefInstallUI.dll Start+5821F
    Params: 18e'02dfc890 1'8002b1be 1'43aff120 1'43aff1a8

1'43afeeb0 7ff9'b0171e2f 0001:'00000e2f BeefInstallUI.dll
    Params: 1'43aff100 18e'02e5e8c3 '00000003 '00000100

1'43afefb0 7ff9'b0171630 0001:'00000630 BeefInstallUI.dll
    Params: 18e'02e0e550 7ff6'2677d120 7ff6'267558e8 7ff6'2672f742

1'43aff000 7ff9'b017a5b2 BeefInstallUI.dll Start+62
    Params: '00000041 7ff9'b017a550 1'43aff1c0 7ff9'b0170000

1'43aff330 7ff6'26721a7f 0001:'00000a7f BeefSetup_0_42_3.exe
    Params: '0740d700 1'43aff3f8 '00000000 '00000000

1'43aff940 7ff6'267228ab 0001:'000018ab BeefSetup_0_42_3.exe
    Params: '00000001 '00000000 7ffa'0906a250 '00000000

1'43aff980 7ff6'2672295e 0001:'0000195e BeefSetup_0_42_3.exe
    Params: 18e'02e0aff0 7ff6'00000000 '00000001 7ffa'0906a250

1'43aff9c0 7ff6'26734db8 0001:'00013db8 BeefSetup_0_42_3.exe
    Params: '00000001 '00000000 7ffa'0906a250 '00000000

1'43affa00 7ff6'2673bf7e 0001:'0001af7e BeefSetup_0_42_3.exe
    Params: '00000000 '00000000 '00000000 '00000000

1'43affa30 7ffa'06a17974 KERNEL32.DLL BaseThreadInitThunk+14
    Params: '004e004c 18e'02da0100 '00000000 '00000000

1'43affab0 7ffa'0906a271 ntdll.dll RtlUserThreadStart+21
    Params: '00000000 '00000000 '00000000 '00000000

RAX:'00000000 RBX:1'43afedc0 RCX:'ffffffff RDX:7ff9'b02e5bd8 RSI:'0000000b RDI:7ff9'b02e5a38
R8:'00000000 R9:7ff9'b0170000 R10:7ff9'b02e5bd8 R11:18e'04f83000
R12:1'43aff1a8 R13:1'43aff120 R14:'0000000c R15:7ff9'b0282288
EIP:7ff9'b01ea41b ESP:1'43afed40 EBP:1'43afedf0
CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:'00000206

**Comment by bfiete** [comment]
Can you post your crashdump file?

**Comment by mikota** [comment]
Here you go. Had to change extension because of github.
[crash.txt](https://github.com/beefytech/Beef/files/4587800/crash.txt)

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef_website/commit/16bb3da9c5fbbea486be860b7099deb29d40c4f0, will be in release 0.42.4.
