### ISSUE TITLE
Inconsistencies with IDisposable causing LNK2001: unresolved external symbols

### ISSUE THREAD

**Issue by EnokViking** [beefytech/Beef#231]
```cs
public class SomeClass<T> : IDisposable
{

}

public class SomeOtherClass : SomeClass<int>
{

} //if this class doesn't explicitly implement IDisposable, the compiler throws LNK2001
```

i got rid of the errors either by implementing IDisposable explicitly for child classes, or by making sure there's an instance of the class somewhere

**Comment by EnokViking** [comment]
Additional info:
this only seem to happen if whatever class that implements SomeClass<T> also declares extern functions, e.g.

```cs
public class SomeOtherClass : SomeClass<int>
{
    [Import("some.dll"), CLink]
    static extern void funcToImplement();
}
```

because i can only reproduce this from classes that follow this same pattern of declaration

**Comment by bfiete** [comment]
I'm having trouble reproducing this. Can you post a full example that causes the issue?

**Comment by EnokViking** [comment]
I've had this happen intermittently for all classes that inherit from SFHandle<T> and also doesn't explicitly implement IDisposable. Sometimes it'll compile and then all of a sudden it'll refuse, spitting LNK2001 until i tack on IDisposable, then it goes away and compiles just fine.

Like, i can remove IDisposable from VertexArray right now and compile just fine, but then it'll come back in a while (for whatever reason) and I'll have to tack it on again for it to compile.

```cs
public class VertexArray : SFHandle<VertexArrayHandle>, IDisposable
	{
		public this() : base(sfVertexArray_create()) {}
		public this(VertexArray fromArray) : base(sfVertexArray_copy(fromArray.[Friend]_handle)) {}
		public ~this() { sfVertexArray_destroy(_handle); }

		public void Resize(uint32 vertexCount) => sfVertexArray_resize(_handle, vertexCount);
		public void Clear() => sfVertexArray_clear(_handle);
		public void AppendVertex(Vertex vertex) => sfVertexArray_append(_handle, vertex);

		public Vertex* GetVertex(uint32 index) => sfVertexArray_getVertex(_handle, index);
		public uint32 VertexCount => sfVertexArray_getVertexCount(_handle);

		public FloatRect Bounds => sfVertexArray_getBounds(_handle);
		public PrimitiveType PrimitiveType
		{
			get { return sfVertexArray_getPrimitiveType(_handle); }
			set { sfVertexArray_setPrimitiveType(_handle, value); }
		}

		[Import(CSFML_GRAPHICS), CLink]
		static extern VertexArrayHandle sfVertexArray_create();
                
                ///Bunch of other imports...
	}
```

```cs
	public abstract class SFHandle<T> : IDisposable
	{
		protected T _handle;
		public this() {}
		public this(T handle) { _handle = handle; }
		public ~this() { _handle = default; }

		public virtual void Dispose() { delete this; }
	}
```

**Comment by bfiete** [comment]
Any way you could post some compilable code and some reproducible instructions to generate this error?

I see there's something real here but I'm just not able to trigger this from the current bug description.

**Comment by EnokViking** [comment]
It seems to consistently fail when compiling in release mode (i've had it happen in debug too though)
https://imgur.com/a/XEnoONd - webm shows the build fail and makeshift fix i have to do to get it to compile

i'll see if i can reproduce it outside of the project

**Comment by bfiete** [comment]
Can you just zip up that project and post it here? Or email to beef@beefytech.com if you don't want to put it here.

**Comment by EnokViking** [comment]
[BeefSFMLProj.zip](https://github.com/beefytech/Beef/files/4602286/BeefSFMLProj.zip)
Sure, np

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/2e8306214338b0c8740d055d345258e68a3bd887, will be in 0.42.4.
