### ISSUE TITLE
Broken function found (Win32 only)

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#232]
While linking to the raylib bindings in win32 it is reporting that a broken function was found, if I compile with win64 there is no problem. This is with latest git and the latest release, I've attached the example project with the bindings.

[RayLib.zip](https://github.com/beefytech/Beef/files/4587513/RayLib.zip)

**Comment by bfiete** [comment]
This was related to some recent calling convention changes.

Fixed in https://github.com/beefytech/Beef/commit/bd7a4b392f507fe793e8112952b7d799160cd1c4, will be in 0.42.4.

**Comment by damianday** [comment]
Thanks
