### ISSUE TITLE
Windows: Wrong path formatting for $(BuildDir) and $(TargetDir)

### ISSUE THREAD

**Issue by Jonathan-Racaud** [beefytech/Beef#233]
Hello,

For one of my project I need to copy a file from a folder to the build directory so that it is alongside the binary.

I'm using the `Execute(String cmd)` command to perform that action.
I tested with those two different commands:
`copy $(ProjectDir)\\folder\\myfile $(TargetDir)\\myfile`
`copy $(ProjectDir)\\folder\\myfile $(BuildDir)\\myfile`

This is then executed as (testing building in debug mode for Win64): `cmd.exe /c copy C:\Path\To\ProjectName\folder\myfile C:\Path\To\ProjectName/build/Debug_Win64/ProjectName\myfile`

The issue is because in the path generated by $(BuildDir) and $(TargetDir) includes '/' instead of '\\' and cmd.exe doesn't understand '/' for paths so the command fails with the error: `The syntax of the command is incorrect`. 

The solutions could be to either (or both):
- Change the way the path is generated to use '\\' on Windows.
- Use Powershell instead of cmd.exe. The syntax would be: `powershell.exe -Command "the command to execute"`.
  - Powershell can mix '/' and '\\' inside a path and the copy worked.

I'm on Windows 10, 64 bits.

Sincerely,
Jonathan Racaud

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/421a3246663e3853ff1039f337836d213318296f, will be in release 0.42.4.
