### ISSUE TITLE
Request: A way through reflection to enumerate all of the Types in the project

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#235]
Or all the types with a [Reflect] attribute. Apologies if this already exists, but from the docs I don't see it. In C# you would get the Assembly and then enumerate all of the Types from there.

**Comment by bfiete** [comment]
This is new (evolving) functionality on the trunk. 
```
for (let typeId < Type.TypeIdEnd)
{
	let type = Type.[Friend]GetType(typeId);
}
```

You do have to null-check so it's not very ergonomic, but I'll wrap an enumerator that soon so you can just do something like `for (let type in Type.GetTypes())`.

**Comment by bfiete** [comment]
Note that you'll get types that do not have [Reflect], but those types will contain minimal reflection info - type name, flags, size, etc. but no fields, properties, or methods.

**Comment by bfiete** [comment]
A note here: in 0.42.4 there's an enumerator property called `Type.Types` that will enumerate through all used types.
