### ISSUE TITLE
abstract and virtual properties are not included in subclass's override autocomplete

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#237]
Example: When you type override in ClassB below, autocomplete will only offer ToString() as an option.

```
public abstract class ClassA
{
    public abstract bool PropertyA { get; }
    public virtual bool PropertyB { get { return false; } }
}

public class ClassB : ClassA
{
    
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/a17f8961b0ad508367d95104595f38653dd32d0f, will be in 0.42.4.

**Comment by MattThorson** [comment]
Confirmed fixed
