### ISSUE TITLE
Link Error when calling GetType() on a function pointer

### ISSUE THREAD

**Issue by animehunter** [beefytech/Beef#238]
function void Func(String[] args);

        static void Main(String[] args)
        {
			Func f = => Main;
			f.GetType();
        }

HelloWorld__.lib(HelloWorld_Program.obj) : error LNK2001: unresolved external symbol "public: static int bf::HelloWorld::Program::Func::sBfTypeData" (?sBfTypeData@Func@Program@HelloWorld@bf@@2HA)

**Comment by bfiete** [comment]
This was already fixed here https://github.com/beefytech/Beef/commit/61d9edea832dad4d9a142b5c6fc6c746f8f01fb7, will be in 0.42.4.

**Comment by animehunter** [comment]
Thanks
