### ISSUE TITLE
Hello World/IDE Crashes with Test -> Run -> Normal Test

### ISSUE THREAD

**Issue by hsauro** [beefytech/Beef#24]
I downloaded release 0.42, installed the binaries on windows 10. Started the IDE and picked the Hello World example which loaded into the IDE window. I selected build F7, and build was successful.  Ctrl F5 to run, worked great. However playing around I noticed that if I selected Test -> Run -> Normal Tests the IDE crashed with the following dump:

Crash minidump saved as C:\Program Files\BeefLang\bin\CrashDumps\BeefIDE_20200113_200332.dmp

Exception: Access Violation (code 0xc0000005) at address 7ff7'b9741e38 in thread 40FC
Executable: C:\Program Files\BeefLang\bin\BeefIDE.exe
File Version: 0.42
Product Version: c2ee40181288ee486b179098e62da3494b49ee65

Logical Address: 0001:'001d0e38

c2'809fefb0 7ff7'b9741e38 0001:'001d0e38 BeefIDE.exe
    Params: '00000000 7ff7'b977d0b4 28c'e01a3850 576e9952'4d52a49e

c2'809feff0 7ff7'b9741f67 0001:'001d0f67 BeefIDE.exe
    Params: 28c'cdee0000 7ffd'd2b0922b '00000040 '00000004

c2'809ff960 7ff7'b9619bbc 0001:'000a8bbc BeefIDE.exe
    Params: '00000000 '00000000 '00000000 '00000002

c2'809ff9a0 7ff7'b9767410 0001:'001f6410 BeefIDE.exe
    Params: '00000000 '00000000 '00000000 '0000060c

c2'809ff9d0 7ffd'94783dcd Beef042RT64.dll unsigned long bf::System::Threading::Thread::GetProcessDefaultStackSize(void)+9D
    Params: 28c'df687ef0 '00000000 '00000000 '00000000

c2'809ffa00 7ffd'd0c84034 KERNEL32.DLL BaseThreadInitThunk+14
    Params: '00000000 '00000000 '00000000 '00000000

c2'809ffa50 7ffd'd2b63691 ntdll.dll RtlUserThreadStart+21
    Params: '00000000 '00000000 '00000000 '00000000

RAX:4c'00000012 RBX:'00000000 RCX:4c'00000012 RDX:'00000000 RSI:28c'de715ca8 RDI:4c'00000012
R8:28c'de715ca8 R9:7ff7'b95701ff R10:'00000100 R11:28c'e01a3860
R12:'00000000 R13:7ff7'b9786758 R14:c2'809fefe8 R15:'0000000a
EIP:7ff7'b9741e38 ESP:c2'809fef50 EBP:'00000000
CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:'00010246

**Comment by bfiete** [comment]
The is issue occurs when there are no tests defined. This fix is in https://github.com/beefytech/Beef/commit/8970ebcd93f252293bf0ac5b56847b3e77848491 and will be in release 0.42.2.
