### ISSUE TITLE
Runtime.Assert does not use error message

### ISSUE THREAD

**Issue by Jonathan-Racaud** [beefytech/Beef#240]
Hi,

When trying to use [Runtime class](https://github.com/beefytech/Beef/blob/master/BeefLibs/corlib/src/Runtime.bf#L323) and its Assert(bool condition, String error) method, the error parameter is not used and instead the message "Assert failed" is hard coded.

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/36b6d63dbb6bfc269741dc8dcc4e3440eb6ab8f5, will be in 0.42.4.
