### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#241]
Happens when I try to use PorkStack inside Pork (files are the same name). It works when using List instead of PorkStack. And just figured out that List with RemoveAtFast is propably better than my PorkStack so excuse my bad code in there lol.
[pork.zip](https://github.com/beefytech/Beef/files/4604240/pork.zip)

**Comment by bfiete** [comment]
The backend choked on attempting to dereference a null constant.

```
public T Pop() 
{
	T item = items[--size];
	items[size] = *(T*) null;
	return item;
}
```

Fixed at https://github.com/beefytech/Beef/commit/5de6373b993ca6b14f35bfe600326e3591284f38, will be in 0.42.4.

And yes, I do believe the OP knows `default` would be correct expression here... though actually in a stack there's no reason to "erase" the memory previously occupied by that popped member, anyway (See `List<T>.PopBack`).

**Comment by MineGame159** [comment]
Oh, I didnt know that theres PopBack and yeah, that dereference to null was just me testing things.
