### ISSUE TITLE
Structs behave weirdly inside List

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#242]
Version: 0.42.3

So I have a list of structs, I create the list normally, add 4 items inside it but then I take item from the list at index 1 (can be any item) and add that same struct to the list again. The original struct at index 1 remains unchanged but the copy of it at the end of the list is messed up. It only happens when the list needs to reallocate the internal array so thats why in my example it happens at 5th item and it doesnt happen with every struct. I tried to narrow the problem down so here is the code:
```csharp
enum FooType {
	None,
	Bool,
	Number,
	String
}

struct FooData {
	public bool boolean;
	public double number;
	public String string;

	public this() {
		boolean = false;
		number = 0;
		string = null;
	}

	public this(double number) {
		boolean = false;
		this.number = number;
		string = null;
	}
}

struct Foo {
	public FooType type;
	public FooData data;

	public this(FooType type, FooData data) {
		this.type = type;
		this.data = data;
	}
}

class Program {
	private static void Main() {
		List<Foo> idk = scope .;
		idk.Add(Foo(.Number, .(5)));
		idk.Add(Foo(.Number, .(9)));
		idk.Add(Foo(.None, .()));
		idk.Add(Foo(.Number, .(16)));
		idk.Add(idk[1]); // When debugging this Add function the Foo parameter gets messed up after EnsureCapacity is called
	}
}
```

**Comment by bfiete** [comment]
Good bug. As an aside- not sure if this is from real code you're writing or not, but you should consider enums if it is.
```
enum Foo
{
	case None;
	case Bool(bool val);
	case Number(double val);
	case String(String val);
}
```

**Comment by MineGame159** [comment]
;) Its stripped down version of my code (the FooData struct has Union attribute but figured it doesnt play a role in this bug) and when I first started with it I thought of using enums but I totally forgot that each enum value can have different values even tho I was using Result lol, nwm thanks for that im gonna change my code

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/a30ad3d9d2718260d40572e13ff862cba00e867e.

The issue was that the index operator returns a ref, and Add gets passed that ref (immutably), but the list resizing was destroying the old list data (which the added item referenced) before the inserted item was copied in.
