### ISSUE TITLE
Beef IDE 0.42.3 Crash

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#246]
This is really simple to reproduce, just type `DeleteAndClearItems!<`

    Crash minidump saved as C:\Users\Igor\AppData\Local\BeefLang\bin\CrashDumps\BeefIDE_20200511_174756.dmp

    Exception: Access Violation (code 0xc0000005) at address 189'7a07e6c4 in thread 1208
    Executable: C:\Users\Igor\AppData\Local\BeefLang\bin\BeefIDE.exe
    File Version: 0.42.3
    Product Version: 82ca79947062fc098422ceba72aef5f0710c3dc2

    Logical Address: 0001:'0010d6c4

    6c'8b89ce10 189'7a07e6c4 IDEHelper64.dll BfCodeGen_GenerateObj+2FF14
        Params: 6c'8b89def0 6c'8b89cf30 189'05321958 189'08854dd0

    6c'8b89d3f0 189'7a07f9d5 IDEHelper64.dll BfCodeGen_GenerateObj+31225
        Params: '00000013 6c'8b89d500 6c'8b89d468 189'0c2d3301

    6c'8b89d9b0 189'7a083a56 IDEHelper64.dll BfCodeGen_GenerateObj+352A6
        Params: 6c'8b89da00 189'7a05f200 189'05319680 6c'8b89da40

    6c'8b89dcb0 189'7a084453 IDEHelper64.dll BfCodeGen_GenerateObj+35CA3
        Params: ffffffff'ffffff00 189'05319680 189'053196e8 189'02a47ce8

    6c'8b89dce0 189'7a08f0fd IDEHelper64.dll BfCodeGen_GenerateObj+4094D
        Params: 6c'8b89def0 189'05319680 189'05319658 '00000000

    6c'8b89dd30 189'7a08f044 IDEHelper64.dll BfCodeGen_GenerateObj+40894
        Params: 6c'8b89def0 6c'8b89e260 ffffffff'fffffffe ffffffff'fffffffe

    6c'8b89ddb0 189'7a05c3bd IDEHelper64.dll BfCodeGen_GenerateObj+DC0D
        Params: '00000014 6c'8b89dec0 6c'8b89e260 189'7bbcdf38

    6c'8b89e0c0 189'7a088e54 IDEHelper64.dll BfCodeGen_GenerateObj+3A6A4
        Params: '00000000 189'05319628 '00000000 6c'8b89e260

    6c'8b89e190 189'7a0893e0 IDEHelper64.dll BfCodeGen_GenerateObj+3AC30
        Params: 6c'8b89e260 '00000000 '00000000 6c'8b89e260

    6c'8b89e210 189'7a05c3bd IDEHelper64.dll BfCodeGen_GenerateObj+DC0D
        Params: 189'0283fee0 6c'8b89e500 '00000000 189'7bbe1058

    6c'8b89e3f0 189'7a1d10b1 IDEHelper64.dll Breakpoint_GetPendingHotBindIdx+18B61
        Params: 6c'8b89eb60 101'fffffde8 6c'8b89e500 189'7bbe1058

    6c'8b89e590 189'7a1cfb47 IDEHelper64.dll Breakpoint_GetPendingHotBindIdx+175F7
        Params: 6c'8b89e600 189'05321701 '00000000 6c'0aaa3e00

    6c'8b89f130 189'7a143794 IDEHelper64.dll BfpFindFileData_GetTime_LastWrite+A66B4
        Params: fffffe05'00000000 101'fffffdee 'ffffff00 189'0283fe00

    6c'8b89f410 189'7a19edde IDEHelper64.dll BfParser_SetCompleteParse+3E9BE
        Params: 189'02822110 189'0a340428 189'0868b900 189'02a47ce8

    6c'8b89f4c0 189'7a1acfdb IDEHelper64.dll BfCompiler_ClassifySource+1FB
        Params: 189'02a47ce8 189'0cb71403 189'0c360750 189'029ff890

    6c'8b89f4f0 7ff7'f0587042 0001:'00056042 BeefIDE.exe
        Params: 6c'8b89f5d0 7ff7'f067852e 189'0cb71403 189'0c360750

    6c'8b89f6b0 7ff7'f06785cd 0001:'001475cd BeefIDE.exe
        Params: '00000000 7ffb'f047c2c7 189'0a863cd0 'ffffffff

    6c'8b89f720 7ff7'f05ecf07 0001:'000bbf07 BeefIDE.exe
        Params: 189'0a870210 6c'8b89f778 189'0a863cd0 6c'8b89f778

    6c'8b89f810 7ff7'f07584cf 0001:'002274cf BeefIDE.exe
        Params: '00000000 '00000000 '00000000 '00000002

    6c'8b89f850 7ff7'f0758750 0001:'00227750 BeefIDE.exe
        Params: '00000000 '00000000 '00000000 '00000740

    6c'8b89f880 7ffb'd39d3d7d Beef042RT64.dll unsigned long bf::System::Threading::Thread::GetProcessDefaultStackSize(void)+9D
        Params: 189'02907590 '00000000 '00000000 '00000000

    6c'8b89f8b0 7ffb'f2697bd4 KERNEL32.DLL BaseThreadInitThunk+14
        Params: '00000000 '00000000 '00000000 '00000000

    6c'8b89f930 7ffb'f350ce51 ntdll.dll RtlUserThreadStart+21
        Params: '00000000 '00000000 '00000000 '00000000

    RAX:'00000000 RBX:'00000000 RCX:189'053196d0 RDX:'00000000 RSI:6c'8b89d0d0 RDI:'00000000
    R8:'00000001 R9:189'05319680 R10:'00000000 R11:'00000000
    R12:6c'8b89cf30 R13:189'05321958 R14:189'0868eed0 R15:189'08854dd0
    EIP:189'7a07e6c4 ESP:6c'8b89ccf0 EBP:6c'8b89cdc9
    CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
    Flags:'00010246

[crash_dump2.zip](https://github.com/beefytech/Beef/files/4611997/crash_dump2.zip)

**Comment by bfiete** [comment]
Thanks. This is already fixed on trunk. Will be in 0.42.4.
