### ISSUE TITLE
IDE crash when compiling

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#248]
So some part of the code I wrote is causing the compiler to crash. I will just post the crash long and dump for the time being. When I figure out what part of the code is causing it, I will post comment here.

```
Crash minidump saved as C:\Program Files\BeefLang\bin\CrashDumps\BeefIDE_20200512_095615.dmp
FATAL ERROR
Failure during codegen of ?Call@Pork@pork@bf@@AEAA_NAEAUValue@23@Tint@@@Z in pork_Pork: Unable to spill vreg

Exception: Breakpoint (code 0x80000003) at address '0085CBB2 in thread 178C
Executable: C:\Program Files\BeefLang\bin\BeefIDE.exe
File Version: 0.42.3
Product Version: 82ca79947062fc098422ceba72aef5f0710c3dc2

Logical Address: 0001:'002DBBB2

'09BEC640 '0085CBB2 IDEHelper64.dll BfpOutput_DebugString+4272
    Params: '09BEC670 FFFFFFFF'FFFFFFFF '021885E0 '100317B0

'09BEC6D0 '00852552 IDEHelper64.dll BfpSystem_FatalError+62
    Params: '09BEE028 '021885B8 '0D595E10 '0FB5DDD0

'09BEC730 '0060AA6A IDEHelper64.dll BfpFindFileData_GetTime_Created+C12A
    Params: '09BEE028 '09BEE028 '09BEC840 FFFFFFFF'FFFFFFFF

'09BECB80 '0060A0AA IDEHelper64.dll BfpFindFileData_GetTime_Created+B76A
    Params: '0000001C '00000000 '00000010 '0D582AD8

'09BECBC0 '0061C177 IDEHelper64.dll BfpFindFileData_GetTime_Created+1D837
    Params: '00000000 '09BECCD0 '0000000E '00000000

'09BEDD80 '00631E3C IDEHelper64.dll BfpFindFileData_GetTime_Created+334FC
    Params: '1047F680 '100BD120 '104AD400 '0D754D00

'09BEE270 '005F0EDA IDEHelper64.dll BfSystem_Log+6DCA
    Params: '07A37520 '0FB5DD30 '0D6235A0 '10343CF0

'09BEE330 '005F1517 IDEHelper64.dll BfSystem_Log+7407
    Params: '0D6095D8 '0D6095D8 '0FD287F0 '103AE3F8

'09BEFA00 '0065BD5E IDEHelper64.dll CDep_Shutdown+1089E
    Params: '0FAF2630 '00000000 '00000000 '0FBE7BB0

'09BEFA30 '76C4556D kernel32.dll BaseThreadInitThunk+D
    Params: '00000000 '00000000 '00000000 '00000000

'09BEFA80 '76DA385D ntdll.dll RtlUserThreadStart+1D
    Params: '00000000 '00000000 '00000000 '00000000


RAX:'00000000 RBX:'09BEC6B8 RCX:'005167B0 RDX:4582'0203033F RSI:FFFFFFFF'FFFFFFFF RDI:'021885E0
R8:'0FE33FD0 R9:'09BEC840 R10:'00000000 R11:4581'01FA033E
R12:'0D582AD8 R13:'00000000 R14:'00000056 R15:'00000002
EIP:'0085CBB2 ESP:'09BEC620 EBP:'09BEC840
CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:'00000206
```

https://mega.nz/file/ElcD0QTI#g03NiEIiWAfO56p5xXtSrmXVozzQV4wyuGsybXL6_nk

**Comment by bfiete** [comment]
Well, we see what function was failing right there in the crash text:`bool pork.Pork.Call(pork.Value&, int)`. That's failing in the backend. Any chance you can share the code that causes this?

**Comment by MineGame159** [comment]
Here it is
```cs
PorkFunction func;
switch (callee.type) {
case .Function: func = callee.AsFunction();
case .Closure:  func = callee.AsClosure().func;
default:        return false;
}

if (func.IsPork()) {
if (argCount != func.AsPork().arity) {
	RuntimeError("Expected {} arguments but got {}.", func.AsPork().arity, argCount);
	return false;
}

frames.Add(new CallFrame(func, callee.IsClosure() ? &callee.AsClosureRef() : null, mStack.Count - argCount));
return true;		
} else if (func.IsNative()) {
let result = func.AsNative()(this, argCount);
Pop();
if (result case .Ok(let value)) Push(value);
else return false;
return true;
}

return false;
```
but I found out that when I remove one paticular field inside some class then it stops crashing, I can send the whole thing if needed.

**Comment by bfiete** [comment]
Yeah-send the whole thing, if you can.

**Comment by MineGame159** [comment]
[pork.zip](https://github.com/beefytech/Beef/files/4618039/pork.zip)
So when I comment out 'closed' field inside PorkUpvalue (same filename) it doesnt crash. For it to not give errors (when commented out that field) you need comment out one function's body inside Pork (same filename).

**Comment by bfiete** [comment]
One bug here is that data cycles in unions were not being detected properly.
ValueContainer.upvalue -> PorkUpvalue.closed -> Value.value -> ValueContainer -> ...

Still doesn't excuse the code generation issue...

**Comment by bfiete** [comment]
The actual bug was the same as this: https://github.com/beefytech/Beef/issues/253, fixed in https://github.com/beefytech/Beef/commit/d5a2db5a066148e06e2c30ef5897ee8002a730e7.

This code helped me find another issue with debug information with nested inlined methods called from the same source line, so thanks for that too (it was a silent failure).

Another note: this syntax is no longer supported `String str = scope .;`, which you do a lot. The parens are required now: `String str = scope .();`

**Comment by MineGame159** [comment]
Oh ok, im just amazed how quickly you fix those bugs, keep up the awesome work :1st_place_medal:
