### ISSUE TITLE
Unable to build IDEHelper

### ISSUE THREAD

**Issue by blabtonic** [beefytech/Beef#25]
While running the build.sh script I came across an error once it hits the IDEHelper build
the extern directory is not in the IDEHelper directory but in the root directory of the compiler(Beef-0.42.1)
Starting build.sh
-- Configuring done
-- Generating done
-- Build files have been written to: /home/developer/devprojects/Beef-0.42.1/jbuild_d
[  5%] Built target hunspell
[ 74%] Built target BeefySysLib
[ 92%] Built target IDEHelper
[ 93%] Built target BeefBoot
[100%] Built target BeefRT
-- Configuring done
-- Generating done
-- Build files have been written to: /home/developer/devprojects/Beef-0.42.1/jbuild
[ 75%] Built target hunspell
[ 75%] Built target BeefySysLib
[ 75%] Building CXX object IDEHelper/CMakeFiles/IDEHelper.dir/BfDiff.cpp.o
In file included from /home/developer/devprojects/Beef-0.42.1/IDEHelper/../extern/llvm-project_8_0_0/llvm/include/llvm/Support/AlignOf.h:17:0,
                 from /home/developer/devprojects/Beef-0.42.1/IDEHelper/../extern/llvm-project_8_0_0/llvm/include/llvm/ADT/SmallVector.h:18,
                 from /home/developer/devprojects/Beef-0.42.1/IDEHelper/Beef/BfCommon.h:18,
                 from /home/developer/devprojects/Beef-0.42.1/IDEHelper/BfDiff.cpp:11:
/home/developer/devprojects/Beef-0.42.1/IDEHelper/../extern/llvm-project_8_0_0/llvm/include/llvm/Support/Compiler.h:18:10: fatal error: llvm/Config/llvm-config.h: No such file or directory
 #include "llvm/Config/llvm-config.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
IDEHelper/CMakeFiles/IDEHelper.dir/build.make:62: recipe for target 'IDEHelper/CMakeFiles/IDEHelper.dir/BfDiff.cpp.o' failed
make[2]: *** [IDEHelper/CMakeFiles/IDEHelper.dir/BfDiff.cpp.o] Error 1
CMakeFiles/Makefile2:196: recipe for target 'IDEHelper/CMakeFiles/IDEHelper.dir/all' failed
make[1]: *** [IDEHelper/CMakeFiles/IDEHelper.dir/all] Error 2

**Comment by bfiete** [comment]
Are those the results of the first execution of build.sh? When first run it should retrieve and build LLVM. It appears that failed. The build script for that is in extern/llvm_build.sh.
