### ISSUE TITLE
Overriding virtual accessor results in "Unable to find indexer property" in child class

### ISSUE THREAD

**Issue by KillaMaaki** [beefytech/Beef#250]
Attempting to define a virtual accessor in a parent class, and then overriding that accessor in a child class, results in being unable to use that accessor on instances of the child class. Minimal repro example:

```
class Parent
{
	public virtual int this[int index]
	{
		get {
			return 0;
		}
	}
}

class Child : Parent
{
	public override int this[int index]
	{
		get {
			return 1;
		}
	}
}

Child c = new Child();
int value = c[0]; // doesn't compile, "Unable to find indexer property"
value = ((Parent)c)[0]; // works, returns 1 as expected
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/299918d64191facb381abf83c8f58ab694274331, will be in 0.42.4.
