### ISSUE TITLE
IDE crashes when compiling delegate returning non empty struct

### ISSUE THREAD

**Issue by qzole** [beefytech/Beef#253]
For quick reading, minimal example:
```csharp
namespace CrashTest
{
	struct MyStruct
	{
		public int value;
		public this(int v) { value = v; }
	}

	class Program
	{
		public static void Main()
		{
			MyStruct myStruct = .(5);
			MyStruct myStructGetter() { return myStruct; }
			delegate MyStruct() myTest = scope => myStructGetter; // CRASH
		}
	}
}
```
A more complete example is attached, with some examples what crashes and what doesn't: [beef-delegate-crash.zip](https://github.com/beefytech/Beef/files/4620362/beef-delegate-crash.zip)

No crashdump is created, the following error pops up when the crash happens:
![image](https://user-images.githubusercontent.com/8840889/81781978-66c25200-94f9-11ea-942b-745fa06af6bd.png)

If the debug IDE is run an assert happens earlier it seems:
![image](https://user-images.githubusercontent.com/8840889/81782017-780b5e80-94f9-11ea-9b86-b9a3161fe065.png)

**Comment by bfiete** [comment]
This is fixed at https://github.com/beefytech/Beef/commit/d5a2db5a066148e06e2c30ef5897ee8002a730e7, will be in 0.42.4.
