### ISSUE TITLE
Crash after renaming System.Collections.Generic

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#256]
Not really sure how this happened but after modifiying a few modules to remove the warnings for System.Collections this error popped up.

[crash.zip](https://github.com/beefytech/Beef/files/4629549/crash.zip)

**Comment by bfiete** [comment]
I can't use this crash dump unless you post your IDEHelper64.dll, IDEHelper64.pdb, BeefIDE.exe, and BeefIDE.pdb...

**Comment by bfiete** [comment]
Hm- maybe I should add some functionality to submit built modules and debug information to a symbol server in these cases. Also we could just submit the crash dump and just provide a link someone can just post instead of having to attach the dump themselves.

**Comment by damianday** [comment]
That would be helpful, I'd already rebuilt the IDE since having that crash
as well :/
