### ISSUE TITLE
Crash adding parenthesis to member

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#257]
Compiler flagged the String up as an error, added the parenthesis and the IDE crashed.

```
public static class Global
{
        public static String g_UserID = new String ~ delete _; 
}
```

[crash.zip](https://github.com/beefytech/Beef/files/4629701/crash.zip)

**Comment by damianday** [comment]
I will see if i can reproduce these, because they were all on my own git build and I think its valid code for the last public release :/

**Comment by bfiete** [comment]
Hm- is this reproducible for you on trunk? I can't repro this. If you can repro it, could you post a crash dump along with your IDEHelper64.pdb?

**Comment by damianday** [comment]
I can't reproduce this anymore :/ and I've since rebuilt beef, if it does come up again i'll reopen and post with the necessary files.
