### ISSUE TITLE
Compile-time reflection

### ISSUE THREAD

**Issue by Domain** [beefytech/Beef#26]
I hope Beef can have compile-time reflection like d language.

**Comment by rumbu13** [comment]
Do you have any use case not covered by generics? I really don't like how D pollutes function definitions with ugly long constraints making them difficult to understand and not code completion friendly.

**Comment by Domain** [comment]
> Do you have any use case not covered by generics? I really don't like how D pollutes function definitions with ugly long constraints making them difficult to understand and not code completion friendly.

Something like getMember, FieldNameTuple ...
These can be done in runtime reflection, but less efficient.

**Comment by bfiete** [comment]
We have this now.
