### ISSUE TITLE
Installer access violation

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [beefytech/Beef#260]
Windows 10 x64
[log.txt](https://github.com/beefytech/Beef/files/4631320/log.txt)

**Comment by IlyaStuurFedorov** [comment]
Dump: 
[cd.zip](https://github.com/beefytech/Beef/files/4631325/cd.zip)

**Comment by bfiete** [comment]
Do you have any more information about the circumstances around this crash? It appears to be related to the eula somehow but doesn't make a lot of sense on its own.

**Comment by IlyaStuurFedorov** [comment]
All that happened is that after launching the installer, I hear a sound of it "popping out", but instead of a launcher popping out, it outputs the stacktrace that I provided. I did not do anything to the installer, and I don't really know how could EUAL be related to this problem either.

**Comment by bfiete** [comment]
Did this just happen one time and then it worked after that?

**Comment by IlyaStuurFedorov** [comment]
It keeps happening every time I open installer up.
