### ISSUE TITLE
Crash after closing application in debug mode

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#261]
Exception: Access Violation (code 0xc0000005) at address 23b'647fd0b6 in thread FF0
Executable: C:\beef\IDE\dist\BeefIDE.exe
File Version: 0.42.4
Product Version: 0000000000000000

Logical Address: 0001:'0031c0b6

b9'604fcd10 23b'647fd0b6 IDEHelper64.dll BeefyDbg32::DbgType::GetByteCount+6
    at c:\beef\idehelper\dbgmodule.cpp:1957
    Params: b9'604fd018 ffffffff'ffffffff '00000008 23b'7db40950

b9'604fcd50 23b'647f887a IDEHelper64.dll <lambda_346d3b131c11e2790bdd9b612a4bcfc6>::operator()+7A
    at c:\beef\idehelper\debugtarget.cpp:2239
    Params: 23b'7d3e7c20 '00000000 '00000008 7ff7'00000002

b9'604fcf40 23b'647f8523 IDEHelper64.dll BeefyDbg32::DebugTarget::GetValueByNameInBlock_Helper+4C3
    at c:\beef\idehelper\debugtarget.cpp:2331
    Params: 23b'7e9efac0 23b'7e9efa60 23b'7e9efa98 6d097365'74794264

b9'604fcfb0 23b'647f8ad6 IDEHelper64.dll BeefyDbg32::DebugTarget::GetValueByNameInBlock+136
    at c:\beef\idehelper\debugtarget.cpp:2415
    Params: 23b'7db40950 23b'7e9efa60 23b'7db40950 b9'604fd120

b9'604fd070 23b'647f478c IDEHelper64.dll BeefyDbg32::DebugTarget::GetValueByName+10C
    at c:\beef\idehelper\debugtarget.cpp:446
    Params: b9'604fdcd0 23b'64327318 30293635'38335f54 41444645'38303778

b9'604fd840 23b'648170db IDEHelper64.dll BeefyDbg32::DbgExprEvaluator::LookupIdentifier+152B
    at c:\beef\idehelper\dbgexprevaluator.cpp:3688
    Params: 23b'787dba04 b9'604fd888 23b'71ef00a0 b9'604fdbf0

b9'604fd8b0 23b'6481a9b9 IDEHelper64.dll BeefyDbg32::DbgExprEvaluator::Visit+39
    at c:\beef\idehelper\dbgexprevaluator.cpp:4781
    Params: b9'604fdca0 b9'604fdad0 b9'604fdbf0 23b'77d2e280

b9'604fd9d0 23b'64823998 IDEHelper64.dll BeefyDbg32::DbgExprEvaluator::Resolve+C8
    at c:\beef\idehelper\dbgexprevaluator.cpp:7944
    Params: 23b'7d3e7c20 b9'604fdae0 23b'7d3f7160 38303778'30293635

b9'604fde90 23b'647df7e1 IDEHelper64.dll BeefyDbg32::WinDebugger::EvaluateContinue+3D1
    at c:\beef\idehelper\windebugger.cpp:8979
    Params: 23b'643c0760 '00000000 23b'7dde27a0 b9'604fdfa0

b9'604fe290 23b'647e2911 IDEHelper64.dll BeefyDbg32::WinDebugger::Evaluate+1A21
    at c:\beef\idehelper\windebugger.cpp:9493
    Params: 23b'643c0760 b9'604fe4e0 b9'604fe4d0 b9'604fe3a8

b9'604fe480 23b'647e2cdc IDEHelper64.dll BeefyDbg32::WinDebugger::Evaluate+10C
    at c:\beef\idehelper\windebugger.cpp:9514
    Params: 23b'6438f520 23b'6438f520 b9'604fe5e8 '00000000

b9'604fe510 23b'647665f5 IDEHelper64.dll Debugger_Evaluate+105
    at c:\beef\idehelper\debugmanager.cpp:1231
    Params: '00000000 'ffffffff b9'604fe5e8 ffffffff'ffffffff

b9'604fe570 7ff7'21bb0426 BeefIDE.exe IDE.Debugger.DebugManager.Evaluate+56
    at c:\Beef\IDE\src\Debugger\DebugManager.bf:764
    Params: 448e4000'43c60000 10000b9'604fe6e0 1'0000002a ffffffff'0000002e

b9'604fe6b0 7ff7'21be1f8c BeefIDE.exe IDE.IDEApp.DebugEvaluate+2EC
    at c:\Beef\IDE\src\IDEApp.bf:10968
    Params: 23b'64378e50 b9'604fe720 23b'683059d0 7ff7'21cba26d

b9'604fee30 7ff7'21cba356 BeefIDE.exe IDE.ui.WatchPanel.IDE.ui.IWatchOwner.UpdateWatch+256
    at c:\Beef\IDE\src\ui\WatchPanel.bf:2217
    Params: 23b'6cb43600 23b'683059d0 23b'6cc06930 23b'6cbeb7b0

b9'604fee90 7ff7'21cb5a0a BeefIDE.exe IDE.ui.WatchListViewItem.DrawAll+BA
    at c:\Beef\IDE\src\ui\WatchPanel.bf:1134
    Params: 448cc000'40000000 433f0000'449d4000 '00000000 '00000000

b9'604feef0 7ff7'21b669b7 BeefIDE.exe Beefy.theme.dark.DarkListViewItem.DrawChildren+77
    at c:\Beef\BeefLibs\Beefy2D\src\theme\dark\DarkListView.bf:546
    Params: '00000000 '00000000 '00000000 '00000000

b9'604fef70 7ff7'21b66d15 BeefIDE.exe Beefy.theme.dark.DarkListViewItem.DrawAll+135
    at c:\Beef\BeefLibs\Beefy2D\src\theme\dark\DarkListView.bf:597
    Params: 23b'6cbfc3d0 7ff7'21b64c98 23b'6cc1d270 1'80002c95

b9'604ff020 7ff7'21b93c07 BeefIDE.exe Beefy.widgets.Widget.DrawAll+157
    at c:\Beef\BeefLibs\Beefy2D\src\widgets\Widget.bf:441
    Params: '00000000 '00000000 '00000000 '00000000

b9'604ff0d0 7ff7'21b93c07 BeefIDE.exe Beefy.widgets.Widget.DrawAll+157
    at c:\Beef\BeefLibs\Beefy2D\src\widgets\Widget.bf:441
    Params: 23b'78652c40 '00000000 '00000000 23b'6cc36220

b9'604ff180 7ff7'21b93c07 BeefIDE.exe Beefy.widgets.Widget.DrawAll+157
    at c:\Beef\BeefLibs\Beefy2D\src\widgets\Widget.bf:441
    Params: 23b'6cc36220 7ff7'21b5b561 '00000003 23b'6ce8c260

b9'604ff1c0 7ff7'21cb8a35 BeefIDE.exe IDE.ui.WatchPanel.DrawAll+45
    at c:\Beef\IDE\src\ui\WatchPanel.bf:1877
    Params: '00000002 23b'6cb011f0 23b'6cc06930 7ff7'21b5b99a

b9'604ff270 7ff7'21b93c07 BeefIDE.exe Beefy.widgets.Widget.DrawAll+157
    at c:\Beef\BeefLibs\Beefy2D\src\widgets\Widget.bf:441
    Params: b9'604ff330 7ff7'21b5bf7a 23b'6cbfc7d0 7ff7'21b5bba5

b9'604ff320 7ff7'21b93c07 BeefIDE.exe Beefy.widgets.Widget.DrawAll+157
    at c:\Beef\BeefLibs\Beefy2D\src\widgets\Widget.bf:441
    Params: '45200000 44a72000'00000000 '00000000 23b'6cc360e0

b9'604ff360 7ff7'21b7fd11 BeefIDE.exe Beefy.widgets.DockingFrame.DrawAll+11
    at c:\Beef\BeefLibs\Beefy2D\src\widgets\DockingFrame.bf:979
    Params: b9'604ff470 7ff7'21b5b561 23b'44a72000 23b'6cc06930

b9'604ff3a0 7ff7'21b60392 BeefIDE.exe Beefy.theme.dark.DarkDockingFrame.DrawAll+12
    at c:\Beef\BeefLibs\Beefy2D\src\theme\dark\DarkDockingFrame.bf:66
    Params: b9'604ff400 23b'6cc35320 '00000000 '00000000

b9'604ff450 7ff7'21b93c07 BeefIDE.exe Beefy.widgets.Widget.DrawAll+157
    at c:\Beef\BeefLibs\Beefy2D\src\widgets\Widget.bf:441
    Params: b9'604ff4a8 7ff7'21bb6c97 7ff7'21beaa00 7ff7'21bcb335

b9'604ff490 7ff7'21b7fd11 BeefIDE.exe Beefy.widgets.DockingFrame.DrawAll+11
    at c:\Beef\BeefLibs\Beefy2D\src\widgets\DockingFrame.bf:979
    Params: 23b'6840eef0 7ff7'21b5b561 '00000000 23b'643adcc0

b9'604ff4d0 7ff7'21b60392 BeefIDE.exe Beefy.theme.dark.DarkDockingFrame.DrawAll+12
    at c:\Beef\BeefLibs\Beefy2D\src\theme\dark\DarkDockingFrame.bf:66
    Params: '00000000 1'80008c08 23b'6cbf9290 7ff7'21b59355

b9'604ff580 7ff7'21b93c07 BeefIDE.exe Beefy.widgets.Widget.DrawAll+157
    at c:\Beef\BeefLibs\Beefy2D\src\widgets\Widget.bf:441
    Params: '00000000 b9'604ff648 7ff7'21efa288 7ff7'21efa2a0

b9'604ff610 7ff7'21b52e87 BeefIDE.exe Beefy.BFApp.Draw+E7
    at c:\Beef\BeefLibs\Beefy2D\src\BFApp.bf:733
    Params: b9'604ff648 23b'643907d0 '00000000 b9'604ff648

b9'604ff660 7ff7'21be8c5d BeefIDE.exe IDE.IDEApp.Draw+5D
    at c:\Beef\IDE\src\IDEApp.bf:12718
    Params: ce'4dd2ba02 '80000012 '00000001 23b'6432d7c0

b9'604ff690 1'8002f05c BeefySysLib64.dll Beefy::WinBFApp::Draw+2C
    at c:\beef\beefysyslib\platform\win\winbfapp.cpp:1150
    Params: '00000006 '00000007 23b'667b2770 7ffe'97ae31c7

b9'604ff6c0 1'80001b52 BeefySysLib64.dll Beefy::BFApp::Process+222
    at c:\beef\beefysyslib\bfapp.cpp:227
    Params: 23b'6cb0e420 b9'604ff740 23b'6cb0e420 7ffe'95569820

b9'604ff760 1'8002e286 BeefySysLib64.dll Beefy::WinBFWindow::WindowProc+806
    at c:\beef\beefysyslib\platform\win\winbfapp.cpp:966
    Params: '00000000 '00100544 '00000113 '00000000

b9'604ff7a0 1'8002eb1a BeefySysLib64.dll Beefy::WinBFWindow::WindowProcStub+4A
    at c:\beef\beefysyslib\platform\win\winbfapp.cpp:1027
    Params: '00000001 '00000000 '00000000 '00000000

b9'604ff930 7ffe'97ae5c0d USER32.dll CallWindowProcW+3BD
    Params: 23b'667b2770 1'8002ead0 '00100544 b9'604ff9f0

b9'604ff9b0 7ffe'97ae5602 USER32.dll DispatchMessageW+1F2
    Params: 1'8002ead0 23b'6432d7c0 23b'643907d0 100023b'643a71d0

b9'604ffa20 1'8002efe6 BeefySysLib64.dll Beefy::WinBFApp::Run+46
    at c:\beef\beefysyslib\platform\win\winbfapp.cpp:1139
    Params: '00000001 '00000000 '00000000 '00000000

b9'604ffa60 7ff7'21beef8e BeefIDE.exe IDE.Program.Main+4E
    at c:\Beef\IDE\src\Program.bf:32
    Params: 23b'6432a190 7ff7'00000022 23b'643137ad 23b'6437208d

b9'604ffaa0 7ff7'21d94126 BeefIDE.exe WinMain+156
    Params: '00000001 '00000000 '00000000 '00000000

b9'604ffae0 7ff7'21d943ae BeefIDE.exe __scrt_common_main_seh+106
    at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    Params: '00000000 '00000000 '00000000 '00000000

b9'604ffb10 7ffe'99857bd4 KERNEL32.DLL BaseThreadInitThunk+14
    Params: '00000000 '00000000 '00000000 '00000000

b9'604ffb90 7ffe'999ace51 ntdll.dll RtlUserThreadStart+21
    Params: '00000000 '00000000 '00000000 '00000000

RAX:b9'604fcf80 RBX:b9'604fcdb8 RCX:'00000000 RDX:23b'7e9efa60 RSI:'00000000 RDI:23b'7f02f3e0
R8:23b'7f02f914 R9:'0000114e R10:23b'7e9efa60 R11:'70869099
R12:23b'7db40950 R13:'00000008 R14:ffffffff'ffffffff R15:b9'604fd018
EIP:23b'647fd0b6 ESP:b9'604fccf0 EBP:b9'604fce60
CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:'00010206

Hopefully I've got all the files you need here, if not let me know, thanks :)
https://drive.google.com/open?id=1A9f4OW_qGsL3TtfsxRY2judpD3huPwaw

**Comment by damianday** [comment]
This triggers an error as well, loos like the same one from the crash dump

```
using System;

namespace Test
{
	public delegate void NotifyEvent(Control sender);

	public class Control
	{
		public Event<NotifyEvent> mOnClick;

		public Event<NotifyEvent> OnClick
		{
			get { return mOnClick; }
		}
	}

	class Program
	{
		public static int Main(String[] args)
		{
			let control = new Control();
			control.OnClick.Add(new => OnButtonPressed);

			control.mOnClick.Invoke(control);

			return 0;
		}

		private static void OnButtonPressed(Control sender)
		{
		}
	}
}
```

**Comment by damianday** [comment]
If I change the OnClick event to take a ref (which I think it should anyway) then the error goes.

**Comment by bfiete** [comment]
The root issue was that the debugger was choking on some missing debug information in the release build of the leak checker (gc.cpp). When a leak is detected, technically that gc.cpp file performs a break which causes debug information for that active function to be loaded, and the 'errorStr' local variable there didn't have a type specified in YOUR build of BeefRT even though it is present in my build. Anyway, that should be handled now (I hope) but I couldn't reproduce it directly locally.

Your test code triggers that bug because the "new Control()" value leaks.

Presumably fixed in https://github.com/beefytech/Beef/commit/c334761aaa107363665c2419bd0515fb478fda5f

**Comment by damianday** [comment]
Yup that fixed both issues.
