### ISSUE TITLE
double.Parse returns colliding hash codes

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#262]
The double.Parse function returns values whose hash codes are very similar (when converted to int32).
**This only applies when building 64 bit application and can easily occur when using the doubles in collections which use the hash codes as keys.**
HashSet and Dictionary internally converts the hash code of the double value to int32 (important detail).

I stumbled upon this issue while creating a map viewer application.
The program reads geo coordinates from an XML file, which then gets parsed by double.Parse.
Then I used these coordinates in a Dictionary for fast lookups. This turned out to be not fast as intended. When I looked into the internals, I saw that 4096 buckets where created, but all of the keys got inserted to just a few buckets.

Code snippet to reproduce:
10 out of 10 run, the NormalDistribution function generates 1000 unique hash codes, while
the Collision function generates 8 unique hash code from 1000 randomly generated double value.
```
using System;
using System.Collections;
using System.Diagnostics;

namespace hashCollision
{
	class Program
	{
		static void NormalDistribution(){
			Random r = scope Random();
			int count = 1000;
			HashSet<int> uniqueHashCodes = scope HashSet<int>();

			for(int i < count){
				double v = r.NextDouble();
				uniqueHashCodes.Add(int32(v.GetHashCode()));
			}

			Debug.WriteLine("{}", uniqueHashCodes.Count);
		}

		static void Collision(){
			Random r = scope Random();
			int count = 1000;
			HashSet<int> uniqueHashCodes = scope HashSet<int>();

			String buffer = scope String();

			for(int i < count){
				double v = r.NextDouble();
				buffer.Clear();
				v.ToString(buffer);
				uniqueHashCodes.Add(int32(double.Parse(buffer).Value.GetHashCode()));
			}

			Debug.WriteLine("{}", uniqueHashCodes.Count);
		}

		static void Main(){
			// Normal hash distribution when generating random double values
			NormalDistribution();
			// Collision when randomly generated doubles are getting parsed from a string
			Collision();
		}
	}
}

```

Possible solution to fix the problem:
In the double.Parse method, if I comment out the whole `sizeof(int) == sizeof(double)` block and just leave there the last two lines, the problem goes away.
```
public int GetHashCode()
{
	double d = (double)this;
	if (d == 0)
	{
		// Ensure that 0 and -0 have the same hash code
		return 0;
	}

	/*if (sizeof(int) == sizeof(double))
	{
		var val = (double)this;
		return *(int*)(&val);
	}
	else
	{*/
		int64 value = *(int64*)(&d);
		return ((int32)value) ^ ((int32)(value >> 32));
	//}
}
```

**Comment by bfiete** [comment]
Thank you for the well-written bug report.
Fix is at https://github.com/beefytech/Beef/commit/f3e9224a45143205438d47e8f48e6c86430665ce.

**Comment by Hiroko103** [comment]
Thank you for the very quick fix!
