### ISSUE TITLE
Beef IDE 0.42.3 Crash - Conditional breakpoint

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#263]
Placing a conditional breakpoint on the line containing the return with the following condition, and then running the program crashes the IDE:

`list.Count == 1`

```
using System.Collections;

namespace idecrash2 {
	class Program {
		public static void Main(){
			List<int> list = scope List<int>();
			return;
		}
	}
}
```

Version info:
0.42.3 release downloaded from the website

**Comment by bfiete** [comment]
Probably not the resolution that you wanted, but functional calls are disabled now for conditional breakpoints, at https://github.com/beefytech/Beef/commit/cfc25003a0fb03f5bb8f5f9e4fedf658b02d39bf

You can directly access members such as mSize though.

Visual Studio also doesn't support function calls for conditional breakpoints, but there do seem to be some presumably hard-coded exceptions like std::vector.size() and such.

One day we will make conditional breakpoints with function calls work properly, but they'll still be a few times slower than conditional breakpoints without calls.

**Comment by Hiroko103** [comment]
Cool, I didn't know I could access private members as well. Thank you for that information.
