### ISSUE TITLE
Beef IDE 0.42.3 - Open debug session menu - Corrupted text

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#264]
The window opened when clicking `File -> Open -> Open Debug Session...` shows a garbage/uninitialized text as the window title.

Image attached.

It's something new every time I close and reopen the whole IDE.
![windowText](https://user-images.githubusercontent.com/6961586/82097965-41556400-9704-11ea-80df-fcc1387eaf4f.PNG)

**Comment by bfiete** [comment]
Just that one, not Open Workspace, Open Project, etc?

**Comment by Hiroko103** [comment]
Yes, only this one from the 'Open' menu. Also, it's worth mentioning that the language of my OS is Hungarian, not English. This might contribute to the issue.
Also, opening 'Open Workspace' shows the title in my native language.
All the other menus open their window with the correct english text.

**Comment by Hiroko103** [comment]
One more thing that I noticed: If I start the BeefIDE_d.exe program, the text is not corrupted.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/9499c727abbfdf44f1f669bd280f3350cac6a770, will be in 0.42.4.
