### ISSUE TITLE
object allocation crash on Android

### ISSUE THREAD

**Issue by kochol** [beefytech/Beef#265]
I write a single android application with beef

but It crashes on first memory allocation

`(bf::System::Internal::Dbg_ObjectAlloc(bf::System::ClassVData*, int, int, int)+116)`

**Comment by kochol** [comment]
it crash on line 370 with allocSize = 12

https://github.com/beefytech/Beef/blob/372bb5f32ff99e400fb7e6aaf53ac4c8cf0cd084/BeefRT/dbg/DbgInternal.cpp#L370

**Comment by kochol** [comment]
Maybe I have to Initialize the BeefRT before using it?
If yes what functions I need to call?

**Comment by kochol** [comment]
I created a native activity in my c code after creating my activity I call Main function of my beef program. But it seems before doing it I have to initialize my runtime but I don't know how yet.

```
		[Export, CLink]
		public static void Main()
		{
			var app = scope GameApp();
			RunApplication(app);
		}
```

**Comment by bfiete** [comment]
You need to call the `main(int, char**)` method - that calls the static constructors (which initializes the runtime), calls your program's Main, and then calls the static destructors.

This is a bit uncharted territory - I've gotten as far as getting the most basic Android application to run one single time, to lay the groundwork for future support, but it's certainly not fleshed out or tested at this point.

**Comment by kochol** [comment]
You mean I also have to compile BeefBoot for android?

**Comment by bfiete** [comment]
No - BeefBoot is a bootstrapping compiler. Why are you asking about that?

**Comment by kochol** [comment]
I can't find `main(int, char**)`  method inside BeefRt library. Can you tell me where is it?

**Comment by kochol** [comment]
Because you said I have to call `main(int, char**)` method but I can not find it in BeefRT
Can you tell me where is it?

**Comment by bfiete** [comment]
The compiler generates that method for you in your own project. I meant to call that instead of trying to direct call your own "Main" method.

**Comment by kochol** [comment]
Oh it is BeefMain thank you for your help.
