### ISSUE TITLE
GL_CreateContext not linked to the correct name

### ISSUE THREAD

**Issue by jharvs97** [beefytech/Beef#266]
On line 813 of SDL.bf, the GL_CreateContext function has the LinkName of SDL_GLContext, causing linking issues. Changing it to the correct link name of "SDL_GL_CreateContext" fixed the issue, would create a PR but dont have the repo on my machine 😔

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/79ae4e3eb2af3331d4624db5eaa88df5718d6760
