### ISSUE TITLE
C interop always passes values by pointer

### ISSUE THREAD

**Issue by TheRawMeatball** [beefytech/Beef#267]
I first came up to this issue while trying to use the [raylib-beef](https://github.com/M0n7y5/raylib-beef) bindings by @M0n7y5, and I have now constructed a small, reproducable version. 
Here's `Program.bf`:
```
using System;

namespace testproj
{
	class Program
	{
		public static void Main(String[] args)
		{
			TestS t;
			t.a = 1;
			t.b = 2;
			t.c = 3;

			Util.printStruct(t);
		}		 	
	}

	public static class Util
	{
		[CLink]
		public static extern void printStruct(TestS t);
	}					 	

	[CRepr]
	public struct TestS
	{
		public int32 a;
		public int32 b;
		public int32 c;
	}
}
```

And here's Util.c: (lib file created with `gcc -c -g util.c && ar rcs libmylib.a util.o`)
```
#include <stdio.h>

typedef struct TestS
{
    int a;
    int b;
    int c;
} TestS;

void printStruct(TestS t)
{
    printf("%d, %d, %d\n", t.a, t.b, t.c);
}
```

With these, running the program outputs `168948368, 32765, 0`.
However, if we modify the `printStruct()` function as such:
```
void printStruct(TestS *t)
{
    printf("%d, %d, %d\n", t->a, t->b, t->c);
}
```
it outputs `1, 2, 3` as it should.

**Comment by kochol** [comment]
It only happens on Linux?

**Comment by TheRawMeatball** [comment]
I don't know, only tested this code on linux.

**Comment by kochol** [comment]
Thank you so much for this fix. I really need it.

**Comment by bfiete** [comment]
I'm just closing this one for now, will deal with new issues as they arise.

**Comment by kochol** [comment]
I tested the new fix and struct returns fixed but there are still bugs when your parameter is by refrence.

`void AddSruct(StructA& a)`

**Comment by bfiete** [comment]
@kochol That doesn't really make sense to me- there's no ambiguity in the calling convention there. Can you provide a full example where this doesn't work?
