### ISSUE TITLE
Does not find VS Tools Path on Windows and when I tell Beef it messes up

### ISSUE THREAD

**Issue by kragil** [beefytech/Beef#268]
I get an error like:

Executing: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools/link.exe" -out:c:\Users\Udo\AppData\Local\BeefLang\Samples\SpaceGame\dist\SpaceGame_d.exe -subsystem:windows C:\Users\Udo\AppData\Local\BeefLang\Samples\SpaceGame/build/Debug_Win64/corlib/corlib__.lib C:\Users\Udo\AppData\Local\BeefLang\Samples\SpaceGame/build/Debug_Win64/SDL2/SDL2__.lib C:\Users\Udo\AppData\Local\BeefLang\Samples\SpaceGame/build/Debug_Win64/SpaceGame/SpaceGame__.lib C:\Users\Udo\AppData\Local\BeefLang\Samples\SpaceGame/build/Debug_Win64/SpaceGame/vdata.obj -defaultlib:libcmtd c:\Users\Udo\AppData\Local\BeefLang\BeefLibs\SDL2\dist\SDL2.lib c:\Users\Udo\AppData\Local\BeefLang\BeefLibs\SDL2\dist\SDL2_ttf.lib c:\Users\Udo\AppData\Local\BeefLang\BeefLibs\SDL2\dist\SDL2_image.lib c:\Users\Udo\AppData\Local\BeefLang\BeefLibs\SDL2\dist\SDL2_mixer.lib -nologo -incremental:no -pdb:c:\Users\Udo\AppData\Local\BeefLang\Samples\SpaceGame\dist\SpaceGame_d.pdb -debug -opt:noref -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64" -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64" -libpath:"C:\Users\Udo\AppData\Local\BeefLang\bin\lib\x64" -libpath:c:\Users\Udo\AppData\Local\BeefLang\Samples\SpaceGame\dist Beef042RT64.lib Beef042Dbg64.lib 
Failed to execute "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools/link.exe"

I guess wrong  slash before the linker :-/

**Comment by bfiete** [comment]
The slash isn't an issue. Did these VS paths get auto-detected or did you manually enter them?

**Comment by bfiete** [comment]
You should be able to go into Preferences / Settings / Visual Studio and click Reset Settings to detect the paths. Do those not work?

**Comment by kragil** [comment]
I set them manually. I reinstalled with admin rights and it worked, but when I try to build something I get "ERROR: Visual Studio tool path not configured. Check Visual Studio configuration in File\Preferences\Settings.
Compile failed."  Resetting does not work.

**Comment by kragil** [comment]
I tried a few things, but nothing helps. Can it be that my VS Studio Install is to blame? I have it installed like it came with Unity.

**Comment by kragil** [comment]
I set a different path manually and now I get: Executing: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\bin\\Hostx86\\x64/link.exe" -out:a:\BeefLang\Samples\SpaceGame\dist\SpaceGame_d.exe -subsystem:windows A:\BeefLang\Samples\SpaceGame/build/Debug_Win64/corlib/corlib__.lib A:\BeefLang\Samples\SpaceGame/build/Debug_Win64/SDL2/SDL2__.lib A:\BeefLang\Samples\SpaceGame/build/Debug_Win64/SpaceGame/SpaceGame__.lib A:\BeefLang\Samples\SpaceGame/build/Debug_Win64/SpaceGame/vdata.obj -defaultlib:libcmtd a:\BeefLang\BeefLibs\SDL2\dist\SDL2.lib a:\BeefLang\BeefLibs\SDL2\dist\SDL2_ttf.lib a:\BeefLang\BeefLibs\SDL2\dist\SDL2_image.lib a:\BeefLang\BeefLibs\SDL2\dist\SDL2_mixer.lib -nologo -incremental:no -pdb:a:\BeefLang\Samples\SpaceGame\dist\SpaceGame_d.pdb -debug -opt:noref -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64" -libpath:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64" -libpath:"A:\BeefLang\bin\lib\x64" -libpath:a:\BeefLang\Samples\SpaceGame\dist Beef042RT64.lib Beef042Dbg64.lib 
LINK : fatal error LNK1104: Datei "libcmtd.lib" kann nicht geffnet werden.

**Comment by bfiete** [comment]
Install the build tools from here:
https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019

if you still get linking problems then install the windows kit from here:
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/

After each step use that 'Reset' button in the Visual Studio settings.

**Comment by kragil** [comment]
Yeah, I added the build tools to Visual Studio and now it works. Is their presence not checked at install time?

**Comment by bfiete** [comment]
No, it is detected at compile time. Did you not see this message the first time you compiled:
```
Beef requires the Microsoft C++ build tools for Visual Studio 2013 or later, but they don't seem to be installed.

Install just Microsoft Visual C++ Build Tools or the entire Visual Studio suite from:
    https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019
```

**Comment by kragil** [comment]
Sorry, no I didn't see that.
