### ISSUE TITLE
I told it to install to a:\Beef and it installed to C:\Users\Udo\AppData\Local\BeefLang

### ISSUE THREAD

**Issue by kragil** [beefytech/Beef#269]
What is wrong with the installer?

**Comment by bfiete** [comment]
Did the installer request elevation and did you refuse that elevation? That may have reset the installation directory.

**Comment by kragil** [comment]
Yes and no. It asked for elevation, but it couldn't get it (for some weird reason) although I clicked yes.
The cow is funny and all, but a working installer is a lot nicer :-P

**Comment by kragil** [comment]
When I execute the installer with Admin rights the install works.

**Comment by bfiete** [comment]
What version of Windows is this?

**Comment by kragil** [comment]
Windows 10 1909 64bit

**Comment by bfiete** [comment]
Well, I'd love to find a repro case for "It asked for elevation, but it couldn't get it (for some weird reason)" but I have not yet been able to cause an elevation failure on any test machine.
