### ISSUE TITLE
Proposal: Link the list of community made Beef libraries to the main website

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#272]
It would be handy to have a list of all the community made Beef libraries, until there is no official package manager for the language.

Similar to these as examples:
- https://github.com/vinta/awesome-python
- https://github.com/quozd/awesome-dotnet
- https://github.com/kozross/awesome-c

The reason I created an issue for it is that, in my opinion, it would be best to put a repository like this under the beefytech github account.

**Comment by animehunter** [comment]
It already exists but not under beefytech: https://github.com/Jonathan-Racaud/awesome-beef

**Comment by damianday** [comment]
Good idea I didn't know about these, would be good to have more visibility, place on the main website or add a Wikipedia to the website

**Comment by Hiroko103** [comment]
I also didn't know it already existed. In this case, I don't intend to move it to another account.
I agree with @damianday.

**Comment by bfiete** [comment]
A link to https://github.com/Jonathan-Racaud/awesome-beef has been placed on https://www.beeflang.org/.
