### ISSUE TITLE
Autocomplete disappears when variable/field name starts with a language keyword

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#276]
This is just a minor inconvenience.
If I start typing out the name of the variable, it disappears when it exactly matches one of the language keywords, but if I continue, it appears again.

It happens when the variable is a struct field or a class member, but also when it's a simple variable on the stack.

![rec](https://user-images.githubusercontent.com/6961586/82154947-9662b880-9871-11ea-9b7d-8e1e73424471.gif)

**Comment by bfiete** [comment]
Improved at https://github.com/beefytech/Beef/commit/e16e4613b691f8cf8c458aa65125cb06eff0dab1. Check out the nightly build tomorrow.

**Comment by Hiroko103** [comment]
Works great. Thank you!
