### ISSUE TITLE
Bug on compiler

### ISSUE THREAD

**Issue by kochol** [beefytech/Beef#278]
Compiler bug. I think the code speaks better 😁
The compiler cast types to types* without getting an error if you use a struct or class filed.

```
public struct foo
{
    public uint32 bar = 0;
}

public static uint32 temp;

public static test(uint32* _val)
{
// do something
}

public static call_test()
{
     foo f;
     test(temp); // error: unable to implicity cast 'uint32' to 'uint32*' -- OK
     test(f.bar); // Compiles and makes bug
}
```

**Comment by bfiete** [comment]
I can't reproduce this with the given code - also, there were a couple errors which cause that exact code to not compile so perhaps your test program was different?

![image](https://user-images.githubusercontent.com/3042917/82234569-6f929980-98e6-11ea-8c52-e87c6c538f9d.png)
