### ISSUE TITLE
Dependency removal

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#279]
Removing a project from a workspace does not remove it from the project dependencies, furthermore you are then unable to remove it until you reopen the project.

**Comment by bfiete** [comment]
This is from right-clicking Remove... from the workspace panel, on a trunk build? I'm having a bit of trouble reproducing this so far...

**Comment by damianday** [comment]
Yeah, the project gets removed and when I check the depencies it is also removed. But then when I reopen the project after closing the ide the dependency is back in red, but the project is removed successfully

**Comment by bfiete** [comment]
Ah. If I understand correctly, it was really just an issue of projects depending on that removed project not being marked as being "changed" (and thus needing to be saved).

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/cd09529c9a2b7cf11f2a1b07b7ea5f1f7b85e862
