### ISSUE TITLE
Crash when changing font to non-existent file

### ISSUE THREAD

**Issue by Zoodinger** [beefytech/Beef#28]
In my first effort to change the font I replaced fonts/SourceCodePro-Regular.ttf with fonts/Consolas.ttf which popped up a very nasty crash whose UI was frozen (I couldn't scroll or see core dump either).
![image](https://user-images.githubusercontent.com/6585526/72441060-ecc7c980-37a1-11ea-9e3b-f23b470d797e.png)

I managed to change font by simply having the word Consolas instead of fonts/Consolas.ttf (duh)

**Comment by bfiete** [comment]
Fixed with https://github.com/beefytech/Beef/commit/957f24e1598c5a77e487f7ce8f6d6336de2b190d, will be in release 0.42.2.
