### ISSUE TITLE
Closing issues marked as fixed

### ISSUE THREAD

**Issue by TheRawMeatball** [beefytech/Beef#280]
When a bug is fixed, shouldn't the issue be closed? As it stands, there are a lot of open issues which have been fixed and even labeled as such, but the issue is still open. Will they be closed, and if so, when?

**Comment by bfiete** [comment]
This is a good question - when working with QA I expect them to close bugs after the fix has been verified. Is standard practice here just to close bugs as they are fixed and then let the OP reopen them if the fix doesn't address the issue?

**Comment by bfiete** [comment]
My current working rule was to close them "after a while" after an official release has gone out with the fix, if the OP doesn't close it.

**Comment by TheRawMeatball** [comment]
Ok, I was just curious.
