### ISSUE TITLE
IDE crash after removing project

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#281]
After removing a project from the workspace with 'right click, remove' and then attempting to immediately build the project causes the IDE to crash.

**Comment by bfiete** [comment]
Clearly this project removal doesn't get tested very often. I added a test to the IDE test suite now, at least.

I believe this particular issue should be fixed here https://github.com/beefytech/Beef/commit/833b4002a54da54559c20a7b66a9ecfd4ea98165
