### ISSUE TITLE
Renaming issue

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#282]
It seems sometimes when I go to rename a variable, usually for the first time it fails and only modifiers the text at the cursor.

**Comment by bfiete** [comment]
I use this quite a lot and never see failures like this.

Do you see the "Renaming" box in the upper right when that happens? Does it properly show a reference count? Do you rename through the right-click menu or with Ctrl+R?

**Comment by damianday** [comment]
Yes the box pops up briefly and looks correct, as soon as I type it vanishes and doesn't modify.
Most of the time it works as expected.

I can reproduce it by:
1. Click once to open a file in the preview tab on the right.
2. Immeditaley right click a variable to rename a member.

**Comment by damianday** [comment]
At least I think thats what was causing the issue.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/01f82d125004e73c7b526afea718fe1ac8bd83a4
