### ISSUE TITLE
Cannot Invoke an event parameter by reference

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#283]
This snippet demonstrates the problem.

```
using System;

namespace Test
{
	public delegate void NotifyEvent(ref int sender);

	class Program
	{
		public static int Main(String[] args)
		{
			int value = 10;
			Event<NotifyEvent> mOnClick = default;

			mOnClick.Invoke(ref value);

			return 0;
		}
	}
}
```

**Comment by damianday** [comment]
As a workaround one can change the signature to use pointer..

> public delegate void NotifyEvent(int* sender);
> 
> 	class Program
> 	{
> 		public static int Main(String[] args)
> 		{
> 			int value = 10;
> 			Event<NotifyEvent> mOnClick = default;
> 
> 			mOnClick.Invoke(&value);
> 
> 			return 0;
> 		}
> 	}

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/e82daf74d43bde3b9beb9dcf275f301e758c1760

Also, the "Invoke" part is implicit so you could just do `mOnClick(ref value);`

**Comment by damianday** [comment]
@bfiete Oh, now you tell me :P, thanks didnt know that.
