### ISSUE TITLE
0.42.4 - Ambiguous reference bug with extensions

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#287]
### Overview:
I have a class like this:
```
class FuncHelper
{
}
```
This class has some extensions in different files, like this:
```
extension FuncHelper
{
	public static bool Func(int param)
	{
		// do something
		return true;
	}
}
```

### The issue:
If I change the base class to static, any reference to the class will accuse an ambiguous reference:
![image](https://user-images.githubusercontent.com/14041768/82604410-a7ba0680-9b8a-11ea-80c6-8f0234e71079.png)

This will not block the build, and the only way to fix it is to Clean the build.

**Comment by bfiete** [comment]
I'm having some trouble reproducing this-
Do you have an actual working repro case you can post here, with some step-by-step instructions to trigger this?

**Comment by Igoorx** [comment]
This is the project that I used to test this issue, to reproduce the bug just open the project, go to file Program.bf and you will see everything is normal with no errors whatsoever, then open the file FuncHelper.bf and add the static keyword to the class, after that go back to Program.bf and you will see the ambiguous reference.
[test3 - Copy.zip](https://github.com/beefytech/Beef/files/4677784/test3.-.Copy.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/e25f8901a5cf0f4fa611849450c3abbe065235e0
