### ISSUE TITLE
[Feature request] Allow using spaces instead of tabs

### ISSUE THREAD

**Issue by Ruzihm** [beefytech/Beef#29]
The IDE seems to be hardcoded to write tab characters instead of spaces when indenting code. 

Please add an IDE option for using space characters (` `) for indentation and an option for how many characters wide the indentation should be.

**Comment by LucaSoato** [comment]
Python developers would love this lol

**Comment by bfiete** [comment]
Finally implemented at 67329ac774a128dba41a73400fdebd49f450a471
