### ISSUE TITLE
Autocomplete on wrong screen

### ISSUE THREAD

**Issue by procfxgen** [beefytech/Beef#293]
Hi, I have a pc with 2 monitors and autocomplete context menu open on wrong screen. 
I use Version 0.42.5 (Nightly 05/25/2020) built 5/25/2020 at 6:51 AM.
Thanks.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/323f984a723620829625173b40edd8ff20d3eafc
