### ISSUE TITLE
"Value doesn't fit into int64" error when assigning -0x8000000000000000L to variable

### ISSUE THREAD

**Issue by pmysl** [beefytech/Beef#295]
BeefBuild returns `"Value doesn't fit into int64"` error for the following snippet of code. When I assign the same value, but without `L` suffix then code compiles without problem

```cs
using System;

namespace nmspc
{
        class Program
        {
                public static int Main(String[] args)
                {
                        let test = -0x8000000000000000L;

                        return 0;
                }
        }
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/534d20121c387258ea46b1eab47f99fea448cad9
