### ISSUE TITLE
Crash while installing Beef Nightly build

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#304]
```
Exception: Access Violation (code 0xc0000005) at address 7ffb'5671adfc in thread 2DCC
Executable: D:\Downloads\BeefSetup.exe
File Version: 0.42.5 (Nightly 05/26/2020)
Product Version: bff1d657ccae405b1cb81fe5afceacb9d41f00cd

Logical Address: 0001:'00079dfc

7b'6027fd90 7ffb'5671adfc BeefInstallUI.dll Start+708AC
    Params: '00000000 '00000000 '00000000 '00000002

7b'6027fdd0 7ffb'5670dede BeefInstallUI.dll Start+6398E
    Params: '00000000 '00000000 '00000000 '00000bf4

7b'6027fe20 7ffb'5671aacb BeefInstallUI.dll Start+7057B
    Params: 7b'5fbfeb10 '00000000 '00000000 '00000000

7b'6027fe50 7ffb'793a7bd4 KERNEL32.DLL BaseThreadInitThunk+14
    Params: '00000000 '00000000 '00000000 '00000000

7b'6027fed0 7ffb'7952ce51 ntdll.dll RtlUserThreadStart+21
    Params: '00000000 '00000000 '00000000 '00000000


RAX:'00000000 RBX:7b'5fbfeb10 RCX:7b'5fbfeb10 RDX:7b'6027fdcc RSI:7b'5fbfeb10 RDI:7b'6027fdcc
R8:7b'6027fd68 R9:'00000000 R10:'00000000 R11:'00000246
R12:'00000000 R13:'00000000 R14:'00000000 R15:'00000000
EIP:7ffb'5671adfc ESP:7b'6027fd70 EBP:'00000000
CS:0033 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:'00010202
```

[bfs_crashdump.zip](https://github.com/beefytech/Beef/files/4690952/bfs_crashdump.zip)

**Comment by bfiete** [comment]
Does this consistently crash on start up? Does the installer from the stable build NOT crash currently for you?

**Comment by Igoorx** [comment]
It consistently crashes while installing with "Install for All Users" unchecked, in the stable build using the same settings it doesn't crash but gives this fatal error:
![image](https://user-images.githubusercontent.com/14041768/83063688-eb9f8680-a036-11ea-99e5-65f2a83e72bb.png)

**Comment by bfiete** [comment]
And what happens in those cases when you have Install for All Users checked?

**Comment by Igoorx** [comment]
The IDE asks for elevation and installs successfully.

**Comment by RogueMacro** [comment]
I believe this isn't a problem in the current version of Beef.

**Comment by bfiete** [comment]
Yeah- reopen if it does!

**Comment by Igoorx** [comment]
Yeah, looks like it doesn't happen anymore, but I would like to mention that I can't reopen by myself a issue that you closed!

**Comment by bfiete** [comment]
True! That kinda seems like a weird default on Github's part, considering the OP could just create a new item, so what's the point in restricting them from continuing from an old one. Oh well.
