### ISSUE TITLE
Attempting to compile a release crashes the IDE but not when compiling the debug version

### ISSUE THREAD

**Issue by FranklyGD** [beefytech/Beef#305]
After a certain unknown point while developing, the IDE decides to crash when attempting to compile a release. However compiling the debug version works fine in IDE and externally runs fine. I did add lines in the corlib project, specifically the "Window.bf" file if this had contributed to this crash.

```
[CLink, StdCall]
public static extern IntBool ReadProcessMemory(ProcessHandle process, void* baseAddress, void* buffer, int size, int* numberOfBytesRead);
```

Besides corlib, SDL2 is also used.

[Crash Error Log](https://pastebin.com/Q2SPQqTB)
[Crash Dump](https://github.com/beefytech/Beef/files/4691706/beefcrashdump.zip)

Semi-background, I wanted to attach to another program and read and display its data in a certain way to understand. Hence the added two lines added to "Window.bf". If the whole project is required for reproducing, I will gladly send.

**Comment by bfiete** [comment]
There's a poorly-formed LLVM IR function... from the dump I can see the module name is 'ExternalSomething_Emulator' which is representative of the file the error occurred in, but I can't tell what function had the issue.

One way to debug this: go to Workspace/Properties, Beef/General/Intermediate Type, and set that to "Object And IRCode". Compile with release (let it crash) and then find ExternalSomething_Emulator.ll -- attach that here. I'll be able to run the IR file through the LLVM IR compiler and determine what the function is.  Then we can figure out what's going on there that's interesting.

**Comment by bfiete** [comment]
Sadly in this case, LLVM actually prints out useful info to stderr but we just can't see it. I'm going to try to capture stderr so we can attach it to crash reports in the future...

**Comment by bfiete** [comment]
Tonight's nightly build will include support for capturing the LLVM error output in the crash dialog, so you can try that build tomorrow (or whenever) so we can narrow this down...

**Comment by bfiete** [comment]
@FranklyGD Any chance of giving this another try? I'd like to get this resolved...

**Comment by FranklyGD** [comment]
I'm sorry I took long to return. Here are the files while on the latest nightly build. I do notice some extra details to the error in the long. Something about pointer not the same?

[Crash Error Log](https://pastebin.com/brzK1RHE)
[Crash Dump](https://github.com/beefytech/Beef/files/4733064/BeefDump.zip)

**Comment by bfiete** [comment]
Hm, there's something fishy going on in ExternalSomething.Emulator.BindToEmulator() involving the ExternalSomething.Emulator.EmulatorType enum.

The easiest thing would be if you could share the source to that project (either email to beef@beefytech.com or post it here). if you don't want to do that, then maybe we can figure it out from just the code from that method and the declaration of EmulatorType...

**Comment by FranklyGD** [comment]
@bfiete I sent over an email with the zip of the project. The title should contain the issue number.

**Comment by bfiete** [comment]
Thanks, that was super helpful. Fixed in https://github.com/beefytech/Beef/commit/71bc9c5d614ab7bf0e12f59d68dc46855b213006, try the nightly release after the next build (next build in ~11 hours)!
