### ISSUE TITLE
[Feature Request] (IDE) Add option to place cursor at the end of the line rather than everywhere

### ISSUE THREAD

**Issue by RUSshy** [beefytech/Beef#31]

**Comment by wilsonk** [comment]
Hello @RUSshy , you can sort of get this functionality, when moving around the IDE using the left/right keys, by holding down Ctrl at the same time. This will pop the cursor to the first or last character on a line, when jumping one word at a time. Seems to work pretty well for me. I would like to see Vim bindings for the IDE however ;)
