### ISSUE TITLE
Generic method overload doesn't work

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#310]
This code:
```
	class Class1
	{
		public bool Method1<T>(T param1) where T : var
		{
			return Class2.Method1<T>(this, param1);
		}

		public bool Method1(int param1)
		{
			Console.WriteLine(param1);
			return true;
		}
	}

	static class Class2
	{
		public static bool Method1<T>(Class1 param1, List<T> param2)
		{
			return Method2(param1, (IEnumerator<T>)param2.GetEnumerator(), param2.Count);
		}

		public static bool Method2<T>(Class1 param1, IEnumerator<T> param2, int param3)
		{
			for (let p in param2)
			{
				Console.WriteLine(p);
			}
			return true;
		}
	}

	class Program
	{
		public static void Main()
		{
			Class1 c = scope Class1();
			c.Method1(999);

			Console.In.Read();
		}
	}
}
```

Results in this error:
```
ERROR: Unable to implicitly cast 'int' to 'System.Collections.List<int>'
  while specializing method 'test3.Class1.Method1<int>(int param1)' at line 10:35 in d:\BeefLang\test3\src\Program.bf
   return Class2.Method1<T>(this, param1);
                                  ^^^^^^
```

Tested in version: 0.42.5 (Nightly 05/26/2020)

**Comment by bfiete** [comment]
It looks like it's doing what you're asking for:

In Main you call `c.Method1(999)` which invokes `Class1.Method1<int>(int param1)`.
Then you call `Class2.Method1<T>(this, param1)` which invokes `Class2.Method2(Class1 param1, List<int> param2`.

You're trying to pass a an `int` to a method that expects a `List<int>`. 

This is one of the reasons you don't want to use `var` as a generic constraint unless you really need to: you end up with less-friendly error messages. 

Did you indent for Class1.Method1 to only accept lists as an argument, or did you expect that somehow the `int` would magically be turned into `List<T>` for the Class2.Method1 call?

**Comment by Igoorx** [comment]
@bfiete neither, I wanted to call the overload, the error is here showing that for some reason beef is calling the generic method while there's a overload for the type.

**Comment by bfiete** [comment]
Oh, yeah. I totally missed the basic issue because I was focused on error. 

Here's a simplified version without the other noise.
```
class Program
{
	public static bool Method1<T>(T param1)
	{
		return false;
	}

	public static bool Method1(int param1)
	{
		return true;
	}

	public static void Main()
	{
		Runtime.Assert(Method1(123));
	}
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/7bd29b5b692821b4e0aacc03ac2a7b4192b7dfb3
