### ISSUE TITLE
[IDE] Crash after pressing CTRL+K, CTRL+D (code format)

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#315]
IDE will crash after pressing key bind  for code formatting **(CTRL+K, CTRL+D)**
IDE version Version 0.42.5 (Nightly 05/30/2020) built 5/30/2020 at 6:31 AM.

Code:
```csharp
namespace Hydra
{
	public struct PROCESSENTRY32 {
	  int32     dwSize;
	  int32     cntUsage;
	  int32     th32ProcessID;
	  void*     th32DefaultHeapID;
	  int32     th32ModuleID;
	  int32     cntThreads;
	  int32     th32ParentProcessID;
	  int64     pcPriClassBase;
	  int32     dwFlags;
	  char8[260]szExeFile;
	} 
}
```

**Comment by bfiete** [comment]
Is this still happening on the latest nightly for you?

If so, can you post the crash dump?
And this text is the total contents of the file you're reformatting?

**Comment by bfiete** [comment]
Waiting for validation this is still happening...

**Comment by M0n7y5** [comment]
@bfiete I am gonna try it asap

**Comment by M0n7y5** [comment]
@bfiete No still problem .... 

Content of file 
```csharp
using System;
namespace Hydra
{
	[CRepr]
	public struct PROCESSENTRY32 {
	  public uint32     dwSize;
	  public uint32     cntUsage;
	  public uint32     th32ProcessID;
	  public void*  	th32DefaultHeapID;
	  public uint32     th32ModuleID;
	  public uint32     cntThreads;
	  public uint32     th32ParentProcessID;
	  public uint64     pcPriClassBase;
	  public uint32     dwFlags;
	  public char8[260]	szExeFile;
	}

	public enum SnapshotFlags : uint32
	{
		HeapList = 0x00000001,
		Process = 0x00000002,
		Thread = 0x00000004,
		Module = 0x00000008,
		Module32 = 0x00000010,
		Inherit = 0x80000000,
		All = 0x0000001F,
		NoHeaps = 0x40000000
	}
}
```

Crash dump
[crash.zip](https://github.com/beefytech/Beef/files/4737385/crash.zip)

**Comment by bfiete** [comment]
The funny thing is that the issue was actually the whitespace at the end of the file..
Fixed at https://github.com/beefytech/Beef/commit/2eac63e31c6b5cdb237ad1cf968715016ea75edb
