### ISSUE TITLE
IDE Crash typing in lambda

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#317]
5/31 Nightly build - [crash dump](https://github.com/beefytech/Beef/files/4708259/crash.zip)

Here's a simplification of the relevant code:
```
private bool autoJump;

private Timer tAutoJump;

public this(Point position) : base(position)
{
    tAutoJump = Add(new Timer(new () =>
    {
        //Beginning to type "autoJump = false;" here crashes the IDE
    }));
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/fa3914e6748a57f30cf363eaf06b0871c751f1c4
