### ISSUE TITLE
IDE rename crash

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#318]
Daily build 5/31 - [crash dump](https://github.com/beefytech/Beef/files/4708621/crash.zip)

I don't think I was doing anything special, just using Ctrl+R to rename an int instance variable.

**Comment by bfiete** [comment]
This was introduced here https://github.com/beefytech/Beef/commit/5a5287bc8b058078130f1423744a7b1461865a4c

And fixed here
https://github.com/beefytech/Beef/commit/4fe4bcc3426ce883e0d00dc3ec4d14f1ce12c2ce
