### ISSUE TITLE
SDL GL_SetAttribute sign

### ISSUE THREAD

**Issue by andreakarasho** [beefytech/Beef#319]
From SDL doc, the `GL_SetAttribute` sign wants an int32: 
https://wiki.libsdl.org/SDL_GL_SetAttribute

Instead beef sdl2 is an enum [casted as int32]:
https://github.com/beefytech/Beef/blob/394dec5bae897a7f3035964e658dca1fe586a286/BeefLibs/SDL2/src/SDL2.bf#L859

I think because of:
https://github.com/flibitijibibo/SDL2-CS/blob/3e7eaf9d5be29f181507226f626ac61f1e068b6e/src/SDL2.cs#L1851

**Comment by bfiete** [comment]
Maybe someone will submit a PR for this

**Comment by RogueMacro** [comment]
Fixed in 8b8d7fd
