### ISSUE TITLE
Crash pasting code into editor

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#32]
Attached crash dump and relevant file I was copying.

[base.zip](https://github.com/beefytech/Beef/files/4081736/base.zip)

[beef.zip](https://github.com/beefytech/Beef/files/4081735/beef.zip)

**Comment by bfiete** [comment]
Do you mind sharing the rest of the project's code? The crash is dependent on some other code in that project... I can see where it's crashing but not exactly why yet.

**Comment by bfiete** [comment]
Anyway- potential fix checked in, will be available in 0.42.2.

**Comment by damianday** [comment]
To trigger the error all I did was create a new class with the ide and copy paste the contents of the .cs file overwriting the generated beef class file.

Thank you will test it in the next release.

**Comment by damianday** [comment]
Confirmed no longer crashing.
