### ISSUE TITLE
0.42.5 - "Unreachable code" is reachable

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#320]
The IDE complains that this code contains unreachable code but actually all of the code is perfectly reachable.

![image](https://user-images.githubusercontent.com/14041768/83483353-d1bbd480-a478-11ea-91a4-1990c87006af.png)

```
using System;
using System.Collections;

namespace test3
{
	class Class1
	{
		public bool Method1(ref int param1)
		{
			return true;
		}

		public bool Method1<T>(ref List<T> param1) where T : var
		{
			for (int i = 0; i < param1.Count; ++i)
			{
				T obj_ = (T)param1[i];
				if (!Method1(ref obj_))
					return false;
				Console.WriteLine("Line reached");
			}
			return true;
		}
	}

	class Program
	{
		public static void Main()
		{
			Class1 c = scope .();

			List<int> i = scope .();
			i.Add(1337);
			Runtime.Assert(c.Method1(ref i));

			Console.WriteLine("End.");
			Console.In.Read();
		}
	}
}
```

**Comment by bfiete** [comment]
I knew exactly what this was when I saw it - it was caused by another "fix" for these generics issues!
Fixed at https://github.com/beefytech/Beef/commit/41629b49d1bba462e56a5c3b40de85cf4efbd7bb
