### ISSUE TITLE
0.42.5 - IDE Crash while editing call argument

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#323]
So, I just found yet another crash, maybe this one is related to https://github.com/beefytech/Beef/issues/314 or https://github.com/beefytech/Beef/issues/312 because they both occurred while I was editing a line.

I will need a gif to show how this crash happens:
![crasshh_line](https://user-images.githubusercontent.com/14041768/83577461-95d14f80-a50a-11ea-800c-9dd60c97b9cc.gif)
Basically, I insert a `(` in that specific location and delete it and insert it again and the crash happens.

Here is the crashdump:
[crashdump_line.zip](https://github.com/beefytech/Beef/files/4720081/crashdump_line.zip)

And here is the code used:

```
using System;
using System.Collections;

namespace test3
{
	class Class1
	{
		public bool Method2<T>(ref IEnumerator<T> param1)
		{
			return true;
		}

		public bool Method1<K, V>(ref Dictionary<K, V> param1) where K : IHashable
		{
			return Method2(param1.GetEnumerator());
		}
	}

	class Program
	{
		public static void Main()
		{
			Class1 c = scope .();

			Dictionary<int, int> d = scope .();
			d.Add(1337, 123);
			Runtime.Assert(c.Method1(ref d));

			Console.WriteLine("End.");
			Console.In.Read();
		}
	}
}
```

**Comment by bfiete** [comment]
Can you verify this again with the next nightly? I'm not sure where it got fixed but I can't reproduce it.

**Comment by Igoorx** [comment]
@bfiete Yeah, tested it again and it crashed.
```
File Version: 0.42.5 (Nightly 06/04/2020)
Product Version: a186421ba8ebdc39a99f871ab4fc0fc6e4fa5780
```

**Comment by Igoorx** [comment]
> Can you verify this again with the next nightly? I'm not sure where it got fixed but I can't reproduce it.

Yeah, it's happening:
![image](https://user-images.githubusercontent.com/14041768/83973879-b1987500-a8bf-11ea-934f-4894a3732dbc.png)

Here is the crashdump with the debug build:
[d_dump_call.zip](https://github.com/beefytech/Beef/files/4742403/d_dump_call.zip)

**Comment by bfiete** [comment]
Ah- I'm pretty sure this is the same crash as https://github.com/beefytech/Beef/issues/312

The missing piece of information was that you are using the autocomplete panel rather than the "normal" pop-up autocomplete. 

Fixed at https://github.com/beefytech/Beef/commit/ad89d4cc821621ea2abfb939f795888d7652b389
