### ISSUE TITLE
0.42.5 - A couple of bugs

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#324]
This code should work but has parsing issues:
```
public bool Method2<TEnumerator, TElement>(TEnumerator param1) where TEnumerator : IEnumerator<TElement>
{
    return true;
}

public bool Method1<K, V>(Dictionary<K, V> param1) where K : IHashable
{
    return Method2<Dictionary<K, V>.Enumerator, (K key, V value)>(param1.GetEnumerator());
}
```

Also, I wanted to use this another code but right now I can't figure how to make it work in Beef, in C# I would use IEnumerables but IEnumerables can't be used in for-loops in Beef, the only way I found was to use IEnumerators, that works with the List method but something seems to be wrong with the Dictionary method.
```
	class Class1
	{
		public bool Method2<T>(IEnumerator<T> param1)
		{
			for (var i in param1)
			{
				Console.WriteLine(i);
			}
			return true;
		}

		public bool Method1<K, V>(Dictionary<K, V> param1) where K : IHashable
		{
			return Method2(param1.GetEnumerator());
		}

		public bool Method1<T>(List<T> param1)
		{
			return Method2((IEnumerator<T>)param1.GetEnumerator());
		}
	}
```

**Comment by bfiete** [comment]
These are fixed. Also you can enumerate over generics with `IEnumerator<T>` constraints (like in Method2 in the first example).
