### ISSUE TITLE
Auto Include folder not working on startup

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#326]
I have a folder with some files I'm not using that contains errors.  I turned off Auto Include for that folder, the errors disappeared, but after I opened the IDE again later, the errors pop back up until I turn  Auto Include off and on again.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/5d9a5f183dab5dfe2f6adbf2168b26559bf22800
