### ISSUE TITLE
TypeInstance.CreateObject() fails

### ISSUE THREAD

**Issue by Jonathan-Racaud** [beefytech/Beef#328]
Hello,

What could be the cause of the ```mTypeClassVData``` to be ```null``` when using the ```TypeInstance.CreateObject()``` method ? I'm working on a JSON lib and am trying to implement Deserializing a JSON String into a user defined type.

Here is how I retrieve what type I need to create:
```c#
// The field I'm inspecting is of type List<Book>
let generic = fieldType as SpecializedGenericType;
let genericType = generic.GetGenericArg(0) as TypeInstance;
```
When getting the type's fullname I successfully get "JSON_Beef_Test.Book"
I then try to create the Book type by calling ```genericType.CreateObject()```, but if fails because ```mTypeClassVData``` is null.

Here's how my project is organised:
- JSON_Beef is the lib project (built as Library)
- JSON_Beef_Test a test program where I test every methods from the JSON_Beef lib. JSON_Beef is added to the JSON_Beef dependencies.

About my classes:

I have an Author class defined like so:
```c#
[Serializable]
public class Author: Person
{
	public List<Book> Books = new List<Book>() ~ DeleteContainerAndItems!(_);
	public List<String> Publishers = new List<String>() ~ delete _;

	public this(String firstName = "", String lastName = "", int age = 0)
	{
                FirstName = firstName;
		LastName = lastName;
		Age = age;
	}
}
```

and the Book class:
```c#
[Serializable]
public class Book
{
	public String Name;

        // Defining this constructor or not doesn't change the issue
	public this()
	{
	}

	public this(String name = "")
	{
		Name = name;
	}
}
```

and the SerializableAttribute:
```c#
[AttributeUsage(.Class | .Struct, .ReflectAttribute, ReflectUser=.All)]
public struct SerializableAttribute: Attribute
{

}
```

It's most likely that I am the cause of this problem, because at one point the check for  mTypeClassVData didn't failed. The Book object was not created either because I didn't have a constructor without argument at first. The issue arrived after adding it to the class.

Thanks in advance for your help.

**Comment by bfiete** [comment]
You need to add an "[AlwaysInclude(AssumeInstantiated=true)]" attribute to any types that are not explicitly instantiated in your program but you want to be instantiated via reflection.

**Comment by Jonathan-Racaud** [comment]
Thank you, I changed the declaration of my SerializableAttribute like so:
```c#
[AttributeUsage(.Class, ReflectUser=.All),
	AlwaysInclude(AssumeInstantiated=true),
	Reflect]
public struct SerializableAttribute: Attribute
{
}
```

And I am now able to instantiate it via reflection.

**Comment by bfiete** [comment]
Oh- you should have needed that `AlwaysInclude` attribute on the actual types that weren't able to be instantiated, not on the attribute itself. That worked?

**Comment by bfiete** [comment]
It kindof brings up a point, that maybe the AttributeUsage could have AlwaysIncludeUser and AssumeUserInstantiated properties...

**Comment by Jonathan-Racaud** [comment]
So I verified again and what I said in my last comment doesn't work. As for the initial issue, the AlwaysIncludeUser attribute fixed it.

I have however a weird issue with my builds regarding the attributes. Sometimes, changes related to the attributes are not taken into account. I'll document it here, but if it needs to be put into its own issue, I'll create a new one.

1. Write the Book class like that:
```c#
//[Serializable]
[AlwaysInclude(AssumeInstantiated=true, IncludeAllMethods=true)]
[Reflect]
public class Book
```
2. Compile.
3. The Book object can be created using the Type.CreateObject() method and its attributes can be set.
![Attributes_on_Book_class](https://user-images.githubusercontent.com/4101737/83901383-f48d0800-a75a-11ea-9f3f-7ed3067c5a6f.png)

4. Change the Book class declaration as to have this:
```c#
//[Serializable]
//[AlwaysInclude(AssumeInstantiated=true, IncludeAllMethods=true)]
//[Reflect]
public class Book
```
5. Compile.
6. The Book object cannot be created using reflection.
![No_attributes_on_Book_class](https://user-images.githubusercontent.com/4101737/83901421-066eab00-a75b-11ea-8998-deb9d6798c08.png)

7. Repeat steps 1-3, the behavior is as intended (object created and fields can be set).
8. Rewrite the Book class as: 
```c#
[Serializable]
//[AlwaysInclude(AssumeInstantiated=true, IncludeAllMethods=true)]
//[Reflect]
public class Book
```
8bis. The SerializeAttribute is written as:
```c#
[AttributeUsage(.Class, ReflectUser=.All),
	AlwaysInclude(AssumeInstantiated=true, IncludeAllMethods=true),
	Reflect]
public struct SerializableAttribute: Attribute
{
}
```
9. Build.
10. I have the behavior I expect (c.f figure 1).
11. Clean and Clean Beef.
12. Build again.
13. The behavior is the same as in step n°6 (c.f figure 2).

Also one thing I forgot to mention, the SerializableAttribute is declared inside the JSON_Beef library and not in the JSON_Beef_Test where the Author and Book classes are declared.

My intention was to have the user of the library to only use the SerializableAttribute to allow Serialization and Deserialization using reflection, hence why I tried to concatenate the AlwaysInclude and Reflect attributes together (I also tried inheriting from one of them, but to no avail).

**Comment by Jonathan-Racaud** [comment]
Thank you for all those clarifications and help.

**Comment by bfiete** [comment]
Closing this because the side-issue of metadata removal should be fixed now at https://github.com/beefytech/Beef/commit/f81a1cf89661dc685f4bc302d563e2f602cc7e24
