### ISSUE TITLE
Socket server fails

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#331]
```cs
Socket.Init();

var listener = scope Socket();
defer listener.Close();
listener.Listen(6666);

var socket = scope Socket();
defer socket.Close();

socket.AcceptFrom(listener);
```
I tried this code but it fails on `socket.AcceptFrom(listener);`.
Im using win7 if that matters.

**Comment by bfiete** [comment]
AcceptFrom returns an error if there's no connection waiting.  You can use Select to wait for the listening socket (in readFS) to have a connection or simply poll AcceptFrom until there's a connection.

**Comment by TheRawMeatball** [comment]
It does in linux though..

**Comment by MineGame159** [comment]
Ah, so if I have a loop thats listening for packets or connections do I just have to add every socket to the fd sets at the beginning of the loop?

**Comment by bfiete** [comment]
Yeah. There's really no "functionality" here - it's just a very thin wrapper over normal sockets.
