### ISSUE TITLE
Sockets behave diffrently on diffrent platforms

### ISSUE THREAD

**Issue by TheRawMeatball** [beefytech/Beef#332]
As outlined in  #331 , sockets are blocking on Linux, and non-blocking on Windows. It would be nice if they were always non-blocking, or better yet the choice of blocking or non-blocking could be made with a function call, or if it were a constructor parameter.

**Comment by bfiete** [comment]
Oh, yeah, it's still using the FIONBIO value lifted from Windows... maybe someone will be a dear and post a PR with a fix for that...

**Comment by TheRawMeatball** [comment]
I looked around and figured 0x00005421 was the value, according to [here](https://linux.die.net/man/2/ioctl_list), but when I set FIONBIO to that value, it didn't block, and, it didn't send back an error either. It just continued, like there was a connection waiting, and exited with no errors.

**Comment by TheRawMeatball** [comment]
Made the PR.
