### ISSUE TITLE
IDE Suggestion: Add CTRL+SHIFT+Z (Redo shortcut)

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#334]
Quite self-explanatory, almost any editor supports this shortcut but Beef IDE doesn't. I can't even edit the Redo shortcut because It isn't in the Settings panel.

**Comment by bfiete** [comment]
Added in https://github.com/beefytech/Beef/commit/d46383216858b8268b73eb47ed8728f63c850daa, with a few other keys:
Shift+Delete, Ctrl+Insert, and Shift+Insert : Cut/Copy/Paste
Ctrl+K, Ctrl+C  / Ctrl+K, Ctrl+U : comment/uncomment block
Ctrl+D duplicate line
