### ISSUE TITLE
IDE Suggestion: Preview property on mouse over

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#335]
I find it quite annoying that I can't see the result of properties in Beef, mainly the auto-properties.

![image](https://user-images.githubusercontent.com/14041768/83977009-237ab980-a8d4-11ea-9093-f95105494d05.png)
_The first row shows I hovering the Test1 property first in C# and second in Beef, the second row shows I hovering the Test2 property first in C# and second in Beef but this time in the line that I set the value of it._

**Comment by bfiete** [comment]
Note that in the 'Test1' example, hovering over it will cause a memory leak since you allocate an object that you don't delete... 

Of course this auto-execution of methods in C# can also have bad side effects. It seems very dangerous to me, but maybe it is justified...

**Comment by Igoorx** [comment]
> Note that in the 'Test1' example, hovering over it will cause a memory leak since you allocate an object that you don't delete...
> 
> Of course this auto-execution of methods in C# can also have bad side effects. It seems very dangerous to me, but maybe it is justified...

I know about the memory leak, this was done just for demonstration.
And, yes, I understand that this can be dangerous, but I'm pretty sure that you aren't supposed to do fancy things on a property getter.

**Comment by bfiete** [comment]
This is added in https://github.com/beefytech/Beef/commit/85943230b1b6afd4b429a22a2710b777246eeb80

By default Auto Property Evaluation is disabled, but there will be a hoverwatch with a button you can press to evaluate the property. There's a setting in Preferences to enable auto evaluation.
