### ISSUE TITLE
0.42.5 - IDE Crash with generic tuple

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#336]
This code crashes the IDE while building:

```
	class Program
	{
		public static bool TupleTestGeneric<K, V>((K key, V value) param1)
		{
			Console.WriteLine("Tuple: {}", param1);
			return true;
		}

		public static void Main()
		{
			TupleTestGeneric((1, 2));

			Console.WriteLine("End.");
			Console.In.Read();
		}
	}
```

**Comment by bfiete** [comment]
I didn't reproduce the crash, but I did fix the generic inference issue - this code will now actually compile. Fixed in https://github.com/beefytech/Beef/commit/3d191b6cc5324b29efc82ebb5f199129828c01fd

If you do get a crash related to this, post the crash dump.
