### ISSUE TITLE
[IDE] Hard Crash after explicitly specifying Enum type

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#339]
I have IDE crashing after i explicitly define enum type ... 
The main problem is that there is no error message. It will just crash to desktop, so i am unable to get crash dump since the crash dialog will not show.

**Version 0.42.5 (Nightly 06/10/2020)**

![vdmL12CN8V](https://user-images.githubusercontent.com/17201053/84398516-55f02380-ac00-11ea-9fcf-bcf18eee6a31.gif)

Source file: **Only via Discord DM**

**Comment by M0n7y5** [comment]
I found that crash dump file 

[BeefIDE_20200611_034520.zip](https://github.com/beefytech/Beef/files/4765493/BeefIDE_20200611_034520.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/f56667ff617ba49c734139b40ec34ebc157e89de
