### ISSUE TITLE
Go to Definition fails when instance property and method names collide

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#340]
In the example code below, if you select Go to Definition on the X(); call, it goes to the public int X definition rather than the method definition.

```
class Test
{
	public this()
	{
		X();
	}

	public int X;

	public void X()
	{

	}
}
```

**Comment by bfiete** [comment]
Fixed https://github.com/beefytech/Beef/commit/71c020c4a1df384ad5a26e56badf328ca0ccd4c4
