### ISSUE TITLE
Crash when building using CopyFilesIfNewer

### ISSUE THREAD

**Issue by DeFYzz** [beefytech/Beef#341]
Im on the latest release. If I use CopyFilesIfNewer, the IDE crashed when trying to build.
I try to copy all files from a 'resources' folder to a folder at the target directory.
Postbuild command looks like this:
`CopyFilesIfNewer("$(ProjectDir)/resources/*", "$(TargetDir)/resources/")`

**Comment by bfiete** [comment]
Can you post the crash dump?

**Comment by DeFYzz** [comment]
It does not generate one. IDE Just closes and shows nothing.

**Comment by bfiete** [comment]
There was an issue copying nested directories, fixed at https://github.com/beefytech/Beef/commit/b811f5daf81b2136617ef08de276493f80de0daf.

Will be in the next nightly build and in the 0.42.5 release.
