### ISSUE TITLE
Default font breaks text display under high-DPI

### ISSUE THREAD

**Issue by ghost** [beefytech/Beef#342]
The original state after I install and open Beef (latest nighly): 
![image](https://user-images.githubusercontent.com/34786330/84908686-5d736900-b0e7-11ea-9dd5-f80c34670e5e.png)
It fixes after switching the font to Consolas: 
![image](https://user-images.githubusercontent.com/34786330/84908832-8eec3480-b0e7-11ea-8f8f-94295a02cabc.png)

**Comment by ChlorineX** [comment]
Actually, it fixes after I change it to any other font.

**Comment by bfiete** [comment]
Fixed
