### ISSUE TITLE
Used memory text in debugger

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#343]
I know its not that useful but I like seeing the used memory chart in visual studio

**Comment by bfiete** [comment]
Hm. Technically we could do even better- we could show a per-type heap chart - the info you get from `GC.Report()`

**Comment by MineGame159** [comment]
That would be great

**Comment by bfiete** [comment]
The next nightly will have a "diagnostic panel" with a CPU graph and a few memory graphs. You can also get a per-type heap usage list.
