### ISSUE TITLE
FixIt: add "using ..."

### ISSUE THREAD

**Issue by procfxgen** [beefytech/Beef#348]
On IDE, when I use "FixIt" and "add using ..." from context menu, source code cursor jump to top of document.
Please don't move cursor, keep cursor in it's place.

**Comment by bfiete** [comment]
This is by design. Use alt+left to go back. Maybe there should be some hint popup that says that.

**Comment by xposure** [comment]
I can't think of a time I have ever wanted to go to the using statements after auto insertion. When you say by design, is that an implementation detail or a design choice?

**Comment by bfiete** [comment]
It's a design choice. When you request a change to the source code then you see that change.

**Comment by bfiete** [comment]
No "invisible" source code changes.

**Comment by NicEastvillage** [comment]
I also noticed this behaviour today. I am used to IntelliJ adding imports for me. It's not a completely "invisible" source code change as the user clicks a button and explicitly selects what to add. Maybe there should be a setting for it?

**Comment by bfiete** [comment]
Alright- I thought more about this and tried out not focusing on the change and I do think that's better. So that'll be in the next nightly build...
