### ISSUE TITLE
Impossible type inference ignored by the compiler

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#355]
IDE Version: 0.42.5 (Nightly 06/19/2020)
Build 386316654541c7c6dfc02f95df3bebb645196427

The following code will compile fine but the line with the impossible type inference will be ignored by the compiler.

```
	class Program
	{
		static void Foo<T>(T value) where T : struct
		{
			Console.WriteLine("1");
		}

		static void Foo<T>(T value) where T : class where T : new where T : delete
		{
			Console.WriteLine("2");
		}

		public static void Main(String[] args)
		{
			Foo(1);

			Foo(scope .("oi"));

			Console.WriteLine("End.");
			Console.In.Read();
		}
	}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/754b24cbd84c1b84507dbcd67fe668173731fe74
