### ISSUE TITLE
Calling a generic method with a null parameter crashes the IDE

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#359]
IDE Version: 0.42.5 (Nightly 06/19/2020)
Build 386316654541c7c6dfc02f95df3bebb645196427

This code instantly crashes the IDE:
_Btw, I just tried this to see what would happen, lol_
```
	class Program
	{
		static void Foo<T>(T value)
		{
			// nothing
		}

		public static void Main(String[] args)
		{
			Foo(null);

			Console.WriteLine("End.");
			Console.In.Read();
		}
	}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/fdc42519d88ba15923a65960a079dc3ac4cf7635
