### ISSUE TITLE
[Enhancement] Adding reflection to corelib types

### ISSUE THREAD

**Issue by Jonathan-Racaud** [beefytech/Beef#360]
Hello,

I was wondering if there was a reason the corelib types don't use the ``[Reflect]`` and ``[AlwaysInclude]`` attributes.
If there's no reason would it be possible to add them?

People such as myself working on libraries deserializing data into object could benefit from having those features. For example deserializing a Json list into a ``List<T>``. 

For the moment the only workaround that I was able to think of is to have a class inheriting from List<T> just to have a class that gives the reflection capabilities, but if every Json/Yaml/Toml/Xml or whatever define their own List type it would be unmanageable for the developer if he needs to use more than one data representation format.

I'm taking the List as an example here as it is the type I poses problem for my use case, but I think this issue can be extended for the other types as well.

**Comment by bfiete** [comment]
The reason those don't have Reflect and AlwaysInclude: if they had AlwaysInclude, then even a Hello World program would have to compile that code in. And if they had Reflect, then every program that used those types would have to carry that binary burden of reflection information.

My solution for this is to allow reflection settings at the "Distinct Build Options" level, which would allow even a library to request reflection information and "always include" for specific types - or even all types in a given namespace, or even just ALL TYPES (expensive).

**Comment by Jonathan-Racaud** [comment]
I understand that choice.

I found where we would set the "Distinct Build Options" for the project/lib and then it would be a matter of setting `Runtime checks` and/or `Object access checks` ?
![Distinct_Build_Options](https://user-images.githubusercontent.com/4101737/85289207-58bc0580-b497-11ea-918e-814c4acdc84f.png)

But it seems it is not something that is yet implemented.
Also ``System.Collections.List`` shows in red, but ``System.Collections.*`` seems to be good.

**Comment by bfiete** [comment]
Oh sorry I wasn't clear- I meant "my PROPOSED solution"! Not implemented yet.

**Comment by bfiete** [comment]
And you'd want to use `System.Collections.List<*>`

**Comment by Jonathan-Racaud** [comment]
Thanks for the clarification on the syntax. I liked your proposed solution as well.

**Comment by Jonathan-Racaud** [comment]
Thanks !
