### ISSUE TITLE
Use of unassigned local variable

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#362]
Version 0.42.5 (Nightly 06/17/2020).
Notice that the compiler does not complain that the variable str is unassigned.
Now remove any of the break words and it complains.
Shouldn't it complain either way, since break is inferred in the switch?

```
public bool DrawItem(int bItemType)
{
	bool validateItem = true;
    bool bDrawItem = false;
	String str;

    switch ( bItemType )
    {
        case 0:
        {
            if (validateItem)
			{
                str = new String();
                bDrawItem = true;
            }
            break;
        }

        case 1:
        {
			if (validateItem)
			{
                str = new String();
                bDrawItem = true;
            }
            break;
        }

        default: break;
    }
    
    if ( bDrawItem )
    {
        Console.WriteLine(str);
        return true;
    }

    return false;
}
```

**Comment by Igoorx** [comment]
The same thing is happening with the following code, and I don't even assign something to `usingNode` anywhere
![image](https://user-images.githubusercontent.com/14041768/85448919-8d01f580-b56d-11ea-89d0-d370b09dc952.png)

**Comment by bfiete** [comment]
This should be fixed at https://github.com/beefytech/Beef/commit/5b8d2ffee2290d51eb42dcaefa28e62df3e9e00e
