### ISSUE TITLE
Type inference for scope/new keyword crashes the IDE

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#364]
File Version: 0.42.5 (Nightly 06/21/2020)
Product Version: 754b24cbd84c1b84507dbcd67fe668173731fe74

The following code crashes the IDE, but if you don't use the new/scope keyword everything works as expected _(Actually It doesn't work because this is an ambiguous call but, yeah, It doesn't crash)_.
```
	class Program
	{
		struct S1 { public int x; }

		struct S2 { }

		static void M(S1 s1)
		{
			Console.WriteLine("s1");
		}

		static void M(S2 s2)
		{
			Console.WriteLine("s2");
		}

		public static void Main(String[] args)
		{
			M(scope .)

			Console.WriteLine("End.");
			Console.In.Read();
		}
	}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/6997116dc8e75258003124d267c315d9bfea1c1c
