### ISSUE TITLE
Crash while editing mixin header

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#365]
File Version: 0.42.5 (Nightly 06/21/2020)
Product Version: 754b24cbd84c1b84507dbcd67fe668173731fe74

The following code crashes the IDE:
```
                static Result<mixin ReturnMixin()
		{
			return .Ok;
		}

		static Result<void> Test()
		{
			ReturnMixin!();
			return .Err;
		}
```

![image](https://user-images.githubusercontent.com/14041768/85368980-9f931500-b502-11ea-935c-060dd83d502b.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/26205eefcd50751a0fb6df7041cfa2970cd50e4d.
