### ISSUE TITLE
IDE Crash while editing error handling

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#368]
I was editing an error handling code and the IDE Crashed when the code was as follows:
```
class Program
{
     static Result<String, char8> Test()
     {
          return .Ok("ok");
     }

     public static void Main(String[] args)
     {
          var result = Test();
          if (result case .Ok(let s)..Err())
     }
}
```

**Update:**
While trying to isolate the previous crash, I found another crash lol
The following code will also crash the IDE (with another type of crash)

```
class Program
{
     static Result<String, char8> Test()
     {
          return .Ok("ok");
     }

     public static void Main(String[] args)
     {
          var result = Test();
          if (result case .Ok(()))
     }
}
```

**Comment by Igoorx** [comment]
While trying to isolate this crash, I found another crash lol
The following code will also crash the IDE (with another type of crash)

```
class Program
{
     static Result<String, char8> Test()
     {
          return .Ok("ok");
     }

     public static void Main(String[] args)
     {
          var result = Test();
          if (result case .Ok(()))
     }
}
```

**Comment by bfiete** [comment]
Nice, a two-for-one. Fixed at https://github.com/beefytech/Beef/commit/fb5eaaa0105deacb3f7ec7e65dc42ae3c094f2d9
