### ISSUE TITLE
A generic constrained method can't call itself

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#369]
The compiler doesn't compiler the following code because `The type 'T' must be a deletable type in order to use it as parameter 'T' for 'test3.Program.Test1<T>(T value)'`
```
	class Program
	{
		public static void Test1<T>(T value) where T : class, new, delete
		{
			if (value == null)
				return;
			T i = null;
			Test1(i);
		}

		public static void Main(String[] args)
		{
			String str = scope .();
			Test1(str);

			Console.WriteLine("End.");
			Console.In.Read();
		}
	}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/40e428b2f0da2179315d01f256552346f72b0667
