### ISSUE TITLE
Array constructor using generic const parameter crashes the IDE

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#373]
Yeah, for some reason this code crashes the IDE:
_**Update:** The same crash happens if the generic parameter is from the method_
```
namespace test3
{
	class CTest1<T> where T : const int
	{
		public int Get()
		{
			int[T] o = .()
			return T;
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/92e189826b29603fb6f3a689c9c40f058e55d981
