### ISSUE TITLE
Crash when set null in FieldInfo.SetValue

### ISSUE THREAD

**Issue by kochol** [beefytech/Beef#376]
When I want to set an object field to null through Reflection it crashes.

https://github.com/beefytech/Beef/blob/71087af6d3a7897d307bf736a19ba6d272dfa25e/BeefLibs/corlib/src/Reflection/FieldInfo.bf#L69

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/e7afee67703b0fb06297abd060b3424f38eb8b91
