### ISSUE TITLE
[Suggestion] Make it possible to overload a generic unconstrained method

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#380]
When I have a generic method with `where T : struct` and a overload of it with `where T : System.Enum` and then I call it with an Enum, even through the Enum is a value type, the compiler correctly chooses the `where T : System.Enum` one.
But if I have a generic method with `where T : var` and a overload with `where T : System.Enum`, an `Ambiguous method call error` raises if I try to call it with an Enum.
My suggestion is to make the `var` case to work like the `struct` case.

**Comment by bfiete** [comment]
This should work now https://github.com/beefytech/Beef/commit/eec61a425bb2ac1369bf5a61193ba60c42ab7cfb
