### ISSUE TITLE
Copy and Paste shortcuts broken

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#385]
Selecting a word in the IDE and then right clicking to copy and paste no longer works they are greyed out keyboard shortcuts still work

**Comment by bfiete** [comment]
I can't reproduce this.

So you are right-clicking inside the selection area and the selection area doesn't disappear or anything but the popup menu just doesn't have those Copy/Cut options enabled? Presumably Paste is enabled though right?

**Comment by bfiete** [comment]
What if you drag-select and then right click? Does that work?

**Comment by bfiete** [comment]
Oh nevermind, I reproduced.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/9f3d025ab5a072dfb87ffe896b03eebf2ce6188b
