### ISSUE TITLE
[Enhancement] Hide projects in the IDE

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#390]

**Comment by bfiete** [comment]
I don't get the use case here... explain?

**Comment by RogueMacro** [comment]
So that if I have many projects like a library such as BeefGLFW, I wont’t have them flooding up the workspace. Especially since I am writing a package manager that all the dependencies can stack up quite a bit.

**Comment by bfiete** [comment]
One thing VS does is allow you to group together projects into hierarchical folders (not related to disk path). It seems that would be more generally useful.

**Comment by RogueMacro** [comment]
That would be perfect. Will I see it in a future nightly maybe?

**Comment by damianday** [comment]
Grouping dependancies under its own folder like c# does with references would be nice to have.
