### ISSUE TITLE
Cannot assign to a instanced function

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#391]
When I try to bind a member method to a function with an instance, the compiler gives an error:
`No overload for 'Put' matches function 'function bool(test3.Class1 this, int)'`

The function assignment in question is as follows:
`function bool(Class1 this, int) callInstDirect = => c.Put<int>;`

The Put is declared as follows:
`public bool Put<T>(T param1)`

_By the way, sorry if I'm not using the right terms._

**Comment by bfiete** [comment]
I don't even have a proper name for those, I call them "functions with an explicit 'this'" which isn't very elegant.

These should be working in the next nightly: https://github.com/beefytech/Beef/commit/7f726ef9ba595d27526c950e86dd818c27d30042
