### ISSUE TITLE
PSDReader calls delete on null

### ISSUE THREAD

**Issue by JamesOrson** [beefytech/Beef#393]
PSDReader.cpp contains a `dynamic_cast` followed by a delete if the value is `null`.

Is the intention that if the downcast fails, the image should be deleted?

[Source Link](https://github.com/beefytech/Beef/blob/1eaaf9510da8af52d4c0cfc86c579544197a4c2a/BeefySysLib/img/PSDReader.cpp#L1708)

Code
```c++
if (dynamic_cast<PSDLayerInfo*>(combinedImage) == NULL)
    delete combinedImage;
```

**Comment by bfiete** [comment]
The code says "if this is something besides a PSDLayerInfo then delete it".

The reasoning is that `combinedImage` will be an `ImageData` instance if a new image had to be allocate to hold the bits, so that would have to be deleted. Otherwise if it's a `PSDLayerInfo` then that's just a reference to an existing layer which will get cleaned up later.

**Comment by JamesOrson** [comment]
> The code says "if this is something besides a PSDLayerInfo then delete it".
> 
> The reasoning is that `combinedImage` will be an `ImageData` instance if a new image had to be allocate to hold the bits, so that would have to be deleted. Otherwise if it's a `PSDLayerInfo` then that's just a reference to an existing layer which will get cleaned up later.

Awesome. It seemed like it was either a type check like you are describing, or an extra complicated way of doing nothing of import. Nice to know it was the former!

**Comment by bfiete** [comment]
Cool. Anyway- nice to know someone is using this code. It was intended as part of a resource processing toolchain for gamedev but this code never made it into production. It's moderately tested and doesn't have any known bugs, though!

**Comment by bfiete** [comment]
Oh I missed the part where you aren't actually using it though- you were just looking at the actual 'delete' :-)
