### ISSUE TITLE
Implement bitfields

### ISSUE THREAD

**Issue by bfiete** [beefytech/Beef#399]
Not sure how these should work yet.

**Comment by M0n7y5** [comment]
+1

**Comment by bfiete** [comment]
For reference, here's the C# feature request for bitfields, opened 5 years ago and still not implemented: https://github.com/dotnet/csharplang/issues/465

**Comment by RogueMacro** [comment]
@bfiete Do you see this coming to Beef anytime soon?

**Comment by bfiete** [comment]
Yeah, probably within the next couple years.

**Comment by bfiete** [comment]
We have some "experimental" bitfield support- you can see an example at https://github.com/beefytech/Beef/blob/master/IDEHelper/Tests/src/Bitfields.bf

You specify a backing field, and then `Bitfield` attributes will generate properties to access bitfields within that backing variable.
No decision yet on what to do on big endian machines.

@RogueMacro @M0n7y5
