### ISSUE TITLE
Metaprogramming / Compile-time execution

### ISSUE THREAD

**Issue by bfiete** [beefytech/Beef#408]
This is a big topic and probably fairly far out. Just making an issue to track it here.

**Comment by elfring** [comment]
Would you like to avoid a typo in the subject for this issue?

**Comment by bfiete** [comment]
Thanks

**Comment by xposure** [comment]
Has anyone seen some of Jonathan Blow's work, some of his reference work can be found on youtube [here](https://www.youtube.com/user/jblow888/search?query=meta) (all though a bit of digging is required). 

I remember watching a stream of his where he had code that was executed compile-time using the same language to implement things like reflection and other cool features.

**Comment by bfiete** [comment]
That's a very powerful kind of metaprogramming -- the kind of power where someone can (and will) write a library that does a git update of itself on every compile. The IDE "code awareness" of that language will be weak among it's other statically-typed peers.

**Comment by sgf** [comment]
. Net 5 implementation of a code generator
I guess this will be a powerful technique for static reflection, compile-time calculation and other functions.

**Comment by bfiete** [comment]
sgf is referring to this: https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/
I haven't looked closely at this yet.

**Comment by C34A** [comment]
In rust using WGPU, it is possible to use and compile shaders from separate source files using macros like `incluse_str!()` or compiling them with a build script and using `incluse_spirv!()`. I'm not a graphics expert by any means, but this seems like a very convenient way to pre-compile shaders without having to deal with reading them from a file at runtime or awkwardly including them in your source code. I don't know how exactly something like this would be best done in beef, but something similar would be nice to have.

**Comment by bfiete** [comment]
Comptime added.
