### ISSUE TITLE
IDE crash with typealias

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#414]
Creating a typealias using the name of an existing structure causes a crash.
Will post an example tomorrow if needed.

**Comment by bfiete** [comment]
Yeah, you could post an example? It's not readily reproducing for me...

**Comment by damianday** [comment]
In the example change MessagePtr to Message and it should trigger the crash.
I'm using Version 0.42.5 (Nightly 07/11/2020) if that makes any diffrerence.

```
public struct Message
{
	public int Value1;
}

typealias MessagePtr = Message*;
```

**Comment by bfiete** [comment]
Ah. this is more of a "circular reference" issue...

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/6232de0aaa76b1c3c0d7bdaaefb8c0f614198995
