### ISSUE TITLE
Debug IDE Crash on static block

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#419]
![bcraash](https://user-images.githubusercontent.com/14041768/87505502-63edf580-c63f-11ea-8f78-766aeb43a2cb.gif)
[crrrrrrraaaaash.zip](https://github.com/beefytech/Beef/files/4922992/crrrrrrraaaaash.zip)

**Comment by bfiete** [comment]
Seems simple enough... but I'm still working on reproducing it with no luck so far.

**Comment by bfiete** [comment]
The absolute easiest way to reproduce it is to just sent the workspace, if you're willing.

**Comment by Igoorx** [comment]
No problem, this project will be open-source anyway, I just haven't created a repository yet because I'm still not very satisfied with the structure of the project.
[BeefSerializer.zip](https://github.com/beefytech/Beef/files/4926834/BeefSerializer.zip)

The file in question is `SerPair.bf`

**Comment by bfiete** [comment]
The issue was the conflicting `BeefSerializer.SerializeHelper` extension and the `BeefSerializer.SerializeHelper` namespace with the static block.

Should be fixed at https://github.com/beefytech/Beef/commit/37fc1a08e15598477f6f92ddffbbd43682e58303
