### ISSUE TITLE
Type.GetMethod gives different results depending on List's parameter

### ISSUE THREAD

**Issue by Jonathan-Racaud** [beefytech/Beef#425]
Hi,

When declaring a field as ``List<String>``, when using reflection I can successfully get the **Add** method by using:

```c#
// field has successfully been retrieve before and checked as being of type List
let fieldType = field.FieldType;
let addMethod = fieldType.GetMethod("Add");
```

However, when the type is declared as ``List<List<String>>`` the method cannot be found and the ``GetMethod`` method returns ``Result<.NoResults>`` even though the field has successfully been checked to be of type List before arriving at this code snippet.

Also here I'm using the new Reflect section of the Distinct Build Options as follows:
![image](https://user-images.githubusercontent.com/4101737/87913333-3524b480-ca6f-11ea-89cf-da30a6611ec0.png)

**Comment by bfiete** [comment]
Is the "Add" method directly called on that type in your code? 

You don't have the "Include All" option set on "Always Include" so only called methods will be compiled (and only compiled methods are included in reflection information)...

**Comment by bfiete** [comment]
The fact that `List<String>` works is a bit of a red herring since there are other places where `List<String>.Add` is called by the corlib.

**Comment by bfiete** [comment]
You can also use the "Method Filter" to add a list of semicolon-separated method names (name only, no arguments) if you only need specific methods like "Add", which can reduce bloat.

**Comment by bfiete** [comment]
And to clarify a bit more - if you DO you use Method Filter, the filter means "apply these settings only to these methods", meaning you still do need to set "Include All".

**Comment by bfiete** [comment]
Sweet.
