### ISSUE TITLE
Can't create variables in destructor

### ISSUE THREAD

**Issue by kochol** [beefytech/Beef#427]
When I want to create a variable in destructor it says Attempted to access deleted object

```
        class Bar
	{
		public this()
		{

		}

		public ~this()
		{
			var s = scope String("BUG");
			Console.WriteLine(s);
		}
	}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/bec6f1d007e19a7b5179ceda39e4c650a96acd07
