### ISSUE TITLE
[Bug] Post Build Commands seems to run before compilation

### ISSUE THREAD

**Issue by Jonathan-Racaud** [beefytech/Beef#429]
Hello,

I'm trying to copy the generated binary of a console app by using the following PostBuild Command: ```xcopy $(TargetPath) $(ProjectDir)\bin```. I tried with different variant: ```xcopy $(TargetDir)\$(ProjectName).exe $(ProjectDir)\bin``` but this fails as it does not find the generated .exe file. The build then fails as well:

![image](https://user-images.githubusercontent.com/4101737/88720615-6f541d00-d125-11ea-9067-9ee7d91ca65b.png)

When I remove the command or configure the project to never run the commands the compilation works.

## Steps to reproduce the error
1. Build > Clean
2. Build > Clean Beef
3. Add  ```xcopy $(TargetPath) $(ProjectDir)\bin``` to the list of PostBuild commands
4. Try and build
5. Fails

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/41485f4106e5b06d8d3f8cbaebe670b468090b66

Also xcopy will attempt to display user prompts for that command and appear to freeze.. you probably want `xcopy /y $(TargetPath) $(ProjectDir)\bin\`

**Comment by Jonathan-Racaud** [comment]
Great thanks. 

I already use the ``/y`` parameter. Just forgot to write it.
