### ISSUE TITLE
IDE 0.42.6 - Method crashes the IDE

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#430]
This code crashes the IDE:
```
		public static bool Foo<T>(ref T[][] x) where T : var, Array
		{
			return true;
		}

		public static void Main(String[] args)
		{
			var a = new int[1];
			Foo(a);
		}
```

In other circumstance just the method declaration gives another type of crash:
[d_crash_array.zip](https://github.com/beefytech/Beef/files/4996895/d_crash_array.zip)

![image](https://user-images.githubusercontent.com/14041768/88841887-f9979200-d1b4-11ea-8cd5-0ee9ea0297d2.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/fb960747ec294353cdddb9532b39d4db625497e7
