### ISSUE TITLE
Accessing property of base-class results in compilation error

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#433]
Accessing a property of the base class using the "base"-keyword results in a compilation error. 

The error can be reproduced with the following code:
```c#
class MyParentClass
{
    private float myFloat;

    public float MyFloat
    {
        get => myFloat;
        set => myFloat = value;
    }
}

class MyChildClass : MyParentClass
{
    public new float MyFloat
    {
        set
        {
            base.MyFloat = value;
        }
    }
}
```
The code generates the following error message:
"Failed to devirtualize MyParentClass.MyFloat set accessor while compiling 'MyChildClass'"

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/f9bed24c00ea0da736d51c0a37187c44a0b5a827
Will be in the next nightly.
