### ISSUE TITLE
Some issues while trying to update my code

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#434]
Hello! I was fixing some issues of my code and I got a bunch of crashes and errors.

## Issue 1
I tried to follow the advice that Beefy gave me to move the constraint from a method to the extension declaration but I have got this compiler error:
```
ERROR: Cannot find generic parameter in constraint at line 3:28 in d:\BeefLang\test3\src\BugTest2.bf
 extension Array1<T> where bool : operator T == T
                           ^^^^
```

**Reproduction code**:
```
extension Array1<T> where bool : operator T == T
{
}
```

## Issue 2
I tried to change the generic parameters of the Array1 extension but I have got this crash:
[crash_constraint.zip](https://github.com/beefytech/Beef/files/5023016/crash_constraint.zip)

**Reproduction code**:
```
extension Array1<T, b>
{
}
```

## Issue 3
While trying to get the above crash on the Debug IDE, I have got this crash on the project opening:
[d_crash_crash.zip](https://github.com/beefytech/Beef/files/5023008/d_crash_crash.zip)

**How to reproduce**:
Sorry, I don't know how to reproduce this as this isn't happening anymore.

## Issue 4
As using the constraint in the extension declaration wasn't working, I tried to use it in the method declaration anyway, It worked fine for the Array1 extension, so I tried the following in the `Dictionary.operator==`
```
public static bool operator==(Self lhs, Self rhs) where bool : operator K == K, operator V == V
```
But I have got a hard crash while trying to compile it:
[BeefIDE.exe.24296.dmp.zip](https://github.com/beefytech/Beef/files/5023167/BeefIDE.exe.24296.dmp.zip)
(Funnily enough, after reopening the IDE, It compiled successfully)

**How to reproduce**:
Sorry, I don't know how to reproduce this as this crash seems to be quite random.

## Issue 4.1
When the Dictionary extension declaration was like this:
```
extension Dictionary<K, V> : IOpEquals
```
First I have got this crash:
[crash_IOpEquals.zip](https://github.com/beefytech/Beef/files/5023220/crash_IOpEquals.zip)
 
After reopening the IDE I got these `unresolved external symbol`
```
corlib__.lib(System_Collections_Dictionary_System_String_System_Collections_Dictionary_System__.obj) : error LNK2019: unresolved external symbol "public: static int bf::System::IOpEquals::sBfSlotOfs" (?sBfSlotOfs@IOpEquals@System@bf@@2HA) referenced in function "protected: virtual class bf::System::Object * __cdecl bf::System::Collections::Dictionary<class bf::System::String *,class System::String::Collections::Dictionary<class bf::System::String *,union int> *>::DynamicCastToInterface(int)" (?DynamicCastToInterface@?$Dictionary@PEAVString@System@bf@@PEAV?$Dictionary@PEAVString@System@bf@@Tint@@@Collections@12@@Collections@System@bf@@MEAAPEAVObject@34@H@Z)
corlib__.lib(System_Collections_Dictionary_System_String_int.obj) : error LNK2001: unresolved external symbol "public: static int bf::System::IOpEquals::sBfSlotOfs" (?sBfSlotOfs@IOpEquals@System@bf@@2HA)
corlib__.lib(System_Collections_Dictionary_int_System_Collections_List_BeefSerializerTests_SS__.obj) : error LNK2001: unresolved external symbol "public: static int bf::System::IOpEquals::sBfSlotOfs" (?sBfSlotOfs@IOpEquals@System@bf@@2HA)
corlib__.lib(System_Collections_Dictionary_int_System_String.obj) : error LNK2001: unresolved external symbol "public: static int bf::System::IOpEquals::sBfSlotOfs" (?sBfSlotOfs@IOpEquals@System@bf@@2HA)
```

In the debug IDE I have got this crash:
[d_crash_kind.zip](https://github.com/beefytech/Beef/files/5023675/d_crash_kind.zip)

**Reproduction code**:
```
namespace System
{
		extension Dictionary<K, V> : IOpEquals
		{
			public static bool operator==(Self lhs, Self rhs) where bool : operator K == K, operator V == V
			{
				if (lhs.mCount != rhs.mCount)
					return false;
				for (var kv in ref lhs)
				{
					if (rhs.TryGetValue(kv.key, var rhsVal))
					{
						if (!(*kv.valueRef == rhsVal))
							return false;
					}
					else
						return false;
				}
				return true;
			}
		}
}
```

##
Here is the file that had all these issues:
[Extensions.txt](https://github.com/beefytech/Beef/files/5023266/Extensions.txt)

**Comment by bfiete** [comment]
There's a lot of things here all at once. Which of these individually reproducible?

**Comment by Igoorx** [comment]
@bfiete I edited the issue to make it (perhaps) more organized and to clearly show how to reproduce the problems.

**Comment by bfiete** [comment]
#1 and #4.1 fixed by https://github.com/beefytech/Beef/commit/c3bc2bc67c668c14016505a906ede4a3338eb9e2

**Comment by Igoorx** [comment]
#1 is now crashing my IDE:
![image](https://user-images.githubusercontent.com/14041768/89724849-7826d780-d9de-11ea-9c61-0654ad244b40.png)
[d_crash_asib.zip](https://github.com/beefytech/Beef/files/5046761/d_crash_asib.zip)

Code used:
```
namespace System
{
	extension SizedArray<T, CSize>
	{
		public static bool operator==(Self lhs, Self rhs)
		{
			if (lhs.Count != rhs.Count)
				return false;
			for (int i = 0; i < lhs.Count; i++)
				if (!(((T[CSize])lhs)[i] == ((T[CSize])rhs)[i]))
					return false;
			return true;
		}

		public mixin Transform<Input, Output>(var predicate)
		{
			Output[] output = scope:mixin Output[Count];
			for (int i = 0; i < Count; i++)
				output[i] = predicate(((T[CSize])this)[i]);
			output
		}
	}
}
```

**Comment by bfiete** [comment]
Thanks- the code was very useful. I think I've reproduced and resolved all these now.

Also note that the sized-array Put (incorrectly) allowed taking the address of the array being passed in. This works now though:
```C#
public bool Put<T, U>(T[U] x) where U : const int
{
	Debug.Assert(U <= 0xffffffff);
	var x;
	return PutArray((T*)&x, U);
}
```

Because values are passed immutably and (potentially) non-addressably. The `var x` semantically makes a copy, but that copy will be optimized away in the backend.

**Comment by Igoorx** [comment]
Thank you, everything seems to be working fine now! 👍
