### ISSUE TITLE
Compiler stuck compiling project

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#439]
After some changes that I did to my project, when I try to compile my project the compiler phase never ends, I waited a long time to see what would happen and the IDE crashed:
[BeefIDE.exe.23900.dmp.zip](https://github.com/beefytech/Beef/files/5064252/BeefIDE.exe.23900.dmp.zip)
(Strangely, the crash doesn't seem to happen in the Debug IDE)

My project folder:
[BeefSerializer.zip](https://github.com/beefytech/Beef/files/5064259/BeefSerializer.zip)

IDE version:
0.42.6 (Nightly 08/12/2020)

**Comment by bfiete** [comment]
When did you install the nightly? There was a bad built last night that I just updated a few hours ago.

**Comment by bfiete** [comment]
Nevermind, just reproduced.

**Comment by bfiete** [comment]
It's looking like an LLVM issue, maybe a bug in LLVM... If you switch the workspace Optimization Level to Og+ then it works. Continuing investigation..

**Comment by bfiete** [comment]
LLVM's has issues with stores to large aggregates, and SSerializable was triggering some of those issues. Those are now emitted as memcpy/memset. Fixed in the next nightly.
