### ISSUE TITLE
IDE Request: allow mouse forward and back buttons to be used for navigation

### ISSUE THREAD

**Issue by MoshiBar** [beefytech/Beef#441]

**Comment by xposure** [comment]
I would add to this to have proper `ctrl+tab` support. Its not as simple as going forward and backwards on the tabs. If you use something like vscode and vscommunity, ctrl+tab will go back and forth between 2 documents which is good for making quick edits. It keeps a history of the order you accessed the tabs.

I have also become quite acustom to the mouse forward and back buttons which I believe are the same as `alt+left arrow` and `alt+right arrow` but sometines the `alt+left arrow` doesn't do what I expect in my normal code flow.

**Comment by xposure** [comment]
https://github.com/beefytech/Beef/issues/220

**Comment by bfiete** [comment]
@xposure If you have concrete examples where alt+left doesn't do what you expect then that's worth reporting.

**Comment by bfiete** [comment]
@xposure Yeah, ctrl+tab seems good. I use alt+w+2 a lot myself for toggling between two documents, but ctrl+tab is better.

**Comment by bfiete** [comment]
@xposure Ctrl+Tab support has been added @ https://github.com/beefytech/Beef/commit/6511d6a8451426a6a40cb418f52a39c810b0ea27
