### ISSUE TITLE
IDE for mac OSX

### ISSUE THREAD

**Issue by rakista112** [beefytech/Beef#443]
Hi, I'm interested in Beef but there doesn't seem to be an IDE for OSX.

I got to build the source and run the compiler but I would like to make development faster by using an IDE.

Are there plans or ongoing projects for the OSX IDE? 
Could the CLI tools be integrated into Visual Studio Code, Atom, or Sublime?

I'm willing to contribute.

Thanks

**Comment by bfiete** [comment]
There has been some interest in this, particularly in a VSCode LSP. It's even mentioned in the FAQ @ https://www.beeflang.org/docs/faq/

I'm not aware of anyone having started any work on it, however.
