### ISSUE TITLE
Request: Get file path and line number

### ISSUE THREAD

**Issue by kochol** [beefytech/Beef#444]
I want something like System.Runtime.CompilerServices.CallerFilePath in C# or __FILE__ and __LINE__ in C to assign to my functions.

They are very good for the logger class

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerlinenumberattribute?view=netcore-3.1

**Comment by xposure** [comment]
I'd like to also add that something of a HASHCODE of the file and or line number would be good too. This can be handy as when implementing soemthing like IMGUI where the ID is generated by the filename and line number. I suppose if the string is stored in readonly memory you could just grab the memory address for the ID and skip the hashcode portion.

**Comment by xposure** [comment]
https://github.com/beefytech/Beef/issues/407

**Comment by kochol** [comment]
I think it is better to have an option to calculate them in compile-time like constexpr functions in C++

**Comment by bfiete** [comment]
Implemented at https://github.com/beefytech/Beef/commit/25f44ae133e9606ba0dc4da94efe85e87aa7c022
It's different than C#. Example:
```C#
public static void Assert(bool condition, String error = Compiler.CallerExpression[0], String filePath = Compiler.CallerFilePath, int line = Compiler.CallerLineNum) 
```

**Comment by kochol** [comment]
Thank you it's better than C#
