### ISSUE TITLE
IDE Suggestion: Prevent add using from scrolling to top

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#446]
When adding a using statement with `ctrl+.` the IDE will scroll up to where the using statement was added forcing you to have to scroll back down.

**Comment by bfiete** [comment]
This was discussed here: https://github.com/beefytech/Beef/issues/348

**Comment by xposure** [comment]
Ahh sorry I missed this when searching. I'l close it.

**Comment by bfiete** [comment]
The fixit will no longer scroll to the top (in the next nightly).
