### ISSUE TITLE
ToString with NumberFormatInfo wrong result

### ISSUE THREAD

**Issue by Jonathan-Racaud** [beefytech/Beef#449]
Hi, I'm trying to call the ``ToString`` method on a float to have its String representation with a certain numbers of digits after the decimal point. I'm calling it like this:

```
let numStr = scope String();
let numInfo = scope NumberFormatInfo();
numInfo.NumberDecimalDigits = 10;

num.ToString(numStr, "N", numInfo);
```

At one point it arrives in the method ``NumberFormatter.GetNumberFormatInstance(IFormatProvider fp)``, but the variable ``fp`` is never used:

```
// Inside NumberFormatter.bf
static NumberFormatInfo sDefaultNFI = new NumberFormatInfo() ~ delete _;

private NumberFormatInfo GetNumberFormatInstance (IFormatProvider fp)
{
    /*if (_nfi != null && fp == null)
        return _nfi;
	return NumberFormatInfo.GetInstance (fp);*/
    return sDefaultNFI;
}
```

Actually from what I understand of the code from the call to ``ToString``, the FormatProvider asked as parameter is never actually used.

**Comment by bfiete** [comment]
That's implemented now at https://github.com/beefytech/Beef/commit/20cbac3155663dbf53d585d26d9516da4345ccfb

But also you could just do
```C#
num.ToString(numStr, ".000000000", null);
```
or
```C#
numStr.AppendF("{:.0000000000}", num);
```
