### ISSUE TITLE
DllMain is impossible to use in dlls

### ISSUE THREAD

**Issue by LoopyAshy** [beefytech/Beef#450]
As the title says: if you include DllMain with its correct layout it will never be used, most of the time it won't even be included in the dll at all. if you try to force this via [AlwaysInclude] it will proceed to give a error every time claiming DllMain has already been defined in that obj file, this will only happen in the main file of the program.
this is quote annoying to be honest and hope I am just doing something wrong.

thank you and hope this helps either you or me.

**Comment by bfiete** [comment]
DllMain is implemented for you when you create a DLL. It is responsible for calling your static constructors on load and destructors on unload. You cannot directly override it.

**Comment by LoopyAshy** [comment]
In that case how to I extend it with my own code?

**Comment by LoopyAshy** [comment]
Nevermind I figured it out via adding a static constructor to the main class, I do think this however needs to be made clearer as I could not seem to find any information regarding this, thank you for your help regardless

**Comment by bfiete** [comment]
Currently when compile as a DLL then you don't get a "Main" method called, but I think that's wrong - I'm going to change it so you still get a Main method called at load time, which allows you to do initialization without creating static constructors.

**Comment by LoopyAshy** [comment]
As long as you make methods for both loading and unloading, I think it will be helpful and much clearer (and an example should also be within the documentation to assist people like myself learning the language), as now I figured out how it is currently implemented it is not too bad at all, but I am a sucker for loving easy to use implementations but also liking having the option if I say please to change whatever I need.

one last thing is: as a long term .NET programmer I do admit the documentation although simple and gets straight to the point does not feel like it has enough examples for new users, which is example here as the documentation does tell me about [Export] and [Import(*)] etc but it does not give any examples of it in use, which requires users to figure it out themselves via reading code in corlib or guessing.
