### ISSUE TITLE
IDE Suggestion: Allow dot in the project name

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#451]
Coming from C# and .NET, every single project I have will have a `DOT` in it because the project name usually follwes the namespacing conventions.

**Comment by bfiete** [comment]
Project naming restrictions have been related @ https://github.com/beefytech/Beef/commit/4d55a32c90838c07be562377934c416993127946
There was also a general decoupling of project name from project directory name (even for installed libraries), so you can even name your project with characters that aren't legal in the file system.
