### ISSUE TITLE
IDE Suggestion: Drag and drop files

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#452]
And possibly auto-move them into their new namespace? For example, if I move `ExampleClass` from `src/ExampleClass.bf` to `src/Example/ExampleClass.bf` it moves it changes `namespace MyProject` to `namespace MyProject.Example`. This would not need to be done every time but maybe a popup of some sort or something like that?

**Comment by LoopyAshy** [comment]
I do agree the ide needs drag and drop for the folder structure, I am not too surely about the automatically renaming namespaces around the change part however, however as a refactoring option it could very well have its place.

**Comment by RogueMacro** [comment]
Yeah, or as a refactoring option. At long as it's there and I don't have to edit many files

**Comment by RogueMacro** [comment]
@bfiete Update on this? File dragging in the IDE.

**Comment by bfiete** [comment]
As noted at https://github.com/beefytech/Beef/issues/521

Files can now be moved within a project.

**Comment by RogueMacro** [comment]
I guess this issue can be closed then
