### ISSUE TITLE
How to bind c/c++ code in runtime 

### ISSUE THREAD

**Issue by Sokharev** [beefytech/Beef#453]
Hello, thank you for great language!
Is there any method exists to bind c code in 'mono' manner like mono_add_internal_call (const char *name, gconstpointer method)
( for example :  mono_add_internal_call ("MyApp.Services.ScriptService:Slowdown(int,bool)", mySlowdownHandler); )
therefore any (non static) methods from bf class will be mapped directly c function?

**Comment by bfiete** [comment]
You can just statically link to C code, and you can directly pass around C function pointers.

Beef is not an embedded runtime, it's a statically compiled language.
