### ISSUE TITLE
Fatal error: Failure during codegen

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#46]
Attached crash dump below
[crash.zip](https://github.com/beefytech/Beef/files/4196067/crash.zip)

Happens when I run the Normal Test, the culprit is when I changed msg from'var' to 'let' in 'TestTagCount', otherwise compiles successfully.

```
                using System;

                public static int TagCount(StringView source, char32 value)
		{
			var count = 0;
			if (source.IsEmpty == false)
			{
				for (var ch in source)
					if (ch == value)
						count++;
			}
			return count;
		}

                [Test]
		public static void TestTagCount()
		{
		    let msg = "message";

		    Test.Assert(2 == Utility.TagCount(msg, 'e'));
		    Test.Assert(1 == Utility.TagCount(msg, 'a'));
		}
```

**Comment by bfiete** [comment]
Thanks.
Fixed in https://github.com/beefytech/Beef/commit/2b0f7fb4858df13bd9e0599bc14e2226010959f0. Will be in release 0.42.2.
