### ISSUE TITLE
[Question] Debugging Working Directory

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#461]
What is the purpose of the setting Debugging Working Directory? It seems that there isn't a way to change the `System.IO.Directory.GetCurrentDirectory()` location without changing the Target Build Directory.

Shouldn't working directory by default be set to `$(BuildDir)` instead of `$(ProjectDir)` and debugging working directory should be the path used as the relative path for all System.IO?

**Comment by bfiete** [comment]
I'm not sure I completely understand the question, but the reason the working directory is set to $(ProjectDir) is because the $(BuildDir) only houses temporary files and the actual executable. When you "clean", that directory gets completely deleted. 

As a default working directory, that directory isn't very useful but the project directory may be. Thus the default.

I don't understand the rest of your question though.

**Comment by xposure** [comment]
Let me try to clarify.

When you run an application `System.Directory.GetCurrentDirectory(String)` is set to the `$(BuildDir)` or I guess more importantly its set to where the executable is running from. If I wanted to change this to something else like `$(PorjectDir)\dist` for example (see SpaceGame) I have to change the target build output.

The SpaceGame example changes its build output from `$(BuildDir)` to `$(ProjectDir)\dist` so that it can easily relative load the assets. Wouldn't it make more sense to keep the build output to `$(BuildDir)` and set the Debugging Working Directory to `$(ProjectDir)/dist` so that your build isn't polluting the dist folder and `System.Directory.GetCurrentDirectory() == DebuggingWorkingDirectory`.


Last but not least, in c# if you were to set the `WorkingDir` in the project and then execute the project from the IDE `System.Enviroment.CurrentDirectory` would be equal to your WorkingDir and not the executable startup directory.

**Comment by bfiete** [comment]
SpaceGame explicitly sets the working directory to the directory of the executable in SDLApp.Init. At startup the working directory is set to the value in the debugger settings but then the app itself changes it.

**Comment by bfiete** [comment]
This is how SpaceGame finds its resources regardless of where the current working directory is when the user executes it.

The are other solutions, it's just the way that app is implemented and the way I like to do things.

**Comment by xposure** [comment]
Ah, I see now, I was looking for this because I assumed WorkingDir would work like I'm describing above. So due to SDLApp.Init on line 109 its changing the CurrentDirectory, is it possible to change SDLApp.Init to grab the CurrentDirectory and then restore it before it returns from Init or would this have other side effects later down the road?

Alternatively I can grab the path prior to SDLApp.Init for my own ContentManager.

**Comment by bfiete** [comment]
SDLApp could also be changed to optionally not change the working directory - perhaps providing a virtual method for setting up the initial working directory that could be overriden. Or some app flags that could be changed or something.

**Comment by bfiete** [comment]
But anway- no, there are no side effects for changing the working directory. SDLApp is just meant to be a simple example of a way to use SDL and that was just a simple default behavior.

**Comment by xposure** [comment]
Just to note here, I did verify that its wokring as expected. I just used a static ctor to grab the current directory and create my content path here. I'll leave the discussion/debate up to someone else if SDL should be changed, but it would be helpful to have libraries with minimal side effects the the runtime.
