### ISSUE TITLE
[BUG] Type could not be found

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#463]
I was adding this to my project to test https://github.com/qzole/imgui-beef

WorkSpace looks like this with dependencies

Workspace
|- Game (Windows App) 
|-- CommonLibrary
|--- References all imgui + sdl libs

Since the common library has imgui + sdl as dependencies, this auto checks them as dependencies for Game project too, but inside the game project I get the following error trying to reference anything imgui even though the project builds and runs correctly.

![image](https://user-images.githubusercontent.com/6292318/92155535-8c9b9b80-edf5-11ea-85b8-2e99d1fdd3d4.png)

![image](https://user-images.githubusercontent.com/6292318/92155566-94f3d680-edf5-11ea-8830-0a0ce5adf52a.png)

Also, ignoring the typealias, auto complete does not bring anything up with imgui either.

**Comment by bfiete** [comment]
The most useful thing, of course, would be if you could attach a workspace that reproduces the issue here...

**Comment by xposure** [comment]
The problem does persist after closing and opening. I will hopefully prepare an exampe tomorrow.

**Comment by xposure** [comment]
Not reproducible in the lastest nightly now.
