### ISSUE TITLE
IDE does not show which Debug.Assert() failed

### ISSUE THREAD

**Issue by NicEastvillage** [beefytech/Beef#464]
Maybe I just missed it, but the assert-failed popup does not tell me which assertion failed.

When a `Debug::Assert` fails and you press F5 again the IDE takes you to `Debug::Assert`'s implementation. Ideally, it should take you to the failed Assertion, i.e. the call to `Debug::Assert`.

This issue might depend on #407

**Comment by cphillips83** [comment]
I believe though you should be able to go to the thread window which will be broke on the current thread that threw the assert and then look at the call stack. Its not ideal but a few times I had to do something similar.

**Comment by bfiete** [comment]
This is implemented @ https://github.com/beefytech/Beef/commit/25f44ae133e9606ba0dc4da94efe85e87aa7c022
