### ISSUE TITLE
[IDE] Move line up and down

### ISSUE THREAD

**Issue by NicEastvillage** [beefytech/Beef#465]
Some editors allow the user to move a line up or down (swap the line with the one above/below). The keyboard shotcut is a bit different from editor to editor. I suggest `ctrl+shift+up/down`.

A related feature would be the ability to move elements up and down. In IntelliJ, `alt+shift+up/down` can be used to swap the order of functions, properties, statements, and more.

**Comment by bfiete** [comment]
Mm, I like the idea of moving methods around like that.

**Comment by NicEastvillage** [comment]
It's super handy for reorganizing the inners of your classes/structs!

**Comment by bfiete** [comment]
These have been implemented and will be in the next nightly build.
