### ISSUE TITLE
[Enhancement] Specify optional method parameters explicitly by name

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#466]
I want to be able to do something like this when calling a method: `MyMethod(param1: 420, param2: "KoalaBear");` or `MyMethod(param1 = 420, param2 = "KoalaBear");`

**Comment by blat-blatnik** [comment]
Bump.

I would also really like this feature. In C# this is called [Named Arguments](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments#named-arguments). And it can make method calls with a lot of optional parameters a lot clearer.

**Comment by bfiete** [comment]
Added at 79320652e34681887bc32c73f8e948eac22a2190
