### ISSUE TITLE
[Enhancement] BeefIDE crash + auto launch recent project

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#467]
I've been having issues with the IDE crashing quite frequently. Most of the time its not random and a easily reproducible action that you just have to work around to stop the crash until there is a nightly fix. 

It would save some time if we could either auto relaunch the IDE when it crashses like some other IDEs do or add an additional button to the crash window to close and relaunch. It would also be helpful if it relaunched the same project you were on.

**Comment by bfiete** [comment]
Are there crashes you haven't reported?

**Comment by xposure** [comment]
There have been 4 or 5 when I first started using this messing around, off the top of my head these were some I have expereinced so far, not all were reported.

- Crashing when adding using statement from `ctrl+.`. This became extremely problametic when I generated a large number of vec classes and the code generation was messing a using statement. Rather than fixing the generator I was going through each error line and fixing them. About every 3-4 it would crash, but it was a delayed crash, I could ctrl-s quickly prior to it crashing.
- More recently mouse back crashed, again probaly related to auto generated files. I overwrite these files a lot outside of the editor.
- I've had crashes when removing projects
- I've had crashed when deleting files, sometimes they wouldn't appear to remove and on 2nd attempt it would crash (not always)

I know there are a few more that I'm forgetting, but in general I think this would be a helpful addition

**Comment by bfiete** [comment]
When you get those crashes, make sure to report those here with the crash report. None of those are known issues at this time.

**Comment by xposure** [comment]
Yep, I started reporting everything on discord last week. So far, everything I have actually reported has already been fixed, unfortuately some of those weren't reported prior.

**Comment by xposure** [comment]
Circling back to this, I still face a number of crashes a day, while they are usually fixed quickly, this could still save some time.

I also wanted to entertain the IDE of possibly doing something like VS or VSCODE where when you relauch the IDE there is an option to recover files. I have lost some work recently due to the crashes and I find my safe ctrl+shft+s on almost every change now.

**Comment by bfiete** [comment]
Yaeh, I agree.

**Comment by bfiete** [comment]
Crash 'Relaunch' added at https://github.com/beefytech/Beef/commit/a215bac75538fd9cd987974df69a56b25149fd68
Working on file recovery.

**Comment by bfiete** [comment]
Okay, now we have file recovery at https://github.com/beefytech/Beef/commit/b975acb7110d2175f87da44f7e503473ec858ee1
There's a "recovery" directory under the workspace that contains the recovery files and a recovery index. When opening a workspace after a crash, any unsaved files will be shown opened with the recovered contents applied as a file modification (you'll see a * by the file name like normal unsaved files). You can hit undo to undo the recovered changes, even.

The system uses hashes to verify that the recovered changes apply to the correct saved file. If the saved file has changed (ie: updated from git or externally modified) then the recovered changes will not be applied. Recovered files will main in the recovery directory for one week, however, so they can be manually viewed/recovered if necessary.

Oh- and the file recovery even remembers where your actual cursor position in that unsaved file. This should actually be very helpful for reproducing crashes during typing.
