### ISSUE TITLE
[Enhancement] Close all + close all but this window

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#469]
Under the `window` menu we have close all, could we add this to the window management icon on the right too?

![image](https://user-images.githubusercontent.com/6292318/92516163-cb10cc00-f1e2-11ea-8c0b-fde9a31444ee.png)

Additionally, when right clicking the document tabs, a `Close`, `Close All`, `Close all but this` could be helpful too.

**Comment by bfiete** [comment]
Added at https://github.com/beefytech/Beef/commit/8d934192c07abb7462d2900ad0e25747f33e1d8a
