### ISSUE TITLE
[Bug] IDE crashed on mouse back/alt+left arrow

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#470]
[back-mouse-button.zip](https://github.com/beefytech/Beef/files/5190448/back-mouse-button.zip)

As reported on discord, this may have been related to auto generating source files outside of the IDE and using the back mouse button. I can't say for sure.

**Comment by xposure** [comment]
[crash-on-mouseback.zip](https://github.com/beefytech/Beef/files/5197754/crash-on-mouseback.zip)

Here is another.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/0b7edafd73d1ecb4c9eb720f7cb4c1772683c6b6
