### ISSUE TITLE
[Bug] Rename symbol (namespace)

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#472]
I used `Rename Symbol` to rename my namespace from `BGF` to `GameLib` and statements that used the full namespace path were not renamed, for example:

![image](https://user-images.githubusercontent.com/6292318/92615439-1b436900-f28b-11ea-99a6-9b8c74a9c0ab.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/569d121c14997f16362e7fc33985e0191e90bc28
