### ISSUE TITLE
[Bug] Crash on auto complete for adding using statement

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#474]
Hit `ctrl+.` to bring up the auto complete dialog so I could select add missing using statement but before the dialog even opened it crashed.

[crash-on-closedocument.zip](https://github.com/beefytech/Beef/files/5196358/crash-on-closedocument.zip)

**Comment by bfiete** [comment]
Did you put the wrong file here? This is the file from https://github.com/beefytech/Beef/issues/473

**Comment by bfiete** [comment]
Found the right one in Discord.
Fixed at https://github.com/beefytech/Beef/commit/c34e6fe66a082167f8dceeed0a0635ca9078d554
I'm curious what was on the line of code that actually caused this crash.
