### ISSUE TITLE
Some crashes in latest build

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#477]
I encountered some crashes while testing some things and decided to create one issue only as they are really easy to reproduce and they occurred in a short period of time, here they are:

**Crash 1:**
_Happens as soon as the below code is in a namespace_
```
class Anan<T>
{
  private function Anan<T>(int) OnAnan;
}
```

~~**Crash 2:**~~ **(fixed)**
~~_Happens when you hover the `while` of the below code_~~
```
public class Test
{
    public void Test()
    {
        lock (foo)
        {
            while (foo[write]?.bar)
                foobar = true;
        }
    }
}
```

**Crash 3:**
_Happens as soon as the below code is in a namespace_
```
public class Test
{
	public void Test2(delegate void<int>)
	{
	}
}
```

**Comment by bfiete** [comment]
I'm having trouble reproducing Crash 2. Can you post a crash dump?

**Comment by Igoorx** [comment]
> I'm having trouble reproducing Crash 2. Can you post a crash dump?

I'm sorry for wasting your time, the 2nd crash actually was from a previous build and I just assumed that it was still occurring in the latest build. I just tested it and it is fixed.

**Comment by bfiete** [comment]
#1 fixed at https://github.com/beefytech/Beef/commit/947426b3846e49bcb88e13d1a793aae42f7ba262
#3 fixed at https://github.com/beefytech/Beef/commit/a852bdb8cc4afaa844ed856653a062f9a9d8c9b2
