### ISSUE TITLE
[Enhancement] Auto-property default values

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#478]
Default values for auto-properties is really useful, I think Beef should support this too as it already supports auto-properties.

Example:
```
public GameState State { get; private set; } = GameState.Invalid;
```

([More](https://www.kunal-chowdhury.com/2014/11/csharp-6-auto-property.html))

**Comment by damianday** [comment]
Seems like a useful enhancement

**Comment by sgf** [comment]
public int Version => 10;

**Comment by Igoorx** [comment]
> public int Version => 10;

This code doesn't do the same thing, in this code everytime that you call the Version getter a new int will be created and returned.

**Comment by bfiete** [comment]
sgf is correct in the sense that making an auto-property with no setter that is initialized to a constant value is functionally equivalent to just returning that constant. I'd consider that a valid optimization.

But yeah, if you were doing that you might as well just do `public const int Version = 10;` of course

**Comment by Igoorx** [comment]
You're right, this was just a poor example, I will change the example to something that can benefit from this kind of feature.

**Comment by bfiete** [comment]
Supported at 041a17cf894191c42895d86d86d17c90fb79ced6
