### ISSUE TITLE
Compiler segfault on allocation of array of empty struct

### ISSUE THREAD

**Issue by lukpank** [beefytech/Beef#48]
The following program segfaults compiler (it triggers assertion `irValue.mId >= 0` in `BfIRBuilder.cpp` line 1704 when runnig `BeefBuild_d` at commit 2b0f7fb). When replacing `scope S[1]` with `scope S[0]` another assertion is triggered.

```csharp
using System;

namespace Issue
{
	public class Program
	{
		public static int Main(String[] args)
		{
			scope S[1];
			return 0;
		}
	}

	struct S
	{
	}
}
```

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/6dd49f5d9b8c99c1390030135fd95240ffda1b92, will be in release 0.42.2.
