### ISSUE TITLE
[BUG] Persistent crash

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#481]
[crash_while_typing.zip](https://github.com/beefytech/Beef/files/5220183/crash_while_typing.zip)

**Comment by xposure** [comment]
I was writing some code and added  `using statis System.Diagonstics.Debug;` and then further down I went to type `Assert(!` and on `!` the IDE crashed.

**Comment by xposure** [comment]
Editing the `Assert(!)` line outside of the IDE stopped the crash.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/11b9463fcde99deb5cfaa41e8438797636381ac4

It's a high impact bug introduced at https://github.com/beefytech/Beef/commit/25f44ae133e9606ba0dc4da94efe85e87aa7c022, and unfortunately made it into the last official build. That will necessitate a new build very soon.
