### ISSUE TITLE
[BUG] Crash when closing debug session

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#482]
I was testing something and closed the game window (sdl2 window) while debugging to change some code and the IDE crashed.

[closed-debugging.zip](https://github.com/beefytech/Beef/files/5221268/closed-debugging.zip)

**Comment by bfiete** [comment]
This actually looks like the same bug from here https://github.com/beefytech/Beef/issues/483 - it's the Ctrl+Tab handler here

**Comment by bfiete** [comment]
Any chance this was somehow the wrong crash dump, or that you actually did hit ctrl+tab here?

**Comment by xposure** [comment]
Looks to be the correct file to me, I could have just hit ctrl-tab quickly and not recondized.

**Comment by bfiete** [comment]
If it's the right file then it is the same (fixed) bug.
