### ISSUE TITLE
[BUG] Ide crashed while debugging and hitting ctrl-tab

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#483]
I hit ctrl+tab (with only a single document open) while I was debugging but had the IDE focused. 
[ctrl-tab.zip](https://github.com/beefytech/Beef/files/5221283/ctrl-tab.zip)

**Comment by xposure** [comment]
Can reproduce this by opening my project up and simply hitting ctrl+tab with a single tab open.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/4713f5528b2f18df6b3c1344afd8fe0f9cef5389
