### ISSUE TITLE
[bug] struct + operator bug

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#484]
This bug doesn't occur at the last major release, only on the latest nightly build. This is built with LLVM in workspace settings btw.

```
public static int Main(String[] args)
{
	Rect r = .(20, 20, 40, 40);
	Point p = .(30, 30);
	r = r + p;

	String str = scope .();
	r.X.ToString(str);
	Debug.WriteLine(str);

	return 0;
}
```

Output result is random garbage.  The Rect + Point operator is what you'd expect, see attached workspace.

[Repro.zip](https://github.com/beefytech/Beef/files/5221374/Repro.zip)

**Comment by bfiete** [comment]
Thanks for the nice repro. This issue was fixed earlier today at https://github.com/beefytech/Beef/commit/702eee993c23513a43c7831d379989957c6c5a2d. The next nightly build will include that fix.
