### ISSUE TITLE
[BUG] Hard crash with auto complete (no dump)

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#485]
When I try to autocomplete `List<T>` and then select `add using` IDE hard crashes without a dump.

```
namespace GameLib
{
extension List<T> where T : IOpComparable
	{
	    public T GetMax()
	    {
	        if (mSize == 0)
	            return default;
	        T max = this[0];
	        for (let val in this)
	        {
	            // This '>' check would fail without the IOpComparable constraint
	            if (val > max)
	                max = val;
	        }
	        return max;
	    }
	}
}

```

**Comment by xposure** [comment]
Its not just autocomplete. When you try to type `using System` it then hard crashes too.

**Comment by xposure** [comment]
Most likely related, so I'll add it here. I tried to clean this up and couldn't get intellisense so I attempted to build to determine what the errors were actually and IDE has just hanged while building.

![image](https://user-images.githubusercontent.com/6292318/93144861-0286e900-f6b9-11ea-959c-5db5c3d117c9.png)

**Comment by bfiete** [comment]
Hm, this is not readily reproducing for me. Does it happen if you try it in a new clean project?

**Comment by xposure** [comment]
No, just tested it.

**Comment by bfiete** [comment]
Windows Error Reporting is disabled by default on Windows 10 - applications with stacks overflows will just "disappear". 

Here's what you can do (optional): edit the "WER.reg" from https://github.com/beefytech/Beef/tree/master/bin, and set the "DumpFolder" to some folder that you want to put crash dumps on your computer. Then import the WER.reg file into your registry (ie: double click on it in Windows). When you get another one of these crash dumps you should see an actual dialog and then there will be a crash dump you can send...

**Comment by xposure** [comment]
I've added it, not sure that I can get the code back in the state to try to reproduce it though.

**Comment by xposure** [comment]
[BeefIDE.exe.26480.zip](https://github.com/beefytech/Beef/files/5226559/BeefIDE.exe.26480.zip)

**Comment by bfiete** [comment]
Hard to tell exactly what's going on, but it's a circular reference issue with type generic constraints and a conversion operator... 
Can you make this happen on demand now? I can keep adding extra debugging info to try to narrow it down over time.  

How did you trigger it this time?

**Comment by xposure** [comment]
Yes, I can trigger it on demand just by adding the initial code back to my project.

**Comment by bfiete** [comment]
So what's happening here: the List extension was in the wrong namespace (GameLib vs System.Collections) so that extension declaration created a kind of "zombie" type declaration at `GameLib.List<T>`, which okay in isolation but then references to `List<T>` elsewhere end up bound to that zombie type instead of `System.Collections.List<T>` and it caused some issues.

In the process of fixing still.

But in the meantime, you want your extension declaration like this:
```C#
namespace System.Collections
{
	extension List<T> where bool : operator T > T
	{
		...
	}
}
```

**Comment by xposure** [comment]
What I was actually trying to do before I hit the crash was to play with the extension code to see if there was an easy way to add the `Take<T>` method I suggested. I thought about trying it with mixins but I didn't like the syntax.

Since you pointed out that there is a GrowUnint, I started using that without issue.

**Comment by bfiete** [comment]
You could have also done it with extension methods, like this:
```C#
namespace GameLib
{
	public static class Extensions
	{
		public static Span<T> Take<T>(this List<T> self, int count)
		{
			...
		}
	}
}
```
And then in files wanting to use that extension: `using static GameLib.Extensions;`

**Comment by bfiete** [comment]
Crash fixed at https://github.com/beefytech/Beef/commit/6cb1235fd63bac6c441361fc10dcb21a9a56b1e8
