### ISSUE TITLE
[Enhancement] Add Span<T> Take(int count) to List<T>

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#486]

**Comment by bfiete** [comment]
Not *exactly* what you requested, but: https://github.com/beefytech/Beef/commit/7e0c25ef8f79a597b52053b0f55978f1a39a3515

GetRange(offset, count) is equivalent to Take(0, count)

**Comment by bfiete** [comment]
Also though- Beef does support extension methods (as well as extensions). In C#, those LINQ-ish style methods are exposed as extension methods. That allows them to be imported by namespace rather than just always existing on every instance of `List<T>` and whatnot.

**Comment by xposure** [comment]
My bad for not clarifing, I was actually thinking something like this.

```
        public Span<T> Take(int32 count){
            if(mSize + count > AllocSize)
            {
                // We free after the insert to allow for inserting a ref to another list element
                let oldPtr = EnsureCapacity(mSize + count, false);
                Free(oldPtr);
            }
            mSize += count;
            
#if VERSION_LIST
            mVersion++;
#endif
            return .(&mItems[mSize - count], count);
        }
```

**Comment by bfiete** [comment]
Ah- there's already a GrowUnitialized...
