### ISSUE TITLE
Float literal suggestion

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#487]
```
float f1 = 0.3f;
float f2 = 3f;
float f3 = .3f;
```

In C#, all three of these compile. In C++, f2 does not compile. 

In Beef, only f3 doesn't compile, which trips me up occasionally. Just a minor annoyance!

**Comment by bfiete** [comment]
There's a parsing ambiguity there with unnamed tuple fields, which use index numbers.
```C#
var b = (a).0;
```
If `a` is a tuple then that's a reference to the first field. If `a` is a type then that's a cast of a double.

**Comment by bfiete** [comment]
Languages seem kind of split on that one - Rust, Swift, and Zig don't support it...

**Comment by MattThorson** [comment]
Ah that makes sense. I suppose you could support it with floats only and not doubles, because the 'f' at the end should clarify that your example above could only be a cast. But then you aren't treating floats and doubles consistently.

Not a huge deal or anything, just wanted to mention it. I'll close this!
