### ISSUE TITLE
[BUG] Crash on hitting . 

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#488]
[9152020.zip](https://github.com/beefytech/Beef/files/5227118/9152020.zip)

**Comment by bfiete** [comment]
This looks like it's an issue with attempting to call an indexer with 2 values when the indexer only takes one value. What's going on on that line?

**Comment by xposure** [comment]
It was most likely related to that, I've noticed intellisense acts weird with indexers that return structs and I was most likely fighting with . trying to get intellisense to pop up and it is probably true that I may have typed the wrong number of args.

**Comment by bfiete** [comment]
If you can figure out what the code was at that point, I'd like to know.

Also if you have any specific examples of autocomplete behaving strangely then I'd like to know what that is too.

**Comment by bfiete** [comment]
Reopen on repro, if this ever happens again.

**Comment by xposure** [comment]
[crash-indexer.zip](https://github.com/beefytech/Beef/files/5343346/crash-indexer.zip)

I think this is related. I attempted to reference an indexer _map[0] (which isn't a valid indexer, it takes an int3) and the IDE crashed.

**Comment by bfiete** [comment]
Got it this time, thanks. https://github.com/beefytech/Beef/commit/58370d2c8cd516882e1cf92886b7760a4281350f
