### ISSUE TITLE
Array.BinarySearch must implement 'System.IComparable<char8>'

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#49]
```
                public static void Search(StringView source, char8[] divider)
		{
			var position = Array.BinarySearch(divider, 0, divider.Count, 'a');
		}
```

Can't implement because its a built-in type - had this problem with other types such as int as well

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/90e4cf8825d657cb157110ecfe6682c5d5676a9c, will be in release 0.42.2.
