### ISSUE TITLE
[BUG] Crash on build after rename + refactoring

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#490]
Was moving code around to gamelib and renaming things. Hit build to look for compile errors and it crashed.

[crash-build-afterrename.zip](https://github.com/beefytech/Beef/files/5234024/crash-build-afterrename.zip)

**Comment by bfiete** [comment]
And presumably when you opened the project back up it was able to compile without a crash?

**Comment by xposure** [comment]
No, it persisted

**Comment by xposure** [comment]
The gist of what happened is I moved the Color.bf file from GameLib to Math and then named it from `Color` to `color` I then changed the namespace from `GameLib` to `Atma.Math`.
