### ISSUE TITLE
[BUG] Hard crash with auto complete

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#491]
I'm in the process of porting over a large library that has tons of errors so its most likely related to that.

[BeefIDE.exe.4976.zip](https://github.com/beefytech/Beef/files/5234661/BeefIDE.exe.4976.zip)

**Comment by bfiete** [comment]
The crash didn't reproduce, just happened this one time?

**Comment by bfiete** [comment]
A reproducible case is gold. I can put in some extra debugging information for this kind of issue but it's not really possible to determine what caused it yet from just this crash dump.

**Comment by xposure** [comment]
I worked around it and no longer have the crash, in the future on the hard crashes I will send you a zipped project via email.

**Comment by bfiete** [comment]
Reopen on repro, if this ever happens again.
