### ISSUE TITLE
[BUG] struct reports possibly uninit field usage when field name matches type name

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#493]
![image](https://user-images.githubusercontent.com/6292318/93400414-c1740d80-f84d-11ea-96e4-d1b212c92449.png)

**Comment by bfiete** [comment]
Yeah- this is illegal in Beef.
C# will allow `IndexElementSize.XXX` to EITHER match the non-static field instance of `IndexElementSize` or the type name `IndexElementSize`. It's an odd rule that only exists when the typename and the field name are the same.

In C# if you have a field named `String String;` then `String.Length` will refer to the non-static Length property of the field and `String.Format` will refer to the static method. If you have `int String` then `String.Format` just doesn't work anymore. Kinda weird rule.

In Beef, `IndexElementSize` will be the field reference always. If you want to reference the type name then you need to use the fully-qualified name (including the namespace).

**Comment by bfiete** [comment]
This does not currently work, but I could make this work:
```C#
IndexElementSize = decltype(IndexElementSize).ThirtyTwoBits;
```

**Comment by xposure** [comment]
Yea, I could see that working. I ended up just using the full namespace name. Perhaps provide a better error to this because the issue isn't really about using the uninit'ed field, its about the right hand side actually being the field reference and not the type its self.

**Comment by bfiete** [comment]
Well, there are two errors there. One is `Use of possibly unassigned field` like you noted, but the other is `Member 'IndexElementSize' cannot be accessed with an instance reference; qualify it with a type name instead`

The first error *is* a valid error for a non-static lookup on the IndexElementSize field.

**Comment by bfiete** [comment]
Support for that `decltype` feature mentioned above has been added at https://github.com/beefytech/Beef/commit/7f9e0c4f5be991e3b8cc97044ff38abdac66c6a0
