### ISSUE TITLE
[BUG] Crash with DLL library binding

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#494]
I made a minimal binding to the Unicorn CPU Emulator library (Win64) in this project.
If the code uses any of the library's function, it will crash when opening up the Memory panel
while debugging.

If I don't open up the Memory panel, the program/debugging runs fine.

The zip contains the minimal reproducible code and everything required to run the project (Library DLL).

[beef-unicorn-crash.zip](https://github.com/beefytech/Beef/files/5236804/beef-unicorn-crash.zip)

Version: Nightly 09/16/2020

**Comment by bfiete** [comment]
The debugger used to support MinGW DWARF debug info but those code paths had grown stale and untested. The unicorn DLL is build on MinGW and it triggered some DWARF parsing bugs. The DWARF support has just been turned off in the debugger now, so that crash is fixed in the next nightly.
