### ISSUE TITLE
[BUG] Moving/Renaming workspace folder breaks IDE functions

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#495]
If I create a copy of my Beef workspace to somewhere else or just rename the workspace folder, these things will not work as expected:

- Although breakpoints are still visible, they will not be hit when debugging (even those that are created
after the move/rename (this issue is connected to the following item)
- Recent files menu will try to open up the files in their original location / Files that were open before the move/rename will still link to the original files

These issues come from the fact that paths are stored absolutely in the BeefSpace_User.toml file.

Two solutions I can think of:
- Store relative paths instead of absolute ones (only for those projects that are inside the workspace folder physically, not to cause issues with projects stored outside of the workspace folder)
- Store the original workspace location in the BeefSpace_User.toml file and when it gets moved/renamed, the IDE should check on startup if it's the same location or not from where it gets opened. If's not the same, it could delete the BeefSpace_User.toml file and create a clean one. (Also, a warning message could show up saying that the BeefSpace_User.toml file will be deleted)

Version: Nightly 09/16/2020

**Comment by bfiete** [comment]
Good idea. The user file will now use workspace-relative paths when the paths are actually inside the workspace directory, and still use absolute paths for things outside.
https://github.com/beefytech/Beef/commit/980132c3cc09f7b0415ddbe157f4e098710d7dbb
