### ISSUE TITLE
[BUG] Workspace file tree navigation losing focus

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#496]
Navigation keys will lose focus after a few steps.

Steps to reproduce:
1. Open any workspace (new or existing)
2. Open at least one file from the workspace (Important)
3. Only do these with the keyboard: Start navigating between folders and files, open/collapse the folders

Corlib is a good folder to test Step 3.

It's reproducible for me in about 10 seconds.
I hope it's not an issue just for me.

Version: Nightly 09/16/2020

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/10da44e341c9922d1cbe2af7b0a5fac96feb5c4e - will be in the next nightly
