### ISSUE TITLE
[BUG] Docs left nav is incorrect when viewing the statement page

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#498]
https://www.beeflang.org/docs/language-guide/statements/

**Comment by bfiete** [comment]
Weird- I use a doc generator (Hugo), some bug in there or in the theme I guess.
Fixed at https://github.com/beefytech/Beef_website/commit/afbbe6ef038dc956812d6a788dea403ec024466b, just by reordering the pages a bit.
