### ISSUE TITLE
Windows: IDE is not DPI aware

### ISSUE THREAD

**Issue by vitalyster** [beefytech/Beef#5]
It is declared as DPI-aware but no actual DPI aware support present => extremely small text size on hi-dpi screens

**Comment by bfiete** [comment]
What is your DPI for your system? And if you open up File/Preferences/Settings, what is the UI Scale currently set to?

**Comment by vitalyster** [comment]
200% scale

**Comment by deNULL** [comment]
I've noticed some problems with hi-DPI support, but to a lesser extent. At the first launch, file names in Workspace panel were offset to the left, overlapping with their file icons. However, I have not been able to reproduce that afterwards (possibly after I played with DPI compatibility in Windows file properties dialog, but now it works even when compatibility mode is disabled).

But there's still some problems in disassembly view. Top bar is small than expected, branch indicators on the left are messed up, breakpoint and current instruction pointer are cropped.

![2020-04-25 15_08_34-SpaceGame - Beef IDE](https://user-images.githubusercontent.com/575909/80279725-07e29780-8708-11ea-8833-69245dd48a00.png)

**Comment by HydrogenC** [comment]
> I've noticed some problems with hi-DPI support, but to a lesser extent. At the first launch, file names in Workspace panel were offset to the left, overlapping with their file icons. However, I have not been able to reproduce that afterwards (possibly after I played with DPI compatibility in Windows file properties dialog, but now it works even when compatibility mode is disabled).
> 
> But there's still some problems in disassembly view. Top bar is small than expected, branch indicators on the left are messed up, breakpoint and current instruction pointer are cropped.
> 
> ![2020-04-25 15_08_34-SpaceGame - Beef IDE](https://user-images.githubusercontent.com/575909/80279725-07e29780-8708-11ea-8833-69245dd48a00.png)

Weirdly, this problem got fixed itself after switching the font from the default one to Consolas.

**Comment by bfiete** [comment]
I checked in a fix for the Disassembly issues yesterday...

**Comment by bfiete** [comment]
I think most of these issues are addressed now. Reopen if not.

**Comment by vitalyster** [comment]
@bfiete I misread your comment about manual change of UI scale in Beef IDE settings. Yes it works correctly when I change app UI scale to 200%, but it is not how it should work. What if I drag IDE to second monitor with 100% scale? It should not be a global setting, but automatically detected per monitor (DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2), see https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process for details
