### ISSUE TITLE
GetHashCode unaccessible on primitive type

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#50]
GetHashCode is declared private in primitive types.

```
        public class Vector2 : IHashable
	{
		public int GetHashCode()
		{
		    return X.GetHashCode() ^ Y.GetHashCode();
		}

		public float X;
		public float Y;
	}
```

**Comment by bfiete** [comment]
Yeah, those implementations didn't need to be private. Changed in https://github.com/beefytech/Beef/commit/b9debfe3bf636e58521504744adf90361930c6ea, will be in release 0.42.2.
