### ISSUE TITLE
[BUG] Issue with auto complete adding unusable using static statement

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#500]
I'm not sure how you want to handle this one or if it can be handled. Autocomplete wants to add the a static using statement to `System.Collections.Dictionary` since `ValueEnumerator` is a struct defined inside `Dictionary<T, K>`, but the problem is the static using statement won't work due to the type generics and it will keep suggesting (and adding multiple) the fix is a static using.

The actual fix is `System.Collections.Dictionary<T,K>.ValueEnumerator`.

```
	public struct ReadOnlyDictionary<T, K> : IEnumerable<(T key, K value)>
	{
		private readonly Dictionary<T, K> _dict;

		public int Count => _dict.Count;

		public this(Dictionary<T, K> dict)
		{
			_dict = dict;
		}

		public K this[T key]
		{
			get => _dict[key];
		}

		public IEnumerator<(T key, K value)> GetEnumerator() => _dict.GetEnumerator();

		public ValueEnumerator Keys => _dict.Values;
		public ValueEnumerator Values => _dict.Values;
	}
```

**Comment by bfiete** [comment]
It was a coincidence that the fixit happened to find an appropriate ValueEnumerator reference in this case.
There's no way for the fixit to know what the proper generic arguments should be, however.

"using static" fixit will no longer add generic types: https://github.com/beefytech/Beef/commit/93f5890d6d171b89ebc8e3d7c39b36d1f9b1f300
