### ISSUE TITLE
[Enhancement] Allow autocomplete to implement missing ctor

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#501]
![image](https://user-images.githubusercontent.com/6292318/93631844-4845f900-f9ba-11ea-85f2-c2936f244e7c.png)

Would be useful if we could ask autocomplete to add the missing ctors.

**Comment by xposure** [comment]
Thinking out loud, what difficulties would there be marking a ctor to propagate to children? This could be useful when you have a base class that does most the work and has a large number of ctors but delegates most the work to an implementation class.

**Comment by bfiete** [comment]
Ctor fixit added at https://github.com/beefytech/Beef/commit/4571221551cc7aa2cd9b8bf240934df7289976a8
