### ISSUE TITLE
[Enhancement] Expand treeview on add new folder/files

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#502]
The treeviews by default are not expanded and when you add a folder to a new folder it does not expand. In addition, it would be useful if new folder was also set to edit so you don't have to hit f2 to rename it. Alternatively the IDE could ask for the folder name instead of defaulting to "new folder".

**Comment by bfiete** [comment]
Good idea. https://github.com/beefytech/Beef/commit/f1a094536f5bbeabde0a61a78df5f9d7107e797a
