### ISSUE TITLE
[Bug] Git merging (with conflicts) causes IDE to crash

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#505]
I merged my repo with git and got some merge conflicts. The IDE didn't show any errors at first, because the BeefSpace.toml file had a conflict. After I fixed it and reopened the workspace, the IDE crashed (Crash dump + project in zip). 
[Steel.zip](https://github.com/beefytech/Beef/files/5251590/Steel.zip)

**Comment by bfiete** [comment]
Yeah- that's a good idea, we can add some conflict-marker awareness to the parsers to at least give some better-formed errors. Technically we could even have a ctrl+. fixit for selecting conflict resolution (A/B/A+B).

**Comment by bfiete** [comment]
The crash should be fixed at https://github.com/beefytech/Beef/commit/31ac632ea6795d9aeed8bcb98184ae862c1ef684
Still working on handling conflict markers better.

**Comment by bfiete** [comment]
Merge conflict markers will now generate better errors and there's fixits for conflict resolution. The conflict behaves as an #if true/#else/#endif, so only one merge branch is processed and only one error is (directly) generated: "Conflict marker found".

https://github.com/beefytech/Beef/commit/c76c19e8526347873794ac8290b353ab3a3af01e
