### ISSUE TITLE
Crash while trying to write a extension

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#506]
Here is a simple repro code:
```
using System;

namespace System
{

}

namespace test4
{
	class Program
	{
		public static int Main(String[] args)
		{
			return 0;
		}
	}
}
```

To trigger the crash you just need to paste the following code inside the `System` namespace
```
	extension Array1<T>
	{

	}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/f0a6ec4870e69b0e08a779972d95ae089374f6c5
