### ISSUE TITLE
Crash while debugging crash

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#507]
I was trying to find more about a crash and the IDE suddenly crashed when I tried to go down on the call stack, here is the crashdump:
[crash_while_debugging_crash.zip](https://github.com/beefytech/Beef/files/5256278/crash_while_debugging_crash.zip)

Screenshot:
![image](https://user-images.githubusercontent.com/14041768/93784552-8a15b000-fc03-11ea-8051-7417dafaf14a.png)

**Comment by bfiete** [comment]
The key to this crash is the little bar of grey you see above the "Workspace" panel. That's a 3-pixel high tabbed view where the document is being opened. How in the world did you get the IDE into that state? That's the real bug here, the crash is just a symptom...

**Comment by bfiete** [comment]
Ah, I figured it out- it's a bug with the new "document recovery" system. That sliver of a tabbed view is created when recovered documents are being shown at startup.

**Comment by bfiete** [comment]
Fixed the crash issue and I'm fairly certain the underlying tiny-tabbedview issue is fixed too https://github.com/beefytech/Beef/commit/cfe46abeaa2f3e273f2529c001f164f7de2e3415
