### ISSUE TITLE
Crash when calling generic with null

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#508]
As said in the issue title, this code will crash the IDE:
```
using System;
using System.Collections;

namespace test4
{
	class Program
	{
		public static void Foo<T>(T value) where T : var
		{
			T i = default;
			Runtime.Assert(i.value);
		}

		public static int Main(String[] args)
		{
			Foo(null);
			return 0;
		}
	}
}
```

Also, the same type of crash is happening in another project but with an assert failed, maybe it is the same cause, so here is the crashdump:
[i.value crash.dmp.zip](https://github.com/beefytech/Beef/files/5256371/i.value.crash.dmp.zip)

**Comment by bfiete** [comment]
'null' will no longer be allowed for generic parameter inference at https://github.com/beefytech/Beef/commit/989f9e6019aeb90bc63356354793ea170111319f
