### ISSUE TITLE
Beef IDE cant correctly display  unicode text?

### ISSUE THREAD

**Issue by sgf** [beefytech/Beef#510]
![image](https://user-images.githubusercontent.com/2557696/94059919-b6087f80-fe15-11ea-8ddf-3b9dc170c0c6.png)

In the code edit box, **unicode text cannot be displayed correctly**.
and **what the default encoding of the Beef-lang ?**
C#'s string is very powerful. the default encoding is UTF16LE;

About:utf-8 
Although many people think that utf-8 is better than utf16. But in fact they are all variable length codes. There is no essential difference. When utf16 represents cjk, many characters only need two bytes. But utf-8 needs at least three.

Of course I am not against Beef using UTF-8 as the default encoding. 
**But be sure to confirm a default encoding.**
Otherwise, it will be like C++, making the string type store various codes, which becomes very confusing.

In addition, **a complete font system loader may be needed**.
Although most In Western games now like to carry their own font files. But using the system font of the operating environment is also a very good choice.

**Comment by bfiete** [comment]
There's a font setting in File \ Preferences \ Settings. There is no CJK font specified by default, but you should be able to add one to the list. It does support specifying system font names. The font layout engine is weak, however, so many languages will not display certain types of characters or ligatures correctly.

Strings are documented at https://www.beeflang.org/docs/language-guide/strings/, but the short answer is that they are UTF8.
