### ISSUE TITLE
[BUG] this source file appears to crash beef ide

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#512]
Sent an email with the project

**Comment by xposure** [comment]
![image](https://user-images.githubusercontent.com/6292318/94174591-808a8300-fe63-11ea-85e8-8c5fd801615c.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/797aa7cedc8cf49ed15dfd54006290f41e36b6f9

The issue is that this ends up defining an `Texture` class inside `GL_Texture`, and then it's base type declaration of `Texture.Platform` saw the inner `Texture` type and caused an issue.
