### ISSUE TITLE
[BUG] Intellisense doesn't always show the right arg

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#513]
![image](https://user-images.githubusercontent.com/6292318/94184445-ea118e00-fe71-11ea-94d9-a01b74b4cd48.png)

I've come across this a lot and I think it usually relates to using the short version of `.(...)`, usually intellisense gets stuck on the previous argument.

**Comment by bfiete** [comment]
Fxied at https://github.com/beefytech/Beef/commit/b86c0cde9ed5701c24793d1ca86e87546f945aff
