### ISSUE TITLE
[BUG] Autocomplete doesn't work unless there is one letter typed when using enter

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#514]
![image](https://user-images.githubusercontent.com/6292318/94184844-850a6800-fe72-11ea-979e-cd31b16b9628.png)

The following will work if you hit tab but will fail if you use enter and go to a new line.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/b86c0cde9ed5701c24793d1ca86e87546f945aff
