### ISSUE TITLE
[BUG] Strange missing document

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#515]
![image](https://user-images.githubusercontent.com/6292318/94188458-6b1f5400-fe77-11ea-9143-ee77d6ccefd0.png)

**Comment by xposure** [comment]
Looks like it was trying to open some sort of source file for debugging in the core?

**Comment by bfiete** [comment]
This is what happens when you try to view functions in the C runtime- there is debug info available that points to the path where it was built (somewhere on a build machine in Microsoft). Sometimes Auto Find can find a compatible source file on your machine.

**Comment by bfiete** [comment]
Anyway, I don't see a bug here unless it was something around the circumstances of why this source location was being shown, which you haven't described.

**Comment by xposure** [comment]
Yea i'm not sure, in fact there were about 6 of these windows open and its th first time I have seen them appear. I figured it was due to debug and I'm going to assume it must of happened while I was stepping through some code. I didn't notice these though until I was closing a bunch of tabs that I had at the time.

**Comment by bfiete** [comment]
Generally you'll only see them if you explicitly click on the callstack location inside c runtime function, or if there's a crash inside there. Stepping will generally skip locations that you don't have source code for. Anyway- if you see a case where one of these should not actually appear then reopen.
