### ISSUE TITLE
[BUG] Crash on f2 then home

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#517]
I was attempting to rename a file in the workspace from `_Images.bf` to `Image.bf`, I selected the file then hit f2 -> home key and the ide crashed.

**Comment by xposure** [comment]
[f2-then-home.zip](https://github.com/beefytech/Beef/files/5283383/f2-then-home.zip)

Forgot to include the dump.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/f41a4b017326198a3d312c2adb9c77200329a164
