### ISSUE TITLE
[BUG] Renaming a file causes the ide to show the old file as missing

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#518]
If you rename a file in the editor that is open and then close it, the IDE will open the old file and say its missing.

For example, this file was open and active and I renamed it and then hit ctrl+w to close it which then opened the old file name and said it was missing.

![image](https://user-images.githubusercontent.com/6292318/94279635-6364bb80-ff1a-11ea-83c8-89d3257be34f.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/4b64f2c14da45ee157506e6c6be9ad97f70fb551

**Comment by xposure** [comment]
While the file no longer appears in this manner, it can still be seen with `ctrl+tab`.

**Comment by bfiete** [comment]
Yeah, step 1 was just not auto-opening the most-recently-viewed file if it no longer existed. Step 2 is actually renaming the items in the recently-viewed list.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/05d5b5f5940b96e530b570d79f61de557765109a
