### ISSUE TITLE
[BUG] Crash on commenting line

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#519]
[comment.zip](https://github.com/beefytech/Beef/files/5283520/comment.zip)

![image](https://user-images.githubusercontent.com/6292318/94282634-0c60e580-ff1e-11ea-8dc5-e128a3a44a1f.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/f6ab79d2efa6f4abe0e5d6f10def5abcd2158ee8
