### ISSUE TITLE
[BUG] Find and replaced will replace locked projects

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#523]
I "thought" i hit `find in all` but I must have hit `replace in all` and when I looked in the output window it said "2 replaces in sdl" which is a locked project. Had to reinstall to revert the changes.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/5403cdb74870ef4b1effc224d82a1a754469822a
Undo works for undoing those changes, btw.
