### ISSUE TITLE
[BUG] Prop window locked up when changing keybindings

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#526]
![image](https://user-images.githubusercontent.com/6292318/94371242-1a03a000-00c3-11eb-9573-f402c4caa063.png)

I originally bind `Show class view` to `ctrl+comma` the first time and then went back to change it to `find class` and the ide prop window locked on hitting `apply`

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/077ebe2659c2f447e628e57588a355da0fabdf6c
