### ISSUE TITLE
Cannot invoke private constructor from another constructor

### ISSUE THREAD

**Issue by lukpank** [beefytech/Beef#53]
In the following program `public` constructor cannot invoke `private` constructor, failing to compile with error `Too many arguments, expected 1 fewer`. But if `private this` is replaced with `protected this` the program compiles without problem.

```csharp
namespace Issue
{
	public class Program
	{
		public static int Main(String[] args)
		{
			return 0;
		}

		public this()
			: this(0)
		{
		}

		private this(int i)
		{
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/9ffdb9474057813ee8288eed07a4676a4dbd7696, will be in release 0.42.2.
