### ISSUE TITLE
[BUG] Stack corruption when vewing property

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#530]
The project I sent you on 9/27/20 for https://github.com/beefytech/Beef/issues/529 can also reproduce this bug. The code below is the culprit in `GameSim\World\Map.bf` around line 62. If you set a break point on the first `if` condition and view `loc.xy` with the debugger, it will corrupt the stack.

```
		public int3 GetFirstTileDown(int3 loc, TileFilter filter, out Tile tile)
		{
			if (loc.x >= 0 && loc.x < Size && loc.y >= 0 && loc.y < Size && loc.z >= 0 && loc.z < Layers)
			{
				for (var z = loc.z; z > 0; z--)
				{
					tile = _layers[loc.z].Get(loc.xy);
					if (filter(tile))
						return .(loc.xy, z);
				}
			}

			tile = Tile.Invalid;
			return -int3.Ones;
		}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/c28ed988b3815b9951e3d5b8b5d2f98ca86dc1e0
