### ISSUE TITLE
[Enhancement] Add possible compiler warning on defer statement with mixin

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#531]
```
				defer  DeleteAndNullify!(_indices16); 
```

This code is valid but does not execute as you would want it to, in defers the delete then immediately sets the value to null. You want the following.

```
				defer { DeleteAndNullify!(_indices16); }
```

Could the compiler detect this and give you a warning?

**Comment by xposure** [comment]
```
	public static mixin DeleteAndNullify(var val)
	{
		delete val;
		val = null;
	}
```

It appears that `delete val` is defered and `val = null` executes immediately. I guess its possible it all executes immediately, would have to test it with a custom mixin to see.

**Comment by bfiete** [comment]
This is now disallowed at https://github.com/beefytech/Beef/commit/64af84f0de31ce3186fa95f5a3e3e07fdff1efeb
