### ISSUE TITLE
[BUG] Keybinding conflict can cause IDE to hang

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#532]
![image](https://user-images.githubusercontent.com/6292318/94373322-b84b3200-00d2-11eb-874e-1658616441b4.png)

Having both of these set to F2 and then attempting to hit F2 to rename something like a class or const will cause the IDE to hang

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/077ebe2659c2f447e628e57588a355da0fabdf6c
