### ISSUE TITLE
[BUG] Crash on typing generic constraints

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#534]
[generic-crash.zip](https://github.com/beefytech/Beef/files/5289003/generic-crash.zip)

**Comment by bfiete** [comment]
I'm pretty sure this should fix the issue, but I wasn't able to reproduce the bug myself. It involves a const expression in a generic argument.

https://github.com/beefytech/Beef/commit/ae063463577f62060fe084e43ab44d80011a975f
