### ISSUE TITLE
[BUG] Incorrect arg shown

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#536]
![image](https://user-images.githubusercontent.com/6292318/94464824-f9078180-018c-11eb-8948-3014e1a0fa24.png)

Seems to be the same as this but its marked fixed/closed (and I have noticed an improvement with this).
https://github.com/beefytech/Beef/issues/513

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/9db256f28160ffafc52aab4591ef9cb80230ea27
