### ISSUE TITLE
[BUG] Crash on creating static struct

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#537]
![image](https://user-images.githubusercontent.com/6292318/94465385-d3c74300-018d-11eb-9831-2d5042584c93.png)

[creating-struct.zip](https://github.com/beefytech/Beef/files/5293971/creating-struct.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/b7f30c798c2b5833c6b967b186902eec81370151
