### ISSUE TITLE
[BUG] Crash on save all

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#538]
[save-all.zip](https://github.com/beefytech/Beef/files/5293994/save-all.zip)

**Comment by bfiete** [comment]
Hm- it looks like it was while saving key bindings. Somehow that structured got into an invalid state... Any ideas?

**Comment by xposure** [comment]
Nope, just like the `0` key some how got bound to `rename item` which I also reported in another issue that would hang the IDE if it was bound to rename symbol. 

But at least now I can see how to fix it, for awhile it stopped and then the IDE crashed and now its back again.

**Comment by bfiete** [comment]
Reopen on repro, if this ever happens again.
