### ISSUE TITLE
Syntax highlighting for 'this'

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#54]
Not a big deal, just used to it being highlighted in visual studio.
'this.' is not highlighted yet 'this' without the dot is highlighted.

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/590df7aec73621ec7ebb28579e59d4b53a7c8130, will be in release 0.42.2. 

Also fixed "Go to Definition" for 'this' and 'base'.
