### ISSUE TITLE
[BUG] Some keybindings get reverted

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#540]
This isn't something I can easily reproduce but it happens quite frequently. Most of the time I lose some sort of settings until the eventually "take hold". 

For example, I have swapped F7 to "ctrl+shft+b" for build and hit apply, it works for awhile, but sometimes closing the ide and reopen it the setting will be reverted back to F7. The one I have this happen to the most is `ctrl+comma` I remove it off `next document` and put it on `find class` and it will continuely revert on me even after closing and reopening. Eventually it stops doing this and I'm not sure why.

**Comment by bfiete** [comment]
I'm going to say this is fixed here https://github.com/beefytech/Beef/commit/5746214198c4c7b71c459197bc93c89d6dadffda

**Comment by bfiete** [comment]
I stick by my "it was fixed".
