### ISSUE TITLE
[BUG] Crash while refactoring

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#543]
[refactoring.zip](https://github.com/beefytech/Beef/files/5295200/refactoring.zip)
![image](https://user-images.githubusercontent.com/6292318/94489322-3d594880-01b2-11eb-8f85-3215757558a4.png)

Was creating a overload for a method and then deleting its body after converting it to a simple `=>` it crashed

**Comment by bfiete** [comment]
Pretty sure this fixes it https://github.com/beefytech/Beef/commit/b13bee470c54f7812def34a8cd13320483f6aa18

It was an overly-assertive assert, I think it wouldn't have caused a Release issue. It was related to trying to resolve the type of the 'let e' field.
