### ISSUE TITLE
[BUG] if statement with || crash

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#544]
[092820_1.zip](https://github.com/beefytech/Beef/files/5295540/092820_1.zip)
![image](https://user-images.githubusercontent.com/6292318/94495602-3afdeb00-01c0-11eb-9115-e14db5c54c95.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/3d4455d1f6051692f493265898b897c7ff4730fa
