### ISSUE TITLE
[BUG] Crashed changing a namespace

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#549]
Was adding a `s` to the namespace and the IDE crashed.
[added-s-namespace.zip](https://github.com/beefytech/Beef/files/5313293/added-s-namespace.zip)

![image](https://user-images.githubusercontent.com/6292318/94832567-0cf4f280-03dc-11eb-8204-2c9ade4d62bf.png)

**Comment by bfiete** [comment]
Hm. Is there anything unusual about the way that file was opened?

**Comment by bfiete** [comment]
I can see what the general issue is, I just can't see how to cause it to happen.

**Comment by xposure** [comment]
Yes, the folder was in GameSim and then I decided to move it to Framework, I did this outside of the editor since there is no way that I know of to move a file or folder in the editor.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/f6c42b561a051b7a7a500a9445791d7d35cc71c9
