### ISSUE TITLE
Declaring multiple extensions in the same class causes IDE crash.

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#55]
Below example will cause the crash.
Attached crash dump.
[extension_crash.zip](https://github.com/beefytech/Beef/files/4232791/extension_crash.zip)

```
using System;

namespace System
{
	extension Array
	{
		
	}

	extension StringView
	{

	}
}
```

**Comment by damianday** [comment]
Doesn't seem to be just the same class file, I tried to split it over multiple files and still crashing.

**Comment by bfiete** [comment]
There were actually a couple issues there. Fixed in https://github.com/beefytech/Beef/commit/4efa88376c186e662673a5066bea724582b77ff7, will be in release 0.42.2.
