### ISSUE TITLE
[BUG] Lock up on on autocomplete implementing method

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#552]
My guess is due to the type inference being used here that the implement method auto complete locked up the IDE.

![image](https://user-images.githubusercontent.com/6292318/94879946-a994b000-042f-11eb-8e8f-f31e11e43063.png)

**Comment by bfiete** [comment]
I haven't managed to reproduce it yet.
One thing you could try: https://docs.microsoft.com/en-us/sysinternals/downloads/procdump
You can `procdump BeefIDE` to generate a minidump of the frozen process.

**Comment by xposure** [comment]
[BeefIDE.exe_201002_111511.zip](https://github.com/beefytech/Beef/files/5318816/BeefIDE.exe_201002_111511.zip)

**Comment by xposure** [comment]
Interesting enough, I tried it and it locked the first time today and then I tried it again and it worked, then i ctrl-z'ed and tried it again and it locked.

**Comment by bfiete** [comment]
Ah this is actually the same as this: https://github.com/beefytech/Beef/issues/551

This should be fixed in the current nightly build.
