### ISSUE TITLE
[Enhancement] Goto definition without ( ) on a function

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#554]
![image](https://user-images.githubusercontent.com/6292318/95114107-6c6f3d00-0711-11eb-9638-5d70ce71b0e4.png)

This is a little QOL thing, you can't go to definition unless you add the a `(`

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/8647d6380660a1af4a887f82ba0de1fa716cc08a
