### ISSUE TITLE
Visual studio-like xml documentation commenting

### ISSUE THREAD

**Issue by LoopyAshy** [beefytech/Beef#558]
Not much is needed to be explained thanks to the availability of this link: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments

Simply put this feature really assists in making visual studio more helpful when using new libraries, other peoples code or simply for documenting your own code clearly, it is just such a wonderful quality of life feature to be able to highlight most pieces of code from fields to methods and receive a developer created explanation of what it does and even how to use it in some examples, it is also especially good for documenting code to be used for autogenerated documentation websites and such.

I apologise if this feature has already been requested for the IDE but I was unable to see such a request.

**Comment by bfiete** [comment]
Doxygen-style documentation is supported https://www.doxygen.nl/manual/docblocks.html

**Comment by bfiete** [comment]
I realize this wasn't documented anywhere. It'll be adding it to the official docs.

**Comment by xposure** [comment]
@bfiete I'll add on to this as we already talked aboit this briefly on discord. What I think we are all expecting is more of when you hit `///` (triple slash) the IDE auto fills in the doxy gen comment (including all the params, return type, etc). Visual Studio already does this using their own format.

In addition, the .NET compiler allow you to generate warnings and errors if public methods are missing their documentation which is useful when writing libraries and making sure you don't mess public interfaces.

**Comment by LoopyAshy** [comment]
Personally the main feature I was thinking about was when highlighting references to the documented classes/fields/etc it would do what visual studio does and show the documentation nicely formatted, now if I am just flat out wrong do let me know but I tried what you suggested but this feature seems just flat out missing from the ide which in my opinion feels like a shame.

![image](https://user-images.githubusercontent.com/42229301/95278985-654b4a80-0849-11eb-8693-dc8308ad4b7d.png)

**Comment by bfiete** [comment]
@LoopyAshy What did you try exactly?

![image](https://user-images.githubusercontent.com/3042917/95333048-1b6e5e80-0861-11eb-8fb9-71aef9add68d.png)

![image](https://user-images.githubusercontent.com/3042917/95332994-04c80780-0861-11eb-9fe6-abcb023d7239.png)

**Comment by bfiete** [comment]
Also this comment style is supported:
```C#
class Test
{
	/** Test method
	* @param a First argument
	* @param b Second argument
	*/
	public static void Testiclars(int a, int b)
	{

	}
}
```

**Comment by LoopyAshy** [comment]
I am most confused due to the fact that I was unable to get that to work yesterday with the exact same comment formatting, it merely did not show anything other than than the suggested classes/methods name, however today it works perfectly, I wish I knew why as it may very well be a bug, but I am unable to reproduce that.

Thank you for clearing this up for me (although I do think it is a shame that corlib isn't full commented via this method)

**Comment by bfiete** [comment]
I also think it's a shame corlib isn't commented via this method!
And also @xposure is right that it would be nice to have some additional documentation "intelligence" built into the IDE/compiler.
