### ISSUE TITLE
[IDE highlighting bug] Highlights class as namespace

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#559]
When a class has the same name as it's namespace and you write something like `var test = ImGui.Style();` it highlights `ImGui` with a namespace color and `Style` with a class color.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/dbe38df60fcd705c1f16f2f4e110e5a3c800141f

**Comment by RogueMacro** [comment]
Bump. Still getting this issue in latest nightly

**Comment by RogueMacro** [comment]
Seems like it only applies to fields
![image](https://user-images.githubusercontent.com/51059464/97203572-4c351a00-17b5-11eb-886f-e736fd3b8185.png)

**Comment by bfiete** [comment]
Should be fixed at https://github.com/beefytech/Beef/commit/38d2eff3f652e3fe51be2b3f5ddb2e181a712fa0
