### ISSUE TITLE
[BUG] Hidden process hanging

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#560]
[BeefIDE_d.exe_201006_124225.zip](https://github.com/beefytech/Beef/files/5335582/BeefIDE_d.exe_201006_124225.zip)
![image](https://user-images.githubusercontent.com/6292318/95238669-d4885680-07d7-11eb-9c50-e1656cce6db3.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/d0c91456557b3f48097f46a7b6ccbe64cb5cb4f0
The GC deadlocked trying to report a memory leak on exit.

**Comment by bfiete** [comment]
Of course the leak itself is a bug, but a different bug...
