### ISSUE TITLE
[Enhancement] IDE menus to wrap around

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#561]
![image](https://user-images.githubusercontent.com/6292318/95255161-f17c5400-07ee-11eb-9f99-92da186b2bb9.png)

These menus (this includes tabbing documents) don't wrap around. It would be nice if you could wrap both directions (from end to start and start to end). I hit this a lot with autocomplete where the last option is usually the one I want (not the the warning supression).

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/557b13070c3ad920eccf1158af701b23431506c3
