### ISSUE TITLE
[BUG] Beef Debug IDE crashing on load

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#565]
The IDE crashed from https://github.com/beefytech/Beef/issues/488 here and then I decided to open up the debug IDE and it crashed immediately before I could open the workspace.

**Comment by xposure** [comment]
[beefd-crash.zip](https://github.com/beefytech/Beef/files/5343768/beefd-crash.zip)

**Comment by bfiete** [comment]
Thanks- Fixed at https://github.com/beefytech/Beef_website/commit/a1e516d81f61a6cccbe34f2b9eaeb8f57c2b6ff2
