### ISSUE TITLE
[BUG] Crash with class

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#567]
My guess to this crash is that I have a namespace Jobs and a global variable Jobs. This was working for awhile, but inside this class it appears to crash now.

[crash-jobclass.zip](https://github.com/beefytech/Beef/files/5344047/crash-jobclass.zip)

```	
        public class FindJob : Sequence<Character>
	{
		public this()
		{
			Add(new (c) => Jobs)
		}
	}
```

EDIT: Could be wrong on this, I renamed the namespace and it still crashes. There is a lot of code involved so I can send the project if needed.

**Comment by bfiete** [comment]
I was able reproduce the issue from just the crash dump. Investigating...

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/16cd9f7a77b4a62ef08c623c60f4810581004ce1
