### ISSUE TITLE
IDE: (VER 0.42) Find in Files does not pre-populate [find what] field with the currently selected text. 

### ISSUE THREAD

**Issue by jhenzie** [beefytech/Beef#57]
In the IDE Find in document populates the find field with the currently selected text.

Find in files does not.

Expected find in files, to behave the same as find in document.

See attached files.
![Find_bug](https://user-images.githubusercontent.com/21959/75093811-00bed200-557d-11ea-9de3-f53da4565e3d.png)

**Comment by bfiete** [comment]
Good idea. Added in https://github.com/beefytech/Beef/commit/68ae9f4036bdde37e46f9625558766ec4224cb9d, will be in release 0.42.2.
