### ISSUE TITLE
[Enhancement] Add Debugger.Break

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#570]
It would be useful to support Debugger.Break several reason.

- It persists in source control
- Its far more perfromant than setting a breakpoint and configuring
- Its more declarative of what you are trying to do

**Comment by bfiete** [comment]
Added at https://github.com/beefytech/Beef/commit/06f6c41679af4c2ae6af0abf6af316ff57c810dc
Debug.Break()
Debug.SafeBreak()
Debug.IsDebuggerPresent

SafeBreak allows these to not "crash" the program when running it outside the debugger. It uses a cached `IsDebuggerPresent` value which only refreshes at startup and when the user explicitly calls IsDebuggerPresent.
