### ISSUE TITLE
[BUG] Strange behavior/crash with delegates

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#571]
My original code was a bit different but the issue was the stack was being corrupted with the local scoped array. This error is a little bit different but I think its the same issue.

```

		int[] data1 = new int[](0, 1, 2, 3, 4, 5) ~ delete _;

		public void TestMe1()
		{
			Test1(10, (x) =>
				{
					System.Console.WriteLine(StackStringFormat!("x: {0}", x));
				});
		}


		[Inline]
		public void Test1<T>(int x, T dlg) where T : delegate void(int)
		{
			let news = scope int[](0, 1, 2, 3, 4, 5);
			for (var i < news.Count)
			{
				dlg(x + news[i]);
				for (var t < data.Count)
				{
					System.Diagnostics.Debug.Assert(data1[t] == news[t]);
				}
			}
		}
```

**Comment by bfiete** [comment]
The temporary workaround is to remove the `[Inline]` declaration. Still working on the root issue.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/aed026f4fc35000b78dda1fca66ae06612e199f6
Turned out it didn't have anything to do with delegates, it was a combination of array allocation and inlining.
