### ISSUE TITLE
SDLApp.bf

### ISSUE THREAD

**Issue by LanceJZ** [beefytech/Beef#572]
This function has a bug. It should look like this. It has a 0 where rot goes in the last call.

		public void Draw(Image image, float x, float y, float rot)
		{
			SDL.Rect srcRect = .(0, 0, image.mSurface.w, image.mSurface.h);
			SDL.Rect destRect = .((int32)x, (int32)y, image.mSurface.w, image.mSurface.h);
			SDL.RenderCopyEx(mRenderer, image.mTexture, &srcRect, &destRect, rot, null, .None);
		}

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/d7de0f19ca561651066968d16bc58560a53883d3
It also didn't take a rotation center point, which made it pretty useless.
