### ISSUE TITLE
[BUG] Crash while working on a stream reader helper

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#573]
[crash-stream-read.zip](https://github.com/beefytech/Beef/files/5357620/crash-stream-read.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/42a361a8c093d6ab725f1a921335f5601597031b
This was caused by a new feature for showing method signatures as part of the documentation text in the autocomplete list, it had an issue with some generic methods
