### ISSUE TITLE
[BUG] Crash with ' inside the array index

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#574]
[crash-on-type.zip](https://github.com/beefytech/Beef/files/5357624/crash-on-type.zip)

The first crash was from this where I accidentally hit `'` and then when going to backspace I accidentally hit `\`
```
var data = new BYTE[size'\'];
```

When I went to reproduce it, this crashed it immediately though.
```
var data = new BYTE[size'];
```

BYTE is just
```
typealias BYTE = uint8;
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/0f9ae6ab8cbf953d72858fd8e6b2e6028b8936cf

**Comment by bfiete** [comment]
Re-fixed at https://github.com/beefytech/Beef/commit/d24f169181a47a6a31c224d251bb72bb10e84a78
