### ISSUE TITLE
Error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#58]
When running the normal Test in Debug, the output is "public: static void __cdecl bf:MyList<struct _T0>::TestAdd(void)". If I remove the template and just use a concrete type there is no problem.

Reduced test case:

```
        public class MyList<T>
	{
		public struct Node
		{
			public T data;
		}

		[Test]
		public static void TestAdd()
		{
			// Test add
			MyList<int> l = scope .();
		}
	}
```

**Comment by bfiete** [comment]
MyList<T>.TestAdd() is parameterized by 'T', so MyList<int>.TestAdd() is distinct from MyList<float>.TestAdd().

SO- if the user specifies a [Test] method on a method that is in a parameterized type (or that is itself a parameterized method), the only thing that could make sense is to tests all the parameterizizations for that given method for the current program IF there actually were any. 

If that's not what is intended then you'd have to pull your tests out into a non-generic type.

I was attempting to link to the generic MyList<T>.TestAdd() which isn't actually a concrete method, thus the link error.

**Comment by damianday** [comment]
Ah thanks didn't realise that, I thought making it static would get around that. I'll pull the tests out into a seperate class which solves it nicely.

**Comment by bfiete** [comment]
Well, I also did the fix I mentioned so anyone who does actually want to test individual (implicitly determined) parameterized types can do so: https://github.com/beefytech/Beef/commit/e962a1a3396020b660f2f6b7dc57399110e6bbc6
