### ISSUE TITLE
[BUG] Crash after tabbing between 2 documents

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#581]
[strange-crash.zip](https://github.com/beefytech/Beef/files/5365982/strange-crash.zip)

**Comment by bfiete** [comment]
This was an issue related to a method call... this happened just this one time?
I added some extra debugging information to the minidump that should help narrow this crash (and others) in the future.

**Comment by xposure** [comment]
Happened one time, the thing that was odd was how it randomly happened while just switching between 2 files and reviewer the differences. It should be noted that one of the files was straight C# and I was working on porting it to Beef. Those sort of crashes usually happen instantly, in this case it was while I was just thinking.

**Comment by bfiete** [comment]
There's nothing I can do with this until it happens again. Will await that. It was not directly related to tabbing between two documents, though.
