### ISSUE TITLE
ide: cursor column not updated properly on delete

### ISSUE THREAD

**Issue by sgraham** [beefytech/Beef#586]
Repro:
- delete a word (via ctrl-del, or ctrl-shift-right, then del)
- move down
- cursor jumps to what the column would have been before delete, not where it was after the delete

Possibly-lightly-helpful cap:
![down-after-delete](https://user-images.githubusercontent.com/1822/95797983-aefebf80-0ca5-11eb-8860-214caf0ed096.gif)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/14609dc6361dddae93766c66eeb7f73a0b95a328
