### ISSUE TITLE
[BUG] Debugger showing incorrect value

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#588]
I tried to reproduce this in a smaller snippet of code but couldn't, I hope the screenshots are enough, if not I can send the project.

The below screenshots show that mousing over Source will show the correct data, but if you mouse over Min it becomes invalid (all though the data does not get corrupted as I first suspected).

The struct looks something like this...

```
public struct Subtexture
	{
		public rect Source		{			get => source;		}

		public rect Frame		{			get => frame;		}

		public float Width => frame.Width;
		public float Height => frame.Height;

		private Texture texture;
		private rect frame;
		private rect source;

		public (rect Source, rect Frame) GetClip(rect clip)
		{
			var clip;
			(rect Source, rect Frame) result;

			clip.Offset(Source.Min + Frame.Min);

			result.Source = clip.Intersection(Source);

			let fx = Math.Min(0, Frame.X + clip.X);
			let fy = Math.Min(0, Frame.Y + clip.Y);
			let fw = clip.Width;
			let fh = clip.Height;

			result.Frame = rect(fx, fy, fw, fh);
			return result;
		}

		public (rect Source, rect Frame) GetClip(int x, int y, int w, int h)
		{
			return GetClip(rect(x, y, w, h));
		}

		public Subtexture GetClipSubtexture(rect clip)
		{
			var (source, frame) = GetClip(clip);
			return Subtexture(texture, source, frame);
		}
}
```

and Source.Min is just 

```
		public int2 Min => .(X, Y);
```

![image](https://user-images.githubusercontent.com/6292318/95897427-86390180-0d5b-11eb-9e51-231fef00053d.png)
![image](https://user-images.githubusercontent.com/6292318/95897456-9355f080-0d5b-11eb-82a2-074f73517581.png)

**Comment by bfiete** [comment]
Yeah, an actual runnable repro case would be really helpful here.

**Comment by xposure** [comment]
The last project I sent, if you set a breakpoint inside Subtexture.cs on the line `var clip;` you can see this happening.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/95c603ada5d38d07bf252d905662581af2cc8adb
