### ISSUE TITLE
Method does not match function having qualified and nullable function as parameter

### ISSUE THREAD

**Issue by lukpank** [beefytech/Beef#59]
The following program causes `ERROR: Method 'Issue.Program.F(function void()? c)' does not match function 'function void(function void()? c)'`. Parameter of  type of `f` must be a namespace qualified nullable type (`Issue.C?`) and `C` must be a function (`typealias C = int;` compiles without error).

```csharp
using System;

namespace Issue
{
	public class Program
	{
		public static int Main(String[] args)
		{
			function void(Issue.C? c) f = => F;
			f(null);
			return 0;
		}

		static void F(Issue.C? c)
		{
		}
	}

	public typealias C = function void();
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/f9ee4010cb58a3b9574ce8b0d95f4410b7bc3493
Better late than never!
