### ISSUE TITLE
[Enhancement] Add delayed to debug ide prior to init'ing

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#591]
When crashing the IDE via source content, it can be a bit of a pain trying to relauch and quickly change the file so that the IDE doesn't crash once it initializes the source. For example, today I have been facing issues with `{` and each time the IDE crashes I relaunch it and quickly try to delete the { before the IDE tokenizes/inits everything. Sometimes its not possible and I have to modify the file external which of course will lose changes and you have to go in to the recovery folder to get them back.

Adding a 4-5 second delay in the debug IDE would allow corrections like this.

**Comment by bfiete** [comment]
There's now a safe mode https://github.com/beefytech/Beef/commit/72411118c287412137f90dbc4916ffea20df5ae2
When you relaunch you'll get a dialog asking if you want to go into safe mode. Then you have all the time you want to make all the changes you want and then hit a button to disable safe mode (which does a relaunch).
