### ISSUE TITLE
[BUG] Crash defining array

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#593]
If you delete the last `]` the ide will crash.

```
let autotiles = scope uint8[Map.mapSize][];
```

**Comment by bfiete** [comment]
Doesn't seem to happen in isolation. Can you point out in your latest source where to put that to cause the issue?

**Comment by xposure** [comment]
Not reproducing at the moment.

**Comment by xposure** [comment]
It "feels" like its related to the curly crashes. I ended up gutting all of the code and removing the lambda expressions and haven't had any more crashes. With the `ForEach` code I was crashing almost every 5 minutes, between missing `{}` or `[]` would trigger it.

**Comment by bfiete** [comment]
Cleaning this up- maybe it was already fixed? Reopen if it happens again.
