### ISSUE TITLE
Double click not always being caught

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#594]
Sometimes when I double click a variable and then right click to rename it doesn't highlight the variable, I guess I'm just clicking too fast? It's only a minor annoyance but I'm getting to good at it.

**Comment by bfiete** [comment]
Also- you can just right click on the variable without highlighting it.

**Comment by damianday** [comment]
Dang, didn't expect it to be that clever :-P

**Comment by bfiete** [comment]
Close this then? I couldn't reproduce any actual double clicking issue... it's a bit curious - even if you incorrectly double click on purpose and then right click, it still renames the symbol properly. Right?

**Comment by damianday** [comment]
Yeah it will still rename, which was my main use case. I've had the issue with copy and paste also but alas not just on your editor but also vscode so possibly the problem is my end.
