### ISSUE TITLE
[IDE][Enhancement] Have "return" before "rettype" when autocompleting

### ISSUE THREAD

**Issue by NicEastvillage** [beefytech/Beef#595]
So many times I have written `ret` and then pressed enter which results in `rettype` instead of `return` as I expected. This is beause `rettype` is first in the autocomplete suggestions instead of `return`. But `return` is used much more commonly than `rettype`, so an exception that makes for `return` appear first would be nice.

**Comment by bfiete** [comment]
There's an MRU (most recently used) list which will select "return" for you after you select it the first time on a given execution of the IDE. The issue is that the MRU list is not serialized so it resets every time you run the IDE.

**Comment by bfiete** [comment]
But also it may be good to initialize the MRU list to more useful defaults, as you mention.

**Comment by bfiete** [comment]
This fixed your specific issue https://github.com/beefytech/Beef/commit/5e4ecade6de37ad8586db1cb643d815f068c8521
Proper MRU serialization will come later sometime.
