### ISSUE TITLE
[BUG] Crash on semicolon in generic constraints

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#596]
[crash-semicolon.zip](https://github.com/beefytech/Beef/files/5380074/crash-semicolon.zip)

```
public class HotReload<T>
  where T: class;
{

}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/f9c632cbe7a8d6aa8caaaf5c43b9f0c01d65f94b
