### ISSUE TITLE
[BUG] crash while declaring variable

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#597]
![image](https://user-images.githubusercontent.com/6292318/96039120-2bc0a380-0e36-11eb-81cd-2c13a14a7594.png)
[variable.zip](https://github.com/beefytech/Beef/files/5380566/variable.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/a944aa6d2404632435bd5c4437221fe33111245d
