### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by YaakovDavis** [beefytech/Beef#60]
I get the following errors when running build.bat. (I ran llvm_build.bat prior to that successfully):

```
error C2511: 'intptr Beefy::StringImpl::LastIndexOf(char,int64) const': overloaded member function not found in 'Beefy::StringImpl' [H:\Beef\BeefRT\BeefRT.vcxproj]
```
```
error C2352: 'Beefy::StringImpl::GetPtr': illegal call of non-static member function [H:\Beef\BeefRT\BeefRT.vcxproj]
```
```
error C3536: 'ptr': cannot be used before it is initialized [H:\Beef\BeefRT\BeefRT.vcxproj]
```
```
error C2109: subscript requires array or pointer type [H:\Beef\BeefRT\BeefRT.vcxproj]
```

**Comment by YaakovDavis** [comment]
The issue was in the declaration; changing [here](https://github.com/beefytech/Beef/blob/23dd0f22e99b9ac43b35f27465f2140140b67db7/BeefySysLib/util/String.h#L975) from `intptr `to `int64` fixed it.

**Comment by bfiete** [comment]
Yeah. Fixed in https://github.com/beefytech/Beef/commit/41cb0052b21620f797a19b9d94035f8586f21193.
