### ISSUE TITLE
[BUG] Crash on build 2

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#600]
[build2.zip](https://github.com/beefytech/Beef/files/5386755/build2.zip)

I grabbed a copy of the code, but haven't sent it, let me know if its needed.

NOTE: After relaunching the editor, the crash did not presist so the project may be useless.

**Comment by bfiete** [comment]
This issue was `ig.SetTooltip(StackStringFormat!("{0}", bits));` in `GameSim.TestApp.Render()`. `bits` was a bad value...

**Comment by xposure** [comment]
I didn't fully understand what you meant by the `ig` comment as the crash was on build and not execution.

Here is another crash on build that may be related, relaunching and building did not crash.

[build-crash.zip](https://github.com/beefytech/Beef/files/5388143/build-crash.zip)

**Comment by bfiete** [comment]
I just meant that was what the compiler was compiling when it choked.
