### ISSUE TITLE
[Enhancement] Better parenthesis support

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#604]
I run in to this all the time, I will hit backspace then `(` to bring up the tooltip for the method and this will add an addition parenthesis.

![parenthesis](https://user-images.githubusercontent.com/6292318/96295034-46705500-0fbb-11eb-8cc7-e5199257c339.gif)

**Comment by xposure** [comment]
![parenthesis2](https://user-images.githubusercontent.com/6292318/96308191-eab0c680-0fd0-11eb-9dda-bb03e40b8e83.gif)

An example of `)` being eaten even though there aren't the correct number.

**Comment by bfiete** [comment]
Neither VS nor VSCode operate on the "are their enough parentheses" as their metric. VS has different behavior depending on whether you manually move the cursor around after inserting parentheses which breaks out of the "paired parens" mode, it's kinda weird. VSCode will just ALWAYS delete the `()` pair when you delete the first `(`, which is probably a good solution.

**Comment by bfiete** [comment]
This has been revised at https://github.com/beefytech/Beef/commit/743a8da08bd01f7ef50eca8a10a724eaf9be2b78
Also the feature where pressing ')' to move through a closing paren is different too. Basically there's a "recently inserted parentheses list" which is used for determining whether to insert a paren pair and to move through a closing paren. Manually moving the cursor clears that list.
