### ISSUE TITLE
[BUG] Another build crash

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#606]
[crash-build3.zip](https://github.com/beefytech/Beef/files/5394315/crash-build3.zip)

This crash is a long rewrite of the atlas packer to support hot reload. Nothing specific was changed that stands out for a crash.

c5a3291

**Comment by bfiete** [comment]
1) Fixed at https://github.com/beefytech/Beef/commit/852748ae1f944e46bfa52ed55728d467e09ddea3
2) Fixed at https://github.com/beefytech/Beef/commit/687addf7a5c2bee4e7c59fd8137f7de33f918c90
