### ISSUE TITLE
[BUG] Crash while debugging some memory leaks

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#607]
I was simply looking around the source and ctrl tabbing around, I clicked inside of a file and the IDE crashed.

[crash-lookingaround.zip](https://github.com/beefytech/Beef/files/5394385/crash-lookingaround.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/a700a6bbd2cffdddb43a90370802553fa7cd1562
It was an issue in the debugger evaluating a method call with a property target.
`_gameDefs.AddTexture("shadow_tile", Assets.Load<Aseprite>("dist/aseprite/shadow_small.aseprite"))`
