### ISSUE TITLE
[BUG] Crashed while debugging and typing in source window

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#608]
![image](https://user-images.githubusercontent.com/6292318/96311154-d7085e80-0fd6-11eb-93ce-d543f5526638.png)
[crash-typing.zip](https://github.com/beefytech/Beef/files/5394438/crash-typing.zip)

d7922f7

EDIT: I basically can't touch a single character in the Assets.bf file at this point.

I think its related to this.

```
		public Event<delegate void(StringView)> AssetChanged = default ~ AssetChanged.Dispose();
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/79d13a3626c05882b1db9f466e6575ac24e0f18d
