### ISSUE TITLE
ide: copy/paste of full line loses indent

### ISSUE THREAD

**Issue by sgraham** [beefytech/Beef#609]
Repro:
- select full line
- copy
- paste multiple times

Indent should be preserved for all lines.

![first-paste-loses-indent](https://user-images.githubusercontent.com/1822/96329013-c7504080-0ffd-11eb-9532-4726f1a1d11b.gif)

Beef IDE Version 0.42.8 (Nightly 10/15/2020) Build fe7d3d80e7b759c46b9fec3cb8435fb2ea9a2a3e

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/2a57d9d447e1b07066fef6e0c563a9a02f435f1b
Also a tip: you can ctrl+c with no selection and it'll copy the entire current line, then you can just ctrl+v in-place (cursor doesn't even have to be on the line start) and it'll insert that copied line.

**Comment by sgraham** [comment]
Thanks! The no select version is great, but old muscle memory dies hard sometimes.
