### ISSUE TITLE
[Feature request] infer nullable type in method argument

### ISSUE THREAD

**Issue by lukpank** [beefytech/Beef#61]
In the following program (a) is not allowed and causes `Type of conditional expression cannot be determined because there is no implicit conversion between 'int' and 'null'`, but somehow (b) works without explicit cast and it seems to be a similar context to (a). But one can use explicit cast such as in (c) or (d) so (a) would be just a small convenience.  In C# (mono at least) even (b) and (d) does not work. Also method overloading may make the requested feature problematic. So that is just a proposal.

```csharp
using System;

namespace Issue
{
	public class Program
	{
		public static int Main(String[] args)
		{
			int i = 3;

			// (a) not allowed
			F((i != 0) ? i : null);

			// (b)
			int? j = (i != 0) ? i : null;
			F(j);

			// (c)
			F((i != 0) ? (int?)i : null);

			// (d)
			F((int?)((i != 0) ? i : null));

			return 0;
		}

		static void F(int? i)
		{
		}
	}
}
```

**Comment by bfiete** [comment]
Now (a) is allowed. https://github.com/beefytech/Beef/commit/a8d57c5d28593fff1a12f265a9cb16ec92029af8

This works with method overloading, as well. Beef has a kind of deferred evaluation for certain argument expressions where method overloads that cause errors when evaluating an argument expression will be rejected for method selection.

The most obvious use of this is when you have overloads with different kinds of delegate types and you pass in a lambda - the method overloads with delegate types with differing numbers of arguments (for example) will be rejected.

**Comment by bfiete** [comment]
BUT- (a) will still not bind to a "void F<T>(T? i)".
