### ISSUE TITLE
[BUG] Dictionary inside value type causes data cycle

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#611]
Value type containing Dictionary with this type as Key/Value causes data cycle error.
Example code to reproduce:
```
struct Foo
{
    public static Dictionary<String, Foo> bar = new .() ~ delete _;
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/d46c60d956ccdb0fafc781ed9cb87bd9969615c7
