### ISSUE TITLE
[BUG] Crash on git update with IDE open

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#618]
I didn't actually witness this crash, I did a git update in the morning on my project and several hours later, while doing my normal job, I noticed that Beef had 2 window indicators and when I checked, the 2nd window was a crash dialog with the following dump.

[crash-gitupdate.zip](https://github.com/beefytech/Beef/files/5402864/crash-gitupdate.zip)

cdb060a..af8d3c3

**Comment by bfiete** [comment]
This also a dup of another bug fixed yesterday.
