### ISSUE TITLE
0.42 b49ee65  IDE  -- Provide a means to dynamically change the UI scale.

### ISSUE THREAD

**Issue by jhenzie** [beefytech/Beef#62]
It would be nice to boost the font size dynamically, say [Ctrl -] and [Ctrl +],  on a per editor basis.

Even if observing the DPI scaling across different monitors, this is still a useful function when looking at code across a video link, say.

Implementing this would certainly provide a work around for observing the DPI scaling across monitors, which, IIRC, is a much more complex problem.

Attached image illustrates VS implementation of such and is illustrative rather than an endorsement of said product <wink/>
![UI_Scaling](https://user-images.githubusercontent.com/21959/75359458-56141f80-58ac-11ea-8015-d67a8fa0347c.png)

**Comment by RogueMacro** [comment]
@bfiete This exists in the current version of Beef
