### ISSUE TITLE
[BUG] Adding extension class that changes the data generates a memory leak

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#620]
Texture is define in framework, if I add an extension from OpenGL project, it reports that GL_Texture was leaked (GL_Texture is a instance of Texture.Platform and is a Implementation field member of texture).

```
public extension Texture
	{
		public uint32 asdf;
	}
```

1eeddd6

EDIT: If you comment out that extension code, the memory leak goes away.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/49a4536e1e7d2c0f36959463c3fbc737a0f23c78
