### ISSUE TITLE
[Enhancement] Better support for extern linking across projects that provide implementations

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#621]
This would allow to easily define a class defintion in one project and implementing it in another project. For example, defining a basic texture interface in the core framework and then defining the implementation in another project for opengl or directx.

The current workaround for this scenario is to manually specify `LinkerName` on both projects and mark the implementation method as `AlwaysInclude`.

Base project
```
public class Texture 
{
  [LinkerName("SetData)]
  public extern void SetData(void* buffer)
}
```

OpenGL project
```
public extension Texture
{
  public readonly uint32 ID;
  private GLEnum glFormat;
  private GLEnum glType;

  public this()
  {
    GL.GenTextures(1, &ID);
  }

  [LinkName("SetData")]
  [AlwaysInclude]
  public void SetData(void* buffer)
  {
    GL.ActiveTexture(GL.GL_TEXTURE0);
    GL.BindTexture(GL.GL_TEXTURE_2D, ID);
    GL.TexSubImage2D((.)GLEnum.TEXTURE_2D, 0,0,0,0,0, (.)glFormat, (.)glType, data);
  }
}
```

**Comment by xposure** [comment]
For reference in case anyone comes across this, this is now possible in the latest nightly.

```
public class Texture 
{  
  public extern void SetData(void* buffer)
}
```

OpenGL Project
```
public extension Texture
{
  public readonly uint32 ID;
  private GLEnum glFormat;
  private GLEnum glType;

  public this()
  {
    GL.GenTextures(1, &ID);
  }

  public override SetData(void* buffer)
  {
    GL.ActiveTexture(GL.GL_TEXTURE0);
    GL.BindTexture(GL.GL_TEXTURE_2D, ID);
    GL.TexSubImage2D((.)GLEnum.TEXTURE_2D, 0,0,0,0,0, (.)glFormat, (.)glType, data);
  
```

**Comment by xposure** [comment]
[beef-extern.zip](https://github.com/beefytech/Beef/files/5435454/beef-extern.zip)

112c37d

While this code isn't correct, its producing a build crash.

**Comment by xposure** [comment]
Properties produce a "already defined" error.

4d9a431

**Comment by bfiete** [comment]
That Issue from yesterday should be fixed, and properties support are included now at https://github.com/beefytech/Beef/commit/71f5448f32e9d0ea3d0a9789243ea39a9ce62b06
