### ISSUE TITLE
[BUG] Access modifiers appear to be valid inside of an interface

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#624]
This appears valid but if you actually tried to use it, it would say that the interface isn't implemented (unless you of course made the implementation public).

```
	public interface ITexture
	{
		uint ID { get; }

		protected void SetData(void* buffer, int x, int y, int w, int h);
	}
```

**Comment by bfiete** [comment]
Access specifiers for interface members were allowed in C# 8. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods

The basic idea is that default interface methods can create new methods inside of a concrete type, and the access specifier can  determine what protection that created method will have. But, yes, it doesn't make sense unless there's actually a method body specified so it shouldn't be allowed in those cases.

**Comment by bfiete** [comment]
These will produce warnings now when there's no method body https://github.com/beefytech/Beef/commit/5167298ab2508f642c1ceb0a8220619f06511b93

Will upgrade to errors later.
