### ISSUE TITLE
[BUG] function inside function does not correctly report build errors

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#625]
c3d5a72

```

		private void Initialize()
		{
			_graphics.ProcessCommands(scope => Init);
			void Init()
			{
				GL.GenTextures(1, &_id);
				using (PushTexture(_id, 0))
				{
					GL.TexImage2D((.)GLEnum.TEXTURE_2D, 0, Format.GLInternalFormat, Width, Height, 0, Format.GLFormat, Format.GLType, null);
					GL.TexParameteri((.)GLEnum.TEXTURE_2D, (.)GLEnum.TEXTURE_MIN_FILTER, Filter.GLType);
					GL.TexParameteri((.)GLEnum.TEXTURE_2D, (.)GLEnum.TEXTURE_MAG_FILTER, Filter.GLType);
					GL.TexParameteri((.)GLEnum.TEXTURE_2D, (.)GLEnum.TEXTURE_WRAP_S, WrapX.GLType);
					GL.TexParameteri((.)GLEnum.TEXTURE_2D, (.)GLEnum.TEXTURE_WRAP_T, WrapY.GLType);
				}
			}
		}

```

If you go to `GL_Texture` and look at the `public extension Texture` you'll notice that I've commented out `_id` but yet the code inside `void Init()` shows that its valid. If you run a build it will report the the identifier not found error.

EDIT: After taking the latest nightly, its reporting the errors now, perhaps it was resolved.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/4449952235cbbf4bfc24bbae2262ddc036b25a08

**Comment by bfiete** [comment]
I did find an issue here that would cause the IDE to not show an error squiggle, but it did seem that a compile would have properly generated an error, and I couldn't get it not to. Hoping it was related somehow.
