### ISSUE TITLE
[Enhancement] Allow method information (//) to stand above attribute (IDE)

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#626]
You can comment a function by putting two slashes in the line above it, but if you try to do that above a function with an attribute it doesnt register. Instead you have to put the two slashes in the line under the function with looks extremely weird.
Being able to put the comment above it would be the expected way of how to do it and I would like if there was support for it.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/bf5e68902943d330304012bed5b44be978975e88
