### ISSUE TITLE
[BUG] Immediate window crashes if accessing an internal access modifier

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#628]
130deb3

If you break on this line and type `Filter.GLType` in the immediate window it will crash.

![image](https://user-images.githubusercontent.com/6292318/96648964-32e82580-12fe-11eb-922f-bba1cda44db0.png)

**Comment by bfiete** [comment]
Crash fixed at https://github.com/beefytech/Beef/commit/b16f8b303ea147d029e05dab25618fbfefb366f3
Although "Filter.GLType" doesn't evaluate still. That's a different issue.

**Comment by xposure** [comment]
I scrapped all that code anyways ;)
