### ISSUE TITLE
Unable to concantate 2 constant Strings

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#63]
This example,

```
const String base = "Sound/";
const String sound1 = base + "Sound1.wav";
const String sound2 = base + "Sound2.wav";
const String sound3 = base + "Sound3.wav";
const String sound4 = base + "Sound4.wav";
// etc..
```

Cannot perform binary operation '+' between two instances of type 'System.String'.

The error of course makes sense, but it would be super useful to allow for constants.

**Comment by bfiete** [comment]
In https://github.com/beefytech/Beef/commit/c92bc523db3178a0834ae7c4794e1cd43c3afc27.

Also fixed some other bugs related to const strings.

**Comment by damianday** [comment]
Excellent thanks!
