### ISSUE TITLE
[Enhancement] Option for "find in finds" to not search locked projects

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#634]
![image](https://user-images.githubusercontent.com/6292318/97114069-b621c680-16c4-11eb-8807-65b1d24eb0ba.png)

Was trying to find all my code that was still using `LinkName` but there is no way to filter out corlib, so it returned a ton of results.

EDIT: Correction, the results were from SDL + ImGui, but none the less, these are still locked projects that I wouldn't want to search.

**Comment by bfiete** [comment]
Added at https://github.com/beefytech/Beef/commit/710d7636d698c1ebe556928f9803a66f88635f16
