### ISSUE TITLE
[Bug] Scrollbar not working for autocomplete

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#636]
It just closes the autocomplete-window when I click the scrollbar

**Comment by bfiete** [comment]
Seems to work fine for me, I can't seem to reproduce this behavior.

**Comment by RogueMacro** [comment]
Seems I can't reproduce it either. It might have been fixed in the latest nightly

**Comment by bfiete** [comment]
Reopen if you find a way to reproduce this.

**Comment by RogueMacro** [comment]
It's back. I'm not sure what causes it, but it seems to be file dependent. It might have been here for a while since I never really use the scrollbar anyway.

**Comment by RogueMacro** [comment]
If there's an error on the same line it causes the autocomplete to disappear when trying to drag the scrollbar

**Comment by RogueMacro** [comment]
Or rather, this line: `bgfx.set_texture(0, _uTexColor, sprite.Texture, (.) (.MinPoint | .MagPoint | .MipPoint | .UClamp | .VClamp));`
Where the .MinPoint | .MagPoint etc, is underlined with an unqualified dot syntax error, and I try using autocomplete within the same parameter of the function. Like after the last comma and before the parenthesis.
