### ISSUE TITLE
Compiler segfault when let binded delegate (capturing object) is given as argument of generic method

### ISSUE THREAD

**Issue by lukpank** [beefytech/Beef#64]
In the following program `let dlg` is not allowed but it triggers the compiler error together with two conditions:

1.  `dlg` captures an object from `Main` (might also be a method call such as `p.M2()` even if `M2` does not exist),

2. `p.M()` call is not explicitly specialized with some type.

```csharp
using System;

namespace Issue
{
	public class Program
	{
		public static int Main(String[] args)
		{
  			let p = new Program();
			let dlg = new (obj) => {
				Console.WriteLine("{}", p);
			};
			p.M(dlg);
			return 0;
		}

		public void M<T>(delegate void(T obj) dlg)
		{
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed crash in https://github.com/beefytech/Beef/commit/bb34a468bbe6ed9e59f004eabfdb1aa2bec515bf
