### ISSUE TITLE
[Discussion] Supporting string interpolation

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#640]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

I'm curious if something like this could be implemented behind the scenes. Please excuse the over simplification.

```
public static void Test(){
    let x = true;
    let y = 1;
    let z = DateTime.Now;
    let s = scope $"x: {x}, y: {y}, z: {z:HH:mm}";
    Console.WriteLIne(s);
}
```

Could in theory be translated in to...

```
public static void Test(){
    let x = true;
    let y = 1;
    let z = DateTime.Now;
    let s = scope String();
    s.AppendF("x: {0}, y: {1}, z: {2:HH:mm}", x, y, z);
    Console.WriteLIne(s);
}

```
And of course if you used `new` or a different allocator it should be easy to modify.

And of course you would want this to work as well...

```
public static void Test(){
    let x = true;
    let y = 1;
    let z = DateTime.Now;
    Console.WriteLIne(scope $"x: {x}, y: {y}, z: {z:HH:mm}");
}

```

This would save my precious fingers from having to type the StackAlloc mixin and then always doing the same `"{0}"` etc which is used heavily for quick tests (or ImGui usage).

**Comment by RogueMacro** [comment]
Another way to write it is using cascading member access (Dot Dot syntax):
```cs
public static void Test(){
    let x = true;
    let y = 1;
    let z = DateTime.Now;
    let s = scope String()..AppendF("x: {0}, y: {1}, z: {2:HH:mm}", x, y, z);;
    Console.WriteLIne(s);
}
```

But I think that string interpolation isn't a bad idea and could be implemented. @bfiete Thoughts?

**Comment by bfiete** [comment]
Added at https://github.com/beefytech/Beef/commit/281f19e04c9dd2e5821f7902e1ef9136122a14ee

There are two kinds - allocation and argument expansion. The allocation interpolation works just as you described. The argument expansion style works like `Console.WriteLine($"x = {mX} y = {mY}")` which expands to `Console.WriteLine("x = {} y = {}", mX, mY)`.
