### ISSUE TITLE
IDE enhancements

### ISSUE THREAD

**Issue by Ivo-Balbaert** [beefytech/Beef#646]
1) The menu-item Build uses the term Build Solution.
    As far as I know, the term Solution is nowhere else used.
    Should "Build Solution" be replaced with "Build Workspace" ?

2) It would be nice to have a Comment Toggle feature, so that you could select a piece of code
    and comment it out with a key combination, and or a right-click menu-item and or a menu-item under Edit

**Comment by xposure** [comment]
2. ctrl-k/c and ctrl-k/u will comment and uncomment selected code (same as vs)

**Comment by bfiete** [comment]
Renamed to "Build Workspace" at https://github.com/beefytech/Beef/commit/6afaf4faadc10ecbea885958e543deb7fe625ada
Also added the Comment/Uncomment Selection to Edit/Advanced menu
