### ISSUE TITLE
[BUG] Crash after typing '{'

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#648]
IDE will crash when i type `{` after `public ~this() `
IDE version: **Version 0.42.8 (Nightly 11/01/2020) built 11/1/2020 at 8:58 PM**

```csharp

	public class Menu
	{
		Button b;

		public this()
		{
			b = new 
		}

		public ~this() 



		public void Render()
		{
			
		}

		public void Update()
		{
		}

		public Vector2 GetCenter() => .(GetScreenWidth() / 2, GetScreenHeight() / 2);
	}

```

**Comment by Ivo-Balbaert** [comment]
I don't have the code for Button or Vector 2 , b = new seems suspicious. If I comment these out, I don't get the crash after typing {
Same version of Beef.

**Comment by bfiete** [comment]
Did you get a crash or a freeze?

**Comment by bfiete** [comment]
Assuming you meant freeze - fixed at https://github.com/beefytech/Beef/commit/6302b5e2475af75148843fcd344eb6655d9f434c
