### ISSUE TITLE
[Bug] IDE crash when renaming symbol

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#650]
When I hit Ctrl-R to rename a symbol, often the IDE crash. Not all the time, but mostly. Don't know exactly when.
[crash.zip](https://github.com/beefytech/Beef/files/5505252/crash.zip)

The project zip was a little too big, so if you can't reproduce and want the project, I can send it to you.

I'm on the current nightly (11/06/2020)

**Comment by bfiete** [comment]
Ah- this was an assert I put in to find a bug @xposure had reported with unsaved buffers and git updates not 'taking'. I think it may all make sense now.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/330eb037e8698816dfdb9ae9303816f41046b0cc

@xposure This should resolve the file saving/reloading issues you had. Rename has slightly different behavior now - when you rename a symbol in a file that you do not have an editor panel open for then that change is immediately applied to the file itself. Previously it was stored in an invisible "unsaved buffer" and only got saved when you performed a Save All.

**Comment by xposure** [comment]
Excellent, I'll keep a look out for this.
