### ISSUE TITLE
[BUG] "Rename Symbol" issue

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#653]
When a comment above a class was modified "Rename Symbol" will replace some code with the class-name depending on how many characters were added/removed.

Example:
```C#
// comment
class MyClass {}
```
Add four characters to the comment:
```C#
// comment1234
class MyClass {}
```
Use "Rename Symbol" on "MyClass":
```C#
// comment1234
clMyClasslass {}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/22cc81862b4100db6f266481c709271878199eef
