### ISSUE TITLE
[BUG] Generic constraint, array object member not found

### ISSUE THREAD

**Issue by Booklordofthedings** [beefytech/Beef#655]
When having a generic class contraint that T inherits from another class you are unable to acess
a public member of the base class from an array of T.

//Sourcecode
[Program.zip](https://github.com/beefytech/Beef/files/5538674/Program.zip)
 (Version 0.42.7)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/234b3591eb91b8b51efc46c499a3ac65d7037f61
