### ISSUE TITLE
[Bug] LinkName Attribute does not apply (.CPP) correctly to extern static variables

### ISSUE THREAD

**Issue by taxmancw** [beefytech/Beef#658]
Using `[LinkName(.CPP)]` on a static variable results in the same mangled symbol as `[LinkName(.Beef)]`

`[LinkName(.C)]` and `[LinkName("CustomName")]` on the other hand, work correctly.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/ca3308d9591d3e5b986a11f43404b31dd400d92c
