### ISSUE TITLE
[BUG] Crash on build (declBegin > declEnd)

### ISSUE THREAD

**Issue by jazzbre** [beefytech/Beef#659]
[Repo.zip](https://github.com/beefytech/Beef/files/5543020/Repo.zip)
Beef Version 0.42.8 (Nightly 11/12/2020) built 11/12/2020 at 8:57 PM.

Callstack:
`>	Beef042RT64.dll!Beefy::CrashCatcher::Crash(const Beefy::StringImpl & str) Line 1146	C++	Symbols loaded.
 	IDEHelper64_d.dll!BfpSystem_FatalError(const char * error, const char * title) Line 1078	C++	Symbols loaded.
 	IDEHelper64_d.dll!Beefy::BFFatalError(const Beefy::StringImpl & message, const Beefy::StringImpl & file, int line) Line 416	C++	Symbols loaded.
 	IDEHelper64_d.dll!Beefy::BFFatalError(const char * message, const char * file, int line) Line 1264	C++	Symbols loaded.
 	IDEHelper64_d.dll!Beefy::BeCOFFObject::DbgStartVarDefRange(Beefy::BeDbgFunction * dbgFunc, Beefy::BeDbgVariable * dbgVar, const Beefy::BeDbgVariableLoc & varLoc, int offset, int range) Line 1035	C++	Symbols loaded.
 	IDEHelper64_d.dll!Beefy::BeCOFFObject::DbgOutputLocalVar(Beefy::BeDbgFunction * dbgFunc, Beefy::BeDbgVariable * dbgVar) Line 1288	C++	Symbols loaded.
 	IDEHelper64_d.dll!Beefy::BeCOFFObject::DbgOutputLocalVars(Beefy::BeInlineLineBuilder * curInlineBuilder, Beefy::BeDbgFunction * dbgFunc) Line 1354	C++	Symbols loaded.
 	IDEHelper64_d.dll!Beefy::BeCOFFObject::DbgGenerateModuleInfo() Line 1576	C++	Symbols loaded.
 	IDEHelper64_d.dll!Beefy::BeCOFFObject::Generate(Beefy::BeModule * module) Line 2117	C++	Symbols loaded.
 	IDEHelper64_d.dll!Beefy::BeCOFFObject::Generate(Beefy::BeModule * module, const Beefy::StringImpl & fileName) Line 2136	C++	Symbols loaded.
 	IDEHelper64_d.dll!Beefy::BfCodeGenThread::RunLoop() Line 453	C++	Symbols loaded.
 	IDEHelper64_d.dll!RunLoopThunk(void * codeGenThreadP) Line 583	C++	Symbols loaded.
`

The problem is these 4 lines in SpriteRenderer.bf (line 59+):
`					vertices[i + 0] = Vector3(0.0f, 0.0f, instanceIndex);
					vertices[i + 1] = Vector3(1.0f, 0.0f, instanceIndex);
					vertices[i + 2] = Vector3(1.0f, 1.0f, instanceIndex);
					vertices[i + 3] = Vector3(0.0f, 1.0f, instanceIndex);`

Repo case: just unpack the repo, open the workspace and build via F7...

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/e2de5becab3b89d54847b1f66785446c86947316
