### ISSUE TITLE
[Enhancement] Ctrl-/ comment hotkey with different behavior

### ISSUE THREAD

**Issue by C34A** [beefytech/Beef#660]
I know about the Ctrl-K, Ctrl-C thing to comment out a block, but I find it not as convenient as the more popular Ctrl-/ functionality in other editors. Specifically, in other editors using the comment hotkey will put a // at the beginning of each line you have even partially highlighted, so it is possible to simple highlight a few lines with shift-up/down and do a ctrl-/ to comment them all out. With the way that Ctrl-K, Ctrl-C currently works in the beef editor this will make a multiline comment block that doesn't necessarily include everything on the start/end lines, making it more time consuming to comment out a particular bit of code. I know this is a nitpick, but this has been pretty much the only thing I dislike about the beef editor so I figured I'd bring it up.

**Comment by bfiete** [comment]
The current behavior is the way Visual Studio works, which is the primary target audience.

**Comment by bfiete** [comment]
VS also has a "Toggle Comment" hotkey but it does not do the whole-line selection you're requesting...

**Comment by C34A** [comment]
Yeah, I know. I was thinking it would be nice to have as another option (not default), for those used to other IDEs.

**Comment by marsej** [comment]
I was about to post this same bug. 
In VS 2019 C++, If sometthing is selected it ctrl+k+c comments with /* */. 
If nothing is selected ctrl+k+c it adds // to beginning of the line, which is what I'd prefer. Beef IDE doesn't do this.

**Comment by marsej** [comment]
I made the following change and now it works more closer to VS.

0.43.0 SourceEditWidgetContent.bf l 2158

```cs
		public bool ToggleComment(bool? doComment = null)
		{
			if (CheckReadOnly())
				return false;
+			bool noStar = false;
			if ((!HasSelection()) && (doComment != null))
			{
				CursorToLineEnd();
				int cursorEndPos = CursorTextPos;
				CursorToLineStart(false);
				mSelection = .(CursorTextPos, cursorEndPos);
+				noStar = true;
			}

			if ((HasSelection()) && (mSelection.Value.Length > 1))
			{
				var startLineAndCol = CursorLineAndColumn;

				UndoBatchStart undoBatchStart = new UndoBatchStart("embeddedToggleComment");
				mData.mUndoManager.Add(undoBatchStart);

				mData.mUndoManager.Add(new SetCursorAction(this));

				int minPos = mSelection.GetValueOrDefault().MinPos;
				int maxPos = mSelection.GetValueOrDefault().MaxPos;
				mSelection = null;

				var str = scope String();
				ExtractString(minPos, maxPos - minPos, str);

				var trimmedStr = scope String();
				trimmedStr.Append(str);
				int32 startLen = (int32)trimmedStr.Length;
				trimmedStr.TrimStart();
				int32 afterTrimStart = (int32)trimmedStr.Length;
				trimmedStr.TrimEnd();
				int32 afterTrimEnd = (int32)trimmedStr.Length;

				int firstCharPos = minPos + (startLen - afterTrimStart);
				int lastCharPos = maxPos - (afterTrimStart - afterTrimEnd);
+				if ((doComment != true) && (trimmedStr.StartsWith("//")))
+				{
+					mSelection = EditSelection(firstCharPos, firstCharPos + 2);
+					DeleteChar();
+				}
				if ((doComment != true) && (trimmedStr.StartsWith("/*")))
				{
					if (trimmedStr.EndsWith("*/"))
					{
						mSelection = EditSelection(firstCharPos, firstCharPos + 2);
						DeleteChar();
						mSelection = EditSelection(lastCharPos - 4, lastCharPos - 2);
						DeleteChar();

						if (doComment != null)
							mSelection = EditSelection(firstCharPos, lastCharPos - 4);
					}
				}
				else if (doComment != false)
				{
+					CursorTextPos = firstCharPos;
+					if (noStar) InsertAtCursor("//");
+					else
+					{
+						InsertAtCursor("/*");
+						CursorTextPos = lastCharPos + 2;
+						InsertAtCursor("*/");
+					}
+					if (!noStar && doComment != null)
+						mSelection = EditSelection(firstCharPos, lastCharPos + 4);
				}

				if (undoBatchStart != null)
					mData.mUndoManager.Add(undoBatchStart.mBatchEnd);

				CursorLineAndColumn = startLineAndCol;

				if (doComment == null)
					mSelection = null;

				return true;
			}

			return false;
		}
```

**Comment by bfiete** [comment]
We have this now with "Comment Lines". The default binding is "Ctrl+K, Ctrl+/"
