### ISSUE TITLE
[BUG] Crash on hot reloading

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#661]
I get this one quite frequently and completely random.

[hot-reload.zip](https://github.com/beefytech/Beef/files/5555431/hot-reload.zip)

**Comment by bfiete** [comment]
Could you send your GameSim_lld.pdb file? It appears to be a parsing issue with one of the debug modules inside there but it doesn't reproduce on my side...

**Comment by xposure** [comment]
I haven't had a crash since I updated 11/18 to the latest nightly. I will let this open over the weekend and close it on Monday if I'm still crash free on hot reload.

**Comment by bfiete** [comment]
(closing out non-recent raw crash reports)
