### ISSUE TITLE
[BUG] Implicit cast to int fails on array index

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#664]
Unfortunately I did not document this one and don't remember the exact context/usage. The short version is, I have a struct, enum, or something that should have been able to implicit cast to int and used as an index to an array, aka `let someArray = float[100]; let x = someArray[implicitIntCast];` and had a compiler error that it couldn't implicit cast to int.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/8f59a9dc0afa54ff1690f372d8f2bc6db754b48c
