### ISSUE TITLE
[Enhancement] Allow trailing commas in certain scenarios

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#667]
https://stackoverflow.com/questions/8253413/why-c-sharp-4-0-tolerates-trailing-comma-in-anonymous-objects-initialization-cod
https://stackoverflow.com/questions/26865030/why-does-c-sharp-allow-trailing-comma-in-collection-initializers-but-not-in-para
http://blog.mediawhole.com/2010/07/c-object-initialisers-and-trailing.html

Here are a few links where c# spec allows trailing commas, there are probably more though. I think I seen a proposal for it in method signatures too, but that could be dangerous.

EDIT: The most useful place I would see this is in array initialization, there are times when you are messing with array ordering and copy/pasting lines around and constantly have to move/add/delete commas to make it compile.

**Comment by bfiete** [comment]
They are allowed in array initialization. Do you have an array initialization case you can post where they don't work?

**Comment by bfiete** [comment]
These are also allowed in object initializers already, too. What's the case there where you see them not working when they should?

**Comment by xposure** [comment]
Hrm I will have to keep an eye out for this, the other day I was going back and forth with commas and today I tested it and it worked as expected, so its possible that I'm losing my mind...

**Comment by bfiete** [comment]
Did you see this again or were you just losing your mind?

**Comment by xposure** [comment]
I think I was just losing my mind, I'll close it and keep an eye out for it.
