### ISSUE TITLE
[Bug] Beef functions called from C crash or produce invalid result

### ISSUE THREAD

**Issue by jazzbre** [beefytech/Beef#670]
I've attached two repo cases, the first is setting a function pointer into a CRepr struct Config and passing it to a C function where it's called (and returning another CRepr struct with float r,g,b,a), but crashes upon entering back to C.
[ReturnTest.zip](https://github.com/beefytech/Beef/files/5569228/ReturnTest.zip)

The second is similar, the Config struct now contains two functions, first is a function pointer that returns int32 and the second is the same as in the first repo case. The C code then calls the int32 function with success (returns the right value), and then the function returning the x,y,z,w struct is called which now doesn't crash, but when printing you can observe random data is written.
[ReturnTest2.zip](https://github.com/beefytech/Beef/files/5569240/ReturnTest2.zip)

It's pretty straight forward that's why I'm not sure if I'm doing something wrong here.

Thanks!

(In both cases you need to open cproj/cproj.sln and build Debug|x64 and  open and run the beef project)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/84a0cf329f6775bd14039c891b3138fbaf2f302c

**Comment by bfiete** [comment]
Thanks for the nice repro!
