### ISSUE TITLE
[BUG] "Identifier not found" error when creating a typealias to an array using const for size

### ISSUE THREAD

**Issue by thibmo** [beefytech/Beef#671]
When creating a typealias you are able to alias an array of<type> with and without specifying the array's size.
This seems to error out whenever you use a const to specify the size of the array.

Error message:
![image](https://user-images.githubusercontent.com/12035362/99847065-c324bf00-2b77-11eb-8696-3cf80b9f7f29.png)

Repro code:
```cpp
namespace Sample
{
    class Test
    {
        public const int TABLE_BYTE_LEN = 272;
        public const int TABLE_WORD_LEN = TABLE_BYTE_LEN / 4;

        public typealias TYPE_TEST = uint[];
        public typealias TYPE_TEST_LITERAL = uint[272 / 4];
        public typealias TYPE_TEST_CONST = uint[TABLE_WORD_LEN];
    }
}
```

**Comment by bfiete** [comment]
Fixed a while back.
