### ISSUE TITLE
[BUG] Null exception when accessing virtual prop

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#672]
851c987fafa73f2fa361dc3ad2210cbda02b0710

```
		public virtual bool Track => false;
```

![image](https://user-images.githubusercontent.com/6292318/99864383-fca5fc00-2b70-11eb-9be1-ba17c61c1b60.png)

**Comment by bfiete** [comment]
Did you push the commit that was supposed to have this bug?

**Comment by xposure** [comment]
Oops forgot to push to github. Its there now.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/b83bc2c2dc801aabd330a2ebce2f4c9738f45fe5
The game is starting to look like a game now! Nice.
