### ISSUE TITLE
[BUG] Folder is hiding files?

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#674]
37052a3

I'm not sure how the beef project got in the state its in, but the Scene folder is blue and doesn't show MainMenuScene or SimpleScene in the IDE. If you right click scene and `Auto Include` it, the files missing come back but the folder is still marked blue and appears in the beef project file.

EDIT: Based on our discussion this may be working as intended but I'm not sure how the project got in this state and I also think it may be confusing to hide these files in that folder that are really there. I'm also not sure how to remove this "manual" entry other than manually editing the project file which leads to further confusion on how I got here.

**Comment by xposure** [comment]
Based on further discussion its a serialization issue. If you fix the project file by removing those ignore entries and then reload the project and remove the 3 files again, close + reopen the project once again, the project is marking the Scene folder as manually included.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/5fd037bc581c42a185769ed855f63e977d7ae438
