### ISSUE TITLE
[BUG] Possible incorrect warning 472

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#675]
7380e09

If you build this project you will see 3 warnings from 

```
		public void GetAll<T>(List<T> list) where T : Component
		{
			for (var component in _components)
				if (var it = component as T) //warning
					list.Add(it);
		}
```

This doesn't appear correct as T can be anything that comes from `Component` and the component may not be castable to T which should return `null` right?

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/b264d7e4cb3beb5b1608f12f7a6c63da9959a25e
