### ISSUE TITLE
25MB LLVM source code zip file instead of full LLVM git clone

### ISSUE THREAD

**Issue by apg360** [beefytech/Beef#679]
Hi,

it is very painful to git clone llvm and build it. Not mentioning that it weight 2GB download and even more generated on disk when compiling.

My question, will it work if I rather use the 25MB  LLVM source code zip file found here https://releases.llvm.org/download.html#11.0.0 ???

Second question please, would it be possible to rather use pre-built LLVM binaries instead of only source code as only option. For example on MacOS one could be able to use "clang+llvm-9.0.1-x86_64-apple-darwin.tar.xz"

Please let me know

Kinds regards

**Comment by apg360** [comment]
This : https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-11.0.0.src.tar.xz

And NOT this : git clone https://github.com/llvm/llvm-project.git

Please advise

**Comment by Green-Sky** [comment]
you can use a shallow clone with `--depth 1 --branch llvmorg-11.0.0` as a quick hack. downloads less than 1gig this way...

**Comment by apg360** [comment]
Awesome thank you. 
As of right now, I successfully have the full git clone (2.2GB) but failing to compile it in MacOS 10.15.7 ....
cmake ../
make

Here error output  :
```
Scanning dependencies of target llvm-mt
[ 94%] Building CXX object tools/llvm-mt/CMakeFiles/llvm-mt.dir/llvm-mt.cpp.o
[ 94%] Linking CXX executable ../../bin/llvm-mt
Undefined symbols for architecture x86_64:
  "_xmlNewNs", referenced from:
      searchOrDefine(unsigned char const*, _xmlNode*) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlFreeNs", referenced from:
      checkAndStripPrefixes(_xmlNode*, std::__1::vector<_xmlNs*, std::__1::allocator<_xmlNs*> >&) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlDocSetRootElement", referenced from:
      llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest() in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlNewDoc", referenced from:
      llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest() in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlFreeDoc", referenced from:
      llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest() in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
      llvm::windows_manifest::WindowsManifestMerger::~WindowsManifestMerger() in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlCopyNamespace", referenced from:
      treeMerge(_xmlNode*, _xmlNode*) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlAddChild", referenced from:
      treeMerge(_xmlNode*, _xmlNode*) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlFree", referenced from:
      treeMerge(_xmlNode*, _xmlNode*) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
      llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest() in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
      llvm::windows_manifest::WindowsManifestMerger::~WindowsManifestMerger() in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlSetGenericErrorFunc", referenced from:
      llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge(llvm::MemoryBuffer const&) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlUnlinkNode", referenced from:
      stripComments(_xmlNode*) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
      treeMerge(_xmlNode*, _xmlNode*) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlKeepBlanksDefault", referenced from:
      llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest() in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlFreeNode", referenced from:
      stripComments(_xmlNode*) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlNewProp", referenced from:
      treeMerge(_xmlNode*, _xmlNode*) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlDocDumpFormatMemoryEnc", referenced from:
      llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest() in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlStrdup", referenced from:
      treeMerge(_xmlNode*, _xmlNode*) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlReadMemory", referenced from:
      llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge(llvm::MemoryBuffer const&) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
  "_xmlDocGetRootElement", referenced from:
      llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge(llvm::MemoryBuffer const&) in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
      llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest() in libLLVMWindowsManifest.a(WindowsManifestMerger.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/llvm-mt] Error 1
make[1]: *** [tools/llvm-mt/CMakeFiles/llvm-mt.dir/all] Error 2
make: *** [all] Error 2
a0@GRgr llvm_linux_rel_11_0_0 %
```

Any clue or advise on this error will be much appreciated.


Meanwhile, I am very interested to know if : 
would it be possible to rather use pre-built LLVM binaries instead of only source code as only option. For example on MacOS one could be able to use "clang+llvm-9.0.1-x86_64-apple-darwin.tar.xz"

That will really make easier to compile beef (use llvm pre-built binaries) and have beef ready in no time, without the long journey of llvm source compilation.

Is that possible now ? if not then something possible in future ? or else there is really no other choice than using llvm source code compilation to use beef

**Comment by Green-Sky** [comment]
I have no clue for your problem :(.
Also keep in mind, that building llvm requires >25gig space on your disk, and >12gig ram on linux while linking a executable...

**Comment by apg360** [comment]
> I have no clue for your problem :(.
> Also keep in mind, that building llvm requires >25gig space on your disk, and >12gig ram on linux while linking a executable...

Ohhhh my goodness ! I did not know that .....
Why does beef developer not stick with llvm pre-built binaries then. They are making incredibly difficult to get started with Beef. 

If really no other choice than using full LLVM git clone, then they can do a fedora/ubuntu VM in windows and voilà have beef setup binary for linux.

**Comment by apg360** [comment]
Undefined symbols for architecture x86_64:
  "_xmlNewNs", referenced from:

_xmlNewNs = libxml2

My error is related to linking MacOS libxml2 while building LLVM.
https://stackoverflow.com/questions/23856167/apple-mach-o-linker-error-objective-c/23856204#23856204

Special thanks to "[SR] ThibmoRozier" at Beef Discord chat

Will try again and revert back so it can help anyone trying Beef on something else than Windows.

**Comment by apg360** [comment]
Using 25MB source code zip file

This : https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-11.0.0.src.tar.xz
And NOT this : git clone https://github.com/llvm/llvm-project.git

Seems to work so far .... once finalized and works 100%, I will make contribution change so everyone can enjoy a lighter process and have Beef running in no time.

Will keep this post with latest info for record.

**Comment by apg360** [comment]
Here are the pull request : 
[#681](https://github.com/beefytech/Beef/pull/681) : Update X86.cpp
[#682](https://github.com/beefytech/Beef/pull/682) : Update X64.cpp
[#683](https://github.com/beefytech/Beef/pull/683) : No need of the 2.2GB full LLVM git clone

**Comment by apg360** [comment]
Special thanks to @bfiete
