### ISSUE TITLE
segfaults on macos with BeefBuild -run

### ISSUE THREAD

**Issue by bentxt** [beefytech/Beef#684]
Hi

After hours building Beef from source, I finally have the binaries. BeefBuild -new works but BeefBuild -run fails

Error:
```
BeefBuild -run
fish: 'BeefBuild -run' terminated by signal SIGSEGV (Address boundary error)
```

It's just a simple project

```
tree
.
├── BeefProj.toml
├── BeefSpace.toml
├── build
│   └── Debug_macOS
│       └── foo
└── src
    └── Program.bf

4 directories, 3 files

```

```
cat src/Program.bf
using System;
namespace foo{
	class Program{
		public static int Main(String[] args){
			return 0;
		}
	}
}⏎
```

```
 BeefBuild -version
BeefBuild 0.42.7
```

dist is in PATH
```
which BeefBuild
/Volumes/sdapfs/[...]/builds/beef/beef/IDE/dist/BeefBuild
```

**Comment by apg360** [comment]
Hi,

I compiled it yesterday and it worked fine 
beef new, create hello world, beef run

I am busy compiling it again right now (second try from scratch). 
I am on macOS Catalina 10.15.7, what is yours please ?

I believe your issue lie on how exactly you compiled. Especially the LLVM part.
Would you make a summary step by step of all steps you did so I can try to assist

Best regards

**Comment by apg360** [comment]
Finished the new build, here my hello world try :

a0@GRgr dist % sw_vers -productVersion
10.15.7
a0@GRgr dist % ./BeefBuild -version
BeefBuild 0.42.8
a0@GRgr dist % mkdir Hello
a0@GRgr dist % cd Hello 
a0@GRgr Hello % ../BeefBuild -new
Created new workspace in '/Users/a0/Downloads/Beef-master/IDE/dist/Hello'
a0@GRgr Hello % vi src/Program.bf
a0@GRgr Hello % ../BeefBuild -run
Hello, world!
a0@GRgr Hello % 
a0@GRgr Hello % ls      
BeefProj.toml	BeefSpace.toml	_2.txt		build		src
a0@GRgr Hello % cat src/Program.bf 
using System;

namespace Hello
{
    class Program
    {
        static void Main()
        {
            Console.WriteLine("Hello, world!");
        }
    }
}
a0@GRgr Hello %

**Comment by apg360** [comment]
I am on macOS Catalina 10.15.7, what is yours please ?

As I said, your issue might be on how exactly you compiled the stuff. **Especially the LLVM part.**
Would you make a summary step by step of all steps you did so I can try to assist

My method is given here as a Pull request to improve llvm_build.sh [#683](https://github.com/beefytech/Beef/pull/683)


This is what I just finished building now and it works.
If you want to make a try using my method : 
1. Make a fresh download of Beef (Beef-master.zip) and unzip it
2. copy [llvm-11.0.0.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-11.0.0.src.tar.xz) in extern directory
2. modify extern/llvm_build.sh [copy paste text of here](https://github.com/apg360/Beef/blob/patch-4/extern/llvm_build.sh)
3. in bin directory, ./build.sh

**Comment by bentxt** [comment]
```
sw_vers -productVersion
11.0.1
```

aka Bit Sur ...

wrt the build process, I followed the readme and ran

`./bin/build.sh`

**Comment by apg360** [comment]
> ```
> sw_vers -productVersion
> 11.0.1
> ```
> 
> (Big Sur)
> 
> Regarding the build process: There where no (manual) build steps. The only thing I did, I followed the readme and ran
> 
> `./bin/build.sh`

That is not good, my bet is fault is entirely llvm 

build.sh > ../extern/llvm_build.sh > git clone llvm repo

Try my method instead :
1. Make a fresh download of Beef (Beef-master.zip) and unzip it
2. copy [llvm-11.0.0.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-11.0.0.src.tar.xz) in extern directory
2. modify extern/llvm_build.sh [copy paste text of here](https://github.com/apg360/Beef/blob/patch-4/extern/llvm_build.sh)
3. in bin directory, ./build.sh

**Comment by apg360** [comment]
Did you have a chance to try again using my suggestion ?

**Comment by bentxt** [comment]
@apg360 sorry for being silent and absent. I didn't forget my issue here, but I wasnt happy with my findings and then procrastination mode kicked it ...

The thing is the following: in one in your answers you have a hint in a console output that says
`Created new workspace in '/Users/a0/Downloads/Beef-master/IDE/dist/Hello'`

So I also try to call Beefbuild directly relativ to my project workspace. And guess what, it worked!

`../dist/BeefBuild -run`

Now calling BeefBuild via the PATH variable, that seems the thing that don't work. So I'm not exactly sure how to proceed....

**Comment by apg360** [comment]
Wow, fantastic !

Happy days :)

Your issue might be with priorities in PATH, the order on which variable are putted is the order priority.
Do echo $PATH and check once.

**Comment by bentxt** [comment]
Just to make sure there is no misunderstanding I can call BeefBuild from the PATH from anywhere on the filesystem. But here is the weird behavior:

- I can run `BeefBuild -new`
- but it crashes with `BeefBuild -run` (see OP above)

**Comment by apg360** [comment]
My side BeefBuild is not added into PATH. Means you added it manually.
Would you please share how you added it into PATH variable ?

Assuming issue is not there then I bet you also need to add LD_LIBRARY_PATH.

**Comment by bentxt** [comment]
hmmm, I dont think there is anything wrong with my PATH, I mean it can call `BeefBuild` from anywhere, that means the [...]/dist path is part of PATH. 

Then on mac os it DYLD_LIBRARY_PATH and you don't suppose to mess with that variable. 

What I tried is to use lldb to debug any potential problems. I dont know lldb well, so any help is appreciated, here is the output:
```

(lldb) process launch
Process 82056 launched: '/[...]/IDE/dist/BeefBuild' (x86_64)
libIDEHelper.dylib was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 82056 stopped
* thread #2, stop reason = EXC_BAD_ACCESS (code=1, address=0x14)
    frame #0: 0x0000000100d1c004 libIDEHelper.dylib`Beefy::MultiHashSet<Beefy::BfTypeDef*, Beefy::BfTypeDefMapFuncs>::Iterator Beefy::MultiHashSet<Beefy::BfTypeDef*, Beefy::BfTypeDefMapFuncs>::TryGet<Beefy::BfAtomComposite>(Beefy::BfAtomComposite const&) at BfSystem.h:0:16 [opt]
   1   	#pragma once
   2
   3   	#include "BeefySysLib/Common.h"
   4   	#include "BeefySysLib/util/CritSect.h"
   5   	#include "BeefySysLib/util/Hash.h"
   6   	#include "BeefySysLib/util/HashSet.h"
   7   	#include "BeefySysLib/util/Deque.h"
Target 0: (BeefBuild) stopped.
```

**Comment by apg360** [comment]
Hi,

Sorry I missed your reply.

cd IDE/dist
ls -lhrt

Make sure the symbolinc link are fine
When compiled at one place, it does hard code that location and create symbolic link and etc .... if after compilation you move directory to another place it will stop working.

Just confirm you have not changed or renamed directory or anything after initial compilation.
And that symbolic link are all fine in IDE/dist

Best regards,

**Comment by bentxt** [comment]
> Sorry I missed your reply.

No problem, thanks for replying 
> 
> cd IDE/dist
> ls -lhrt
> 
> Make sure the symbolinc link are fine

There are no symbolic links in IDE/dist, should there be links?

**Comment by apg360** [comment]
In mine yes they are (both linux and macOS)

lrwxr-xr-x   1 a0  staff    64B 24 nov 19:56 libBeefRT_d.a -> /Users/xx/Downloads/Beef-master/jbuild_d/Debug/bin/libBeefRT_d.a
lrwxr-xr-x   1 a0  staff    73B 24 nov 19:56 libBeefySysLib_d.dylib -> /Users/xx/Downloads/Beef-master/jbuild_d/Debug/bin/libBeefySysLib_d.dylib
lrwxr-xr-x   1 a0  staff    71B 24 nov 19:56 libIDEHelper_d.dylib -> /Users/xx/Downloads/Beef-master/jbuild_d/Debug/bin/libIDEHelper_d.dylib
lrwxr-xr-x   1 a0  staff    62B 24 nov 19:56 libBeefRT.a -> /Users/xx/Downloads/Beef-master/jbuild/Release/bin/libBeefRT.a
lrwxr-xr-x   1 a0  staff    71B 24 nov 19:56 libBeefySysLib.dylib -> /Users/xx/Downloads/Beef-master/jbuild/Release/bin/libBeefySysLib.dylib
lrwxr-xr-x   1 a0  staff    69B 24 nov 19:56 libIDEHelper.dylib -> /Users/xx/Downloads/Beef-master/jbuild/Release/bin/libIDEHelper.dylib

If you don't mind just delete everything, redownload Beef (my recent change was merged)
This time before starting the build, you download 25MB file [llvm-11.0.0.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-11.0.0.src.tar.xz) and put it at extern directory. Only after that you start the build.

**Comment by apg360** [comment]
> hmmm, I dont think there is anything wrong with my PATH, I mean it can call `BeefBuild` from anywhere, that means the [...]/dist path is part of PATH.
> 
> ```
> echo $PATH
> . /Volumes/sdapfs/[...]/builds/beef/beef/IDE//dist
> ```
> 
> Then on mac os it DYLD_LIBRARY_PATH and you don't suppose to mess with that variable. So I set the 'fallback' variable
> 
> ```
> echo $DYLD_FALLBACK_LIBRARY_PATH
> /Volumes/sdapfs/[...]/builds/beef/beef/IDE//dist
> ```
> 
> What I tried is to use lldb to debug any potential problems. I dont know lldb well, so any help is appreciated, here is the output:
> 
> ```
> lldb -- BeefBuild -run
> (lldb) process launch
> Process 82056 launched: '/[...]/IDE/dist/BeefBuild' (x86_64)
> libIDEHelper.dylib was compiled with optimization - stepping may behave oddly; variables may not be available.
> Process 82056 stopped
> * thread #2, stop reason = EXC_BAD_ACCESS (code=1, address=0x14)
>     frame #0: 0x0000000100d1c004 libIDEHelper.dylib`Beefy::MultiHashSet<Beefy::BfTypeDef*, Beefy::BfTypeDefMapFuncs>::Iterator Beefy::MultiHashSet<Beefy::BfTypeDef*, Beefy::BfTypeDefMapFuncs>::TryGet<Beefy::BfAtomComposite>(Beefy::BfAtomComposite const&) at BfSystem.h:0:16 [opt]
>    1   	#pragma once
>    2
>    3   	#include "BeefySysLib/Common.h"
>    4   	#include "BeefySysLib/util/CritSect.h"
>    5   	#include "BeefySysLib/util/Hash.h"
>    6   	#include "BeefySysLib/util/HashSet.h"
>    7   	#include "BeefySysLib/util/Deque.h"
> Target 0: (BeefBuild) stopped.
> ```
> 
> And this is how it looks when I successfully lounch it next to dist directory
> 
> ```
> lldb -- ../dist/BeefBuild -run
> 
> (lldb) process launch
> Process 82296 launched: '/Volumes/sdapfs/[...]/builds/beef/Beef-0.42.7/IDE/dist/BeefBuild' (x86_64)
> Hello, world!
> Process 82296 exited with status = 0 (0x00000000)
> ```
> 
> Its of course the same binary

My echo $PATH output is not like yours.
I suspect you do not copy paste your terminal output, you rather alter it trying not to show your username in pc etc .... for example when you do '/[...]/IDE

Whereby that hidden part is exactly what I am looking for to understand & confirm where it is and what is the location it tries to search for. By hiding like that I am unable to assist. 

Well then good luck trying to resolve your problem. Once resolved please let us know the solution; it might help somebody else.

**Comment by bentxt** [comment]
I would like to delete everything and start from stratch, the last time I've built from sources the ./bin/install.sh script produced/downloaded 20GB of data and it took arount 6 hours. Do I have to expect the same procedure again?

**Comment by apg360** [comment]
> I would like to delete everything and start from stratch, the last time I've built from sources the ./bin/install.sh script produced/downloaded 20GB of data and it took arount 6 hours. Do I have to expect the same procedure again?

Downloaded 2.2GB+ yes but this time no. Delete your existing Beef-master.zip and download latest one.
Thanks to Beef community, it will use the 25MB LLVM if it exists in extern and will not download anything.
**before starting the build**, you download 25MB file [llvm-11.0.0.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-11.0.0.src.tar.xz) and put it at extern directory. Only after that you start the build.

And YES it will generated 15GB+ for the compiled LLVM debug version. 
And YES it will take 2hours+ for each LLVM compilation : one time for LLVM debug version, another time for LLVM release version
NO, nothing force your to do debug compilation you can comment it and stick to release compilation for the moment.
But there is no existing flag for this, you have to modify llvm_build.sh and build.sh yourself manually. This will reduce cut process length to half.


Before you start **REMEMBER GOLD RULE** :)
1) My macOS catalina does not allow every software (including macos terminal) to access Documents, Downloads etc folders) I need to explicitely grant/allow access to it. A new security rule by macOS to prevent ransomware and virus I guess.
So keep this in mind when trying to put in fancy location that are protected. In my case I used Documents folder and I had to allow macOS security green light to terminal and Beef. for it to run freely

If this happens in Catalina (old version), it will also happen in Big Sur (new version). Maybe this could be your problem right now, assuming the symbolinc link are all fine and that you did not move/rename locations.

2) Do no move/rename location after compilation. Make sure to have it at final destination that you will always use **before** starting the compilation.

I cannot see any other major roadblock except these two points, I myself tried it like that.


Am I clear ? I hope it makes sens, if not then please do not hesitate to revert back.

Best regards

**Comment by apg360** [comment]
Thanks to @Green-Sky  llvm disk size once compiled on disk is now acceptable compared to before :
7,7G llvm_linux_11_0_0
294M llvm_linux_rel_11_0_0

Can see pull request #688 for detail
This is just for info.

@bentxt  Have you had a chance to try again ?
I am interested in your case because I am about to update from catalina to big sur, I don't want to end up with beef not usable.

**Comment by bentxt** [comment]
After several hours, the build process failed with the following message

```
[ 93%] Linking CXX shared library ../Debug/bin/libIDEHelper_d.dylib
ld: library not found for -llibxml2.tbd
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Debug/bin/libIDEHelper_d.dylib] Error 1
make[1]: *** [IDEHelper/CMakeFiles/IDEHelper.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Green-Sky** [comment]
> ld: library not found for -llibxml2.tbd

yes, llvm needs `libxml2`. not  a mac expert, but can you install this somehow?

> After several hours, ...

it looks like you are building not parallel (make default).
if you have `ninja` you can do `CMAKE_GENERATOR=Ninja bin/build.sh` (or extern/build_llvm.sh).
if you don't want to use ninja, you can do `CMAKE_BUILD_PARALLEL_LEVEL=4 bin/build.sh` and replace `4` with how many threads you want to spawn. (core count or core count + 2 seem to be good options).

**Comment by apg360** [comment]
> libxml2

I had this error too. BE CAREFUL it is delicate because MacOS dev tool already provide it.
So it is not recommended to do brew install libxml2

But in my personnal case as a rush testing, I still did it though :) because afterall I can remove it with brew remove and back to standard.

Before going into macos way (xcode-select --install  or Command_Line_Tools_for_Xcode_12.dmg) etc....
Let us first try brew method, **please do :** brew install libxml2

And let us know

Kinds regards

**Comment by bentxt** [comment]
Thanks for the directions, do you of an alternative to `make clean` where I loose all the previsously built binaries?

**Comment by apg360** [comment]
> Thanks for the directions, do you of an alternative to `make clean` where I loose all the previsously built binaries?

alternative to `make clean` ? where you lose or don't lose built binaries
Sorry I don't get you

**Comment by apg360** [comment]
I faced this libxml2.tbd three times already .... so far I failed to resolve it.

file exist, even the tbd is there .... I got it by Command_Line_Tools_for_Xcode_12.dmg (xcode-select --install)
% ls /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libxml2.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libxml2.tbd
% ls /usr/lib/libxml2.*
/usr/lib/libxml2.2.dylib    /usr/lib/libxml2.dylib
%

I guess we are two now with the same problem.
My workaround so far is to remove it from build file. Sorry I don't remember which file exactly it is in Beef to remove ld (linker) to search for it.

Try to grep :   grep -R -il "llibxml2.tbd" .

**Comment by Green-Sky** [comment]
@bentxt you can just go into the llvm directory and run `make` there, it will continue where it left of.
(those: `llvm_linux_11_0_0` `llvm_linux_rel_11_0_0`)

**Comment by Green-Sky** [comment]
iirc, `llvm-config` returns link flags, including xml2, so we might have to look there..

**Comment by apg360** [comment]
> iirc, `llvm-config` returns link flags, including xml2, so we might have to look there..

interesting, I like your approach. Look what I found :
```
-DLLVM_ENABLE_LIBXML2=OFF
Cmake file : 
option(LLVM_ENABLE_LIBXML2 "Use libxml2 if available." ON)
set(LLVM_ENABLE_LIBXML2 "ON" CACHE STRING "Use libxml2 if available. Can be ON, OFF, or FORCE_ON")
```
What do you think ? can I do cmake -DLLVM_ENABLE_LIBXML2=OFF ?

**Comment by Green-Sky** [comment]
@apg360 worth a shot

**Comment by apg360** [comment]
> @apg360 worth a shot

Well ... I face this issue with Beef only when doing full git clone of LLVM. Not when using 25MB file LLVM src..... one of this day I need to try with your git clone --depth 1 --branch approach.
So I am going to try it with one of the other build project where I face this same issue with llvm 11.

**Comment by Green-Sky** [comment]
> only when doing full git clone of LLVM. Not when using 25MB file

that's super weird ...

**Comment by bfiete** [comment]
It does seem like that library can and should be disabled via LLVM_ENABLE_LIBXML2 - see discussion at https://reviews.llvm.org/D45234

**Comment by bentxt** [comment]
ok, ldflags are set but ./bin/build.sh still cant find it


```
sh ./bin/build.sh
Starting build.sh
Building from from /Volumes/[...]/Beef-master/bin
-- Configuring done
-- Generating done
-- Build files have been written to: /Volumes/[...]/Beef-master/jbuild_d
[  5%] Built target hunspell
[ 75%] Built target BeefySysLib
[ 75%] Linking CXX shared library ../Debug/bin/libIDEHelper_d.dylib
ld: library not found for -llibxml2.tbd
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Debug/bin/libIDEHelper_d.dylib] Error 1
make[1]: *** [IDEHelper/CMakeFiles/IDEHelper.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by bentxt** [comment]
> Edit 2 :
> @bentxt did you download 25MB file [llvm-11.0.0.src.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-11.0.0.src.tar.xz) ???
yes

**Comment by bentxt** [comment]
just a quick update, at this point I'm not sure how important it is

in `beef/Beef-master/extern/llvm_linux_11_0_0` `make` finished without errors.

sh ./bin/build still fails though

**Comment by apg360** [comment]
> just a quick update, at this point I'm not sure how important it is
> 
> in `beef/Beef-master/extern/llvm_linux_11_0_0` `make` finished without errors.
> 
> sh ./bin/build still fails though

Sorry but I never done that, just to avoid surprise I prefer the hard way, once started must finish in one shot.
You want to be on safe side ? then do one by one, else you should really know what you are doing as they might be so many reason of what can go wrong even if the make finish 100% when done manually. 

1) extern/.llvm-build.sh  
If it ever abort for any reason and want to resume then 
delete llvm_linux_rel_11_0_0 llvm_linux_11_0_0 llvm-project_11_0_0 and start again from zero
This activity is one time only, so once completed its over. ~2hours

2) now ./build.sh
if for any reason it aborts, delete jbuild_d and jbuild then start again.

I am very sorry but thats the only way out of this. If done like this then we will validate each step.
You are unable to start build.sh and guarantee that the long process will run till end. So why taking the risk ? 
Do step1, when finish without any abort then validated and we don't touch again.
After what we can remain with step2 only, build.sh

Please do yourself a favor, delete directories llvm_linux_rel_11_0_0 llvm_linux_11_0_0 llvm-project_11_0_0 jbuild_d jbuild 
and rebuild one step at a time.

extern/.llvm-build.sh  => Make sure no pause/abort, the resume method is to delete the llvm dirs
After this we can finally focus on beef only.

**Comment by Green-Sky** [comment]
@apg360 please fix the paths `extern/.llvm_build.sh` -> `extern/llvm_build.sh` or better:
```
cd extern
./llvm_build.sh
```
pleas keep in mind, that `llvm_build.sh` must be executed from `extern/` !

**Comment by apg360** [comment]
> @apg360 please fix the paths `extern/.llvm_build.sh` -> `extern/llvm_build.sh` or better:
> 
> ```
> cd extern
> ./llvm_build.sh
> ```
> 
> pleas keep in mind, that `llvm_build.sh` must be executed from `extern/` !

Indeed, my mistake writing from memory. Nevertheless he will understand implicitely just like you did, he is not a beginner :)
Just in case though, I edited my comment and corrected.

Thank you Sir

**Comment by apg360** [comment]
> > just a quick update, at this point I'm not sure how important it is
> > in `beef/Beef-master/extern/llvm_linux_11_0_0` `make` finished without errors.
> > sh ./bin/build still fails though
> 
> Sorry but I never done that, just to avoid surprise I prefer the hard way, once started must finish in one shot.
> You want to be on safe side ? then do one by one, else you should really know what you are doing as they might be so many reason of what can go wrong even if the make finish 100% when done manually.
> 
> 1. cd extern
>    ./llvm_build.sh
>    If it ever abort for any reason and want to resume then
>    delete llvm_linux_rel_11_0_0 llvm_linux_11_0_0 llvm-project_11_0_0 and start again from zero
>    This activity is one time only, so once completed its over. ~2hours
> 2. cd bin
>    ./build.sh
>    if for any reason it aborts, delete jbuild_d and jbuild then start again.
> 
> I am very sorry but thats the only way out of this. If done like this then we will validate each step.
> You are unable to start build.sh and guarantee that the long process will run till end. So why taking the risk ?
> Do step1, when finish without any abort then validated and we don't touch again.
> After what we can remain with step2 only, build.sh
> 
> Please do yourself a favor, delete directories llvm_linux_rel_11_0_0 llvm_linux_11_0_0 llvm-project_11_0_0 jbuild_d jbuild
> and rebuild one step at a time.
> 
> llvm_build.sh => Make sure no pause/abort, the resume method is to delete the llvm dirs
> After this we can finally focus on beef only.

@bentxt  no news good news ? :)

**Comment by apg360** [comment]
Hi @bentxt

**Comment by bentxt** [comment]
> Hi @bentxt

sorry I'm a little accupied atm, but I will try during this night, since it takes several hours on my machine

can I work through this 2 steps above or do I have consider further instrouctions then:

1. clone beef
2. cd extern
[...]
3. cd bin
[...]
4 . profit (?)

**Comment by apg360** [comment]
@bentxt  Sorry for delay, yes you can follow the steps given above.

**Comment by apg360** [comment]
> > just a quick update, at this point I'm not sure how important it is
> > in `beef/Beef-master/extern/llvm_linux_11_0_0` `make` finished without errors.
> > sh ./bin/build still fails though
> 
> Sorry but I never done that, just to avoid surprise I prefer the hard way, once started must finish in one shot.
> You want to be on safe side ? then do one by one, else you should really know what you are doing as they might be so many reason of what can go wrong even if the make finish 100% when done manually.
> 
>     1. cd extern
>        ./llvm_build.sh
>        If it ever abort for any reason and want to resume then
>        delete llvm_linux_rel_11_0_0 llvm_linux_11_0_0 llvm-project_11_0_0 and start again from zero
>        This activity is one time only, so once completed its over. ~2hours
> 
>     2. cd bin
>        ./build.sh
>        if for any reason it aborts, delete jbuild_d and jbuild then start again.
> 
> 
> I am very sorry but thats the only way out of this. If done like this then we will validate each step.
> You are unable to start build.sh and guarantee that the long process will run till end. So why taking the risk ?
> Do step1, when finish without any abort then validated and we don't touch again.
> After what we can remain with step2 only, build.sh
> 
> Please do yourself a favor, delete directories llvm_linux_rel_11_0_0 llvm_linux_11_0_0 llvm-project_11_0_0 jbuild_d jbuild
> and rebuild one step at a time.
> 
> llvm_build.sh => Make sure no pause/abort, the resume method is to delete the llvm dirs
> After this we can finally focus on beef only.

@bentxt  No news ?

**Comment by apg360** [comment]
@bentxt 
No news good news :) 
Else you are no more interested in Beef on macos
