### ISSUE TITLE
[Crash] Crash on build with enum + static methods

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#689]
da6118259c8439f3df2f13329ac1f36b1f0b6e67

[crash-enum.zip](https://github.com/beefytech/Beef/files/5611609/crash-enum.zip)

EDIT: Most likely related to the case and the static methods being the same name.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/1efd403472e01cd155d15714970274b1bacbad22

It was a general issue with consts inside enums where the const type was not the actual declaring type.
