### ISSUE TITLE
Test.CountIndices causes a data cycle

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#69]
The following snippet produces the cycle. I can't see why it would cause a data cycle since they are constants fully defined before '_indices' gets declared.

```
        public class Test
	{
		private const int CountX = 2;
		private const int CountY = 10;
		private const int CountIndices = CountX * CountY * 3 * 2;

	    private int[CountIndices] _indices;
	}
```

**Comment by bfiete** [comment]
Fixed by https://github.com/beefytech/Beef/commit/e9ef8ed27cde3c012bc5737dcbbb847c325340cc.
