### ISSUE TITLE
[BUG] Crash while declaring an extension

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#690]
8dbd676

[crash-extension.zip](https://github.com/beefytech/Beef/files/5624453/crash-extension.zip)

```
	public static int CompareTo<T>(this )
```

**Comment by xposure** [comment]
Side Note: If you correctly implement this as 

```
	public static int CompareTo<T>(this T self, T other)
		where bool: operator T < T
		where bool: operator T > T
	{
		if(self < other)
			return -1;
		else if(self > other)
			return 1;

		return 0;
	}
```

You get an error that it can not determine T when its used.

```
	public class RenderableComparer : IComparer<IRenderable>
	{
		public int Compare(IRenderable self, IRenderable other)
		{
			var res = other.RenderLayer.CompareTo<int>(self.RenderLayer); //have to specify int even though RenderLayer is an int
			if (res == 0)
			{
				res = other.LayerDepth.CompareTo(self.LayerDepth);
				if (res == 0)
				{
					// both null or equal
					if (ReferenceEquals(self.Material, other.Material))
						return 0;

					if (other.Material == null)
						return -1;

					return 1;
				}
			}

			return res;
		}
	}
```

**Comment by bfiete** [comment]
Also- you are familiar with the spaceship operator intended for these types of comparisons, right? 
`int result = a <=> b` is the new `int result = a.CompareTo(b)`

**Comment by bfiete** [comment]
Also there's another constraint bug- your CompareTo should have only required the `T < T` constraint but not the `T > T`

**Comment by bfiete** [comment]
Fixed https://github.com/beefytech/Beef/commit/222d030aa4220eaba57f1e6dc173195de23ae1f8 and https://github.com/beefytech/Beef/commit/d976ea77e93901ba8aa09e47307472560df52f2a
