### ISSUE TITLE
[BUG] Crash on git update

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#692]
[git-update.zip](https://github.com/beefytech/Beef/files/5630617/git-update.zip)

Updatd from `b4db2bf`
To `8bc7c55`

**Comment by xposure** [comment]
[crash-build3 (2).zip](https://github.com/beefytech/Beef/files/5630628/crash-build3.2.zip)

After reopening the IDE and trying to build I get this crash and when I went to close the documents to see if any buffers were dirty, it asked if I wanted to save changes to Camera.bf.

**Comment by xposure** [comment]
After updating to the latest, debug ide is still crashing but with a different error. Release IDE works fine.
[build-crash4.zip](https://github.com/beefytech/Beef/files/5630679/build-crash4.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/230b71cecb66508c83e732ed0f40fab07a2c4369

**Comment by bfiete** [comment]
This did not, btw, fix the issue you alluded to with Camera.bf
