### ISSUE TITLE
[Enhancement] Find class to show extension members

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#693]
Class view will only show, so its impossible to find its implementation.

```
		protected extern void ClearInternal(RenderTarget target, Clear flags, Color color, float depth, int stencil, ref rect viewport);
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/687dde063f2e73329cd11d1c6fbddf8ea72d8f31

ClassView will show both the original declaration and the overload now. And you can Go To Definition on the overload to take you to the original extern decl.
