### ISSUE TITLE
[BUG] Init block crash

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#694]
7e9971d

[initblock.zip](https://github.com/beefytech/Beef/files/5638494/initblock.zip)

**Comment by xposure** [comment]
Its related to the Runtime.Fatal. compiler doesn't like that the init block has a noreturn tied to it or something.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/195a699af469a696f9a049a7568ce86b889886ec
