### ISSUE TITLE
[Enhancement] Ability to create default params with an initializer syntax

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#695]
Base on our discussion we were trying to come up with a way to solve the issue of having `simple` struct initializations that didn't require having a static variables already defined. One use case for this is library porting, for example, ImGui has a range of default values on its methods that could be ...

- Vec4(0,0,0,0)
- Vec4(1,1,1,1)
- Vec2(0,0)
- Vec2(1,1)
- Vec2(-1, 0)
- Vec2(0, -1)
- Vec2(1, 0)
- Vec2(0, 1)
- And so forth.

You would have to create a static variable for each one of these combinations and then assign it as the default param. Something like what we discussed below would better us to initialize the struct without any invisible functions calls or any sort of ctor.

> 
> There is initializer syntax for structs. Vec2 us = .() {mX = 0, mY = 0} but that assumes calling a constructor, AND that's still an expression (which is not allowed).
> There'd have to be a special version like "Vec2 us = default { mX = -1, mY = -1}" or something that checks to ensure the field settings are all constant...
> or something.
>

**Comment by xposure** [comment]
Adding additional discussion points from 12/8/20.

I run in to the scenario a lot where you are simply defining a data struct that requires you to implement a ctor with all the params if any of the fields are readonly or if they aren't, use a more verbose syntax that requires naming all the params with an initializer block.

I had suggested allowing structs to support a default ctor via `default( field1, field2 )` to initialize a struct (including its read only fields) as an alternative solution not only to the problem in this issue but as a way to eliminate the overly verbose need of defining ctors for simple data structs.

You had mentioned that you may be in favor of an IDE helper and later on using an "ordered initializer list", aka something like `float2 val = .{1, 2};` which I would also be in favor of with proper intellisense support.

**Comment by xposure** [comment]
Just to add more clarification here that there are essentially 2 problems but I feel there could be a single solution to solve them both.

Issue 1: Allowing for inline "constant values" that don't have side effects that a ctor could generate which would then allow them to be used as constant expressions as a default param to a method for example.

```
public struct float2{
  public float x, y;
  public readonly static float Zeros = .(0,0);
  public readonly static float Ones = .(0,0);
  public readonly static float OneZero = .(0,0);
  public readonly static float ZeroOne = .(0,0);
}
```

These seem overly verbose and also would consume a little bit of memory and it explodes the more fields you have. It is the only way to set a default param to a method for a user defined struct.


Issue 2: The need to specify a ctor if you have readonly fields that then lead to a requirement to also add all fields to the ctor (you could add default params to those fields in the ctor though). This leads to again a verbose description of simple data intialization.

```
public struct float2
{
  public readonly float x, y;
  public this(float x, float y){
    this.x = x;
    this.y = y;
  }
}
```


Ideally being able to create a constant expression of a data struct would remove the veborsity of these sort of data structures with something like `default ( fields ) ` or ` . { fields } `

**Comment by Shadowblitz16** [comment]
why not just `Vec2 vec = {0,0}`? similar to c?

**Comment by bfiete** [comment]
We have const eval now!
