### ISSUE TITLE
[BUG] Hot compiling doesn't work

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#697]
c46b760

If you run this code and modify this function by changing `.Red` to `.Green` and do a hot recompile it doesn't work until you kill the app and reload it.

```
		public override void DebugRender()
		{
			base.DebugRender();
			for (var it in _points)
				Core.Draw.Pixel(it, .Red, 2f);

			_points.Clear();
		}
```

EDIT: Vehicle.bf
EDIT2: The dot at the cursor position is what should change color.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/670de8d4dc5f367fb08abba5639a8c30fd0bf0b4

I think. This was weird, it seems like hot swapping in release builds of the IDE has been broken for a long time...

**Comment by bfiete** [comment]
Or rather maybe it only worked if you hit a breakpoint or did something else first...
