### ISSUE TITLE
[Enhancement] nameless structs for unions like c

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#701]
Based on our discussion in language on 12/7/20 we talked about ways to solve the following...

```
[Union]
public struct float2
{
    struct { float x, float y }
    float[2] values;
}
```

As it stands, you can't have a nameless struct. Some possible solutions discussed.

Dual purpose properties.
```
public struct float2
{
    float[2] values;
    public ref float x mut => ref values[0];
    public float x => values[0];
}
```

Using T
```
[Union]
public struct float2
{
    public struct Coords{
         float x;
         float y;
    }

    float2 values;
    Coords coords;
    using coords;
}
```

Field offset attributes (like C#)
```
[ManualLayout]
public struct float2
{
    [FieldOffset(0)]
    float[2] values;

    [FieldOffset(0)]
    float x;
    [FieldOffset(sizeof(float))]
    float y;
}
```

Out of these options, I think `using` provides the most flexibility, for example a swizzle struct could also be created and allow direct access to its members rather than going through another type which is more verbose.

**Comment by bfiete** [comment]
Also anti-OOPers like that kind of `using` since it gives you some of the same features of inheritances but it's technically composition. You end up dealing with some new name collision type issues, though, when you use `using` on multiple fields with fields with the same names. Like- do you throw an error on definition or a "ambiguous reference" on usage? Probably the later, but that's whole new class of error type...

**Comment by jayrulez** [comment]
How about something like this?

```
public union float2 : struct {
    struct value {float x; float y;}
    float[2] value;
}
```

or

public union /*struct*/ float2 {
    struct value {float x; float y;}
    float[2] value;
}

or

```
public union float2 : struct {
    value: struct {float x; float y;}
    value: float[2];
}
```

Giving "value" a special meaning inside union declarations

**Comment by bfiete** [comment]
We finally have this at 450d5412920581b12739149086da7451f42132a4 -
```C#
[Union]
struct Vector2
{
    public struct Coords
    {
        public float mX;
        public float mY;
    }

    public float[2] mValues;
    public using Coords mCoords;
}
```
