### ISSUE TITLE
[BUG] Crash while defining property

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#704]
If you delete `.w` and try to type `.width` the IDE crashes.

![image](https://user-images.githubusercontent.com/6292318/101660609-5a619180-3a15-11eb-9383-f6d939279f22.png)

[definingprop.zip](https://github.com/beefytech/Beef/files/5667438/definingprop.zip)

32e854d

**Comment by bfiete** [comment]
Doesn't seem to happen anymore. Probably a dup of some other bug that was fixed in the meantime...
