### ISSUE TITLE
[BUG] static initializer blocks not executing on static classes

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#705]
fdf1cbb

```
namespace Atma.Framework
{
	public extension Core
	{
		public static SpriteFont DefaultFont;

		static this
		{
			//Doesn't execute
			DefaultFont = Core.Assets.Load<SpriteFont>(@"fonts/PressStart2P.ttf");
		}
	}
}
```

**Comment by bfiete** [comment]
Does that work with a normal field initializer?

And what if you use a static ctor `static this()` instead?

**Comment by xposure** [comment]
Yea, a static ctor works, I didn't try it because I just assumed it would have the same issues as an instanced ctor, but now I realize those issues are the same.

**Comment by bfiete** [comment]
This should still work though, so I'll leave this open.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/189398819573ad7349252a4439c299b268d90f34
