### ISSUE TITLE
[BUG] Hard crash when defining a tuple typealias

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#708]
72fb4b6

open ObjectPool.bf and edit the following code: `typealias ObjectPoolItem = (int PoolIndex, T)` if you try to name T in this line the IDE hard crashes.

```
	public class ObjectPool<T>
	{
		typealias ObjectPoolItem = (int PoolIndex, T)
		private List<T> _items = new .() ~ Release(_);
		private List<int> _free = new .() ~ Release(_);


	}
```

**Comment by bfiete** [comment]
This seems to have been fixed somewhere along the line...
