### ISSUE TITLE
Using alias for class member deconstruction

### ISSUE THREAD

**Issue by Shadowblitz16** [beefytech/Beef#709]
Can be have a more clear way of cleaning up members
instead of..
```
static List<Image> sImages = new .() ~ delete _;
```

we **could** do something like..
```
using static List<Image> sImages = new List<Image>();
```

Its a little more clear to C# developers to what it does..

**Comment by bfiete** [comment]
`delete` is not the only way things are cleaned up. If you use a custom allocator then you need `delete:YourAllocator _`. Sometimes you have to `Dispose` a struct. Or perhaps there's another method that needs to be called, like `ObjectPool.Return(_)` or something.

**Comment by Shadowblitz16** [comment]
Ya this would only cover deleting the item your declaring using on.

**Comment by NicEastvillage** [comment]
If you replace that comma with `~` when you pretty much have the current syntax.

**Comment by Shadowblitz16** [comment]
so here is a better idea what about allowing for something like so..
`static List<Image> sImages = new(), delete; // deletes List<Image>`
`static List<Image> sImages = new(), delete sImage;` //same thing

I really don't like `_` tbh I think there needs to be a better and more clear alternative

**Comment by bfiete** [comment]
I hope you'll enjoy how this all works after you've spent more time with the language.
