### ISSUE TITLE
Alternate error syntax proposal

### ISSUE THREAD

**Issue by Shadowblitz16** [beefytech/Beef#710]
instead of something like so...
```
		public static Result<Image> Load(StringView fileName)
		{
			Image image = new Image();
			if (image.Load(fileName) case .Err)
			{
				delete image;
				return .Err;
			}
			sImages.Add(image);
			return image;
		}
```

why not reserve 2 keywords?
- catch
- error

here is a example..
```
		public static Result<Image> Load(StringView fileName)
		{
			Image image = new Image();
			catch (image.Load(fileName))
			{
				delete image;
				return error;
			}
			sImages.Add(image);
			return image;
		}
```

or 
```
		public static Result<Image> Load(StringView fileName)
		{
			Image image = new Image();
			catch (!image.Load(fileName))
			{
			        sImages.Add(image);
			        return image;
			}
                        delete image;
			return error;
		}
```

It aids readability

**Comment by bfiete** [comment]
The `Result` type is just one type of an enum. There's nothing intrinsically error-related about it, it's just a convention. The `case` handling is how enum cases are handled -- also works in a switch.

**Comment by Shadowblitz16** [comment]
Hmm so what about doing something like so..
```
		public static Result<Image> Load(StringView fileName)
		{
			Image image = new Image();
			if (image.Load(fileName)) //returns a enum or 1 or true if successful
			{
			        sImages.Add(image);
			        return image;
			}
			delete image;
			return .Error; //more clear what it is
		}```

**Comment by bfiete** [comment]
I hope you'll enjoy how this all works after you've spent more time with the language.

**Comment by Shadowblitz16** [comment]
I will never enjoy having to use `.` everywhere or use cases in if statements
I thought the idea was to make the language easier to understand and use?

**Comment by bfiete** [comment]
It seems like you are looking for a language earlier in its design stages so you can contribute to syntax and semantics. This language is _not_ one of those -- the syntax and semantics are set, and the kind of suggestions that are useful at this point at those that fit _within_ that charted course. It will be difficult to make useful suggestions along those lines until a user has a fairly significant amount of experience working within this language _as it exists_.
