### ISSUE TITLE
Use wxWidgets for editor

### ISSUE THREAD

**Issue by Shadowblitz16** [beefytech/Beef#711]
Is it possible to rewrite the editor in wxwidgets?

Here are some pros of doing so..
- Support for native theming on windows, mac and linux
- Could be themed
- Cross platform
- WxWidgets is easier to work with then windows.h 

Here are some cons..
- Requires to rewrite the editor
- Theming requires custom painting over the controls.

**Comment by bfiete** [comment]
One day if the IDE gets ported to other platforms then there will be an open discussion of what APIs may be useful in that effort and you are welcome to make your case for this particular library at that time.
