### ISSUE TITLE
Networked editor similar to microsoft's live share

### ISSUE THREAD

**Issue by Shadowblitz16** [beefytech/Beef#712]
How feasible would something like [microsoft's live](https://visualstudio.microsoft.com/services/live-share/) share be?

Basically it would allow people to connect to other people and edit code together.

**Comment by bfiete** [comment]
There are two ways this can happen:
1) The IDE may one day have a very flexible extension system that allows for a third party to create something like this.
2) A VSCode extension for Beef is created one day.

Either way, this item is out of scope for first-party inclusion in this IDE.
