### ISSUE TITLE
String concatenation should be handled with streams in the compiler

### ISSUE THREAD

**Issue by Shadowblitz16** [beefytech/Beef#719]
Can we have it so strings are handled and cleaned up with streams when doing..

```
static void Main()
{
    if (SDL.Init(SDL.InitFlag.Everything) < 0)
    {
        Console.WriteLine("SDL could not initialize! " + SDL.GetError().ToString() + MyClass.ToString());	
    }
}
``` 

here is what it might look like in c++...

```
auto temp = to_string(MyClass)
cout << "SDL could not initialize! " << SDL_GetError(); << temp << endl	
delete temp
``` 

The only case where it isn't cleaned up is when using new
```
var temp1 = new String("Test"); //not cleaned up automaticly
var temp2 = "bruh" //cleaned up automatically 

```

I would guess this would need some sort or GC to do and I think arc would be fine for strings.

**Comment by bfiete** [comment]
I believe in time you will understand why this doesn't work.
