### ISSUE TITLE
Compiler segfault for conversion of Result<T> to Object when T is empty class

### ISSUE THREAD

**Issue by lukpank** [beefytech/Beef#72]
The following program segfaults compiler (same segfault for `M(r)` where `M` expects `Object` as argument).

```csharp
using System;

namespace Issue
{
	public class Program
	{
		public static void Main()
		{
			Result<C> r = .Err;
			Object o = r;
		}
	}

	public class C {}
}
```

**Comment by bfiete** [comment]
Hm- I think I already fixed this. Does this occur still with a build from trunk?

**Comment by lukpank** [comment]
Yes.

**Comment by damianday** [comment]
@bfiete @lukpank I can reproduce this.
From BfModule::EmitTupleToStringBody() it crashes in BfExprEvaluator::CreateCall with methodInstance as null parameter.

**Comment by bfiete** [comment]
This seems to have gotten fixed sometime.
