### ISSUE TITLE
[BUG] IDE crash

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#724]
[Koa.zip](https://github.com/beefytech/Beef/files/5689804/Koa.zip) (its a library)

If you uncomment line 363 or 373 (in Parser.bf) then the IDE crashes when compiling.

**Comment by bfiete** [comment]
I'm not seeing any crash here with the current nightly build. Can you check this again and post the crash dump if you have one?

**Comment by MineGame159** [comment]
Oh, I am using latest release which was few days old and haven't thought about updating. Lemme try nightly.

**Comment by MineGame159** [comment]
Still crashed using latest nightly. Here is crash dump https://ufile.io/azx2y61m

**Comment by bfiete** [comment]
You can also just zip the dumps and put them here, btw.

**Comment by MineGame159** [comment]
Oh yeah forgot.

**Comment by bfiete** [comment]
I don't think the zip you posted actually causes the error.

**Comment by MineGame159** [comment]
I just zipped the entire workspace, for me it crashes with those lines uncommented.

**Comment by bfiete** [comment]
Try your own zip - unzip it and open it up.

**Comment by bfiete** [comment]
This crash would require an actual program, in the workspace not just a library.

**Comment by MineGame159** [comment]
Oh yeah sorry. 1 sec, gonna upload some sample file.

**Comment by MineGame159** [comment]
This is weird. I just copied my test main file to a new project and now it doesn't crash, but the old one still does.

**Comment by bfiete** [comment]
The bug is a backend code generation issue. It's not happening in the new project because you're not actually _calling_ those methods in question so no machine code is generated for them.

**Comment by MineGame159** [comment]
I am using them, I literally just copied the source to a new project and that one doesnt crash, but the old one does, With the same source.

**Comment by bfiete** [comment]
There must be some other project setting then. You can open up the .toml files to more easily see the non-default settings.

**Comment by MineGame159** [comment]
Can it be something to do with the location of the project? Because I just deleted the old project and created it again but it still crashes. So both of them have the default settings but only one of them crashes.

**Comment by MineGame159** [comment]
Its not the location, maybe you can test project, it expects you to have the library installed.
[KoaTest.zip](https://github.com/beefytech/Beef/files/5709859/KoaTest.zip)

**Comment by bfiete** [comment]
Yes, that reproduced the error.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/7bc9b7af0a0c03b5d3982d4b8cbf94407cd7b173
