### ISSUE TITLE
[BUG} access violation due to code optimization

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#726]
The following branch `optissue` contains the reproducible code. Start up with "samples" workspace and run the helloworld project. Click on any of the hollow pink rects to trigger it.

**Comment by bfiete** [comment]
I think this must have been fixed accidentally? I wasn't able to reproduce this one with a current build...

**Comment by xposure** [comment]
Yep, looks to be indirectly fixed by something. I'll close it.
