### ISSUE TITLE
[BUG] IDE crash with extension method

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#727]
This code crashes the IDE:
```
namespace Anything
{
    static
    {
        public static operator bool(this MyResult this)
    }
}
```

Tested on the build from Nightly 12/08/2020

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/792d92d0147ea9405737059960a3c55ff806cf1f

Also you can't do operator overloads as extension methods. But the crash is fixed!
