### ISSUE TITLE
[BUG?] Static block as argument type gives linker error

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#728]
This code compiles fine but gives a linker error, I know that there's no reason that someone would do something like this but I'm reporting it anyway because this behavior doesn't look right.
```
namespace test4
{
	static
	{
		public static void Hello(Self self = default)
		{
			Console.WriteLine("Hello! I'm {}", self.GetType());
		}
	}

        class Program
        {
                public static int Main(String[] args)
		{
			Hello();
		}
        }
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/4ee40c8a065f6c47216a99b488b94abf29a01aab
