### ISSUE TITLE
[Enhancement] Buffered FileStream

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#729]
Currently FileStream isn't buffered (even though there's a `bufferSize` argument in the constructor) and using it to read large files with small read calls is really inefficient and takes a long time (my test file took more than one minute to load), here's the profiling result:
![image](https://user-images.githubusercontent.com/14041768/102154120-8175f400-3e57-11eb-8199-d021d9a62718.png)

**Comment by bfiete** [comment]
You're not wrong, but even with buffering I would expect the actual ReadFile calls to dominate the profile.

**Comment by Igoorx** [comment]
I think I get what you mean, I didn't mean that it's inefficient because it dominates the profile, but because currently the loading of the file takes more than one minute. One way that I found to speed up things was to do a `CopyTo` to a MemoryStream and then reading the data from it, after this it took just 4 seconds to read everything, but I think this is really memory inefficient even though this works for my current case.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/4bf12e121c1e677353353c680967eea7bf43a66f
