### ISSUE TITLE
[BUG] IDE memory leak

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#730]
I was using the Profiler of the debug IDE and encountered a memory leak, I hope this crash dump helps because when I clicked the "Save Dump" button, the IDE closed, so I couldn't copy the crash message...
_(I have a crash dump because I remembered that crashdumps are also stored in the "CrashDumps" folder of the IDE)_
[BeefIDE_d_20201214_220958.zip](https://github.com/beefytech/Beef/files/5692565/BeefIDE_d_20201214_220958.zip)

**Comment by bfiete** [comment]
Hm, had something to do with profiling. Any idea how you made that happen?

**Comment by Igoorx** [comment]
Actually yes, I remember that I clicked multiple times in "Start Profiling" while the workspace was compiling, I just tried this again and the memory leak happened once again.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/4e27903fe5e7ff02436550c05a317876d121bc15
