### ISSUE TITLE
[BUG] Crash with sized array

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#731]
This code crashes the IDE, but it's not instantly, you need to do some clicks on the error or edit a little like adding/removing numbers.
```
using System;

namespace test4
{
	class Program
	{
		public static int Main(String[] args)
		{
			int[0xffffffff + 1] arr = new int[0xffffffff + 1];
			 
			Console.Read();
			return 0;
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/d5b7fc3bbeaabafec22f83d88240368604327d00
