### ISSUE TITLE
[BUG] Various problems with Nullables

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#736]
1. Even though this code is in a mixin, it can't assign to a nullable without reference
<details>

![image](https://user-images.githubusercontent.com/14041768/102243345-d5292180-3ed9-11eb-830e-2d076b060dae.png)
</details>

2. This code gives a really cryptic error:
<details>

```
ERROR: Only value types can be boxed
  while compiling 'test4.Program'
```
```
		public static void Foo<T>(T v) where T : struct, INumeric
		{

		}

		public static void Foo<T>(T v) where T : struct
		{

		}

		public static void Bar<T>(T? x) where T : struct
		{
			Foo(x);
		}

		public static int Main(String[] args)
		{
			int? i = 0;
			Bar(i);
		}
```
</details>

3. Nullable can't be inferred when called from a generic method
<details>

```
		public static void Bar<T>(T? x) where T : struct
		{
		}

		public static void FooBar<T>(T x) where T : struct
		{
			Bar(x); // ERROR: Unable to implicitly cast 'T' to 'System.Object?'
		}

		public static int Main(String[] args)
		{
			int? i = 0;
			FooBar(i);
		}
```
</details>

4. In this piece of code, the compiler chooses to use the method with `class` constraint, even though one method for Nullable is defined.
<details>

Note: If you change the `public static void Bar2<T>(T? x) where T : var` to `public static void Bar2<T>(T? x) where T : struct` the error continues until you clean the build.
```
		public static mixin Test2<T>(T x) where T : class
		{

		}

		public static mixin Test2<T>(T? x) where T : struct
		{

		}

		public static void Bar2<T>(T? x) where T : var
		{
			Test2!(x);
		}
```
</details>

**Comment by bfiete** [comment]
The initial error is `Unable to determine generic argument 'T'1 and then it fails over to Object which is.. just a failover. An improvement would be to just stop error messages at that point but... the point is that this code SHOULD still produce an error.

**Comment by Igoorx** [comment]
Thanks for cleaning this up, If this is the case the error really was misleading, I can understand why the compiler wouldn't be able to pick a method as the only constraint of the generic was struct but when I saw that the error wasn't something clearly stating this, I thought this could work smh

**Comment by bfiete** [comment]
The other bugs are all good, though.
Fixed https://github.com/beefytech/Beef/commit/5808bd555c96b83faab4a651eefbf2a8e5e73f96
And https://github.com/beefytech/Beef/commit/ff6c7c5b90910ceb157ad99d1b136cbcb17cc74f
