### ISSUE TITLE
[BUG] non-default constructor isn't allowed even with var constraint

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#748]
![image](https://user-images.githubusercontent.com/14041768/102641900-9c888280-413b-11eb-9f7e-8bb1fe7d852f.png)

This is the code used (simplified for the issue):
```
		private class Val2User<T>
			where T : var, new
		{
		    public void Init() => new T();

		    public void Init<T1>(T1 t1) => new T(t1);
		};
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/9eb3d8c3a5ea8c1b7909888138a672eed48b0fe2
