### ISSUE TITLE
[BUG] Invalid codegen on conversion operator

### ISSUE THREAD

**Issue by BradFitz66** [beefytech/Beef#749]
Getting a invalid codegen error with some code inside a conversion operator.

The code can be seen here:
```cs 
return (flag.zero           ? 1 : 0)    << ZERO_FLAG_BYTE_POSITION |
       (flag.subtract    ? 1 : 0)  << SUBTRACT_FLAG_BYTE_POSITION |
       (flag.half_carry ? 1 : 0)    << HALF_CARRY_FLAG_BYTE_POSITION |
       (flag.carry       ? 1 : 0)     << CARRY_FLAG_BYTE_POSITION;
```

Rewriting the code as such fixes the issue
```cs 
let zero = (flag.zero ? 1 : 0) << ZERO_FLAG_BYTE_POSITION;
			let subtract = (flag.subtract ? 1 : 0) << SUBTRACT_FLAG_BYTE_POSITION;
			let half_carry = (flag.half_carry ? 1 : 0) << HALF_CARRY_FLAG_BYTE_POSITION;
			let carry = (flag.carry ? 1 : 0) <<  CARRY_FLAG_BYTE_POSITION;
			return uint8(zero | subtract | half_carry | carry);
```

exact error is

> ERROR: Module 'BeefBoy_FlagsRegister' failed during codegen with: Failure during codegen of ??BFlagsRegister@BeefBoy@bf@@SAEU012@@Z: Invalid liveness - from init flag not being set properly?

**Comment by bfiete** [comment]
Any chance you can post an actual project I can compile to recreate this error?

**Comment by BradFitz66** [comment]
[BeefBoy - Codegen error.zip](https://github.com/beefytech/Beef/files/5719594/BeefBoy.-.Codegen.error.zip)

This should be it

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/e8de8cd7be0b83b1459a24ac1a166f4250ba12fc
