### ISSUE TITLE
[BUG] IDE hard crash with typealias and generics + tuples

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#751]
```
	public class Test<T, K>
		where K: enum
	{
		typealias x = function void (T t);
		typealias y = (K) //try to define a variable name (K xyz) etc
	}
```

**Comment by xposure** [comment]
Also note that you can't do `public void Foo(K? state)` it will give a compile error saying that K must be a value type.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/2130b7d60c90d141f60cebeb34f65580e280152d
