### ISSUE TITLE
[BUG] Complier.CallerExpression crash

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#756]
Crashes once you try to use the method `Test()`

![image](https://user-images.githubusercontent.com/6292318/103040401-510e1400-4541-11eb-818a-c9ba72580f43.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/73b643d298a0d00d8b850f082d1ecbf46b94c945

Your method will properly fail now (since there are no caller expressions)
