### ISSUE TITLE
[BUG] Latest nightly (22nd) crashes the neon shooter example 

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#757]
Workspace https://github.com/xposure/Atma.Framework/tree/master/samples

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/8894430f98f7a21439e66f5a7a18db9814cab2d1

It was a backend code gen issue with taking the address of zero-sized structs... not sure how it was working before, but it's working again now!
