### ISSUE TITLE
when the github can search the beef language?

### ISSUE THREAD

**Issue by sgf** [beefytech/Beef#758]
I think we need some third-party author's component library, such as wrapper  for imgui
We need to use github to build our own community, ecology

and we need the **package manger**

**Comment by bfiete** [comment]
What?

I thought this item was going to be about adding BeefLang to Linguist based on the title, but I'm not sure what this issue is about now.

**Comment by sgf** [comment]
1.add beef-lang to github search language filter(This way I can use the search syntax provided by github for example: gui language:beef to search)
2.add package-mange to beef-lang let peoples easy share them works(Give priority to this work because it solves librarys sharing problems rather than piecing source code.).I admire you very much, but after all, your energy is limited. So we may need to build a community where people help build Beef's own language ecology. For example: development and port of some third-party feature libraries.

**Comment by bfiete** [comment]
1) Linguist a threshold of "used in hundreds of repos" for adding a new language. We're not there yet.
2) Yes, there will be a package manager at some point.

**Comment by RogueMacro** [comment]
@sgf There already is an imgui wrapper: https://github.com/RogueMacro/imgui-beef

**Comment by sgf** [comment]
understand

**Comment by Green-Sky** [comment]
Looks like github has now (partially?) adopted beef-lang
https://github.com/trending/beef
