### ISSUE TITLE
[Enhancement] Abstract classes don't have to implement interface members

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#759]
As of right now, abstract classes that don't implement interface members throw an error, but that isn't right since the members would be implemented in the class derived from the abstract class.

**Comment by bfiete** [comment]
Interface implementations methods are not assumed to be virtual methods in BeefLang like they are in C#. If your intention is that the interface methods also be declared as abstract virtual methods then you need to declare them as such.

**Comment by bfiete** [comment]
In other words "this is by design".

**Comment by RogueMacro** [comment]
Ok :+1:

**Comment by bfiete** [comment]
The abstract default method implementation issue discussed on Discord was fixed at https://github.com/beefytech/Beef/commit/cad0b10aaedc1f98bf02de99efe3efd83ca111fb
