### ISSUE TITLE
[BUG] Test crash in atma framework

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#763]
If you open the samples project and run tests, they will hard crash, if you debug them you will get an access violation on

```
[StaticInitPriority(2000)]
	public struct ComponentType : IHashable// IEquatable<ComponentType>
	{
		internal static LookupList<Type> _typeLookup = new LookupList<Type>(); //crash

```

**Comment by xposure** [comment]
Works if I turn it to an initializer block (ignore the memory leaks, still porting)...

```
		static this
		{
			_typeLookup = new .();
		}
```

**Comment by xposure** [comment]
Had to do this to fix memory leaks... `static this` is being called multiple times.

```

		static this
		{
			if(_typeLookup == null)
				_typeLookup = new .();
		}

```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/4a00830adfa81c3b3c08c0231b417ee9df8d085b
