### ISSUE TITLE
[Enhancement] Support {{ and }} in string interpolation 

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#764]
```
		public override void ToString(String output) => output.Append(scope $"{{ Spec: {SpecIndex}, Chunk: {ChunkIndex}, Index: {Index}, ID: {ID} }}");
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/2ac2fe70fbdf50e69c942a0ff36f6ee5224deaf9
Also fixed a string interpolation lexical scoping issue with expressions like `$"{val.ToString(.. scope .())}"`
