### ISSUE TITLE
[BUG] Not sure if this will reproduce bug several weird crashes with this commit

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#765]
https://github.com/xposure/Atma.Framework/commit/7ea01462d4aa58aa29f9750d0e751d8e43c6e9d3
![image](https://user-images.githubusercontent.com/6292318/103160518-35ef0e80-47a4-11eb-85b2-3361ad6d1e35.png)

**Comment by xposure** [comment]
Another crash later after getting around the above 754b8f8

**Comment by bfiete** [comment]
There were a couple issues here such as issues with functions refs in generics, generic inlines, inlines with defaults...
Fixed at
https://github.com/beefytech/Beef/commit/6c049988b3d6b3d616f18636c951bffcdb47ec7c
https://github.com/beefytech/Beef/commit/ba9ce75a0b4d18f83df5f8457ab4ae529366ae0e
https://github.com/beefytech/Beef/commit/2896b84f7f681382d75c3a72f62f714e46b3c069
