### ISSUE TITLE
[Bug] Fixit "create constructor" creates wrong constructor when AllowAppend specified

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#766]
Using the fixit option to create a constructor that has the "AllowAppend"-attribute specified will generate a constructor that is wrong in two ways:
1. The constructor won't have the required "AllowAppend"-attribute specified
2. The constructor will have a parameter "ref int appendIdx"

### Example:
Given this code:
```C#
class Parent
{
	[AllowAppend]
	public this() {}
}

class Child : Parent
{
}
```
Using the Fixit "create constructor" on Child creates the following constructor:
```C#
public this(ref int appendIdx) : base(ref appendIdx)
{
}
```
But the expected result would be:
```C#
[AllowAppend]
public this() : base()
{
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/80fcf84de2204c837c53cdbd6be6c92f8d024fb3
