### ISSUE TITLE
[Bug] IDE crashes when compiling

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#767]
The IDE crashes while compiling my project. I couldn't figure out why specifically, however it is somehow related to the "AllowAppend" attribute.

[crashdump.zip](https://github.com/beefytech/Beef/files/5745037/crashdump.zip)

My Project to reproduce the crash:
[project.zip](https://github.com/beefytech/Beef/files/5745033/project.zip)

To reproduce the crash simply open the project and hit compile.

**Comment by bfiete** [comment]
Thanks-
Fixed at https://github.com/beefytech/Beef/commit/585e2575e809d4de8693b080b9f3c5b389a3d7ed
