### ISSUE TITLE
macOS call stack corruption

### ISSUE THREAD

**Issue by jazzbre** [beefytech/Beef#768]
A simple `bool SomeTest(const char* label,float v[2],const char* format,SomeShit flags) ` crashes when running on macOS.
Repo case is attached. To build and run just change the path to your local BeefBuild in build.sh, and run build.sh.
The output should be something like this:
`Before
fromC1 2.000000 2.500000 format3 4
Before
./build.sh: line 5:  9466 Segmentation fault: 11  ./build/Debug_macOS/test/test`

Tested with 585db3b579970de1c870a604b4a53b4212bb011c commit.

[test.zip](https://github.com/beefytech/Beef/files/5745098/test.zip)

**Comment by jazzbre** [comment]
Fix for this is to write the function in Beef as:
`bool SomeTest(char8* label,float[] v,char8* format,SomeShit flags)`
(so float[] instead of float[2]) but the problem is that it works on windows, just not on macOS (possible linux?).

Thanks!

**Comment by jazzbre** [comment]
Just did a new test on Windows.
If I compile the C++ file with clang it actually crashes when entering that function even on windows.
Works ok when compiled with Visual studio. 
So it looks like something fishy is going on, maybe some compiler settings?

**Comment by bfiete** [comment]
Well, the crash in windows is AFTER the printf. A "ud2" invalid-operation instruction gets added because you didn't return from SomeTestVec in test.cc. Clang reports this as a warning during compilation. If you add a `return true:` then everything works as expected on Windows.

**Comment by bfiete** [comment]
But, yeah- there is a Linux/osX calling convention issue here, still.

**Comment by jazzbre** [comment]
Oh right, I've noticed the missing return later on macOS but didn't testi it on windows again, sorry. :D

**Comment by bfiete** [comment]
This should be fixed at https://github.com/beefytech/Beef/commit/8a63a7ed8072b99aab49c3c1d703ef2ef2e952d9

**Comment by jazzbre** [comment]
Works, great job! Thanks
