### ISSUE TITLE
[BUG] Crash with entity.bf

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#769]
[entity-crash.zip](https://github.com/beefytech/Beef/files/5747634/entity-crash.zip)
![image](https://user-images.githubusercontent.com/6292318/103220813-2e884c00-48ef-11eb-8b02-00b024651fab.png)

**Comment by xposure** [comment]
I should note, I'm not sure if this is just one big issue in this file, but this file has become incredibly hard to edit and making changes to. EntityList has become a bit tricky too, but not as bad.

**Comment by bfiete** [comment]
Private repo?

**Comment by bfiete** [comment]
Could you try that in the debug IDE?

**Comment by xposure** [comment]
Yea, its in atma framework too.

**Comment by xposure** [comment]
Its not happening in the latest nightly, let me play with it for a little bit.

**Comment by xposure** [comment]
I'm going to close it, I can't trigger it now. I'll create a new issue if it comes back. Just for a point of reference, I've noticed these issues in files that have a lot of lambda usage.
