### ISSUE TITLE
[BUG] Minor issue navigating with arrow keys after erasing text

### ISSUE THREAD

**Issue by kumikumi** [beefytech/Beef#772]
Steps to reproduce:

1. erase some text (using backspace)
2. optionally, without moving cursor, type some text
3. attempt to navigate to previous/next line using up/down arrow keys

expected behavior: cursor goes up/down to previous/next line
actual behavior: nothing happens

workaround: navigate to left/right using arrow keys first, before attempting to navigate up/down

This does not reproduce in 100% of cases, but at least does when erasing text on keywords, variable types and method names.

**Comment by bfiete** [comment]
Ah, this is with Autocomplete Require Tab disabled. Seems pretty broken, I wonder why no one has complained before.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/cadd1f809ff193e1dd7caa6fa1a597cc9e90ee4c
