### ISSUE TITLE
[BUG] Linker errors with the following code

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#776]
```
if (_lastError.Length == 0 && Expect( () => (LookAhead() case .Ok(let token), token.IsEOF)))
```

In Atma.Common 0e0e079 I cleaned up the json stuff and its in its own projects now FYI.

**Comment by xposure** [comment]
Also note that c33c511 now has an issue with 
```
if (mTypeClassVData == null)
				return .Err;
```
On `TestClass`

**Comment by bfiete** [comment]
Just to clarify from the Discord char - this second issue in c33c511 requires having compiled with the bug from 0e0e079 first. Correct?

**Comment by bfiete** [comment]
Fixed original issue at https://github.com/beefytech/Beef/commit/56c250f251ea0961d7b21cd552b64e12b5ae4d00
This was a failure-without-an-error situation.  If you can get the c33c511 issue to occur without the broken lambda then that's something else...

**Comment by xposure** [comment]
Thanks!

So the secondary issue from our chat appears to be that the metadata sticks around when you "lower" the reflection flags. So this explains why when I was switching machines that this bug would happen and when I increased the settings it would go away and not come back.

I'll let this open for now unless you want a new issue.

**Comment by bfiete** [comment]
That should be fixed here now: https://github.com/beefytech/Beef/commit/f81a1cf89661dc685f4bc302d563e2f602cc7e24
