### ISSUE TITLE
Building IDE_bf failed

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#78]
Building IDE_bf
[******************************]
Beef compilation time: 36.12s
Executing Command: CopyToDependents("$(ProjectDir)/dist/BeefySysLib64.dll")
Executing Command: CopyToDependents("$(ProjectDir)/dist/BeefySysLib64.pdb")
Failed to execute "C:\beef\IDE\dist\llvm\bin\lld-link.exe"
ERROR: BUILD FAILED

**Comment by damianday** [comment]
There was also an issue with creating stats\IDE_Debug_build.csv & stats\IDE_Release_build.csv
because no stats folder is present by default.

**Comment by bfiete** [comment]
Ah, yeah, I have to add that to the build instructions. You have to put in an lld-link.exe from either a Beef install or from an LLVM/Clang install.

**Comment by bfiete** [comment]
Fixed in https://github.com/beefytech/Beef/commit/5a63fec1685b972da0a06a40489add45935271fa
