### ISSUE TITLE
[BUG] Open Type.bf in corlib and format the file, it strips extern

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#781]
![image](https://user-images.githubusercontent.com/6292318/103446712-c15b1a80-4c50-11eb-8ba7-80d37223a82c.png)

![image](https://user-images.githubusercontent.com/6292318/103446716-ca4bec00-4c50-11eb-904e-ca06deed1822.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/8ceb7bf1832488b4047e9609f99344250a4aaedc
