### ISSUE TITLE
[BUG] System.Reflection.MethodInfo not behaving as expected

### ISSUE THREAD

**Issue by Moneyl** [beefytech/Beef#784]
I'm invoking a struct method via reflection and changes to member variables in the method aren't working.

The struct:
```cs
[Reflect(.Methods), AlwaysInclude(AssumeInstantiated=true, IncludeAllMethods=true)]
public struct StructA
{
	private uint32 _value = 0;
	public this(uint32 value)
	{
		_value = value;
	}

	public void SetValue(uint32 newValue) mut
	{
		_value = newValue;
	}
}
```

How to reproduce the issue:
```cs
//Create struct instance and get method info
StructA a = .(2);
Type type = typeof(StructA);
let method = type.GetMethod("SetValue");
//Invoke SetValue on instance. Expect _value to be 11 after this but it still equals 2.
method.Value.Invoke(a, 11);
```
Before invoking the method a._value = 2, as expected. I expect a._value to equal 11 after invoking the method, however it still equals 2. Interestingly if I set a breakpoint at the end of StructA.SetValue it shows _value as being 11. Anywhere after that it shows as 2 again. Tried passing `ref StructA` to `Invoke` and that didn't make a difference.

Using Beef v0.42.8

**Comment by bfiete** [comment]
You were close!
`method.Value.Invoke(&a, 11);`

**Comment by Moneyl** [comment]
That works. Thank you. Closing this.
