### ISSUE TITLE
[BUG] Crash when acessing enum through derived class

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#789]
In this code, the typealias causes a crash, probably because it's accessing the enum through the derived class
```
	typealias EAlias = STest.ETest;

	public class STest : STest<Stream>
	{
	}

	public class STest<T>
	{
		public enum ETest
		{
			A,
			B,
			C
		}
	}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/ccacf0b9db77576a8c5bcd90e6d342e697a6c42e
