### ISSUE TITLE
[Feature Request] Ctrl+Click jump to defination and clicking to set breakpoints

### ISSUE THREAD

**Issue by HydrogenC** [beefytech/Beef#79]
Beef is an excellent language with a elegant codestyle and a fully-featured ide. 
However, to jump to defination requires pressing F12, which is hard to do on laptops (on laptops I have to press Fn+F12). Please make it able to jump to defination with ctrl+click like Visual Studio. 
Also, please implement "click on line number to set breakpoint" like Visual Studio and other common IDEs.

**Comment by HydrogenC** [comment]
Also, is it possible to implement "click on line number to set breakpoint" like Visual Studio?

**Comment by damianday** [comment]
I agree with the click on the line in the gutter to set code breaks, I think they can be removed that way so we're good way their

**Comment by bfiete** [comment]
Good features. Implemented in https://github.com/beefytech/Beef/commit/9102a54ce4f6d141bf53449802349cb839393399, will be in release 0.42.2 (planned for later this month).

**Comment by HydrogenC** [comment]
Great, glad to see that. Thanks.
