### ISSUE TITLE
[BUG] "Delegate constrained" type can't be called & Crash

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#790]
I wanted to be able to do a "templated delegate" in Beef, the first thing I thought was using a `var` constraint to allow a behaviour similar to templates, but looks like currently there's no way to call a `var` constrained type...  Afterwards, I tried to specialize the method that calls the delegate based on the delegate type, but this causes a crash (and looks like it also can't be called like the `var` constraint).
Here's my test code
```
	struct TestFunc<T, Del>
	{
		private int mId;
		private Del mComparer;

		public static TestFunc<T, Del> Create(int id, Del comparer)
		{
			return .()
			{
				mId = id,
				mComparer = comparer
			};
		}

		public bool Check(T item) where Del : delegate bool(T)
		{
			return mComparer(item);
		}

		public bool Check(T item) where Del : delegate bool(int, T)
		{
			return mComparer(mId, item);
		}
	}

	class Program
	{
		public static int GetID()
		{
			return 10;
		}
		
		public static int Main(String[] args)
		{
			let testF = TestFunc<String, delegate bool(String)>.Create(10, scope (s) => s == "Str");
			testF.Check("Str");

			let testF2 = TestFunc<String, delegate bool(int, String)>.Create(10, scope (i, s) => i == GetID() && s == "Str");
			testF2.Check("Str");
		}
	}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/093a617b560fc295722d47c8013ce739fbf4eaed
The whole code snippet actually works now.
