### ISSUE TITLE
[BUG] Crash with deleting lines

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#792]
Atma.Framework branch crashOnDelete

If you open `JsonReader2Tests.bf` (note the 2) and go to line 16 `let jr = scope JsonReader2();` and then just hit `ctrl-x` three times the IDE will crash with

```
FATAL ERROR
(mModule->mCurMethodState->mClosureState != NULL) || (mModule->mBfIRBuilder->mIgnoreWrites) in C:\Users\cphillipd83\Documents\Git\Beef\IDEHelper\Compiler\BfExprEvaluator.cpp:3448

Executable: C:\Users\cphillipd83\Documents\Git\Beef\IDE\dist\BeefIDE_d.exe

File Version: 0.42.9

Product Version: 0000000000000000
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/07bb71150d194f87abaa16d99f51a963ae6112ea
