### ISSUE TITLE
[BUG] Crash with the following code

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#796]
I was trying to define a vec2 class with the new ctor stuff and it crashes the IDE. I'm aware this isn't valid, I was 1/2 way through writing a ctor and I was like "oh wait, he committed new ctor stuff".

```
using System;
namespace Atma.Json.Tests
{
	class JsonStructTests
	{
		[Serializable]
		public struct vec2:this(int x{
			public int x, y;
			public this
		}

		[Test]
		public static void Test(){

		}
	}
}

```

**Comment by xposure** [comment]
This also seems to crash on build.
```
		public struct vec2:this(int x, int y){}

		public struct vec3:this(vec2 v2, int z){}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/2fd58a38bb87c96c53fa6306225aad504714b7a0 and https://github.com/beefytech/Beef/commit/111631dd9cf55a04f6827a00469c25f7cc9f68ee
