### ISSUE TITLE
[BUG] Thread.CurrentThread is null in a static constructor

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#802]
_(This constructor is called by a static constructor)_
![image](https://user-images.githubusercontent.com/14041768/103711961-5767ab80-4f97-11eb-850a-c0dac50439c1.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/080dd5a25ead1eeb5c100a678b626cfbab52622e

**Comment by Igoorx** [comment]
Hey @bfiete, I encountered another problem related to this issue, the Thread.CurrentThread is being deleted before my class static dctor is called and this causes an access to a deleted object error:
![image](https://user-images.githubusercontent.com/14041768/104640722-9ed0f480-5687-11eb-8a25-06dbd094cabe.png)
