### ISSUE TITLE
[Enhancement] Unintuitive Error Message When Overloading Operators's Result is Discarded

### ISSUE THREAD

**Issue by jdbener** [beefytech/Beef#807]
I have been experimenting with the language and I found a weird edge case with operator overloading. If you don't store the result of the operation then the compiler spits out an error:

```
ERROR: This expression cannot be used as a statement at line 44:4 in /.../beef-test/src/Program.bf
t + 7;
^^^^^^
```

I spent a good half an hour experimenting trying to figure out what "This expression cannot be used as a statement" was supposed to mean. If this behavior is intended and overloaded operator's results need to be used, a better error message (maybe like "Overloaded Operators cannot have their return types discarded.") would be helpful.

```c#
namespace beeftest {      
       class Tests {
		int val = 5;

		public static int operator + (Tests t, int o){
			return t.val + o;
		}
	}

	class Program {
		public static int Main(String[] args) {
	         	Tests t = scope Tests();

			// Works
			int res = t + 7;

			// Errors
			t + 7;

			return 0;
		}
	}
}
```

**Comment by bfiete** [comment]
The error in C# is `CS0201: Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement`

That seemed a bit verbose. It has nothing to do with operator overloads, by the way.

**Comment by bfiete** [comment]
If someone has a suggestion for better phrasing then I'd be open to that...
