### ISSUE TITLE
Bug? with generics in multi project workspace

### ISSUE THREAD

**Issue by MineGame159** [beefytech/Beef#813]
[GenericsIssue.zip](https://github.com/beefytech/Beef/files/5824635/GenericsIssue.zip)

After the workspace is opened this error comes up:
![image](https://user-images.githubusercontent.com/25082624/104815946-277e9a80-5818-11eb-81dd-28162f8c5851.png)

**Comment by bfiete** [comment]
Thanks for the bug.
Fixed at https://github.com/beefytech/Beef/commit/da49fa0408a05db90496a19bddbed875ece2e04f
