### ISSUE TITLE
[Bug] Crash when extending IEnumerable

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#815]
This only happens when making an extension of IEnumerable<T>, does not crash when extending an identical class with a different name.

```cs
namespace System.Collections
{
	extension IEnumerable<T>
	{
		public void Method()
	}
}
```

Crashes when typing out the parenthesis.

[IEnumerableExtensionBugDump.zip](https://github.com/beefytech/Beef/files/5825285/IEnumerableExtensionBugDump.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/7787efda7e17fcf03f46036951475eacfc78621d
