### ISSUE TITLE
[Enhancement] Better indication of failed tests

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#819]
When you have a lot of tests, you don't see the errors in the output unless you scroll up and this deceptively looks like the tests passed unless you read the end of the line. Some like turning this line red if there is a failed test would be a quicker way to see it at a glance.

![image](https://user-images.githubusercontent.com/6292318/104846511-ea161d80-58a8-11eb-825f-9c345af1b475.png)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/dcfcc03a552b160642589cadd0bfa7e71efb3947
