### ISSUE TITLE
[BUG] Template causes code generation crash

### ISSUE THREAD

**Issue by jazzbre** [beefytech/Beef#821]
Bellow is a little sample project, just try to run it, it crashes with (nightly build 16.1.2021):
`FATAL ERROR
Failure during codegen of ??$AddState@PEAVStartState@TutorialBasicStateMachine@Game@bf@@@StateMachine@Game@bf@@QEAAX_N@Z in Game_StateMachine: Unable to find bevalue for operand: void %0
 MCBlock: entry:0`

The problem is with the AddState<T> in TutorialBasicStateMachine.bf at line 21.

[Test.zip](https://github.com/beefytech/Beef/files/5826694/Test.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/6d06ee3430c296cf02da6ed3f751267eb50d6b1d
