### ISSUE TITLE
[Bug] IDE crashes on compile (Also crashes when relaunching in safe mode without compiling)

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#823]
I can't say much more, can't find a reproducible example, but I think it has something to do with the Texture class and ContentWindow. I was trying to load a png as a texture and show it in the editor.
Here's the project (WeTransfer since FileBin doesn't work):
https://we.tl/t-YFSujCMlAJ

**Comment by RogueMacro** [comment]
Not a problem when re-installing to the latest nightly

**Comment by bfiete** [comment]
Oh, yes, this was fixed but I forgot to close it. I think it was this fix https://github.com/beefytech/Beef/commit/6d06ee3430c296cf02da6ed3f751267eb50d6b1d
