### ISSUE TITLE
[Enhancement] Feature to get the address of the ... argument list

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#824]
It would be very helpful for consuming variadic C API's (specifically, ones that take `va_list`), if there was a feature in Beef to be able to get the address of a `...` argument list.

Example:
```
void MyTestFunc(int count, ...)
{
    void *va_list = ThisProposedFeature();
    CLibrary.variadic_api(count, va_list);
}
```

**Comment by bfiete** [comment]
This is supported now (in the next nightly) with https://github.com/beefytech/Beef/commit/9ccdf7282e4c7c5d5c0aa0ac9d3a95fc43c0dab5

See usage cases at https://github.com/beefytech/Beef/blob/master/IDEHelper/Tests/src/VarArgs.bf
