### ISSUE TITLE
[BUG] Crash with interface that declares a method

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#827]
The following code crashes while compiling, the crash doesn't occur if `TestC<T>` doesn't extend `MyInterface<T>`
```
interface MyInterface<T>
{
	public bool Any()
	{
		return false;
	}
}

class TestC<T> : MyInterface<T>
{
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/95fe97496c82cceafc046e3ac64aa3c96b0a3a00
