### ISSUE TITLE
[BUG] Cannot declare delegate type for function which returns a ref

### ISSUE THREAD

**Issue by hunterbridges** [beefytech/Beef#828]
Consider the following syntax (though practically it would cause infinite recursion)

```
public static ref int32 DoReferenceThing(ref float floatyMan)
{
	function ref int32(ref float) func = =>DoReferenceThing;
	return func(ref floatyMan);
}
```

This should be a valid use of ref, but the compiler throws an error

**Comment by bfiete** [comment]
Thanks for the bug.
Fixed at https://github.com/beefytech/Beef/commit/77c3eebbae694227737058574e0a1fc589665994
