### ISSUE TITLE
[BUG] Events doesn't work if they are a property

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#829]
Maybe this one isn't a bug, I guess this is happening because the value being returned from the getter is a copy of the Event, so if it's not possible to make this code work correctly I think this should at least give a warning (I lost some time thinking there was something wrong with my code when in the end this was the cause :P)
```
	public class MyEvent
	{
		public Event<EventHandler> Event { get; set; }
	}

	class Program
	{
		public static int Main(String[] args)
		{
			MyEvent MyEvent = scope .();
			MyEvent.Event.Add(new (event, e) => { Console.WriteLine("Called!"); });
			MyEvent.Event(null, null);
			// Nothing gets shown in the console...
			return 0;
		}
	}
```

*Update*
Actually, if the property is in the `Program` class, the Event works correctly, so I think this must be a bug. Here is the code that I tested and works:
```

		public static Event<EventHandler> Event { get; set; }
		public static int Main(String[] args)
		{
			//MyEvent MyEvent = scope .();
			Event.Add(new (event, e) => { Console.WriteLine("Called!"); });
			Event(null, null);
			// OK! "Called!" shows in console
			return 0;
		}
	}
```

**Comment by xposure** [comment]
If you look at Event<T> its just a struct that manipulates a `int` member, is this due to modifying a copy of a struct?

Perhaps thsi would work? 'public static ref Event<EventHandler> Event { get; set; }`

**Comment by bfiete** [comment]
@xposure is right - you get a new copy of `Event<EventHandler>` on each call. The fix should be to add 'ref' but that caused a bug, so... fixing that bug now.

**Comment by Igoorx** [comment]
@bfiete But why this works when the property is in `Program` but not when the property is in `MyEvent`?

**Comment by bfiete** [comment]
That's correct. Though that optimization has a bug (as you've noticed) because it should create a copy also.

**Comment by bfiete** [comment]
ref autoprop issue fixed here https://github.com/beefytech/Beef/commit/18208cb95816bbfbe32f93d5352e441ffad70dcd

**Comment by bfiete** [comment]
Autoprop direct-field-access optimization value copy bug fixed here https://github.com/beefytech/Beef/commit/981e56baada21dc40d017ccb4f670c7d72d6904a

**Comment by bfiete** [comment]
I didn't see the possibility of a warning here. Note that this is also how C# (and C/C++) works and there's no warnings.

The warning would have to be "calling a mutable method on a copy of a value" or something? I don't see any general warning that would make sense...

**Comment by Igoorx** [comment]
> I didn't see the possibility of a warning here. Note that this is also how C# (and C/C++) works and there's no warnings.
> 
> The warning would have to be "calling a mutable method on a copy of a value" or something? I don't see any general warning that would make sense...

I guess you're right, I only thought a warning would make sense because, using the code of this issue as example, `MyEvent.Event.Add` does nothing (and even leaks memory in this case)

**Comment by bfiete** [comment]
One could imagine something like a `[WarnIfCalledOnTemporaryValue]` method attribute or something, but I'm not sure it's really worth it.

**Comment by Igoorx** [comment]
What about a [NoCopy] Attribute that would give a warning if the type is copied? I guess this would be a perfect fit when the type isn't meant to be copied

**Comment by bfiete** [comment]
There's no problem with copying an `Event<T>`, as long as Dispose gets called on ONE of the copies eventually.

**Comment by Igoorx** [comment]
I see... I only have one more idea, I don't know how practical this is but what about a `[NoDiscard]` but for types? This makes sense as in the example of `MyEvent.Event.Add` what is happening is that a new copy of `Event<EventHandler>` is being created and the `Add` method is being called on it and then it's immediately "discarded" (without ever being assigned to an variable for example), the only operations that is possible with Events are `Add`, `Remove`, `Invoke`, `Dispose` and every one of them have some sort of issue if you call it in a copy that is later discarded:
```
// 1. Call Add
// Result: Would leak & Doesn't apply to original Event & Makes a unnecessary copy
MyEvent.Event.Add(new (event, e) => { Console.WriteLine("Called!"); });

// 2. Call Add and then call Invoke
// Result: Would leak & Doesn't apply to original Event & Makes a unnecessary copy
(MyEvent.Event..Add(new (event, e) => { Console.WriteLine("Called!"); }))();

// 3. Call Remove
// Result: Makes a unnecessary copy & Leaves the original Event in UB
MyEvent.Event.Remove(new (event, e) => { Console.WriteLine("Called!"); });

// 4. Call Invoke
// Result: Makes a unnecessary copy
MyEvent.Event(null, null);

// 5. Call Dispose
// Result: Makes an unnecessary copy & Leaves the original Event in UB
MyEvent.Event.Dispose();
```

**Comment by bfiete** [comment]
That's what I meant with `[WarnIfCalledOnTemporaryValue]` here https://github.com/beefytech/Beef/issues/829#issuecomment-763760972

**Comment by bfiete** [comment]
I don't think putting it on the whole _type_  makes sense because it would break if we added something like an "IsEmpty" property which _does_ work just fine on copies...

**Comment by bfiete** [comment]
Also there's no issue with Invoke. "unnecessary copy" is a single pointer-sized value.

**Comment by Igoorx** [comment]
Oh, I thought the `WarnIfCalledOnTemporaryValue` attribute was meant to be applied to the method, not to the type, but anyway, If a copy isn't a problem, I think the case of `IsEmpty` and `Invoke` could be solved with an argument in the attribute like `OnlyMutable`, that doesn't consider that it is being discarded if the method called isn't mutable, basically https://github.com/beefytech/Beef/issues/829#issuecomment-763729798 (or `WarnIfCalledMutableOnTemporaryValue`)
But this looks too specific so I can understand if you don't like the idea lol
