### ISSUE TITLE
[BUG] Crash on IDE load and safe mode load

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#830]
https://github.com/xposure/Beef.Linq/commit/97010278fd23588c1b0db6558dfb407fa920721d

If you look at the commit diff here from the prior commit, it looks like formatting the document stripped a lot of stuff off. All those `where` changes weren't done by me.

**Comment by Igoorx** [comment]
Adding my testimony to this issue, it seems to me that recently many crashes (if not all) are also crashing in safe mode, I guess some change broke the safe mode.

**Comment by bfiete** [comment]
A general parsing issue can break safe mode. Those should be very rare.

**Comment by bfiete** [comment]
Oh, actually safe mode was just broken recently when making some IDE features asynchronous which were previously synchronous, which was required due to (potentially) unbounded comptime execution time.

**Comment by bfiete** [comment]
Linq qrash fixed at https://github.com/beefytech/Beef/commit/92d14df5bd02eedff2ace99ff97da9dae2d12538
Safe mode crash fixed at https://github.com/beefytech/Beef/commit/6c3b2d9eea147675e42292d8bd67e2cdac4b7c2c
