### ISSUE TITLE
[LINQ] Intellisense isn't picking up extension methods

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#831]
If you open xposure/Beef.Linq and in the test project, try to type any of the extensions for linq, you'll notice that intellisense doesn't pick up the methods, but once you type it out and hit `(` you will then get the correct intellisense for the method.
 ```
let data = new List<int>();
data.Wh //no intellisense
data.Where( //intellisense shows for the extension
```

**Comment by bfiete** [comment]
Added at https://github.com/beefytech/Beef/commit/3560554127c45133ad1e08bf098bf8504d18c71b
Also there's a distinct icon in autocomplete for extension methods now, too.
