### ISSUE TITLE
[LINQ] Array support for IEnumerable<T>

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#832]
Arrays need to support the concrete IEnumerable<T> interface (error is unable to determine TElem, perhaps its just a inference issue)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/3f35ef51f21179380eaaa996b9f20d04294a43dc

**Comment by Igoorx** [comment]
@bfiete SizedArray is still lacking IEnumerable<T>

**Comment by xposure** [comment]
https://github.com/beefytech/Beef/issues/842
