### ISSUE TITLE
[LINQ] Sum/Average/Etc with nullable primitives

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#835]
.Net has the aggregate methods as concrete primitives, aka (int, float, double, etc) rather than generics because of the lack of operator constraints. They also have a variation of all the same methods but (int?, float?, double?), I assume it returns null if there are no items in the list because the ienumerable is still IEnumerable<int> (not nullable). I think this would also require something for `var t = default(TResult) as it shouldn't be nullable` unless there isnt much of a performance issue with accessing `.Value`

```
		public static TResult? Sum<T, TElem, TResult, TSelector>(this T items, TSelector selector)
			where T : concrete, IEnumerable<TElem>
			where TResult : operator TResult + TResult
			where TResult : operator TResult / TResult
			where TSelector : delegate TResult(TElem)
		{
			var hasElements = false;

			var t = default(TResult);
			for (var it in items){
				t += selector(it);
				hasElements = true;
			}

			if(!hasElements)
				return null;

			return t;
		}
```

**Comment by xposure** [comment]
```
Binary operation for 'System.Linq.Sum<System.Collections.List<int?>, int?>(System.Collections.List<int?> items)' must result in 'int?' from binary operation 'int? + int?' at line 146:23 in c:\Users\cphillipd83\Documents\Git\Beef.Linq\src\test\src\EnumerableTests.bf
    let actual = data.Sum();
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/d0cfb373092e4df544f66b2e70843b04ae4291ba
