### ISSUE TITLE
[LINQ] Concrete type methods are called over extension methods

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#836]
https://github.com/xposure/Beef.Linq/commit/46e9f6adff62b1d6a1b98fa54c3a5577533c1426

Suggestions on how to handle `.Contains()`, perhaps just rename it to something else or allow it to select the extension method of the base method?

The problem is that we have concrete types and if that concrete type has a GetEnumerator + Contains method, it will always call the concrete types Contains instead of linq. This is an issue because it forces code to be executed on call rather than when enumeration happens.

**Comment by bfiete** [comment]
I'm not following. Is this different than how C# handles extension methods somehow? 
How do you call the Linq `Contains' on a C# `List<T>`?

**Comment by bfiete** [comment]
And I'm not understanding the case where you don't want to call the List.Contains

**Comment by xposure** [comment]
The issue was more about "deferred execution", that something like .Contains() doesn't happen until the enumerator actually executes. But as I was playing with different examples (one being something like GroupBy) I realized that these would all be lambdas and would still have the same deferred execution. Also note that there isn't an enumerator for Contains in C# linq.

So perhaps its not an issue for it to call that and it only needs to default back to LINQ version if the concrete doesn't have it.

For reference.

```
        public static bool Contains<TSource>(this IEnumerable<TSource> source, TSource value) {
            ICollection<TSource> collection = source as ICollection<TSource>;
            if (collection != null) return collection.Contains(value);
            return Contains<TSource>(source, value, null);
        }
 
        public static bool Contains<TSource>(this IEnumerable<TSource> source, TSource value, IEqualityComparer<TSource> comparer)
        {
            if (comparer == null) comparer = EqualityComparer<TSource>.Default;
            if (source == null) throw Error.ArgumentNull("source");
            foreach (TSource element in source)
                if (comparer.Equals(element, value)) return true;
            return false;
        }
```


I'm going to let this stew for a little bit, but I think you are right, this isn't needed, since its executed on call in c# as well.

**Comment by bfiete** [comment]
Hm. I'm still not really getting what an "enumerator for contains" even means. Don't you always just want `Contains` to produce a single value? It's not supposed to generate a list of values... I'm still 100% confused here.

**Comment by xposure** [comment]
No, you are right, I had a false assumption of how contains worked in C# over IEnumerable, it returns a single value on invocation, there is no enumerators or deferred execution, it works like Sum/Avg/Count/etc. Other scenarios like GroupBy would have lambdas called on the subset of data so it would also work correctly. My gut is just saying that I think I'm missing a scenario, but according to the C# source, there isn't one.
