### ISSUE TITLE
[BUG] IDE crash, not reproducible

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#837]
![image](https://user-images.githubusercontent.com/6292318/105230067-d847ab00-5b32-11eb-91c6-a127e32cd665.png)

When I hit `}` it crashed.

**Comment by bfiete** [comment]
Oh- if you do get something like this then try attaching another instance of the IDE and then post a screenshot of the callstack at the crash if you can.

**Comment by xposure** [comment]
Will do
