### ISSUE TITLE
[BUG] Array ref foreach can't infer type anymore

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#838]
The following code was working previously but doesn't work anymore:
```
			int[10] aaa = .();
			for (var a in ref aaa)
				a = 0;
```

if you change the code to the following, it works again:
```
			int[10] aaa = .();
			for (int a in ref aaa)
				a = 0;
```

_Update:_ Actually the code doesn't work as I expected, even though it compiles, the values of the array doesn't change, I can't remember if before this was working, but I can't use `ref int` in the foreach because of the error: `Unable to cast 'int' to 'ref int'`

_PS: Tested with the latest version that I compiled myself_

**Comment by bfiete** [comment]
It's your fault - I broke it while fixing another one of your bugs!

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/b1432782a821f621b953484bb9941cb3d89ba104
