### ISSUE TITLE
[BUG] Use of unassigned field error

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#840]
This code gives me the error `Use of possibly unassigned field 'myInt'` even though it's clearly assigned.
```
	public class TestC<T>
	{
		private int myInt;

		public this()
		{
			myInt = 0;
		}

		public InnerClass Get()
		{
			myInt = 0;
			return InnerClass(this);
		}

		public struct InnerClass
		{
			TestC<T> parent;
			int myInt;

			public this(TestC<T> test)
			{
				parent = test;
				myInt = parent.myInt; // Use of possibly unassigned field 'myInt'
			}
		}
	}
```

**Comment by bfiete** [comment]
You sure that reproduces for you in isolation?
I'm not seeing the error here on the latest nightly build.

**Comment by Igoorx** [comment]
@bfiete For some reason looks like this error only happens in Release mode.

**Comment by bfiete** [comment]
Oh, yes, that does it.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/e1394e2fb7c49f8178ed7f9d19da9d73183da4da
