### ISSUE TITLE
[BUG] Moving a ignored file to a new folder causes a crash

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#844]
Repro:
![multiplefilemovebug](https://user-images.githubusercontent.com/14041768/105255078-af8ada00-5b61-11eb-841b-8b1e4810148a.gif)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/0543dfec65938f34f22f02c10e623b7254636dc5
