### ISSUE TITLE
[BUG] IDE Hangging when a tab is closed

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#845]
Here is what I did that led to the hang:
![idehang](https://user-images.githubusercontent.com/14041768/105255562-920a4000-5b62-11eb-9ba2-97ebe0398b99.gif)

Here is a screenshot of the callstack when the IDE hangs:
![image](https://user-images.githubusercontent.com/14041768/105254575-ab11f180-5b60-11eb-81ff-e85df862a756.png)

The code that can reproduce this hang is this one:
```
using System;
using System.IO;
using System.Collections;
using System.Diagnostics;
using System.Reflection;
using System.Linq;

namespace test5
{
	class Program
	{
		public static int Main(String[] args)
		{
			int[] test1 = scope .(10, 11, 10, 12, 13, 14, -1);
			int val = test1.Reverse().Take(2).Where((x) => x > 0 && x % 2 == 0)/*.Take(2)*/.Sum();
			Console.WriteLine(val);


			Console.Read();
			return 0;
		}
	}
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/c0dd9b0e0949e2ccb587bc3d14cd060ad3871edc
