### ISSUE TITLE
[BUG] "new" keyword doesn't work on the signature of methods inside extensions

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#847]
![this](https://user-images.githubusercontent.com/14041768/105274042-2bdde700-5b7b-11eb-9970-02930376e392.gif)

**Comment by bfiete** [comment]
Hm- can you post a text sample? I was trying to reproduce this and I'm not getting that error.

**Comment by bfiete** [comment]
Ah no I just got it nevermind.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/7093476126f6addf28b299b9254e758c0763c43d
