### ISSUE TITLE
[Enhancement] Dynamic casting

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#848]
By dynamic casting, I mean to cast an object to a `Type` at runtime. Specifically being able to cast it to an interface that can be passed to a constructor invoked at runtime.

**Comment by xposure** [comment]
Something like this? 

```
(T*)Internal.UnsafeCastToPtr(xy);
```

**Comment by RogueMacro** [comment]
No, not generic. I meant using a `Type` object. Like `typeof(T)`

**Comment by RogueMacro** [comment]
@bfiete You could close this as dynamic casting it provided by Variants.
```cs
BaseItem item;
Item itemImpl = scope .();
Variant variant = Variant.Create(typeof(BaseItem), &itemImpl);
item = variant.Get<BaseItem>(); // or Get<Object>()
```
