### ISSUE TITLE
[BUG] Crash while const evaluating method

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#853]
Just for curiosity, I was trying to make the [WeekendRaytracerWithBeef](https://github.com/DerTee/WeekendRaytracerWithBeef) project work in compile-time, but this crashes the IDE while compiling
Unfortunatelly, I have no idea what is causing the crash so I will have to send the whole modified project, here it is: [WeekendRaytracerWithBeef-master.zip](https://github.com/beefytech/Beef/files/5858354/WeekendRaytracerWithBeef-master.zip)

**Comment by bfiete** [comment]
This is closer to working (https://github.com/beefytech/Beef/commit/61f54a4f887af367e5ce5a167fa431c1b76d96c8)
Still working on some issues...
