### ISSUE TITLE
[BUG] Concatenation of stringified const crashes the IDE

### ISSUE THREAD

**Issue by Igoorx** [beefytech/Beef#854]
The following code crashes the IDE, it doesn't crash if Stringify is commented out and replaced with the content of the consts.

```
	[Comptime(OnlyFromComptime=true, ConstEval=true)]
	public static String Stringify<T>(T value)
		where T : var
	{
		String str = scope String();
		value.ToString(str);
		return str;
	}

	public static class VersionInfo
	{
		public const int Version = 0;
		public const int SubVersion = 1;

		public const String VersionStr = Stringify(Version) + (SubVersion > 0 ? "." + Stringify(SubVersion) : String.Empty);
	}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/41f95003fe64430bb54d1721c12a93edd6746986

This works without any `[Comptime]` attributes now.

**Comment by Igoorx** [comment]
@bfiete Thanks again for the fix! While testing I noticed that `OnlyFromComptime` is causing an error now, so I changed the function attribute to be only `[Comptime(ConstEval=true)]`, because I wanted this function to only return const strings, as it returns a deleted string without this attribute:
![image](https://user-images.githubusercontent.com/14041768/105610136-cb25f880-5d8c-11eb-9140-8d33d73f0925.png)

But with the attribute on the function, the IDE is still crashing in the same way if you `Clean` and then `Build`
![crashcrashxx](https://user-images.githubusercontent.com/14041768/105610300-d2013b00-5d8d-11eb-944c-c3bb1c9ab277.gif)
_(Although this isn't much of a big deal for me because I will not really use this function outside of consts)_

**Comment by bfiete** [comment]
Yeah, the `[Comptime(ConstEval=true)]` is required if you want to force a const result.
I'll look into the crash issue from the gif.

**Comment by bfiete** [comment]
I fixed some bugs in comptime since this, and I guess this was one of the bugs - I can't reproduce it anymore.
