### ISSUE TITLE
Collections.Generic.Queue problems

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#86]
SetCapacity does not delete its buffer before it is reassigned causing a GC crash.
Base constructor never sets the default capacity (cDefaultCapacity).
The class could probably benefit from using AllowAppend like List does.

**Comment by bfiete** [comment]
Made some improvements here https://github.com/beefytech/Beef/commit/96c53d4a9e0b740483e5b21644bffcc31273c883

Also it has a debug visualizer defined now.

The 'cDefaultCapacity' is copied from the C# impl, which only uses it when initializing from an IEnumerable<T> where it's not possible to know the size ahead of time. Our current impl doesn't have that functionality.

**Comment by damianday** [comment]
Thank you
