### ISSUE TITLE
[LINQ] Error with constaints on sub types that reference outter generics

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#867]
1721acf

If you open Enumerable.bf and go to `MapEnumerable` and uncomment the code towards the end, this code can't compile due to some generic constraints issues.

**Comment by bfiete** [comment]
This was a general issue of extern constraints (constraints such as `where float : operator T + T`) were not accessible from inner types.
Fixed at https://github.com/beefytech/Beef/commit/925497f1e7ce49890bebe8200fa2544abef51004
