### ISSUE TITLE
[Enhancement] Allow for const unions

### ISSUE THREAD

**Issue by EnokViking** [beefytech/Beef#870]
Like the title says, a nice addition would be const unions, example where it's required below:

```cs
public enum LayerOrder
{
    PushBack(void);
    PushFront(void);
    Custom(int order);
}

public struct LayerPriorityAttribute : Attribute
{
    private LayerOrder _order;

    public this(LayerOrder order) 
    {
        _order = order;
    }
}

[LayerPriority(.Custom(1))]
public SomeClass
{

}
```

The above example doesn't currently work because LayerOrder cannot be evaluated as a constant value

**Comment by bfiete** [comment]
This is partially supported now at https://github.com/beefytech/Beef/commit/86967c39c3ab4ae1b49d64a58e24d3ba1991d82a
In particular, payloads with string literals still won't work. That requires a much larger change which will be coming in the future some time.

**Comment by bfiete** [comment]
We can handle string values in const enums now at c9f1e37da7a0fcf0eda17755cd76749b0f6f2564
