### ISSUE TITLE
[Bug] Pointer arithmetic

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#871]
In the example below "TestStruct" has a size of 12 and a stride of 16. Using an index or addition-operators adds sizeof(TestStruct) to "ptr". The increment operator however adds strideof(TestStruct).

```C
struct TestStruct
{
	int32 dw;
	int64 qw;
}

static int Main(String[] args)
{
	TestStruct* ptr = (.)(void*)0;
			
	TestStruct* ptrIndex = &ptr[1]; // = 12

	TestStruct* ptrAdd = ptr + 1; // = 12
	
	TestStruct* ptrAdEq = ptr;
	ptrAdEq += 1; // = 12

	TestStruct* ptrInc = ptr;
	ptrInc++; // = 16

	return 0;
}
```

**Comment by bfiete** [comment]
Good bug, thanks.
Fixed at https://github.com/beefytech/Beef/commit/e60bbdf64fea73e8584c2d8a589cdaf2fa2a96d8
