### ISSUE TITLE
Generic type is based on another generic

### ISSUE THREAD

**Issue by kochol** [beefytech/Beef#872]
Hi
I want to say my generic type is based on another one so I can cast from Base to T in my method.
this is a sample code
```
ComponentHandle<T> CreateComponent<T, Base>() where Base : IComponent
where T : Base, class, new    
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/1519a6010448d8b46f96717e52f3a8652c29b635
