### ISSUE TITLE
[Enhancement] Proper wrapping for mouse messages

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#877]
1. Proper wrapping of mouse over messages like errors, long messages will just go off the screen.
2. Also make sure that wrapping is tied to the monitor instead of going off on to a 2nd display.

**Comment by xposure** [comment]
![image](https://user-images.githubusercontent.com/6292318/106374343-9f88ac80-6350-11eb-9ce2-493e0633ea2d.png)

**Comment by bfiete** [comment]
Get it a try https://github.com/beefytech/Beef/commit/142332baaa70dfafdb65699f0ab7ebe1016a7a8d
I didn't explicitly try multi-mon but I think it should work.

**Comment by xposure** [comment]
Not that important and please ignore the potato quality of the picture, but if you look in the middle there, you can see some of the tooltip bleeding to the next monitor. Maybe add some padding to the rect?

![image](https://user-images.githubusercontent.com/6292318/106525654-4df83300-64b2-11eb-8eee-f84c8166939f.png)

**Comment by bfiete** [comment]
I think this should do it then: https://github.com/beefytech/Beef/commit/012f093d268dc48a6d5ddfe328ad4d0c7ca5dac3

**Comment by xposure** [comment]
Yep, has nice padding from the edge now.
