### ISSUE TITLE
Unable to find entry point class Sample1.Program' in project 'Sample1'

### ISSUE THREAD

**Issue by vinodvinu** [beefytech/Beef#878]
Hi all,
I just installed the IDE in Windows and tried a Hello World sample. But when i try to compile, it shows this as error message.
Unable to find entry point class Sample1.Program' in project 'Sample1'

Do i miss something ?
These are my steps.
1. Created a new project named Sample1. It creates a folder with same name. 
2. Created a new class and copy the hello world code.
3. Tried to compile but got this error message.

**Comment by bfiete** [comment]
The startup object in your project properties under General/Beef/Startup Object does not match your startup object in your actual code.

**Comment by vinodvinu** [comment]
@bfiete
Thanks for quick response. It worked like charm. But it's not showing the result in output window. Instead result showed in a new cmd window. Anyhow, I managed it with a Console.Read() ;. I hope i can have fun with some Beef coding now. :)

**Comment by bfiete** [comment]
The output window does not show console output.

**Comment by bfiete** [comment]
Also check out the Discord channel at https://discord.gg/rnsc9YP for help, if you want.

**Comment by vinodvinu** [comment]
> Also check out the Discord channel at https://discord.gg/rnsc9YP for help, if you want.

Sure
