### ISSUE TITLE
[Bug] Comptime method giving different results depending on how many Compiler.EmitTypeBody calls

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#880]
Not much more to say. I couldn't make a minimal example so you get the whole file:
```cs
using System;

namespace BugTesting
{
	[Serializable]
	class SerializableClass
	{
		public int Number1 = 1;
		public SerializableSub Sub;
	}

	[Serializable]
	class SerializableSub
	{
		public String Str = "Hello World!";
		public StringView StrView = "I'm a StringView!";
	}

	class Program
	{
		public static int Main(String[] args)
		{
			var test = scope SerializableClass();
			test.ToJson(.. scope .());

			return 0;
		}
	}

	[AttributeUsage(.Class | .Struct, ReflectUser=.NonStaticFields | .StaticFields | .DefaultConstructor | .DynamicBoxing)]
	public struct SerializableAttribute : Attribute, IComptimeTypeApply
	{
		[Comptime]
		public void ApplyToType(Type type)
		{
			Compiler.EmitTypeBody(type, scope $"public void ToJson(String output, bool pretty = false) \n{{\n");
			Compiler.EmitTypeBody(type, "	if (pretty)\n	{\n		");
			//EmitJson(type, true);
			Compiler.EmitTypeBody(type, "\n	}\n	else\n	{\n		");
			EmitJson(type, false);
			Compiler.EmitTypeBody(type, "\n	}\n}");

			
		}

		[Comptime, OnCompile(.TypeDone)]
		private static void EmitJson(Type type, bool pretty)
		{
			Compiler.EmitTypeBody(type, "output.AppendF(\n\"\"\"\n");

			EmitJsonValue(type, type, pretty);

			Compiler.EmitTypeBody(type, "\n\"\"\",\n");

			bool isFirst = true;
			for (var field in type.GetFields())
			{
				if (!isFirst)
					Compiler.EmitTypeBody(type, ",\n");
				else
					isFirst = false;

				Compiler.EmitTypeBody(type, scope $"			{field.Name}");
			}

			Compiler.EmitTypeBody(type, "\n		);");
		}

		[Comptime]
		private static void EmitJsonValue(Type serializableType, Type fieldType, bool pretty)
		{
			Compiler.EmitTypeBody(serializableType, scope $"");

			if (fieldType == typeof(String))
			{
				Compiler.EmitTypeBody(serializableType, "\"{}\"");
			}
			else if (fieldType.IsIntegral || fieldType.IsFloatingPoint)
			{
				Compiler.EmitTypeBody(serializableType, "{}");
			}
			else if (fieldType.IsArray)
			{

			}
			else
			{
				

				Compiler.EmitTypeBody(serializableType, "{{");
				bool isFirst = true;
				for (var field in fieldType.GetFields(.Instance | .Public))
				{
					if (field.FieldType == typeof(StringView))
						continue;

					if (!isFirst)
						Compiler.EmitTypeBody(serializableType, ",");
					else
						isFirst = false;

					Compiler.EmitTypeBody(serializableType, scope $"\"{field.Name}\":");
					EmitJsonValue(serializableType, field.FieldType, pretty);
				}
				Compiler.EmitTypeBody(serializableType, "}}");
			}
		}
	}
}
```

Try duplicating the first line in EmitJsonValue() and try making it a normal string and a scope $"" string and so on. It gives different results. See F12 on the ToJson() method to see.

**Comment by bfiete** [comment]
I'm not understanding the reproduction instructions. Can you give step-by-step instructions on what you're expecting to see and what you _actually_ see?

**Comment by bfiete** [comment]
I mean, clearly the `Compiler.EmitTypeBody(serializableType, scope $"");` is a no-op instruction since you are just adding an empty string...

**Comment by RogueMacro** [comment]
I'll make a more detailed explanation later when I get home, but I can tell you some now. The expected output is that the "Str" object in the outputted JSON should be empty, just a `{}`. If you duplicate the line that should be a no-op, it doesn't return true when checking if the fieldType is `typeof(String)`. This here:
```cs
if (fieldType == typeof(String))
{
	Compiler.EmitTypeBody(serializableType, "\"{}\"");
}
```

When duplicating the no-op it skips that and goes straight to the `else` statement and will output the fields of the String instead of an empty object.

**Comment by RogueMacro** [comment]
@bfiete After having to relaunch a few times it doesn't reproduce. Might have been local to a file or something. Will notify you if it happens again.

**Comment by bfiete** [comment]
Did you update to the latest nightly? It's possible I fixed a bug related to it yesterday...

**Comment by RogueMacro** [comment]
No, I did not, it just didn't want to come out after restarting the IDE.

**Comment by bfiete** [comment]
Hm, well, I _did_ still fix some bugs there yesterday so I guess just update and if you see it happen again (even once) then let me know here.

**Comment by RogueMacro** [comment]
Updated to latest nightly. Still here, don't know exactly what's causing it.

**Comment by bfiete** [comment]
Okay- can you step-by-step give instructions on how to see the error _if_ it occurs?

**Comment by RogueMacro** [comment]
First you copy the code like I said. The in Program.bf hit F12 on any `.ToJson()` method (There is one in `Main()`). You will see in the emitted code that the JSON in output.AppendF() changes.

**Comment by bfiete** [comment]
Okay. It would have been a little easier if you have done something like add an assert that would be thrown if the result is incorrect.

**Comment by RogueMacro** [comment]
Okay, I will remember that to next time. Were you able to reproduce?

**Comment by bfiete** [comment]
Yeah

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/cb877b1860e33b999ac7e8d252e7367cb3ec21c3
The `if (fieldType == typeof(String))` check was failing because the high 32 bits from typeof() were uninitialized. It worked if there happened to be a zero up there and otherwise failed.

**Comment by bfiete** [comment]
Also- thanks for the bug :-)

**Comment by RogueMacro** [comment]
Bug's still here, unfortunately :(

**Comment by bfiete** [comment]
Yeah

**Comment by bfiete** [comment]
Just making sure since there was confusion with the nightly builds not running. This _is_ fixed for you, right?

**Comment by RogueMacro** [comment]
Yes
