### ISSUE TITLE
Changes on Inactive Source Tabs of Secondary IDE Windows aren't seen on Window Close

### ISSUE THREAD

**Issue by bttelle** [beefytech/Beef#884]
When you use the `Close` button on Secondary IDE Windows that have changed but inactive source tabs, the changes aren't picked up and you won't be asked to save them.  This also corrupts some IDE state. There is a proposed fix for this in #883.

**Comment by bttelle** [comment]
Steps to reproduce:

1. Drag two source files to a new window (outside the main window)
2. Make changes on one file
3. Select that tab of the unchanged file to make it active (the tab with changes should be inactive)
4. Click the close button
5. You wont get any Save Changes dialog and the IDE will be in a bad state because there are filesystem changes without a source view.
.

**Comment by bfiete** [comment]
Fix applied at https://github.com/beefytech/Beef/commit/7e139f5d7c19b04459fa3c80c314bb709b3f638d
