### ISSUE TITLE
Clicking 'Dont Save' on Secondary IDE Window Close with changed source panels will sometimes assert

### ISSUE THREAD

**Issue by bttelle** [beefytech/Beef#885]
![mod-no-source-panel](https://user-images.githubusercontent.com/8131818/106545559-78e88400-64be-11eb-926a-f1ab5ffa2bb0.png)

There is a proposed fix for this in #883.

**Comment by bttelle** [comment]
Steps to reproduce:
1. Drag a source file (or several) to a new window (outside the main window)
2. Make changes on the file(s)
3. Click the Close button (X)
4. Hit "Dont Save" button.
5. Get the assert above (when run under the debugger).

**Comment by bfiete** [comment]
Fixed applied at https://github.com/beefytech/Beef/commit/7e139f5d7c19b04459fa3c80c314bb709b3f638d
