### ISSUE TITLE
Closing Secondary IDE Windows leads to unopenable standard panels

### ISSUE THREAD

**Issue by bttelle** [beefytech/Beef#886]
Steps to reproduce:

1. Open the IDE
2. Drag Workspace pane outside of the main window
3. Close this secondary window with the (x) button
4. Re-open the Workspace pane (notice the failed assert)

There is a proposed fix in #883.

**Comment by bfiete** [comment]
Fix applied at https://github.com/beefytech/Beef/commit/7e139f5d7c19b04459fa3c80c314bb709b3f638d
Good work.
