### ISSUE TITLE
[LINQ] Strange crashes related to ThenBy

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#888]
4d312c6

I have gotten the following errors in the debug IDE.

`mIsModuleMutating`
`generic is deleting`
`allowFail `

I believe if you open the IDE up on the above commit and just sort of play around with the code a little bit in the ThenBy enumerable + try and run test, you should see the `allowFail`. The others sort of come and go and I can't reproduce them consistently.

**Comment by xposure** [comment]
I narrowed down the crash to this block of code in `OrderByEnumerable`

```
			public SubSortEnumerable<decltype(default(sortedEnumerable).GetEnumerator()), TSource, TKey, TKey2, TKeyDlg2, TCompare2>
				ThenBy<TKey2, TKeyDlg2, TCompare2>(TKeyDlg2 key, TCompare2 compare)
				//where TEnum2 : concrete, IEnumerator<(TKey key, TSource value)>
				where TKeyDlg2 : delegate TKey2(TSource)
				where TCompare2 : delegate int(TKey2 lhs, TKey2 rhs)
			{
				return .(mSorted.GetEnumerator(), key, compare, false);
			}

			public SubSortEnumerable<decltype(default(sortedEnumerable).GetEnumerator()), TSource, TKey, TKey2, TKeyDlg2, delegate int(TKey2 lhs, TKey2 rhs)>
				ThenBy<TKey2, TKeyDlg2>(TKeyDlg2 key)
				where TKeyDlg2 : delegate TKey2(TSource)
				where int : operator TKey2 <=> TKey2
			{
				return .(mSorted.GetEnumerator(), key, OrderByComparison<TKey2>.Comparison, false);
			}
```

**Comment by bfiete** [comment]
I did find one issue, fixed here https://github.com/beefytech/Beef/commit/f999ada369a16aa18bc9f97bf1475568bfccf77d 
I'm not sure it could cause these other issues, but I couldn't get anything else to fail after that.
