### ISSUE TITLE
[Enhancement] Track active file in workspace hierarchy

### ISSUE THREAD

**Issue by jazzbre** [beefytech/Beef#891]
A setting that when enabled tracks the currently selected file in workspace hierarchy.

Thanks!

**Comment by bfiete** [comment]
Where is that feature in VS? I know it's there but I'm just not sure where.

**Comment by jazzbre** [comment]
Tools\Options\Projects And Solutions\Track Active Item in Solution Explorer

:D

**Comment by bfiete** [comment]
Ah- also there's a "Ctrl + [, S" shortcut for "SolutionExplorer.SyncWithActiveDocument". I thought there was a menu item somewhere for that too but I couldn't find one.

**Comment by bfiete** [comment]
Added at https://github.com/beefytech/Beef/commit/3f68473fe1cd6942eed417a2179238c17b8bfbd3
I don't use this in VS, so let me know if there are any behavioral issues.

**Comment by bfiete** [comment]
It's called "Sync with Workspace Panel" here. It's available via a permanent settings or the (copied) hotkey.

**Comment by jazzbre** [comment]
Thanks, works as intended! :D
