### ISSUE TITLE
[BUG]  Crash when using struct auto constructor

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#897]
Version 0.42.9 (Nightly 02/04/2021) built 2/4/2021 at 7:50 AM.

The issue only seems to occur when the struct is defined in namespace. When the struct is defined inside another type it does not crash.

Code to reproduce:
```
namespace Test
{
	struct Foo : this() { }
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/d63d65bd7168d2144eb45897635933c7e18a0c19
Thanks
