### ISSUE TITLE
[Bug] Crash when comptime emission output window is open

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#898]
Steps to reproduce:
1. Have an IComptimeTypeApply attribute that emits a method to that type
2. Hit F12 on a call to that method to open the code emission window
3. Go to `String.Free()` and comment out the `void* ptr` parameter. 

It will crash if the code emission window is open

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/eddbf7a98466ddc9468229aec180dd88c246fc7d
This didn't really have anything to do with comptime, it was a problem with how we dealt with removing required system type definitions, which would occur as you type out a `/*`, temporarily removing types like `System.StringView` which occurs later in the file.
