### ISSUE TITLE
[Bug] Destructor not called on delete

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#899]
In the following example I have a class named "Parent", an Extension for this class and a class that Inherits from "Parent".
All three have a String that needs to be freed.
In the Example the String "parentString" will leak because the destructor of "Parent" is not being called. Move "extensionString" from the extenision to "Parent" and the leak is gone.

```C#
class Parent
{
	String parentString = new String("Hello") ~ delete _;
}

extension Parent
{
	String extensionString = new String("World") ~ delete _;
}

class Child : Parent
{
	String childString = new String("!") ~ delete _;
}

class Program
{
	static int Main(String[] args)
	{
		Child c = new Child();

		delete c;

		return 0;
	}
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/9268e3b25df1ff09d82766c7da5b17be1eb3f70c
Thanks.
