### ISSUE TITLE
Dragging the last tab out of panel marked 'Permanent' still closes the panel

### ISSUE THREAD

**Issue by bttelle** [beefytech/Beef#903]
Steps to reproduce:

1. File\Preferences\ResetUI
2. Mark the Workspace containing panel 'Permanent'
3. Drag the Workspace tab to the source panel on the right

Notice the panel closes. It should remain open since it's permament.  Note that closing the Workspace panel using the X on the tab works as expected and the panel remains open (and empty.)

Fix proposed in #902.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/544c00f2c3e33e83a0f7f81f2b8b0f892f3671d2
