### ISSUE TITLE
[Bug] Crash when building in Release using LLVM toolchain

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#904]
When running a using the LLVM toolchain program it crashes before it even enters Main() and crashes when you try to switch over to the Call Stack window. It happens to any project using LLVM and System MSVCRT. This did not happen before.

Note: This seems to only happen in Release, so I might be wrong that it wasn't a case before

**Comment by bfiete** [comment]
Unable to reproduce.
Are you saying that even a simple Hello World does this for you?
Let's start with at least a crash dump, here. If you can attach a specific program that actually causes this then that would be helpful.

**Comment by RogueMacro** [comment]
I'm not able to reproduce now (Same IDE version)

**Comment by bfiete** [comment]
If you _do_ get this to happen again, then post the PDBs. I've had one case where I found a corrupted PDB generated by Visual Studio but then I lost it and couldn't reproduce it.
