### ISSUE TITLE
Comptime only functions and attributes strings included in binary

### ISSUE THREAD

**Issue by LoopyAshy** [beefytech/Beef#905]
As the title says, this seems random as even when the function is set to [Comptime(OnlyFromComptime = true, ConstEval=true)] it will still be included in the binary, this includes strings within the comp time only function which as you can imagine is not needed.

another issue is the attribute itself gets included in the binary which makes even less sense to me considering it isn't set to reflect and is never used by the program at runtime.

this is found within the binary even when compiled on highest optimisation:

![image](https://user-images.githubusercontent.com/42229301/107349228-e0569300-6abf-11eb-9de7-1568baa963eb.png)
![image](https://user-images.githubusercontent.com/42229301/107349470-2ad80f80-6ac0-11eb-8a3e-02f0495d478c.png)

this may not seem like much but it does indeed make the binary bigger for no reason, which seems wasteful.

the binary also includes strings pasted to comptime constants, which is the same issue as before.

Sorry if this is done for a specific reason, but it simply seems pointless to me.

**Comment by bfiete** [comment]
One note- you don't need the `if (Compiler.IsComptime)` there

**Comment by bfiete** [comment]
Then you say "the attribute itself gets included in the binary", what specifically do you mean?

**Comment by LoopyAshy** [comment]
I am sorry I worded that horrendously, I simply meant values stored in them which can never be retrieved after compile time are stored in binary and for example is when I used a string to handle compile time generation. regarding the if (Compiler.IsComptime) yeah I am aware I added that hoping it could help the compiler realise the string was impossible to get to at runtime lol, thank you though

**Comment by bfiete** [comment]
I've committed several fixes for this today, starting with https://github.com/beefytech/Beef/commit/9d79db063b6b4efa54eebcaac69f21ab3b796b22
