### ISSUE TITLE
int64 values incorrect when stored in attributes when compiled on 32 bit release mode

### ISSUE THREAD

**Issue by LoopyAshy** [beefytech/Beef#909]
The title says it all but here is an example:
![image](https://user-images.githubusercontent.com/42229301/107559373-eb024c80-6bd3-11eb-95ce-23d94788e4b8.png)

however when compiled in 64 bit you get the expected result:
![image](https://user-images.githubusercontent.com/42229301/107559562-2c92f780-6bd4-11eb-84e3-52ddd30f3190.png)

I realise this is int64 enums but this is exactly the same effect on plain int64s both signed and unsigned.

**Comment by bfiete** [comment]
Just a note for next time- when you post a code example it's easier if you post the text instead of an image so I can actually compile it.

**Comment by LoopyAshy** [comment]
Sorry about that; I just did that to show the output but I'll post text next time.

**Comment by bfiete** [comment]
This is the code I'm testing, that does not appear to cause the issue from what I can see.

```C#
enum TestEnum : int64
{
	A = 1,
	B = 2,
	C = 4,
	D = 8,
	E = 16
}

[AttributeUsage(.Class, .ReflectAttribute)]
struct TestItAttribute : Attribute
{
	public TestEnum mTE = 0;

	public this(TestEnum te)
	{
		mTE = te;
	}
}

[TestIt(.A | .B)]
class TestClass
{

}

public class TestProgram
{
	static int Main(String[] args)
	{
		var v = scope TestClass();
		Console.WriteLine(typeof(TestClass).GetCustomAttribute<TestItAttribute>().Value.mTE);
		Console.Read();

		return 0;
	}
}
```

**Comment by LoopyAshy** [comment]
are you compiling in 32 bit mode?, if yes: I am not sure whats going on lol

**Comment by LoopyAshy** [comment]
Interestingly when messing I noticed it is only doing this bug if compiled on release mode 32bit, on debug mode it gives expected result

**Comment by bfiete** [comment]
This seems to have been fixed.
