### ISSUE TITLE
[Minor Problem] Menu sometimes become out of screen 

### ISSUE THREAD

**Issue by HydrogenC** [beefytech/Beef#91]
The issue is about the menu displayed when clicking this button. 
![Note-2020-03-21-092729](https://user-images.githubusercontent.com/33123710/77216644-e6195200-6b56-11ea-9b42-336bdb120d69.png)
The menu is supposed to expand to the left (blue frame) but it actually expands to the right (red frame), so that part of the menu is out of screen. 
![Note-2020-03-21 093056](https://user-images.githubusercontent.com/33123710/77216669-0a752e80-6b57-11ea-89f4-780fd8bcfb95.png)

**Comment by bfiete** [comment]
Thanks. Fixed by https://github.com/beefytech/Beef/commit/9413d3ded49c35949822ec232936142f3b9fb305, will be in release 0.42.2.

**Comment by HydrogenC** [comment]
Thanks a lot for fixing it!
