### ISSUE TITLE
Error parsing global constants/variables used as default arguments without full namespace specified

### ISSUE THREAD

**Issue by taxmancw** [beefytech/Beef#910]
Repro:
In this example `Test.TEST_VALUE` will work, but `TEST_VALUE` will not.
![image](https://user-images.githubusercontent.com/34224458/107660463-6a7b4300-6cdc-11eb-8ba2-ed417d4f7730.png)

**Comment by bfiete** [comment]
Note- please post actual text for error cases instead of screenshots in the future.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/6e5845482509dde3d566514ae9f9e2edc3129c23
Should work in the current nightly build.
