### ISSUE TITLE
[Bug] Hard crash from derived generic classes

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#912]
If you go to ExamplePlugin/ExamplePlugin.bf and finish typing the generic in the class ExamplePlugin derives from:
```cs
public class ExamplePlugin : Program.ProgramPlugin<ExamplePlugi>
```
to
```cs
public class ExamplePlugin : Program.ProgramPlugin<ExamplePlugin>
```
It will crash.

[Project.zip](https://github.com/beefytech/Beef/files/5967089/Project.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/fda6c326c090062d925e37f2ce159f40459de501

I'm not sure what you're trying to do with things like
`public abstract class Plugin<T> : IPlugin where T : Plugin<T>, new, class`
There's no type that could possibly satisfy the constraint `T : Plugin<T>`...

**Comment by RogueMacro** [comment]
`public class ExamplePlugin : Plugin<ExamplePlugin>`

**Comment by bfiete** [comment]
Right. When I haven't seen CRTP for a while I keep forgetting that it actually does work.

**Comment by RogueMacro** [comment]
Yeah, I had to do it that way in order to export a method that returns a new instance of the derived plugin instead of the base plugin.

**Comment by bfiete** [comment]
Okay, NOW it is fixed https://github.com/beefytech/Beef/commit/a6e8436b2f61f7dadf1f66b0a24460a5cafc9393
Also added that pattern to my test cases - that's a good one.
