### ISSUE TITLE
PostBuild cmd executing before linking when PreBuild cmds are in use

### ISSUE THREAD

**Issue by EinBurgbauer** [beefytech/Beef#914]
another issue with post-build commands executing after  linking. Before, i only had postbuild cmds in my workspace and it worked. Now some of my projects use prebuild cmds and the postbuild cmd is now also executed before link together (admittedly after them, but before link)
```
29 modules built, 14 object files generated
Executing Command: CopyToDependents("$(ProjectDir)/dist/win64/SDL2.dll")
Executing Command: CopyToDependents("$(ProjectDir)/dist/win64/soloud.dll")
Executing Command: Execute("$(TargetPath PileGame).exe -packager")
Executing: <actual path>
INFO: Package shaders didn't change; took 2ms
INFO: Package content didn't change; took 122ms
Execution time: 0.22s
Executing: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\
```
should be reproducable by running Examples/Template of <https://github.com/EinBurgbauer/Pile>

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/b356e4735cc4289d9bb5063dab495e40e906cd31
