### ISSUE TITLE
[SDL lib] SDL_GetDisplayUsableBounds wrong linkname

### ISSUE THREAD

**Issue by andreakarasho** [beefytech/Beef#915]
https://github.com/beefytech/Beef/blob/a6e8436b2f61f7dadf1f66b0a24460a5cafc9393/BeefLibs/SDL2/src/SDL2.bf#L720

Should be 
```LinkName["SDL_GetDisplayUsableBounds"]```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/1d5bb1fade76cea0fe0091676c6ca3340274a5d7
