### ISSUE TITLE
IDE crash when using field destructor on field containing struct with no fields

### ISSUE THREAD

**Issue by russpowers** [beefytech/Beef#917]
I've been learning the language (looks great btw), and when I was playing around with field destructors, the IDE kept crashing on build. I isolated it to the below code. If you add any field to `Foo` it will work fine. Of course, it doesn't really make any sense to call a field destructor on a field that contains a struct with no fields, so I'm not sure if this is a particularly high priority 😄 

```cs
using System;

namespace HelloWorld
{
	struct Foo
	{
		public void Dispose()
		{
		}
	}

	class Bar
	{
		Foo f ~ _.Dispose();
	}

	class Program
	{
		static void Main()
		{
			Bar b = new Bar();
			delete b;
		}
	}
}
```

**Comment by bfiete** [comment]
Good find. Fixed at https://github.com/beefytech/Beef/commit/0bbb8398d213ceba5a0f617f50793601c3dacd08 (will be in the next nightly build)
