### ISSUE TITLE
struct inheriting from function crashes IDE

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#918]
Code bellow will crashes IDE

```csharp
	public struct Func<T> : function T() // <- typing () will crash IDE
	{
		function T() f;

		public T Invoke() => f();

		this(function T() f)
		{
			this.f = f;
		}

		public static implicit operator Func<T>(function T() f)
		{
			return Func<T>(f);
		}
	}
```

**Comment by bfiete** [comment]
I wasn't able to get anything to crash here. You sure you're able to get this to crash if you paste it into an empty project?

**Comment by M0n7y5** [comment]
That's weird ... I am gonna try to isolate this bug asap.

**Comment by M0n7y5** [comment]
I am no longer able to replicate that bug ... Looks like problem was something else. Closing this issues for now.
