### ISSUE TITLE
Infinite type generation with recursive generic declarations

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#919]
Title says it all ... 

Tested Beef IDE version: **Version 0.43.0 (Nightly 02/15/2021)**
Project files:

[BeefMachineWorkspace.zip](https://github.com/beefytech/Beef/files/5987696/BeefMachineWorkspace.zip)

**Comment by bfiete** [comment]
The root issue here is recursive generic declarations
```C#
IStateBuilder<NewStateT, TType, IStateBuilder<T, TType, TParent>> State<NewStateT>()
```
Which results in the creation of an infinite number of types.

This type of pattern will be very difficult to allow. In the meantime I will work on generating a proper error.

**Comment by M0n7y5** [comment]
Is there any workaround for this? 
For the context... I am trying to port this C# project:
https://github.com/Real-Serious-Games/Fluent-State-Machine

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/eb86c717f038c90318b3e85eb5376fca06d87763
Cases where the recursive types are used in methods now work (which is your case), but cases where they are used as field types will cause a compilation error.
