### ISSUE TITLE
Formatting failure

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#92]
When formatting this code:

```
class Controller
{
	private bool FActive;

	public this()
	{
	}

	public ~this()
	{
	}

	public bool Active
	{
		get { return FActive; }
		set { FActive = value; }
	}
}
```

It becomes like so:

```
class Controller
{
	private bool FActive;

	public this()
	{
	} public ~this()
	{
	}

	public bool Active
	{
		get { return FActive; }
		set { FActive = value; }
		}
}
```

The last bracket on the properties become indented and the destructor is on the wrong line.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/0facfb8c296e5c679c35ae6ba4e160f06409f2f9

**Comment by HydrogenC** [comment]
There's also some problem while formatting raw function pointers. 
`function void(void* item) myFunc;`
Becomes: 
`functionvoid(void* item) myFunc`
It deletes the space between function and void and the code can no longer compile.

**Comment by damianday** [comment]
@HydrogenC Just tested with git master and that case is already fixed.
