### ISSUE TITLE
[BUG] Typing delegate void Action<T crashes IDE

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#922]
When i type `delegate void Action<T` in System.Delegate.bf file IDE will crash.

**Version 0.43.0 (Nightly 02/15/2021)**

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/9163312712c479c0c202de6341c8c5ccb14b14bb
Typing that effectively removes a required type (System.Delegate) from the type system, which caused the issue. The compiler now survives that case.
