### ISSUE TITLE
[Bug] Crash when hovering over error (Very large int array)

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#925]
If you open this test project: [BugTesting.zip](https://github.com/beefytech/Beef/files/5998311/BugTesting.zip), then go to where the error is underlined in FontSourceSansPro.bf then hover your cursor over that parenthesis it will crash.

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/aa89d7d4969fc12fa9691ce23f135f8f1504e07a
And of course the correct syntax there is `public static uint8[?] SourceSansPro_Regular_ttf = .(`.

**Comment by RogueMacro** [comment]
@bfiete  What does the question mark do and why don't I need to use `new`?

**Comment by bfiete** [comment]
This is a sized array (valuetype, just a block of data) with an inferred size. Documented here: https://www.beeflang.org/docs/language-guide/datatypes/#arrays
