### ISSUE TITLE
[BUG] High CPU usage spikes when working with generics 

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#928]
I get high CPU usage when uing generic in my project. Not sure whats it causing 
[BeefMachineWorkspace.zip](https://github.com/beefytech/Beef/files/6004798/BeefMachineWorkspace.zip)

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/4c40028b33c5944c19851e3ca9c3e7010cafcf69
"accidentally quadradic" 
This is a case of O^2 time complexity relative to method chaining length, and you just happened to be the first to chain a method long enough to notice. Now it's back to linear time as expected. @xposure This would have also affected other chaining-style APIs such as Beef.Linq.

**Comment by bfiete** [comment]
Also I just pushed a new nightly build with that fix.
