### ISSUE TITLE
[BUG] Inspector popup shows incorrect values for float generic constants 

### ISSUE THREAD

**Issue by M0n7y5** [beefytech/Beef#929]
![image](https://user-images.githubusercontent.com/17201053/108428297-a1061000-723e-11eb-93fb-332b64d1d3b3.png)

Same behavior is for debugging

**Comment by M0n7y5** [comment]
Similar problem #930

**Comment by bfiete** [comment]
Same problem, actually. Fixed at https://github.com/beefytech/Beef/commit/8047bebfcacde76aaa911c8e50e316dc5e536df5
