### ISSUE TITLE
[BUG] IDE crashes when using fixed-size array in comptime function

### ISSUE THREAD

**Issue by aharabada** [beefytech/Beef#931]
Using a fixed-size array in a function with the Comptime-attribute will cause the IDE to crash while compiling. If the function also has the OnCompile-Attribute the IDE will crash immediately.

Code to reproduce:
```C#
struct MyStruct
{
	[Comptime, OnCompile(.TypeInit)]
	public static void Generate()
	{
		String[4] strs = .("Hello", "Bla", "123", "!!!");
	}
}
```

**Comment by aharabada** [comment]
I've tried a few more things and noticed that the IDE also crashes when using a tuple instead of an array. It also seems to be caused by the string literals.
`var tuple1 = ("X", "Y");` also causes a crash. Oddly enough `var tuple2 = (StringView(), "Y");` does not.

**Comment by bfiete** [comment]
Fixe at https://github.com/beefytech/Beef/commit/a5e0a5688b6e142ae7d50084a56d7d9d13be7ff9
