### ISSUE TITLE
[Bug] Mysterious crash

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#932]
This line crashes (GUIApplication.bf:77)
```cs
new Button(.(100, 200), .(180, 20), "CLICK!").OnClick(new () => Debug.WriteLine("TEST"));
```

(Crash dump inside)
[Project.zip](https://github.com/beefytech/Beef/files/6016522/Project.zip)

Note: I modified the SDL lib a bit to make it work, see #920

**Comment by RogueMacro** [comment]
Found the line causing the crash (Line 51 in `Widgets/Widget.bf` in AddChild()):
```cs
widget.Parent = this;
```

**Comment by bfiete** [comment]
Mysteriously fixed at https://github.com/beefytech/Beef/commit/59d4e258d5dd71a0cbcfd43cc223ef75fdb71f02
