### ISSUE TITLE
[Bug] DirectX failed call

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#933]
I don't know where this came from, but it was like my computer "refreshed" and the screens went black, then it came back on and poof, I got this crash dump:

[crash.zip](https://github.com/beefytech/Beef/files/6023774/crash.zip)

I don't know if this is something you can fix, but I'm putting it here anyway. Have no idea what happened.

It might have gone into sleep mode for a moment.

**Comment by Hiroko103** [comment]
I got a similar crash. (Version 0.43.0 (Nightly 02/26/2021))
I had an empty workspace/project open while browsing corlib (so not actively coding), when the screen went black twice and then crash.

I'm attaching the crashdump.
[20210227-directx.zip](https://github.com/beefytech/Beef/files/6054593/20210227-directx.zip)

**Comment by bfiete** [comment]
This longstanding issue has finally been fixed at e87bf5b0294c07b8906af932c071a79b647f686a
