### ISSUE TITLE
[Crash] IDE crash from invalid syntax

### ISSUE THREAD

**Issue by MoshiBar** [beefytech/Beef#934]
Nightly 2/22/2021
entering `[}]` inside an enum caused the IDE to crash
I couldn't reproduce the bug in isolation so i included the project
https://cdn.discordapp.com/attachments/543114067137527848/813980520182054912/Regex.zip

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/234aaa772ca2a6b06d82697c45be6cff3c040ea5
The issue was that the '}' closed off the enum declaration, and then the following enum cases were declared with the outer type (Program), and that caused the issue.
