### ISSUE TITLE
[Bug] build fails on Og+

### ISSUE THREAD

**Issue by MoshiBar** [beefytech/Beef#935]
Nightly 2/22/2021
Build fails with error when trying to builo on Og+:
```ERROR: Module 'Regex_Program' failed during codegen with: Failure during codegen of ?ParseRegex@Program@Regex@bf@@CAPEAV?$List@?AUStringView@System@bf@@@Collections@System@3@UStringView@63@0@Z: VRegAddr used without ForceMem```
project file:
https://cdn.discordapp.com/attachments/543114067137527848/814199392738607145/Regex.zip

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/fa8b9eca28d42d844a67204b4160f2652d076fc8
The other debugging issue you mentioned in Discord is fixed at https://github.com/beefytech/Beef/commit/d1d3af1cc07e6056a5d8e3004e6cf35fd5084711
