### ISSUE TITLE
[Bug] IDE crash when building an enum with a constant value

### ISSUE THREAD

**Issue by MoshiBar** [beefytech/Beef#936]
Nightly 2/24/2021
attempting to compile with an enum that has ToString called on it and contains a constant value will cause an IDE crash on any optimization setting other than Og+

This code demonstrates the crash
```
using System;
namespace Test2
{
    class Program
    {
        static void Main(){
            Console.WriteLine(TestEnum.Wild);
        }
        enum TestEnum{
            public const int infinity = -1;

            case Wild;
        }
    }
}
```

**Comment by bfiete** [comment]
Fixed at https://github.com/beefytech/Beef/commit/f3c17a671cbf72a44d3f7904062e1ec99948b3f6
