### ISSUE TITLE
[BUG] Crash when extending type with auto constructor

### ISSUE THREAD

**Issue by Fusioon** [beefytech/Beef#943]
Version 0.43.0 (Nightly 02/26/2021) built 2/26/2021 at 9:00 PM.

Code to reproduce: 
```
struct Foo : this(int count)
{ }

extension Foo
{ }
```

**Comment by Fusioon** [comment]
Crash is coming from this line: https://github.com/beefytech/Beef/blob/10e2a5653077476a4f6192525eeb6fe8448e3496/IDEHelper/Compiler/BfSystem.cpp#L3063
The `fieldDef->mFieldDeclaration` is null for some reason, just adding a null check before `fieldDef->mFieldDeclaration->mInitializer` fixes the issue and doesn't seem to have any side effects.

**Comment by bfiete** [comment]
Good fix. Implemented at https://github.com/beefytech/Beef/commit/f5a863d55a35ed85e99ff612305aafe3e14b3825
