### ISSUE TITLE
[Bug] Linker failure when Array1 used

### ISSUE THREAD

**Issue by Hiroko103** [beefytech/Beef#944]
**Version**: 0.43.0 (Nightly 02/26/2021)

For some reason, if I try to instantiate **Array1**, the linker will fail with the error below.
But I can successfully instantiate **Array2**.

Does this behaviour have a valid reason or is it a bug?

```
using System;

namespace test
{
	class Program
	{
		public static void Main(){
			// Doesn't compile
			// Results in fatal error LNK1169: one or more multiply defined symbols found
			//Array1<int> a = new Array1<int>();

			// Compiles successfully
			//Array2<int> b = new Array2<int>();
		}
	}
}
```

**Comment by bfiete** [comment]
Don't directly use that class. Use `int[]`

**Comment by Hiroko103** [comment]
Alright, thank you. I close the issue then.
