### ISSUE TITLE
Extensions build issue

### ISSUE THREAD

**Issue by MaddyThorson** [beefytech/Beef#945]
I have some extensions to the ImGui Beef API (https://github.com/RogueMacro/imgui-beef) in my project that won't compile in a specific case. ImGui Beef is installed in BeefLibs. [Workspace (zip)](https://github.com/beefytech/Beef/files/6056246/Repro.zip) - note that this repro project will crash if it successfully runs, that's fine, the issue is just in the building.

My extensions look like this...

```
using ImGui;
namespace ImGui
{
	extension ImGui
	{
		public extension Vec2
		{
			static public Vec2 operator+(Vec2 a, Vec2 b)
			{
				return .(a.x + b.x, a.y + b.y);
			}

			static public Vec2 operator-(Vec2 a, Vec2 b)
			{
				return .(a.x - b.x, a.y - b.y);
			}
		}

		static public bool BeginSplitter(char8* id, float percent, bool horizontal, float padding, bool enableFirst, bool enableSecond, WindowFlags flags)
		{
			PushID(id);

			// get bounds
			let p = GetCurrentWindow().DC.CursorPos;
			let s = GetContentRegionAvail();
			var rect = ImGui.Rect(p, p + s);
                        ...
```

This builds. But if I replace any instances of `ImGui.Rect` with simply `Rect` then it gets a linker error (no Beef compiler error). This is odd because I am able to remove the `ImGui.` preceding other members of Imgui (such as method calls).

**Comment by bfiete** [comment]
Hey Maddy!
Thanks for the bug. Fixed at https://github.com/beefytech/Beef/commit/c4b7cc58a1088b901b04844d680a5461d7e224a8 - the fix will be in the next nightly.

**Comment by MaddyThorson** [comment]
Here's another case of the same linker error on the latest nightly
[Repro.zip](https://github.com/beefytech/Beef/files/6098099/Repro.zip)
