### ISSUE TITLE
[Bug] Unresolved external symbol error from enum extension property

### ISSUE THREAD

**Issue by RogueMacro** [beefytech/Beef#946]
[Project.zip](https://github.com/beefytech/Beef/files/6057270/Project.zip)

The extension of KeyCode has a property called IsCharacter. It is not always giving me an unresolved external symbol error, but as the workspace is now, it does.

**Comment by bfiete** [comment]
Fixed at 95c6b1db98986afebc67b1e04b76565163d0892b
