### ISSUE TITLE
Option to add additional libpath

### ISSUE THREAD

**Issue by HydrogenC** [beefytech/Beef#95]
I want to link to a .lib file, but if I add it to "Linker Dependencies", it takes no effect. 
Thus, It would be good if there has a option called "Additional Libpath" in which I can pass more libpath to the linker. 
This would be a lot easier than editing the linker flags manually.

**Comment by bfiete** [comment]
Yeah- Linker Dependencies is just a list of files that, if modified, will cause relinking. You're right that it would be convenient to explicitly state lib paths that will be both date-checked and mixed into the linker flags. Also "Link Dependencies" should probably be renamed to something that make it clear it's just for date checking...

**Comment by HydrogenC** [comment]
Thanks.

**Comment by bfiete** [comment]
For the record- added in https://github.com/beefytech/Beef/commit/2f144ee19be55afbf56093191eef616381d7ca2a, will be in 0.42.2.
