### ISSUE TITLE
false Comptime error & Ide crash

### ISSUE THREAD

**Issue by EinScott** [beefytech/Beef#954]
I'm putting these two issues together because i used the same codebase to reproduce them. I've sent it to you via mail, the subject is "Beef issue #954 code". You also need Atma.Json. Open the workspace of necrocard to start.

Edit: i saw that the project will say its missing FastNoiseBeef, but it is unused and can be removed from the workspace as well as the one using statement in Game.bf

BUG 1

EDIT2: when running the game, it may crash with an access violation. That is another bug that has since popped up. Let me know if it happens here or if i need to reupload. It's this line `drawStartXOffset = -(hand.Count * (CardSpacing + Card.Size.X)) / 2;` in Stats.bf, which i've botched with
```
let spacing = CardSpacing;
let cardSize = Card.Size.X;
let negOffset = hand.Count * (spacing + cardSize) / 2;

drawStartXOffset = -negOffset;
```
Looks like a codegen issue, something stores like a 43 value somewhere and then uses it as a pointer.
EDIT2_END

random access violation in comptime
seems to occur when adding/removing variables from classes
steps to reproduce:
- open & debug and run (clean or reopen project if this is a second attempt)
go into Game.bf and add & remove a space somewhere to make it recompile the thing
- debug and run again (should work fine)
go into Menu.bf and uncomment line 62, where it says "bool sliderDragging"
- debug and run again
now it will error, saying that theres an access violation while comptiming a string.
as said previously, when i changed the comptime into multiple emits without the use of String.AppendF, it instead errored, saying "Invalid StringView"

both cleaning and reopening the project fix this.

EDIT3: alternative repro step: just uncomment some code in Game.bf's Render() method.

BUG 2

when doing
- clean
- clean beef
- clean
(each one as soon as possible)
i also get this error
i've never seen it crash because of this before, but i've seen it as a ghost error in the ide error list a few times.

FatalError: constLHS->mTypeCode == constRHS->mTypeCode
at BfIRValue BfIRBuilder::CreateSub(BfIRValue lhs, BfIRValue rhs) in BfIRBuilder.cpp 4197
  where lhs { mId=336, mFlags BfIRValue_Const }, rhs { mId=304, mFlags=BfIRValueFlags_Const }
at BfExprEvaluator.cpp 22075

source of the error in project: CardLayout.bf ln 11 "XDrawOffsetDelta - Card.Size.Y"
one of them is a const uint, the otherone is a const struct.

**Comment by bfiete** [comment]
#1 fixed at c0d6db082484b6157f7520912e3e58567f4ddde4
#2 fixed at 8280cdba56bde00f04278a155c63653a6b158d10
