### ISSUE TITLE
Extensions Build Issue (pt 2)

### ISSUE THREAD

**Issue by MaddyThorson** [beefytech/Beef#955]
I posted this in the previous, related issue (#945), but couldn't re-open it on my end. It's another case of the linker error on the latest nightly-
[Repro.zip](https://github.com/beefytech/Beef/files/6098109/Repro.zip)

**Comment by EinBurgbauer** [comment]
I've tried to look at this today, and while i can't be sure, this looks more like an issue with the binding. The function that the missing symbol is linked with "ImRect_ImRect", which it doesnt find. But the thing is that i couldn't find it either in the c bindings. Instead there is "ImRect_ImRect_Vec2", "-Vec4", "-Nil" and "_Float", so replacing them like this (ln 4318 `[LinkName("ImRect_ImRect_Float")]` and the other constructors) linked correctly for me. @RogueMacro probably knows more? I haven't really looked at the generator that much.
The extensions didn't really seem to pose a problem here-- or not anymore (i've just tested on the current nightly)

**Comment by EinBurgbauer** [comment]
The issue has been fixed in imgui_beef, this can be closed.
