### ISSUE TITLE
[Enhancement] Ability to use Math functions like Math.Log in consteval/comptime

### ISSUE THREAD

**Issue by EinBurgbauer** [beefytech/Beef#959]
As per this discussion https://discord.com/channels/670260150656827422/703658975014420480/819478832355868692

you can currently not constEval the extern Math functions like the following (for obvious reasons)
```
let e = [ConstEval]Math.Log(4);
```

Especially for the the Math functions this would be pretty nice to have though.

**Comment by bfiete** [comment]
They do work if you use them _within_ a const-evaluated method... they just don't directly work like this.

**Comment by EinBurgbauer** [comment]
I see, I kind of forgot about that case. Since the example is a very weird thing for an actual use case anyway i'll close this for now.
