### ISSUE TITLE
[Bug?] Access violation using the same enumerator twice

### ISSUE THREAD

**Issue by marsej** [beefytech/Beef#969]
My thoughts on this is that maybe it's not a bug but better error message could be nice.
`

			var fe = System.IO.Directory.Enumerate("*",.Files);
			for (var f in fe) {}
			for (var f in fe) {}

`

**Comment by RogueMacro** [comment]
You have to reset it between loops. After the first loop the enumerator is at the last index and can't continue until you tell it to start over. Just call enumerator.Reset()

**Comment by bfiete** [comment]
Yeah- it's all on the enumerator. Some enumerators are not resettable (that one isn't).
