### ISSUE TITLE
[Bug?] Something with returning .Err

### ISSUE THREAD

**Issue by marsej** [beefytech/Beef#980]
0.43.0 Win 10
After running this and entering some a-z character as input.eg 't',
the Console.WriteLine(r); produces "Err(InvalidChar(0))" but the ERROR was never printed. 
I think one would expect that if Parse fails, the code path to ERROR is taken.

```cs
			var str = scope String();
			Console.ReadLine(str);
			var r = int.Parse(str);
			if (r == .Err)
			{
				Console.WriteLine("ERROR");
				return;
			}
			Console.WriteLine(r);
			Console.WriteLine(str);

```

**Comment by bfiete** [comment]
You need `if (r case .Err)`. But, yes, `r == .Err` should produce an error since it's not a valid value.

**Comment by marsej** [comment]
Okay thanks I changed it to case.

**Comment by bfiete** [comment]
This `(r == .Err)` case has properly been producing an error for a while now.
