### ISSUE TITLE
Comptime attribute crash on compile

### ISSUE THREAD

**Issue by Moneyl** [beefytech/Beef#998]
Using the the latest nightly build. The code below causes a crash on compile. You also need to create an instance of `CrashStruct` for the crash to happen. Here's my crash dump:
[BeefCrashDump_ComptimeAttributeCrash.zip](https://github.com/beefytech/Beef/files/6328647/BeefCrashDump_ComptimeAttributeCrash.zip)

```cs
	[AttributeUsage(.All)]
	public struct ComptimeCrashAttribute : Attribute, IComptimeTypeApply
	{
		public this(StringView str)
		{
			
		}

		[Comptime]
		public void ApplyToType(Type type)
		{

		}     
	}

	[ComptimeCrash(
		"""
		.............
		""")]
	public struct CrashStruct
	{

	}
```

**Comment by bfiete** [comment]
Fixed at some point.
